CMakeLists.txt
cmake/HPX_GeneratePackage.cmake
cmake/templates/hpxcxx.in
python/scripts/hpxcxx

HPX should have a compiler wrapper to make things easier for users, similar to mpicc. This request was created to solve that need.

Create a compiler wrapper

---

hpx/runtime/components/server/wrapper_heap.hpp

This fixes one more lock which was being held while suspending

More held locks

---

hpx/runtime/agas/server/symbol_namespace.hpp
hpx/runtime/naming/name.hpp
src/runtime/agas/server/symbol_namespace_server.cpp
src/runtime/naming/name.cpp

Fixing symbolic namespace hang

---

docs/CMakeLists.txt
docs/hpx.idx
docs/manual/parallel_algorithms.qbk
hpx/include/parallel_is_partitioned.hpp
hpx/include/parallel_is_sorted.hpp
hpx/parallel/algorithm.hpp
hpx/parallel/algorithms/is_partitioned.hpp
hpx/parallel/algorithms/is_sorted.hpp
hpx/parallel/algorithms/search.hpp
tests/unit/parallel/CMakeLists.txt
tests/unit/parallel/is_partitioned.cpp
tests/unit/parallel/is_sorted.cpp
tests/unit/parallel/is_sorted_until.cpp

Implemented the is_sorted, is_sorted_until and is_partitioned algorithms. 
I also fixed the formatting I had messed up on search.hpp.

Is_sorted, Is_sorted_until and Is_partitioned Algorithms

---

cmake/GitExternal.cmake
cmake/SubProject.cmake

These files have been relicensed with permission under the Boost license
which has been added accordingly.

Add GitExternal and SubProject cmake scripts from eyescale/cmake repo

---

hpx/lcos/future.hpp
hpx/lcos/local/detail/invoke_when_ready.hpp
hpx/runtime/actions/continuation.hpp
hpx/runtime/agas/request.hpp
hpx/runtime/applier/apply.hpp
hpx/runtime/components/client_base.hpp
hpx/runtime/parcelset/parcel.hpp
hpx/traits/serialize_as_future.hpp
hpx/util/bind.hpp
hpx/util/bind_action.hpp
hpx/util/detail/function_template.hpp
hpx/util/detail/unique_function_template.hpp
hpx/util/detail/vtable/serializable_vtable.hpp
hpx/util/function.hpp
hpx/util/functional/colocated_helpers.hpp
hpx/util/tuple.hpp

This fixes the action move test count problems introduced recently

Fixing action move tests

---

docs/hpx.qbk
docs/manual/parallel_algorithms.qbk
hpx/error.hpp
hpx/include/parallel_task_block.hpp
hpx/parallel/task_block.hpp
tests/unit/parallel/CMakeLists.txt
tests/unit/parallel/task_block.cpp

see #1458: Update parallel::task_region with N4411

Consolidated task_region with N4411

---

examples/quickstart/CMakeLists.txt
examples/quickstart/latch_local.cpp
examples/quickstart/latch_remote.cpp
hpx/components/containers/unordered/unordered_map.hpp
hpx/components/containers/vector/vector.hpp
hpx/hpx_fwd.hpp
hpx/include/lcos.hpp
hpx/include/local_lcos.hpp
hpx/lcos/latch.hpp
hpx/lcos/local/latch.hpp
hpx/lcos/server/latch.hpp
hpx/runtime/components/client_base.hpp
src/lcos/barrier.cpp
src/lcos/latch.cpp
src/runtime/components/component_type.cpp
src/util/runtime_configuration.cpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/latch_local.cpp
tests/unit/lcos/latch_remote.cpp

This is a first step towards resolving #1457

Adding hpx::lcos::latch and hpx::lcos::local::latch

---

hpx/lcos/local/condition_variable.hpp
hpx/util/register_locks.hpp
src/util/register_locks.cpp
tests/regressions/lcos/CMakeLists.txt
tests/regressions/lcos/ignore_while_locked_1485.cpp

Introduced default (main) template implementation for ignore_while_checking

---

hpx/runtime.hpp
hpx/runtime/components/runtime_support.hpp
hpx/runtime/components/server/runtime_support.hpp
hpx/runtime/components/stubs/runtime_support.hpp
src/pre_main.cpp
src/runtime/components/server/runtime_support_server.cpp
src/runtime/components/stubs/runtime_support_stubs.cpp
src/runtime_impl.cpp

Making sure that wrong command line options cause non-zero exit code

---

hpx/runtime/serialization/multi_array.hpp
tests/unit/serialization/serialization_array.cpp

Added support for boost.multi_array serialization

---

hpx/config/emulate_deleted.hpp
hpx/lcos/local/mutex.hpp
hpx/lcos/local/once.hpp
hpx/lcos/local/spinlock.hpp
hpx/lcos/local/spinlock_no_backoff.hpp
hpx/lcos/local/spinlock_pool.hpp
hpx/util/spinlock.hpp
hpx/util/spinlock_pool.hpp
tests/performance/local/spinlock_overhead1.cpp
tests/performance/local/spinlock_overhead2.cpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/fail_compile_mutex_move.cpp
tests/unit/lcos/fail_compile_spinlock_move.cpp
tests/unit/lcos/fail_compile_spinlock_no_backoff_move.cpp

Make sure sync primitives are not copyable nor movable

---

hpx/lcos/local/dataflow.hpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/local_dataflow_executor.cpp

This fixes one issue as listed in #1544

Integrate executors with dataflow

---

hpx/util/plugin/detail/dll_dlopen.hpp
hpx/version.hpp
src/util/find_prefix.cpp
src/util/init_ini_data.cpp
src/version.cpp

Added support for dynamically linked mach-o libraries

Dylib support

---

src/runtime/agas/addressing_service.cpp
tests/regressions/agas/CMakeLists.txt
tests/regressions/agas/duplicate_id_registration_1596.cpp

Duplicate binding of global ids should fail

---

hpx/runtime/parcelset/parcelport_impl.hpp
hpx/util/connection_cache.hpp
src/runtime/naming/name.cpp

This fixes the heartbeat example.

Improved the reliability of connecting/disconnecting localities

---

cmake/HPX_AddConfigTest.cmake
cmake/toolchains/XeonPhi.cmake

Fixing RDTSC on Xeon/Phi

---

tests/regressions/util/CMakeLists.txt
tests/regressions/util/configuration_1572.cpp

This test was left un-pushed while fixing #1572

Adding missing test for #1572

---

docs/manual/commandline.qbk
hpx/util/batch_environment.hpp
src/util/batch_environment.cpp
src/util/command_line_handling.cpp
src/util/parse_command_line.cpp

This is a useful debug option to test things under batch systems

Add command line option to ignore batch environment

---

CMakeLists.txt
cmake/HPX_AddConfigTest.cmake
cmake/templates/HPXConfig.cmake.in

This fixes build issues. I have not yet looked carefully at install rules, but these changes can be safely merged.

Fixing 1617

---

src/runtime/agas/addressing_service.cpp

Fixed performance counters related to AGAS cache timings

---

hpx/parallel/execution_policy.hpp

- inhibit generic  execution_policy  from being instantiated by 'shim' execution policies

Working on 1544: More executor changes

---

CMakeLists.txt
docs/manual/scheduling_policies.qbk
hpx/hpx_fwd.hpp
hpx/parallel/executors.hpp
hpx/parallel/executors/detail/thread_executor.hpp
hpx/parallel/executors/executor_traits.hpp
hpx/parallel/executors/this_thread_executors.hpp
hpx/parallel/executors/thread_pool_executors.hpp
hpx/runtime/threads/detail/scheduling_loop.hpp
hpx/runtime/threads/detail/thread_num_tss.hpp
hpx/runtime/threads/detail/thread_pool.hpp
hpx/runtime/threads/executors/manage_thread_executor.hpp
hpx/runtime/threads/executors/this_thread_executors.hpp
hpx/runtime/threads/executors/thread_pool_executors.hpp
hpx/runtime/threads/policies/schedulers.hpp
hpx/runtime/threads/policies/static_queue_scheduler.hpp
src/hpx_init.cpp
src/runtime/threads/detail/thread_num_tss.cpp
src/runtime/threads/detail/thread_pool.cpp
src/runtime/threads/executors/this_thread_executors.cpp
src/runtime/threads/executors/thread_pool_executors.cpp
src/runtime/threads/threadmanager.cpp
src/runtime_impl.cpp
src/util/parse_command_line.cpp
tests/unit/parallel/executors/CMakeLists.txt
tests/unit/parallel/executors/this_thread_executors.cpp
tests/unit/parallel/executors/thread_pool_executors.cpp

Second attempt to merge these changes

This thread executors

---

examples/quickstart/CMakeLists.txt
examples/quickstart/shared_mutex.cpp
hpx/lcos/local/counting_semaphore.hpp
hpx/lcos/local/detail/counting_semaphore.hpp
hpx/lcos/local/shared_mutex.hpp
hpx/runtime/actions/action_invoke_no_more_than.hpp
hpx/runtime/threads/detail/thread_group.hpp
tests/regressions/lcos/CMakeLists.txt
tests/regressions/lcos/shared_mutex_1702.cpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/counting_semaphore.cpp
tests/unit/lcos/shared_mutex/CMakeLists.txt
tests/unit/lcos/shared_mutex/shared_mutex1.cpp
tests/unit/lcos/shared_mutex/shared_mutex2.cpp
tests/unit/lcos/shared_mutex/shared_mutex_locking_thread.hpp
tests/unit/lcos/shared_mutex/thread_group.hpp

- adding tests
- adding quickstart example

Fixing shared_mutes

---

src/runtime/threads/policies/affinity_data.cpp

Command line option --hpx:cores does not work as expected

---

CMakeLists.txt

Moving library detection to be executed after feature tests

---

README.rst
docs/manual/build_system/recipe_mic.qbk
docs/manual/build_system/using_hpx_cmake.qbk
examples/1d_hydro/1d_hydro_upwind.cpp
hpx/util/coroutine/detail/default_context_impl.hpp

changing misspellings

---

hpx/runtime/serialization/vector.hpp

...which was causing compiler warnings.

dropped superfluous typedef

---

hpx/parallel/executors.hpp
hpx/parallel/executors/timed_executor_traits.hpp
hpx/parallel/executors/timed_thread_executor_traits.hpp
hpx/runtime/threads/thread_executor.hpp
tests/unit/parallel/executors/CMakeLists.txt
tests/unit/parallel/executors/timed_this_thread_executors.cpp
tests/unit/parallel/executors/timed_thread_pool_executors.cpp

This adds a timed_executor_traits specialization for threads::executors

Timed executor traits for thread-executors

---

hpx/performance_counters/server/elapsed_time_counter.hpp
src/performance_counters/server/elapsed_time_counter.cpp
tests/regressions/performance_counters/CMakeLists.txt
tests/regressions/performance_counters/uptime_1737.cpp

This fixes #1737: Uptime problems

Making sure that uptime counter throws exception on any attempt to be reset

---

src/runtime/actions/invocation_count_registry.cpp
tests/regressions/performance_counters/CMakeLists.txt
tests/regressions/performance_counters/discover_counters_1787.cpp

This fixes #1787: discover_counter_types not working

Fixing discover_counter_types API function

---

docs/manual/build_system/prerequisites.qbk
hpx/parallel/executors/executor_information_traits.hpp
hpx/runtime/serialization/serialization_fwd.hpp
hpx/traits/get_remote_result.hpp

This PR ticks of the remaining points of #1723.

Fixing #1723

---

hpx/runtime/actions/continuation.hpp
hpx/util/bind.hpp
hpx/util/unwrapped.hpp

...that GCC was complaining about.

drop superfluous typedefs

---

hpx/util/coroutine/detail/tss.hpp
src/runtime/agas/addressing_service.cpp

This fixes the currently failing intel13 builder.

Fix intel13

---

hpx/runtime/components/client_base.hpp
tests/unit/agas/find_clients_from_prefix.cpp
tests/unit/agas/find_ids_from_prefix.cpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/client_then.cpp

Fixing client_base<>::then

---

cmake/templates/HPXConfig.cmake.in

Don't pollute CMAKE_CXX_FLAGS through find_package()

---

CMakeLists.txt
examples/CMakeLists.txt

Fixing 1871

---

docs/manual/build_system/cmake_toolchains.qbk
docs/manual/build_system/cmake_variables.qbk
docs/manual/parallel_algorithms.qbk
hpx/hpx_init.hpp
hpx/hpx_start.hpp
hpx/lcos/wait_all.hpp
hpx/lcos/wait_any.hpp
hpx/lcos/when_all.hpp
hpx/lcos/when_any.hpp
hpx/parallel/algorithms/adjacent_difference.hpp
hpx/parallel/algorithms/inner_product.hpp
hpx/parallel/execution_policy.hpp
hpx/parallel/executors/parallel_executor.hpp
hpx/parallel/executors/service_executors.hpp
hpx/runtime/get_os_thread_count.hpp
hpx/runtime/launch_policy.hpp

Simple documentation refactoring to clean up the warnings generated.

Documentation refactoring based off #1868 

---

hpx/parallel/algorithm.hpp

In reference to #1876 , but commit log is cleaned up.

Add missing parallel algorithm header

---

hpx/runtime/threads/detail/scheduling_loop.hpp
hpx/runtime/threads/detail/thread_pool.hpp
src/runtime/threads/detail/thread_pool.cpp

- also fly-by changes to preprocessor constant usage
@pagrubel Please verify whether this fixes your issue reported by #1859

Fixed resetting performance counters related to idle-rate, etc.

---

hpx/parallel/algorithms/sort.hpp

@biddisco Please have a look (if you the time) and comment.

Changing parallel::sort to return the last iterator as proposed by N4560

---

hpx/plugins/parcelport/mpi/mpi_environment.hpp
hpx/util/batch_environment.hpp
hpx/util/batch_environments/pbs_environment.hpp
plugins/parcelport/mpi/mpi_environment.cpp
src/util/batch_environment.cpp
src/util/batch_environments/pbs_environment.cpp
src/util/command_line_handling.cpp
tests/unit/util/parse_slurm_nodelist.cpp

Fix mpirun with pbs

---

hpx/runtime/threads/policies/noop_topology.hpp
src/runtime/threads/policies/affinity_data.cpp

Making sure code compiles if HPX_WITH_HWLOC=Off

---

CMakeLists.txt
hpx/config.hpp
hpx/util/register_locks.hpp
src/CMakeLists.txt
src/runtime.cpp
src/util/register_locks.cpp

This fixes some memory leaks and a ODR violation reported by clang's address sanitizer

Address sanitizer fixes

---

hpx/runtime/serialization/array.hpp
tests/unit/serialization/serialization_array.cpp

- also adding corresponding test
This fixes #1923

Fixing serialization of std::array

---

circle.yml

Reverts STEllAR-GROUP/hpx#1927

Revert "Using ninja for circle-ci builds"

---

src/performance_counters/server/statistics_counter.cpp

Making sure interval timer is started for aggregating performance counters

---

hpx/parallel/algorithms/rotate.hpp
hpx/parallel/container_algorithms/remove_copy.hpp
hpx/parallel/container_algorithms/replace.hpp
hpx/parallel/container_algorithms/reverse.hpp
hpx/parallel/container_algorithms/rotate.hpp
tests/unit/parallel/container_algorithms/remove_copy_if_range.cpp
tests/unit/parallel/container_algorithms/remove_copy_range.cpp
tests/unit/parallel/container_algorithms/replace_copy_if_range.cpp
tests/unit/parallel/container_algorithms/replace_copy_range.cpp
tests/unit/parallel/container_algorithms/replace_if_range.cpp
tests/unit/parallel/container_algorithms/replace_range.cpp
tests/unit/parallel/container_algorithms/reverse_copy_range.cpp
tests/unit/parallel/container_algorithms/reverse_range.cpp
tests/unit/parallel/container_algorithms/rotate_copy_range.cpp
tests/unit/parallel/container_algorithms/rotate_range.cpp

This fixes compilation problems caused by the container algorithm tests on some platforms

Fixed container algorithm tests

---

hpx/runtime/components/server/console_error_sink_singleton.hpp
hpx/runtime/components/server/runtime_support.hpp
hpx/runtime/threads/threadmanager_impl.hpp
hpx/runtime/threads/topology.hpp
hpx/util/connection_cache.hpp
hpx/util/io_service_pool.hpp
hpx/util/one_size_heap_list.hpp
hpx/util/plugin/detail/dll_dlopen.hpp
hpx/util/thread_mapper.hpp
hpx/util/try_lock_wrapper.hpp
src/runtime/agas/big_boot_barrier.cpp
src/runtime/components/server/console_error_sink_singleton.cpp
src/runtime/parcelset/parcelhandler.cpp
src/runtime_impl.cpp
src/util/io_service_pool.cpp
tests/regressions/threads/block_os_threads_1036.cpp
tests/unit/parallel/executors/service_executors.cpp

- replace with separate headers files
- flyby changes adding missing #includes

Removing use of unified Boost.Thread header

---

hpx/lcos/base_lco.hpp
hpx/lcos/detail/async_implementations.hpp
hpx/lcos/detail/future_data.hpp
hpx/lcos/packaged_action.hpp
hpx/lcos/promise.hpp
hpx/runtime/applier/apply_callback.hpp
src/runtime/agas/stubs/component_namespace_stubs.cpp
src/runtime/agas/stubs/locality_namespace_stubs.cpp
src/runtime/agas/stubs/primary_namespace_stubs.cpp
src/runtime/agas/stubs/symbol_namespace_stubs.cpp
src/runtime/components/stubs/runtime_support_stubs.cpp
tests/regressions/actions/CMakeLists.txt
tests/regressions/actions/async_deferred_1523.cpp

- refactored lcos::promise and lcos::packaged_action
- added test
This fixes #1523

Fix remote async with deferred launch policy

---

hpx/runtime/threads/detail/scheduling_loop.hpp
hpx/runtime/threads/executors/thread_pool_executors.hpp
hpx/runtime/threads/resource_manager.hpp
src/runtime/threads/detail/thread_pool.cpp
src/runtime/threads/executors/this_thread_executors.cpp
src/runtime/threads/executors/thread_pool_executors.cpp
src/runtime/threads/resource_manager.cpp
tests/unit/threads/CMakeLists.txt
tests/unit/threads/resource_manager.cpp

- adding missing code
- adding test
- thread_pool_executors now report real number of assigned cores

Fixing problems in over-subscription management in the resource manager

---

hpx/components/papi/server/papi.hpp
src/components/papi_counters/server/papi.cpp
tests/regressions/performance_counters/CMakeLists.txt
tests/regressions/performance_counters/papi_counters_basic_functions.cpp

Papi fixes

---

tests/unit/parallel/algorithms/inclusive_scan.cpp
tests/unit/parallel/algorithms/inclusive_scan_tests.hpp
tests/unit/parallel/algorithms/sort.cpp
tests/unit/parallel/algorithms/sort_by_key.cpp

This has not passed CircleCi tests yet, but I'd like to merge it to master as soon as it does so that I can start collecting timings of sort/scan tests as soon as possible - to give a few baseline points on a timing graph before I modify the parallel sort algorithm, and/or possibly the scan implementation.

Fixing 1965

---

README.rst

Spotted a spelling mistake -
`regularily` > `regularly`

Fixes typo in README.rst

---

hpx/exception.hpp
src/exception.cpp

Fixing 2000

---

cmake/HPX_GeneratePackage.cmake
cmake/templates/hpx_component.pc.in
cmake/templates/hpx_component_debug.pc.in
docs/manual/build_system/using_hpx_pkgconfig.qbk
examples/hello_world_component/hello.sh
examples/hello_world_component/hello_world_client.cpp
examples/hello_world_component/hello_world_component.cpp
examples/hello_world_component/hello_world_component.hpp

- also: fix documentation (remove stubs, remove mentioning of ini files)
- this fixes #2011 and #2009

Fixing compilation issues with external example

---

docs/manual/build_system/prerequisites.qbk
hpx/runtime/components/pinned_ptr.hpp
hpx/runtime/parcelset/parcelport.hpp
hpx/runtime/serialization/detail/pointer.hpp
src/runtime/agas/addressing_service.cpp

Cleanup after the removal of support for Intel 13

Intel13 removal

---

hpx/runtime/naming/name.hpp
src/runtime/naming/name.cpp
src/runtime/serialization/output_archive.cpp
tests/unit/agas/split_credit.cpp

- added locking while splitting credit
- moved set_credit_split_mask_for_gid to proper spot
- extended test

Attempt to narrow down split_credit problem

---

src/util/command_line_handling.cpp
src/util/runtime_configuration.cpp
tests/unit/component/CMakeLists.txt
tests/unit/component/launch_process.cpp

- re-enable launch_process test

Fix process launching/connecting back

---

docs/manual/build_system/howto_win32.qbk
docs/manual/build_system/recipe_mic.qbk
docs/manual/build_system/recipe_osx.qbk
docs/tutorial/examples.qbk
docs/tutorial/introduction.qbk

I fixed some spelling mistakes found while reading the documentation.

Fixed some typos in docs

---

docs/hpx.idx
docs/manual/parallel_algorithms.qbk
hpx/parallel/algorithms/for_loop.hpp
tests/unit/parallel/algorithms/CMakeLists.txt
tests/unit/parallel/algorithms/for_loop_n.cpp
tests/unit/parallel/algorithms/for_loop_n_strided.cpp

  Adding missing for_loop algorithms

---

cmake/HPX_AddLibrary.cmake
examples/accumulators/CMakeLists.txt
examples/accumulators/server/template_accumulator.hpp
examples/accumulators/template_accumulator.cpp
examples/accumulators/template_accumulator.hpp
examples/accumulators/template_accumulator_client.cpp

Adding example demonstrating template components 

---

hpx/plugins/parcel/coalescing_message_handler.hpp
hpx/runtime/parcelset/policies/message_handler.hpp
plugins/parcel/coalescing/coalescing_message_handler.cpp
src/runtime/parcelset/parcelhandler.cpp

@justwagle Please integrate this with your branch replacing the deadline timer for parcel-coalescing.

Adding flush-mode to message handler flush

---

CMakeLists.txt

Updating the APEX version from 0.1 to 0.5-rc0.

Updating APEX version for testing.

---

hpx/util/detail/basic_function.hpp

- this solves a significant performance regression

Fix storage size for util::function<>

---

src/pre_main.cpp
src/runtime/parcelset/parcelhandler.cpp

Making sure that a missing parcel_coalescing module does not cause startup exceptions

---

hpx/parallel/algorithms/reduce_by_key.hpp
tests/unit/parallel/algorithms/reduce_by_key.cpp

In the process of integrating the reduce_by_key with an external library, I found more problems which are now fixed.

Fixing 2119

---

examples/1d_stencil/1d_stencil_4_repart.cpp

… from Nick Chaimov
This version of 1d_stencil_4_repart allows the tuning to use any selected performance counter

Added repartition version of 1d stencil that uses any performance counter

---

tools/inspect/deprecated_include_check.cpp

Add deprecated #include check for hpx_fwd.hpp

---

src/util/command_line_handling.cpp

Changing default bind mode to balanced

---

examples/quickstart/CMakeLists.txt
examples/quickstart/receive_buffer.cpp
tests/regressions/lcos/CMakeLists.txt
tests/regressions/lcos/shared_future_then_2166.cpp

- flyby: adding test verifying shared_future::then() works properly
This fixes #2166

Adding new example demonstrating receive_buffer

---

hpx/runtime/serialization/detail/polymorphic_id_factory.hpp
hpx/runtime/serialization/detail/polymorphic_intrusive_factory.hpp
src/runtime/agas/big_boot_barrier.cpp
src/runtime/serialization/detail/polymorphic_id_factory.cpp

- flyby: improve error handling/reporting

Moving more code into source files

---

src/runtime/components/server/runtime_support_server.cpp

Fixed typos

---

cmake/tests/cxx11_function_template_default_args.cpp
hpx/parallel/algorithms/adjacent_find.hpp
hpx/parallel/algorithms/copy.hpp
hpx/parallel/algorithms/equal.hpp
hpx/parallel/algorithms/find.hpp
hpx/parallel/algorithms/for_each.hpp
hpx/parallel/algorithms/includes.hpp
hpx/parallel/algorithms/is_sorted.hpp
hpx/parallel/algorithms/lexicographical_compare.hpp
hpx/parallel/algorithms/minmax.hpp
hpx/parallel/algorithms/mismatch.hpp
hpx/parallel/algorithms/search.hpp
hpx/parallel/algorithms/set_difference.hpp
hpx/parallel/algorithms/set_intersection.hpp
hpx/parallel/algorithms/set_symmetric_difference.hpp
hpx/parallel/algorithms/set_union.hpp
hpx/parallel/algorithms/sort.hpp
hpx/parallel/algorithms/sort_by_key.hpp
hpx/parallel/algorithms/transform.hpp
hpx/parallel/container_algorithms/minmax.hpp
hpx/parallel/container_algorithms/sort.hpp
hpx/parallel/container_algorithms/transform.hpp

Use defaulted template/function arguments to reduce the number of overloads.

Simplify algorithm overloads

---

src/runtime.cpp
src/version.cpp
tests/regressions/parallel/CMakeLists.txt
tests/regressions/parallel/static_chunker_2282.cpp

Throwing exceptions if the runtime is not up and running

---

hpx/util/command_line_handling.hpp
src/hpx_init.cpp
src/runtime/threads/policies/affinity_data.cpp
src/util/command_line_handling.cpp

This fixes #2313 addressing describes a long standing problem in our command line handling

Fixing command line handling for default bind mode

---

hpx/runtime/threads/policies/hwloc_topology.hpp
hpx/runtime/threads/policies/parse_affinity_options.hpp
hpx/runtime/threads/topology.hpp
src/hpx_init.cpp
src/runtime/threads/policies/affinity_data.cpp
src/runtime/threads/policies/parse_affinity_options.cpp
tests/unit/util/parse_affinity_options.cpp

Improve handling of --hpx:bind=<bind-spec>

---

CMakeLists.txt

Updating APEX version to the release branch (for testing), and adding OTF2 support.

Updating APEX support to include OTF2

---

hpx/runtime/serialization/bitset.hpp
hpx/runtime/serialization/dynamic_bitset.hpp
hpx/runtime/threads/cpu_mask.hpp
src/compute/host/get_host_targets.cpp

This fixes #2352 
@pagrubel please verify if this fixes you issue.

Adding serialization for mask_type if CPU_COUNT > 64

---

hpx/hpx_fwd.hpp
hpx/runtime/config_entry.hpp
hpx/runtime/parcelset/parcelport_impl.hpp
hpx/runtime/threads/detail/scheduling_loop.hpp
hpx/runtime_fwd.hpp
hpx/util/ini.hpp
plugins/parcel/coalescing/coalescing_message_handler.cpp
src/exception.cpp
src/hpx_init.cpp
src/hpx_main.cpp
src/hpx_user_main.cpp
src/hpx_user_main_argc_argv.cpp
src/runtime.cpp
src/runtime/parcelset/parcelhandler.cpp
src/runtime/threads/policies/affinity_data.cpp
src/runtime_impl.cpp
src/util/ini.cpp
src/util/query_counters.cpp
src/util/register_locks.cpp
tests/unit/util/CMakeLists.txt
tests/unit/util/config_entry.cpp

- made key/value registry thread safe
- renamed the header file declaring the API functions
- add test

Adding set_config_entry

---

hpx/hpx_fwd.hpp
hpx/plugins/parcel/coalescing_message_handler.hpp
hpx/runtime/config_entry.hpp
hpx/runtime/parcelset/parcelport_impl.hpp
hpx/runtime/threads/detail/scheduling_loop.hpp
hpx/runtime_fwd.hpp
hpx/util/ini.hpp
plugins/parcel/coalescing/coalescing_message_handler.cpp
src/exception.cpp
src/hpx_init.cpp
src/hpx_main.cpp
src/hpx_user_main.cpp
src/hpx_user_main_argc_argv.cpp
src/runtime.cpp
src/runtime/parcelset/parcelhandler.cpp
src/runtime/threads/policies/affinity_data.cpp
src/runtime_impl.cpp
src/util/ini.cpp
src/util/query_counters.cpp
src/util/register_locks.cpp
tests/unit/util/CMakeLists.txt
tests/unit/util/config_entry.cpp

- made key/value registry thread safe
- renamed the header file declaring the API functions
- add test

Adding API functions set_config_entry_callback 

---

CMakeLists.txt
cmake/HPX_SetupLibFlatArray.cmake
hpx/parallel/traits/detail/libflatarray/fake_accessor.hpp
hpx/parallel/traits/detail/libflatarray/vector_pack_alignment_size.hpp
hpx/parallel/traits/detail/libflatarray/vector_pack_count_bits.hpp
hpx/parallel/traits/detail/libflatarray/vector_pack_load_store.hpp
hpx/parallel/traits/detail/libflatarray/vector_pack_type.hpp
hpx/parallel/traits/vector_pack_alignment_size.hpp
hpx/parallel/traits/vector_pack_count_bits.hpp
hpx/parallel/traits/vector_pack_load_store.hpp
hpx/parallel/traits/vector_pack_type.hpp

Untested as current state of datapar_zip_iterator branch doesn't compile for me.

add LibFlatArray-based backend for datapar

---

hpx/lcos/local/recursive_mutex.hpp

Fixing lock registration for recursive mutex

---

CMakeLists.txt
hpx/parallel/algorithms/copy.hpp
hpx/parallel/algorithms/for_each.hpp
hpx/parallel/algorithms/minmax.hpp
hpx/parallel/algorithms/partition.hpp
hpx/parallel/algorithms/remove_copy.hpp
hpx/parallel/algorithms/replace.hpp
hpx/parallel/algorithms/sort.hpp
hpx/parallel/algorithms/transform.hpp
hpx/parallel/container_algorithms/copy.hpp
hpx/parallel/container_algorithms/for_each.hpp
hpx/parallel/container_algorithms/minmax.hpp
hpx/parallel/container_algorithms/remove_copy.hpp
hpx/parallel/container_algorithms/replace.hpp
hpx/parallel/container_algorithms/sort.hpp
hpx/parallel/container_algorithms/transform.hpp
hpx/parallel/datapar/zip_iterator.hpp
hpx/parallel/traits/detail/boost_simd/vector_pack_load_store.hpp
hpx/parallel/traits/detail/libflatarray/vector_pack_load_store.hpp
hpx/parallel/traits/detail/vc/vector_pack_load_store.hpp
hpx/parallel/traits/projected.hpp
hpx/traits/is_iterator.hpp
hpx/traits/segmented_iterator_traits.hpp
hpx/util/zip_iterator.hpp
tests/regressions/parallel/CMakeLists.txt
tests/regressions/parallel/datapar/CMakeLists.txt
tests/regressions/parallel/datapar/lambda_arguments_2403.cpp
tests/regressions/parallel/datapar/lambda_return_type_2402.cpp

Solving #2402 and #2403

---

hpx/lcos/local/composable_guard.hpp
src/lcos/local/composable_guard.cpp

1) Add docs to header
2) Fix cleanup bug
3) Fewer async calls.

Improve guards:

---

CMakeLists.txt

This fixes #2329
@gentryx Please verify that this fixes your issue

Testing for experimental/optional only in C++14 mode

---

hpx/runtime/actions/trigger.hpp
hpx/runtime/parcelset/detail/call_for_each.hpp
hpx/runtime/parcelset/parcel.hpp
hpx/runtime/parcelset/parcelport_impl.hpp

These three commits fix various compile issues we currently see with msvc12

Fixing msvc12

---

hpx/parallel/executors/parallel_executor.hpp

- flyby: fix race in parallel_executor

Fix parallel_executor thread spawning

---

hpx/components/containers/partitioned_vector/partitioned_vector_segmented_iterator.hpp
hpx/parallel/algorithms/for_each.hpp
tests/regressions/CMakeLists.txt
tests/regressions/computeapi/CMakeLists.txt
tests/regressions/computeapi/for_each_value_proxy.cpp

- adding test
- flyby: add specializations for traits::is_value_proxy for segmented iterators
@atrantan please verify if this solves your issue

Enable parallel::for_each for iterators returning proxy types

---

docs/whats_new.qbk
examples/performance_counters/CMakeLists.txt
examples/performance_counters/access_counter_set.cpp
hpx/include/performance_counters.hpp
hpx/performance_counters/performance_counter_set.hpp
hpx/performance_counters/server/base_performance_counter.hpp
hpx/util/query_counters.hpp
src/performance_counters/performance_counter_set.cpp
src/util/query_counters.cpp

- using this facility for 'normal' command-line based performance counter evaluation
- this fixes #475

Adding facility representing set of performance counters

---

hpx/runtime/threads/resource_manager.hpp
src/runtime/threads/resource_manager.cpp

- implementing missing functionality
- fixed a couple of problems

More fixes to resource manager

---

src/lcos/local/composable_guard.cpp

I believe the issue is caused by stack overflows. These changes solve the problem for me.

Fix segfaults

---

CMakeLists.txt
cmake/HPX_AddConfigTest.cmake
cmake/HPX_PerformCxxFeatureTests.cmake
cmake/tests/cxx11_non_static_data_member_initialization.cpp
hpx/util/lightweight_test.hpp
hpx/util/spinlock.hpp

- adding feature test for NSDMI

Attempting to fix initialization errors on newer platforms (Boost V1.63)

---

examples/compute/cuda/CMakeLists.txt
examples/compute/cuda/cublas_matmul.cpp
hpx/compute/cuda/target.hpp
src/compute/cuda/cuda_target.cpp

Demonstrates how to mix calls to CUDA cublas with hpx futures

Cublas demo

---

hpx/runtime/applier/apply_helper.hpp

This solves random hangs when running octotiger in distributed.

Guarantee to execute remote direct actions on HPX-thread.

---

hpx/runtime/parcelset/parcelport.hpp
hpx/runtime/parcelset/parcelport_impl.hpp
src/runtime/parcelset/parcelport.cpp

- this reduces the contention on the parcel-handler mutex

Added atomic counter for parcel-destinations

---

docs/manual/commandline.qbk
docs/manual/scheduling_policies.qbk
hpx/runtime/threads/policies/hierarchy_scheduler.hpp
hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/local_queue_scheduler.hpp
hpx/runtime/threads/policies/periodic_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/static_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/static_queue_scheduler.hpp
hpx/runtime/threads/policies/throttle_queue_scheduler.hpp
hpx/runtime/threads/thread_data_fwd.hpp
hpx/runtime/threads_fwd.hpp
src/hpx_init.cpp
src/runtime/threads/detail/thread_pool.cpp
src/runtime/threads/threadmanager.cpp
src/runtime_impl.cpp
src/util/command_line_handling.cpp
src/util/parse_command_line.cpp
src/util/runtime_configuration.cpp

- flyby: removed unneeded #includes
- flyby: removed unneeded type definitions

Added priority-queue lifo scheduler

---

docs/manual/config_defaults.qbk
hpx/runtime/threads/policies/thread_queue.hpp
src/util/runtime_configuration.cpp

Making thread-queue parameters runtime-configurable 

---

hpx/compute/cuda/concurrent_executor.hpp
hpx/lcos/dataflow.hpp
hpx/lcos/split_future.hpp
hpx/lcos/wait_all.hpp
hpx/lcos/wait_any.hpp
hpx/lcos/wait_some.hpp
hpx/lcos/when_all.hpp
hpx/lcos/when_any.hpp
hpx/lcos/when_each.hpp
hpx/lcos/when_some.hpp
hpx/traits/acquire_future.hpp
hpx/util/unwrapped.hpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/local_dataflow_std_array.cpp
tests/unit/lcos/split_future.cpp
tests/unit/lcos/split_shared_future.cpp
tests/unit/lcos/unwrapped.cpp
tests/unit/lcos/wait_all_std_array.cpp
tests/unit/lcos/wait_any_std_array.cpp
tests/unit/lcos/when_all_std_array.cpp
tests/unit/lcos/when_any_std_array.cpp
tests/unit/lcos/when_some_std_array.cpp
tests/unit/serialization/serialization_array.cpp
tools/inspect/include_check.cpp

- this also adds support for invalid futures in the input

Adding support for std::array to wait_all and friends 

---

hpx/runtime/threads/detail/scheduling_loop.hpp
src/lcos/barrier.cpp
src/runtime/components/server/runtime_support_server.cpp
src/runtime/threads/detail/thread_pool.cpp

Fixing background work invocations

---

docs/manual/components.qbk

component_type clashes with the [internal typedef](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/components/component_type.hpp#L25)

Fix components example

---

hpx/lcos/detail/future_data.hpp

Currently hpx::lcos::detail::compose_cp_impl might lead to a stack overflow if
sufficient continuations are attached. To mitigate this, we register a new
thread if no sufficient stack space is available.

Fixing compose_cb stack overflow

---

hpx/plugins/parcel/coalescing_counter_registry.hpp
plugins/parcel/coalescing/coalescing_counter_registry.cpp
plugins/parcel/coalescing/coalescing_message_handler.cpp
src/runtime/parcelset/parcelhandler.cpp

Instead of unlocking, ignore the lock while creating the message handler

---

docs/manual/existing_performance_counters.qbk
hpx/components/performance_counters/memory/mem_counter.hpp
src/components/performance_counters/memory/mem_counter_linux.cpp
src/components/performance_counters/memory/memory.cpp

We need this merged before I can push my changes to pxfs (well, I can push them but they won't compile for anyone else).

added counter for reading available memory

---

docs/manual/build_system/cmake_toolchains.qbk
docs/manual/build_system/cmake_variables.qbk
hpx/plugins/parcelport_factory.hpp

- flyby: fix for generated toolchains.qbk
This fixes #2561

Fixed unhandled exception during startup

---

src/lcos/barrier.cpp
src/lcos/detail/barrier_node.cpp
src/pre_main.cpp
src/util/runtime_configuration.cpp

This is to fix startup hangs we see for large number of nodes

This adds another barrier::synchronize before registering performance counters

---

src/compute/cuda/cuda_target.cpp
tests/performance/compute/CMakeLists.txt
tests/performance/compute/cuda/CMakeLists.txt
tests/performance/compute/cuda/synchronize.cpp

- Setting CUDA future directly from the stream callback

Allowing CUDA callback to set the future directly from an OS thread

---

cmake/HPX_AddCompileFlag.cmake

Removing bogus handling of compile flags for CUDA

---

hpx/async.hpp
hpx/lcos/detail/future_data.hpp
hpx/lcos/detail/promise_base.hpp
hpx/lcos/future_wait.hpp
hpx/lcos/local/futures_factory.hpp
hpx/lcos/local/packaged_task.hpp
hpx/lcos/local/promise.hpp
hpx/lcos/promise.hpp
hpx/traits/future_access.hpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/local_promise_allocator.cpp
tests/unit/lcos/promise_allocator.cpp
tests/unit/lcos/test_allocator.hpp
tests/unit/lcos/use_allocator.cpp

Adding allocator support to:
- hpx::lcos::local::promise, hpx::lcos::promise
- hpx::lcos::local::packaged_task
- hpx::lcos::packaged_action
Also, adding tests

Adding allocator support to promise and friends

---

CMakeLists.txt
docs/manual/build_system/prerequisites.qbk

Update CMake minimum required version to 3.0.2 (closes #2621)

---

CMakeLists.txt
docs/whats_new.qbk
hpx/parallel/algorithms/inclusive_scan.hpp
hpx/parallel/algorithms/transform_inclusive_scan.hpp
tests/unit/parallel/algorithms/inclusive_scan_tests.hpp
tests/unit/parallel/algorithms/transform_inclusive_scan.cpp

Adding algorithm signatures for `inclusive_scan` and `transform_inclusive_scan` matching C++17.

Algorithms signatures

---

docs/tutorial/examples.qbk
examples/quickstart/fibonacci_futures.cpp

I am not a narrow-minded person :)

Fix typos and erroneous things in examples and tutorials.

---

examples/nqueen/nqueen.cpp
examples/nqueen/server/nqueen.hpp
hpx/components/iostreams/ostream.hpp
hpx/components/iostreams/server/buffer.hpp
hpx/components/iostreams/server/order_output.hpp
hpx/components/iostreams/server/output_stream.hpp
hpx/performance_counters/counters.hpp
hpx/performance_counters/registry.hpp
hpx/performance_counters/server/statistics_counter.hpp
hpx/plugins/parcelport/tcp/receiver.hpp
hpx/runtime/components/binpacking_distribution_policy.hpp
hpx/runtime/parcelset/decode_parcels.hpp
hpx/runtime/threads/coroutines/coroutine.hpp
hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/thread_queue.hpp
src/components/iostreams/server/output_stream.cpp
src/performance_counters/counters.cpp
src/performance_counters/registry.cpp
src/performance_counters/server/statistics_counter.cpp
src/runtime/threads/policies/parse_affinity_options.cpp

This fixes some compilation errors and integral conversion warnings for 32bit MSVC

Fixing 32bit msvc

---

hpx/runtime/threads/detail/scheduling_loop.hpp
hpx/runtime/threads/executors/manage_thread_executor.hpp
hpx/runtime/threads/executors/this_thread_executors.hpp
hpx/runtime/threads/executors/thread_pool_executors.hpp
hpx/runtime/threads/policies/scheduler_base.hpp
hpx/runtime/threads/resource_manager.hpp
hpx/runtime/threads/thread_executor.hpp
src/runtime/threads/detail/thread_pool.cpp
src/runtime/threads/executors/this_thread_executors.cpp
src/runtime/threads/executors/thread_pool_executors.cpp
src/runtime/threads/resource_manager.cpp
tests/unit/threads/CMakeLists.txt
tests/unit/threads/resource_manager.cpp

A couple of fixes I had lying around for a while in my local copy of the repository.
This improves the behavior of the resource-manager in cases where the user requests more resources than available.

Resource manager fixes

---

cmake/HPX_AddConfigTest.cmake

This significantly speeds up feature detection during configuration

Speedup feature test

---

CMakeLists.txt
docs/whats_new.qbk
examples/CMakeLists.txt
examples/queue/queue_client.cpp
hpx/include/lcos.hpp
hpx/lcos/queue.hpp
hpx/lcos/server/queue.hpp

Removing hpx::lcos::queue<T>

---

hpx/performance_counters/server/statistics_counter.hpp
src/performance_counters/performance_counter_set.cpp
src/performance_counters/server/statistics_counter.cpp
src/util/query_counters.cpp
tests/regressions/performance_counters/CMakeLists.txt
tests/regressions/performance_counters/statistics_2666.cpp

- this fixes #2666
@justwagle Please verify

Making sure statistics counters work as expected

---

hpx/lcos/future.hpp

- flyby: refactor future_serialization_save to reduce code duplication

Turning assertions into exceptions

---

hpx/runtime/components/server/managed_component_base.hpp
hpx/runtime/components/server/memory_block.hpp

Attempt to fix problem in managed_component_base

---

hpx/include/traits.hpp
hpx/traits/is_tuple_like.hpp
tests/unit/traits/CMakeLists.txt
tests/unit/traits/is_tuple_like.cpp

Requires #2685, otherwise the unit test won't pass

Add an is_tuple_like trait for sequenceable type detection

---

docs/manual/existing_performance_counters.qbk
hpx/util/histogram.hpp
hpx/util/rolling_max.hpp
hpx/util/rolling_min.hpp
src/performance_counters/registry.cpp
src/performance_counters/server/statistics_counter.cpp
src/runtime.cpp

- rolling_variance, rolling_max, rolling_min

Adding new statistics performance counters:

---

hpx/compute/cuda/default_executor.hpp
hpx/parallel/algorithms/for_each.hpp
hpx/parallel/algorithms/for_loop.hpp
src/compute/cuda/cuda_target.cpp
tests/performance/compute/cuda/synchronize.cpp

This patch tries to solve some issue when building hpx  with enabled Cuda Clang.

Make Cuda Clang builds pass

---

.github/CODE_OF_CONDUCT.md
README.rst

This is a suggestion for a code of conduct for the HPX project. Please comment.

Adding code of conduct

---

hpx/runtime/components/client_base.hpp
tests/regressions/lcos/CMakeLists.txt
tests/regressions/lcos/channel_register_as_2722.cpp

Enable lcos::channel<T>::register_as

---

CMakeLists.txt
README.rst
appveyor.yml
tests/performance/parallel_algorithms/CMakeLists.txt
tests/performance/parallel_algorithms/local/CMakeLists.txt

This adds support for the Windows AppVeyor contiguous integration service.

Appveyor support

---

cmake/HPX_SetupVc.cmake

Making sure Vc V2 builds without additional HPX configuration flags

---

hpx/util/ini.hpp
src/util/ini.cpp
tests/regressions/util/CMakeLists.txt
tests/regressions/util/set_config_entry_deadlock.cpp

This cherry picked commit fixes a deadlock in config registery.

Adding test, fixing deadlock in config registery

---

hpx/parallel/util/loop.hpp

Fixed a minor error with the accumulate function in util/loop.hpp

Error with reduce and transform reduce fixed

---

hpx/components/containers/partitioned_vector/partitioned_vector.hpp
hpx/runtime/serialization/partitioned_vector.hpp
tests/unit/serialization/CMakeLists.txt
tests/unit/serialization/serialization_partitioned_vector.cpp

hpx::partitioned_vector serializer

---

hpx/util/any.hpp

Circumvent scary warning about placement new creating object of larger size than space is available

Circumvent scary warning about placement new 

---

hpx/lcos/detail/future_data.hpp
hpx/lcos/detail/promise_base.hpp
hpx/lcos/packaged_action.hpp
tests/regressions/agas/duplicate_id_registration_1596.cpp
tests/regressions/lcos/CMakeLists.txt
tests/regressions/lcos/wait_for_action_2796.cpp

- this fixes #2796 
@KADichev please verify whether this fixes your problem

Making sure future::wait_for et.al. work properly for action results

---

hpx/util/tuple.hpp
tests/unit/util/tuple.cpp

* Add a test which targets the same issue on other toolchains

Fix a unit test failure on GCC in tuple_cat

---

hpx/parallel/algorithms/partition.hpp
tests/unit/parallel/algorithms/partition_tests.hpp

@hkaiser Fix some compile errors in #2778.

Fix compile errors on some environments of parallel::partition.

---

CMakeLists.txt
appveyor.yml
circle.yml
hpx/config/attributes.hpp

- disable those warnings for CircleCI and AppVeyor

Add option allowing to disable deprecation warning

---

tests/unit/parallel/container_algorithms/partition_range.cpp

@hkaiser Fix compile errors in #2778.
Very sorry to my mistake :(

Fix compile errors in unit test of container version of parallel::partition.

---

hpx/lcos/async_continue.hpp
hpx/lcos/detail/promise_base.hpp
hpx/lcos/packaged_action.hpp
src/runtime/agas/addressing_service.cpp
tests/regressions/lcos/CMakeLists.txt
tests/regressions/lcos/broadcast_wait_for_2822.cpp

this fixes #2822 
@KADichev please verify if this fixes your problem.

Making sure promises are marked as started when used as continuations

---

docs/manual/vector.qbk

This patch adds full documentation about views over partitioned_vector. Documentation for co-arrays is in progress.

Add documentation for partitioned_vector_view

---

hpx/runtime/serialization/detail/serialize_collection.hpp
tests/regressions/CMakeLists.txt
tests/regressions/serialization/CMakeLists.txt
tests/regressions/serialization/buffer_overrun_2839.cpp

This fixes #2839 
@krivenko please verify whether this fixes your problem

Fix usage of std::aligned_storage

---

hpx/util/detail/pack_traversal_impl.hpp

Remove constexpr from a void function

---

appveyor.yml

Add Visual Studio 2015 to the tested toolchains in Appveyor

---

hpx/parallel/util/detail/handle_local_exceptions.hpp

Fix a strange thing in parallel::util::detail::handle_local_exceptions. (Fix #2818)

---

CMakeLists.txt
cmake/HPX_AddConfigTest.cmake

Add check for libatomic

---

hpx/lcos/broadcast.hpp
tests/regressions/lcos/CMakeLists.txt
tests/regressions/lcos/broadcast_unwrap_future_2885.cpp

Adapt broadcast() to non-unwrapping async<Action>

---

src/runtime/agas/addressing_service.cpp
tests/performance/local/agas_cache_timings.cpp

Removing dependency on Boost.ICL

---

src/runtime/threads/threadmanager.cpp

This fixes #2893 
@biddisco please verify that this fixes your problem

Adding missing #include and missing guard for optional code section

---

hpx/lcos/channel.hpp
hpx/lcos/local/channel.hpp
hpx/lcos/local/receive_buffer.hpp
hpx/lcos/server/channel.hpp
hpx/throw_exception.hpp
tests/regressions/lcos/CMakeLists.txt
tests/regressions/lcos/channel_not_empty_2890.cpp

Optionaly force-delete remaining channel items on close 

---

hpx/runtime/threads/policies/parse_affinity_options.hpp
src/runtime/threads/policies/parse_affinity_options.cpp

Add numa-balanced mode to hpx::bind, spread cores over numa domains

---

hpx/runtime.hpp
hpx/runtime/resource/detail/partitioner.hpp
hpx/runtime/resource/partitioner_fwd.hpp
hpx/runtime/threads/policies/affinity_data.hpp
hpx/util/static_reinit.hpp
src/runtime.cpp
src/runtime/resource/detail/detail_partitioner.cpp
src/runtime/resource/partitioner.cpp
src/runtime/threads/policies/affinity_data.cpp
tests/regressions/CMakeLists.txt
tests/regressions/multiple_init_2918.cpp

Make sure the resource_partitioner is properly destructed on hpx::finalize

---

cmake/HPX_AddConfigTest.cmake
cmake/HPX_PerformCxxFeatureTests.cmake
cmake/tests/cxx11_override.cpp

Add a feature test to test for CXX11 override

---

src/runtime/threads/policies/affinity_data.cpp

This fixes #2785 (hopefully ;-)

Attempting to solve affinity problems on CircleCI

---

hpx/lcos/split_future.hpp
tests/unit/lcos/split_future.cpp

Adding split_future for std::vector

---

hpx/lcos/channel.hpp
hpx/lcos/server/channel.hpp

From IRC: 
15:57 <mbremer> Also @Heller s channel_direct branch is much faster, than the current channels

Changing channel actions to be direct

---

hpx/include/actions.hpp
tests/regressions/actions/CMakeLists.txt
tests/regressions/actions/missing_include_2958.cpp

- this fixes #2958 
@chinz07 Please verify whether this solves your issue.

Adding missing #include

---

hpx/runtime/resource/detail/partitioner.hpp
hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp
src/runtime/resource/detail/detail_partitioner.cpp
src/runtime/threads/executors/thread_pool_os_executors.cpp
tests/regressions/parallel/executors/CMakeLists.txt
tests/regressions/parallel/executors/handled_exception_2959.cpp

- making sure exceptions thrown during construction of a local_priority_queue_os_executor get propagated properly
- this fixes #2959 
@chinz07 please verify whether this fixes your issue

Fixing a couple of held locks during exception handling

---

CMakeLists.txt
cmake/HPX_AddConfigTest.cmake
cmake/HPX_PerformCxxFeatureTests.cmake
cmake/tests/cxx11_thread_local.cpp
hpx/util/thread_specific_ptr.hpp
tests/performance/local/native_tls_overhead.cpp

Adding explicit feature test for thread_local

---

hpx/lcos/detail/future_data.hpp
hpx/lcos/future.hpp
hpx/lcos/wait_all.hpp
hpx/runtime/components/client_base.hpp
hpx/traits/acquire_shared_state.hpp
hpx/traits/future_access.hpp
src/lcos/detail/future_data.cpp
tests/regressions/components/CMakeLists.txt
tests/regressions/components/client_base_registration.cpp
tests/unit/resource/throttle.cpp

@hapoo please verify whether this fixes your problem

Making sure client_base instance that registered the component does not unregister it when being destructed

---

hpx/util/detail/pack_traversal_impl.hpp

Workaround for #2904, broken build for Intel compilers

Simplify allocator rebinding in pack traversal

---

src/runtime/threads/policies/hwloc_topology_info.cpp

Fix cpuset leak in hwloc_topology_info.cpp

---

hpx/include/serialization.hpp
hpx/runtime/serialization/optional.hpp
hpx/util/optional.hpp
tests/unit/serialization/CMakeLists.txt
tests/unit/serialization/serialization_optional.cpp

Adding hpx::util::optional as a first step to replace experimental::optional

---

hpx/runtime/threads/coroutines/detail/context_linux_x86.hpp
hpx/runtime/threads/coroutines/detail/context_posix.hpp

This patchset was somehow missing from #3016

Fix stack overflow detection configuration in header files

---

hpx/util/detail/pack_traversal_async_impl.hpp

@Naios please verify that this does not break anything

Attempting to avoid data races in async_traversal while evaluating dataflow()

---

hpx/lcos/local/packaged_continuation.hpp
hpx/parallel/executors/execution.hpp
hpx/parallel/executors/execution_fwd.hpp
hpx/parallel/executors/thread_execution.hpp

Reverts STEllAR-GROUP/hpx#3026

Revert "implement executor then interface with && forwarding reference"

---

tests/unit/util/pack_traversal_async.cpp

Removing test which violates the asserted asynchronous traversal post conditions.

Fixing pack_traversal_async test

---

hpx/lcos/detail/async_colocated.hpp
hpx/runtime/actions/basic_action.hpp
hpx/runtime/applier/register_apply_colocated.hpp
hpx/util/annotated_function.hpp
hpx/util/bind.hpp
hpx/util/bind_back.hpp
hpx/util/bind_front.hpp
hpx/util/deferred_call.hpp

..to reduce the number of redudant instantiations

Pre-decay template arguments early

---

hpx/components/containers/container_distribution_policy.hpp
hpx/runtime/components/default_distribution_policy.hpp
tests/regressions/components/CMakeLists.txt
tests/regressions/components/bulk_new_3054.cpp

Fixing assertion in default_distribution_policy

---

hpx/util/logging/defaults.hpp
hpx/util/logging/detail/cache_before_init.hpp
hpx/util/logging/format/formatter/thread_id.hpp
hpx/util/logging/tag/defaults.hpp

- this makes things compile with clang compile-only plugin for VS

Remove more references to Boost from logging code

---

hpx/util/get_and_reset_value.hpp

This relaxes the atomic operations on performance counter values

Relax atomic operations on performance counter values

---

tests/unit/parallel/algorithms/is_heap_tests.hpp

is_heap_text fix

---

tests/unit/util/pack_traversal_async.cpp

- I removed a leftover of the std array cleanup in 00ea15c

Remove a leftover of the cxx11 std array cleanup

---

hpx/components/component_storage/server/migrate_from_storage.hpp
hpx/components/component_storage/server/migrate_to_storage.hpp
hpx/runtime/agas/addressing_service.hpp
hpx/runtime/agas/interface.hpp
hpx/runtime/agas/primary_namespace.hpp
hpx/runtime/agas/server/primary_namespace.hpp
hpx/runtime/components/server/migrate_component.hpp
hpx/runtime/components/server/migration_support.hpp
hpx/runtime/get_ptr.hpp
src/runtime/agas/addressing_service.cpp
src/runtime/agas/interface.cpp
src/runtime/agas/primary_namespace.cpp
src/runtime/agas/server/primary_namespace_server.cpp

- Simplified migration handling in primary namespace
- Fixing various race conditions

Fixing component migration

---

CMakeLists.txt
cmake/HPX_SetCMakePolicy.cmake
cmake/HPX_SetupTarget.cmake
cmake/HPX_Utils.cmake

Suppressing cmake warning issued by cmake > V3.11

---

hpx/runtime/actions/basic_action.hpp

This mostly improves consistency of different APIs.

Minor changes to how actions are executed

---

hpx/runtime/threads/topology.hpp
src/runtime/threads/topology.cpp

Fixes #3161
Adds thread local bitmap for nodesets used when querying memory binding.

Topology improvements

---

hpx/util/optional.hpp
tests/regressions/util/CMakeLists.txt
tests/regressions/util/optional_swap_3200.cpp

Fixing optional::swap

---

src/runtime/resource/partitioner.cpp

Fixes shutdown issues (hangs) for VS2015

Resolving problems during shutdown for VS2015

---

examples/CMakeLists.txt
examples/pipeline/CMakeLists.txt
examples/pipeline/Readme.md
examples/pipeline/collector.cpp
examples/pipeline/emitter.cpp
examples/pipeline/worker.cpp

This adds a simple, elastic, pipeline example to be used on multiple nodes

Adding Pipeline example

---

hpx/runtime/components/server/memory_block.hpp
src/runtime/agas/server/primary_namespace_server.cpp
src/runtime/components/server/memory_block.cpp
src/util/runtime_configuration.cpp

Fixing memory_block

---

src/runtime/threads/topology.cpp

Fixes #3221 
Not sure that the fix is correct and generic though.

Applying quick fix for hwloc-2.0

---

hpx/lcos/detail/async_implementations.hpp
hpx/parallel/executors/execution.hpp
hpx/runtime/actions/transfer_action.hpp
hpx/runtime/actions/transfer_continuation_action.hpp
hpx/runtime/components/server/managed_component_base.hpp
hpx/util/detail/vtable/vtable.hpp

Assorted fixes for CUDA

---

cmake/HPX_Documentation.cmake

Making sure documentation correctly links to source files

---

tests/unit/parallel/algorithms/adjacentfind.cpp
tests/unit/parallel/algorithms/adjacentfind_bad_alloc.cpp
tests/unit/parallel/algorithms/adjacentfind_binary.cpp
tests/unit/parallel/algorithms/adjacentfind_binary_bad_alloc.cpp
tests/unit/parallel/algorithms/adjacentfind_binary_exception.cpp
tests/unit/parallel/algorithms/adjacentfind_exception.cpp
tests/unit/parallel/algorithms/copy.cpp
tests/unit/parallel/algorithms/copyif_bad_alloc.cpp
tests/unit/parallel/algorithms/copyif_exception.cpp
tests/unit/parallel/algorithms/copyif_forward.cpp
tests/unit/parallel/algorithms/copyif_input.cpp
tests/unit/parallel/algorithms/copyif_random.cpp
tests/unit/parallel/algorithms/copyn.cpp
tests/unit/parallel/algorithms/count_tests.hpp
tests/unit/parallel/algorithms/countif_tests.hpp
tests/unit/parallel/algorithms/destroy_tests.hpp
tests/unit/parallel/algorithms/destroyn.cpp
tests/unit/parallel/algorithms/equal.cpp
tests/unit/parallel/algorithms/equal_binary.cpp
tests/unit/parallel/algorithms/fill.cpp
tests/unit/parallel/algorithms/filln.cpp
tests/unit/parallel/algorithms/find.cpp
tests/unit/parallel/algorithms/findend.cpp
tests/unit/parallel/algorithms/findfirstof.cpp
tests/unit/parallel/algorithms/findfirstof_binary.cpp
tests/unit/parallel/algorithms/findif.cpp
tests/unit/parallel/algorithms/findifnot.cpp
tests/unit/parallel/algorithms/findifnot_bad_alloc.cpp
tests/unit/parallel/algorithms/findifnot_exception.cpp
tests/unit/parallel/algorithms/for_loop.cpp

Fixes #2954 
This PR is in continuation of PR #3204.

Changing std::rand() to a better inbuilt PRNG generator.

---

hpx/util/optional.hpp

Replace constexpr with HPX_CXX14_CONSTEXPR and HPX_CONSTEXPR

---

.circleci/config.yml
tests/unit/parallel/segmented_algorithms/CMakeLists.txt
tests/unit/parallel/segmented_algorithms/partitioned_vector_find2.cpp
tests/unit/parallel/segmented_algorithms/partitioned_vector_inclusive_scan2.cpp
tests/unit/parallel/segmented_algorithms/partitioned_vector_transform_binary.cpp
tests/unit/parallel/segmented_algorithms/partitioned_vector_transform_binary1.cpp
tests/unit/parallel/segmented_algorithms/partitioned_vector_transform_binary2.cpp
tests/unit/parallel/segmented_algorithms/partitioned_vector_transform_binary3.cpp
tests/unit/parallel/segmented_algorithms/partitioned_vector_transform_scan2.cpp
tests/unit/parallel/segmented_algorithms/test_transform_binary.hpp
tests/unit/parallel/segmented_algorithms/test_transform_binary2.hpp

Splitting tests to avoid compiler OOM

---

.circleci/config.yml

Fixes #3272 
- Fixing failing install step
- Executing install and deploy step even in if the test steps failed
- Properly setting up test summaries
- Using ninja instead of make to speed up some job steps

Fix circleci workspace

---

src/performance_counters/counters.cpp
src/runtime/threads/threadmanager.cpp

- flyby: enable `{locality#0/pool#default/*}` wildcard for performance counter discovery

Fixing /scheduler/utilization/instantaneous performance counter

---

.circleci/config.yml

Fix mistakes after merge of CircleCI config

---

tests/performance/local/future_overhead.cpp

1. plain `wait_all` without the "scratcher"
2. don't wait for futures at all but look at thread counts instead to determine when all functions have finished
Both of these are usually faster than the existing benchmarks and give an idea of how much time is spent purely on scheduling and executing the functions without overheads from calling scratcher or waiting on futures.

Add two variations to the future_overhead benchmark

---

examples/hello_world_component/CMakeLists.txt
examples/hello_world_component/Makefile

Fixes #3290

---

hpx/runtime/threads/run_as_hpx_thread.hpp
tests/regressions/threads/CMakeLists.txt
tests/regressions/threads/run_as_hpx_thread_exceptions_3304.cpp

Add proper exception handling to run_as_hpx_thread

---

hpx/util/ini.hpp
src/util/ini.cpp
src/util/runtime_configuration.cpp

Fixes https://github.com/STEllAR-GROUP/phylanx/issues/395

Don't overwrite user settings with defaults in registration database

---

tests/unit/parallel/algorithms/for_loop_induction.cpp
tests/unit/parallel/algorithms/for_loop_induction_async.cpp
tests/unit/parallel/algorithms/for_loop_n.cpp
tests/unit/parallel/algorithms/for_loop_n_strided.cpp
tests/unit/parallel/algorithms/for_loop_reduction.cpp
tests/unit/parallel/algorithms/for_loop_reduction_async.cpp
tests/unit/parallel/algorithms/for_loop_strided.cpp
tests/unit/parallel/algorithms/foreach_tests.hpp
tests/unit/parallel/algorithms/foreachn_bad_alloc.cpp
tests/unit/parallel/algorithms/foreachn_exception.cpp
tests/unit/parallel/algorithms/foreachn_projection_bad_alloc.cpp
tests/unit/parallel/algorithms/foreachn_projection_exception.cpp
tests/unit/parallel/algorithms/includes.cpp
tests/unit/parallel/algorithms/inplace_merge_tests.hpp
tests/unit/parallel/algorithms/is_heap_tests.hpp
tests/unit/parallel/algorithms/is_partitioned.cpp
tests/unit/parallel/algorithms/is_sorted_tests.hpp
tests/unit/parallel/algorithms/is_sorted_until.cpp
tests/unit/parallel/algorithms/lexicographical_compare.cpp
tests/unit/parallel/algorithms/merge_tests.hpp
tests/unit/parallel/algorithms/mismatch.cpp
tests/unit/parallel/algorithms/mismatch_binary.cpp
tests/unit/parallel/algorithms/move.cpp
tests/unit/parallel/algorithms/partition_copy_tests.hpp
tests/unit/parallel/algorithms/partition_tests.hpp
tests/unit/parallel/algorithms/reduce_.cpp
tests/unit/parallel/algorithms/reduce_by_key.cpp
tests/unit/parallel/algorithms/remove_copy.cpp
tests/unit/parallel/algorithms/remove_copy_if.cpp
tests/unit/parallel/algorithms/remove_tests.hpp

Fixes #2954
This PR is in continuation of PR #3239 .

Changed std::rand to a better inbuilt PRNG Generator

---

examples/quickstart/simplest_hello_world_2.cpp
src/hpx_user_main_argc_argv.cpp
src/runtime/components/server/runtime_support_server.cpp

Reduce amount of information printed for unknown command line options

---

hpx/runtime/components/memory_block.hpp
hpx/runtime/components/server/memory_block.hpp

Renaming two functions to avoid problem described in #3285

---

hpx/lcos/future.hpp
hpx/lcos/local/packaged_continuation.hpp

@justwagle please verify whether this fixes the application hangs you're seeing.

Reverting changes introduced by #3283 as those make applications hang

---

tests/regressions/parallel/stable_merge_2964.cpp
tests/unit/parallel/container_algorithms/countif_range.cpp

Fixes some more C++11 build problems (like #3318).

Fix some more c++11 build problems

---

CMakeLists.txt
src/CMakeLists.txt

This relies on https://github.com/STEllAR-GROUP/hpxMP/pull/3

Adding build system support to integrate hpxmp into hpx at the user's machine

---

hpx/lcos/channel.hpp

Adding missing include
Fixes #3378

Fixing #3378

---

src/runtime/agas/server/primary_namespace_server.cpp

Fix small mistake in primary_namespace_server.cpp

---

src/runtime/threads/detail/scheduled_thread_pool.cpp
tests/unit/threads/schedule_last.cpp

Fixes schedule_last_test linkage failures on msvc

Explicitly instantiate configured schedulers

---

hpx/runtime/threads/policies/scheduler_base.hpp

Fix floating point exception scheduler_base idle backoff

---

.circleci/config.yml

Changing -DHPX_HAVE_THREAD_LOCAL_STORAGE=On to 
-DHPX_WITH_THREAD_LOCAL_STORAGE=On

Circle CI setting changes for hpxMP 

---

src/runtime/threads/topology.cpp

Fixes #3455. 
Adds back the old hwloc calls without `HWLOC_MEMBIND_BYNODESET` with #ifdefs so that we still get rid of the deprecation warnings with newer versions of hwloc.

Add #ifdefs to topology.cpp to support old hwloc versions again

---

tests/unit/parallel/algorithms/CMakeLists.txt
tests/unit/parallel/algorithms/remove1.cpp
tests/unit/parallel/algorithms/remove2.cpp

Fixes current circleci problems

Attempting to work around recent clang test compilation failures

---

hpx/parallel/algorithms/find.hpp
tests/unit/util/unwrap.cpp

Fixes some warnings about unused variables.

Remove unused variables

---

.circleci/config.yml
hpx/config.hpp
hpx/config/weak_symbol.hpp
hpx/parallel/util/detail/algorithm_result.hpp
hpx/util/checkpoint.hpp
src/hpx_main.cpp
tools/docker/Dockerfile

This new base docker image providing better support for C++17

Changing Base docker image

---

CMakeLists.txt
docs/sphinx/contributing/release_procedure.rst

Update main CMake file for hpxMP configuration
Add hpxMP instructions to release procedure

hpxMP release

---

hpx/util/logging/detail/logger.hpp

Fix logging regression after 2972f39e1944a564aa1013f7786d55f4f6281740

Fix logging regression

---

examples/quickstart/EasyBMP/EasyBMP.cpp
hpx/runtime/actions/lambda_to_action.hpp
hpx/runtime/threads/executors/current_executor.hpp
hpx/runtime/threads/executors/default_executor.hpp
hpx/runtime/threads/executors/pool_executor.hpp
hpx/runtime/threads/executors/service_executors.hpp
hpx/runtime/threads/executors/this_thread_executors.hpp
hpx/runtime/threads/executors/thread_pool_attached_executors.hpp
hpx/runtime/threads/executors/thread_pool_os_executors.hpp
hpx/runtime/threads/policies/local_queue_scheduler.hpp
tests/unit/parallel/algorithms/uninitialized_default_construct_tests.hpp
tests/unit/parallel/algorithms/uninitialized_default_constructn.cpp
tests/unit/parallel/algorithms/uninitialized_value_constructn.cpp

Fixes more warnings (I ran clang-format on some of the files I touched so diffs are bigger than they would be otherwise, I'll remove those changes if someone doesn't like that).

Fix more warnings

---

cmake/templates/cmake_variables.rst.in
docs/sphinx/manual/launching_and_configuring_hpx_applications.rst
docs/sphinx/terminology.rst
hpx/error.hpp
hpx/plugins/parcelport_factory.hpp
hpx/runtime/actions/basic_action.hpp
hpx/runtime/parcelset/parcelport.hpp
hpx/util/logging.hpp
src/runtime/parcelset/parcelhandler.cpp
src/runtime/parcelset/parcelport.cpp

Remove leftover security options and documentation

---

src/runtime/threads/topology.cpp

Fixes #3526.
Fixes hopefully the last hwloc version check that was wrong.

Fix hwloc version check

---

examples/resource_partitioner/CMakeLists.txt

Fixing #3533

---

docs/sphinx/releases/whats_new_1_1_0.rst
docs/sphinx/releases/whats_new_1_2_0.rst

Adds release notes for 1.2.0. Please have a read through and see if there's anything you feel is missing or needs changing (@NK-Nikunj could you look through what I wrote about `hpx_main` to see if it's accurate).
I will keep this open until just before the release to add last-minute PRs/issues to the list.

Release notes for 1.2.0

---

docs/sphinx/about_hpx/people.rst

Updating HPX people section

---

hpx/util/detail/basic_function.hpp
hpx/util/detail/vtable/unique_function_vtable.hpp

This reverts commit eb83d9d930df5dfe24f1259f6c393918d11e403f.

Partially revert "Remove vtable empty flag"

---

docs/sphinx/manual/launching_and_configuring_hpx_applications.rst

Fix formatting errors in launching_and_configuring_hpx_applications.rst

---

hpx/runtime/agas/addressing_service.hpp
hpx/runtime/parcelset/parcelhandler.hpp
hpx/runtime/threads/detail/scheduling_loop.hpp
hpx/runtime/threads/policies/scheduler_base.hpp
hpx/runtime_fwd.hpp
hpx/util/runtime_configuration.hpp
src/runtime.cpp
src/runtime/agas/addressing_service.cpp
src/runtime/agas/interface.cpp
src/runtime/applier/applier.cpp
src/runtime/parcelset/parcelhandler.cpp
src/runtime_impl.cpp
src/util/command_line_handling.cpp
src/util/parse_command_line.cpp
src/util/runtime_configuration.cpp
tests/unit/component/CMakeLists.txt
tests/unit/component/launch_process.cpp
tests/unit/parallel/executors/service_executors.cpp
tests/unit/parcelset/put_parcels.cpp
tests/unit/threads/start_stop_callbacks.cpp

Making sure networking is disabled for default one-locality-runs

---

examples/cancelable_action/cancelable_action/server/cancelable_action.hpp

Fixes errors like this:
```
terminating with uncaught exception of type hpx::thread_interrupted: std::exception
```
in the `cancelable_action_client` example.
- Use atomic to protect `id_` instead of spinlock mutex
The commit message contains more details on what happens.
Side note: this is triggered because of `spinlock` calling `suspend` after a few iterations (in `yield_k`). `spinlock` to me sounds like it should never suspend the current thread. Should that be changed as well?

Fix cancelable_action_client example

---

hpx/lcos/dataflow.hpp
hpx/lcos/detail/future_data.hpp
hpx/lcos/detail/promise_lco.hpp
hpx/lcos/packaged_action.hpp
tests/regressions/lcos/CMakeLists.txt
tests/regressions/lcos/dataflow_future_ref_3639.cpp

Dataflow now works with functions that return a reference

---

hpx/util/detail/vtable/vtable.hpp
hpx/util/function.hpp

Fixing nullptr dereference inside of function

---

hpx/runtime/threads/coroutines/detail/context_impl.hpp
hpx/util/hardware/timestamp.hpp
src/runtime/threads/coroutines/swapcontext.cpp

Adding timestamp option for S390x platform

---

hpx/error_code.hpp
hpx/util/detail/pack_traversal_impl.hpp
hpx/util/unused.hpp
src/error_code.cpp

Fixes #3643
@diehlpk Could you check whether this fixes the warnings you reported in #3643, please?

Blind attempt to fix warnings issued by gcc V9

---

hpx/parallel/executors/execution_parameters.hpp

Fixed the handling of reference wrappers to be able to safely copyable.

Fixing execution_parameters

---

cmake/templates/config_version.hpp.in

Fixes https://github.com/STEllAR-GROUP/phylanx/issues/775

Fix generated full version number to be usable in expressions

---

cmake/HPX_AddConfigTest.cmake

Making sure HPX_HAVE_LIBATOMIC is unset before checking

---

docs/sphinx/quickstart.rst

Revise quickstart CMakeLists.txt explanation

---

hpx/lcos/local/barrier.hpp
src/lcos/local/local_barrier.cpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/local_barrier_count_up.cpp

Added barrier:: increment function to increase the total number of thread
Test added

Added barrier::increment function to increase total number of thread

---

docs/sphinx/contributing/release_procedure.rst

- Add notes about which steps to skip for patch releases
- Reorder and group steps for clarity

Update release procedure

---

src/exception.cpp

Ignore all locks while handling assertions

---

hpx/lcos/local/barrier.hpp
src/lcos/local/local_barrier.cpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/local_barrier_count_up.cpp
tests/unit/lcos/local_barrier_count_up_reset.cpp
tests/unit/lcos/local_barrier_reset.cpp

Add barrier reset function, requested by hpxMP for reusing barrier

Add barrier reset function, requested by hpxMP for reusing barrier

---

hpx/parallel/algorithms/detail/accumulate.hpp
hpx/parallel/algorithms/detail/distance.hpp
hpx/parallel/algorithms/reduce.hpp
hpx/parallel/segmented_algorithms/reduce.hpp
tests/regressions/parallel/CMakeLists.txt
tests/regressions/parallel/reduce_3641.cpp

Working towards #3646, fixes #3641.

Allowing for end iterator being different from begin iterator

---

.circleci/config.yml
CMakeLists.txt
cmake/HPX_UpdateGitDocs.cmake
cmake/templates/conf.py.in
docs/CMakeLists.txt
docs/sphinx/releases.rst

Generate single-page HTML, PDF, manpage from documentation

---

hpx/lcos/local/latch.hpp
tests/unit/lcos/local_latch.cpp

Add member function count_up and reset in class latch, requested by hpxMP

Add latch member function count_up and reset, requested by hpxMP

---

hpx/util/ini.hpp
src/util/ini.cpp

Attempt to fix deadlocks during component loading

---

plugins/parcel/coalescing/coalescing_counter_registry.cpp
src/runtime/agas/server/component_namespace_server.cpp

Making sure locks are not held during suspension

---

cmake/templates/hpxrun.py.in

Fix help formatting in hpxrun.py

---

cmake/templates/conf.py.in
docs/sphinx/index.rst

Fix link to stackoverflow in documentation

---

python/hpx/environment.py
python/hpx/process.py
python/scripts/hpx_environment.py
python/scripts/hpx_invoke.py
python/scripts/hpx_optsweep.py
python/scripts/hpx_run_test.py

- Update the python scripts to work with python 3

Update python scripts to work with python 3

---

cmake/HPX_SetupBoost.cmake
docs/sphinx/manual/building_hpx.rst
tests/performance/local/CMakeLists.txt
tests/performance/local/htts_v2/CMakeLists.txt
tests/unit/threads/CMakeLists.txt
tools/CMakeLists.txt
tools/inspect/CMakeLists.txt

Improve how Boost gets linked by the CMake scripts

Disable Boost auto-linking 

---

hpx/parallel/algorithms/sort.hpp
hpx/util/lightweight_test.hpp
tests/unit/parallel/algorithms/sort.cpp
tests/unit/parallel/algorithms/sort_by_key.cpp
tests/unit/parallel/algorithms/sort_tests.hpp

Sort algorithms now use the supplied chunker to determine the required minimal chunk size

---

src/runtime/parcelset/parcelhandler.cpp
src/util/command_line_handling.cpp

This fixes some test issues in Phylanx when running them concurrently

Disabled even more spots that should not execute is networking is disabled

---

hpx/exception.hpp
hpx/exception_list.hpp
hpx/runtime/threads/coroutines/detail/context_linux_x86.hpp
hpx/util/any.hpp
hpx/util/backtrace/backtrace.hpp
src/exception.cpp
tests/regressions/util/serialize_buffer_1069.cpp
tests/unit/util/function/stateless_test.cpp

Change throw() to noexcept

---

src/runtime/parcelset/parcelhandler.cpp
src/util/command_line_handling.cpp

Second attempt for #3783 ... this time hopefully in working order

Disabled even more spots that should not execute if networking is disabled

---

tests/unit/resource/shutdown_suspended_pus.cpp

Re-enable testing all schedulers in shutdown_suspended_test

---

hpx/parallel/executors/thread_execution.hpp
hpx/parallel/executors/thread_timed_execution.hpp
hpx/performance_counters/counter_creators.hpp
hpx/runtime/agas/detail/bootstrap_locality_namespace.hpp
hpx/runtime/agas/locality_namespace.hpp
hpx/runtime/agas/server/component_namespace.hpp
src/runtime/agas/detail/bootstrap_locality_namespace.cpp
src/runtime/parcelset/parcelport.cpp
src/runtime/threads/detail/scheduled_thread_pool.cpp
src/runtime/threads/topology.cpp

Remove duplicated includes reported by cppclean.

Remove duplicated includes

---

src/util/batch_environments/slurm_environment.cpp

The SLURM batch environment parser didn't work if the number of tasks isn't a
multiple of the number of nodes.

Fixing SLURM environment parsing

---

hpx/parallel/algorithms/for_loop_reduction.hpp

Significantly speeds up `hpx::parallel::for_loop` with a reduction object.

Add cache line padding to intermediate results in for loop reduction

---

tests/performance/local/agas_cache_timings.cpp
tests/performance/local/coroutines_call_overhead.cpp
tests/performance/local/hpx_homogeneous_timed_task_spawn_executors.cpp
tests/performance/local/serialization_overhead.cpp
tests/performance/local/timed_task_spawn.cpp
tests/performance/network/network_storage/network_storage.cpp
tests/performance/network/osu/osu_bw.cpp
tests/performance/network/osu/osu_multi_lat.cpp
tests/regressions/id_type_ref_counting_1032.cpp
tests/regressions/iostreams/lost_output_2236.cpp
tests/regressions/lcos/receive_buffer_1733.cpp
tests/regressions/threads/thread_rescheduling.cpp
tests/unit/parallel/algorithms/includes.cpp
tests/unit/parallel/executors/minimal_sync_executor.cpp
tests/unit/parallel/executors/parallel_executor.cpp
tests/unit/parallel/executors/parallel_fork_executor.cpp
tests/unit/parallel/executors/parallel_policy_executor.cpp
tests/unit/parallel/executors/sequenced_executor.cpp
tests/unit/parallel/executors/service_executors.cpp
tests/unit/parallel/executors/this_thread_executors.cpp
tests/unit/parallel/executors/thread_pool_attached_executors.cpp
tests/unit/parallel/executors/thread_pool_executors.cpp
tests/unit/parallel/executors/thread_pool_os_executors.cpp
tests/unit/threads/set_thread_state.cpp

Replace the macro HPX_ASSERT by HPX_TEST in tests

---

docs/sphinx/examples/1d_stencil.rst
docs/sphinx/examples/accumulator.rst
docs/sphinx/examples/fibonacci.rst
docs/sphinx/examples/hello_world.rst
docs/sphinx/examples/interest_calculator.rst
docs/sphinx/why_hpx.rst
examples/1d_stencil/1d_stencil_2.cpp

I fixed some small errors in the documentation (code references + text). Well, I think I fixed them. I am not a native English speaker.

Documentation

---

hpx/runtime/actions/basic_action.hpp

Fixes recent compilation problems using VS2019.

Working around VS2019 problem with make_action

---

hpx/runtime/resource/detail/create_partitioner.hpp
src/hpx_init.cpp
src/runtime/resource/partitioner.cpp

Making sure errors during command line processing are properly reported and will not cause assertions

---

CMakeLists.txt
cmake/HPX_Option.cmake
libs/CMakeLists.txt
libs/cache/CMakeLists.txt
libs/cache/examples/CMakeLists.txt
libs/cache/tests/CMakeLists.txt
libs/config/CMakeLists.txt
libs/config/examples/CMakeLists.txt
libs/config/tests/CMakeLists.txt
libs/create_library_skeleton.py
libs/preprocessor/CMakeLists.txt
libs/preprocessor/tests/CMakeLists.txt

Making sure all tests are disabled if HPX_WITH_TESTS=OFF

---

cmake/templates/conf.py.in
docs/sphinx/manual/running_on_batch_systems.rst

* RostamBod only provides http.
* Fix a misspelling
Credit: Laura Lazzati

Correct rostambod url. Fix typo in doc

---

hpx/runtime/threads/coroutines/detail/context_base.hpp

Fixes HPX compilation with ASAN enabled

Fix bug in context_base.hpp

---

hpx/traits/pack_traversal_rebind_container.hpp

Fixes #3929
@khuck, @stevenrbrandt please verify that this fixes your issues.

Fixing 3929

---

cmake/HPX_AddCompileTest.cmake

Exclude modules header tests from all target

---

cmake/HPX_AddModule.cmake

[HPX_AddModule] Fix lower name var to upper

---

docs/sphinx/examples/1d_stencil.rst
docs/sphinx/examples/fibonacci_local.rst
docs/sphinx/manual/building_hpx.rst
docs/sphinx/manual/launching_and_configuring_hpx_applications.rst
docs/sphinx/manual/writing_distributed_hpx_applications.rst

Minor rst formatting fixes.
GSoD'19 applicant.

Minor docs fixes

---

hpx/util/annotated_function.hpp

Fixes https://github.com/STEllAR-GROUP/hpx/issues/2590.
I have added few lines of documentation for the function. Please let me know if you have any suggestions.
GSoD'19 applicant.
Prev
- https://github.com/STEllAR-GROUP/hpx/pull/3887
- https://github.com/STEllAR-GROUP/hpx/pull/3886
- https://github.com/STEllAR-GROUP/hpx/pull/3885
- https://github.com/STEllAR-GROUP/hpx/pull/3882
- https://github.com/STEllAR-GROUP/hpx/pull/3855
- https://github.com/STEllAR-GROUP/hpx/pull/3854
- https://github.com/STEllAR-GROUP/hpx/pull/3853

Add documentation for annotated_function

---

docs/sphinx/manual/launching_and_configuring_hpx_applications.rst
docs/sphinx/manual/miscellaneous.rst
docs/sphinx/manual/optimizing_hpx_applications.rst
docs/sphinx/manual/writing_distributed_hpx_applications.rst
docs/sphinx/manual/writing_single_node_hpx_applications.rst

@lslada I took the liberty of combining your PRs into one. Our CI infrastructure unfortunately doesn't deal too well with the number of PRs we have open. I hope you don't mind.
All credit goes to @lslada.

Fix typos in documentation

---

libs/assertion/include/hpx/assertion.hpp

Make sure __LINE__ is an unsigned

---

cmake/HPX_AddCompileTest.cmake
libs/assertion/tests/CMakeLists.txt
libs/assertion/tests/unit/CMakeLists.txt
libs/cache/tests/CMakeLists.txt
libs/collectives/tests/CMakeLists.txt
libs/config/tests/CMakeLists.txt
libs/create_library_skeleton.py
libs/format/tests/CMakeLists.txt
libs/hardware/tests/CMakeLists.txt
libs/testing/tests/CMakeLists.txt

Fix dependencies and flags for for header tests

---

cmake/HPX_AddConfigTest.cmake
cmake/HPX_PerformCxxFeatureTests.cmake
cmake/tests/cxx11_std_atomic_128bit.cpp
examples/resource_partitioner/shared_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/local_queue_scheduler.hpp
hpx/runtime/threads/policies/lockfree_queue_backends.hpp
hpx/runtime/threads/policies/shared_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/static_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/static_queue_scheduler.hpp
hpx/runtime/threads/policies/thread_queue.hpp
src/runtime/threads/detail/scheduled_thread_pool.cpp
src/runtime/threads/threadmanager.cpp
tests/unit/resource/shutdown_suspended_pus.cpp
tests/unit/resource/suspend_pool.cpp
tests/unit/resource/suspend_pool_external.cpp
tests/unit/resource/suspend_runtime.cpp
tests/unit/resource/suspend_thread.cpp
tests/unit/resource/suspend_thread_external.cpp
tests/unit/resource/suspend_thread_timed.cpp
tests/unit/threads/schedule_last.cpp

Hopefully fixes https://github.com/laristra/flecsi-third-party/pull/88

Attempt to solve issue where -latomic does not support 128bit atomics

---

libs/format/tests/unit/CMakeLists.txt
tests/regressions/build/CMakeLists.txt

Exclude a couple of tests from being built automatically.

Exclude tests from all target

---

.circleci/config.yml

Ignore stable tag on CircleCI

---

.circleci/config.yml

@parsa, @hkaiser you'll probably want to change this for Phylanx as well.

Update URL to test output conversion script

---

plugins/parcelport/mpi/mpi_environment.cpp
src/util/command_line_handling.cpp

- flyby: remove dependency on Boost.Assign from command line handling
Fixes #4032

Fixing support for mpirun

---

cmake/HPX_AddModule.cmake

Adding main HPX #include directory to modules

---

hpx/runtime/threads/policies/shared_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/thread_queue_mc.hpp

@biddisco please verify that this does not break anything on your end.

Adapting thread_queue_mc to behave even if no 128bit atomics are available

---

libs/algorithms/CMakeLists.txt
libs/allocator_support/CMakeLists.txt
libs/assertion/CMakeLists.txt
libs/cache/CMakeLists.txt
libs/collectives/CMakeLists.txt
libs/concepts/CMakeLists.txt
libs/concurrency/CMakeLists.txt
libs/config/CMakeLists.txt
libs/debugging/CMakeLists.txt
libs/errors/CMakeLists.txt
libs/execution/CMakeLists.txt
libs/format/CMakeLists.txt
libs/functional/CMakeLists.txt
libs/hardware/CMakeLists.txt
libs/hashing/CMakeLists.txt
libs/iterator_support/CMakeLists.txt
libs/logging/CMakeLists.txt
libs/plugin/CMakeLists.txt
libs/preprocessor/CMakeLists.txt
libs/segmented_algorithms/CMakeLists.txt
libs/statistics/CMakeLists.txt
libs/testing/CMakeLists.txt
libs/timing/CMakeLists.txt
libs/topology/CMakeLists.txt
libs/type_support/CMakeLists.txt
libs/util/CMakeLists.txt

Updating module dependencies from output generated by cpp-dependencies

Updating module dependencies

---

cmake/HPX_AddConfigTest.cmake
cmake/HPX_PerformCxxFeatureTests.cmake
cmake/tests/cxx17_std_in_place_type_t.cpp
examples/tuplespace/central_tuplespace/server/tuples_warehouse.hpp
hpx/util/serializable_any.hpp
hpx/util/storage/tuple.hpp
libs/datastructures/include/hpx/datastructures/any.hpp
libs/datastructures/tests/unit/any.cpp
libs/datastructures/tests/unit/boost_any.cpp
libs/program_options/include/hpx/program_options/detail/value_semantic.hpp
libs/program_options/include/hpx/program_options/value_semantic.hpp
libs/program_options/include/hpx/program_options/variables_map.hpp
libs/program_options/src/value_semantic.cpp
tests/unit/util/any_serialization.cpp
tests/unit/util/serializable_any.cpp
tests/unit/util/serializable_boost_any.cpp

Making hpx::util::any compatible with C++17

---

libs/topology/CMakeLists.txt

Stop-gap measure until cmake overhaul is in place

---

libs/create_library_skeleton.py

Fixes python script to create new modules

Fix append module path in module CMakeLists template

---

.circleci/config.yml

Store diffs of files instead of just the list of modified files.

Make CircleCI formatting check store diff

---

libs/algorithms/include/hpx/parallel/algorithms/partition.hpp
libs/algorithms/include/hpx/parallel/algorithms/sort.hpp
libs/algorithms/include/hpx/parallel/util/detail/chunk_size.hpp
libs/execution/include/hpx/parallel/executors/execution_parameters.hpp
libs/execution/tests/regressions/CMakeLists.txt
libs/execution/tests/regressions/annotated_minmax_2593.cpp
libs/execution/tests/regressions/chunk_size_4118.cpp
libs/execution/tests/regressions/future_then_async_executor.cpp
libs/execution/tests/regressions/parallel_executor_1781.cpp

Fixies #4118
@jefftrull Could you please verify whether this fixes your issue?
Note this also moves three tests into the execution module that were left behind earlier. Those are unrelated to the issue at hand.

Making sure chunk_size and max_chunk are actually applied to parallel algorithms if specified

---

hpx/util/serializable_any.hpp
libs/datastructures/include/hpx/datastructures/any.hpp

Fixes current problems on master (see http://rostam.cct.lsu.edu/builders/hpx_gcc_7_boost_1_65_centos_x86_64_debug/builds/428/steps/build_core/logs/stdio)

Attempt to fix basic_any constructor for gcc 7

---

hpx/runtime/serialization/detail/preprocess_futures.hpp
hpx/runtime/serialization/detail/preprocess_gid_types.hpp
hpx/util/serializable_any.hpp
libs/datastructures/include/hpx/datastructures/any.hpp
libs/datastructures/tests/unit/CMakeLists.txt
libs/datastructures/tests/unit/unique_any.cpp
libs/serialization/include/hpx/serialization/detail/pointer.hpp
libs/serialization/include/hpx/serialization/extra_archive_data.hpp
libs/serialization/include/hpx/serialization/extra_input_data.hpp
libs/serialization/include/hpx/serialization/extra_output_data.hpp

Renaming moveonly_any to unique_any

---

tests/regressions/build/CMakeLists.txt

Exclude test_client_1950 from all target

---

docs/sphinx/why_hpx.rst

Doc updates why hpx

---

docs/sphinx/manual/creating_hpx_projects.rst

Doc updates creating hpx projects

---

libs/serialization/include/hpx/serialization/traits/brace_initializable_traits.hpp

Adding `#include <utility>` to fix #4150

Adding utility include

---

cmake/HPX_GeneratePackage.cmake
cmake/HPX_GeneratePackageUtils.cmake

Fix hpxcxx configuration

---

docs/sphinx/manual/writing_single_node_hpx_applications.rst

Doc updates writing single node hpx applications

---

cmake/HPX_SetupCUDA.cmake

Continues #4192.
@weilewei would you mind trying this out to see if things are better?

Fix CUDA configuration

---

docs/sphinx/manual/running_on_batch_systems.rst

Updates do documentation; grammar edits.

---

docs/sphinx/manual/debugging_hpx_applications.rst

Updates to documentation; grammar edits.

---

cmake/templates/HPXConfig.cmake.in
cmake/templates/HPXMacros.cmake.in

Making sure that differences in CMAKE_BUILD_TYPE are not reported on multi-configuration cmake generators

---

examples/balancing/hpx_thread_phase.cpp
examples/balancing/os_thread_num.cpp
examples/throttle/throttle/server/throttle.cpp
hpx/runtime/parcelset/decode_parcels.hpp
hpx/runtime/parcelset/parcelport_impl.hpp
tests/regressions/threads/thread_rescheduling.cpp
tests/unit/threads/set_thread_state.cpp

Fixes #
(No bug filed)
- It looks like some namespace updates were missed in recent changes (probably [this one](https://github.com/STEllAR-GROUP/hpx/commit/435f935523164a482f3eb8578565973f3c9f41e0))
Requested by @msimberg on IRC

Update register_{thread,work} namespaces

---

hpx/runtime/threads/thread_data.hpp

Fixes #4220
-  Change 7 locations of 70000 to 70300
-
-

Changing HPX_GCC_VERSION check from 70000 to 70300

---

hpx/runtime/actions/lambda_to_action.hpp
hpx/runtime/threads/thread_data.hpp
libs/config/include/hpx/config/attributes.hpp
libs/resource_partitioner/examples/CMakeLists.txt
libs/serialization/include/hpx/serialization/detail/extra_archive_data.hpp

Fixes #4204
@instaM could you please try this PR to see whether it solves the compilation issues you were seeing?

Attempting to fix Intel compilation

---

docs/sphinx/contributing/docker_image.rst
docs/sphinx/contributing/documentation.rst
docs/sphinx/contributing/release_procedure.rst
docs/sphinx/contributing/testing_hpx.rst

Google Season of Docs. Updates to documentation; grammar edits.

Google Season of Docs updates to documentation; contributing to hpx

---

CMakeLists.txt

update hpxmp tage to v0.3.0

---

CMakeLists.txt
libs/concurrency/include/hpx/concurrency/cache_line_data.hpp
libs/coroutines/include/hpx/coroutines/detail/context_windows_fibers.hpp
libs/coroutines/include/hpx/coroutines/detail/get_stack_pointer.hpp
src/CMakeLists.txt

- adding stack size detection on Windows
- specialize cache_line_data for items that don't require padding
- fixing HPX_WITH_SWAP_CONTEXT_EMULATION on Windows

Couple of minor changes

---

libs/collectives/docs/index.rst
libs/local_lcos/docs/index.rst
libs/synchronization/docs/index.rst

Fix docs compilation problems

---

docs/sphinx/about_hpx/people.rst

Updating the acknowledgement list on the People page

Adding new authors to the people.rst

---

libs/resource_partitioner/examples/async_customization.cpp

This fixes a problem found by @msimberg and improves the test so that in future such problems would be detected.
Force pushed because I pushed the wrong branch ref first time.

Async customization

---

hpx/runtime/threads/detail/scheduling_loop.hpp
src/util/runtime_configuration.cpp

Fixes some very bad configuration values related to scheduler stealing etc. This was bad copy-pasting by me.

Fix scheduler related configuration values

---

tests/performance/local/future_overhead.cpp
tests/unit/resource/CMakeLists.txt

Applying two small changes fixing various MSVC/Windows problems

---

tests/unit/build/CMakeLists.txt

Remove warnings about missing pkgconfig on Windows

---

hpx/lcos/local/futures_factory.hpp
hpx/util/annotated_function.hpp
tests/unit/resource/scheduler_priority_check.cpp

Remove extra call to annotate function that messed up traces

---

libs/errors/src/exception.cpp

Remove environment handling from exception.cpp

---

hpx/runtime/applier/detail/apply_colocated.hpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/async_colocated.cpp
tests/unit/lcos/async_continue_colocated.cpp

- fixing a problem revealed by the new tests

This adds the missing tests for async_colocated and async_continue_colocated

---

cmake/HPX_AddComponent.cmake
cmake/HPX_AddExecutable.cmake
cmake/HPX_AddLibrary.cmake
cmake/HPX_AddModule.cmake
cmake/HPX_SetupTarget.cmake
src/CMakeLists.txt

Installing pdb files on Windows

---

CMakeLists.txt

Remove HCC and SYCL options from CMakeLists.txt

---

hpx/async.hpp
hpx/async_launch_policy_dispatch.hpp
hpx/lcos/local/futures_factory.hpp
hpx/runtime/threads/detail/scheduling_loop.hpp
hpx/runtime/threads/detail/set_thread_state.hpp
hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/local_queue_scheduler.hpp
hpx/runtime/threads/policies/scheduler_base.hpp
hpx/runtime/threads/policies/shared_priority_queue_scheduler.hpp
hpx/runtime/threads/policies/thread_queue.hpp
libs/concurrency/include/hpx/concurrency/cache_line_data.hpp
libs/coroutines/include/hpx/coroutines/coroutine.hpp
libs/coroutines/include/hpx/coroutines/detail/context_base.hpp
libs/coroutines/include/hpx/coroutines/detail/coroutine_impl.hpp
libs/coroutines/include/hpx/coroutines/thread_enums.hpp
libs/coroutines/include/hpx/coroutines/thread_id_type.hpp
libs/coroutines/src/detail/context_base.cpp
libs/execution/include/hpx/execution/executors/post_policy_dispatch.hpp
src/runtime/threads/execution_agent.cpp
src/runtime/threads/executors/thread_pool_attached_executors.cpp
src/util/backtrace/backtrace.cpp

This is a collection of mostly minor (cleanup) fixes to various places of the threading subsystem

This is a collection of mostly minor (cleanup) fixes

---

README.rst

Change copyright year in README.rst

---

components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_view_iterator.hpp
components/iostreams/include/hpx/components/iostreams/server/buffer.hpp
hpx/lcos/wait_any.hpp
hpx/lcos/when_any.hpp
hpx/parallel/task_block.hpp
libs/errors/include/hpx/errors/throw_exception.hpp
libs/local_lcos/include/hpx/local_lcos/promise.hpp
libs/logging/include/hpx/logging.hpp
libs/logging/include/hpx/logging/detail/macros.hpp
libs/logging/src/logging.cpp
plugins/parcelport/mpi/parcelport_mpi.cpp
tests/performance/local/boost_tls_overhead.cpp
tests/performance/local/htts_v2/htts2.hpp
tests/performance/local/nonconcurrent_fifo_overhead.cpp
tests/performance/local/nonconcurrent_lifo_overhead.cpp
tests/performance/local/print_heterogeneous_payloads.cpp
tests/performance/network/network_storage/network_storage.cpp
tests/unit/util/mem_fn/mem_fn_unary_addr_test.cpp
tests/unit/util/text_archive.hpp

Reverts STEllAR-GROUP/hpx#4356.

Revert "Remove some minor unused and unnecessary Boost includes"

---

.circleci/config.yml
examples/transpose/transpose_serial_block.cpp
hpx/runtime/threads/policies/queue_holder_thread.hpp
python/scripts/hpx_optsweep.py
tools/.codespell_whitelist

Add a codespell whitelist to ignore some spelling suggestions
Hint : The words to ignore should be separated with a comma

Add a whitelist of words for weird spelling suggestions

---

cmake/HPX_GeneratePackageUtils.cmake

Relax build type matching when generating pkgconfig files

---

docs/sphinx/examples/accumulator.rst

Doc updates examples components

---

docs/sphinx/examples/interest_calculator.rst

Updates to documentation; grammar edits

---

tests/regressions/component/CMakeLists.txt
tests/regressions/component/new_4369.cpp

- flyby: clean up CMakeFile.txt for this test
Fixes #4369

Adding test that verifies for 4369 to be fixed

---

tests/unit/resource/CMakeLists.txt
tests/unit/resource/cross_pool_injection.cpp

This addresses the issue mentioned in #4405

Make test specific to HPX_WITH_SHARED_PRIORITY_SCHEDULER

---

hpx/util/register_locks_globally.hpp
libs/basic_execution/include/hpx/basic_execution/register_locks.hpp
libs/basic_execution/src/register_locks.cpp
src/util/register_locks_globally.cpp
src/util/runtime_configuration.cpp

Making sure hpx.lock_detection=0 works as advertized

---

libs/batch_environments/docs/index.rst

Creating documentation for batch environments module.

Doc updates batch environment

---

tests/regressions/lcos/CMakeLists.txt
tests/regressions/lcos/dataflow_4436.cpp

Adding a test that verifies the problem can be solved using a trait specialization

---

docs/sphinx/manual/creating_hpx_projects.rst

Documentation on 'How to build HPX components with pkg-config' hello_world_component.cpp was quoted incompletely 
`:lines7-29.` The correct is 
`:lines 7-30`

Fix hello_word_component.cpp :lines

---

libs/performance_counters/tests/regressions/CMakeLists.txt
libs/threading/src/thread.cpp
libs/threading_base/include/hpx/threading_base/register_thread.hpp
libs/threading_base/tests/regressions/CMakeLists.txt
libs/threading_base/tests/regressions/thread_local_data.cpp

- flyby: fixing solution FOLDER for performance data test

Fixing execution of thread exit functions

---

src/CMakeLists.txt

Fixes master for windows (I hope!)

Move the hpx_init_params header/source to hpx target

---

CMakeLists.txt
cmake/HPX_AddConfigTest.cmake
libs/datastructures/CMakeLists.txt
libs/datastructures/include/hpx/datastructures/tuple.hpp
libs/datastructures/include/hpx/datastructures/variant_helper.hpp
libs/serialization/include/hpx/serialization/variant.hpp
libs/serialization/tests/regressions/CMakeLists.txt
libs/serialization/tests/regressions/std_variant_4448.cpp
libs/serialization/tests/unit/CMakeLists.txt
libs/serialization/tests/unit/serialization_std_variant.cpp

- adding compile only test verifying serialization of std::variant
Fixes #4448

Fixing build system to actually build variant test

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

- Try to trigger builds over here for pull requests.
- Try to use our container image for linux builds.

Update GitHub actions configs

---

README.rst

- adding more current and past funding sources

Fixing broken url in README.rst

---

.circleci/config.yml
docs/CMakeLists.txt
libs/async/include/hpx/async/detail/async_implementations_fwd.hpp
libs/datastructures/CMakeLists.txt
libs/execution/include/hpx/execution/executors/parallel_executor_aggregated.hpp

Fixes header test failures that I missed when merging #4521.

Fix header tests

---

src/runtime_impl.cpp

Fixes #4550 
As described in the referenced issue

Fix a runtime_ptr problem at shutdown when apex is enabled

---

libs/threading_base/CMakeLists.txt
libs/threading_base/include/hpx/threading_base/detail/reset_backtrace.hpp
libs/threading_base/include/hpx/threading_base/detail/reset_lco_description.hpp
libs/threading_base/src/execution_agent.cpp
libs/threading_base/src/thread_data.cpp
libs/threading_base/src/thread_helpers.cpp

Fixing compilation if HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=On

---

.github/workflows/macos.yml

I'll keep updating this until the builder is green most of the time.

Update macOS test blacklist

---

CMakeLists.txt
cmake/HPX_AddConfigTest.cmake
cmake/HPX_PerformCxxFeatureTests.cmake
cmake/tests/cxx20_coroutines.cpp
examples/transpose/CMakeLists.txt
hpx/lcos/detail/future_await_traits.hpp
hpx/lcos/detail/future_data.hpp
hpx/lcos/future.hpp
tests/unit/lcos/CMakeLists.txt
tests/unit/lcos/await.cpp

- adding allocator support for futures returned by co_return
- adding support for shared_future
- adding more tests

Adapting co_await support for C++20

---

libs/program_options/docs/index.rst
libs/resiliency/docs/index.rst

Doc updates modules program options

---

hpx/lcos/local/packaged_continuation.hpp
libs/execution/include/hpx/execution/detail/post_policy_dispatch.hpp
libs/execution/include/hpx/execution/executors/thread_pool_executor.hpp
libs/executors/include/hpx/executors/dataflow.hpp
libs/executors/include/hpx/executors/parallel_executor.hpp
libs/functional/include/hpx/functional/traits/get_function_annotation.hpp
libs/threading_base/include/hpx/threading_base/thread_description.hpp
tests/unit/apex/CMakeLists.txt
tests/unit/apex/annotation_check.cpp

Fixes #4257 (again) since the previous fixes were not complete.

Dataflow annotations for APEX

---

libs/CMakeLists.txt
libs/async/CMakeLists.txt
libs/checkpoint/CMakeLists.txt
libs/collectives/CMakeLists.txt
libs/distributed_executors/CMakeLists.txt
libs/lcos_distributed/CMakeLists.txt
libs/performance_counters/CMakeLists.txt
libs/segmented_algorithms/CMakeLists.txt

@hkaiser I've based this on the CMake formatting branch.

Deal with distributed modules in their respective CMakeLists.txt

---

libs/segmented_algorithms/docs/index.rst

Moved a hyperlink for better flow.

Updates to documentation; moved hyperlink

---

cmake/HPX_SetupBoost.cmake

Trigger an error for older boost versions on power architectures

---

libs/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp

Fixes https://github.com/STEllAR-GROUP/hpx/pull/4609#discussion_r427265367

Fixing the fix for get_idle_core_count() API

---

libs/synchronization/CMakeLists.txt
libs/synchronization/include/hpx/barrier.hpp
libs/synchronization/include/hpx/synchronization/barrier.hpp
libs/synchronization/tests/unit/CMakeLists.txt
libs/synchronization/tests/unit/barrier_cpp20.cpp

- adding hpx/barrier.hpp that imports lcos::local::cpp20_barrier into namespace hpx

Adding C++20 barrier

---

examples/quickstart/hello_world_distributed.cpp
hpx/runtime/actions/transfer_action.hpp
hpx/runtime/actions/transfer_continuation_action.hpp
libs/async/include/hpx/async/applier/apply.hpp

- flyby: simplify hello_world_distributed
Fixes #4652

Fixing task annotations for actions

---

.github/workflows/linux_debug.yml
.github/workflows/linux_release_fetchcontent.yml
.github/workflows/macos_debug.yml
.github/workflows/windows_debug.yml
.github/workflows/windows_release.yml

https://github.com/STEllAR-GROUP/hpx/pull/4659#issuecomment-633520852

Add release build on Windows to GitHub actions

---

components/performance_counters/papi/CMakeLists.txt
components/performance_counters/papi/tests/regressions/papi_counters_basic_functions.cpp

Fix PAPI counters compilation

---

examples/quickstart/CMakeLists.txt

Forcing registry option to be accepted without checks.

---

wrap/CMakeLists.txt

Fixes #4680. @scheherzade would you mind check that this works for you too?

Fix HPX_WITH_DYNAMIC_HPX_MAIN=OFF

---

libs/algorithms/tests/regressions/count_3646.cpp
libs/algorithms/tests/regressions/iter_sent.hpp
libs/algorithms/tests/regressions/reduce_3641.cpp

Add `stopValue` in `Sentinel` struct instead of `Iterator`

Add `stopValue` in `Sentinel` struct instead of `Iterator`

---

libs/serialization/docs/index.rst

First attempt generating documentation for a module. Let me know if it's too long/short, if it needs more/less detail, etc.

Doc updates; generating documentation. Will likely need heavy editing.

---

docs/sphinx/quickstart.rst

Grammar edits to documentation.

Doc updates quick start

---

libs/executors/include/hpx/executors/parallel_executor.hpp
libs/threading_base/include/hpx/threading_base/thread_description.hpp
libs/threading_base/src/thread_description.cpp
tests/unit/resource/CMakeLists.txt

Fixes #4661 ~, maybe someday... This doesn't actually fix anything yet. I'm struggling to reproduce this locally so I'll play around a bit more with this on CircleCI. It may be hitting some pathological case that only happens with limited resources. Not sure what's going on. Let's see.~

Fix resource tests

---

libs/init_runtime/CMakeLists.txt
libs/init_runtime/include/hpx/hpx_user_main_config.hpp
src/CMakeLists.txt

Move header file to module

---

libs/init_runtime/src/hpx_init.cpp
libs/performance_counters/src/counters.cpp
src/runtime/agas/addressing_service.cpp
src/runtime/components/server/runtime_support_server.cpp
src/runtime_distributed.cpp

Fix missing runtime includes for distributed runtime

---

plugins/parcelport/mpi/parcelport_mpi.cpp

Changing #include for MPI parcelport

---

cmake/HPX_SetupAllocator.cmake
cmake/templates/HPXConfig.cmake.in

Fix mimalloc linking on Windows

---

examples/1d_stencil/1d_stencil_6.cpp
examples/1d_stencil/1d_stencil_7.cpp

Fixes #4731. Let's at least get this in. Unfortunately I don't have a clue about #4746.

Fix 1d stencil index calculation

---

libs/async_cuda/CMakeLists.txt
libs/collectives/include/hpx/collectives/detail/communicator.hpp
libs/collectives/src/detail/communicator.cpp

Fixes incompatibilities between #4385 and #4718.

Remove all force linking leftovers

---

examples/1d_stencil/1d_stencil_7.cpp
libs/serialization/include/hpx/serialization/serialize_buffer.hpp

- flyby: touching up on 1d_stencil_7 example
Fixes #4746
@kordejong please verify whether this fixes your issue(s).

Fixing deleter argument bindings in serialize_buffer

---

libs/lcos_local/src/composable_guard.cpp

Make sure global variable is
a) initialized on demand only
b) freed during shutdown

Make sure global variable is handled properly

---

libs/debugging/include/hpx/debugging/print.hpp
libs/debugging/tests/unit/CMakeLists.txt
libs/debugging/tests/unit/print.cpp
libs/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp
libs/threading_base/include/hpx/threading_base/print.hpp

This PR contains a load of debug printing improvements from several branches I'm working on, in particular latest libfabric changes. Pushing this to see if it causes any compilation problems on dashboards, as I will need it merged before other branches.

debug print improvements

---

.circleci/config.yml
libs/async_cuda/CMakeLists.txt
libs/collectives/CMakeLists.txt
libs/functional/CMakeLists.txt
libs/include/CMakeLists.txt
libs/init_runtime/CMakeLists.txt
libs/iterator_support/CMakeLists.txt
libs/performance_counters/CMakeLists.txt
libs/runtime_configuration/CMakeLists.txt
libs/runtime_local/CMakeLists.txt
libs/serialization/CMakeLists.txt
libs/synchronization/CMakeLists.txt
libs/thread_pools/CMakeLists.txt
libs/threading_base/CMakeLists.txt
libs/version/CMakeLists.txt
tools/check_module_cmakelists.sh

Merges many of the unit test steps into a single step.

Clean up CircleCI config

---

libs/errors/CMakeLists.txt
libs/errors/include/hpx/errors/exception.hpp

Replace hpx::function_nonser with std::function in error module

---

libs/algorithms/include/hpx/parallel/algorithms/sort.hpp
libs/algorithms/tests/unit/algorithms/CMakeLists.txt
libs/algorithms/tests/unit/algorithms/parallel_sort.cpp

Fixes #2836 
This is integrating changes as suggested by @fjtapia (see #2836). Thanks Francisco!

Applying changes that resolve time complexity issues in sort

---

.jenkins/cscs/env-clang-newest.sh
libs/affinity/include/hpx/affinity/detail/partlit.hpp
libs/command_line_handling/src/parse_command_line.cpp
src/runtime/parcelset/detail/parcel_await.cpp

Update clang-newest configuration to use clang 10

---

libs/coroutines/src/detail/coroutine_impl.cpp

Fixes the TSS test problems that found their way into master.

Fixing TSS problems during thread termination

---

libs/schedulers/include/hpx/schedulers/local_priority_queue_scheduler.hpp
libs/schedulers/include/hpx/schedulers/local_queue_scheduler.hpp
libs/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp

@scheherzade Please check whether this fixes the issue you encountered with calculating the idle masks

Fixing the calculation of the number of idle cores and the corresponding idle masks

---

cmake/HPX_SetupBoost.cmake

Disable Boost.Asio concepts support

---

libs/algorithms/include/hpx/parallel/algorithms/move.hpp
libs/algorithms/include/hpx/parallel/container_algorithms/move.hpp
libs/algorithms/tests/unit/algorithms/move.cpp
libs/algorithms/tests/unit/container_algorithms/move_range.cpp
libs/include/include/hpx/algorithm.hpp
libs/segmented_algorithms/tests/unit/partitioned_vector_move.cpp

Making move conforming with C++20

---

libs/algorithms/CMakeLists.txt
libs/algorithms/include/hpx/parallel/algorithms/equal.hpp
libs/algorithms/include/hpx/parallel/container_algorithms.hpp
libs/algorithms/include/hpx/parallel/container_algorithms/copy.hpp
libs/algorithms/include/hpx/parallel/container_algorithms/equal.hpp
libs/algorithms/tests/unit/algorithms/equal_binary.cpp
libs/algorithms/tests/unit/container_algorithms/CMakeLists.txt
libs/algorithms/tests/unit/container_algorithms/equal_binary_range.cpp
libs/algorithms/tests/unit/container_algorithms/equal_range.cpp
libs/include/include/hpx/algorithm.hpp
libs/include/include/hpx/include/parallel_equal.hpp

Adapting hpx::equal to be conforming to C++20

---

hpx/lcos/detail/promise_base.hpp
libs/actions_base/include/hpx/actions_base/basic_action.hpp
libs/actions_base/include/hpx/actions_base/plain_action.hpp
libs/async_distributed/include/hpx/async_distributed/detail/sync_implementations.hpp
libs/components_base/include/hpx/components_base/traits/component_pin_support.hpp
libs/coroutines/include/hpx/coroutines/detail/coroutine_stackless_self.hpp
libs/coroutines/include/hpx/coroutines/stackless_coroutine.hpp
libs/datastructures/include/hpx/datastructures/tuple.hpp
libs/execution/include/hpx/execution/detail/post_policy_dispatch.hpp
libs/execution/include/hpx/execution/executors/execution_parameters.hpp
libs/futures/include/hpx/futures/packaged_continuation.hpp
libs/init_runtime/include/hpx/hpx_init_impl.hpp
libs/init_runtime/include/hpx/hpx_start_impl.hpp
libs/io_service/include/hpx/io_service/io_service_thread_pool.hpp
libs/serialization/include/hpx/serialization/serialize_buffer.hpp
libs/thread_support/include/hpx/thread_support/set_thread_name.hpp
libs/threading_base/include/hpx/threading_base/external_timer.hpp
libs/threading_base/include/hpx/threading_base/register_thread.hpp
libs/threading_base/include/hpx/threading_base/set_thread_state.hpp

Fixing unused variable warning

---

src/CMakeLists.txt

Remove HPX::hpx_no_wrap_main target

---

docs/sphinx/api/public_api.rst
docs/sphinx/manual/writing_single_node_hpx_applications.rst

Add missing `numeric.hpp` header documentation, and update headers and names in `writing_single_node_hpx_applications.rst`.

Fix algorithms documentation

---

libs/synchronization/include/hpx/synchronization/latch.hpp

Second attempt at creating this PR

Don't acquire lock if not needed

---

hpx/lcos/detail/promise_lco.hpp
hpx/runtime/components/server/component_base.hpp
hpx/runtime/components/server/fixed_component_base.hpp
libs/algorithms/include/hpx/parallel/algorithms/detail/sample_sort.hpp
libs/algorithms/include/hpx/parallel/algorithms/fill.hpp
libs/algorithms/include/hpx/parallel/algorithms/inclusive_scan.hpp
libs/algorithms/include/hpx/parallel/algorithms/move.hpp
libs/algorithms/include/hpx/parallel/algorithms/partition.hpp
libs/algorithms/include/hpx/parallel/algorithms/transform_inclusive_scan.hpp
libs/algorithms/include/hpx/parallel/algorithms/uninitialized_default_construct.hpp
libs/algorithms/include/hpx/parallel/algorithms/uninitialized_value_construct.hpp
libs/algorithms/include/hpx/parallel/task_block.hpp
libs/collectives/include/hpx/collectives/detail/barrier_node.hpp
libs/execution_base/include/hpx/execution_base/register_locks.hpp
libs/runtime_local/include/hpx/runtime_local/runtime_local_fwd.hpp
libs/segmented_algorithms/include/hpx/parallel/segmented_algorithms/all_any_none.hpp
libs/segmented_algorithms/include/hpx/parallel/segmented_algorithms/detail/reduce.hpp
libs/segmented_algorithms/include/hpx/parallel/segmented_algorithms/fill.hpp
libs/segmented_algorithms/include/hpx/parallel/segmented_algorithms/find.hpp
libs/threading_base/CMakeLists.txt
libs/threading_base/include/hpx/threading_base/thread_init_data.hpp
libs/threadmanager/CMakeLists.txt
libs/threadmanager/include/hpx/modules/threadmanager.hpp
libs/threadmanager/include/hpx/threadmanager/threadmanager_fwd.hpp
libs/topology/include/hpx/topology/cpu_mask.hpp

Fixes warnings reported on #4906

Fixing compiler warnings

---

docs/sphinx/manual/writing_distributed_hpx_applications.rst

Adding semicolon to complete line

Adding Semicolon in Documentation

---

docs/joss_paper/paper.md
tools/.codespell_whitelist

Fixes missing copyright/license inspect tool error

Add copyright and license to joss paper file

---

docs/sphinx/api/public_api.rst
docs/sphinx/contributing/docker_image.rst
docs/sphinx/contributing/modules.rst
docs/sphinx/manual/optimizing_hpx_applications.rst
docs/sphinx/releases/whats_new_1_5_0.rst

Minor documentation fixes part 2

---

libs/core/type_support/include/hpx/type_support/pack.hpp

Remove indirection layer in at_index_impl

Remove indirection layer in at_index_impl

---

libs/core/serialization/CMakeLists.txt
libs/core/serialization/include/hpx/serialization/exception_ptr.hpp

Extracts the change from #4955.

Remove serialization to functional module dependency

---

examples/random_mem_access/random_mem_access_client.cpp
libs/full/async_cuda/tests/performance/cuda_executor_throughput.cpp
libs/full/async_cuda/tests/unit/cublas_matmul.cpp
libs/full/compute/tests/unit/block_allocator.cpp
libs/full/resiliency/examples/dataflow_replicate.cpp
libs/full/resiliency/tests/performance/replay/1d_stencil_checksum.cpp
libs/full/resiliency/tests/performance/replay/1d_stencil_replay.cpp
libs/full/resiliency/tests/performance/replay/dataflow_replay.cpp
libs/full/resiliency/tests/performance/replay/dataflow_replay_validate.cpp
libs/full/resiliency/tests/performance/replicate/1d_stencil_replicate.cpp
libs/full/resiliency/tests/performance/replicate/1d_stencil_replicate_checksum.cpp
libs/parallelism/algorithms/tests/performance/transform_reduce_scaling.cpp
libs/parallelism/algorithms/tests/regressions/scan_different_inits.cpp
libs/parallelism/algorithms/tests/regressions/scan_shortlength.cpp
libs/parallelism/algorithms/tests/unit/algorithms/adjacentfind.cpp
libs/parallelism/algorithms/tests/unit/algorithms/copyif_forward.cpp
libs/parallelism/algorithms/tests/unit/algorithms/detail/test_spin_sort.cpp
libs/parallelism/algorithms/tests/unit/algorithms/sort_by_key.cpp
src/runtime/agas/big_boot_barrier.cpp
tests/performance/local/foreach_scaling.cpp
tests/performance/local/transform_reduce_binary_scaling.cpp
tools/inspect/include_check.cpp

Add <random> inspect check

---

libs/full/command_line_handling/src/parse_command_line.cpp

Fixing help string

---

.github/workflows/macos_debug.yml

See https://github.com/actions/virtual-environments/issues/1811.

Work around problems in GitHub actions macOS builder

---

.circleci/config.yml

Add codespell version print in circleci

---

.jenkins/cscs/env-clang-newest.sh
libs/core/config_registry/tests/unit/config_registry.cpp
libs/core/coroutines/CMakeLists.txt

Actually enable unity builds on Jenkins

---

docs/sphinx/api/public_api.rst
docs/sphinx/manual/writing_single_node_hpx_applications.rst
libs/parallelism/algorithms/CMakeLists.txt
libs/parallelism/algorithms/include/hpx/parallel/algorithm.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/partial_sort.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/sort.hpp
libs/parallelism/algorithms/tests/performance/CMakeLists.txt
libs/parallelism/algorithms/tests/performance/benchmark_partial_sort.cpp
libs/parallelism/algorithms/tests/performance/benchmark_partial_sort_parallel.cpp
libs/parallelism/algorithms/tests/unit/algorithms/CMakeLists.txt
libs/parallelism/algorithms/tests/unit/algorithms/partial_sort.cpp
libs/parallelism/algorithms/tests/unit/algorithms/partial_sort_parallel.cpp

@fjtapia thank you very much for contributing!

Adding Francisco Tapia's implementation of partial_sort

---

libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/adjacent_find.hpp

Thanks @aurianer for pointing this out!

Fix hpx::range::adjacent_find doxygen function signatures

---

libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/adjacent_find.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/adjacent_find.hpp

Missed in #4996. Thanks again to @aurianer for going through the PRs!

Add support for sentinels to adjacent_find

---

libs/core/config/include/hpx/config/lambda_capture.hpp

Avoid moving from lvalues

---

.jenkins/lsu/slurm-configuration-hipcc.sh

Use all AMD nodes again on rostam

---

libs/core/errors/include/hpx/errors/exception.hpp
libs/full/runtime_local/include/hpx/runtime_local/custom_exception_info.hpp
libs/full/runtime_local/src/custom_exception_info.cpp
libs/full/runtime_local/src/runtime_local.cpp

Making sure exceptions during runtime initialization are correctly reported

---

libs/core/threading_base/include/hpx/threading_base/threading_base_fwd.hpp
libs/parallelism/threading/include/hpx/threading/thread.hpp

Fixes #5129
@ct-clmsn: I hope this helps fixing your issue.

Adding specialization for std::hash<hpx::thread::id>

---

libs/parallelism/algorithms/include/hpx/parallel/algorithms/remove.hpp

Remove include of itself

---

cmake/HPX_SetupApex.cmake

Can we remove the cmake/GitExternal.cmake script now?

Fetching APEX using cmake FetchContent

---

libs/core/coroutines/include/hpx/coroutines/detail/context_posix.hpp

Attempt to fix compilation problems on Power for Fedora 35 (see: https://kojipkgs.fedoraproject.org//work/tasks/1457/62181457/build.log)

Fixing Fedora 35 for Power architectures

---

components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/detail/view_element.hpp
components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_decl.hpp
components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_fwd.hpp
components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_segmented_iterator.hpp
components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_view.hpp
components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_view_iterator.hpp
components/containers/unordered/include/hpx/components/containers/unordered/unordered_map.hpp
components/containers/unordered/include/hpx/components/containers/unordered/unordered_map_segmented_iterator.hpp
libs/core/config/include/hpx/config/deprecation.hpp
libs/core/iterator_support/tests/unit/is_iterator.cpp
libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/fill.hpp
libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/for_each.hpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_for_each.cpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/for_each.hpp
libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/for_each.hpp
libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/remove_copy.hpp
libs/parallelism/algorithms/tests/unit/algorithms/foreach_tests.hpp
libs/parallelism/algorithms/tests/unit/algorithms/foreachn_exception.cpp
libs/parallelism/algorithms/tests/unit/container_algorithms/foreach_adapt.cpp

This works towards solving #5156

Starting to separate segmented algorithms: for_each

---

libs/full/components/examples/CMakeLists.txt
libs/full/components/tests/CMakeLists.txt
libs/full/runtime_components/examples/CMakeLists.txt
libs/full/runtime_components/tests/CMakeLists.txt

#5153  crossed paths in an unfortunate way with #5177.

Re-enable component tests

---

libs/full/compute/tests/unit/CMakeLists.txt
libs/full/resource_partitioner/examples/CMakeLists.txt
libs/full/resource_partitioner/examples/async_customization.cpp
libs/full/resource_partitioner/examples/guided_pool_test.cpp
libs/full/resource_partitioner/examples/oversubscribing_resource_partitioner.cpp
libs/full/resource_partitioner/examples/simple_resource_partitioner.cpp
tests/regressions/threads/CMakeLists.txt
tests/unit/resource/CMakeLists.txt

Fixes some leftovers from #5171.

Remove some leftover HPX_WITH_*_SCHEDULER uses

---

.jenkins/lsu/env-hipcc.sh

I compiled fine locally on Rostam, let's see what CI says

Update ROCm to 4.0.1 on Rostam

---

libs/CMakeLists.txt
libs/core/hashing/include/hpx/hashing/fibhash.hpp
libs/core/itt_notify/CMakeLists.txt
libs/core/itt_notify/include/hpx/modules/itt_notify.hpp
libs/core/itt_notify/src/itt_notify.cpp
libs/core/synchronization/include/hpx/synchronization/spinlock_pool.hpp
libs/full/actions_base/include/hpx/actions_base/basic_action.hpp
libs/full/components_base/src/server/wrapper_heap.cpp

- fixing wrong #include path
- flyby: make ittnotify functions constexpr and noexcept where possible
Fixes #5222

Fixing build system for ittnotify

---

.github/workflows/linux_hip.yml

Try out a Github action for hipcc, in case the lsu CI end up with an invalid build id

Add a HIP github action

---

libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/all_any_none.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/all_any_none.hpp
libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/all_any_none.hpp

Seperate segmented algorithms for none_of, any_of and all_of
Replace tag_invoke with tag_fallback_invoke
Issue #5156 
Issue #5204

Separate segmented algorithms for none_of, any_of and all_of

---

examples/quickstart/CMakeLists.txt
examples/quickstart/invoke_function.cpp
libs/full/actions/include/hpx/actions/invoke_function.hpp
libs/full/executors_distributed/include/hpx/executors_distributed/distribution_policy_executor.hpp
libs/full/include/include/hpx/hpx.hpp

- also applies fixes to the facility itself.

Add an example demonstrating the use of the invoke_function_action facility

---

.circleci/config.yml
CMakeLists.txt
libs/parallelism/algorithms/include/hpx/parallel/datapar/iterator_helpers.hpp
libs/parallelism/algorithms/include/hpx/parallel/datapar/loop.hpp
libs/parallelism/algorithms/include/hpx/parallel/datapar/transform_loop.hpp
libs/parallelism/algorithms/tests/unit/datapar_algorithms/count_datapar.cpp
libs/parallelism/algorithms/tests/unit/datapar_algorithms/countif_datapar.cpp
libs/parallelism/algorithms/tests/unit/datapar_algorithms/foreach_datapar.cpp
libs/parallelism/algorithms/tests/unit/datapar_algorithms/foreach_datapar_zipiter.cpp
libs/parallelism/algorithms/tests/unit/datapar_algorithms/foreachn_datapar.cpp
libs/parallelism/algorithms/tests/unit/datapar_algorithms/transform_binary2_datapar.cpp
libs/parallelism/executors/include/hpx/executors/datapar/execution_policy.hpp

Fixes #
- Format datapar/transform_loop.hpp
- Fix in_in_out_result
- Fix tests/datapar_algorithms
https://github.com/STEllAR-GROUP/hpx/pull/5235#issuecomment-803026630

Fixing datapar

---

libs/full/command_line_handling/CMakeLists.txt
libs/full/command_line_handling/include/hpx/command_line_handling/late_command_line_handling.hpp
libs/full/command_line_handling/src/command_line_handling.cpp
libs/full/command_line_handling/src/late_command_line_handling.cpp
libs/full/command_line_handling/tests/regressions/configuration_1572.cpp
libs/full/command_line_handling/tests/regressions/late_commandline_options_5257.cpp
libs/full/command_line_handling/tests/regressions/options_as_config_3339.cpp
libs/full/command_line_handling/tests/regressions/use_all_cores_2262.cpp
libs/full/runtime_distributed/src/server/runtime_support_server.cpp
libs/full/runtime_local/include/hpx/runtime_local/runtime_local_fwd.hpp
libs/full/runtime_local/src/runtime_local.cpp
tests/regressions/CMakeLists.txt

@msimberg please verify that this works as advertized for the local runtime.

Making late command line options available for local runtime

---

libs/core/execution_base/include/hpx/execution_base/operation_state.hpp
libs/core/execution_base/tests/unit/basic_sender.cpp
libs/core/execution_base/tests/unit/basic_submit.cpp
libs/core/type_support/include/hpx/type_support/pack.hpp
libs/parallelism/execution/CMakeLists.txt
libs/parallelism/execution/include/hpx/execution/algorithms/detail/single_result.hpp
libs/parallelism/execution/include/hpx/execution/algorithms/just.hpp
libs/parallelism/execution/include/hpx/execution/algorithms/sync_wait.hpp
libs/parallelism/execution/include/hpx/execution/algorithms/when_all.hpp
libs/parallelism/execution/tests/unit/CMakeLists.txt
libs/parallelism/execution/tests/unit/algorithm_just.cpp
libs/parallelism/execution/tests/unit/algorithm_just_on.cpp
libs/parallelism/execution/tests/unit/algorithm_on.cpp
libs/parallelism/execution/tests/unit/algorithm_transform.cpp
libs/parallelism/execution/tests/unit/algorithm_when_all.cpp
libs/parallelism/executors/include/hpx/executors/p0443_executor.hpp
libs/parallelism/executors/tests/unit/CMakeLists.txt
libs/parallelism/executors/tests/unit/p0443_executor.cpp

Adds the `when_all` algorithm from P1897. Contains #5237 and #5245.

P1897 when_all

---

libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/transform.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform.hpp
libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/transform.hpp

Seperate segmented algorithms for transform
Replace tag_invoke with tag_fallback_invoke
Issue #5156 
Issue #5204

Separate segmented algorithms for transform

---

libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/transform_reduce.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_reduce.hpp
libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/transform_reduce.hpp

Seperate segmented algorithms for transform_reduce
Replace tag_invoke with tag_fallback_invoke
Issue #5156
Issue #5204

Separate segmented algorithms for transform_reduce

---

.jenkins/cscs/env-clang-cuda.sh
.jenkins/cscs/env-gcc-cuda.sh
.jenkins/cscs/env-icc.sh

Update Boost for daint 20.11 after update

---

libs/parallelism/algorithms/include/hpx/parallel/algorithms/destroy.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/equal.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/fill.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/find.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/for_loop.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/generate.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/includes.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/is_heap.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/is_partitioned.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/is_sorted.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/make_heap.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/merge.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/mismatch.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/move.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/partial_sort.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/reduce.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/remove.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/remove_copy.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/search.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/set_difference.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/set_intersection.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/set_symmetric_difference.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/set_union.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_reduce.hpp

Move algorithms to tag_fallback_invoke
https://github.com/STEllAR-GROUP/hpx/issues/5204

Move algorithms to tag_fallback_invoke

---

.jenkins/cscs/env-clang-newest.sh

Update clang-newest configuration to use clang 12 and Boost 1.76.0

---

libs/core/errors/include/hpx/errors/exception_list.hpp
libs/core/synchronization/include/hpx/synchronization/latch.hpp
libs/core/synchronization/src/detail/condition_variable.cpp
libs/parallelism/algorithms/CMakeLists.txt
libs/parallelism/algorithms/include/hpx/parallel/task_block.hpp
libs/parallelism/algorithms/include/hpx/parallel/task_group.hpp
libs/parallelism/algorithms/tests/unit/block/CMakeLists.txt
libs/parallelism/algorithms/tests/unit/block/task_group.cpp

- this is similar to tbb:task_group

Adding hpx::execution::experimental::task_group

---

libs/core/testing/include/hpx/modules/testing.hpp

Add explicit keyword to fixture constructor

---

libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/reduce.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/reduce.hpp
libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/reduce.hpp
libs/parallelism/algorithms/tests/unit/algorithms/reduce_.cpp
libs/parallelism/algorithms/tests/unit/container_algorithms/reduce_range.cpp

Seperate segmented algorithms for reduce
Replace tag_invoke with tag_fallback_invoke
Add sentinel tests for reduce.
Issue #5156
Issue #5204

Seperate segmented algorithms for reduce

---

libs/parallelism/algorithms/tests/unit/container_algorithms/reduce_range.cpp

Follow-up iter_sent header include fix.

Follow up iter_sent include on #5225

---

libs/parallelism/execution/include/hpx/execution/algorithms/detail/partial_algorithm.hpp

I previously only specialized it for zero and one arguments, out of laziness. This should make it work with any number.

Make partial_algorithm work with any number of arguments

---

CMakeLists.txt
cmake/HPX_SetupAsio.cmake

APEX: 2.3.1 to 2.4.0.
asio: asio-1-18-1 to asio-1-18-2.

Update APEX and asio tags

---

libs/full/command_line_handling/src/command_line_handling.cpp
libs/full/command_line_handling_local/src/command_line_handling_local.cpp

Fix check for pu-step in single-core case

---

libs/core/coroutines/include/hpx/coroutines/detail/context_posix.hpp
libs/core/coroutines/src/detail/context_posix.cpp

Fixes problems as described in #5351

Making sure default_stack_size is defined whenever declared

---

CMakeLists.txt
cmake/HPX_GeneratePackage.cmake
tests/unit/build/CMakeLists.txt

@aurianer this is relevant to #5283. Also to https://github.com/STEllAR-GROUP/hpx/issues/4942 (as this would allow working around problems with generating pkgconfig files by simply disabling it).

Add option to disable pkgconfig generation

---

libs/full/async_mpi/src/mpi_future.cpp

This was missed due to the tests not running on rostam. Let's wait for those to actually run correctly before merging this.

Fix compilation with MPI enabled

---

libs/core/functional/include/hpx/functional/deferred_call.hpp
libs/core/functional/include/hpx/functional/invoke_fused.hpp
libs/core/functional/include/hpx/functional/invoke_result.hpp
libs/core/functional/include/hpx/functional/traits/is_invocable.hpp

Remove HPX 1.5.0 deprecations

---

libs/full/collectives/src/detail/barrier_node.cpp

Attempt to fix the startup hang with nodes > 32

---

libs/full/collectives/include/hpx/collectives/gather.hpp
libs/full/collectives/tests/unit/gather.cpp

Fixes issue reported here: https://github.com/STEllAR-GROUP/hpx/pull/4676#issuecomment-860999175
@khuck, please verify whether this fixes your problem.

Fixing gather_there for used with lvalue reference argument

---

CMakeLists.txt

Updating APEX version to v2.4.1 to patch HPX collectives API change.

Update APEX tag

---

libs/core/synchronization/tests/unit/sliding_semaphore.cpp

The semaphore has to be kept alive long enough for all tasks to get to signal it. The task that releases the waiting thread may not be the last task to signal the semaphore, and if that happens the semaphore will go
out of scope too early. (Explanation and diagram in the test.)

Fix sliding semaphore test

---

tools/perftests_ci/driver.py

This just got missed with #5382 and #5044 being merged at roughly the same time.

Fetch Asio automatically in perftests CI

---

libs/full/collectives/docs/index.rst
libs/full/collectives/include/hpx/collectives/all_gather.hpp
libs/full/collectives/include/hpx/collectives/all_reduce.hpp
libs/full/collectives/include/hpx/collectives/all_to_all.hpp
libs/full/collectives/include/hpx/collectives/broadcast.hpp
libs/full/collectives/include/hpx/collectives/exclusive_scan.hpp
libs/full/collectives/include/hpx/collectives/gather.hpp
libs/full/collectives/include/hpx/collectives/inclusive_scan.hpp
libs/full/collectives/include/hpx/collectives/scatter.hpp

- flyby: updating documentation for collective operations
Fixes #5395

Introduce compatibility layer for collective operations

---

libs/parallelism/executors/include/hpx/executors/p0443_executor.hpp

Removing unneeded typedef

---

libs/core/config/include/hpx/config/attributes.hpp

Reverts STEllAR-GROUP/hpx#5425

Revert "Adding the missing defined for HPX_HAVE_DEPRECATION_WARNINGS"

---

libs/core/config/include/hpx/config/deprecation.hpp

Add deprecation warnings for the next version (i.e. v1.8).

Add deprecation warnings for v1.8

---

libs/parallelism/execution/include/hpx/execution/algorithms/when_all.hpp

Fix when_all_sender connect for references

---

libs/full/async_cuda/src/cuda_event_callback.cpp

@aurianer I think this fixes the inconsistency you noticed on #5342. I just made the logging statements print both the queue and vector sizes each time as both may be interesting. Could you please have a look?

Update CUDA polling logging to be more verbose

---

docs/sphinx/releases/whats_new_1_7_0.rst

Fills in remaining release notes (PR and issue lists will be updated separately as those are a living thing...).
Could everyone please have a look and fill in whatever I've missed. Apologies in advance for anything that I have missed. In particular, @hkaiser could you add a note on the collectives changes (and anything else that you think is relevant)? @Jedi18, @srinivasyadav18 could you have a look to see if I've missed some algorithms that you've adapted?

Final release notes for 1.7.0

---

libs/core/topology/src/topology.cpp

The "Node" word can be confusing

Change the print-bind output to be more precise

---

CMakeLists.txt
tools/roll_release.sh

I've also updated the `roll_release.sh` script to add a link to the release notes in the release description on GitHub (I've manually added it for this release, we'll see at the next release if it's right...).

Post 1.7.0 version bump

---

tools/perftests_ci/perftest/plot.py

The performance plot was not showing if there weren't significant performance change.

Make performance plot show even if similar performance

---

libs/parallelism/algorithms/CMakeLists.txt
libs/parallelism/algorithms/include/hpx/parallel/algorithms/copy.hpp
libs/parallelism/algorithms/include/hpx/parallel/datapar.hpp
libs/parallelism/algorithms/include/hpx/parallel/datapar/loop.hpp
libs/parallelism/algorithms/include/hpx/parallel/datapar/transfer.hpp
libs/parallelism/algorithms/include/hpx/parallel/datapar/transform_loop.hpp
libs/parallelism/algorithms/include/hpx/parallel/util/transfer.hpp
libs/parallelism/algorithms/tests/unit/algorithms/copy.cpp
libs/parallelism/algorithms/tests/unit/algorithms/copy_tests.hpp
libs/parallelism/algorithms/tests/unit/algorithms/copyn.cpp
libs/parallelism/algorithms/tests/unit/algorithms/copyn_tests.hpp
libs/parallelism/algorithms/tests/unit/datapar_algorithms/CMakeLists.txt
libs/parallelism/algorithms/tests/unit/datapar_algorithms/copy_datapar.cpp
libs/parallelism/algorithms/tests/unit/datapar_algorithms/copyn_datapar.cpp

- Adapts `copy` algorithm to datapar
https://github.com/STEllAR-GROUP/hpx/issues/2333

Adapt datapar copy

---

libs/core/functional/include/hpx/functional/bind.hpp
libs/core/functional/include/hpx/functional/traits/is_action.hpp
libs/core/functional/include/hpx/functional/traits/is_bind_expression.hpp
libs/core/functional/include/hpx/functional/traits/is_placeholder.hpp
libs/core/functional/tests/regressions/CMakeLists.txt
libs/core/functional/tests/regressions/bind_sfinae_5488.cpp
libs/core/type_support/include/hpx/type_support/pack.hpp
libs/full/async_distributed/include/hpx/async_distributed/bind_action.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_exclusive_scan.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_inclusive_scan.hpp

Fixes #5488
- flyby: modernize bind and related facilities

Adding bound-checking for bind placeholders

---

.jenkins/cscs-perftests/Jenkinsfile
.jenkins/cscs/Jenkinsfile
.jenkins/cscs/entry.sh
.jenkins/lsu/Jenkinsfile
.jenkins/lsu/entry.sh

Update Jenkins GitHub token to use StellarBot GitHub account

---

libs/core/serialization/include/hpx/serialization/detail/extra_archive_data.hpp
libs/core/serialization/include/hpx/serialization/detail/pointer.hpp
libs/core/serialization/src/detail/pointer.cpp
libs/full/checkpoint_base/include/hpx/checkpoint_base/checkpoint_data.hpp
libs/full/checkpoint_base/src/checkpoint_data.cpp
libs/full/naming/include/hpx/naming/detail/preprocess_gid_types.hpp
libs/full/naming/src/detail/preprocess_gid_types.cpp
libs/parallelism/lcos_local/include/hpx/lcos_local/detail/preprocess_future.hpp
libs/parallelism/lcos_local/src/preprocess_future.cpp

Change extra archive data to rely on uniqueness of a variable address, not a function address

---

.gitignore
cmake/HPX_AddConfigTest.cmake
cmake/HPX_PerformCxxFeatureTests.cmake
cmake/tests/cxx20_perfect_pack_capture.cpp
libs/core/execution_base/include/hpx/execution_base/execution.hpp
libs/core/iterator_support/CMakeLists.txt
libs/core/iterator_support/include/hpx/iterator_support/counting_shape.hpp
libs/core/iterator_support/include/hpx/iterator_support/range.hpp
libs/core/iterator_support/include/hpx/iterator_support/traits/is_range.hpp
libs/parallelism/execution/include/hpx/execution/algorithms/bulk.hpp
libs/parallelism/execution/include/hpx/execution/algorithms/detach.hpp
libs/parallelism/executors/CMakeLists.txt
libs/parallelism/executors/include/hpx/executors/guided_pool_executor.hpp
libs/parallelism/executors/include/hpx/executors/scheduler_executor.hpp
libs/parallelism/executors/tests/unit/CMakeLists.txt
libs/parallelism/executors/tests/unit/scheduler_executor.cpp

This implements an executor that relies on any sender/receiver scheduler

Scheduler executor

---

cmake/tests/builtin_make_integer_seq.cu
cmake/tests/builtin_type_pack_element.cu
docs/sphinx/manual/building_hpx.rst
libs/core/config/include/hpx/config/constexpr.hpp
libs/core/execution_base/include/hpx/execution_base/operation_state.hpp
libs/core/execution_base/include/hpx/execution_base/receiver.hpp
libs/core/execution_base/include/hpx/execution_base/sender.hpp
libs/full/async_cuda/include/hpx/async_cuda/transform_stream.hpp
libs/parallelism/execution/tests/unit/algorithm_test_utils.hpp

Require cxx17 minor comments

---

libs/parallelism/executors/include/hpx/executors/scheduler_executor.hpp
libs/parallelism/executors/tests/unit/scheduler_executor.cpp

Adds missing commits from #5429.
@hkaiser please have a look if this still looks sane. Particularly, if there's anything that you pushed later on that this reverts.

Add missing commits from scheduler_executor PR

---

docs/sphinx/api/public_api.rst
docs/sphinx/manual/writing_single_node_hpx_applications.rst
examples/quickstart/potpourri.cpp
libs/full/include_local/include/hpx/local/algorithm.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/sort.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/sort_by_key.hpp
libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/sort.hpp
libs/parallelism/algorithms/tests/performance/benchmark_inplace_merge.cpp
libs/parallelism/algorithms/tests/performance/benchmark_merge.cpp
libs/parallelism/algorithms/tests/unit/algorithms/parallel_sort.cpp
libs/parallelism/algorithms/tests/unit/algorithms/sort.cpp
libs/parallelism/algorithms/tests/unit/algorithms/sort_tests.hpp
libs/parallelism/algorithms/tests/unit/container_algorithms/sort_range.cpp
libs/parallelism/algorithms/tests/unit/container_algorithms/sort_range_tests.hpp

Adapted sort to C++ 20 and added container overloads. (range and sentinel). Added sentinel tests.
Issue #4822
Issue #3646

Adapt sort to C++ 20

---

.jenkins/cscs-perftests/comment_github.sh
.jenkins/cscs-perftests/entry.sh

Comment on the PR with the performance report in case of a failure
Note: I will work on uploading the corresponding image of the report on CDash as it is not allowed through the Github API, only through manual drag and drop

Experimentation to make the perftest report public

---

libs/core/asio/src/map_hostnames.cpp
libs/core/concurrency/include/hpx/concurrency/deque.hpp
libs/core/schedulers/include/hpx/schedulers/local_priority_queue_scheduler.hpp
libs/full/batch_environments/src/batch_environment.cpp
libs/full/runtime_configuration/include/hpx/runtime_configuration/runtime_configuration.hpp
libs/full/runtime_configuration/src/runtime_configuration.cpp
libs/full/runtime_local/include/hpx/runtime_local/pool_timer.hpp

- flyby: fix minor inconsistency while thread stealing
- flyby: fixing warnings on Windows
This separates some minor improvements from #5467

Minor changes that improve performance

---

libs/parallelism/algorithms/CMakeLists.txt
libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/fill.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/fill.hpp
libs/parallelism/algorithms/include/hpx/parallel/datapar.hpp
libs/parallelism/algorithms/include/hpx/parallel/datapar/fill.hpp
libs/parallelism/algorithms/tests/unit/algorithms/fill.cpp
libs/parallelism/algorithms/tests/unit/algorithms/fill_tests.hpp
libs/parallelism/algorithms/tests/unit/algorithms/filln.cpp
libs/parallelism/algorithms/tests/unit/algorithms/filln_tests.hpp
libs/parallelism/algorithms/tests/unit/datapar_algorithms/CMakeLists.txt
libs/parallelism/algorithms/tests/unit/datapar_algorithms/fill_datapar.cpp
libs/parallelism/algorithms/tests/unit/datapar_algorithms/filln_datapar.cpp

- Convert `sequential_fill` to `CPO`.
- Adapt datapar fill.
- Adapt datapar fill unit tests.
#2333

Adapt datapar fill

---

docs/sphinx/api/public_api.rst
docs/sphinx/manual/writing_single_node_hpx_applications.rst
libs/parallelism/algorithms/CMakeLists.txt
libs/parallelism/algorithms/include/hpx/parallel/algorithm.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/shift_left.hpp
libs/parallelism/algorithms/include/hpx/parallel/algorithms/shift_right.hpp
libs/parallelism/algorithms/include/hpx/parallel/container_algorithms.hpp
libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/shift_left.hpp
libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/shift_right.hpp
libs/parallelism/algorithms/tests/unit/algorithms/CMakeLists.txt
libs/parallelism/algorithms/tests/unit/algorithms/shift_left.cpp
libs/parallelism/algorithms/tests/unit/algorithms/shift_right.cpp
libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt
libs/parallelism/algorithms/tests/unit/container_algorithms/shift_left_range.cpp
libs/parallelism/algorithms/tests/unit/container_algorithms/shift_right_range.cpp

Added shift_left and shift_right algorithms.
Closes #3706
Issue #4822

Add shift_left and shift_right algorithms

---

libs/parallelism/algorithms/include/hpx/parallel/algorithms/mismatch.hpp

No API changes since the range overloads rely on mismatch_binary not mismatch.

Adapt mismatch to support sentinels

---

libs/full/collectives/src/detail/communication_set_node.cpp
libs/full/collectives/tests/unit/communication_set.cpp

This fixes occasional hangs of the communication set test

Fixing communication set

---

.jenkins/cscs/env-clang-cuda.sh

The module has been updated after the latest Piz Daint maintenance.

Update CUDA module in clang-cuda configuration

---

libs/core/async_cuda/include/hpx/async_cuda/transform_stream.hpp

Use `try_catch_exception_ptr` as the catch block may yield

Change try catch block to try_catch_exception_ptr

---

examples/balancing/CMakeLists.txt
examples/balancing/hpx_thread_phase.cpp
examples/balancing/os_thread_num.cpp
examples/future_reduce/CMakeLists.txt
examples/future_reduce/rnd_future_reduce.cpp
examples/quickstart/composable_guard.cpp
examples/quickstart/executor_with_thread_hooks.cpp
examples/quickstart/fibonacci_dataflow.cpp
examples/quickstart/fibonacci_futures.cpp
examples/quickstart/fibonacci_local.cpp
examples/quickstart/file_serialization.cpp
examples/quickstart/interval_timer.cpp
examples/quickstart/latch_local.cpp
examples/quickstart/potpourri.cpp
examples/quickstart/safe_object.cpp
examples/quickstart/timed_wake.cpp
examples/quickstart/use_main_thread.cpp
examples/quickstart/wait_composition.cpp
examples/transpose/transpose_await.cpp
examples/transpose/transpose_serial.cpp
examples/transpose/transpose_serial_block.cpp
examples/transpose/transpose_smp.cpp
examples/transpose/transpose_smp_block.cpp

Make more examples work with local runtime

---

libs/core/futures/CMakeLists.txt
libs/core/futures/include/hpx/futures/packaged_task.hpp
libs/core/futures/tests/regressions/CMakeLists.txt
libs/core/futures/tests/regressions/exception_from_continuation_1613.cpp
libs/core/futures/tests/regressions/set_hpx_limit_798.cpp
libs/core/futures/tests/regressions/wait_for_1751.cpp
libs/core/futures/tests/unit/CMakeLists.txt
libs/core/futures/tests/unit/await.cpp
libs/core/futures/tests/unit/local_promise_allocator.cpp
libs/core/futures/tests/unit/local_use_allocator.cpp
libs/core/futures/tests/unit/test_allocator.hpp
libs/core/lcos_local/CMakeLists.txt
libs/core/lcos_local/include/hpx/lcos_local/channel.hpp
libs/core/lcos_local/include/hpx/lcos_local/composable_guard.hpp
libs/full/include/include/hpx/include/lcos_local.hpp
libs/full/runtime_distributed/src/server/runtime_support_server.cpp
tests/regressions/lcos/CMakeLists.txt
tests/unit/lcos/CMakeLists.txt

- flyby: move tests related to local futures to futures module

Moving packaged_task to module futures

---

libs/core/algorithms/include/hpx/parallel/util/detail/sender_util.hpp
libs/core/async_cuda/include/hpx/async_cuda/transform_stream.hpp
libs/core/async_cuda/tests/unit/transform_stream.cu
libs/core/execution/CMakeLists.txt
libs/core/execution/include/hpx/execution/algorithms/bulk.hpp
libs/core/execution/include/hpx/execution/algorithms/execute.hpp
libs/core/execution/include/hpx/execution/algorithms/start_detached.hpp
libs/core/execution/include/hpx/execution/algorithms/then.hpp
libs/core/execution/tests/unit/CMakeLists.txt
libs/core/execution/tests/unit/algorithm_ensure_started.cpp
libs/core/execution/tests/unit/algorithm_start_detached.cpp
libs/core/execution/tests/unit/algorithm_then.cpp
libs/core/executors/include/hpx/executors/scheduler_executor.hpp
libs/core/executors/tests/unit/thread_pool_scheduler.cpp
libs/core/synchronization/tests/unit/async_rw_mutex.cpp
libs/full/compute_cuda/tests/performance/synchronize.cu

This is in line with https://wg21.link/p2300.

Rename execution::transform to execution::then and execution::detach to execution::start_detached

---

libs/core/coroutines/include/hpx/coroutines/thread_id_type.hpp
libs/core/schedulers/include/hpx/schedulers/thread_queue.hpp

Fixes #5666
@diehlpk please try whether this fixes the issue you reported

Attempt to fix compilation issues with Boost V1.76

---

.jenkins/cscs/env-clang-12.sh
.jenkins/cscs/env-clang-13.sh
.jenkins/cscs/env-clang-7.sh
.jenkins/cscs/env-clang-apex.sh
.jenkins/cscs/env-clang-cuda.sh
.jenkins/cscs/env-gcc-10.sh
.jenkins/cscs/env-gcc-11.sh
.jenkins/cscs/env-gcc-7.sh
.jenkins/cscs/env-gcc-cuda.sh
.jenkins/lsu/env-clang-9.sh
.jenkins/lsu/env-gcc-8.sh
.jenkins/lsu/env-gcc-9-cuda-11.sh
.jenkins/lsu/env-gcc-9.sh
.jenkins/lsu/env-hipcc.sh
cmake/HPX_CheckCXXStandard.cmake
cmake/HPX_PerformCxxFeatureTests.cmake
docs/sphinx/manual/building_hpx.rst

Use HPX_WITH_CXX_STANDARD for controlling C++ version 

---

docs/sphinx/additional_material.rst

docs: add links to hpx recepies

---

libs/core/algorithms/include/hpx/parallel/algorithms/count.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/exclusive_scan.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/fill.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/find.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/inclusive_scan.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/reduce.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/remove.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/remove_copy.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/replace.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/transform_exclusive_scan.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/transform_inclusive_scan.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/count.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/exclusive_scan.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/fill.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/find.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/inclusive_scan.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/reduce.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/remove.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/remove_copy.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/replace.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/transform_exclusive_scan.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/transform_inclusive_scan.hpp

Issue #5653
- Added default template type parameters for the algorithms mentioned in P2248

Add default template type parameters for algorithms

---

docs/sphinx/manual/building_hpx.rst

Add the agreed most important CMake options in the Manual.

Add most important CMake options

---

.circleci/config.yml
.circleci/tests.unit1.targets
.circleci/tests.unit2.targets
libs/core/algorithms/include/hpx/parallel/datapar/loop.hpp
libs/core/algorithms/include/hpx/parallel/datapar/transfer.hpp
libs/core/algorithms/include/hpx/parallel/datapar/transform_loop.hpp
libs/core/algorithms/tests/unit/algorithms/CMakeLists.txt
libs/core/algorithms/tests/unit/block/CMakeLists.txt
libs/core/algorithms/tests/unit/container_algorithms/CMakeLists.txt
libs/core/algorithms/tests/unit/datapar_algorithms/CMakeLists.txt
libs/core/execution/include/hpx/execution/algorithms/transfer.hpp
libs/core/threading/tests/unit/tss.cpp

Attempting to fix CircleCI timeouts

---

libs/core/async_cuda/include/hpx/async_cuda/transform_stream.hpp
libs/core/async_mpi/include/hpx/async_mpi/transform_mpi.hpp
libs/core/execution/include/hpx/execution/algorithms/bulk.hpp
libs/core/execution/include/hpx/execution/algorithms/let_error.hpp
libs/core/execution/include/hpx/execution/algorithms/let_value.hpp
libs/core/execution/include/hpx/execution/algorithms/make_future.hpp
libs/core/execution/include/hpx/execution/algorithms/schedule_from.hpp
libs/core/execution/include/hpx/execution/algorithms/split.hpp
libs/core/execution/include/hpx/execution/algorithms/start_detached.hpp
libs/core/execution/include/hpx/execution/algorithms/sync_wait.hpp
libs/core/execution/include/hpx/execution/algorithms/then.hpp
libs/core/execution/include/hpx/execution/algorithms/when_all.hpp
libs/core/execution/tests/include/algorithm_test_utils.hpp
libs/core/execution_base/include/hpx/execution_base/any_sender.hpp
libs/core/execution_base/include/hpx/execution_base/receiver.hpp
libs/core/execution_base/include/hpx/execution_base/sender.hpp
libs/core/execution_base/tests/unit/any_sender.cpp
libs/core/execution_base/tests/unit/basic_receiver.cpp
libs/core/execution_base/tests/unit/basic_sender.cpp
libs/core/executors/include/hpx/executors/thread_pool_scheduler_bulk.hpp
libs/core/executors/tests/unit/thread_pool_scheduler.cpp

P2300R4 renames set_done to set_stopped

Renaming set_done to set_stopped (as per P2300)

---

docs/sphinx/api/public_api.rst
libs/core/algorithms/include/hpx/parallel/algorithms/ends_with.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/move.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/fill.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/is_heap.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/is_partitioned.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/move.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/partition.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/shift_left.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/shift_right.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/unique.hpp

Fix the missing links in API documentation

Fix missing links in Public API 

---

libs/core/datastructures/include/hpx/datastructures/detail/small_vector.hpp
libs/core/datastructures/tests/performance/CMakeLists.txt
libs/core/datastructures/tests/performance/small_vector_benchmark.cpp

Slight improvement of small_vector performance

---

libs/core/functional/tests/unit/contains_test.cpp

See https://github.com/STEllAR-GROUP/hpx/pull/5783#discussion_r806267727

Remove unneeded (and commented) tests

---

libs/full/collectives/include/hpx/collectives/detail/barrier_node.hpp
libs/full/collectives/src/detail/barrier_node.cpp

@biddisco could you please try whether this improves the situation?

Attempting to fix hangs in distributed barrier

---

libs/core/algorithms/include/hpx/parallel/algorithms/detail/advance_and_get_distance.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/for_each.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/reverse.hpp
libs/core/algorithms/include/hpx/parallel/task_group.hpp
libs/core/algorithms/include/hpx/parallel/util/detail/algorithm_result.hpp
libs/core/algorithms/include/hpx/parallel/util/foreach_partitioner.hpp
libs/core/datastructures/include/hpx/datastructures/tuple.hpp
libs/core/execution/include/hpx/execution/executors/execution_parameters.hpp
libs/core/execution/include/hpx/execution/executors/execution_parameters_fwd.hpp
libs/core/execution/include/hpx/execution/executors/num_cores.hpp
libs/core/execution/tests/unit/executor_parameters_dispatching.cpp
libs/core/executors/CMakeLists.txt
libs/core/executors/include/hpx/executors/execution_policy.hpp
libs/core/executors/include/hpx/executors/execution_policy_parameters.hpp
libs/core/executors/include/hpx/executors/parallel_executor.hpp
libs/core/futures/include/hpx/futures/future.hpp
libs/core/iterator_support/include/hpx/iterator_support/counting_iterator.hpp
libs/core/iterator_support/include/hpx/iterator_support/counting_shape.hpp
libs/core/iterator_support/include/hpx/iterator_support/iterator_adaptor.hpp
libs/core/iterator_support/include/hpx/iterator_support/iterator_facade.hpp
libs/core/iterator_support/include/hpx/iterator_support/iterator_range.hpp
libs/core/iterator_support/include/hpx/iterator_support/zip_iterator.hpp

- adding more constexpr and noexcept

Making sure num_cores is properly handled by parallel_executor

---

docs/sphinx/manual.rst
docs/sphinx/manual/building_hpx.rst
docs/sphinx/manual/cmake_variables.rst
docs/sphinx/manual/getting_hpx.rst
docs/sphinx/manual/prerequisites.rst

Restructure HPX build system section to multiple sections

Refactor manual sections

---

cmake/HPX_ForwardCacheVariables.cmake

- this is in support of https://github.com/STEllAR-GROUP/hpx/issues/5774

Avoid writing path and directories into HPXCacheVariables.cmake

---

cmake/HPX_SetupApex.cmake

This attempts to fix build problems in Phylanx. 
@khuck, @stevenrbrandt: please verify whether this overcomes the issues we're seeing.

Adding MPI as a dependency to APEX

---

libs/core/type_support/include/hpx/type_support/meta.hpp
libs/full/components/include/hpx/components/make_client.hpp

@diehlpk please check whether this helps with the CUDA issue you reported

Attempt to fix CUDA related OctoTiger problems

---

libs/core/type_support/include/hpx/type_support/meta.hpp
libs/full/async_colocated/tests/unit/async_continue_cb_colocated.cpp

@JiakunYan Could you please merge this with your PR to see if that fixes the test failure you were seeing, please?

Attempting to fix a test failure when using the LCI parcelport

---

libs/core/algorithms/include/hpx/parallel/algorithms/detail/accumulate.hpp
libs/core/algorithms/include/hpx/parallel/util/loop.hpp
libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/detail/reduce.hpp
libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/reduce.hpp

- fix problem in util::accumulate

Make sure reduction value is properly moved, when possible

---

examples/quickstart/1d_wave_equation.cpp
examples/quickstart/receive_buffer.cpp
libs/core/async_combinators/tests/unit/when_all.cpp
libs/core/command_line_handling_local/src/command_line_handling_local.cpp
libs/core/coroutines/include/hpx/coroutines/detail/coroutine_stackful_self.hpp
libs/core/execution/include/hpx/execution/detail/post_policy_dispatch.hpp
libs/core/execution/include/hpx/execution/detail/sync_launch_policy_dispatch.hpp
libs/core/execution_base/include/hpx/execution_base/this_thread.hpp
libs/core/executors/include/hpx/executors/dataflow.hpp
libs/core/executors/include/hpx/executors/detail/hierarchical_spawning.hpp
libs/core/executors/include/hpx/executors/parallel_executor.hpp
libs/core/futures/include/hpx/futures/traits/is_future.hpp
libs/core/resource_partitioner/tests/unit/suspend_thread_external.cpp
libs/core/runtime_local/src/runtime_local.cpp
libs/core/schedulers/include/hpx/schedulers/local_priority_queue_scheduler.hpp
libs/core/timing/include/hpx/timing/high_resolution_timer.hpp
libs/full/async_distributed/include/hpx/async_distributed/detail/async_implementations.hpp
libs/full/async_distributed/include/hpx/async_distributed/detail/async_unwrap_result_implementations.hpp
libs/full/collectives/tests/unit/CMakeLists.txt
libs/full/command_line_handling/src/command_line_handling.cpp
libs/full/runtime_distributed/src/runtime_distributed.cpp

This reapplies a couple of smaller changes that were initially planned as a part of #5467

Reapply flyby changes from #5467

---

cmake/templates/conf.py.in
docs/CMakeLists.txt
docs/sphinx/api.rst
docs/sphinx/api/full_api.rst
docs/sphinx/api/public_api.rst
docs/sphinx/extensions/sphinx-hpx.py

Fixes #
- Add links to C++ standard
- Split algorithms
- Correct namespaces

Fix Public API main page

---

CMakeLists.txt
cmake/HPX_SetupApex.cmake
cmake/HPX_SetupMPI.cmake
cmake/templates/HPXConfig.cmake.in
libs/core/version/CMakeLists.txt
tests/headers/CMakeLists.txt

Update the MPI cmake setup

---

.github/workflows/windows_debug.yml
.github/workflows/windows_release.yml
examples/transpose/transpose_serial_vector.cpp

Enable permissive- flag on Windows GitHub actions builders

---

libs/core/synchronization/include/hpx/synchronization/barrier.hpp
libs/full/collectives/tests/unit/barrier.cpp

Attempting to fix failing barrier test

---

libs/core/schedulers/include/hpx/schedulers/local_priority_queue_scheduler.hpp

- flyby: disable code not needed if stealing counts are disabled
@srinivasyadav18: could you please try whether this changes the parallelization performance characteristics on your ARM benchmarks?

Steal from neighboring NUMA domain only

---

libs/full/naming_base/include/hpx/naming_base/id_type.hpp

@stevenrbrandt this should fix the Phylanx compilation issues you were seeing.

Add missing compatibility layer for id_type::management_type values

---

libs/core/algorithms/include/hpx/algorithms/traits/segmented_iterator_traits.hpp
libs/full/segmented_algorithms/CMakeLists.txt
libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/exclusive_scan.hpp
libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/minmax.hpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_exclusive_scan.cpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_exclusive_scan2.cpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_inclusive_scan.cpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_inclusive_scan2.cpp

- flyby: add missing dependency to segmented_algorithm module

Attempting to fix timeouts of segmented iterator tests

---

docs/sphinx/manual/launching_and_configuring_hpx_applications.rst

Doc updates launching configuring

---

docs/sphinx/manual/starting_the_hpx_runtime.rst

Doc updates starting the hpx runtime

---

docs/sphinx/manual/hpx_runtime_and_resources.rst

Doc updates hpx runtime and resources

---

libs/core/batch_environments/CMakeLists.txt
libs/core/batch_environments/include/hpx/batch_environments/pjm_environment.hpp
libs/core/batch_environments/src/batch_environment.cpp
libs/core/batch_environments/src/pjm_environment.cpp

This batch environment is used on Fugaku

Adding support for the PJM batch environment

---

libs/core/datastructures/include/hpx/datastructures/serialization/tuple.hpp
libs/core/datastructures/tests/regressions/CMakeLists.txt
libs/core/datastructures/tests/regressions/non_default_constructible_tuple_5886.cpp
libs/core/serialization/include/hpx/serialization/detail/constructor_selector.hpp
libs/core/serialization/tests/regressions/CMakeLists.txt
libs/core/serialization/tests/regressions/non_default_constructible_5886.cpp

Fixing dangling reference in serialization of non-default constructible types

---

libs/core/lock_registration/include/hpx/lock_registration/detail/register_locks.hpp
libs/core/lock_registration/src/register_locks.cpp

fixes #5908 ?
(just creating this PR to get the diff easily)

Remove stuff which is defined in the header

---

docs/sphinx/api/public_api.rst
libs/core/algorithms/include/hpx/parallel/algorithms/adjacent_difference.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/adjacent_find.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/all_any_none.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/copy.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/destroy.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/ends_with.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/equal.hpp

Fixes and improves parallel algorithms documentation.

docs: fix & improve parallel algorithms documentation

---

.jenkins/lsu/env-hipcc.sh
libs/core/datastructures/tests/unit/CMakeLists.txt
libs/core/datastructures/tests/unit/small_vector.cpp

Fixes #
Adding boot to HIP builder

Add boost to hip builder

---

libs/core/algorithms/include/hpx/parallel/algorithms/copy.hpp
libs/core/lcos_local/include/hpx/lcos_local/and_gate.hpp
libs/full/collectives/include/hpx/collectives/all_gather.hpp
libs/full/collectives/include/hpx/collectives/all_reduce.hpp
libs/full/collectives/include/hpx/collectives/all_to_all.hpp
libs/full/collectives/include/hpx/collectives/broadcast.hpp
libs/full/collectives/include/hpx/collectives/create_communicator.hpp
libs/full/collectives/include/hpx/collectives/detail/communicator.hpp
libs/full/collectives/include/hpx/collectives/exclusive_scan.hpp
libs/full/collectives/include/hpx/collectives/gather.hpp
libs/full/collectives/include/hpx/collectives/inclusive_scan.hpp
libs/full/collectives/include/hpx/collectives/reduce.hpp
libs/full/collectives/include/hpx/collectives/scatter.hpp
libs/full/collectives/tests/unit/all_gather.cpp
libs/full/collectives/tests/unit/all_reduce.cpp
libs/full/collectives/tests/unit/all_to_all.cpp
libs/full/collectives/tests/unit/broadcast.cpp
libs/full/collectives/tests/unit/exclusive_scan_.cpp
libs/full/collectives/tests/unit/gather.cpp
libs/full/collectives/tests/unit/inclusive_scan_.cpp
libs/full/collectives/tests/unit/reduce.cpp
libs/full/collectives/tests/unit/scatter.cpp
libs/full/components/include/hpx/components/client_base.hpp

Fixes issues with potentially overlapping consecutive collective operations

Properly implement generation support for collective operations

---

libs/core/execution/CMakeLists.txt
libs/core/execution/include/hpx/execution/executors/adaptive_static_chunk_size.hpp
libs/core/execution/tests/unit/executor_parameters.cpp

I added adaptive_static_chunk_size to executors.

added adaptive_static_chunk_size

---

.circleci/config.yml
.github/workflows/linux_bors.yml
.github/workflows/linux_debug.yml
.github/workflows/linux_release_fetchcontent.yml
.github/workflows/linux_sanitizers.yml
tools/docker/Dockerfile

See https://github.com/STEllAR-GROUP/docker_build_env/pull/49 for context

ci: bump docker image version to 13

---

libs/core/execution_base/include/hpx/execution_base/traits/coroutine_traits.hpp
libs/core/execution_base/tests/unit/coroutine_traits.cpp

@SAtacker Please verify that I have not broken anything

Fixing inspect problems, adding missing header file

---

libs/full/components/include/hpx/components/get_ptr.hpp
libs/full/components/tests/regressions/CMakeLists.txt
libs/full/components/tests/regressions/multiple_inheritance_5964.cpp
libs/full/components_base/include/hpx/components_base/server/component_base.hpp

- flyby: fixing get_ptr<>(sync)
Fixes #5964
@kleinhenz would you be able to verify whether this fixes your problem?

Fixing component multiple inheritance

---

libs/core/algorithms/include/hpx/parallel/container_algorithms/merge.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/nth_element.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/partial_sort.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/partial_sort_copy.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/partition.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/reduce.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/remove.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/remove_copy.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/replace.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/reverse.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/rotate.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/search.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/set_difference.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/set_intersection.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/set_symmetric_difference.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/set_union.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/shift_left.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/shift_right.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/sort.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/stable_sort.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/starts_with.hpp
libs/core/algorithms/include/hpx/parallel/container_algorithms/swap_ranges.hpp

Fix existing and add missing documentation for ranges

Fix documentation for container algorithms

---

libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
libs/core/execution_base/tests/unit/completion_signatures.cpp

- One of the issues discussed is that the implementation currently
considers only those awaitable senders that have a natural coroutine
context i.e. they have a free/member co_await operator.
- Specs given in P2300 v5 does not consider modified coroutine contexts
i.e. using await transform

[P2300] Adapt get completion signatures for awaitable senders

---

libs/core/execution/include/hpx/execution/queries/read.hpp
libs/core/tag_invoke/include/hpx/functional/traits/is_invocable.hpp

flyby: adding hpx::is_nothrow_invocable

More work on execution::read

---

libs/core/asio/src/asio_util.cpp

See https://github.com/STEllAR-GROUP/hpx/issues/5903#issuecomment-1229425123 for the initial report.

Support IPV6 on command line for explicit network initialization

---

.jenkins/lsu/Jenkinsfile
.jenkins/lsu/env-gcc-12.sh
.jenkins/lsu/slurm-configuration-gcc-12.sh

Adding gcc/12 with boost/1.80 to jenkins/lsu

---

libs/core/algorithms/include/hpx/parallel/algorithms/partition.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/reverse.hpp
libs/core/algorithms/include/hpx/parallel/task_block.hpp
libs/core/algorithms/include/hpx/parallel/util/detail/algorithm_result.hpp
libs/core/algorithms/include/hpx/parallel/util/projection_identity.hpp
libs/core/algorithms/include/hpx/parallel/util/result_types.hpp

- Fix current documentation which cause warnings when building the docs and add new documentation when needed

Fix warnings when building docs 

---

libs/core/execution/include/hpx/execution/detail/future_exec.hpp
libs/core/execution/include/hpx/execution/executors/polymorphic_executor.hpp
libs/core/executors/include/hpx/executors/parallel_executor.hpp
libs/core/executors/include/hpx/executors/service_executors.hpp
libs/core/futures/include/hpx/futures/future.hpp
libs/core/futures/include/hpx/futures/future_fwd.hpp
libs/core/futures/include/hpx/futures/packaged_continuation.hpp
libs/core/futures/include/hpx/futures/traits/future_access.hpp
libs/core/timed_execution/include/hpx/timed_execution/timed_executors.hpp
libs/full/init_runtime/tests/unit/parcel_pool.cpp

- flyby: generalize infrastructure for future continuations
- flyby: modernize some future facilities

Attempting to fix timed executor API

---

docs/sphinx/api/public_api.rst
libs/core/algorithms/include/hpx/parallel/container_algorithms/fill.hpp
libs/core/async_base/include/hpx/async_base/async.hpp
libs/core/functional/include/hpx/functional/bind.hpp
libs/core/functional/include/hpx/functional/bind_front.hpp
libs/core/functional/include/hpx/functional/function.hpp
libs/core/functional/include/hpx/functional/move_only_function.hpp
libs/core/functional/include/hpx/functional/traits/is_bind_expression.hpp
libs/core/functional/include/hpx/functional/traits/is_placeholder.hpp
libs/core/futures/include/hpx/futures/future_fwd.hpp
libs/core/futures/include/hpx/futures/packaged_task.hpp
libs/core/futures/include/hpx/futures/promise.hpp
libs/core/synchronization/include/hpx/synchronization/condition_variable.hpp

Fix and add new documentation in Public API page

Fix missing documentation in Public API page

---

libs/full/components_base/include/hpx/components_base/component_type.hpp

Always exporting get_component_name implementations

---

docs/sphinx/api/public_api.rst
libs/core/assertion/include/hpx/assertion/source_location.hpp
libs/core/async_base/include/hpx/async_base/sync.hpp
libs/core/datastructures/include/hpx/datastructures/any.hpp
libs/core/datastructures/include/hpx/datastructures/serialization/serializable_any.hpp
libs/core/datastructures/include/hpx/datastructures/tuple.hpp
libs/core/futures/include/hpx/futures/future.hpp
libs/core/synchronization/include/hpx/synchronization/stop_token.hpp
libs/core/tag_invoke/include/hpx/functional/traits/is_invocable.hpp
libs/core/threading/include/hpx/threading/jthread.hpp
libs/core/threading/include/hpx/threading/thread.hpp

Add and fix current documentation of the public API

Add documentation Public API

---

docs/sphinx/manual/building_hpx.rst

Some minor fixes that I ran across while trying to build HPX on Windows and might help new users.
I summon @dimitraka @hkaiser. The former because I did not build the docs to see the results and might catch a miss just from the source.

Minor fixes on "How to build on Windows"

---

libs/core/command_line_handling_local/src/parse_command_line_local.cpp
libs/core/futures/include/hpx/futures/detail/future_data.hpp
libs/core/futures/include/hpx/futures/future.hpp
libs/core/init_runtime_local/include/hpx/init_runtime_local/init_runtime_local.hpp
libs/core/init_runtime_local/src/init_runtime_local.cpp
libs/full/actions/include/hpx/actions/register_action.hpp
libs/full/command_line_handling/src/parse_command_line.cpp
libs/full/init_runtime/include/hpx/hpx_init_impl.hpp
libs/full/init_runtime/include/hpx/hpx_init_params.hpp
libs/full/init_runtime/include/hpx/hpx_start_impl.hpp

- flyby: add more parameter checking to command line handling

Simplify startup code

---

libs/core/algorithms/CMakeLists.txt
libs/core/algorithms/include/hpx/parallel/algorithms/detail/replace.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/replace.hpp
libs/core/algorithms/include/hpx/parallel/datapar.hpp
libs/core/algorithms/include/hpx/parallel/datapar/replace.hpp
libs/core/algorithms/tests/unit/datapar_algorithms/CMakeLists.txt
libs/core/algorithms/tests/unit/datapar_algorithms/replace_copy_datapar.cpp
libs/core/algorithms/tests/unit/datapar_algorithms/replace_copy_if_datapar.cpp
libs/core/algorithms/tests/unit/datapar_algorithms/replace_datapar.cpp
libs/core/algorithms/tests/unit/datapar_algorithms/replace_if_datapar.cpp

Contributes to Fixing https://github.com/STEllAR-GROUP/hpx/issues/2333
- Moved replace algorithm implementation to detail/replace.hpp
- Added datapar replace implementation
- Added unit tests for datapar replace

Support for data-parallelism for replace, replace_if, replace_copy, replace_copy_if algorithms

---

libs/full/parcelset/src/parcelhandler.cpp

This fixes a performance regression if running on one locality if a parcel port is enabled that performs background work. @diehlpk this should resolve the issue you reported.

Avoid performing parcel related background work if networking is disabled

---

libs/core/pack_traversal/include/hpx/pack_traversal/detail/pack_traversal_impl.hpp
libs/core/pack_traversal/tests/regressions/CMakeLists.txt
libs/core/pack_traversal/tests/regressions/unwrapping_nullary_6045.cpp

Support using unwrapping with nullary function objects

---

libs/core/affinity/include/hpx/affinity/affinity_data.hpp
libs/core/affinity/src/affinity_data.cpp
libs/core/algorithms/include/hpx/parallel/algorithms/rotate.hpp
libs/core/execution/include/hpx/execution/detail/execution_parameter_callbacks.hpp
libs/core/execution/src/execution_parameter_callbacks.cpp
libs/core/executors/include/hpx/executors/fork_join_executor.hpp
libs/core/executors/include/hpx/executors/thread_pool_scheduler_bulk.hpp
libs/core/resource_partitioner/include/hpx/resource_partitioner/detail/partitioner.hpp
libs/core/resource_partitioner/src/detail_partitioner.cpp
libs/core/runtime_local/include/hpx/runtime_local/runtime_handlers.hpp
libs/core/runtime_local/src/runtime_handlers.cpp

- flyby: fixing flaws in fork_join_executor

Adding pu_mask to thread_pool_bulk_scheduler

---

libs/core/execution_base/tests/unit/coroutine_utils.cpp

Fix coroutine test for clang

---

libs/core/datastructures/include/hpx/datastructures/detail/small_vector.hpp

See: https://github.com/martinus/svector/commit/63ea333596b4d30fa8d467adfffefead8510f7a0#commitcomment-88645480

Minor fix in small_vector (from upstream)

---

libs/core/async_combinators/include/hpx/async_combinators/future_wait.hpp
libs/core/execution/include/hpx/execution/algorithms/detail/predicates.hpp
libs/core/futures/include/hpx/futures/packaged_continuation.hpp
libs/full/async_distributed/include/hpx/async_distributed/base_lco_with_value.hpp
libs/full/runtime_components/tests/unit/components/action_invoke_no_more_than.hpp

Using if constexpr instead of tag-dispatching, where possible

---

cmake/tests/builtin_integer_pack.cpp
cmake/tests/builtin_make_integer_seq.cpp
cmake/tests/builtin_type_pack_element.cpp
libs/core/format/include/hpx/util/from_string.hpp
libs/core/iterator_support/include/hpx/iterator_support/traits/is_iterator.hpp
libs/core/iterator_support/tests/unit/is_iterator.cpp

- flyby: modernize is_iterator traits and friends
Working towards #5497

Use C++17 static_assert where possible

---

components/iostreams/tests/regressions/lost_output_2236.cpp
components/process/include/hpx/components/process/util/posix/executor.hpp
components/process/include/hpx/components/process/util/windows/executor.hpp
libs/core/algorithms/include/hpx/parallel/algorithms/for_loop.hpp
libs/core/algorithms/include/hpx/parallel/datapar/zip_iterator.hpp
libs/core/algorithms/include/hpx/parallel/util/prefetching.hpp
libs/core/async_combinators/include/hpx/async_combinators/detail/throw_if_exceptional.hpp
libs/core/async_combinators/include/hpx/async_combinators/wait_some.hpp
libs/core/async_combinators/include/hpx/async_combinators/when_any.hpp
libs/core/async_combinators/include/hpx/async_combinators/when_some.hpp
libs/core/datastructures/include/hpx/datastructures/member_pack.hpp
libs/core/datastructures/include/hpx/datastructures/serialization/tuple.hpp
libs/core/datastructures/include/hpx/datastructures/tuple.hpp
libs/core/execution/include/hpx/execution/executors/execution_parameters.hpp
libs/core/iterator_support/include/hpx/iterator_support/zip_iterator.hpp
libs/core/serialization/include/hpx/serialization/serialization_fwd.hpp
libs/core/serialization/include/hpx/serialization/serialize.hpp
libs/core/serialization/include/hpx/serialization/std_tuple.hpp
libs/full/checkpoint_base/include/hpx/checkpoint_base/checkpoint_data.hpp

- flyby: fix left-over problems from namespace change
working towards resolving #5497

Replace artificial sequencing with fold expressions

---

CMakeLists.txt
libs/core/coroutines/include/hpx/coroutines/thread_id_type.hpp
libs/core/datastructures/tests/unit/dynamic_bitset4.cpp
libs/core/format/include/hpx/modules/format.hpp
libs/core/format/src/format.cpp
libs/core/format/tests/unit/format.cpp
libs/core/logging/include/hpx/logging/level.hpp
libs/core/logging/include/hpx/logging/manipulator.hpp
libs/core/logging/include/hpx/logging/message.hpp
libs/core/logging/src/level.cpp
libs/full/actions_base/include/hpx/actions_base/basic_action.hpp
libs/full/actions_base/include/hpx/actions_base/component_action.hpp
libs/full/actions_base/include/hpx/actions_base/plain_action.hpp

Working towards #5497 and #3440

Replace boost::string_ref with std::string_view

---

libs/core/pack_traversal/include/hpx/pack_traversal/detail/pack_traversal_async_impl.hpp
libs/core/pack_traversal/include/hpx/pack_traversal/detail/pack_traversal_impl.hpp

Using more fold expressions

---

.circleci/config.yml
.github/workflows/linux_bors.yml
.github/workflows/linux_debug.yml
.github/workflows/linux_release_fetchcontent.yml
.github/workflows/linux_sanitizers.yml
cmake/templates/conf.py.in
docs/sphinx/_static/custom.css
docs/sphinx/contributing/documentation.rst

- Change the font color of the code text
- Add an extension for the copy button. The copy button appears at the top-right of a code block.

Enhance the formatting of the documentation 

---

libs/core/algorithms/include/hpx/parallel/util/adapt_placement_mode.hpp
libs/core/algorithms/include/hpx/parallel/util/adapt_sharing_mode.hpp
libs/core/algorithms/include/hpx/parallel/util/adapt_thread_priority.hpp
libs/core/algorithms/include/hpx/parallel/util/foreach_partitioner.hpp
libs/core/algorithms/include/hpx/parallel/util/partitioner.hpp
libs/core/algorithms/include/hpx/parallel/util/partitioner_with_cleanup.hpp

Fixing performance regressions

---

libs/core/execution/include/hpx/execution/algorithms/as_sender.hpp
libs/core/execution/include/hpx/execution/algorithms/bulk.hpp
libs/core/execution/include/hpx/execution/algorithms/just.hpp
libs/core/execution/include/hpx/execution/algorithms/keep_future.hpp
libs/core/execution/include/hpx/execution/algorithms/let_error.hpp
libs/core/execution/include/hpx/execution/algorithms/let_stopped.hpp
libs/core/execution/include/hpx/execution/algorithms/let_value.hpp
libs/core/execution/include/hpx/execution/algorithms/run_loop.hpp
libs/core/execution/include/hpx/execution/algorithms/schedule_from.hpp
libs/core/execution/include/hpx/execution/algorithms/split.hpp
libs/core/execution/include/hpx/execution/algorithms/sync_wait.hpp
libs/core/execution/include/hpx/execution/algorithms/then.hpp
libs/core/execution/include/hpx/execution/algorithms/when_all.hpp
libs/core/execution/include/hpx/execution/algorithms/when_all_vector.hpp
libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
libs/core/execution_base/include/hpx/execution_base/get_env.hpp
libs/core/execution_base/include/hpx/execution_base/traits/coroutine_traits.hpp
libs/core/execution_base/tests/include/coroutine_task.hpp
libs/core/execution_base/tests/unit/basic_sender.cpp
libs/core/execution_base/tests/unit/coroutine_traits.cpp
libs/core/execution_base/tests/unit/coroutine_utils.cpp
libs/core/futures/include/hpx/futures/traits/detail/future_await_traits.hpp
libs/core/type_support/include/hpx/type_support/identity.hpp
libs/core/type_support/include/hpx/type_support/meta.hpp

* Remove obsolete commment
* Fix redundant control flow

[P2300] execution: Cleanup coroutines integration and improve ADL isolation

---

libs/full/collectives/src/detail/barrier_node.cpp

Use LRT_ instead of LAPP_ logging in barrier implementation

---

cmake/HPX_GeneratePackage.cmake

Do not generate hpxcxx if support for pkgconfig was disabled

---

docs/sphinx/manual/writing_single_node_hpx_applications.rst
examples/quickstart/CMakeLists.txt
examples/quickstart/for_each_docs.cpp
examples/quickstart/mutex_docs.cpp
examples/quickstart/shared_mutex.cpp
libs/core/futures/include/hpx/futures/future.hpp

- Remove locks and unlocks mutexes and update corresponding documentation
- Add future functions to futures table
- Document future functions
- Remove old comments

Fix page `Writing single-node applications`

---

components/performance_counters/io/src/io_counters.cpp

fixed deprecated boost header warning

updated deprecated headers

---

libs/core/synchronization/include/hpx/synchronization/barrier.hpp
libs/core/synchronization/src/local_barrier.cpp

Attempting to fix problems in barrier causing hangs

---

docs/sphinx/manual.rst
docs/sphinx/manual/migration_guide.rst
docs/sphinx/quickstart.rst

Added instructions about OpenMP

Add migration guide to manual

---

libs/core/command_line_handling_local/src/command_line_handling_local.cpp
libs/core/command_line_handling_local/src/parse_command_line_local.cpp
libs/core/coroutines/include/hpx/coroutines/detail/context_impl.hpp
libs/core/coroutines/src/detail/context_posix.cpp
libs/core/topology/src/topology.cpp

Consistently #include unistd.h for _POSIX_VERSION

---

.jenkins/lsu/env-gcc-11.sh
examples/quickstart/custom_serialization.cpp
libs/full/agas/src/addressing_service.cpp
libs/full/runtime_distributed/include/hpx/runtime_distributed/migrate_component.hpp
libs/full/runtime_distributed/src/runtime_distributed.cpp

Fixes #6287
- this adds the missing #include
@G-071 please verify whether this fixes your issues.

Re-enable compiling with HPX_WITH_NETWORKING=OFF

---

libs/core/init_runtime_local/include/hpx/init_runtime_local/init_runtime_local.hpp
libs/core/init_runtime_local/src/init_runtime_local.cpp
libs/core/init_runtime_local/tests/unit/CMakeLists.txt
libs/core/init_runtime_local/tests/unit/on_finalize.cpp
libs/full/init_runtime/CMakeLists.txt
libs/full/init_runtime/src/hpx_init.cpp

This is needed for the hpxMP project

Adding user supplied on_finalize

---

libs/core/coroutines/include/hpx/coroutines/detail/posix_utility.hpp

Fixing error message about use_guard_pages

---

CMakeLists.txt

Updating APEX default version to v2.6.3
- see changelist here: https://github.com/UO-OACISS/apex/releases/tag/v2.6.3

Updating APEX default version to v2.6.3

---

libs/full/init_runtime/include/hpx/hpx_init_impl.hpp
libs/full/init_runtime/include/hpx/hpx_start_impl.hpp
libs/full/init_runtime/include/hpx/init_runtime/detail/run_or_start.hpp
libs/full/init_runtime/src/hpx_init.cpp

Fixing linker problem on FreeBSD

---

libs/full/collectives/include/hpx/collectives/all_gather.hpp
libs/full/collectives/include/hpx/collectives/all_reduce.hpp
libs/full/collectives/include/hpx/collectives/all_to_all.hpp
libs/full/collectives/include/hpx/collectives/broadcast.hpp
libs/full/collectives/include/hpx/collectives/create_communicator.hpp
libs/full/collectives/include/hpx/collectives/detail/communicator.hpp
libs/full/collectives/include/hpx/collectives/exclusive_scan.hpp
libs/full/collectives/include/hpx/collectives/gather.hpp
libs/full/collectives/include/hpx/collectives/inclusive_scan.hpp
libs/full/collectives/include/hpx/collectives/reduce.hpp
libs/full/collectives/include/hpx/collectives/scatter.hpp

- flyby: fixing JeMalloc integration for dependent projects

Adding basic logging to collective operations

---

.github/SUPPORT.md

Changing support.md to add discord link

changed chat link to discord

---

libs/core/execution_base/include/hpx/execution_base/traits/is_executor_parameters.hpp

@kmoham6 this should resolve the issues you were seeing

Enable using std::reference_wrapper with executor parameters

---

cmake/templates/conf.py.in

Fix broken links in docs: PDF, Single HTML page, Dependency report

---

libs/core/functional/include/hpx/functional/experimental/scope_exit.hpp
libs/core/functional/include/hpx/functional/experimental/scope_fail.hpp
libs/core/functional/include/hpx/functional/experimental/scope_success.hpp

Fixes #6417
@JiakunYan could you please check if this fixes your issues?

Working around nvcc problems to use CTAD

---

docs/sphinx/index.rst
docs/sphinx/manual/troubleshooting.rst
docs/sphinx/quickstart.rst

- Update communication info for docs
- Add notes for CMake error for missing target HPX::iostreams_component

Minor documentation fixes

---

docs/sphinx/manual/prerequisites.rst

Towards resolving comments in https://github.com/STEllAR-GROUP/hpx/issues/6298

Update supported platforms of Manual/Prerequisites page

---

.github/workflows/macos_debug.yml
.github/workflows/macos_debug_fetch_boost.yml
.github/workflows/macos_debug_fetch_hwloc.yml

Fixes Mac OS GitHub Actions build.
- Remove the usage of workaround for a prior configuration problem.
- Do not upgrade softwares with brew, as it needs latest macOS to upgrade **xcbeautify**.

Fix mac os github actions

---

libs/core/command_line_handling_local/src/command_line_handling_local.cpp
libs/full/command_line_handling/src/command_line_handling.cpp

@diehlpk This should take care of the problem we discussed

Make sure that --hpx:ini log settings take effect

---

libs/core/algorithms/CMakeLists.txt
libs/core/algorithms/tests/unit/algorithms/CMakeLists.txt

Fixes the current build issues on master
@gonidelis please review

Fixing distance test

---

libs/core/concurrency/include/hpx/concurrency/detail/tagged_ptr_ptrcompression.hpp

Fixes for bit_cast on 32bit systems

---

libs/core/include_local/include/hpx/compute.hpp.in
libs/full/include/include/hpx/compute.hpp
libs/full/include/include/hpx/include/compute.hpp

In response to https://github.com/E4S-Project/testsuite/issues/75. @wspear, how can I test whether this fixes the issue?

Attempt to fixing the E4S HPX tests

---

libs/full/parcelport_mpi/include/hpx/parcelport_mpi/sender_connection.hpp

Fix a bug in mpi parcelport due to the change of #6580.
Thanks to @m-diers for reporting the bug.

mpi pp: fix transmission chunk send

---

libs/core/algorithms/include/hpx/parallel/algorithms/detail/spin_sort.hpp

Fixes 
Unqualified calls to insertion_sort
Based on issue 6634
PS - my first contribution here!

Fixed issue 6634: Unqualified calls to insertion_sort

---

.circleci/config.yml
libs/core/algorithms/tests/unit/container_algorithms/CMakeLists.txt
libs/core/algorithms/tests/unit/container_algorithms/is_partitioned_async_range.cpp

CircleCI tests started to time out, this increases the timeout limits for those.

Increase timeouts for CircleCI tests

---

libs/core/iterator_support/include/hpx/iterator_support/iterator_facade.hpp
libs/core/iterator_support/include/hpx/iterator_support/traits/is_iterator.hpp
libs/core/iterator_support/tests/include/hpx/iterator_support/tests/iterator_tests.hpp
libs/core/iterator_support/tests/regressions/CMakeLists.txt
libs/core/iterator_support/tests/regressions/custom_iterator_category_6640.cpp

Allowing to use custom iterator tags with iterator_facade

---

.circleci/config.yml
libs/full/parcelset/tests/regressions/CMakeLists.txt
libs/full/parcelset/tests/regressions/very_big_tchunk.cpp

add a new test to cover the bug fixed by #6619
Split #6619 into two PRs to speed-up its merging.

new test: very big tchunk

---

libs/core/io_service/include/hpx/io_service/io_service_pool.hpp
libs/core/io_service/src/io_service_pool.cpp

Remove the use of deprecated asio::io_context::work

---

libs/core/batch_environments/CMakeLists.txt
libs/core/batch_environments/include/hpx/batch_environments/flux_environment.hpp
libs/core/batch_environments/src/batch_environment.cpp
libs/core/batch_environments/src/flux_environment.cpp

Fixes #6616
This is based on the information found here: https://github.com/flux-framework/flux-core/pull/5024/files

Adding support for the Flux job scheduling environment

---

libs/core/command_line_handling_local/cmake/HPX_SetupJSON.cmake

- this fixes problems when using CMake V4

Bump required version of JSON library

---

README.rst

Mention the HPX book in the readmd.md

Mention the HPX book

---

libs/core/iterator_support/include/hpx/iterator_support/detail/minimum_category.hpp

- This allows for interator categories derived from the standard ones
Fixes #6691

Better implementation of minimal_category

---

libs/core/type_support/include/hpx/type_support/generator.hpp

Adding missing ';'

---

.jenkins/lsu/Jenkinsfile
.jenkins/lsu/env-clang-19.sh
.jenkins/lsu/env-clang-20.sh
.jenkins/lsu/slurm-configuration-clang-19.sh
.jenkins/lsu/slurm-configuration-clang-20.sh
libs/core/algorithms/tests/unit/algorithms/all_of.cpp
libs/core/algorithms/tests/unit/algorithms/any_of.cpp
libs/core/algorithms/tests/unit/algorithms/none_of.cpp
libs/core/algorithms/tests/unit/container_algorithms/all_of_range.cpp
libs/core/algorithms/tests/unit/container_algorithms/any_of_range.cpp
libs/core/algorithms/tests/unit/container_algorithms/none_of_range.cpp
libs/core/algorithms/tests/unit/datapar_algorithms/all_of_datapar.cpp
libs/core/algorithms/tests/unit/datapar_algorithms/any_of_datapar.cpp
libs/core/algorithms/tests/unit/datapar_algorithms/none_of_datapar.cpp
libs/core/command_line_handling_local/cmake/HPX_SetupJSON.cmake
libs/core/concepts/include/hpx/concepts/has_member_xxx.hpp
libs/core/lcos_local/include/hpx/lcos_local/trigger.hpp
libs/core/type_support/include/hpx/type_support/generator.hpp
libs/core/type_support/include/hpx/type_support/is_contiguous_iterator.hpp
libs/core/type_support/tests/unit/is_contiguous_iterator.cpp
libs/full/parcelport_mpi/include/hpx/parcelport_mpi/receiver_connection.hpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_all_of1.cpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_all_of2.cpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_any_of1.cpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_any_of2.cpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_none1.cpp
libs/full/segmented_algorithms/tests/unit/partitioned_vector_none2.cpp

- llvm/19 and llvm/20
- boost/1.87
- cmake/4 to the llvm/20 builds

Adding llvm/19 and 20 and cmake/4 Jenkins

---

cmake/HPX_AddModule.cmake

Making sure .hpp.in files are not being installed

---

libs/core/resource_partitioner/src/detail_partitioner.cpp
libs/core/runtime_local/include/hpx/runtime_local/custom_exception_info.hpp
libs/core/runtime_local/src/custom_exception_info.cpp
libs/core/runtime_local/src/runtime_local.cpp
libs/core/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp
libs/core/threadmanager/include/hpx/modules/threadmanager.hpp
libs/core/threadmanager/src/threadmanager.cpp
libs/full/performance_counters/src/manage_counter_type.cpp
libs/full/runtime_distributed/src/runtime_distributed.cpp
libs/full/runtime_distributed/tests/regressions/CMakeLists.txt
libs/full/runtime_distributed/tests/regressions/shutdown_hang_6699.cpp

- properly report `e.what()` for std::exception
Fixes #6699
@JiakunYan please verify if this resolves your issue

Attempting to fix shutdown hang on exception_info

---

libs/core/execution/include/hpx/execution/algorithms/as_sender.hpp
libs/core/execution/include/hpx/execution/algorithms/bulk.hpp
libs/core/execution/include/hpx/execution/algorithms/keep_future.hpp
libs/core/execution/include/hpx/execution/algorithms/make_future.hpp
libs/core/execution/include/hpx/execution/algorithms/when_all.hpp
libs/core/execution/include/hpx/execution/algorithms/when_all_vector.hpp
libs/core/execution_base/include/hpx/execution_base/any_sender.hpp
libs/core/execution_base/include/hpx/execution_base/completion_scheduler.hpp
libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp

This covers the parts of the code that will be included in 2.0

Simplify code by using NS aliases

---

libs/core/resource_partitioner/src/detail_partitioner.cpp
libs/full/agas/src/addressing_service.cpp

Fixing some of the reported linker warnings

---

.jenkins/lsu/Jenkinsfile
.jenkins/lsu/env-gcc-15.sh
.jenkins/lsu/slurm-configuration-gcc-15.sh
cmake/HPX_SetupLCI.cmake
cmake/tests/stable_inplace_merge.cpp
libs/core/algorithms/tests/performance/benchmark_nth_element.cpp
libs/core/algorithms/tests/performance/benchmark_nth_element_parallel.cpp

Added gcc/15 + boost/1.87 to the LSU/Jenkins

Adding gcc/15 to jenkins

---

.github/workflows/linux_debug.yml
.github/workflows/macos_debug.yml
.github/workflows/windows_debug_vs2022.yml
components/iostreams/src/server/output_stream.cpp
examples/async_io/async_io_low_level.cpp
libs/core/asio/include/hpx/asio/asio_util.hpp
libs/core/asio/src/asio_util.cpp
libs/core/executors/src/service_executors.cpp
libs/core/io_service/include/hpx/io_service/io_service_pool.hpp
libs/core/io_service/src/io_service_pool.cpp
libs/core/runtime_local/src/pool_timer.cpp
libs/full/parcelport_gasnet/src/parcelport_gasnet.cpp
libs/full/parcelport_lci/src/parcelport_lci.cpp
libs/full/parcelport_mpi/src/parcelport_mpi.cpp

Removing deprecated Asio features

---

.circleci/config.yml
.circleci/tests.examples1.targets
.circleci/tests.examples2.targets
.jenkins/lsu/env-clang-20.sh
.jenkins/lsu/env-gcc-15.sh

Adding Boost 1.88 to LSU Jenkins

Adding Boost 1.88

---

libs/core/type_support/include/hpx/type_support/is_contiguous_iterator.hpp
libs/core/type_support/tests/unit/CMakeLists.txt
libs/core/type_support/tests/unit/is_contiguous_iterator.cpp

Fixing is_known_contiguous_iterator support for string
