STEllAR-GROUP/hpx

hpx/components/vector/distribution_policy.hpp, hpx/components/vector/vector.hpp, tests/performance/local/vector_foreach.cpp, tests/unit/components/vector.cpp, tests/unit/components/vector_copy.cpp, tests/unit/components/vector_handle_values.cpp, tests/unit/components/vector_move.cpp, tests/unit/components/vector_transform_reduce.cpp
The distribution policies we've had were not compatible with the iterator model we use. We have to come back to the possibility of having index manipulation schemes at some point. For now, let's remove the half-working attempt of introducing those.
=> Removing various distribution policies for hpx::vector

hpx/components/vector/vector_segmented_iterator.hpp, hpx/parallel/algorithms/copy.hpp, hpx/parallel/algorithms/detail/dispatch.hpp, hpx/parallel/algorithms/remote/dispatch.hpp, hpx/parallel/execution_policy.hpp, hpx/parallel/segmented_algorithms/copy.hpp, hpx/traits/segmented_iterator_traits.hpp, hpx/util/zip_iterator.hpp, tests/unit/components/vector_copy.cpp
This adds the implementation of the segmented `parallel::copy` algorithm. It includes a couple of refinements to the iterators as exposed by `hpx::vector`.
=> Segmented copy

hpx/parallel/algorithms/search.hpp, hpx/parallel/util/loop.hpp, tests/regressions/CMakeLists.txt, tests/regressions/parallel/CMakeLists.txt, tests/regressions/parallel/search_zerolength.cpp
Changed search.hpp to return the first iterator if the search iterators are the same.
=>  Modifying parallel search algorithm for zero length searches

cmake/HPX_SetupTarget.cmake, hpx/lcos/when_all.hpp
With CMake 3.1.0 I get the following warning when building a code that uses HPX:
CMake Warning (dev) at /home/gentryx/local_install/lib/cmake/hpx/HPX_SetupTarget.cmake:134 (if):
Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
Quoted variables like "COMPONENT" will no longer be dereferenced when the
policy is set to NEW.  Since the policy is not set the OLD behavior will be
used.
Call Stack (most recent call first):
/home/gentryx/local_install/lib/cmake/hpx/HPX_AddExecutable.cmake:143 (hpx_setup_target)
src/examples/gameoflife_hpx/CMakeLists.txt:6 (add_hpx_executable)
This warning is for project developers.  Use …
=> resolved warning in CMake 3.1 and newer

cmake/HPX_SetupTarget.cmake
Hartmut: you were right and I was wrong. We do need to check for older versions, policies are not forward-compatible. I've tested this with 2.8.12 and 3.1.0.
=> fix for CMake versions prior to 3.1

docs/CMakeLists.txt, docs/hpx.idx, docs/manual/existing_performance_counters.qbk, hpx/components/component_storage/migrate_from_storage.hpp, hpx/components/component_storage/migrate_to_storage.hpp, hpx/components/component_storage/server/migrate_from_storage.hpp, hpx/components/component_storage/server/migrate_to_storage.hpp, hpx/error.hpp, hpx/runtime/agas/addressing_service.hpp, hpx/runtime/agas/interface.hpp, hpx/runtime/agas/namespace_action_code.hpp, hpx/runtime/agas/response.hpp, hpx/runtime/agas/server/primary_namespace.hpp, hpx/runtime/components/migrate_component.hpp, hpx/runtime/components/server/migrate_component.hpp, hpx/runtime/get_ptr.hpp, hpx/runtime/parcelset/parcelhandler.hpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/interface.cpp, src/runtime/agas/request.cpp, src/runtime/agas/response.cpp, src/runtime/agas/server/component_namespace_server.cpp, src/runtime/agas/server/locality_namespace_server.cpp, src/runtime/agas/server/primary_namespace_server.cpp, src/runtime/agas/server/route.cpp, src/runtime/agas/server/symbol_namespace_server.cpp, src/runtime/agas/stubs/component_namespace_stubs.cpp, src/runtime/agas/stubs/primary_namespace_stubs.cpp, src/runtime/applier/applier.cpp, tests/unit/components/migrate_component_to_storage.cpp
This PR adds a new AGAS API: `hpx::agas::begin_migration` and `hpx::agas::end_migration`. These functions make sure that no address resolution proceeds while a migration operation is in flight. All address resolution requests will be deferred until `end_migration` is called.
This PR also adapts the existing API functions `hpx::components::migrate`, `hpx::components::migrate_to_storage`, and `hpx::components::migrate_from_storage` to use the new AGAS API.
Overall, this is the first step to make the process of migrating objects transparent to the user (see #559).
=> Towards safer migration

hpx/parallel/algorithms/copy.hpp, hpx/parallel/algorithms/exclusive_scan.hpp, hpx/parallel/algorithms/find.hpp, hpx/parallel/algorithms/inclusive_scan.hpp, hpx/parallel/algorithms/mismatch.hpp, hpx/parallel/algorithms/transform_exclusive_scan.hpp, hpx/parallel/algorithms/transform_inclusive_scan.hpp, tests/regressions/parallel/scan_different_inits.cpp, tests/regressions/parallel/scan_shortlength.cpp
Applied fix to inclusive_scan, exclusive_scan, transform_inclusive_scan, transform_exclusive_scan to work with different intial values. Also made quick changes to copy and find.
=> Parallel scan algorithms with different initial values

hpx/parallel/segmented_algorithms/detail/dispatch_gcc46.hpp
The path for dispatch_gcc46.hpp while PP iterating is incorrect and
appears to be a legacy location for the file. The filename is adjusted
to refer to the new location.
=> Correct directory for dispatch_gcc46.hpp iteration

docs/manual/existing_performance_counters.qbk, hpx/runtime/agas/server/component_namespace.hpp, hpx/runtime/agas/server/locality_namespace.hpp, hpx/runtime/agas/server/primary_namespace.hpp, hpx/runtime/agas/server/symbol_namespace.hpp, src/performance_counters/counter_creators.cpp, src/performance_counters/registry.cpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/server/component_namespace_server.cpp, src/runtime/agas/server/locality_namespace_server.cpp, src/runtime/agas/server/primary_namespace_server.cpp, src/runtime/agas/server/symbol_namespace_server.cpp
this also unifies certain performance counter names (related to the AGAS cache) and improves error reporting for missing performance counters
=> Fixed problems with performance counters in distributed

hpx/async.hpp, hpx/hpx_fwd.hpp, hpx/include/async.hpp, hpx/lcos/async_callback.hpp, hpx/lcos/async_callback_fwd.hpp, hpx/lcos/async_colocated_callback.hpp, hpx/lcos/async_colocated_callback_fwd.hpp, hpx/lcos/async_continue_callback.hpp, hpx/lcos/async_continue_callback_fwd.hpp, hpx/lcos/packaged_action.hpp, tests/unit/lcos/CMakeLists.txt, tests/unit/lcos/async_cb_remote.cpp, tests/unit/lcos/async_continue_cb.cpp
These versions are available for actions only, not for purely local operations.
This is per our discussion on IRC this morning. The new overloads will help to manage the lifetime for arguments which are zero-copied. The callback will be invoked once it is safe to overwrite the memory of the arguments.
I decided to stick with callback functions instead of the suggested additional future to minimize the overheads introduced by this change. If a future is required/desired the user can easily pass a packaged_task (or similar) as the callback function object.
=> Adding async_cb, async_continue_cb, and async_colocated_cb. 

hpx/hpx_init_impl.hpp, src/hpx_init.cpp, tests/regressions/CMakeLists.txt, tests/regressions/commandline_options_1437.cpp
This will fix #1437: hpx::init() should strip HPX-related flags from argv
=> Always stripping HPX command line arguments before executing start function

hpx/runtime/actions/action_support.hpp, hpx/runtime/actions/transfer_action.hpp, hpx/runtime/parcelset/encode_parcels.hpp, hpx/runtime/parcelset/parcel.hpp, hpx/traits/type_size.hpp, hpx/util/serialize_buffer.hpp, tests/performance/local/serialization_overhead.cpp, tests/unit/util/zero_copy_serialization.cpp
This allows specializations for classes like serialization_buffer
to return a different size depending on whether zero_copy is
enabled or not.
=> When serializing, pass archive flags to traits::get_type_size

hpx/lcos/async.hpp, hpx/lcos/async_callback.hpp, hpx/lcos/broadcast.hpp, hpx/lcos/local/channel.hpp, hpx/lcos/local/conditional_trigger.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/lcos/reduce.hpp, hpx/runtime/components/server/runtime_support.hpp, hpx/traits/acquire_future.hpp, hpx/util/coroutine/detail/self.hpp, hpx/util/unwrapped.hpp, src/runtime/agas/addressing_service.cpp
These std::moves prevent compiler from using NRVO.
In case it's difficult for compiler to use RVO (e.g. several return statements), move constructor will be used anyways.
=> removed harmful std::moves from return statements

hpx/runtime/components/new.hpp, hpx/runtime/serialization/detail/pointer.hpp, hpx/runtime/serialization/input_archive.hpp, hpx/runtime/serialization/serialization_fwd.hpp, tests/unit/util/stencil3_iterator.cpp
This PR solves a problem with using the intel compiler series with a standard library provided by gcc 4.4.x standard libraries.
=> Fixing problems with the Intel compiler using a GCC 4.4 std library

src/util/command_line_handling.cpp
Exit application on `--hpx:version`/`-v` and `--hpx:info`  after printing the respective information
=> Exit application on --hpx:version/-v and --hpx:info 

hpx/util/logging/format/destination/rolling_file.hpp, src/util/init_ini_data.cpp, src/util/runtime_configuration.cpp
This fixes #1502: boost::filesystem::exists throws unexpected exception
=> Making sure boost::filesystem::exists() does not throw

hpx/util/batch_environments/pbs_environment.hpp
Added "#include <boost/format.hpp>" to pbs_environment.hpp, would not compile on my computer without it.
=> Adding #include - would not compile without this

hpx/util/logging/format/destination/rolling_file.hpp, src/util/init_ini_data.cpp, src/util/runtime_configuration.cpp, tests/regressions/CMakeLists.txt, tests/regressions/dynamic_counters_loaded_1508.cpp
- this was recently introduced by a different patch
- add test to avoid similar problems in the future
This fixes #1508
=> Correct problems with loading dynamic components

hpx/util/coroutine/detail/context_posix.hpp, hpx/util/coroutine/detail/posix_utility.hpp
This patch fixes some copy and past mistakes in the posix context switching facilities.
=> Fixing Posix context

hpx/runtime/serialization/detail/polymorphic_intrusive_factory.hpp
This patch fixes UB when a class is registered with our serialization framework.
=> Fixing UB whil registering polymorphic classes for serialization

hpx/util/unwrapped.hpp, tests/regressions/util/CMakeLists.txt, tests/regressions/util/unwrapped_1528.cpp
The implementation tried to instantiate `tuple<void>`, which was a synonym for `tuple<>` under the faux variadic implementation but is a hard error with true variadics. Fixes #1528
=> Fix unwrapped issue with future ranges of void type

hpx/runtime/serialization/complex.hpp, tests/unit/serialization/CMakeLists.txt, tests/unit/serialization/serialization_complex.cpp
Add serialization support for `std::complex<T>`
Includes drive-by fix for missing tests in CMake file.
=> Serialization complex

docs/whats_new.qbk
The link to the mailing list archive entry describing the change from Boost.Serialization has been updated.  The previous link was not accessible without signing in.
=> Updated the link in the documentation to a publically-accessible URL

hpx/lcos/detail/future_data.hpp, hpx/lcos/local/barrier.hpp, hpx/lcos/local/condition_variable.hpp, hpx/lcos/local/counting_semaphore.hpp, hpx/lcos/local/detail/condition_variable.hpp, hpx/lcos/local/event.hpp, hpx/lcos/local/latch.hpp, hpx/lcos/local/mutex.hpp, hpx/lcos/local/shared_mutex.hpp, hpx/lcos/server/barrier.hpp, hpx/lcos/server/queue.hpp, hpx/plugins/parcelport/mpi/sender.hpp
Minor redesign of how locks are handled by `detail::condition_variable`:
- Makes use of locks safe under destruction (after #1488).
- Makes lock status and ownership explicit in code.
=> Making detail::condition_variable safe to use

hpx/parallel/executors/executor_traits.hpp, hpx/parallel/executors/parallel_executor.hpp, hpx/parallel/executors/parallel_fork_executor.hpp, hpx/parallel/executors/sequential_executor.hpp, tests/unit/parallel/executors/CMakeLists.txt, tests/unit/parallel/executors/bulk_async.cpp, tests/unit/parallel/executors/created_executor.cpp, tests/unit/parallel/executors/minimal_async_executor.cpp, tests/unit/parallel/executors/minimal_sync_executor.cpp, tests/unit/parallel/executors/parallel_executor.cpp, tests/unit/parallel/executors/parallel_fork_executor.cpp, tests/unit/parallel/executors/sequential_executor.cpp, tests/unit/parallel/executors/service_executors.cpp, tests/unit/parallel/executors/thread_pool_executors.cpp
The default return type of `bulk_execute` and `bulk_async_execute` was changed from `void` and `hpx::future<void>` to `std::vector<return_of_F_type>` (void if return_of_F_type is void) and `std::vector<hpx::future<return_of_F_type> >` for each of the executors and for the behavior of executor_traits. Note that the return type is forwarded from the executor_type so a user can easily create an executor with the behavior described by n4406. This was tested in created_executor.cpp.
For sequential_executor, I don't think hpx::util::unwrapped is optimal in bulk_execute. Any suggestions? Also, executor tests compiled on my machine but running thread_pool_executors_test failed about half of the time. I got `{what}: assertion 'running()' failed: HPX(assertion_failure)`
=> Changed return type of bulk executors and added test

cmake/HPX_AddConfigTest.cmake, hpx/util/hardware/timestamp.hpp
Add an `EXECUTE` flag for config test that need to be executed to produce useful results (fixes #1537). Use `linux_generic` as a fallback timestamp when RDTSC/RDTSCP is not available.
=> Fix idle-rate on platforms without TSC

hpx/components/containers/unordered/unordered_map.hpp, hpx/runtime/serialization/serialization_fwd.hpp, hpx/runtime/serialization/variant.hpp, tests/unit/serialization/CMakeLists.txt, tests/unit/serialization/serialization_variant.cpp
Drawbacks:
1) requires n+1 instantiations of load_helper (n - amount of template parameters for variant)
2) all types in variant should be serializable;
3) all types should have default ctor.
=> Serialization variant hpp

hpx/parallel/executors/executor_traits.hpp, hpx/parallel/executors/sequential_executor.hpp, tests/unit/parallel/executors/created_executor.cpp
This fixes compilation problems in executor_traits for older compilers.
=> Executor traits result types

cmake/FindOrangeFS.cmake
This pull request changes the cmake/FindOrangeFS.cmake in PXFS branch, to match with OrangeFS 2.9.1 library names.
=> Pxfs -  Modifying FindOrangeFS.cmake based on OrangeFS 2.9.X

cmake/HPX_SetupBoost.cmake, examples/1d_stencil/1d_stencil_1_omp.cpp, examples/1d_stencil/1d_stencil_3_omp.cpp, examples/future_reduce/CMakeLists.txt, examples/future_reduce/future_reduce.cpp, examples/jacobi_smp/jacobi_nonuniform_omp.hpp, examples/jacobi_smp/jacobi_omp.hpp, examples/quickstart/pipeline1.cpp, examples/transpose/transpose.cpp, examples/transpose/transpose_smp_block.cpp, hpx/config/compiler_specific.hpp, hpx/util/detail/unique_function_template.hpp, hpx/util/high_resolution_clock.hpp, hpx/util/high_resolution_timer.hpp, hpx/util/move.hpp, tests/performance/local/foreach_scaling.cpp, tests/performance/local/htts_v2/htts2.hpp, tests/performance/local/print_heterogeneous_payloads.cpp
This pull request un-breaks the compilation of all of our examples and tests.
=> Fixing intel14/libstdc++4.4

hpx/runtime/actions/plain_action.hpp, tests/regressions/actions/CMakeLists.txt, tests/regressions/actions/plain_action_1550.cpp
- this reverts commit 2bdf6a58fa4c10d404663f47aafd2f523808a52f
- properly fix broken macros
- add missing blurb in documentation
=> Properly fix HPX_DEFINE_*_ACTION macros

hpx/parallel/algorithms/copy.hpp, tests/regressions/parallel/scan_shortlength.cpp
This mainly fixes the failing `scan_shortlength` test
=> Fixed algorithms relying on copy_if implementation

hpx/config/export_definitions.hpp, hpx/runtime/serialization/basic_archive.hpp, hpx/runtime/serialization/input_archive.hpp, hpx/runtime/serialization/output_archive.hpp
Also properly export serialization archives
=> Removing obsolete Boost.Serialization macros. 

hpx/parallel/algorithms/detail/dispatch.hpp, hpx/parallel/algorithms/for_each.hpp, hpx/parallel/exception_list.hpp, hpx/parallel/execution_policy.hpp, hpx/parallel/executors/sequential_executor.hpp, hpx/parallel/util/foreach_partitioner.hpp, tests/unit/parallel/algorithms/CMakeLists.txt, tests/unit/parallel/algorithms/foreach.cpp, tests/unit/parallel/algorithms/foreach_executors.cpp, tests/unit/parallel/algorithms/foreach_tests.hpp
-Integrated for_each with executors
-removed .on() functionality from 'shims'
=> Executor algorithms

hpx/lcos/detail/future_data.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/executors/thread_pool_executors.hpp, hpx/state.hpp, hpx/util/coroutine/coroutine.hpp, hpx/util/coroutine/detail/self.hpp, src/runtime.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/thread_data.cpp, src/util/command_line_handling.cpp, tests/unit/lcos/promise.cpp, tests/unit/threads/CMakeLists.txt, tests/unit/threads/thread_suspension_executor.cpp, tests/unit/threads/thread_yield.cpp
This patch fixes the problems with the thread pool executors. It also includes 2 fly-by changes
- to the shared state of `hpx::future`, fixing a benign data race
- to the promise test
It also includes a new test and an extension to an existing test
=> Fixing thread pool executor

hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/executors/thread_pool_executors.hpp, hpx/runtime/threads/policies/hierarchy_scheduler.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, hpx/runtime/threads/policies/static_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/thread_queue.hpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/util/command_line_handling.cpp
This PR cleans up some minor left over problems from merging #1573:
- Comment fixes
- Fixing wrong conditional expression caught by @sithhell in #1573 
- Improve consistency of exit condition from schedulers 
- Remove an unneeded parameter from one of the scheduler API functions
=> Cleaning up schedulers

tests/unit/parallel/algorithms/rotate.cpp, tests/unit/parallel/algorithms/rotate_copy.cpp
Parallel rotate sometimes failed to pass because of expected exceptions not being thrown. This patch makes sure exceptions are being thrown always.
=> Fixing tests for parallel rotate

docs/manual/config_defaults.qbk, hpx/runtime/parcelset/parcelhandler.hpp, src/runtime/parcelset/parcelhandler.cpp
By default message handlers are now disabled (use `-Ihpx.parcel.message_handlers=1` to enable)
=> Adding configuration option disabling/enabling all message handlers 

tests/unit/components/get_ptr.cpp
This patch fixes problems when running the get_ptr test on Intel 13 platforms (release)
=> Get ptr problems

CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/tests/cxx11_decltype_n3276.cpp
Add config macro for optional N3276 decltype support
=> Mark decltype support as required

docs/manual/commandline.qbk, hpx/hpx_fwd.hpp, hpx/runtime/naming/name.hpp, hpx/runtime/parcelset/encode_parcels.hpp, hpx/runtime/serialization/basic_archive.hpp, hpx/runtime/serialization/container.hpp, hpx/runtime/serialization/detail/size_gatherer_container.hpp, hpx/runtime/serialization/output_archive.hpp, hpx/runtime/serialization/output_container.hpp, hpx/runtime/serialization/serialize.hpp, hpx/util/logging.hpp, src/runtime/actions/action_manager.cpp, src/runtime/components/console_logging.cpp, src/runtime/components/server/console_logging_server.cpp, src/runtime/naming/name.cpp, src/runtime/parcelset/parcelhandler.cpp, src/util/command_line_handling.cpp, src/util/logging.cpp, src/util/parse_command_line.cpp
This additionally 
- fixes the issues showing up after merging #1557 (avoid side effects like id-splitting during fake serialization)
- add parcel logging (command line option `--hpx:debug-parcel-log[=<file>]`, binary parcel content dump, etc.)
=> Removing type_size trait, replacing it with special archive type

CMakeLists.txt
@sithhell Not sure if your change of the default option value was intentional (see https://github.com/STEllAR-GROUP/hpx/commit/34a0e3fe5151ec9a05be7489bc4cf1eae1cccf9a), please comment
=> Fix doc string for config option HPX_WITH_EXAMPLES

hpx/util/date_time_chrono.hpp
This was overlooked when the cmake config constants where unified (see #1461)
=> Fixing preprocessor constant used to enable C++11 chrono 

hpx/hpx_fwd.hpp
This operator is missing but useful.
=> Adding operator|() for hpx::launch

hpx/runtime/serialization/vector.hpp, hpx/util/filesystem_compatibility.hpp
When running the test suite with C++ standard library debug mode enabled, a few problems occured. The commits in this PR fixes them.
=> Fixing array access

src/util/command_line_handling.cpp
This fixes #1606: Running without localities parameter binds to bogus port range
=> Fixed running multiple localities without localities parameter 

circle.yml
Increase timeout for one of the commands executed by CircleCI as it is failing occasionally
=> Increase timeout for CircleCI

tests/unit/parallel/algorithms/remove_copy.cpp, tests/unit/parallel/algorithms/remove_copy_if.cpp
This fixes the occasional test failures we were seeing for the remove_copy_if tests. This also applies similar fly-by changes to the remove_copy test.
=> Fixing problems with remove_copy algorithm tests

hpx/hpx_fwd.hpp, hpx/runtime.hpp, hpx/runtime/threads/detail/periodic_maintenance.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/detail/thread_pool.hpp, hpx/runtime/threads/policies/hierarchy_scheduler.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, hpx/runtime/threads/policies/periodic_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, hpx/runtime/threads/policies/thread_queue.hpp, hpx/runtime/threads/threadmanager.hpp, hpx/runtime/threads/threadmanager_impl.hpp, hpx/runtime_impl.hpp, src/exception.cpp, src/runtime.cpp, src/runtime/threads/detail/thread_pool.cpp, src/runtime/threads/threadmanager.cpp, src/runtime/threads/threadmanager_base.cpp, src/runtime_impl.cpp
This patch separates the thread-pool functionality from the thread-manager. This is the first step towards creating an executor which has full control over processing units. The existing executors are built on top of the underlying main scheduler, which causes them to compete for processing time. The new executor will not have that disadvantage.
=> Refactoring thread manager, mainly extracting thread pool

docs/CMakeLists.txt, hpx/hpx_fwd.hpp, hpx/runtime/actions/continuation.hpp, hpx/runtime/trigger_lco.hpp, src/runtime/actions/continuation.cpp
Allowing to specify whether to send credits along with message  back to the future.
This has shown to fix the HPXCL problems (see comments on https://github.com/STEllAR-GROUP/hpx/commit/42d15d3f378d39ff833344d4ef9b89452ab4db58)
=> Allowing to specify whether to send credits along with message 

hpx/lcos/detail/future_data.hpp, hpx/lcos/local/dataflow.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/lcos/wait_all.hpp, hpx/lcos/wait_some.hpp, hpx/lcos/when_all.hpp, hpx/lcos/when_any.hpp, hpx/lcos/when_each.hpp, hpx/lcos/when_some.hpp
This reapplies changes which have been reverted by merging #1634. This is mainly to better handle continuations on deferred futures. This should also fix the sequential_executor test failures.
=> Partially re-apply changes from limit_dataflow_recursion branch

hpx/lcos/future.hpp
This also changes `boost::detail::iterator_traits` to `std::iterator_traits`
=> Fixing problems introduced by merging #1623 for older compilers

hpx/runtime/serialization/input_archive.hpp, hpx/runtime/serialization/output_archive.hpp, tests/unit/serialization/serialization_builtins.cpp
There still might be some problems when compiling the test in case some platforms don't support numeric_limits for 128bit types
=> Added support for 128bit number serialization

cmake/templates/HPXMacros.cmake.in
string test was starting to annoy me as it was the same path, just had an extra backslash, etc.
=> Improve Boost compatibility check

tests/unit/actions/CMakeLists.txt, tests/unit/lcos/CMakeLists.txt
=> Fixing cmake warnings about not existing pseudo target dependencies 

CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/HPX_Documentation.cmake, cmake/HPX_GeneratePackage.cmake, cmake/HPX_GitCommit.cmake, cmake/HPX_SetupBoost.cmake, docs/CMakeLists.txt, docs/manual/build_system/using_hpx_cmake.qbk, docs/whats_new.qbk, examples/performance_counters/sine/CMakeLists.txt, plugins/binary_filter/bzip2/CMakeLists.txt, plugins/binary_filter/snappy/CMakeLists.txt, plugins/binary_filter/zlib/CMakeLists.txt, plugins/parcel/coalescing/CMakeLists.txt, plugins/parcelport/CMakeLists.txt, plugins/parcelport/ibverbs/CMakeLists.txt, plugins/parcelport/ipc/CMakeLists.txt, plugins/parcelport/mpi/CMakeLists.txt, plugins/parcelport/tcp/CMakeLists.txt, src/CMakeLists.txt, src/components/component_storage/CMakeLists.txt, src/components/containers/unordered/CMakeLists.txt, src/components/containers/vector/CMakeLists.txt, src/components/iostreams/CMakeLists.txt, src/components/memory/CMakeLists.txt, src/components/papi_counters/CMakeLists.txt, src/components/security/CMakeLists.txt, tests/performance/network/network_storage/CMakeLists.txt, tests/unit/agas/components/CMakeLists.txt, tests/unit/build/CMakeLists.txt
Lots of CMake changes:
Use HPX_PACKAGE_NAME for install paths where appropriate
Replace hpx_SOURCE_DIR with PROJECT_SOURCE_DIR
Replace hpx_BINARY_DIR with PROJECT_BINARY_DIR
This should allow one to change the project name and have most
install/find rules remain working.
A number of hardcoded filenames of type hpx_XXXX have been left unchanged
=> Change project name to HPX

hpx/plugins/parcelport/mpi/mpi_environment.hpp, hpx/plugins/parcelport/mpi/receiver.hpp, hpx/plugins/parcelport/mpi/receiver_connection.hpp, hpx/plugins/parcelport/mpi/sender.hpp, hpx/plugins/parcelport/mpi/sender_connection.hpp, hpx/plugins/parcelport/mpi/tag_provider.hpp, plugins/parcelport/mpi/mpi_environment.cpp, plugins/parcelport/mpi/parcelport_mpi.cpp
- Turning receiving and sending into a asynchronous state machine
- Adding explicit tag release mechansim once the receiver is completely done
- Disabling MPI multithreading support by default
=> Fixing the MPI parcelport

hpx/runtime/serialization/detail/polymorphic_nonintrusive_factory.hpp, tests/unit/serialization/polymorphic/CMakeLists.txt, tests/unit/serialization/polymorphic/serialization_polymorphic_semiintrusive_template.cpp, tests/unit/serialization/polymorphic/serialization_polymorphic_template.cpp
The intrusive serialization factory requires a class to ship a serialize() function. This is not always desirable, e.g. if this function is automatically generated externally. The non-intrusive serialization factory requires users to manually register all template instantiations, which is impossible to guarantee in the context of generic libraries (or: a user burden, but that's essentially the same).
The new "semi-intrusive" code adds infrastructure to relieve library developers from having to manually register all template instantiations. This requires a minute change (intrusion) to registered templates, but serialize() can still be put outside.
=> Extended Non-intrusive Serialization to Ease Usage for Library Developers

CMakeLists.txt, docs/manual/scheduling_policies.qbk, hpx/hpx_fwd.hpp, hpx/parallel/executors.hpp, hpx/parallel/executors/detail/thread_executor.hpp, hpx/parallel/executors/executor_traits.hpp, hpx/parallel/executors/this_thread_executors.hpp, hpx/parallel/executors/thread_pool_executors.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/detail/thread_num_tss.hpp, hpx/runtime/threads/detail/thread_pool.hpp, hpx/runtime/threads/executors/manage_thread_executor.hpp, hpx/runtime/threads/executors/this_thread_executors.hpp, hpx/runtime/threads/executors/thread_pool_executors.hpp, hpx/runtime/threads/policies/schedulers.hpp, hpx/runtime/threads/policies/static_queue_scheduler.hpp, src/hpx_init.cpp, src/runtime/threads/detail/thread_num_tss.cpp, src/runtime/threads/detail/thread_pool.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/threadmanager.cpp, src/runtime_impl.cpp, src/util/parse_command_line.cpp, tests/unit/parallel/executors/CMakeLists.txt, tests/unit/parallel/executors/this_thread_executors.cpp, tests/unit/parallel/executors/thread_pool_executors.cpp
- also add executor_traits<>:;has_pending_closures()
- refactoring interface of scheduling_loop
- exit scheduling loop without delay if called from inner scheduler (fixes performance regression)
- add missing #includes
=> Add this_thread_executors

hpx/parallel/algorithms/is_sorted.hpp, hpx/parallel/util/detail/chunk_size.hpp, hpx/parallel/util/foreach_partitioner.hpp, hpx/parallel/util/partitioner.hpp, hpx/parallel/util/partitioner_with_cleanup.hpp, hpx/util/invoke_fused.hpp
The partitioner was changed to make use of the bulk overload of
async execute for the parallel algorithms and functional components
of invoke fused was added.
Other:
- chunk_size.hpp reserves different size for shape function and
shape is now a vector of tuples
- partitioner and foreach partioner takes advantage of
bind(invoked, function, _1)
=> Converting partitioners to use bulk async execute

examples/1d_stencil/1d_stencil_8.cpp
When the results where printed, the inner for loop was iterating over the global number of partitions. 
As stepper_server::space const& s = solution[i]  we know s.size() = local_np and thus the inner for loop has to use the local number of partitions and not the global.
=> 1d stencil fix

hpx/lcos/detail/future_data.hpp, hpx/lcos/future.hpp, tests/unit/serialization/polymorphic/CMakeLists.txt, tests/unit/serialization/polymorphic/polymorphic_semiintrusive_template.cpp, tests/unit/serialization/polymorphic/polymorphic_template.cpp, tests/unit/serialization/polymorphic/smart_ptr_polymorphic.cpp, tests/unit/serialization/polymorphic/smart_ptr_polymorphic_nonintrusive.cpp
This should fix the current locking problems. 
@K-ballo could you please review the changes?
=> Fixing held locks

hpx/parallel/executors/detail/thread_executor.hpp, hpx/parallel/executors/executor_traits.hpp, hpx/parallel/executors/parallel_executor.hpp, hpx/parallel/executors/parallel_fork_executor.hpp, hpx/parallel/executors/sequential_executor.hpp, hpx/parallel/executors/service_executors.hpp, hpx/parallel/executors/thread_pool_executors.hpp, hpx/traits/is_executor.hpp, tests/regressions/parallel/CMakeLists.txt, tests/regressions/parallel/executors/CMakeLists.txt, tests/regressions/parallel/executors/is_executor_1691.cpp
- types derived from parallel::executor_tag are treated as executors by default
=> Fix #1691: is_executor template specification fails for inherited executors

hpx/parallel/algorithms/copy.hpp, hpx/parallel/algorithms/exclusive_scan.hpp, hpx/parallel/algorithms/inclusive_scan.hpp, hpx/parallel/algorithms/transform_exclusive_scan.hpp, hpx/parallel/algorithms/transform_inclusive_scan.hpp, hpx/parallel/util/scan_partitioner.hpp
With these changes, the scan partitioner now takes four functions.
The first two functions are the same as previously, they operate on a
partition and then accumulate the result. The third function now
operates on each partitioner with it's corresponding accumulated result
instead of being called once. The fourth function is just to create a
result type.
Changes accomplish the following:
- Reduce overhead of calling another partitioner inside of
scan_partitioner
- Allow third step to be called as soon as possible instead of waiting
for all of the accumulated items to be finished
-  allow scan algorithms to not need a temporary data structure
- allow transform_exclusive_scan to operate in place
=>  Modified Scan Partitioner for Algorithms

hpx/runtime/serialization/vector.hpp
The speedup is palpable in cpp-serializers benchmark when serializing strings.
=> vector deserialization is speeded up a little

docs/manual/parallel_algorithms.qbk, hpx/include/components.hpp, hpx/parallel/executors.hpp, hpx/parallel/executors/distribution_policy_executor.hpp, hpx/parallel/executors/executor_traits.hpp, hpx/runtime/components/server/invoke_function.hpp, hpx/traits/is_action.hpp, tests/unit/component/CMakeLists.txt, tests/unit/component/distribution_policy_executor.cpp
- integrates executors with distribution policies
- adding test
=> Add distribution_policy_executor

hpx/runtime.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/detail/thread_pool.hpp, hpx/runtime/threads/executors/generic_thread_pool_executor.hpp, hpx/runtime/threads/executors/this_thread_executors.hpp, hpx/runtime/threads/executors/thread_pool_executors.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, hpx/runtime/threads/thread_helpers.hpp, hpx/runtime/threads/threadmanager.hpp, hpx/runtime/threads/threadmanager_impl.hpp, hpx/runtime_impl.hpp, src/runtime/threads/detail/thread_num_tss.cpp, src/runtime/threads/detail/thread_pool.cpp, src/runtime/threads/executors/generic_thread_pool_executor.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/thread_helpers.cpp, src/runtime/threads/threadmanager.cpp, src/runtime_impl.cpp
- exposing new API functions supporting executors
- adding third callback to scheduling_loop for background related work
=> Various fixes to threads::executors to make custom schedulers work

CMakeLists.txt, hpx/runtime/serialization/list.hpp, hpx/runtime/serialization/vector.hpp, tests/unit/serialization/CMakeLists.txt, tests/unit/serialization/serialization_list.cpp
This patch adds serialization support for std::list.
A small flyby change has been included which fixes vector serialization to properly honor the Allocator template during it's serialization.
=> List serialization

hpx/runtime/serialization/array.hpp, tests/unit/serialization/serialization_array.cpp
I did pull out some code of which the first half (related to Endianess) did just look wrong and the other half didn't work properly.
=> serialization of arrays didn't work with non-pod types. fixed.

hpx/runtime/applier/apply_helper.hpp, hpx/runtime/applier/detail/apply_colocated.hpp, hpx/runtime/applier/detail/apply_colocated_fwd.hpp
Some errors occurred while compiling hpxcl. This patch fixes those.
=> Fixing compile problems with apply_colocated

src/runtime/threads/detail/thread_pool.cpp, src/runtime/threads/threadmanager.cpp
- making returned times be measured in seconds (not ns)
=> Fixed #1688: Add timer counters for tfunc_total and exec_total

hpx/runtime/serialization/serialize_buffer.hpp, tests/unit/serialization/serialize_buffer.cpp
While testing my changes I realized that of the two nearly identical implementations found in serialize_buffer.hpp, each was working only partially. I removed the duplication and fixed related bugs.
=> added convenience c-tor and begin()/end() to serialize_buffer

hpx/parallel/algorithms/detail/set_operation.hpp, hpx/parallel/executors/auto_chunk_size.hpp, hpx/parallel/executors/executor_parameter_traits.hpp, hpx/parallel/executors/executor_traits.hpp, hpx/parallel/executors/guided_chunk_size.hpp, hpx/parallel/executors/sequential_executor.hpp, hpx/parallel/executors/static_chunk_size.hpp, hpx/parallel/executors/thread_executor_traits.hpp, hpx/parallel/util/detail/chunk_size.hpp, tests/unit/parallel/executors/minimal_sync_executor.cpp, tests/unit/parallel/executors/minimal_timed_sync_executor.cpp
- this also enables the possibility to customize the max number of processing units to use for a particular algorithm through the supplied executor parameters object.
=> Renaming get_os_thread_count

examples/transpose/CMakeLists.txt, examples/transpose/transpose_serial_vector.cpp, hpx/components/containers/container_distribution_policy.hpp, hpx/components/containers/partitioned_vector/partitioned_vector.hpp, hpx/components/containers/partitioned_vector/partitioned_vector_component.hpp, hpx/components/containers/partitioned_vector/partitioned_vector_segmented_iterator.hpp, hpx/include/partitioned_vector.hpp, src/components/containers/CMakeLists.txt, src/components/containers/partitioned_vector/CMakeLists.txt, src/components/containers/partitioned_vector/partitioned_vector_component.cpp, tests/performance/local/CMakeLists.txt, tests/performance/local/partitioned_vector_foreach.cpp, tests/unit/component/CMakeLists.txt, tests/unit/component/partitioned_vector_copy.cpp, tests/unit/component/partitioned_vector_for_each.cpp, tests/unit/component/partitioned_vector_handle_values.cpp, tests/unit/component/partitioned_vector_iter.cpp, tests/unit/component/partitioned_vector_move.cpp, tests/unit/component/partitioned_vector_transform_reduce.cpp, tools/inspect/length_check.cpp, tools/inspect/length_check.hpp
This is  renaming hpx::vector to hpx::deque
- the rationale is that this data structure does not store its elements sequentially
in memory, but in non-contiguous segments
=> Renaming vector

hpx/lcos/when_all.hpp, tests/unit/lcos/when_all.cpp
when_all did not compile in a case like this:
future<T> f = ...;
when_all(f);
as the wrong result type was computed. A testcase has been added
The testcase and prior failure can be observed here:
https://gist.github.com/sithhell/2f37e44994e596677575
=> Fixing when_all when only a single future is passed.

hpx/components/iostreams/server/output_stream.hpp, hpx/runtime/actions/transfer_action.hpp, hpx/runtime/agas/component_namespace.hpp, hpx/runtime/agas/locality_namespace.hpp, hpx/runtime/agas/primary_namespace.hpp, hpx/runtime/agas/server/component_namespace.hpp, hpx/runtime/agas/server/locality_namespace.hpp, hpx/runtime/agas/server/primary_namespace.hpp, hpx/runtime/agas/server/symbol_namespace.hpp, hpx/runtime/agas/symbol_namespace.hpp, hpx/runtime/parcelset/locality.hpp, hpx/runtime/serialization/detail/polymorphic_intrusive_factory.hpp, hpx/util/detail/function_registration.hpp, hpx/util/detail/fusion_adapt_tuple.hpp, hpx/util/tuple.hpp
This PR reduces `hpx::util::tuple` dependencies, and reduces the number of `#include`s to a bare minimum.
=> Tuple dependencies

src/hpx_init.cpp, src/runtime/threads/policies/parse_affinity_options.cpp
This patch should fix the errors described in #1757.
@pagrubel, @khuck: Can you please confirm?
=> Fixing #1757

hpx/lcos/detail/future_data.hpp, hpx/lcos/local/condition_variable.hpp, hpx/lcos/local/detail/condition_variable.hpp, hpx/lcos/local/mutex.hpp, hpx/runtime/threads/detail/set_thread_state.hpp, src/runtime/threads/thread_helpers.cpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/wait_for_1751.cpp
- this also makes more consistent return codes from suspend and other timer related thread functions
=> Fixed #1751: hpx::future::wait_for fails a simple test

cmake/HPX_GeneratePackage.cmake
- This fixes #1590: CMake fails when CMAKE_BINARY_DIR contains '+'
=> Add more characters with special regex meaning to the existing patch

hpx/runtime/serialization/detail/polymorphic_id_factory.hpp, hpx/runtime/serialization/detail/polymorphic_intrusive_factory.hpp, hpx/runtime/serialization/detail/polymorphic_nonintrusive_factory.hpp, hpx/util/jenkins_hash.hpp, src/runtime/serialization/detail/polymorphic_id_factory.cpp, src/runtime/serialization/detail/polymorphic_intrusive_factory.cpp, src/runtime/serialization/detail/polymorphic_nonintrusive_factory.cpp
With visibility=off the factories might end up being duplicated over the shared libraries. This patch makes sure those are really unique.
=> Making sure all serialization registries/factories are unique 

CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/tests/cxx11_std_reference_wrapper.cpp, hpx/util/decay.hpp
Reimplement `util::decay` on top of `std::decay`. The Boost based version has a considerable compile-time cost compared to the standard one. While on the neighborhood, add `std::reference_wrapper` support to `decay_unwrap`.
=> Forwarding decay to std::

tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/receive_buffer_1733.cpp
This fixes #1733: Add unit test for hpx/lcos/local/receive_buffer.hpp
=> Adding test for receive_buffer

docs/manual/existing_performance_counters.qbk, hpx/performance_counters/counter_creators.hpp, hpx/performance_counters/counters.hpp, hpx/performance_counters/registry.hpp, hpx/performance_counters/server/base_performance_counter.hpp, hpx/runtime/actions/action_support.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/actions/component_action.hpp, hpx/runtime/actions/invocation_count_registry.hpp, hpx/runtime/actions/plain_action.hpp, hpx/runtime/actions/transfer_action.hpp, hpx/runtime/serialization/detail/polymorphic_nonintrusive_factory.hpp, src/performance_counters/registry.cpp, src/performance_counters/server/action_invocation_counter.cpp, src/runtime.cpp, src/runtime/actions/invocation_count_registry.cpp
Adding performance counters for local and remote action invocation counts:
/runtime/count/action_invocation 
/runtime/count/remote_action_invocation 
The actual action name has to be specified as the parameter argument, for instance:
/runtime/count/action_invocation@set_value_action_gid_type
In order to get all action invocation counts, wildcard characters can be used (as usual):
/runtime/count/action_invocation@*
=> Action invocation count

hpx/runtime/agas/addressing_service.hpp, hpx/runtime/agas/server/primary_namespace.hpp, hpx/runtime/applier/detail/apply_colocated.hpp, hpx/runtime/applier/detail/apply_colocated_callback.hpp, hpx/runtime/components/server/runtime_support.hpp, hpx/runtime/components/stubs/runtime_support.hpp, hpx/runtime/parcelset/parcelhandler.hpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/server/primary_namespace_server.cpp, src/runtime/agas/server/route.cpp, src/runtime/applier/applier.cpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime/components/stubs/runtime_support_stubs.cpp, src/runtime/parcelset/parcelhandler.cpp
Stop routing AGAS parcels through locality 0 
Also minor flyby changes, such as:
- enforce owned lock for resolve_gid_locked
- enable more resolved gids in resolve_locally_known_addresses
- explicit unlocking of mutexes before throwing exceptions
This addresses the slowdown over time we observe for various applications. 
@quantomb, @justwagle: please check how applying this patch changes the picture.
=> Agas fixes

hpx/lcos/async_fwd.hpp, hpx/traits/action_capability_provider.hpp, hpx/traits/action_decorate_continuation.hpp, hpx/traits/action_decorate_function.hpp, hpx/traits/action_does_termination_detection.hpp, hpx/traits/action_is_target_valid.hpp, hpx/traits/action_message_handler.hpp, hpx/traits/action_priority.hpp, hpx/traits/action_schedule_thread.hpp, hpx/traits/action_serialization_filter.hpp, hpx/traits/action_stacksize.hpp
Remove legacy forwarding traits, they are not needed anymore and cause early instantiation of arguments
=> Drop legacy forwarding action traits

hpx/parallel/algorithms/for_each.hpp, hpx/parallel/algorithms/transform.hpp, hpx/parallel/traits/projected.hpp
- Fix is_iterator so that SFINAE can work
- Call projection functions with invoke so that member functions
can be passed as arguments.
=> Fix is_iterator for container algorithms

docs/manual/commandline.qbk, docs/whats_new.qbk, src/hpx_init.cpp, src/runtime_impl.cpp, src/util/command_line_handling.cpp, src/util/parse_command_line.cpp, src/util/query_counters.cpp
- `--hpx:printer-counter-at=<arg>` where arg could be startup, shutdown or noshutdown (default is shutdown, i.e. the old behavior)
- `--hpx:reset-counters` which resets the counters after they are evaluated by HPX
This fixes #1464: HPX option for pre and post bootstrap performance counters
=> Adding new command line options:

docs/manual/commandline.qbk, examples/heartbeat/heartbeat_console.cpp, hpx/lcos/local/packaged_task.hpp, hpx/runtime/agas/addressing_service.hpp, hpx/runtime/applier/apply.hpp, hpx/runtime/parcelset/parcelhandler.hpp, hpx/runtime/parcelset/parcelport.hpp, hpx/runtime/parcelset/policies/message_handler.hpp, plugins/parcel/coalescing/coalescing_message_handler.cpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/server/locality_namespace_server.cpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime/parcelset/parcelhandler.cpp, src/util/command_line_handling.cpp, src/util/parse_command_line.cpp, src/util/runtime_configuration.cpp
- bind to port zero only if num_localities == 1 and no locality is expected to connect
- converting parcelset::write_handler_type to unique_function
- adding command line option --hpx::expect-connecting-localities and cfg setting hpx.expect_connecting_localities
- fixed disconnect, disconnecting locality is now properly removed from connection caches
- fly-by changes to package_task invocation
This fixes #1788: connect with hpx::runtime_mode_connect
=> Fix connect with hpx::runtime_mode_connect

CMakeLists.txt, cmake/templates/config_defines.hpp.in
@sithhell Please check this, I think during cmake changes a var used for #define was missed
=> fix a wrong use of HPX_MAX_CPU_COUNT instead of HPX_HAVE_MAX_CPU_COUNT

hpx/runtime/parcelset/parcel.hpp
This fixes #1790: assertion 'action_.get()' failed: HPX(assertion_failure) when running Octotiger with pull request 1786
=> Allow for default constructed parcel instances to be moved

hpx/lcos/local/detail/condition_variable.hpp
@sithhell reported that the segfault does not manifest itself if the mutex is not unlocked while releasing threads. 
- This patch also add proper handling of exceptions happening while executing notify_all.
-  Fly-by change makes slist::size constant time
=> Fixing cv exceptions

cmake/FindActiveHarmony.cmake
Updating the activeharmony CMake module to use externalproject support if the library is requested but not yet installed.  This way the user doesn't have to pre-install the active harmony library, and it is a quick build.
=> Updating the activeharmony CMake module

hpx/runtime/agas/addressing_service.hpp, src/runtime/agas/addressing_service.cpp, src/runtime/parcelset/parcelhandler.cpp, tests/regressions/agas/CMakeLists.txt, tests/regressions/agas/register_with_basename_1804.cpp
- This fixes #1804: `register_with_basename` causes hangs
=> Making sure resolve_localities does not hang during normal operation.

hpx/lcos/detail/async_implementations.hpp, hpx/lcos/packaged_action.hpp, hpx/runtime/agas/server/primary_namespace.hpp, hpx/runtime/naming/name.hpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/server/route.cpp
-  Making sure AGAS cache is not touched for objects managed locally 
-  Adding dont_cache_mask for gid_type which prevents any gid from being stored in an AGAS cache.
- some fly-by optimizations tothe implementations of async and async_cb
=> Agas optimizations

hpx/async.hpp, hpx/lcos/async.hpp, hpx/lcos/async_fwd.hpp, hpx/lcos/detail/future_data.hpp, hpx/lcos/promise.hpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/async_action_1813.cpp
- This fixes #1813: async(launch::..., action(), ...) always invokes locally
=> Fix async to dispatch to the correct locality in all cases

README.rst, docs/manual/build_system/recipe_osx.qbk
This patch updates the build instructions for OSX.
=> Fixing #1667

hpx/lcos/promise.hpp, src/runtime/agas/addressing_service.cpp
This PR works around a memory management issue in `lcos::promise` (see #1826: Memory management issue in hpx::lcos::promise)
=> Fixing a memory management issue for the Parquet application

tests/unit/threads/thread.cpp
- Make sure that interrupt is called only once the interrupts are disabled.
=> Unbreaking thread test

hpx/lcos/promise.hpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/promise_1620.cpp
This patch makes sure that the id of a promise can be retrieved multiple times
keeping the promise alive long enough.
=> Fixing #1620

examples/heartbeat/heartbeat.cpp, hpx/lcos/promise.hpp
This fixes #1832: hpx::lcos::promise<> must be move-only
=> Making hpx::lcos::promise move-only

hpx/lcos/promise.hpp
- also flyby change to add compatibility function promise::get_gid()
- removing obsolete comment
=> Adding exlicit move constructor and assignment operator

CMakeLists.txt, cmake/templates/config_defines.hpp.in, hpx/config.hpp, hpx/parallel/util/numa_allocator.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, hpx/runtime/threads/topology.hpp, src/runtime/threads/detail/thread_pool.cpp, tests/performance/local/stream.cpp
- also fixes NUMA-allocation debug tests for MIC
=> Fixing configuration for use of more than 64 cores

hpx/plugins/parcelport/mpi/receiver.hpp, hpx/plugins/parcelport/mpi/receiver_connection.hpp, hpx/plugins/parcelport/mpi/sender.hpp, hpx/plugins/parcelport/mpi/sender_connection.hpp, plugins/parcelport/mpi/parcelport_mpi.cpp
Instead of getting a hold onto all ongoing connections in the background
work, we just grab one. This gives other idling threads the opportunity to grab
Parcelport work as well.
Fly-by-change: The special allocator has been removed as it didn't have any
positive effect over the regular allocation.
=> Fixing Performance Problems with MPI Parcelport

CMakeLists.txt, cmake/HPX_SetupBoost.cmake
Removing remaining external/endian entries from CMake scripts. This
made some external builds using the exported targets fail.
=> Completely removing external/endian

cmake/HPX_SetupBoost.cmake
Treat boost includes as system includes, so that we don't have to look at their internal wall of warnings (C-style casts, deprecated use of `auto_ptr`, etc).
=> Use SYSTEM for boost includes

tools/gdb/hpx.py
- Adapting to latest changes
- Adding ability to inspect high and low priority threads as well
=> Fixing hpx gdb script

cmake/HPX_SetLibName.cmake
Set output name of target module even if CMAKE_BUILD_TYPE is not set.
=> Setting OUTPUT_NAME as target properties

hpx/lcos/local/mutex.hpp, hpx/runtime/threads/detail/tagged_thread_state.hpp, src/lcos/local/mutex.cpp
Split timed functionality out of `local::mutex` into `local::timed_mutex`. Move definitions to a source file.
=> Touch local::mutex

cmake/tests/cxx11_defaulted_functions.cpp, hpx/apply.hpp, hpx/async.hpp, hpx/lcos/detail/async_colocated.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/applier/register_apply_colocated.hpp, hpx/runtime/components/base_lco_factory.hpp, hpx/runtime/components/component_factory.hpp, hpx/runtime/components/component_factory_base.hpp, hpx/runtime/components/derived_component_factory.hpp, hpx/runtime/components/server/create_component.hpp, hpx/runtime/components/server/create_component_fwd.hpp, hpx/runtime/components/server/fixed_component_base.hpp, hpx/runtime/components/server/managed_component_base.hpp, hpx/runtime/components/server/simple_component_base.hpp, hpx/runtime/threads/thread.hpp, hpx/runtime/threads/thread_helpers.hpp, hpx/runtime/threads/thread_init_data.hpp, hpx/runtime/threads/threadmanager.hpp, hpx/traits/is_callable.hpp, hpx/util/bind.hpp, hpx/util/deferred_call.hpp, hpx/util/mem_fn.hpp, hpx/util/tuple.hpp, src/runtime/parcelset/parcelhandler.cpp, src/runtime/threads/executors/service_executor.cpp, src/runtime/threads/thread.cpp
Rework `bind`, `mem_fn`, `deferred_call` implementations for readability.
Copiability requirements are enforced after these changes. In particular, movable-only `bind` objects are now movable-only instead of fake-copyable.
=> Simplify callables

cmake/tests/cxx11_std_type_traits.cpp, hpx/util/detail/basic_function.hpp, hpx/util/detail/function_registration.hpp, hpx/util/detail/function_template.hpp, hpx/util/detail/get_table.hpp, hpx/util/detail/reset_function.hpp, hpx/util/detail/unique_function_template.hpp, hpx/util/detail/vtable/callable_vtable.hpp, hpx/util/detail/vtable/serializable_vtable.hpp, hpx/util/detail/vtable/vtable.hpp, hpx/util/function.hpp, hpx/util/unique_function.hpp, tests/performance/local/function_object_wrapper_overhead.cpp, tests/unit/util/function.cpp
Simplify `function` and `unique_function`. Unify duplicated functionality. Drop support for generic archive types.
=> Simplify functions

CMakeLists.txt, hpx/runtime/parcelset/parcel.hpp
Reintroduce ignored-qualifiers warning, now that Boost warnings are hidden from sight.
=> Fix some redundant qualifiers.

examples/transpose/transpose_block_numa.cpp, tests/performance/local/transform_reduce_scaling.cpp, tests/regressions/agas/register_with_basename_1804.cpp, tests/regressions/lcos/shared_mutex_1702.cpp, tests/regressions/parallel/scan_different_inits.cpp, tests/regressions/parallel/scan_shortlength.cpp, tests/unit/build/src/CMakeLists.txt, tests/unit/parallel/executors/minimal_async_executor.cpp, tests/unit/parallel/executors/minimal_sync_executor.cpp, tests/unit/parallel/executors/timed_this_thread_executors.cpp, tests/unit/serialization/serialization_variant.cpp
I've gone over the warnings I got from Clang 3.7, CMake 3.3.2 and libc++-trunk. This pull request has one commit per kind of warning:
* unused variables,
* pessimistic move,
* CMake diagnostic,
* infinite recursion.
Please inspect the files touched by the commits and see if my commonly suggested actions of `HPX_UNUSED`:ing the variables is desirable or if the automatic variables can be removed without losing test coverage or expressiveness.
=> Warning cleaning pass

hpx/util/thread_specific_ptr.hpp, tests/performance/local/native_tls_overhead.cpp
Clang has __has_feature which can be used to query for whether
thread_local exists. As clang with libc++ isn't covered by the
existing thread_specific_ptr cases, this adds support for TLS
on this combination of compiler and runtime.
This should resolve the issues in issue #1880.
=> Add feature test for thread_local on Clang for TLS

hpx/parallel/executors/executor_traits.hpp, tests/unit/parallel/executors/CMakeLists.txt, tests/unit/parallel/executors/shared_parallel_executor.cpp
I wanted to use an executor that returns shared_futures not futures. This is how I did it,
but please suggest anything if I missed an obvious alternative. 
Allows an executor to define and use a separate future type.
For example, a shared future instead of a default future. See
added test file.
=> Adds typed future_type for executor_traits

hpx/components/papi/server/papi.hpp, src/components/papi_counters/papi_startup.cpp, src/components/papi_counters/server/papi.cpp, tests/regressions/performance_counters/CMakeLists.txt, tests/regressions/performance_counters/papi_counters_segfault_1890.cpp
Fixes papi counters by converting managed_components to components as was done for other performance counters. see issue #1890
=> Fixing 1890

hpx/util/thread_specific_ptr.hpp, tests/performance/local/native_tls_overhead.cpp
Clang exposes the ability to test for the C++ feature `thread_local` via
the `__has_feature` macro.
Here we test for the presence of the macro and the feature in two
separate steps to avoid the preprocessor bailing out on invalid syntax.
As preprocessors replace before evaluating, naively going:
`#if defined(__has_feature) && __has_feature(cxx_thread_local)`
will result in the preprocessor seeing `0 && 0(0)` if the compiler
doesn't have Clang-style feature testing.
=> Add support for compilers that have thread_local

hpx/lcos/future.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, hpx/runtime/serialization/detail/future_await_container.hpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/future_serialization_1898.cpp
We currently run into a situation where we would need to wait on futures before
actual serialization after the first round of awaiting has been completed. In
addition, the future itself doesn't give its held value the chance to be awaited.
This fixes the segfault on shutdown for the testcase provided by #1898 once all the remaining (user issues) has been fixed (this will come in a separate PR).
=> Fixing a problem with credit splitting as revealed by #1898

hpx/runtime/serialization/access.hpp, hpx/runtime/serialization/input_archive.hpp, hpx/runtime/serialization/output_archive.hpp, hpx/runtime/serialization/serialize.hpp, tests/unit/serialization/CMakeLists.txt, tests/unit/serialization/fail_compile_non_serializable_class.cpp, tests/unit/serialization/succeed_compile_empty_class.cpp
=> Making non-serializable classes non-serializable

hpx/runtime/serialization/list.hpp, hpx/runtime/serialization/map.hpp, hpx/runtime/serialization/set.hpp, hpx/runtime/serialization/vector.hpp, tests/unit/serialization/serialization_map.cpp
- flyby warning fix in one of the tests
- flyby change: moving ..._impl functions into namespace detail
This fixes #1900
=> Making sure std containers are cleared before serialization loads data

docs/hpx.qbk, docs/manual/build_system/cmake_toolchains.qbk, docs/manual/build_system/prerequisites.qbk
Version 1.7 of Open MPI causes problems in HPX. This change
adds Open MPI as a highly suggested software package with
the minimum version being 1.8
=> Adding a minimum version for Open MPI

CMakeLists.txt
If CMAKE_MODULE_PATH was specified previously, keep the values.
We are improving conan.io (c++ package manager) supporting custom FindXXX.cmake for some packages like Boost and Hwloc. So those packages in conan provides their own FindXXX.
If you override the CMAKE_MODULE_PATH, conan won't be able to find the custom finders and the dependencies will be unresolved.
I think it doesn't affect at all to your build system but would be great for HPX conan package.
We are currently improving HPX Package (current version is a very alpha version) generator for conan.io. We hope to have a better version of HPX when we release conan 0.5
=> Keep cmake_module_path

hpx/lcos/promise.hpp, hpx/runtime/actions/continuation.hpp, hpx/runtime/naming/name.hpp, hpx/runtime/naming/split_gid.hpp, hpx/runtime/naming_fwd.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, hpx/runtime/serialization/container.hpp, hpx/runtime/serialization/detail/future_await_container.hpp, hpx/runtime/serialization/detail/size_gatherer_container.hpp, hpx/runtime/serialization/output_archive.hpp, hpx/runtime/serialization/output_container.hpp, hpx/runtime/threads/executors/current_executor.hpp, hpx/runtime/threads/policies/hwloc_topology.hpp, hpx/runtime/threads/thread_helpers.hpp, hpx/runtime/threads/topology.hpp, hpx/util/detail/basic_function.hpp, hpx/util/ini.hpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/server/symbol_namespace_server.cpp, src/runtime/naming/name.cpp, src/runtime/serialization/output_archive.cpp, src/util/logging.cpp
- Removed wrong assert (might fire in situations we actually do allow)
- Made adding of splitted GIDs thread safe as we might add GIDs concurrently when requesting new credit from AGAS
Flyby change: Cleaned up some headers, as this was necessary to make the proposed changes compile.
=> Fixing #1903

hpx/parallel/algorithms/sort.hpp, tests/unit/parallel/algorithms/sort.cpp, tests/unit/parallel/algorithms/sort_tests.hpp
Second attaempt, the former problems are solved now
- Adding explicit return types for lambdas
- flyby change: reduce array sizes for sort tests in Debug
=> Changing parallel::sort to return the last iterator as proposed by N4560

hpx/components/containers/partitioned_vector/partitioned_vector.hpp, hpx/components/containers/partitioned_vector/partitioned_vector_component.hpp
This pull request does 2 small changes:
- Give a public access to the type named data_type in hpx::server::partitioned_vector
- Add a member action (get_copied_data) allowing to asynchronously get a copy of the data 
owned by the server
=> Add utility member functions for partitioned_vector

examples/balancing/hpx_thread_phase.cpp, examples/quickstart/EasyBMP/EasyBMP.cpp, hpx/runtime/agas/big_boot_barrier.hpp, hpx/util/detail/basic_function.hpp, hpx/util/detail/function_template.hpp, hpx/util/detail/vtable/vtable.hpp, src/hpx_init.cpp, src/performance_counters/registry.cpp, src/runtime/agas/big_boot_barrier.cpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime/threads/policies/hwloc_topology.cpp, src/runtime/threads/resource_manager.cpp, src/util/init_ini_data.cpp, tests/performance/local/stencil3_iterators.cpp, tests/performance/local/timed_task_spawn.cpp, tests/unit/lcos/future.cpp, tests/unit/lcos/local_barrier.cpp, tests/unit/lcos/local_event.cpp, tests/unit/lcos/shared_future.cpp, tests/unit/serialization/polymorphic/polymorphic_pointer.cpp
- Fixing memory leaks
- Removing unused variables
- Fixing potential division by zero bugs
=> Fixing problems as reported by clang-check.

external/lockfree/boost/lockfree/queue.hpp, external/lockfree/boost/lockfree/ringbuffer.hpp, hpx/runtime/threads/thread_data.hpp, hpx/util/lockfree/detail/tagged_ptr_pair.hpp
Since this header has been removed in Boost 1.60.0, this also fixes
the compilation with newer Boost versions.
=> Removing superfluous includes of boost/lockfree/detail/branch_hints.hpp

hpx/parallel/container_algorithms/remove_copy.hpp, hpx/parallel/container_algorithms/replace.hpp
This was fixed previously, but lost during a merge
=> Fix a couple of compile errors with clang

CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/tests/cxx11_explicit_variadic_templates.cpp, hpx/util/tagged_tuple.hpp
This is for compilers which don't support explicit variadics (mainly Intel)
=> Adding workaround for tagged_tuple 

cmake/tests/cxx11_explicit_variadic_templates.cpp
This makes regression tests for gcc 4.6 pass.
=> Adapting test for explicit variadics to fail for gcc 4.6

hpx/lcos/future.hpp, tests/unit/lcos/CMakeLists.txt, tests/unit/lcos/make_future.cpp
- add overloads for shared_future
- make sure `make_future<T>(future<T>)` does not create ambiguities
- import make_future into namespace hpx
- adding test
- flyby change: import make_future_void into namespace hpx
=> Touching up make_future

tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/wait_all_hang_1946.cpp
This just adds an additional test verifying the issue does not re-appear (#1946 refers to V0.9.11 and the problem was already fixed).
=> Adding regression test for #1946: Hang in wait_all() in distributed run

cmake/templates/static_parcelports.hpp.in, hpx/plugins/parcelport_factory.hpp, hpx/plugins/parcelport_factory_base.hpp, plugins/parcelport/CMakeLists.txt, src/runtime/parcelset/parcelhandler.cpp
This fixes some UB in the Parcelport plugin initialization phase. This UB shows up in static release builds.
=> Fixing Static Parcelport initialization

hpx/config.hpp, hpx/lcos/detail/future_data.hpp, hpx/runtime/threads/thread_helpers.hpp, hpx/util/coroutine/coroutine.hpp, hpx/util/coroutine/detail/context_generic_context.hpp, hpx/util/coroutine/detail/context_linux_x86.hpp, hpx/util/coroutine/detail/context_posix.hpp, hpx/util/coroutine/detail/get_stack_pointer.hpp, hpx/util/coroutine/detail/self.hpp, src/runtime/threads/thread_helpers.cpp, src/util/lightweight_test.cpp, tests/regressions/lcos/dataflow_recursion_1613.cpp, tests/unit/parcelset/put_parcels.cpp, tests/unit/threads/thread_stacksize.cpp
- Disabling the continuation recursion counter on windows because it is not
needed there (stack grows dynamically)
- Adding function to retrieve the current value of the stack pointers on
supported platforms (x86, x86_64, arm and powerpc)
- When running the completion handlers, check for available stack space
to decide wether to recurse asynchronously or not
- Fallback to continuation recursion count for platforms where we can't retrieve
the stack pointer
This patch fixes a lot of problems with stack overflows in general and leads to less asynchronous completion handler executions in some cases.
=> Fixing continuation recursions to not depend on fixed amount of recursions

hpx/components/containers/partitioned_vector/partitioned_vector_component.hpp
The action is needed to perform a classic "put" operation from remote locality.
=> Add action to update data owned by the partitioned_vector component

tests/unit/parallel/algorithms/exclusive_scan.cpp, tests/unit/parallel/algorithms/inclusive_scan.cpp, tests/unit/parallel/algorithms/inclusive_scan_tests.hpp, tests/unit/parallel/algorithms/sort.cpp, tests/unit/parallel/algorithms/sort_by_key.cpp
Add a try/catch block around benchmark so that
machines with less RAM can fail silently.
=> Reduce size of benchmark timing arrays to fix test failures

hpx/util/coroutine/detail/context_generic_context.hpp, hpx/util/coroutine/detail/context_linux_x86.hpp, hpx/util/coroutine/detail/context_posix.hpp, hpx/util/coroutine/detail/get_stack_pointer.hpp
This cleans up the leftovers of #1969.
=> Replacing uintptr_t (which is not defined everywhere) with std::size_t

hpx/components/component_storage/server/migrate_from_storage.hpp, hpx/components/component_storage/server/migrate_to_storage.hpp, hpx/lcos/detail/async_implementations.hpp, hpx/lcos/packaged_action.hpp, hpx/runtime/applier/detail/apply_implementations.hpp, hpx/runtime/components/server/fixed_component_base.hpp, hpx/runtime/components/server/migrate_component.hpp, hpx/runtime/components/server/simple_component_base.hpp, hpx/traits.hpp, hpx/traits/component_supports_migration.hpp, src/runtime/agas/addressing_service.cpp, src/runtime/components/stubs/runtime_support_stubs.cpp
Avoid invoking migration table look up for objects which don't support migration. This introduces a small optimization avoiding to look up an id in the table of migrated objects for components which do not support migration in the first place. This should remove the slight performance regression we saw after merging the new migration code.
This also introduces a new trait: `traits::component_supports_migration<Component>`
=> Avoid invoking migration table look up for all objects 

examples/async_io/async_io_low_level.cpp, hpx/hpx_init_impl.hpp, hpx/hpx_start_impl.hpp, hpx/runtime/parcelset/parcelport.hpp, hpx/runtime_fwd.hpp, hpx/util/thread_aware_timer.hpp, hpx/util_fwd.hpp, src/hpx_main_winsocket.cpp, src/util/asio_util.cpp, src/util/thread_aware_timer.cpp
Making sure the winsock library is initialized from the main executable only (not from any DLLMain routine)
- this is a Windows specific change
=> Making sure the winsock library is properly initialized

CMakeLists.txt
=> Add missing LANGUAGES tag to a hpx_add_compile_flag_if_available() call in CMakeLists.txt

tests/unit/parallel/container_algorithms/test_utils.hpp
Attempting to fix the error [here](http://hermione.cct.lsu.edu/builders/hpx_msvc_14_boost_1_59_dev_windows_x86_64_release/builds/273/steps/build_unit_tests/logs/stdio)
MSVC builder seems to fail to find std::iota here, perhaps because the <numeric> header is not included?
=> Possible missing include in test_utils.hpp

CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/tests/cxx1y_experimental_std_optional.cpp, hpx/parallel/executors/distribution_policy_executor.hpp, hpx/parallel/executors/executor_traits.hpp, hpx/parallel/executors/parallel_executor.hpp, hpx/parallel/executors/sequential_executor.hpp, hpx/parallel/executors/thread_timed_executor_traits.hpp, hpx/parallel/executors/timed_executor_traits.hpp, hpx/traits/acquire_shared_state.hpp, tests/unit/parallel/executors/shared_parallel_executor.cpp
- flyby: adding missing typedef
=> Fixing shared_executor_test

hpx/util/parse_command_line.hpp, src/hpx_user_main_argc_argv.cpp, src/runtime/components/server/runtime_support_server.cpp, src/util/command_line_handling.cpp
Detect unknown command line options for applications which use the emulated main().
We know that the user is not going to look at the command line parameters if the application uses the simplest emulated main():
#include <hpx/hpx_main.hpp>
int main()
{
// ...
}
This PR reports any unknown options in this case (only). This fixes #1995.
=> Detect unknown command line options 

src/CMakeLists.txt
This is a simple fix, but @sithhell might know some reason why always enabling PIC is a bad idea.
=> Turn on position independent code to solve link problem with hpx_init

docs/CMakeLists.txt, docs/hpx.idx, docs/whats_new.qbk, hpx/include/lcos.hpp, hpx/lcos/gather.hpp, hpx/lcos/local/and_gate.hpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/multiple_gather_ops_2001.cpp
- also: adding gather_here and gather_there accept plain values (instead of futures)
- flyby: change size_t = ~0U to size_t = size_t(-1)
This fixes #2001
=> Adding generation parameter to gather to enable using it more than once

hpx/lcos/dataflow.hpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/dataflow_action_2008.cpp
=> Fixed dataflow if invoked action returns a future

tools/inspect/CMakeLists.txt, tools/inspect/function_hyper.hpp, tools/inspect/inspect.cpp, tools/inspect/inspector.hpp
The relative path to the search was not calculated correctly. This
fix allows the inspect tool to be invoked from any location.
=> Fixing inspect tool

src/runtime/threads/threadmanager.cpp
This fixes the compilation error described in #2033 when compiling with the thread queue wait time performance counter.
=> Fixing compilation error with thread queue wait time performance counter

hpx/traits/get_function_address.hpp
It's a know bug in NVIDIA's CUDA toolkit, but it won't be fixed until the next release and until then this  workaround is required to compile HPX+CUDA codes. I was getting the bug below when compiling LibGeoDecomp with CUDA and HPX enabled. The proposed patch fixes this.
[ 95%] Building CXX object src/testbed/spmvmtests/CMakeFiles/libgeodecomp_testbed_spmvmtests.dir/mmio.cpp.o
[ 95%] Linking CXX executable hpxperformancetests
[ 95%] Built target libgeodecomp_examples_spmvmvectorized
[ 95%] Built target libgeodecomp_testbed_hpxperformancetests
/home/gentryx/test_build_libgeodecomp_rei_g++-4.9.3/install/include/hpx/traits/get_function_address.hpp(87): internal error: assertion failed: alloc_copy_of_pending_pragma: copied pragma has source sequence entry …
=> nvcc dies with an internal error upon pushing/popping warnings inside templates

hpx/lcos/future.hpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/wait_all_std_array_2035.cpp
=> Changing future_iterator_traits to support pointers

hpx/plugins/parcel/coalescing_message_handler_registration.hpp, hpx/runtime/components/server/runtime_support.hpp, plugins/parcel/coalescing/CMakeLists.txt, src/pre_main.cpp, src/runtime.cpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime/parcelset/parcelhandler.cpp
This PR finally fixes the gcc test runner problems we're seeing right now. It corrects mainly:
- fix plugin loading to not re-load the module
- don't register parcel coalescing from coalescing plugin itself
- add missing message handler registration for connected localities
=> Fixing gcc startup hangs

hpx/runtime/threads/run_as_hpx_thread.hpp, hpx/runtime/threads/run_as_os_thread.hpp
- remove redundant invoke_fused()
=> Replacing std::result_of with util::result_of

hpx/util/unwrapped.hpp
Rewrite `unwrapped` for tuples without Boost.Fusion, avoid unnecessary intermediate tuples.
=> Rewrite tuple unwrap

hpx/runtime/components/server/runtime_support.hpp, hpx/runtime/components/stubs/runtime_support.hpp, tests/regressions/CMakeLists.txt, tests/regressions/components/CMakeLists.txt, tests/regressions/components/moveonly_constructor_arguments_1405.cpp
This pull request fixes #1405: Allow component constructors to take movable only types.
=> Enabling usage of moveonly types for component construction

hpx/parallel/executor_parameters.hpp, hpx/parallel/executors/persistent_auto_chunk_size.hpp, tests/unit/parallel/executors/executor_parameters.cpp, tests/unit/parallel/executors/persistent_executor_parameters.cpp
persistent_auto_chunk_size is created to make all chunk sizes of different loops having the same execution time. persistent_auto_chunk_size has smaller thread idle rate compared to auto_chunk_size, which results in
having a better latency hiding and reducing the overheads.
The change has been done by adding a new policy.
=> adding persistent_auto_chunk_size and related tests for for_each

hpx/components/iostreams/write_functions.hpp, hpx/lcos/base_lco.hpp, hpx/lcos/base_lco_with_value.hpp, hpx/parallel/segmented_algorithms/count.hpp, hpx/plugins/parcel/coalescing_message_handler_registration.hpp, hpx/util/ini.hpp, src/lcos/base_lco.cpp, src/runtime/parcelset/parcelhandler.cpp, tests/unit/parcelset/put_parcels_with_coalescing.cpp, tests/unit/serialization/serialize_buffer.cpp
This patch moves the parcel coalescing registration macros from the
headers into the translation units.
flyby: remove boost::mpl from base_lco and some minor header cleanup
This also fixes a memory leak reported from LeakSanitizer
=> Moving coalescing registration to TUs

examples/nqueen/nqueen_client.cpp
The previous code gave a future_has_no_valid_shared_state_exception, because the board object was not being instantiated. Now, when the option 'default' is chosen to solve the standard nqueens puzzle having board size 8 X 8, the correct answer 92 is printed. I think this should fix https://github.com/STEllAR-GROUP/hpx/issues/802#issuecomment-194255571.
=> Instantiate board in nqueen client

examples/quickstart/init_globally.cpp, hpx/hpx_init.hpp, hpx/hpx_init_impl.hpp, hpx/hpx_start.hpp, hpx/hpx_start_impl.hpp
- adding another overload for hpx::init() and hpx::start()
=> Making sure init_globally always executes hpx_main

docs/CMakeLists.txt, docs/hpx.idx, docs/manual/parallel_algorithms.qbk, hpx/include/parallel_reduce.hpp, hpx/parallel/algorithms/reduce_by_key.hpp, tests/unit/parallel/algorithms/CMakeLists.txt, tests/unit/parallel/algorithms/reduce_by_key.cpp
This is an algorithm present in thrust:: but not included in N4409. It is useful for a number of algorithms that use stream compaction (common in visualization).
=> Reduce by key, extends #1141

hpx/parallel/algorithms/reduce_by_key.hpp
GCC 4.6 still failed with my last fixes, so this time I have forced the lambda return type and the build now passes http://hermione.cct.lsu.edu/builders/hpx_gcc_4_6_boost_1_50_debian_x86_64_debug/builds/955
=> GCC 4.6 fails to deduce the correct type in lambda

CMakeLists.txt, hpx/parallel/algorithms/reduce_by_key.hpp, hpx/runtime/threads/executors/current_executor.hpp, hpx/runtime/threads/thread_executor.hpp, hpx/util/thread_description.hpp, tests/unit/parallel/algorithms/reduce_by_key.cpp, tests/unit/threads/thread_suspension_executor.cpp
The thread_description has one constructor missing the initializer for type_. There is a code path through there that causes type_ to be uninitialized.
=> Added missing initializer on last constructor for thread_description.

hpx/runtime/applier/applier.hpp, hpx/runtime/components/component_factory_base.hpp, hpx/runtime_fwd.hpp, hpx/util/ini.hpp, hpx/util_fwd.hpp
Fixes #2109.
See output from [master](http://hermione.cct.lsu.edu/builders/hpx_gcc_4_6_boost_1_50_debian_x86_64_debug/builds/956/steps/build_unit_tests/logs/warnings%20%2889%29) and the one from [this PR](http://hermione.cct.lsu.edu/builders/hpx_gcc_4_6_boost_1_50_debian_x86_64_debug/builds/957/steps/build_unit_tests/logs/warnings%20%2865%29).
=> Fix invalid attribute warnings

examples/1d_stencil/1d_stencil_8.cpp, hpx/components/component_storage/component_storage.hpp, hpx/components/containers/unordered/unordered_map.hpp, hpx/lcos/gather.hpp, hpx/lcos/latch.hpp, hpx/runtime/basename_registration.hpp, src/components/component_storage/component_storage.cpp, src/runtime/agas/addressing_service.cpp
- flyby: change gather API to rely on clients instead of future<id_type>
- flyby: fixed one of the register_with_basename API overloads
This fixes #2121
=> Resolved memory leak in stencil_8

hpx/parallel/executors/executor_parameter_traits.hpp, hpx/parallel/executors/thread_executor_parameter_traits.hpp, hpx/parallel/util/detail/handle_local_exceptions.hpp, hpx/parallel/util/detail/scoped_executor_parameters.hpp, hpx/parallel/util/foreach_partitioner.hpp, hpx/parallel/util/partitioner.hpp, hpx/parallel/util/partitioner_with_cleanup.hpp, hpx/parallel/util/scan_partitioner.hpp, hpx/traits/is_executor.hpp, hpx/traits/is_executor_parameters.hpp, tests/unit/parallel/executors/CMakeLists.txt, tests/unit/parallel/executors/executor_parameters_timer_hooks.cpp
- flyby: fix using std type traits
=> Adding hook functions for executor_parameter_traits supporting timers

hpx/include/compression_registration.hpp, hpx/performance_counters/parcels/gatherer.hpp, hpx/plugins/binary_filter/bzip2_serialization_filter.hpp, hpx/plugins/binary_filter/bzip2_serialization_filter_registration.hpp, hpx/plugins/binary_filter/snappy_serialization_filter.hpp, hpx/plugins/binary_filter/snappy_serialization_filter_registration.hpp, hpx/plugins/binary_filter/zlib_serialization_filter.hpp, hpx/plugins/binary_filter/zlib_serialization_filter_registration.hpp, hpx/runtime/actions/plain_action.hpp, hpx/runtime/parcelset/encode_parcels.hpp, hpx/runtime/parcelset/parcelport.hpp, hpx/runtime/serialization/output_container.hpp, plugins/binary_filter/bzip2/CMakeLists.txt, plugins/binary_filter/snappy/CMakeLists.txt, plugins/binary_filter/zlib/CMakeLists.txt, tests/unit/parcelset/CMakeLists.txt, tests/unit/parcelset/put_parcels_with_compression.cpp
- extract registration macros for compression into separate files
- flyby: make client<>::client(future<id_type>&&) non-explicit
- flyby: added HPX_DECLARE_PLAIN_ACTION
- flyby: fix performance counter mix-up of sent bytes and serialized bytes
This also fixes #2124
=> Fixing parcel compression, adding test

hpx/compute/cuda/detail/launch.hpp, hpx/compute/cuda/detail/scoped_active_target.hpp, hpx/compute/cuda/get_targets.hpp, hpx/compute/cuda/target.hpp, hpx/compute/host/target.hpp, hpx/compute/host/traits/access_target.hpp, hpx/compute/traits/access_target.hpp, hpx/compute/traits/allocator_traits.hpp, hpx/compute/vector.hpp, hpx/config/compiler_specific.hpp, hpx/util/deferred_call.hpp, hpx/util/invoke.hpp, hpx/util/invoke_fused.hpp, src/CMakeLists.txt
- moved traits into sub-namespace traits
- renamed target_traits to traits::access_target
- wrapped all CUDA headers with HPX_HAVE_CUDA
- bulk_construct now takes const& arguments (values are used more than once)
- some fixes to iterator
- added missing #includes
- added compute headers to build system
=> Some minor tweaks to compute prototype

hpx/parallel/execution_policy.hpp
Proper support for rebounded policies.
=> Add missing specializations in execution policies

examples/1d_stencil/1d_stencil_8.cpp, hpx/lcos/latch.hpp, hpx/lcos/local/receive_buffer.hpp, hpx/runtime/basename_registration.hpp, src/components/component_storage/component_storage.cpp, src/runtime/agas/addressing_service.cpp
- Partially reverting changes: remove changes to gather
This fixes #2121, this time for sure.
=> Fixing memory leak in example

hpx/runtime/threads/coroutines/detail/context_generic_context.hpp, tests/unit/threads/CMakeLists.txt, tests/unit/threads/stack_check.cpp
Fix #2156 
when generic context coroutines are used, the stack_remaining number reported in the threads API is wrong. Here's a fix, plus a check that when recursively calling a function the stack space decreases as we go deeper.
Note. when I run this test, it hangs on exit. Not sure why.
=> Stack check

hpx/parallel/algorithms/detail/dispatch.hpp, hpx/parallel/algorithms/for_loop.hpp, hpx/parallel/exception_list.hpp, hpx/parallel/execution_policy.hpp, hpx/parallel/util/detail/algorithm_result.hpp
This fixes 3 independent issues:
-  Fixing check for is_seq in for_loop  
-  Making sure sequential execution of algorithms is using executors as well
-  Calling timer hooks for sequential execution as well
=> Algo fixes

tests/regressions/parallel/executors/CMakeLists.txt
doing a `make tests.unit` followed by `ctest -R tests.unit` produces an error (unless you're lucky and the binary is already there from a previous build) because the regression test is run as part of the unit tests but only built as part of the regression tests.
=> Fix test categorization : regression not unit

hpx/runtime/threads/policies/queue_helpers.hpp, hpx/util/thread_description.hpp
- flyby: fix bad member initialization in thread_description
This fixes #2183.
I can confirm that this fixes the shutdown hangs I was experiencing
=> Fixing logging output not to cause hang on shutdown

hpx/runtime/serialization/input_archive.hpp, hpx/runtime/serialization/output_archive.hpp
Recent Boost (1.61.0) will expose 128-bit ints. nvcc isn't compatible with these, so any compilation of HPX-based code with nvcc will fail. This PR adds a check to the two infringing headers inside HPX to fix CUDA-enabled builds.
I don't get it why nvcc complains in the first case as those 128-bit integers aren't used in device code at all.
=> mask 128-bit ints if CUDA is being used

hpx/lcos/detail/future_data.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/applier/apply_helper.hpp, hpx/runtime/threads/thread_helpers.hpp, src/runtime/parcelset/parcelhandler.cpp, src/runtime/threads/thread_helpers.cpp
- apply_helper
- put_parcel
This should solve the stack-overflows which are assumed to cause problems like reported in #2171
=> Spawning operation on new thread if remaining stack space becomes too small

hpx/runtime/components/server/runtime_support.hpp, hpx/runtime/threads/policies/thread_queue.hpp, hpx/runtime_impl.hpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime_impl.cpp
- Replace `boost::condition` with `boost::condition_variable`
- Replace `typename Mutex::scoped_lock` with `unique_lock<Mutex>`
=> Support Boost.Thread v4

examples/quickstart/partitioned_vector_spmd_foreach.cpp, hpx/plugins/parcel/message_buffer.hpp
- flyby: fixing parcel coalescing to call put_parcels on HPX thread only
=> Fixing partitioned_vector_spmd_foreach example

examples/qt/CMakeLists.txt
Generated CXX flags included on my platform:
-I/home/mcopik/Projekty/stellar/amp/hpx_amp/hpx/examples/qt/QT4_INCLUDE_DIRS}
Now it evaluates to an empty string on my platform.
=> Fix typo in QT CMakeLists

src/runtime/components/server/runtime_support_server.cpp
The current implementation invokes the callback passed to apply_cb on the
parcelport threads, which might not be a HPX thread.
=> The indirect_packaged_task::operator() needs to be run on a HPX thread

hpx/components/containers/partitioned_vector/partitioned_vector_segmented_iterator.hpp, tests/regressions/components/CMakeLists.txt, tests/regressions/components/partitioned_vector_2201.cpp
This avoids suspension during decode_parcel (which may be called on a non-HPX-thread.
Fixes #2201
=> Delay-initialize members of partitoned iterator

hpx/include/serialization.hpp
This pull request adds the missing includes in /hpx/include/serialization.hpp
=> Adding missing includes in /hpx/include/serialization.hpp

hpx/parallel/executors/executor_parameter_traits.hpp, hpx/parallel/util/detail/chunk_size.hpp
During testing, I found that parallel::for() was regularly producing around 5000 chunks in release mode and up to 100,000 chunks in debug mode (especially when stepping through with a debugger) as the chunker uses the time for an iteration to decide how big/small to make chunks (and god forbid that the kernel suspends your thread during that initial check).
This quick fix, limits the chunk size by limiting the number of chunks to 4xCores. It's a small number and there's a strong argument that it should be bigger then 4, but unless the user is running a lot of long running tasks and startving the system of others, it should improve performance overall. I saw a noticable improvement after adding this.
I may experiment with some new parameters for the executor policy that would allow …
=> Limit number of chunks produced by iteration_shape

hpx/compute/host/block_allocator.hpp, hpx/compute/host/block_executor.hpp, hpx/runtime/threads/policies/hwloc_topology.hpp, hpx/runtime/threads/policies/noop_topology.hpp, hpx/runtime/threads/topology.hpp, hpx/util/functional/new.hpp, src/runtime/threads/policies/hwloc_topology.cpp, tests/unit/CMakeLists.txt, tests/unit/computeapi/CMakeLists.txt, tests/unit/computeapi/host/CMakeLists.txt, tests/unit/computeapi/host/block_allocator.cpp
- fixed capturing of args... for older compilers
- properly handling exceptions in bulk construction loop
- added minimal test for block_allocator
- changed to allocate page-aligned memory
=> Fixed host::block_allocator::bulk_construct

CMakeLists.txt
HPX is already using nullptr, mostly in compute. There is a test for nullptr detection, but neither it is required nor a replacement macro is provided.
We decided to require nullptr for HPX; if all compilers can handle current code, then an additional macro should not be necessary.
=> Require support for nullptr

cmake/templates/hpxcxx.in
hpxcxx uses an inappropriate HPX_COMPONENT_NAME (i.e. the name of the output so file). This leads to numerous non-intuitive compilation errors. This change fixes that. Also, invoking the shell with $() in some places and \`\` in others is inconsistent. Here I settle on use of \`\`.
=> fix issue when compiling components with hpxcxx

hpx/lcos/detail/future_data.hpp, hpx/lcos/detail/promise_base.hpp, hpx/lcos/detail/promise_lco.hpp, hpx/lcos/local/promise.hpp, hpx/lcos/packaged_action.hpp, hpx/lcos/promise.hpp
- flyby: simplify implementation of lcos::promise
=> Support for HPXCL's opencl::event

cmake/HPX_AddTest.cmake, hpx/plugins/parcelport/tcp/sender.hpp, hpx/util/asio_util.hpp, plugins/parcelport/tcp/connection_handler_tcp.cpp, src/util/asio_util.cpp, tests/unit/component/CMakeLists.txt, tests/unit/component/launch_process.cpp
These patches solve the problem of launching the test correctly, but do not address the memory access violations that occur. These could be merged in, independently of the greater fix.
I do not know how to progress with the sanitizer errors and double deletions mentioned in #2176
=> Fixing 2176

hpx/config.hpp, hpx/runtime/threads/coroutines/detail/get_stack_pointer.hpp
HPX on ppc64le:
Based on {version}: V0.9.99-trunk (AGAS: V3.0), Git: 516da8e9c4
{platform}: linux
{compiler}: GNU C++ version 6.1.0
{stdlib}: GNU libstdc++ version 20160427
Build with boost-1.60, gcc-6.1, and hwloc-1.11.3.
=> HPX on ppc64le

hpx/parallel/executors/executor_parameter_traits.hpp, hpx/parallel/executors/executor_parameters.hpp, tests/unit/serialization/serialization_custom_constructor.cpp
This fixes various problems exposed when using MSVC12 (VS2013). This also fixes the constructors for the unwrapper classes.
=> Fixing MSVC problems

hpx/parallel/executors/parallel_executor.hpp, tests/unit/parallel/task_block_executor.cpp
The current auto chunker is sub optimal in certain situations. While the static chunker isn't optimal either as it distributes evenly across cores, tests show that it still performs faster, or at least as fast as the auto chunker.
=> change default chunker of parallel executor to static one

tests/unit/component/CMakeLists.txt, tests/unit/component/components/CMakeLists.txt, tests/unit/component/components/launch_process_test_server.cpp, tests/unit/component/components/launch_process_test_server.hpp, tests/unit/component/launch_process.cpp, tests/unit/component/launched_process.cpp
- extending the existing launch_process/launched_process example to additionally test the functionality as requested by #2243
- this fixes #2243
=> This adds an example for handing over a component instance to a dynamically launched locality

hpx/util/tuple.hpp
...to not act as a copy/move-constructor
Fixes #2261
=> Constrain tuple_member forwarding constructor

tests/regressions/util/CMakeLists.txt, tests/regressions/util/use_all_cores_2262.cpp
=> Adding test verifying -Ihpx.os_threads=all

src/components/performance_counters/papi/papi_startup.cpp, src/components/performance_counters/papi/server/papi.cpp, src/components/performance_counters/papi/util/papi.cpp
=> Fixing 2277: build failure with PAPI

CMakeLists.txt, cmake/HPX_GeneratePackage.cmake
My autobuilds of LibGeoDecomp with HPX have been randomly crashing in the past weeks. They're running on multiple machines and some of these machines have a shared NFS. If one machine is running CMake for LibGeoDecomp and another machine is simultaneously deleting an HPX build tree, then CMake may fail because of some missing files. This patch enables users to switch off package registration.
It's also good practice not to clutter a user's home directory/registry and bar the user from disabling this.
=> add CMake option to disable package export

hpx/parallel/algorithms/for_loop.hpp, tests/regressions/parallel/CMakeLists.txt, tests/regressions/parallel/for_loop_2281.cpp, tests/regressions/parallel/minimal_findend.cpp
- flyby: fixing typo
This fixes #2281
=> Making sure for_loop(par, 0, N, ...) is actually executed in parallel

hpx/lcos/detail/promise_base.hpp
If set_id is present in the SharedState for promise_base, we can also
safely set id_retrieved_. This avoids a problem within hpxcl.
=> Set id_retrieved if set_id is present

hpx/util/command_line_handling.hpp, src/util/command_line_handling.cpp
=> Making sure command line warnings are printed once only

CMakeLists.txt
Fixes #2319, also fixes a typo (I believe -std=c++0y is wrong, and it should be -std=c++1y).
=> Std flag fixes

examples/1d_stencil/1d_stencil_4.cpp, examples/1d_stencil/1d_stencil_8.cpp, hpx/include/local_lcos.hpp, hpx/lcos/local/detail/sliding_semaphore.hpp, hpx/lcos/local/sliding_semaphore.hpp, tests/unit/lcos/CMakeLists.txt, tests/unit/lcos/sliding_semaphore.cpp
A sliding semaphore is similar to a counting semaphore. The difference is that it does not guard a given number of resources, but it makes sure that the difference between an upper limit (set by `signal()`) and a lower limit (passed to `wait()`) does not exceed a given maximum. The thread calling `wait()` will be suspended if the upper limit is farther away from the lower limit than the given threshold. All suspended threads will be resumed as soon as their assocuated limit is closer to the lower limit than defined by the threshold (done during during `signal()`).
This facility is useful to limit the depth of a dependency tree, for instance. See the examples `1d_stencil_4` or `1d_stencil_8` for more details on how to use it.
- adding test
- adding sliding_semaphore to stencil_1d examples
=> Adding sliding semaphore

hpx/lcos/detail/async_implementations.hpp, plugins/parcel/coalescing/coalescing_message_handler.cpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/server/locality_namespace_server.cpp
This patch fixes a few problems that occured after merging #2278:
- The locality endpoints count was not consistent when binding the GID to AGAS
- Parcel coalescing held a lock during suspension
- The destination of calls to hpx::async weren't kept alive properly
=> Fix problems that bubbled up after merging #2278

hpx/parallel/util/scan_partitioner.hpp
Parallel algorithms using the scan partitioner are spuriously failing when
the continuation in dataflow is executed asynchronously. This patch uses
the `launch::sync` to have them working. This omits any use of executors with
the scan partitioner at the moment.
This PR is providing a workaround for #2325 to make the algorithms work again, for now.
=> Making scan_partitioner work (for now)

hpx/runtime/serialization/detail/polymorphic_nonintrusive_factory.hpp
This is a workaround for a bug in CUDA 8, but since the affected code path is not performance critical, I hope this will be acceptable.
=> fix LibGeoDecomp builds with HPX + GCC 5.3.0 + CUDA 8RC

hpx/lcos/local/barrier.hpp, src/lcos/local/barrier.cpp
This patch implements the algorithm taken from
http://locklessinc.com/articles/barriers/. This fixes the hang that occasionally
occurs in the local_barrier test.
=> Fixing hpx::lcos::local::barrier

hpx/runtime/components/server/runtime_support.hpp, tests/regressions/components/CMakeLists.txt, tests/regressions/components/create_n_components_2323.cpp
- this fixes #2323
- added regression test
=> Making sure multiple components are properly initialized from arguments

hpx/lcos/channel.hpp
- Adding constructor taking future<id_type> and shared_future<id_type>
- Adding value_type typedef to make traits::is_future_range work properly
=> Making hpx::lcos::channel usable with basename registration

hpx/compute/traits/allocator_traits.hpp, hpx/compute/vector.hpp, hpx/lcos/local/channel.hpp
From the commit messages:
Fixing locking problems in hpx::lcos::channel
This patch fixes problem in the channel implementation that led to locks being
held during suspension.
Fixing hpx::compute::traits::allocator_traits and vector
- hpx::compute::traits::allocator_traits didn't work with std::allocator<T>
because it was using the pointer type instead of value_type for the initial
value
- hpx::compute::vector move operations lead to data being double freed because
the move ctor didn't set the rhs data pointer to nullptr
=> Bug fixes for hpx.compute and hpx::lcos::channel

hpx/parallel/algorithms/copy.hpp, hpx/parallel/algorithms/exclusive_scan.hpp, hpx/parallel/algorithms/inclusive_scan.hpp, hpx/parallel/algorithms/inner_product.hpp, hpx/parallel/algorithms/move.hpp, hpx/parallel/algorithms/reduce_by_key.hpp, hpx/parallel/algorithms/transform.hpp, hpx/parallel/algorithms/transform_exclusive_scan.hpp, hpx/parallel/algorithms/transform_inclusive_scan.hpp, hpx/parallel/algorithms/uninitialized_copy.hpp, hpx/parallel/util/zip_iterator.hpp, hpx/util/zip_iterator.hpp
`zip_iterator::get_iterator()` should return a reference to be symmetric to the
const overload.
This fixes the failing tests for the uninitialized copy algorithms.
=> Fixing return type of get_iterator_tuple

hpx/lcos/local/spinlock.hpp, hpx/lcos/local/spinlock_no_backoff.hpp, hpx/util/lightweight_test.hpp, src/util/lightweight_test.cpp
This fixes problems introduced by changes to `boost::detail::spinlock` in Boost V1.62
=> Fixing compilation against Boost 1 62

hpx/lcos/base_lco.hpp, hpx/lcos/base_lco_with_value.hpp, hpx/lcos/detail/future_data.hpp, hpx/lcos/server/barrier.hpp, hpx/lcos/stubs/barrier.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/actions/transfer_action.hpp, hpx/runtime/applier/apply_helper.hpp, hpx/runtime/components/server/runtime_support.hpp, hpx/util/detail/yield_k.hpp, src/lcos/barrier.cpp, src/lcos/detail/future_data.cpp, tests/performance/network/osu/osu_latency.cpp, tests/regressions/actions/component_action_move_semantics.cpp, tests/regressions/actions/plain_action_move_semantics.cpp
With this patch, direct actions are now always executed directly on the
receiving side. This means that they might get executed in a non-HPX thread.
This is a breaking change in behavior as it doesn't require direct_actions to run on HPX threads.
=> Allowing remote direct actions to be executed without spawning a task

hpx/plugins/parcelport/tcp/receiver.hpp, hpx/runtime/parcelset/parcelhandler.hpp, hpx/runtime/parcelset/parcelport.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime/parcelset/parcelhandler.cpp, src/runtime/parcelset/parcelport.cpp
- Making sure a receiver connection in the TCP parcelports waits until
the connection has been completed to get completely closed
- Make sure that no parcels are still in flight when starting the termination
detection
This completely fixes #2334
=> Fixing shutdown when parcels are still in flight

CMakeLists.txt, hpx/include/parallel_partition.hpp, hpx/parallel/algorithms/partition.hpp, hpx/parallel/algorithms/sort.hpp, hpx/parallel/exception_list.hpp, hpx/parallel/util/detail/algorithm_result.hpp, hpx/parallel/util/invoke_projected.hpp, tests/unit/parallel/algorithms/CMakeLists.txt, tests/unit/parallel/algorithms/stable_partition.cpp, tests/unit/parallel/algorithms/stable_partition_tests.hpp
=> Implemented parallel::stable_partition

hpx/lcos/detail/future_data.hpp, hpx/lcos/local/condition_variable.hpp, hpx/lcos/local/detail/condition_variable.hpp, hpx/lcos/local/latch.hpp, hpx/lcos/server/barrier.hpp, src/lcos/local/detail/condition_variable.cpp, tests/unit/lcos/counting_semaphore.cpp
We need to reaquire the lock in lcos::detail::condition_variable::wait(_until)
in order to avoid a race condition between setting the thread id to invalid
and resetting the queue entry
=> Fixing race condition in condition_variable

src/util/find_prefix.cpp
On windows, component binaries are located in 'bin'
=> Fixing find_prefixes for Windows platforms

hpx/parallel/algorithms/partition.hpp, src/exception_list.cpp
This PR is fixing stable_partition:
- Using executors to do work
- Fixing segfault happening when throwing exceptions
=> Fixing stable_partition

hpx/lcos/barrier.hpp, src/lcos/barrier.cpp, src/pre_main.cpp
This fixes the problems showing up after the scalable_barrier merge:
- Fixing multiple init
- Make sure the barrier is released in the case of terminate.
=> Barrier Fixes

hpx/util/debug/thread_stacktrace.hpp, src/util/debug/thread_stacktrace.cpp
This should help @parsa with python dumps of stacktraces
=> Add a simple utility for debugging that gives supended task backtraces

hpx/compute/vector.hpp, hpx/parallel/algorithms/copy.hpp, hpx/parallel/algorithms/move.hpp, hpx/parallel/algorithms/rotate.hpp, hpx/parallel/util/transfer.hpp
This is a purely cosmetic change to align naming conventions for the copy and move customization points
=> Renaming copy_helper/copy_n_helper/move_helper/move_n_helper

hpx/plugins/parcelport/tcp/connection_handler.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, hpx/util/connection_cache.hpp, plugins/parcelport/mpi/parcelport_mpi.cpp
This renames use_connection_cach to can_send_immediate - which is a better description, and it also adds a runtime check on top of the compile time check so that a parcelport can stop sending immediate parcels dynamically (should it wish to)
=> Can send immediate

hpx/runtime/serialization/vector.hpp
Trivial change, but that superfluous typedef was generating a lot of noise when compiling.
=> remove unused typedef to get rid of compiler warnings

hpx/runtime/threads/coroutines/coroutine.hpp, hpx/runtime/threads/coroutines/detail/context_base.hpp, hpx/runtime/threads/coroutines/detail/coroutine_self.hpp, hpx/runtime/threads/thread.hpp, hpx/runtime/threads/thread_data.hpp, hpx/runtime/threads/thread_helpers.hpp, src/runtime/threads/coroutines/detail/tss.cpp, src/runtime/threads/thread.cpp, src/runtime/threads/thread_helpers.cpp, tests/regressions/threads/CMakeLists.txt, tests/unit/threads/CMakeLists.txt
If `HPX_WITH_THREAD_LOCAL_DATA` is not defined, we now support storing a single size_t as thread local data
This also addresses part of #2371
@dhollman this should enable what you need by default and with reasonably small overheads
=> Add support for minimal thread local data

hpx/parallel/algorithms/for_loop_reduction.hpp
The current iteration value index can not be cached in the reduction helper
=> Fixing race condition in for_loop_reduction

hpx/lcos/local/condition_variable.hpp, hpx/lcos/local/spinlock_pool.hpp, hpx/runtime/applier/apply_helper.hpp, hpx/state.hpp, src/runtime/threads/detail/thread_pool.cpp, src/state.cpp
This patch fixes a race condition between creating the scheduler queues
in the thread pool and setting its state to running.
In addition, we need to wait until the thread pool is running before scheduling
tasks onto it.
Flyby: relaxing lock ignoring for condition_variable
=>  Fixing race condition for early parcels

cmake/HPX_SetupTarget.cmake
target_link_libraries in HPX_SetupTarget.cmake does not use keywords and it creates a conflict when third-party libraries (e.g. Codeplay's ComputeCpp) try to modify our targets by adding their link dependencies.
The proposition is to use PUBLIC.
=> Add keywords in target_link_libraries in hpx_setup_target

CMakeLists.txt
This PR is related to Issue #2396.
Reference: [CMP0060](https://cmake.org/cmake/help/v3.3/policy/CMP0060.html)
See commit logs.
CMP0060 will only be available for CMake versions 3.3 and newer. For CMake versions less than 3.3, a more invasive change to the HPX build system is required to introduce CMake feature 'imported libraries'.
=> Use CMake policy CMP0060

hpx/compute/cuda/detail/launch.hpp, hpx/util/detail/vtable/callable_vtable.hpp, hpx/util/invoke.hpp, hpx/util/invoke_fused.hpp
This pull request tries to solve the issue when result_of cannot deduce the return type of the callable object, i.e. it happens when the callable object is an HPX_DEVICE lambda.
=> Forward the explicitly given result_type in the hpx invoke

hpx/lcos/local/channel.hpp, hpx/lcos/local/receive_buffer.hpp
The changes allow for the entry in receive_buffer to go out of scope
without an outer lock being held. This avoids to suspend a thread while
a lock is being held.
=> Fixing locking for channel and receive_buffer

cmake/HPX_SetupTarget.cmake
Cuda needs plain target_link_libraries() signature.
A similar fix has been done previously  in 0e43777998efd0e3c07e93059d4904ac9df1f675
=> Fix issue in HPX_SetupTarget.cmake when cuda is used

src/runtime/threads/thread.cpp
This patch implements the missing hpx::this_thread::get_thread_data and
hpx::this_thread::set_thread_data
=> Implementing hpx::this_thread thread data functions

hpx/runtime/components/server/runtime_support.hpp, hpx/runtime/naming/name.hpp, hpx/util/tuple.hpp, hpx/util/unused.hpp
This patch fixes some errors due to the introduction of the constexpr specifier for certain `__host__` `__device__` or `__constant__` variables. This pull request has already been submitted under PR #2423 but was stuck with the CircleCl message 
>  Waiting for status to be reported
=> Fix nvcc errors due to constexpr specifier

hpx/components/performance_counters/papi/server/papi.hpp, hpx/runtime/agas/namespace_action_code.hpp, hpx/runtime/parcelset/locality.hpp, hpx/runtime/threads/executors/current_executor.hpp, hpx/runtime/threads/policies/callback_notifier.hpp, hpx/runtime/threads/thread.hpp, hpx/runtime/threads/thread_helpers.hpp, hpx/runtime/threads_fwd.hpp, hpx/util/coordinate.hpp
These patches contain a few patches that remove some warnings about invalid attributes and one about a class/struct mismatch.
=> Warning fixes

CMakeLists.txt, hpx/parallel/traits/detail/vc/vector_pack_alignment_size.hpp, hpx/parallel/traits/detail/vc/vector_pack_count_bits.hpp, hpx/parallel/traits/detail/vc/vector_pack_load_store.hpp, hpx/parallel/traits/detail/vc/vector_pack_type.hpp
@brycelelbach reported that this works well with Vc V2
=> Datapar backend

hpx/runtime/threads/executors/this_thread_executors.hpp
Fixed preprocessor scope to include terminating brackets for namespaces.
=> Issue 2442

hpx/config/compiler_fence.hpp, hpx/lcos/local/spinlock.hpp, hpx/lcos/local/spinlock_no_backoff.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, src/runtime/components/server/runtime_support_server.cpp, tests/performance/local/spinlock_overhead1.cpp, tests/performance/local/spinlock_overhead2.cpp
When running HPX on a larger number of threads (>64) shutdown times
were too long. This patch fixes this, by adding a shortcut in the
scheduling loop when it may exit. This happens after the dijkstra
termination detection so an early exit is fine here.
In addition, the thread count checks at shutdown have an exponential
backoff now.
=> Fixing long shutdown times

CMakeLists.txt, examples/compute/CMakeLists.txt, examples/compute/cuda/partitioned_vector.cu, hpx/components/containers/partitioned_vector/partitioned_vector_component.hpp, hpx/compute/cuda/default_executor.hpp, hpx/compute/cuda/value_proxy.hpp, hpx/compute/serialization/vector.hpp, hpx/compute/vector.hpp, hpx/config.hpp, hpx/config/compiler_specific.hpp, hpx/config/export_definitions.hpp, hpx/config/forceinline.hpp, hpx/lcos/base_lco.hpp, hpx/lcos/base_lco_with_value.hpp, hpx/parallel/algorithms/count.hpp, hpx/parallel/algorithms/for_each.hpp, hpx/parallel/algorithms/transform.hpp, hpx/runtime/actions/plain_action.hpp, hpx/runtime/components/server/managed_component_base.hpp, hpx/runtime/components/server/runtime_support.hpp, hpx/runtime/serialization/input_archive.hpp, hpx/runtime/serialization/output_archive.hpp, hpx/traits/get_function_address.hpp, hpx/traits/is_iterator.hpp, hpx/util/bind.hpp, hpx/util/deferred_call.hpp, hpx/util/protect.hpp, hpx/util/tuple.hpp
This patch tries to remove some compilation errors around partitioned_vector when it is used in cuda clang code. Major changes are : 
- Replacing the checking of defined `__NVCC__` by the checking of both defined `__NVCC__` and defined `__CUDACC__` to compile Cuda code with NVCC and CudaClang in the same conditions
- Avoid some action registrations when compiling in device mode
=> Some fixes around cuda clang partitioned_vector example

hpx/lcos/dataflow.hpp, hpx/lcos/detail/future_data.hpp, hpx/lcos/future.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/lcos/wait_all.hpp, hpx/lcos/when_all.hpp, hpx/lcos/when_each.hpp, hpx/runtime/components/client_base.hpp, hpx/traits/future_access.hpp, tests/unit/lcos/future.cpp
Assigning any `future<T>` to `future<void>` does not require any allocation nor any atomic increfs anymore
=> Downcast to future<void>

docs/manual/existing_performance_counters.qbk, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/detail/thread_pool.hpp, hpx/runtime/threads/threadmanager_impl.hpp, src/runtime/threads/detail/thread_pool.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/threadmanager.cpp
This adds a performance counter which acts as a complement to the idle-rate counter by exposing the current percentage of scheduler threads executing hpx-threads.
=> Adding performance counter exposing instantaneous scheduler utilization

docs/manual/consuming_performance_counters.qbk
Fixing errors in the performance counter documentation.
=> Perf docs update

examples/compute/cuda/CMakeLists.txt, hpx/components/containers/partitioned_vector/partitioned_vector_component.hpp, hpx/parallel/algorithms/for_each.hpp
This patch :
- Properly compiles the new cuda example `cublas_matmult`
- Fixes issue when `for_each` is used in Cuda code
=> Some fixes around hpx compute

hpx/runtime/threads/policies/thread_queue.hpp
- this lessens the scheduler's stealing overheads
=> Changing scheduler to steal only if more than a minimal number of tasks are available

hpx/util/query_counters.hpp, src/util/parse_command_line.cpp, src/util/query_counters.cpp
- this suppresses any generated output (useful when using with ITT or APEX)
=> Extending command line option --hpx:print-counter-destination to support value 'none'

docs/manual/existing_performance_counters.qbk, hpx/config.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/detail/thread_pool.hpp, hpx/runtime/threads/threadmanager_impl.hpp, src/runtime/threads/detail/thread_pool.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/threadmanager.cpp
Those counters are available as
```
/scheduler{counter-instance}/idle-loop-count/instantaneous
/scheduler{counter-instance}/busy-loop-count/instantaneous
```
where `counter-instance` could be `locality#N/total` or `locality#N/worker-thread#M`.
=> Adding performance counters exposing the internal idle and busy-loop counters

docs/manual/config_defaults.qbk, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/policies/hierarchy_scheduler.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, hpx/runtime/threads/policies/static_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/static_queue_scheduler.hpp, hpx/runtime/threads/policies/thread_queue.hpp, hpx/runtime/threads/policies/throttle_queue_scheduler.hpp, src/util/runtime_configuration.cpp
- this value is exposed as `hpx.thread_queue.min_tasks_to_steal_pending`, default is zero
- flyby: renamed the same value for staged tasks to `hpx.thread_queue.min_tasks_to_steal_staged`
=> Enable controlling amount of pending threads which must be available to allow thread stealing

docs/manual/commandline.qbk, hpx/performance_counters/performance_counter_set.hpp, hpx/util/query_counters.hpp, src/hpx_init.cpp, src/performance_counters/performance_counter_set.cpp, src/util/command_line_handling.cpp, src/util/parse_command_line.cpp, src/util/query_counters.cpp
- this is similar to `--hpx:print-counter` except that it additionally resets the counter after it was queried
- flyby: fix ITT domain for itt-counter
=> Adding new command line option --hpx:print-counter-reset

examples/quickstart/component_with_executor.cpp, hpx/include/components.hpp, hpx/runtime/components/server/executor_component.hpp
- all actions will be executed in the context of this executor
=> Adding component base class which ties a component instance to a given executor

docs/manual/config_defaults.qbk, hpx/lcos/detail/future_data.hpp, hpx/lcos/local/spinlock.hpp, hpx/runtime/threads/detail/create_thread.hpp, hpx/runtime/threads/detail/create_work.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/detail/set_thread_state.hpp, hpx/runtime/threads/policies/thread_queue.hpp, hpx/runtime/threads/thread_data.hpp, hpx/runtime/threads/thread_enums.hpp, hpx/util/detail/yield_k.hpp, src/lcos/local/mutex.cpp, src/util/runtime_configuration.cpp
This reschedules a thread waiting (being suspended) on a spinlock right away without having to wait to get through the whole thread queue.
=> Allowing for plain suspend to reschedule thread right away 

hpx/plugins/parcelport/mpi/receiver.hpp, hpx/plugins/parcelport/mpi/receiver_connection.hpp, hpx/plugins/parcelport/mpi/sender_connection.hpp, hpx/plugins/parcelport/mpi/tag_provider.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/actions/trigger.hpp, hpx/runtime/agas/component_namespace.hpp, hpx/traits/get_function_address.hpp, hpx/util/tuple.hpp
Only tuple_impl<Is, Ts...> should be bitwise serialized
Flyby: Cleaning up MPI parcelport.
=> Fix tuple serialization

hpx/compute/serialization/vector.hpp, hpx/runtime/serialization/array.hpp, hpx/runtime/serialization/complex.hpp, hpx/runtime/serialization/detail/boost_simd.hpp, hpx/runtime/serialization/detail/libflatarray.hpp, hpx/runtime/serialization/detail/vc.hpp, hpx/runtime/serialization/map.hpp, hpx/runtime/serialization/vector.hpp, hpx/util/tuple.hpp, src/runtime/naming/address.cpp
This fixes a whole set of problems we were seeing lately. This is an important patch which should be merged as soon as possible.
=> Fixing bit-wise (zero-copy) serialization

hpx/plugins/parcelport/mpi/receiver.hpp, hpx/plugins/parcelport/mpi/sender.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, src/lcos/barrier.cpp, tests/performance/network/CMakeLists.txt, tests/performance/network/pingpong_performance.cpp
This PR fixes:
- Performance problems with the MPI Parcelport
- Locks held during suspension for condition_variable and during migration
- Scheduling of the background work threads
=> MPI Parcelport improvements and fixes related to the background work changes

hpx/lcos/local/condition_variable.hpp, src/runtime/agas/server/primary_namespace_server.cpp
- Properly releasing internal lock in condition variable before locking
the externally provided one again
- Ignore migration lock before notifying about ended migration process.
=> Fixing locks held during suspension:

hpx/lcos/barrier.hpp, hpx/runtime/actions/base_action.hpp, hpx/runtime/actions/transfer_action.hpp, hpx/runtime/actions/transfer_continuation_action.hpp, hpx/runtime/parcelset/decode_parcels.hpp, hpx/runtime/parcelset/parcel.hpp, src/lcos/barrier.cpp, src/runtime/agas/big_boot_barrier.cpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime/parcelset/parcel.cpp, src/runtime_impl.cpp
Due to the recent changes in executing background_work in an HPX thread,
parcel decoding could create a deadlock when a direct actions suspends
and there are more parcels to decode and schedule. This patch remedies
this situation.
This fixes #2516.
=> Fixing parcel scheduling

hpx/lcos/detail/future_data.hpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/shared_future_continuation_order.cpp
Continuations are now invoked in the same order as they were attached
- flyby: remove superfluous typename keyword
This fixes #2504
=> Making sure that all continuations of a shared_future are invoked in order

docs/manual/build_system.qbk
Added a small paragraph to document signal and exception disable switch of the build system. And more general, how to debug an hpx application with the help of a core file.
I'm pretty sure I didn't put that into a file where it really makes sense, I'm creating this pull request to get the process started.
(Also, Circle CI will likely complain, I couldn't get the documentation creation set up on my system.)
=> Added documentation for debugging with core files

examples/1d_stencil/1d_stencil_6.cpp, examples/1d_stencil/1d_stencil_7.cpp, examples/1d_stencil/1d_stencil_8.cpp, examples/quickstart/shared_mutex.cpp, hpx/lcos/gather.hpp, hpx/parallel/util/foreach_partitioner.hpp, hpx/runtime/parcelset/put_parcel.hpp, src/lcos/barrier.cpp
This patch tries to remove some warnings related to unused captured variables detected by Clang 5.0. Because most of those variables are copied via lambda capture for lifetime purpose, `HPX_UNUSED()` has been used.
=> Remove warnings related to unused captured variables

hpx/lcos/future.hpp, hpx/runtime/parcelset/parcel.hpp, hpx/runtime/serialization/detail/preprocess.hpp, hpx/runtime/serialization/output_archive.hpp, src/runtime/serialization/output_archive.cpp
Instead of looking up the gid_type by the GID, the split_gid mechanism is now
using the address of gid_type, which is owned by id_type.
Flyby: Fixing minor inconsistency during future serialization.
=> Fixing handling of GIDs during serialization preprocessing

hpx/include/actions.hpp, hpx/runtime/actions/lambda_to_action.hpp, tests/regressions/actions/async_deferred_1523.cpp, tests/regressions/actions/make_continuation_1615.cpp, tests/regressions/actions/plain_action_1330.cpp, tests/regressions/actions/plain_action_1550.cpp, tests/regressions/actions/plain_action_move_semantics.cpp
This PR tries to give some facilities to create actions from lambdas. It is inspired from the trick explained in http://pfultz2.com/blog/2014/09/02/static-lambda/. The constraints for the lambda are :
- No captured variables (property checked via `static_assert()`)
- Parameters passed by value (similarly to global functions that are converted into actions)
=> Facilities to create actions from lambdas

cmake/HPX_GeneratePackage.cmake, cmake/templates/hpx_bazel_defs.bzl.in, cmake/templates/hpx_bazel_defs_debug.bzl.in
This PR adds the output of a Bazel Skylark extension for all relevant HPX compile options and paths to be able to use them from inside a Bazel project.
=> Add output of a Bazel Skylark extension for paths and compile options

CMakeLists.txt, cmake/HPX_Option.cmake
This branch does two things:
- it makes HPX_WITH_MALLOC non-advanced, so it is eaier to find e.g. in cmake-gui, which is good since probably most users have to modify this settings
- it adds an STRINGS keyword to hpx_option(), and uses this to set the STRINGS cache property, so that the options are presented in a combobox in cmake-gui (and so really easy to select). Use this for HPX_WITH_MALLOC.
=> Make HPX_WITH_MALLOC easier to use

hpx/parallel/traits/detail/vc/vector_pack_load_store.hpp
Oddly, didn't catch this until compiling with Clang.
=> Fix uses of the Vc2 datapar flags; the value, not the type, should be passed to functions.

hpx/config/compiler_specific.hpp
This patch tries to solve the issue because `HPX_HAVE_CUDA` is tested in compiler_specific.hpp
=> Pre-include defines.hpp to get the macro HPX_HAVE_CUDA value

hpx/runtime/components/server/runtime_support.hpp, src/runtime/components/server/runtime_support_server.cpp
This fixes an issue with disconnecting a locality if other localities were connected dynamically as well
=> Fixing issue with disconnect

CMakeLists.txt, docs/manual/config_defaults.qbk, hpx/plugins/parcelport_factory.hpp, plugins/binary_filter/CMakeLists.txt, plugins/parcel/CMakeLists.txt, plugins/parcelport/CMakeLists.txt, plugins/parcelport/mpi/mpi_environment.cpp, plugins/parcelport/mpi/parcelport_mpi.cpp, plugins/parcelport/tcp/connection_handler_tcp.cpp, plugins/parcelport/tcp/parcelport_tcp.cpp, plugins/parcelport/verbs/parcelport_verbs.cpp, plugins/parcelport/verbs/rdma/rdma_controller.cpp, src/runtime/agas/addressing_service.cpp, src/runtime/parcelset/parcelhandler.cpp, src/runtime/parcelset/parcelport.cpp, src/util/command_line_handling.cpp, src/util/runtime_configuration.cpp
This allows to completely disable networking which is useful either if all the user needs is a purely local solution or if HPX is to be combined with legacy MPI code. In the latter case HPX would be run on each of the ranks in console mode and all communication would be left to other solutions.
=> Add configuration option to disable networking

hpx/runtime/threads/policies/hwloc_topology_info.hpp, hpx/runtime/threads/policies/topology.hpp, src/runtime/threads/policies/hwloc_topology_info.cpp, src/runtime/threads/policies/parse_affinity_options.cpp
Rename hwloc_topology to hwloc_topology_info to avoid accidental clashes with hwloc macros
This fixes #2509
=> Rename hwloc_topology to hwloc_topology_info

hpx/parallel/traits/detail/vc/vector_pack_alignment_size.hpp, hpx/parallel/traits/detail/vc/vector_pack_count_bits.hpp, hpx/parallel/traits/detail/vc/vector_pack_load_store.hpp, hpx/parallel/traits/detail/vc/vector_pack_type.hpp, hpx/runtime/serialization/detail/vc.hpp
Change the Vc preprocessor version check from #if Vc_IS_VERSION_1 to #if defined(Vc_IS_VERSION_1) && Vc_IS_VERSION_1; otherwise we would get warnings under -Wundef.
See STEllAR-Group/octotiger/#48 for more info.
=> Prevent -Wundef warnings on Vc version checks.

examples/compute/cuda/cublas_matmul.cpp
This patch tries to remove warnings related to cast from `float` to `double` in `cublas_matmul.cpp`
=> Remove warnings due to float precisions

hpx/parallel/util/scan_partitioner.hpp
This is based from a solution as proposed by @sithhell. It fixes the test failures around `scan_by_key` we're currently seeing.
=> Fixing scan partitioner

examples/compute/cuda/CMakeLists.txt
This patch tries to remove a compilation error due to the limitations of nvcc when compiling `partitioned_vector.cu`
=> Remove partitioned_vector.cu from build tree when nvcc is used

examples/compute/cuda/hello_compute.cu, hpx/compute/cuda/default_executor.hpp, hpx/compute/cuda/target_ptr.hpp, hpx/compute/cuda/value_proxy.hpp, hpx/compute/serialization/vector.hpp, hpx/lcos/base_lco.hpp, hpx/lcos/base_lco_with_value.hpp, hpx/lcos/server/latch.hpp, hpx/parallel/algorithms/detail/predicates.hpp, hpx/parallel/algorithms/for_loop.hpp, tests/unit/computeapi/cuda/default_executor.cu, tests/unit/computeapi/cuda/for_each_compute.cu, tests/unit/computeapi/cuda/for_loop_compute.cu, tests/unit/computeapi/cuda/transform_compute.cu, tests/unit/computeapi/host/CMakeLists.txt
This patch tries to fix some compilation errors that come from both nvcc and cuda-clang for computeapi unit tests
=> Fix computeapi unit tests

src/runtime/agas/addressing_service.cpp, src/runtime/agas/big_boot_barrier.cpp
Attempt to resolve the miracle of `resolve_locality` being called excessively often. 
Essentially this makes sure that all locality endpoints get properly cached on locality 0 as well.
=> Attempt to resolve resolve_locality

src/util/command_line_handling.cpp
This PR picks up hpx.ignore_batch_env from the config map.
=> Pick up hpx.ignore_batch_env from config map

hpx/parallel/algorithms/adjacent_difference.hpp, hpx/parallel/algorithms/all_any_none.hpp, hpx/parallel/algorithms/copy.hpp, hpx/parallel/algorithms/equal.hpp, hpx/parallel/algorithms/exclusive_scan.hpp, hpx/parallel/algorithms/inclusive_scan.hpp, hpx/parallel/algorithms/is_partitioned.hpp, hpx/parallel/algorithms/is_sorted.hpp, hpx/parallel/algorithms/remove_copy.hpp, hpx/parallel/algorithms/transform_exclusive_scan.hpp, hpx/parallel/algorithms/transform_inclusive_scan.hpp, hpx/parallel/algorithms/transform_reduce_binary.hpp, hpx/parallel/segmented_algorithms/detail/scan.hpp, hpx/parallel/util/partitioner.hpp, hpx/parallel/util/partitioner_with_cleanup.hpp, hpx/parallel/util/scan_partitioner.hpp, tests/unit/parallel/algorithms/exclusive_scan.cpp, tests/unit/parallel/algorithms/inclusive_scan_tests.hpp, tests/unit/parallel/algorithms/reduce_.cpp, tests/unit/parallel/algorithms/transform_exclusive_scan.cpp, tests/unit/parallel/algorithms/transform_inclusive_scan.cpp, tests/unit/parallel/algorithms/transform_reduce.cpp
This patch tries to remove some warnings related to unused captured variables detected by Clang 5.0. Because most of those variables are copied via lambda capture for lifetime purpose, HPX_UNUSED() has been used. Also warnings are generated when local const variables are captured by value;  some of those variables are then declared non-const in place of const.
=> Remove warnings due to some captured variables

docs/manual/commandline.qbk, hpx/performance_counters/performance_counter_set.hpp, hpx/util/query_counters.hpp, src/hpx_init.cpp, src/performance_counters/performance_counter_set.cpp, src/util/parse_command_line.cpp, src/util/query_counters.cpp
Add commandline options `--hpx:print-counters-locally` which forces each locality to print only its own counters
=> Add commandline options --hpx:print-counters-locally 

CMakeLists.txt, src/runtime/threads/topology.cpp
We have found that setting the thread NICE level high causes a significant performance drop. This patch sets it to OFF by default, but allows the user to turn it on.
=> Make thread NICE level setting an option

tools/roll_release.sh
Most Linux distribution don't have 7zr command, but almost all of them have 7za as well as Rostam's ContOS. 7za uses same syntax as 7zr
=> chaning 7zip command to 7za in roll_release.sh

CMakeLists.txt
=> Work around MSVC having an ICE when compiling with -Ob2

hpx/runtime/actions/transfer_action.hpp, hpx/runtime/actions/transfer_continuation_action.hpp
Instead of moving the argument in the pack expansion, we should rather move
the argument element we expanded...
=> Fixing transfer_(continuation)_action::schedule

hpx/parallel/spmd_block.hpp, tests/unit/parallel/CMakeLists.txt, tests/unit/parallel/spmd_block.cpp
This PR tries to introduce code related to _spmd_block_ that was presented here http://stellar.cct.lsu.edu/pubs/extending_cpp_with_coarray_semantics_2016.pdf
A major difference in comparaison to what was presented in that paper is that _an image_ is no longer considered as a computation located in an _explicit_ locality. It is now a simple sequential computation able to cooperate with other ones.
=> First attempt to introduce spmd_block in hpx

CMakeLists.txt, hpx/lcos/dataflow.hpp, hpx/lcos/detail/future_data.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/lcos/local/packaged_task.hpp, hpx/runtime/serialization/detail/vc.hpp, hpx/runtime/threads/coroutines/coroutine.hpp, hpx/runtime/threads/coroutines/detail/context_base.hpp, hpx/runtime/threads/coroutines/detail/coroutine_self.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/thread_data.hpp, hpx/runtime/threads/thread_data_fwd.hpp, hpx/util/apex.hpp, src/runtime/threads/thread_data.cpp
This branch adds the APEX data pointer, and matches up with APEX release 1.2, tagged in the APEX git repo as v1.2.
Hartmut - for the APEX release "blurb" text: This release includes OTF2 support, updated TAU integration, enhanced support for HPX threads calling direct actions, updated policy support, updated HPX counter integration, HPX send/recv measurement, new scatterplot output, and performance optimizations and bug fixes.
=> Adding apex data

CMakeLists.txt, cmake/HPX_SetupBoost.cmake, docs/whats_new.qbk, hpx/compat/barrier.hpp, hpx/compat/condition_variable.hpp, hpx/compat/mutex.hpp, hpx/compat/thread.hpp, hpx/runtime/threads/detail/thread_pool.hpp, src/CMakeLists.txt, src/compat/compat_barrier.cpp, src/runtime/threads/detail/thread_pool.cpp, tests/performance/local/CMakeLists.txt, tests/performance/local/boost_tls_overhead.cpp, tests/performance/local/delay_baseline_threaded.cpp, tests/performance/local/native_tls_overhead.cpp, tests/performance/local/nonconcurrent_fifo_overhead.cpp, tests/performance/local/nonconcurrent_lifo_overhead.cpp, tools/inspect/deprecated_include_check.cpp, tools/inspect/deprecated_name_check.cpp
@biddisco I added you as a potential reviewer as we don't know whether Boost.Log requires linking with Boost.Thread (which might be disabled now).
=> Compat fixes

hpx/runtime/parcelset/decode_parcels.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, plugins/parcel/coalescing/coalescing_message_handler.cpp, plugins/parcelport/verbs/parcelport_verbs.cpp, src/lcos/local/detail/condition_variable.cpp, src/runtime/agas/big_boot_barrier.cpp, src/util/pool_timer.cpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/barrier_hang.cpp
This patch fixes a hang observed with certain usages of `hpx::lcos::barrier`.
Flybys:
- Fixing one lock held during suspension error
- Fixing race condition for pre caching localities
=> Barrier hang

hpx/config/compiler_specific.hpp, hpx/lcos/detail/future_data.hpp, hpx/runtime/actions/basic_action.hpp, hpx/util/itt_notify.hpp, hpx/util/plugin/detail/dll_windows.hpp, hpx/util/plugin/dll.hpp, src/components/process/util/windows/search_path.cpp, src/runtime/threads/policies/hwloc_topology_info.cpp
Tested on win7x64 with msys2, mingw-w64, gcc 6.3.0, cmake 1.8.
CMake was called with the following parameters:
```
cmake
-G "MSYS Makefiles"
-DHPX_WITH_TESTS_EXTERNAL_BUILD=Off
-DHPX_WITH_MALLOC=jemalloc
-DCMAKE_INSTALL_PREFIX:PATH=/c/msys64/mingw64 ..
```
=> Fixed build for mingw.

cmake/HPX_SetupBoost.cmake, docs/manual/build_system/prerequisites.qbk, hpx/config.hpp
- flyby: raise minimal required boost version to 1.51 to guarantee existence of boost.context
=> We need to link with boost.thread and boost.chrono if we use boost.context

docs/hpx.idx, hpx/runtime/components/new.hpp, hpx/runtime/components/server/create_component.hpp, hpx/runtime/components/server/create_component_fwd.hpp, hpx/runtime/components/server/managed_component_base.hpp, hpx/runtime/components/server/runtime_support.hpp, hpx/runtime/components/server/simple_component_base.hpp, tests/unit/component/CMakeLists.txt, tests/unit/component/local_new.cpp
- this is equivalent to `hpx::new_<>(find_here(), ...)`, except that it allows
for non-copyable and non-movable argument types and guarantees purely local
operation
- also adding test
- flyby: #ifdef extended friend declarations in simple_component_base
- flyby: fix destruction of components if id couldn't be assigned
- flyby: fixing error messages generated if id couldn't be assigned
=> Adding `hpx::local_new`

hpx/runtime/serialization/detail/preprocess.hpp, hpx/runtime/serialization/output_container.hpp
This patch tries to solve some compilation errors related to gcc 4.9 because it does not accept `constexpr void` functions
This fixes #2638
=> Fix issue #2638

CMakeLists.txt, cmake/HPX_CreateSymbolicLink.cmake, cmake/scripts/create_symbolic_link.bat, docs/CMakeLists.txt
Use cmd under windows to create links
* Prevents errors when generating the documentation
on windows since cmake doesn't provide the
`create_symlink` there.
See the following screenshot:
Further reference of `create_symlink <old> <new>`: https://cmake.org/cmake/help/v3.2/manual/cmake.1.html#unix-specific-command-line-tools
=> Fix cmake soft errors due to failing creation of links on windows

hpx/components/iostreams/ostream.hpp, hpx/util/logging/defaults.hpp, hpx/util/logging/detail/scoped_log.hpp, hpx/util/logging/detail/time_format_holder.hpp, hpx/util/logging/format/destination/defaults.hpp, hpx/util/logging/format/formatter/time_strf.hpp, hpx/util/plugin/detail/dll_windows.hpp, src/util/find_prefix.cpp
- flyby: Fixed typo in iostreams type declaration
- flyby: rename leftover BOOST_ names in logging library
=> Making sure UNICODE on Windows does not break by default

examples/transpose/transpose_await.cpp, hpx/lcos/detail/future_await_traits.hpp, hpx/lcos/detail/future_data.hpp, hpx/lcos/future.hpp, hpx/util/await_traits.hpp, tests/unit/lcos/await.cpp
- adapt specializations of coroutine_traits to latest changes
- properly propagate exceptions through co_await
- flyby: fix co_await future<future<T>>
- flyby: change return to co_return where appropriate
=> Fixing code supporting co_await

docs/manual/parallel_algorithms.qbk
Fix the order of the transform algorithm within table 18, so that it appears at the end of the table, in alphabetical order.  The remainder of the algorithm names are sorted and it is extremely confusing when looking for this algorithm, since it is in an unexpected location.
=> Update docs (Table 18) - move transform to end

examples/quickstart/local_channel.cpp, hpx/lcos/detail/future_await_traits.hpp, hpx/lcos/detail/future_data.hpp, hpx/lcos/future.hpp, hpx/lcos/local/channel.hpp, hpx/lcos/local/futures_factory.hpp, hpx/lcos/local/packaged_task.hpp, tests/unit/lcos/await.cpp, tests/unit/lcos/channel_local.cpp
- refactored local channel implementation
- channel::set is now optionally asynchronous
- adding asynchronous iterator support to channel
=> Add lcos::local::one_element_channel

docs/CMakeLists.txt, docs/hpx.idx, hpx/util/invoke.hpp, hpx/util/invoke_fused.hpp
* Clearify the meaning of `invoke_fused` through
using `invoke_fused_r` instead of the internal implementation.
=> Add documentation to invoke_fused and friends NFC.

cmake/templates/autodoc.doxy.in
I tested this through wrapping the `when_all_n` function inside a namespace called `detail` -> the function disappeared from the documentation.
=> Hide the `detail` namespace in doxygen per default

hpx/lcos/local/spmd_block.hpp, hpx/lcos/spmd_block.hpp, hpx/parallel/spmd_block.hpp, hpx/util/first_argument.hpp, tests/unit/lcos/CMakeLists.txt, tests/unit/lcos/global_spmd_block.cpp, tests/unit/parallel/spmd_block.cpp
This patch tries to implement a distributed version of `define_spmd_block()`.Here are the following changes:
- local `define_spmd_block()` and local `spmd_block()` have been moved to `hpx::lcos::local`
- `hpx::parallel::v2::spmd_block` is now defined as a type alias
- `hpx::parallel::v2::define_spmd_block()` is now wrapping a call to `hpx::lcos::local::define_spmd_block()`
- global `define_spmd_block()` and global `spmd_block()`  (based on `broadcast` and `hpx::lcos::barrier` ) added and located in `hpx::lcos`
=> Distributed define_spmd_block

docs/CMakeLists.txt, docs/hpx.idx, hpx/util/unwrapped.hpp
* Also add some internal comments for improved guidance
The documentation was kept very general so it can be easily extended with the capabilities that are introduced as part of my GSoC project.
=> Add documentation to hpx::util::unwrapped and hpx::util::unwrapped2.

hpx/lcos/future.hpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/fail_future_2667.cpp, tests/regressions/lcos/future_2667.cpp
- adding corresponding tests
- this fixes #2667
=> Inhibit direct conversion from future<future<T>> --> future<void>

hpx/runtime/serialization/container.hpp, hpx/runtime/serialization/output_archive.hpp, hpx/runtime/serialization/output_container.hpp
The archive size only grows if the data is written into the container,
when chunks are added, we do not need to increment the size of the
archive itself.
This fixes a bug where the archive containter is allocated with a much
larger size than needed.
=> Fix bad size during archive creation

hpx/util/tuple.hpp, tests/unit/util/tuple.cpp
Didn't run the test suite on it yet, let's see how it goes.
=> Add support of std::array to hpx::util::tuple_size and tuple_element

hpx/runtime/threads/policies/throttling_scheduler.hpp
This patch adds the missing condition variable member in the case when
HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF is turned OFF.
This fixes #2682
=> Allowing throttling scheduler to be used without idle backoff

hpx/plugins/parcelport/mpi/sender.hpp, hpx/plugins/parcelport/mpi/sender_connection.hpp, hpx/plugins/parcelport/tcp/sender.hpp, hpx/runtime/parcelset/parcelport_connection.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, plugins/parcelport/libfabric/parcelport_libfabric.cpp, plugins/parcelport/libfabric/sender.cpp
This patch is properly releasing handlers used when sending a parcel. This avoids
possible memory leaks. In addition, a race between sending a new parcel and
calling the postprocess handler was fixed.
This is the proper fix for the problems appearing after merging #2619 and should make #2692 unnecessary.
=> Properly releasing parcelport write handlers.

.clang-format
This fixes #2703 
Please see usage guidelines in the file itself
=> Adding .clang-format file

hpx/parallel/task_block.hpp
Prevent multiple definition issue when file is included in multiple translation units, fixes #2707
=> Add inline to prevent multiple definition issue

CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/HPX_AddDefinitions.cmake, cmake/HPX_GeneratePackage.cmake, plugins/parcelport/CMakeLists.txt
Something I came across while working on my GSoC Project:
As stated by https://cmake.org/Wiki/CMake_Useful_Variables CMAKE_FILES_DIRECTORY contains a leading slash already, and should be used as following with the current binary directory:  `${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}`.
Otherwise this will lead to paths with double slashes.
I did find & replace, probably this should work if the CI reports green.
=> Remove slashes before CMAKE_FILES_DIRECTORY variables

hpx/components/containers/partitioned_vector/detail/make_index_sequence.hpp, hpx/components/containers/partitioned_vector/detail/view_element.hpp, hpx/components/containers/partitioned_vector/partitioned_vector_local_view.hpp, hpx/components/containers/partitioned_vector/partitioned_vector_local_view_iterator.hpp, hpx/components/containers/partitioned_vector/partitioned_vector_view.hpp, hpx/components/containers/partitioned_vector/partitioned_vector_view_iterator.hpp, tests/unit/component/CMakeLists.txt, tests/unit/component/partitioned_vector_subview.cpp, tests/unit/component/partitioned_vector_view.cpp, tests/unit/component/partitioned_vector_view_iterator.cpp
This PR proposes to add _spmd multidimensionnal view_ functionalities to manage segments of `partitioned_vector`. The added features include:
- View constructions from` partitioned_vector` iterators : 
example: `hpx::partitioned_vector_view<double,2> view (block, v.begin(), v.end(), {height,width} )`, with `block ` being a `spmd_block`, `v` being a `partitioned_vector` and height and width being integral values
- _Put_ operations (in MPI sense) allowed via the expression `a(i,j) = b(i,j)` or ` a(i,j) = some_std_vector`
- _Get_ operations (in MPI sense) allowed via an explicit conversion : 
`std::vector<T> v = ( std::vector<T> ) a(i,j)`
- _iterators_ to iterate globally (or locally) over the segments covered by the view
=> Integrate spmd multidimensionnal views for partitioned_vectors

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx17_fallthrough_attribute.cpp, hpx/config.hpp, hpx/config/attributes.hpp, hpx/util/jenkins_hash.hpp
Adds a feature test for C++17 `[[fallthrough]]` and removes gcc 7.1 warnings complaining about a possible fallthrough.
=> Config support for fallthrough attribute

docs/manual/applying_actions.qbk, docs/manual/build_system/using_hpx_pkgconfig.qbk
Several examples in the documentation of Action were using incorrect (old ?) syntax.
Notably, arguments to `hpx::async_continue` were passed in the wrong order in section _Applying an Action with a Continuation and with Synchronization_, and `bad_argument` should have been `bad_parameter` in _Action Error Handling_.
I have tested all the updated examples, however I have not rebuilt the documentation, so feel free to make any necessary changes.
=> Fix examples in Action documentation

hpx/components/containers/partitioned_vector/partitioned_vector_view.hpp, tests/unit/component/partitioned_vector_subview.cpp
This patch fixes some msvc `debug vector iterator + offset out of range` issue in `partitioned_vector_subview` test
=> Fixing 2735

hpx/runtime/components/component_factory.hpp, hpx/runtime/components/component_factory_base.hpp, hpx/runtime/components/derived_component_factory.hpp, hpx/runtime/components/server/create_component.hpp, hpx/runtime/components/server/create_component_fwd.hpp, hpx/runtime/components/server/fixed_component_base.hpp, hpx/runtime/components/server/managed_component_base.hpp, hpx/runtime/components/server/migration_support.hpp, hpx/runtime/components/server/runtime_support.hpp, hpx/runtime/components/server/simple_component_base.hpp
=> Adding on_migrated event handler to migratable component instances

docs/manual/existing_performance_counters.qbk, hpx/performance_counters/server/statistics_counter.hpp, src/performance_counters/registry.cpp, src/performance_counters/server/statistics_counter.cpp
- This adds an additional (optional) parameter to the statistics counter names allowing
to specify whether the underlying counter should be reset during evaluation.
- This also improves error reporting related to the parameters specified for statistics
counters
- this fixes #2743
=> Adding ability to statistics counters to reset base counter

docs/manual/existing_performance_counters.qbk, hpx/performance_counters/counters.hpp, hpx/performance_counters/performance_counter_set.hpp, hpx/performance_counters/registry.hpp, hpx/performance_counters/server/arithmetics_counter_extended.hpp, src/performance_counters/counters.cpp, src/performance_counters/performance_counter_set.cpp, src/performance_counters/registry.cpp, src/performance_counters/server/arithmetics_counter.cpp, src/performance_counters/server/arithmetics_counter_extended.cpp, src/performance_counters/server/raw_counter.cpp, src/performance_counters/server/statistics_counter.cpp, src/runtime.cpp
- this adds 5 new performance counters:
`/arithmetics/mean`, `/arithmetics/variance`, `/arithmetics/median`,
`/arithmetics/min`, and `/arithmetics/max`
all of which will calculate the given statistics over a set of
counters specified as counter parameters, for instance:
`/arithmetics/mean@/threadqueue{locality#0/worker-thread#*}/length`
which calculates the average queue length for all worker threads
=> Adding extended arithmetic performance counters

docs/CMakeLists.txt, docs/manual/parallel_algorithms.qbk, hpx/include/parallel_unique.hpp, hpx/parallel/algorithms/partition.hpp, hpx/parallel/algorithms/unique.hpp, hpx/parallel/container_algorithms/unique.hpp, tests/performance/parallel_algorithms/local/CMakeLists.txt, tests/performance/parallel_algorithms/local/benchmark_partition_copy.cpp, tests/performance/parallel_algorithms/local/benchmark_unique_copy.cpp, tests/unit/parallel/algorithms/CMakeLists.txt, tests/unit/parallel/algorithms/is_heap.cpp, tests/unit/parallel/algorithms/is_heap_until.cpp, tests/unit/parallel/algorithms/unique_copy.cpp, tests/unit/parallel/algorithms/unique_copy_tests.hpp, tests/unit/parallel/container_algorithms/CMakeLists.txt, tests/unit/parallel/container_algorithms/unique_copy_range.cpp
Check Box
---------------
=> The parallel version is faster than the sequential version, but not satisfying.
=> Implement parallel::unique_copy.

docs/manual/vector.qbk, examples/quickstart/customize_async.cpp, examples/throttle/throttle/server/throttle.cpp, hpx/runtime/actions/action_priority.hpp, hpx/runtime/actions/action_support.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/threads/detail/create_thread.hpp, hpx/runtime/threads/detail/create_work.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, hpx/runtime/threads/thread_enums.hpp, plugins/parcelport/verbs/parcelport_verbs.cpp, src/runtime/threads/threadmanager.cpp, tests/regressions/threads/resume_priority.cpp
Introducing explicit high priority and high priority (recursive) as thread priorities, deprecating `thread_priority_critical` (replaced by `thread_priority_high_recursive`).
This fixes #2747
@biddisco Please review.
=> New thread priority names

hpx/parallel/algorithms/is_heap.hpp, hpx/parallel/algorithms/partition.hpp, tests/performance/local/serialization_overhead.cpp, tests/performance/network/network_storage/network_storage.cpp, tests/unit/parallel/algorithms/partition_copy_tests.hpp, tests/unit/parallel/algorithms/unique_copy_tests.hpp, tests/unit/parallel/container_algorithms/partition_copy_range.cpp
This patch tries to remove various warnings due to unused variables or captured variables.
=> Remove various warnings detected by clang 5.0

CMakeLists.txt, hpx/runtime/threads/coroutines/detail/context_linux_x86.hpp, hpx/runtime/threads/coroutines/detail/context_posix.hpp, tests/unit/threads/CMakeLists.txt, tests/unit/threads/thread_stacksize.cpp, tests/unit/threads/thread_stacksize_overflow.cpp
Initial implementation of stackoverflow detection for coroutines issue tracker [#2408](https://github.com/STEllAR-GROUP/hpx/issues/2408) . The source was derived from posix/linux system man pages, the [rethinkdb link](https://rethinkdb.com/blog/handling-stack-overflow-on-custom-stacks/) provided in the issue conversation thread, and a [blog post](http://evanjones.ca/software/threading.html) about coroutine implementations.
=> Coroutine stackoverflow detection for linux/posix; Issue #2408

cmake/tests/cxx17_fallthrough_attribute.cpp
=> Fixing detection of [[fallthrough]] attribute

hpx/parallel/algorithms/transform.hpp, hpx/runtime/threads/coroutines/detail/context_linux_x86.hpp, hpx/util/annotated_function.hpp, tests/unit/computeapi/cuda/default_executor.cu
This patch tries to remove some other warnings and errors detected by clang 5.0 (Cuda Clang being enabled)
=> Remove some other warnings and errors detected by clang 5.0

cmake/templates/HPXMacros.cmake.in
I had problems at some point and needed to deref the cmake vars.
=> Fix a bug in compiler version check

hpx/lcos/dataflow.hpp, hpx/lcos/detail/future_data.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/lcos/local/packaged_task.hpp, hpx/parallel/algorithms/for_each.hpp, hpx/parallel/algorithms/for_loop.hpp, hpx/parallel/algorithms/transform.hpp, hpx/util/annotated_function.hpp
- cleaning up use of annotate_function
=> Adding empty (but non-trivial) destructor to circumvent warnings

docs/manual/existing_performance_counters.qbk, src/components/performance_counters/papi/papi_startup.cpp, src/components/performance_counters/papi/util/papi.cpp
- flyby: add prefix 'hpx:' to all command line options exposed by the PAPI performance counter module
- flyby: allow for 'hpx:print-counter-reset' of PAPI counters
- flyby: document units of measure for some of the thread-related counters
=> Adding documentation for PAPI counters

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx14_deprecated_attribute.cpp, hpx/config.hpp, hpx/config/attributes.hpp, hpx/lcos/dataflow.hpp, hpx/lcos/detail/promise_base.hpp, hpx/lcos/future.hpp, hpx/lcos/local/dataflow.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/lcos/queue.hpp, hpx/parallel/algorithms/inclusive_scan.hpp, hpx/parallel/algorithms/transform_exclusive_scan.hpp, hpx/parallel/algorithms/transform_inclusive_scan.hpp, hpx/parallel/algorithms/transform_reduce.hpp, hpx/runtime/actions/continuation.hpp, hpx/runtime/components/client_base.hpp, hpx/runtime/components/runtime_support.hpp, hpx/runtime/components/server/fixed_component_base.hpp, hpx/runtime/components/server/managed_component_base.hpp, hpx/runtime/components/server/memory_block.hpp, hpx/runtime/components/server/simple_component_base.hpp
- flyby: adding missing deprecated attributions to some older functions
- flyby: remove leftovers still referring to Sodium
=> Check for and optionally use [[deprecated]] attribute

hpx/lcos/gather.hpp
- flyby: make sure registered base name for gather component is unregistered after use
=> Improve error handling in gather_here/gather_there

hpx/util/detail/unwrap_impl.hpp, hpx/util/tuple.hpp, tests/unit/util/iterator/zip_iterator.cpp, tests/unit/util/tuple.cpp
This PR provides two hotfixes for the merged PR #2741:
- Build fix for MSVC 2015
- Fix unconditional moves in `tuple_cat`
It would be great if @K-ballo could review this.
=> Unwrap hotfixes

hpx/util/logging/format/formatter/high_precision_time.hpp
Linker was complaining because of multiple definitions. The header was being included in multiple places, and they were each getting and exporting their own instance of the mutex.
This was broken in 0d9d74d1cc78aa738d66bbb04fb5d3e600675ad4
=> Fix OSX build

hpx/lcos/detail/future_data.hpp, hpx/parallel/algorithms/for_each.hpp, hpx/parallel/algorithms/for_loop.hpp, hpx/parallel/algorithms/transform.hpp, hpx/parallel/util/detail/partitioner_iteration.hpp, hpx/util/annotated_function.hpp, hpx/util/bind.hpp, hpx/util/deferred_call.hpp, hpx/util/detail/basic_function.hpp, hpx/util/detail/vtable/callable_vtable.hpp, hpx/util/function.hpp, hpx/util/unique_function.hpp, src/util/thread_description.cpp
This also includes some fixes to `util::annotate_function` to support a wider source of possible function names.
=> Improvements to continuation annotation

tests/unit/build/src/CMakeLists.txt
On MacOS with cmake 3.9.0 on the current master the test
`tests/unit/build/CMakeFiles/cmake_build_dir_test.make_configure`
fails to compile with the error
```
ERROR: Compilers do not match.  In order to compile HPX application it is
recommended to use the same compiler as you did for HPX.
HPX_CXX_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++,
CMAKE_CXX_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++.
HPX_CXX_COMPILER_ID=AppleClang, CMAKE_CXX_COMPILER_ID=Clang.  To disable
this message set HPX_IGNORE_COMPILER_COMPATIBILITY to On.
Call Stack (most recent call first):
/Users/Joseph/Documents/umich/research/libraries/hpx/build/lib/cmake/HPX/HPXMacros.cmake:26 (hpx_error) …
```
=> bump minimum required cmake to 3.0 in test

hpx/hpx_init_impl.hpp, hpx/hpx_start_impl.hpp, hpx/runtime/threads/coroutines/detail/posix_utility.hpp, src/exception.cpp, tests/unit/component/launch_process.cpp
This pull request introduces a workaround for an unavailable `environ` in shared libraries by initializing a `freebsd_environ` in HPX startup for use in the runtime system.
We also remove `MAP_NORESERVE` from `mmap` code for FreeBSD, as the parameter previously was unimplemented and now is completely removed from FreeBSD 11.0.
=> Fix FreeBSD 11

hpx/parallel/executors/thread_pool_executors.hpp, hpx/runtime/threads/executors/thread_pool_executors.hpp, hpx/runtime/threads/policies/noop_topology.hpp, hpx/runtime/threads/policies/schedulers.hpp, hpx/runtime/threads/policies/throttling_scheduler.hpp, src/hpx_init.cpp, src/runtime/threads/detail/thread_pool.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/threadmanager.cpp, src/runtime_impl.cpp
- this is necessary as this scheduler directly uses HWLOC.
- this fixes #2807
=> Disable throttling scheduler if HWLOC is not found/used

hpx/lcos/local/spmd_block.hpp, hpx/lcos/spmd_block.hpp, tests/unit/lcos/global_spmd_block.cpp, tests/unit/parallel/spmd_block.cpp
This patch adds a new method for `spmd_block` class called `sync_images()` to synchronize only a subset of images as opposed to `sync_all()`. The chosen approach is to manage concurrentlly a `map` of barriers that is expanded each time a new combination of _image ids_ is given via a `sync_images()` call. Local and distributed versions have been implemented and unit tests have been changed to test those features.
=> Add sync_images() method to spmd_block class

hpx/lcos/when_all.hpp, hpx/lcos/when_any.hpp, hpx/lcos/when_some.hpp, hpx/runtime/serialization/deque.hpp, hpx/runtime/serialization/detail/serialize_collection.hpp, hpx/runtime/serialization/list.hpp, hpx/runtime/serialization/vector.hpp, hpx/traits/acquire_future.hpp, hpx/traits/acquire_shared_state.hpp, hpx/traits/detail/reserve.hpp, tests/unit/serialization/serialization_deque.cpp, tests/unit/serialization/serialization_list.cpp, tests/unit/serialization/serialization_vector.cpp
=> Serializing collections with non-default constructible data

tests/performance/parallel_algorithms/local/CMakeLists.txt, tests/performance/parallel_algorithms/local/benchmark_partition.cpp, tests/performance/parallel_algorithms/local/benchmark_partition_copy.cpp
Avoid generic lambda of C++14.
Reverted from https://github.com/STEllAR-GROUP/hpx/commit/fadd999212a12107e577f32e9650bdfd90f11541
=> Support C++11 in benchmark codes of parallel::partition and parallel::partition_copy.

hpx/async.hpp, hpx/lcos/async.hpp, hpx/lcos/async_callback.hpp, hpx/lcos/dataflow.hpp, hpx/lcos/future.hpp, hpx/lcos/local/dataflow.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/runtime/launch_policy.hpp, hpx/traits/is_launch_policy.hpp, src/runtime/launch_policy.cpp, tests/unit/lcos/async_local.cpp, tests/unit/lcos/async_remote.cpp, tests/unit/lcos/future_then.cpp, tests/unit/lcos/local_dataflow.cpp, tests/unit/lcos/remote_dataflow.cpp
- this new policy allows to dynamically generate the required launch policy
- adding tests
- this fixes #2800
The name of the new facility is still up in the air. Please add suggestions.
=> Adding hpx::launch::lazy and support for async, dataflow, and future::then

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx11_noreturn_attribute.cpp, hpx/config.hpp, hpx/config/attributes.hpp, hpx/exception.hpp, hpx/exception_info.hpp, hpx/hpx_finalize.hpp, hpx/parallel/exception_list.hpp, hpx/parallel/util/detail/handle_local_exceptions.hpp, hpx/parallel/util/detail/handle_remote_exceptions.hpp, hpx/runtime/components/server/runtime_support.hpp, hpx/runtime/threads/coroutines/detail/context_base.hpp, hpx/runtime/threads/coroutines/detail/coroutine_self.hpp, hpx/throw_exception.hpp, hpx/util/assert.hpp, src/exception.cpp, src/runtime.cpp, src/throw_exception.cpp
- flyby: remove #include <boost/exception/detail/attribute_noreturn.hpp>
=> Properly support [[noreturn]] attribute if available

hpx/runtime/components/component_factory.hpp, hpx/runtime/components/derived_component_factory.hpp, hpx/runtime/components/server/managed_component_base.hpp, hpx/runtime/components/server/simple_component_base.hpp, tests/regressions/components/CMakeLists.txt, tests/regressions/components/new_2848.cpp
- this fixes #2848
@krivenko: please verify this solves the problem you reported the other day,
=> Allowing for non-default-constructible component types

docs/manual/vector.qbk
This patch fixes some typos in the documentation (`partitioned_vector_view` section) and add documentation for C++ co-arrays.
=> Add documentation for coarrays

hpx/util/hardware/timestamp.hpp
My ARMv8 debian gcc doesn't know of `"__arm__"` define, add `"__arm64__"` and `"__aarch64__"`
supporting link: https://reviews.llvm.org/D4379
this fixes #2852
=> Support ARM64 in timestamps

docs/manual/vector.qbk
This patch fixes some variable names in an example code contained in the documentation.
=> Fix some listing in documentation

plugins/parcelport/parcelport_logging.hpp
=> Only use sched_getcpu on linux machines

CMakeLists.txt, docs/CMakeLists.txt, docs/hpx.idx, hpx/util/command_line_handling.hpp, hpx/util/debugging.hpp, hpx/util/lightweight_test.hpp, src/exception.cpp, src/runtime.cpp, src/util/command_line_handling.cpp, src/util/debugging.cpp, src/util/lightweight_test.cpp, src/util/parse_command_line.cpp, src/util/runtime_configuration.cpp
* Currently only implemented for the MSVC debugger if attached
The main idea is that we instantly see which test failed if we execute a test inside a debugger.
I would like to hear your opinion about this:
* Maybe we could allow to enable/disable this from CMake.
* Maybe we could move this up to the test macros which could yield a better stack trace
=> Break the debugger when a test failed

hpx/lcos/base_lco_with_value.hpp, hpx/lcos/detail/async_implementations.hpp, hpx/lcos/detail/async_implementations_fwd.hpp, hpx/lcos/future.hpp, hpx/parallel/execution_policy.hpp, hpx/parallel/executors/executor_parameters.hpp, hpx/runtime/actions/action_support.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/actions/transfer_action.hpp, hpx/runtime/actions/transfer_base_action.hpp, hpx/runtime/actions/transfer_continuation_action.hpp, hpx/runtime/actions/trigger.hpp, hpx/runtime/components/client_base.hpp, hpx/runtime/serialization/detail/non_default_constructible.hpp, hpx/runtime/serialization/detail/pointer.hpp, hpx/runtime/serialization/detail/polymorphic_nonintrusive_factory.hpp, hpx/runtime/serialization/detail/serialize_collection.hpp, hpx/runtime/serialization/serialization_fwd.hpp, hpx/util/tuple.hpp, tests/regressions/actions/CMakeLists.txt, tests/regressions/actions/return_future_2847.cpp, tests/regressions/actions/return_non_default_constructible_2847.cpp, tests/unit/serialization/polymorphic/polymorphic_nonintrusive.cpp, tests/unit/serialization/serialization_array.cpp, tests/unit/serialization/serialize_buffer.cpp
This fixes #2847.
@krivenko: please verify whether this solves the issue you reported.
Note: this requires #2849 to be merged first
=>   Enable returning future<R> from actions where R is not default-constructible

src/runtime/agas/addressing_service.cpp
This assert was preventing applications to call `hpx::apply<action>(component_id)`
from registered OS threads.
=> Removing uneeded assert

src/runtime/threads/detail/scheduled_thread_pool.cpp, src/runtime/threads/threadmanager.cpp
This code got lost while merging the resource partitioner. Those changes enable
it again.
=> Adding missing support for throttling scheduler

hpx/lcos/base_lco_with_value.hpp, hpx/lcos/server/channel.hpp
=> Disambiguate use of base_lco_with_value macros with channel

src/util/batch_environments/slurm_environment.cpp
This patch fixes parsing of the slurm environment in the presence of running
different SLURM steps with different number of tasks and nodes.
=> Fixing SLURM environment parsing

cmake/HPX_AddDefinitions.cmake
With the current version, adding a compile definition with value "0" does not work. Calling:
```
hpx_add_config_define(MY_DEFINITION 0)
```
creates
```
#define MY_DEFINITION
```
in hpx/config/defines.hpp. The PR fixes it.
=> Fix incorrect handling of compile definition with value 0

hpx/runtime/threads/executors/service_executors.hpp, src/runtime/threads/executors/service_executor.cpp
The destructor and thread_wrapper of the service_executor might race for
completion. This patch ensures that the thread_wrapper always completes
before the destructor
=> Fixing service_executor

src/performance_counters/counters.cpp, src/runtime/resource/detail/detail_partitioner.cpp
- this fixes #2905
- flyby: fixing lock held during suspension problem in resource_partitioner
=> Making sure generated performance counter names are correct

src/runtime.cpp, src/runtime/threads/detail/thread_pool_base.cpp, src/runtime_impl.cpp, tests/unit/resource/CMakeLists.txt, tests/unit/resource/used_pus.cpp
Just a minor tweak to get the pool_usage_mask set correctly
=> Fix incorrect pool usage masks setup in RP/thread manager

hpx/runtime/resource/detail/partitioner.hpp, src/runtime/resource/detail/detail_partitioner.cpp, src/runtime/threads/policies/hwloc_topology_info.cpp
This makes sure that exceptions thrown during the creation of the resource_partitioner don't cause hangs at startup.
This also adds a fallback to get_num_cores() for systems which don't report a proper value from hwloc.
=> Fix rp hang

hpx/runtime/resource/detail/partitioner.hpp, hpx/runtime/resource/partitioner.hpp, src/runtime/resource/detail/detail_partitioner.cpp, src/runtime/resource/partitioner.cpp, src/runtime/threads/threadmanager.cpp, tests/unit/resource/CMakeLists.txt, tests/unit/resource/named_pool_executor.cpp
=> Default pool rename

src/util/debugging.cpp
Debugger was not being attached because the relevant code was #ifdef'ed
out and therefore being skipped completely on some linux flavours
fix #2924 problem seems to have been caused by changes introduced in #2830
=> Add #include files needed to set _POSIX_VERSION for debug check

src/runtime/threads/policies/hwloc_topology_info.cpp, src/runtime_impl.cpp
- flyby: fix possible double-free of hwloc bitmap
=> Making error reporting during problems with setting affinity masks more verbose

hpx/parallel/util/detail/chunk_size_iterator.hpp
This PR fixes #2866 .
Now, I classify ```chunk_size_iterator``` to input_iterator_tag, not forward_iterator_tag.
What I worry is that if ```chunk_size_iterator``` will be used incorrectly in any place, he/she may not know what is incorrect and wander with mistery bug.
https://github.com/STEllAR-GROUP/hpx/blob/954818a2202aec118b6dd00a81e96bb18e8c9e9c/hpx/parallel/executors/execution_fwd.hpp#L193-L201
For example, in above code, there is a nothing which explicitly notices that ```chunk_size_iterator``` is input iterator.
So, an user who utilizes ```chunk_size_iterator``` "indirectly" can make a mistake which violates multi-pass gaurantee.
=> Classify chunk_size_iterator to input iterator tag. (Fix #2866)

docs/CMakeLists.txt, docs/hpx.idx, hpx/lcos/dataflow.hpp, hpx/lcos/detail/future_transforms.hpp, hpx/lcos/local/dataflow.hpp, hpx/lcos/when_all.hpp, hpx/util/detail/container_category.hpp, hpx/util/detail/pack_traversal_async_impl.hpp, hpx/util/detail/pack_traversal_impl.hpp, hpx/util/pack_traversal_async.hpp, tests/unit/lcos/CMakeLists.txt, tests/unit/util/CMakeLists.txt, tests/unit/util/pack_traversal_async.cpp
**This is the third PR of my GSoC :sun_with_face: project**
It implements an API for traversing a pack in an asynchronous way.
It uses exceptions for cancelling the current control flow, hoping this is available on all platforms (nvcc).
**I also added the `when_each` test to the build since it wasn't included**, also there wasn't any indication that it was excluded from the build for any reason.
=> Implement an API for asynchronous pack traversal

hpx/util/detail/basic_function.hpp, hpx/util/detail/vtable/vtable.hpp
Reverts STEllAR-GROUP/hpx#2945
The original patch has caused issues during de-serialization of functions.
=> Revert "Make sure the function vtables are initialized before use"

examples/resource_partitioner/shared_priority_scheduler.hpp, hpx/runtime/threads/detail/scheduled_thread_pool.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/policies/hierarchy_scheduler.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, hpx/runtime/threads/policies/thread_queue.hpp, tests/unit/resource/throttle.cpp
- Partially reverting changes to wait_or_add_new and the termination detection
- Commenting out throttle test, to be fixed within #2955.
This supersedes #2952 and fixes #2949.
=> Partially reverting #2891

hpx/lcos/dataflow.hpp
- this fixes test problems with the executor_parameters_timer_hooks test
=> Making sure any function object passed to dataflow is released after being invoked

hpx/hpx_finalize.hpp
Clang will generate a compiler error if an attribute using the C++11 syntax is preceded by another attribute using the GCC syntax.
This PR reorders the attributes to fix this issue.
This fixes #2956.
=> Fixing errors generated by mixing different attribute syntaxes

src/util/command_line_handling.cpp, src/util/ini.cpp, src/util/init_ini_data.cpp, src/util/runtime_configuration.cpp
- flyby: fixed possible deadlock in util::section
This fixes #2947
=> Making sure any hpx.os_threads=N supplied through a --hpx::config file is taken into account

hpx/lcos/channel.hpp, hpx/lcos/local/channel.hpp, hpx/lcos/local/receive_buffer.hpp, hpx/lcos/server/channel.hpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/channel_2916.cpp
- flyby: channel::close() now returns the number of elements left in the channel
=> Adding test to trigger problem reported in #2916

hpx/runtime/threads/coroutines/detail/context_posix.hpp
Adding uintstd.h header so compiling with Clang 5.0 on ppc64le works.
=> Adding uintstd.h header

hpx/traits/is_tuple_like.hpp
- Move SFINAE out of the lookup phase, defer to base implementation
- Ignore cv-qualified specializations of tuple_size
=> Improve is_tuple_like trait

CMakeLists.txt
v1.2 is an old tag, updating APEX GitHub command to pull master instead.
=> Change version of pulled APEX to master

hpx/runtime/resource/partitioner_fwd.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/detail/thread_pool_base.hpp, hpx/runtime/threads/policies/hwloc_topology_info.hpp, hpx/runtime/threads/policies/noop_topology.hpp, hpx/runtime/threads/thread_data_fwd.hpp, hpx/runtime/threads/threadmanager.hpp, hpx/runtime/threads/topology.hpp, src/runtime/threads/detail/thread_pool_base.cpp, src/runtime/threads/policies/hwloc_topology_info.cpp
This provides an interface to the hwloc_alloc_membind function and requires a numa nodeset to be passed that the memory is bound to. 
This in turn requires a nodeset and rather than using a mask and converting to and from hwloc types, it is less error prone to use an hwloc bitmap object wrapped in a c++ holder to manage deletion.
=> Alloc membind

hpx/util/logging/detail/cache_before_init.hpp
...avoid instantiation of distinct std::map per logging message type
=> Deduplicate non-dependent thread_info logging types

hpx/include/parallel_all_any_none_of.hpp, hpx/parallel/algorithms/all_any_none.hpp, hpx/parallel/container_algorithms/all_any_none.hpp, tests/unit/parallel/algorithms/all_of.cpp, tests/unit/parallel/algorithms/none_of.cpp, tests/unit/parallel/container_algorithms/CMakeLists.txt, tests/unit/parallel/container_algorithms/all_of_range.cpp, tests/unit/parallel/container_algorithms/any_of_range.cpp, tests/unit/parallel/container_algorithms/none_of_range.cpp
- Add projection function to all_of, any_of, none_of
- Add range version of the above functions (#1668)
- corresponding tests
=> Adapted parallel::{all_of|any_of|none_of} for Ranges TS (see #1668)

src/util/command_line_handling.cpp, src/util/parse_command_line.cpp, tests/regressions/util/CMakeLists.txt, tests/regressions/util/command_line_required_arguments_2990.cpp
this fixes #2990 
@krivenko please make sure that this fixes the problem you reported, thanks!
=> Making sure --hpx:help does not throw for required (but missing) arguments

hpx/runtime/threads/executors/service_executors.hpp, hpx/runtime/threads/run_as_os_thread.hpp, hpx/runtime/threads/thread_executor.hpp, src/runtime/threads/executors/service_executor.cpp, tests/regressions/threads/CMakeLists.txt, tests/regressions/threads/run_as_os_thread_lockup_2991.cpp
- implement run_as_os_thread in terms of non-blocking io_pool executor
this fixes #2991
=> Adding non-blocking (on destruction) service executors

hpx/runtime/resource/detail/partitioner.hpp, hpx/runtime/threads/policies/affinity_data.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, src/runtime/resource/detail/detail_partitioner.cpp, src/runtime/threads/policies/affinity_data.cpp
- this reduces the overheads in the scheduler significantly
=> Speeding up accessing the resource partitioner and the topology info

hpx/lcos/detail/async_implementations.hpp, hpx/runtime/actions/basic_action.hpp
- this patch significantly speeds up local action execution (both,
direct and non-direct) by avoiding to construct a (remote) promise
but instead directly scheduling the function bound to the action
as a local thread, while using a simple (local-only) future.
- direct actions are executed by directly invoking the function bound to 
the function
=> Speed up local action execution

hpx/lcos/local/packaged_continuation.hpp, hpx/parallel/executors/execution.hpp, hpx/parallel/executors/execution_fwd.hpp, hpx/parallel/executors/thread_execution.hpp
P0443 executor proposal uses API of the form ...
then_execute(Function&& f, Future&& pred) const
=> implement executor then interface with && forwarding reference

hpx/runtime/threads/detail/scheduled_thread_pool.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/policies/scheduler_mode.hpp, src/runtime/threads/detail/thread_pool_base.cpp
- fixing performance problem related to `get_used_processing_units()` for
non-elastic pools
This specifically leaves open  the issue of `get_used_processing_units()` returning an unprotected reference to the mask. This has to be resolved separately.
=> Adding enable_elasticity option to pool configuration

cmake/templates/hpxrun.py.in, hpx/hpx_main_impl.hpp, python/scripts/hpx_run_test.py
- those applications most likely will do their own command line handling,
disabling hpx short options will prevent for the user to run into
surprises.
=> Disable command-line aliasing for applications that use user_main

hpx/lcos/detail/async_implementations.hpp, hpx/runtime/actions/action_invoke_no_more_than.hpp, hpx/runtime/components/server/locking_hook.hpp, hpx/runtime/components/server/migration_support.hpp, hpx/traits/action_decorate_function.hpp
- Fixing local function invocations:
- Only invoke functions locally (sync or asyn) if the calling context is the same as requested and if the action has not been decorated.
- Fixes tests:
- tests.unit.components.distributed.*.action_invoke_no_more_than (#3043)
-  tests.unit.threads.distributed.*.thread_stacksize
=> Fixing #3044

CMakeLists.txt
We just ran into a strange issue with the AllScale project. Investigating it, I found that setting the default build type in HPX does not work. This should be fixed by this PR.
Even if no `CMAKE_BUILD_TYPE` is specified by the user, CMake still creates a cache entry. This entry is empty, yet present -- therefore `FORCE` is required.
=> Fix setting of default build type

tests/unit/parallel/algorithms/CMakeLists.txt, tests/unit/parallel/container_algorithms/CMakeLists.txt, tests/unit/parallel/datapar_algorithms/CMakeLists.txt, tests/unit/parallel/executors/CMakeLists.txt, tests/unit/parallel/segmented_algorithms/CMakeLists.txt
This makes it possible to run all tests in subfolders of `tests/unit/parallel` with one `ctest -R` command. This is also consistent with other test categories with subfolders.
=> Make parallel unit test names match build target/folder names

CMakeLists.txt
=> Do not bind test running to cmake test build rule

README.rst, docs/manual/build_system/recipe_unix.qbk, docs/manual/testing.qbk
This updates the documentation for running tests to reflect the changes made in #3052.
=> Update documentation for running tests

hpx/runtime/resource/detail/partitioner.hpp, hpx/util/command_line_handling.hpp, src/hpx_init.cpp, src/runtime/resource/detail/detail_partitioner.cpp
runtime termination in the presence of --hpx:help or --hpx:version needs to
happen after the runtime has been initialized.
=> Fixing #2931

src/runtime/components/server/wrapper_heap.cpp
This fixes a problem with a wrong condition (which had been in there before) which
led to wrapper heaps being deallocated too early.
=> Fixing wrong condition in wrapper_heap

hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp
This fixes occasional asserts firing on throttle tests. Because the suspension/throttling changes relaxed scheduling loop exit criteria, the assert after exiting also needs to be relaxed.
=> Fix scheduling loop exit

examples/qt/qt.cpp, examples/qt/widget.cpp, examples/qt/widget.hpp
GUI objects must not be manipulated from threads other than the GUI thread. This rule was violated in the qt example. Now it is fixed.
=> Fix HPX-Qt interaction in Qt example.

hpx/include/parallel_move.hpp, hpx/parallel/container_algorithms/copy.hpp, hpx/parallel/container_algorithms/move.hpp, tests/unit/parallel/container_algorithms/CMakeLists.txt, tests/unit/parallel/container_algorithms/move_range.cpp
range version of move (per #1668) and corresponding tests
=> Added range version of parallel::move

hpx/performance_counters/registry.hpp, hpx/runtime/agas/addressing_service.hpp, hpx/runtime/agas/interface.hpp, hpx/runtime/agas/server/symbol_namespace.hpp, hpx/runtime/agas/symbol_namespace.hpp, hpx/util/regex_from_pattern.hpp, plugins/parcel/coalescing/coalescing_counter_registry.cpp, src/hpx_init.cpp, src/performance_counters/registry.cpp, src/runtime/actions/detail/invocation_count_registry.cpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/interface.cpp, src/runtime/agas/server/symbol_namespace_server.cpp, src/runtime/agas/symbol_namespace.cpp, src/runtime/parcelset/detail/per_action_data_counter_registry.cpp, src/util/regex_from_pattern.cpp
This API was never used anywhere and required some face-lifting after being half-way abandoned. It is now needed on one of our projects.
=> Change existing symbol_namespace::iterate to return all data instead of invoking a callback

hpx/runtime/serialization/output_archive.hpp, tests/unit/util/checkpoint.cpp
This change initializes split_gids_ which is the first step to fixing #3075
=> Fixing 3075: Part 1

examples/allgather/mpi_equivalent/mpiallgather.cpp, hpx/plugins/parcelport/mpi/header.hpp, hpx/plugins/parcelport/mpi/mpi.hpp, hpx/plugins/parcelport/mpi/mpi_environment.hpp, plugins/parcelport/mpi/mpi_environment.cpp, plugins/parcelport/mpi/parcelport_mpi.cpp, src/version.cpp, tests/unit/util/parse_affinity_options.cpp, tests/unit/util/tuple.cpp
This ignores build warnings that we can't fix using `#pragma diagnostic GCC/clang ignored ...`.
=> Ignore build warnings

CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/tests/stable_inplace_merge.cpp, tests/unit/parallel/algorithms/inplace_merge.cpp, tests/unit/parallel/algorithms/inplace_merge_tests.hpp
AFAICT [this](https://git.codingcafe.org/Mirrors/llvm-mirror/libcxx/commit/25a78dcd773ce509469a2b892adbeac0c230cdb9) is not yet in any released version of libc++ so I'm ignoring the test for all versions of libc++.
I'll update this to check the version as well once the fix has been merged.
"Fixes" #2964.
=> Don't test inplace_merge with libc++

hpx/runtime/threads/policies/hierarchy_scheduler.hpp, hpx/runtime/threads/policies/periodic_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/static_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/static_queue_scheduler.hpp, tests/unit/resource/CMakeLists.txt, tests/unit/resource/shutdown_suspended_pus.cpp, tests/unit/resource/suspend_disabled.cpp, tests/unit/resource/throttle.cpp, tests/unit/resource/throttle_timed.cpp
This moves enabling elasticity to the test setup before calling `hpx::init`, and creates a separate test to check that suspending is only allowed if elasticity is enabled.
=> Suspend thread cleanup

tests/unit/component/migrate_component_to_storage.cpp, tests/unit/util/tuple.cpp
My previous attempt at ignoring build warnings (#3079) in the tuple test was actually no good. While it was the `tuple.hpp` header generating the warnings, it was included before that transitively by `hpx_init.hpp`. I've instead put the ignores around all hpx headers now, with the risk of silencing future warnings which might be unrelated to the current warnings (but with the benefit of still ignoring the current warnings if `hpx_init.hpp` no longer would depend on `tuple.hpp`).
Sorry for the noise.
This also adds another explicit base class initialization to get rid of a warning.
=> Ignore build warnings round 2

hpx/parallel/algorithms/sort.hpp, hpx/parallel/exception_list.hpp
Fixes #2834 .
flyby: Fixes #3088 .
=> Fix a strange thing in parallel::detail::handle_exception. (Fix #2834.)

cmake/tests/stable_inplace_merge.cpp
Fixes #2964 
- Add include to `stable_inplace_merge` cmake test so that `_LIBCPP_VERSION` is defined
- Fix version comparison
I left out out some crucial parts in #3078. This fixes them.
=> Add ciso646 header to get _LIBCPP_VERSION for testing inplace merge

hpx/config.hpp, hpx/config/compiler_fence.hpp, hpx/config/compiler_native_tls.hpp, hpx/lcos/local/spinlock.hpp, hpx/runtime/agas/big_boot_barrier.hpp, hpx/runtime/naming/name.hpp, hpx/util/detail/yield_k.hpp, hpx/util/thread_specific_ptr.hpp, plugins/parcelport/mpi/parcelport_mpi.cpp, src/runtime/agas/big_boot_barrier.cpp, src/util/runtime_configuration.cpp
- cleanup configuration of TLS and compiler specific fence operation
=> Unify use of yield/yield_k

tests/regressions/lcos/broadcast_wait_for_2822.cpp
Unbreak broadcast_wait_for_2822 test
- Properly testing the broadcast for completion, not relying on particular timing for the test to succeed
=> Unbreak broadcast_wait_for_2822 test

src/components/performance_counters/papi/server/papi.cpp
Partially fixes #3044
Fixing lock held during suspension in papi counter component
This fixes this test: http://rostam.cct.lsu.edu/builders/hpx_clang_3_8_boost_1_59_centos_x86_64_debug/builds/134/steps/run_regression_tests/logs/tests.regressions.performance_counters.papi_counters_active_interface%20%281.10%20sec%29
=> Fixing lock held during suspension in papi counter component

hpx/config.hpp, hpx/config/threads_stack.hpp
Partially Fixes #3044
This patch adapts the compile time constant for the stack overhead for gcc 4.9.
This unbreaks the thread_stacksize test.
HPX tasks are suspect to stack overflows. Currently, the thread_stacksize test fails with a segfault. It is trying to touch all bytes in the stack. It relies on the `HPX_THREADS_STACK_OVERHEAD` define to have a sensible value. This value was to small for gcc 4.9.
=> Adapting stack overhead limit for gcc 4.9

hpx/lcos/local/condition_variable.hpp
According o @K-ballo, condition_variable_any has even more problems, and condition_variable unnecessarily duplicates its functionality, but this should fix the deadlock bug described in #3068 by alternating the order of destructors.
=> Fix #3068 (condition_variable deadlock)

cmake/HPX_AddConfigTest.cmake, cmake/tests/cxx11_std_atomic.cpp
Fixes #3031 
- add some instructions to `cxx11_std_atomic.cpp` to require `__atomic_load_16` symbol
- fix cmake code for testing for `std::atomic` support
The previous cmake code is broken in several ways. First, the REQUIRED option is forwarded to the first `add_hpx_config_test` invocation so it generates at fatal error if the test doesn't compile without the library. Second the `CheckLibraryExists` module is not included so the `check_library_exists` call fails. Third the second `add_hpx_config_test` invocation does nothing because `HPX_WITH_CXX11_ATOMIC` is already set. This fixes those issues and makes the test source a little more comprehensive.
=> fix detection of cxx11_std_atomic

cmake/HPX_AddConfigTest.cmake, cmake/tests/cxx11_std_atomic.cpp
Reverts STEllAR-GROUP/hpx#3096 because of cmake tests failing e.g. [here](http://rostam.cct.lsu.edu/builders/hpx_clang_3_8_boost_1_59_centos_x86_64_debug/builds/186/steps/configure/logs/stdio).
Reverting so that we can keep merging other PRs to master and see the test results.
=> Revert "fix detection of cxx11_std_atomic"

src/runtime/threads/thread_helpers.cpp
It might happen that the id that is being yielded to the scheduling loop
should be run on a different scheduler. This patch fixes that.
This might be related to the occasional failures we see with the thread executors tests.
=> Fixing thread scheduling when yielding a thread id.

hpx/lcos/detail/async_implementations.hpp, hpx/runtime/actions/basic_action.hpp, hpx/traits/action_decorate_function.hpp, tests/unit/threads/thread_stacksize.cpp
- the test whether a direct action should actually be executed directly was checking for thread priority and thread stack-size. This patch removes those checks as they overly constrain direct execution.
=> Local execution of direct actions is now actually performed directly

tests/unit/util/pack_traversal_async.cpp
This patch fixes a problem with the refcount of the async pack traversal visitor
dropping to zero too early.
- Have an initial increase of the refcount when constructing the intrusive_ptr for the frame
- move the frame into the resumable traversal
- return the frame from this resumer
This bug has been detected by running the pack_traversal_async test under address sanitizer which gave this diagnostic:
```
==15221==ERROR: AddressSanitizer: heap-use-after-free on address 0x6040000149e0 at pc 0x0000006877ab bp 0x7ffea7bb1050 sp 0x7ffea7bb1048
READ of size 8 at 0x6040000149e0 thread T0
#0 0x6877aa in bool hpx::util::detail::fixture::check_equal<unsigned long, unsigned long>(char const*, int, char const*, hpx::util::counter_type, unsigned long const&, unsigned long const&, char const*) …
```
=> Fixing refcount for async traversal frame

hpx/config/compiler_fence.hpp
Fixes #3121 
This patch fixes #3121 by adding the proper instructions for SMT_PAUSE for the "big three", for everything else, the fence instruction is used.
=> Fixing #3121

hpx/lcos/detail/future_data.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/components/server/locking_hook.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/detail/set_thread_state.hpp, hpx/runtime/threads/thread_id_type.hpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime/threads/executors/current_executor.cpp, src/runtime/threads/executors/pool_executor.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/executors/thread_pool_os_executors.cpp, src/runtime/threads/thread.cpp, src/runtime/threads/thread_helpers.cpp, src/runtime_impl.cpp, src/util/interval_timer.cpp, tests/performance/local/coroutines_call_overhead.cpp, tests/performance/local/htts_v2/htts2_hpx.cpp, tests/performance/local/timed_task_spawn.cpp, tests/unit/agas/components/managed_refcnt_checker.hpp, tests/unit/agas/components/simple_refcnt_checker.hpp
This change was neceessary after #3120 was merged. It was working with clang 5 and
gcc 6 and up for some reason.
=> Replacing nullptr with hpx::threads::invalid_thread_id

hpx/include/performance_counters.hpp, hpx/performance_counters/base_performance_counter.hpp, hpx/performance_counters/performance_counter.hpp, hpx/performance_counters/performance_counter_base.hpp, hpx/performance_counters/performance_counter_set.hpp, hpx/performance_counters/server/base_performance_counter.hpp, hpx/performance_counters/stubs/performance_counter.hpp, hpx/runtime.hpp, hpx/runtime_fwd.hpp, hpx/util/query_counters.hpp, src/performance_counters/performance_counter.cpp, src/performance_counters/performance_counter_set.cpp, src/performance_counters/stubs/performance_counter_stub.cpp, src/runtime.cpp, src/util/query_counters.cpp, tests/unit/performance_counter/CMakeLists.txt, tests/unit/performance_counter/reinit_counters.cpp
- This change adds a new API function for performance counters that instructs a
counter to re-initialize the set of values it refers to
- This also adds a new `hpx::reinit_active_counters()` API that triggers a
reinit for all active counters
We will need this functionality for the new performance counters to be created for Phylanx where the list of values to be returned from a performance counter may change dynamically based on the evaluated expressions.
=> Adding performance_counter::reinit to allow for dynamically changing counter sets

CMakeLists.txt, docs/hpx.idx, examples/quickstart/component_with_executor.cpp, examples/resource_partitioner/oversubscribing_resource_partitioner.cpp, examples/resource_partitioner/simple_resource_partitioner.cpp, hpx/compute/host/block_executor.hpp, hpx/lcos/local/spmd_block.hpp, hpx/lcos/spmd_block.hpp, hpx/parallel/algorithms/inclusive_scan.hpp, hpx/parallel/algorithms/inner_product.hpp, hpx/parallel/algorithms/transform_exclusive_scan.hpp, hpx/parallel/algorithms/transform_inclusive_scan.hpp, hpx/parallel/algorithms/transform_reduce.hpp, hpx/parallel/executors/execution_information.hpp, hpx/parallel/executors/rebind_executor.hpp, hpx/parallel/executors/timed_executors.hpp, hpx/parallel/spmd_block.hpp, hpx/traits/is_timed_executor.hpp, tests/performance/local/transform_reduce_scaling.cpp, tests/regressions/parallel/executors/is_executor_1691.cpp, tests/regressions/parallel/scan_different_inits.cpp, tests/unit/parallel/segmented_algorithms/partitioned_vector_transform_scan.cpp, tests/unit/parallel/spmd_block.cpp, tests/unit/parallel/task_block_executor.cpp, tests/unit/resource/named_pool_executor.cpp, tests/unit/threads/resource_manager.cpp
- this is in preparation with the V1.1. release at which point the V1 executors
should be disabled by default
- this also sets the default for HPX_HAVE_TRANSFORM_REDUCE_COMPATIBILITY to OFF
=> Disable default executor compatibility with V1 executors

cmake/tests/cxx14_constexpr.cpp
This patch is adding functionality to the C++14 constexpr test to cover more usecases
Our intel builders currently fail to compile master:
http://rostam.cct.lsu.edu/builders/hpx_intel_17_2_174_boost_1_59_centos_x86_64_debug/builds/203/steps/build_core/logs/stdio
=> Update CXX14 constexpr feature test

hpx/runtime/actions/action_invoke_no_more_than.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/components/server/executor_component.hpp, hpx/runtime/components/server/locking_hook.hpp, hpx/runtime/components/server/migration_support.hpp, hpx/runtime/threads/coroutines/coroutine.hpp, hpx/runtime/threads/coroutines/detail/context_base.hpp, hpx/runtime/threads/coroutines/detail/coroutine_impl.hpp, hpx/runtime/threads/coroutines/detail/coroutine_self.hpp, hpx/runtime/threads/coroutines/exception.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/detail/set_thread_state.hpp, hpx/runtime/threads/thread_data.hpp, hpx/runtime/threads/thread_data_fwd.hpp, hpx/runtime/threads/thread_helpers.hpp, hpx/runtime/threads/thread_id_type.hpp, hpx/util/interval_timer.hpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime/threads/coroutines/detail/coroutine_impl.cpp, src/runtime/threads/thread_helpers.cpp, src/runtime/threads/threadmanager.cpp, src/util/interval_timer.cpp, tests/performance/local/coroutines_call_overhead.cpp, tests/performance/local/htts_v2/htts2_hpx.cpp, tests/performance/local/timed_task_spawn.cpp, tests/regressions/threads/thread_rescheduling.cpp, tests/unit/computeapi/host/block_allocator.cpp, tests/unit/parallel/algorithms/partition_tests.hpp, tests/unit/parallel/algorithms/sort_by_key.cpp
- Removing dynamic memory allocation
- Removing intrusive ptr
- Removing unused functions
- Simplifying thread functions to be nullary
- Using thread_data directly to get/set the state_ex value
This patch both simplifies and cleans up current code. This patch gives a rough speedup of about 1.5x for small grain sizes leading to heavy contention in the thread scheduler.
There is a potential breaking change for third party code using thread functions directly. I think this code is minimal and should be mostly under our control.
=> Cleaning up coroutine implementation

hpx/lcos/dataflow.hpp, hpx/parallel/util/scan_partitioner.hpp
Fixes #2325
As time went by, we can re-enable the usage of executors again. Some changes
in our code base seem to have led to this not segfaulting anymore
=> Fixing #2325

hpx/lcos/dataflow.hpp, hpx/parallel/util/scan_partitioner.hpp
Reverts STEllAR-GROUP/hpx#3131 as it breaks the test `tests.unit.parallel.algorithms.reduce_by_key` on nearly every configuration. See [here](http://rostam.cct.lsu.edu/builders/hpx_gcc_4_9_boost_1_58_centos_x86_64_debug/builds/202/steps/run_unit_tests/logs/tests.unit.parallel.algorithms.reduce_by_key%20%286.83%20sec%29) for an example.
=> Revert "Fixing #2325"

hpx/lcos/detail/future_data.hpp, hpx/lcos/detail/future_transforms.hpp, src/lcos/detail/future_data.cpp
This patch removes `compose_cb` in favor of `boost::container::small_vector<callback_type, 3>`. The main motivation is to avoid memory allocations for cases where two or more completion handlers are attached to a future.
Flyby: avoid reference counting for pack traversals.
=> Avoid completion handler allocation

hpx/runtime/actions/action_invoke_no_more_than.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/components/server/executor_component.hpp, hpx/runtime/components/server/locking_hook.hpp, hpx/runtime/components/server/migration_support.hpp, hpx/runtime/threads/coroutines/coroutine.hpp, hpx/runtime/threads/coroutines/detail/coroutine_impl.hpp, hpx/runtime/threads/coroutines/detail/coroutine_self.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/detail/set_thread_state.hpp, hpx/runtime/threads/thread_data.hpp, hpx/runtime/threads/thread_data_fwd.hpp, hpx/runtime/threads/thread_helpers.hpp, hpx/util/interval_timer.hpp, src/runtime/threads/coroutines/detail/coroutine_impl.cpp, src/runtime/threads/thread_helpers.cpp, src/util/interval_timer.cpp, tests/performance/local/coroutines_call_overhead.cpp, tests/performance/local/htts_v2/htts2_hpx.cpp, tests/performance/local/timed_task_spawn.cpp
Fixes #3126
This patch reverts the changes related to the thread state_ex changes as they
seem to lead to overall problems.
=> Partially reverting #3126

examples/resource_partitioner/shared_priority_scheduler.hpp, hpx/runtime/threads/policies/hierarchy_scheduler.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, hpx/runtime/threads/policies/thread_queue.hpp, hpx/runtime/threads/thread_data.hpp
Instead of having to loop over the available queues, this patch stores the queue
in which the thread has been allocated.
In addition, we completely avoid going over an additional memory pool as the
queues cache and reuse the allocated threads.
=> Improving destruction of threads

hpx/lcos/detail/future_data.hpp
This fixes problems with swapping boost::container::small_vector on older boost
versions. In addition, on boost < 1.58, it uses std::vector since
boost::container::small_vector was introduced with boost 1.58
=> Fixing small_vector compatibility with older boost version

hpx/config.hpp, hpx/config/debug.hpp, hpx/config/threads_stack.hpp
- Separate debug definitions into `hpx/config/debug.hpp`
- Include `debug.hpp` in the new `threads_stack.hpp` config file
This is the same as #3097, but makes sure `HPX_DEBUG` is defined for the thread stacksize defines.
=> Fix stack overhead

hpx/lcos/detail/future_data.hpp
This helps to fix failures seen e.g. [here](http://rostam.cct.lsu.edu/builders/hpx_gcc_4_9_boost_1_58_centos_x86_64_release/builds/224).
=> Use small_vector only from boost version 1.59 onwards

hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/util/detail/yield_k.hpp, hpx/util/yield_while.hpp, plugins/parcelport/libfabric/parcelport_libfabric.cpp, plugins/parcelport/libfabric/receiver.cpp, plugins/parcelport/libfabric/rma_receiver.cpp, plugins/parcelport/libfabric/sender.cpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime_impl.cpp, tests/unit/resource/suspend_runtime.cpp
- Move `yield_while` from `yield_k.hpp` in the `detail` namespace to its own file not in the `detail` namespace
- Make `nullptr` the default value for the `thread_name` parameter in `yield_while`
=> Move yield_while out of detail namespace and into own file

hpx/lcos/detail/async_implementations.hpp, tests/unit/threads/thread_stacksize.cpp
This patch makes sure that action invocations always have at least as much
stack space available as they requested.
=> Avoiding more stack overflows

hpx/runtime/threads/detail/set_thread_state.hpp, src/runtime/threads/thread_helpers.cpp, tests/regressions/lcos/wait_for_1751.cpp
When doing a timed suspension on a thread, there were several race conditions
between setting the different participating thread states, which should now be
fixed. The problem was observable with the wait_for_1751 regression test.
=> Fixing a race with timed suspension

hpx/runtime/threads/detail/set_thread_state.hpp, src/runtime/threads/thread_helpers.cpp, tests/regressions/lcos/wait_for_1751.cpp
Reverts STEllAR-GROUP/hpx#3153.
There were timeouts at least in `action_invoke_no_more_than` and possibly some other tests so reverting.
=> Revert "Fixing a race with timed suspension"

hpx/runtime/actions/action_support.hpp, hpx/runtime/actions/base_action.hpp, hpx/runtime/actions/detail/action_factory.hpp, hpx/runtime/actions/transfer_action.hpp, hpx/runtime/actions/transfer_base_action.hpp, hpx/runtime/actions/transfer_continuation_action.hpp, hpx/runtime/components/component_registry.hpp, hpx/runtime/components/component_type.hpp, hpx/runtime/components/server/component_base.hpp, hpx/runtime/components/server/managed_component_base.hpp, src/runtime/actions/base_action.cpp, src/runtime/components/server/component_base.cpp
This allows to reduce the number of instantiated functions and exported symbols, especially for external modules that contain components.
=> Refactoring component_base and base_action/transfer_base_action 

hpx/util/parse_command_line.hpp, src/util/command_line_handling.cpp
Previously quoted command line arguments were stripped of the outermost pair of quotes. The proposed change fixes this issue.
=> Fixing the handling of quoted command line arguments.

src/util/regex_from_pattern.cpp
=> regex_from_pattern: escape regex special characters to avoid misinterpretation

hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/detail/set_thread_state.hpp, hpx/runtime/threads/thread_helpers.hpp, src/runtime/threads/executors/current_executor.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/thread_helpers.cpp, tests/regressions/lcos/wait_for_1751.cpp, tests/unit/component/CMakeLists.txt
When doing a timed suspension on a thread, there were several race conditions
between setting the different participating thread states, which should now be
fixed. The problem was observable with the wait_for_1751 regression test.
This is the second attempt (after #3153), fixing the previous issues.
=> Fixing a race with timed suspension (second attempt)

hpx/runtime/serialization/access.hpp, hpx/util/tuple.hpp, tests/unit/serialization/CMakeLists.txt, tests/unit/serialization/serialize_with_incompatible_signature.cpp
=> Fixing serialization of classes with incompatible serialize signature

cmake/HPX_SetupVc.cmake, hpx/parallel/datapar/transform_loop.hpp
- flyby: disable C++17 compatibility warnings for MSVC when compiling using Vc
Fixes #3165
=> Changing used namespace for seq execution policy

docs/manual/commandline.qbk, docs/manual/parallel_algorithms.qbk, docs/manual/scheduling_policies.qbk, docs/whats_new_previous.qbk, hpx/runtime/resource/partitioner_fwd.hpp, hpx/runtime/threads/policies/lockfree_queue_backends.hpp, src/runtime/resource/detail/detail_partitioner.cpp, src/runtime/threads/detail/scheduled_thread_pool.cpp, src/runtime/threads/threadmanager.cpp, src/util/command_line_handling.cpp, src/util/parse_command_line.cpp, tests/unit/threads/CMakeLists.txt, tests/unit/threads/schedule_last.cpp
This addresses the issue in #3166.
The issue in this case was that when `shutdown_all` waits for all threads to finish it calls `suspend(pending)` which eventually calls `schedule_last` for the `shutdown_all` thread. For the lifo queue backend `schedule_last` is the same as `schedule` and `shutdown_all` will be scheduled as the next thread again, leaving no chance for the remaining threads to run. I suspect we haven't seen this with more than 1 thread because then other OS threads will be able to steal the threads and/or most tests and examples wait for all futures before calling `hpx::finalize`.
- Use deque for the non-abp lifo and fifo queue backends so that `schedule_last` can actually schedule a thread last in the queue.
- Add a test which reproduces the issue.
- Fix some naming in …
=> Fix lifo queue backend

hpx/include/thread_executors.hpp, hpx/parallel/executors.hpp, hpx/parallel/executors/pool_executor.hpp, hpx/runtime/resource/detail/create_partitioner.hpp, hpx/runtime/resource/partitioner.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/executors/pool_executor.hpp, hpx/runtime/threads/policies/hierarchy_scheduler.hpp, hpx/runtime/threads/policies/periodic_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, hpx/runtime/threads/policies/scheduler_mode.hpp, hpx/runtime/threads/policies/static_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/static_queue_scheduler.hpp, hpx/runtime/threads/thread_pool_base.hpp, src/runtime/threads/executors/pool_executor.cpp, src/runtime/threads/threadmanager.cpp, src/util/command_line_handling.cpp, tests/unit/resource/shutdown_suspended_pus.cpp, tests/unit/resource/suspend_pool.cpp, tests/unit/resource/throttle.cpp, tests/unit/resource/throttle_timed.cpp
- adding more constructors to resource::partitioner (aligned with hpx::init)
- adding hpx::parallel::execution::pool_executor alias (for consistency)
- adding default constructor for pool-executor
- adding support to request minimal number of cores (threads) (hpx.force_min_os_threads)
- Making sure resume/suspend is not called for schedulers that don't support it
=> Various minor changes to support FLeCSI

tests/performance/local/CMakeLists.txt, tests/performance/local/openmp_homogeneous_timed_task_spawn.cpp, tests/performance/local/openmp_parallel_region.cpp, tests/performance/local/resume_suspend.cpp, tests/performance/local/start_stop.cpp
- Add resume/suspend benchmark
- Add start/stop benchmark
- Add OpenMP parallel region benchmark
- Flyby: fix a missing comma in an existing OpenMP performance test
#3137
=>  Add runtime start/stop, resume/suspend and OpenMP benchmarks 

examples/nqueen/nqueen.hpp
Fixes #3048.
- Initialize board synchronously to make sure it is initialized before being
accessed.
=> Fix nqueen example

src/performance_counters/server/statistics_counter.cpp
Two times **"#include <boost/accumulators/statistics/median.hpp>"** is included. So, one should be removed .
@hkaiser Would you mind to review !!
=> Deleting one include of median from BOOST library to arithmetics_counter file

src/runtime.cpp
This also removes the call to std::abort in the termination handler as the system is aborting anyways.
=> Optionally disable printing of diagnostics during terminate.

src/runtime.cpp
Updating file as during registering performance counter in function ```void runtime::register_counter_types()``` the description of some performance counter is not aptly correct , which should be updated .
@hkaiser Would you mind to have a review.
=> Updating Runtime.cpp by adding correct description of Performance counters during register

tests/regressions/lcos/sliding_semaphore_2338.cpp
Increment `signal_count` before signaling semaphore to make sure it is incremented by the time the test is done.
`sliding_semaphore_2338` fails every now and then on rostam.
=> Fix sliding_semaphore_2338 test

docs/CMakeLists.txt, hpx/include/parallel_fill.hpp, hpx/parallel/algorithms/count.hpp, hpx/parallel/algorithms/fill.hpp, hpx/parallel/container_algorithms.hpp, hpx/parallel/container_algorithms/fill.hpp, tests/unit/parallel/container_algorithms/fill_range.cpp, tests/unit/parallel/container_algorithms/filln_range.cpp
This is a continuation of my work on #1668. This brings `parallel::fill` and `parallel::fill_n` into accordance with the Ranges TS.
=> parallel::{fill|fill_n}  updated for Ranges TS.

src/runtime_impl.cpp
This fixes a race where `runtime_impl::run_helper` could set the runtime status to `running` before `runtime_impl::start` sets the status to `pre_main` (the status would then be stuck at `pre_main` instead of `running` after actually starting the runtime).
=> Set pre_main status before launching run_helper

tests/unit/lcos/sliding_semaphore.cpp
The test fails if `sem.signal(10)` happens to run before at least one `sem.signal(x)` with `x < 10` (can happen because apply does not guarantee ordering).
This fixes it by using the atomic count as the argument to `sem.signal`.
=> Fix sliding_semaphore test

docs/manual/existing_performance_counters.qbk, src/performance_counters/registry.cpp, src/performance_counters/server/arithmetics_counter_extended.cpp, src/runtime.cpp
References #2455 
This PR has added one new arithmetic performance counter which is ```count``` . This mainly returns the count of values present in the accumulator containing values of the underlying counters.
=> Addition of new arithmetic performance counter "Count"

src/runtime/components/server/runtime_support_server.cpp, src/runtime/resource/partitioner.cpp
This is to test if this helps for the Windows shutdown problems, but I will still see if we can get by with the `stopped_` and `terminated_` flags being `atomic<bool>`s instead (the mutex has to be locked in any case for the condition variables).
- Unlock mutex while yielding/suspending HPX thread during shutdown
- Includes #3203 
HPX threads can migrate between OS threads. Holding an OS mutex in an HPX thread which gets migrated to another OS thread is undefined behaviour (this is checked on Windows). For #3203 a mutex was being held while being destructed.
=> Fix locking problems during shutdown

hpx/util/detail/pack_traversal_async_impl.hpp
Previous form caused compiler errors, new form is fine.
=> Reorder a variadic array to satisfy VS 2017 15.6

docs/manual/build_system/prerequisites.qbk
- Moved the important box about Windows platform to the top
- Added information about possible necessity of using --build-type=complete in the b2 command on Windows platform in the above mentioned important box
- deleted the --build-type=complete from the cross-platform code box
linux users do not use option --build-type=complete so it should not be listed in the cross-platform box. --build-type=complete was added initially for Windows users therefore I moved it to Windows important box.
=> Changed prerequisites.qbk to avoid confusion while building boost.

tests/unit/parallel/executors/sequenced_executor.cpp
Fixes the `sequenced_executor` test, assuming I've read the docs correctly and that they are correct.
Check in the test that the launched thread(s) is(are) executed in the calling thread (not in a different thread). This only applies for the `bulk_then_execute` test. The others already do the correct check.
See my comment in #3205 for background.
=> Fix check in sequenced_executor test

examples/quickstart/init_globally.cpp
Fixes #3208.
- Use `.preinit_array` section instead of `.init_array` to get `argc` and `argv` in the `init_globally` example.
The problem in #3204 was that `argc`  and `argv` were not initialized before the global `manage_global_runtime` object was constructed, leading `hpx::start` to fail (assumes that `argc >= 1`).
From my brief googling it seems that functions in `.preinit_array` are supposed to run before constructors of global objects, but I could not find a definitive source ([this](https://www.cs.stevens.edu/~jschauma/810/elf.html) was the best I could find), and it's not clear to me why release and debug behave differently. This should, however, not be worse than using `.init_array`.
@NK-nikunj Could you try this out to see that this doesn't just work on my system?
=> Use preinit_array to set argc/argv in init_globally example

docs/CMakeLists.txt, hpx/include/parallel_search.hpp, hpx/parallel/algorithms/search.hpp, hpx/parallel/container_algorithms.hpp, hpx/parallel/container_algorithms/search.hpp, hpx/parallel/util/compare_projected.hpp, tests/unit/parallel/container_algorithms/CMakeLists.txt, tests/unit/parallel/container_algorithms/search_range.cpp, tests/unit/parallel/container_algorithms/searchn_range.cpp
This is further continuation of my work with regards to issue #1668. For this particular pull request please take your time with the review process as this is my largest contribution to the library thus far, and I did make some changes to the existing library most notably, to `hpx/parallel/util/compare_projected.hpp` in order to extend it such that it can take two distinct projections. In addition I added an extra constraint to the search(_n) algorithm's template parameter list, enforcing that the two respective iterators are implicitly convertible which is a constraint stated [here](http://en.cppreference.com/w/cpp/algorithm/search). 
Edit: I have since removed the implicit convertible check as it appears after consulting with stack overflow that this an error in the website's template.
=> Adapted parallel::{search | search_n} for Ranges TS (see #1668)

hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp
Fixes locks held during suspension.
- Unlock locks earlier so that they are not held while suspending (HPX threads)
- This still keeps the guarantee the new threads are not created on suspended threads (when elasticity is enabled)
This fixes a problem uncovered by #3203 and #3209.
=> Relax locks for thread suspension to avoid holding locks when yielding

src/runtime.cpp
This abort was removed with #3188.
Without this change, applications can not be stopped by for example hitting ctrl+c or when an exception occurs.
=> Readding accidently removed std::abort

examples/resource_partitioner/shared_priority_scheduler.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/policies/hierarchy_scheduler.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, hpx/runtime/threads/policies/throttling_scheduler.hpp
This was an oversight when doing thread suspension, and makes sure `create_thread` and `schedule_thread` behave the same way in terms of not scheduling on suspended threads.
- Add a `select_active_pu` function to `scheduler_base` which accepts an initial thread number (this one is tried first, others are tried sequentially, wrapping around when needed), and an optional fallback thread number (used in case locks can't be taken immediately to avoid looping forever; the fallback is used in `scheduling_loop` to avoid looping for too long when the current pu could do work)
- None of the above is done if elasticity is disabled
=> Make schedule_thread take suspended threads into account

plugins/parcelport/libfabric/header.hpp, plugins/parcelport/libfabric/libfabric_controller.hpp, plugins/parcelport/libfabric/locality.hpp, plugins/parcelport/libfabric/receiver.cpp, plugins/parcelport/libfabric/rma_receiver.cpp, plugins/parcelport/libfabric/sender.cpp
This patch makes the libfabric parcelport compile and run again after the recent changes
=> Fixing Libfabric Parcelport

hpx/runtime/threads/policies/thread_queue.hpp
- Make sure that `new_tasks_count_` is decremented only after a corresponding count has been incremented (when moving tasks from one queue to another)
- This is to make sure `new_tasks_count_ + thread_map_count_` never goes to 0 while there are tasks available (see below for example)
This is relevant for suspending the runtime after launching a task
```
// in main thread
// no tasks in queues at this point
hpx::async(...); // task added to new_tasks
// scheduler on worker thread removes task from new_tasks (decrements count)
hpx::suspend(); // get_thread_count returns 0, runtime suspends even though
// it should wait for the async task to run
// scheduler on worker thread adds task to thread_map (increments count)
```
I find this a bit ugly, but I expect it to be temporary. Once #3146 and …
=> Modify task counting in thread_queue.hpp

CMakeLists.txt, hpx/runtime/threads/coroutines/coroutine.hpp, hpx/runtime/threads/coroutines/detail/context_base.hpp, hpx/runtime/threads/coroutines/detail/coroutine_self.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/thread_data.hpp, hpx/runtime/threads/thread_data_fwd.hpp, hpx/util/annotated_function.hpp, hpx/util/apex.hpp, src/runtime/threads/thread_data.cpp
- Adds apex_new_task() call when HPX threads are constructed.  The resulting object pointer (apex::task_wrapper* cast as a void*) is stored in the thread.
- Updates the apex start/yield/stop calls to take the apex::task_wrapper object pointer.  The apex::stop call will destroy the object, so HPX doesn't have to manage that memory.
- Removes the start/stop around the background thread - the measurement of that thread actually is handled when the work is scheduled in the regular scheduler.
This pull request updates the APEX/HPX integration to track task dependencies, generate GUIDs within APEX for tracking tasks, and adds those GUIDs to the OTF2 trace output.  The version of APEX that cmake will pull has been modified from "master" to "v2.0", a new tag in APEX representing these API …
=> Apex refactoring with guids

hpx/util/interval_timer.hpp, src/util/interval_timer.cpp
Adds the function change_interval in hpx::util::interval_timer. This function allows the user to change the interval (attribute microsecs_) used by an interval_timer, thereby, slowing it down or speeding it up.
=> Adds new feature: changing interval used in interval_timer (issue 3244)

hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, hpx/runtime/threads/policies/scheduler_mode.hpp, hpx/runtime/threads/policies/static_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/static_queue_scheduler.hpp, src/runtime/threads/threadmanager.cpp, tests/unit/resource/shutdown_suspended_pus.cpp, tests/unit/resource/suspend_pool.cpp, tests/unit/resource/suspend_pool_external.cpp, tests/unit/resource/suspend_runtime.cpp, tests/unit/resource/throttle.cpp, tests/unit/resource/throttle_timed.cpp
This is a follow-up on the fixes in #3180 to allow suspension on static schedulers (in most cases).
- Add a `has_thread_stealing` function to schedulers
- Disallow thread suspension from the same pool if `has_thread_stealing` returns `false`
- Allow thread (except from same pool), pool and runtime suspension on static schedulers
#3179 and #3180.
=> Allow suspension also on static schedulers

hpx/runtime/resource/detail/partitioner.hpp, hpx/runtime/resource/partitioner.hpp, hpx/runtime/threads/policies/scheduler_mode.hpp, src/runtime/resource/detail/detail_partitioner.cpp, src/runtime/resource/partitioner.cpp, src/runtime/threads/threadmanager.cpp
- Add a `default_mode` value to the scheduler mode enum
- Add a an optional scheduler mode parameter to `create_thread_pool` with a default value of `default_mode`
Addresses #3082, but I'm not sure what more we might want. This at least simplifies the use cases in the suspension tests (one does not need to use the callback version of `create_thread_pool` anymore to change scheduler modes).
=> Add optional scheduler mode parameter to create_thread_pool function

hpx/compute/host/block_allocator.hpp, tests/unit/computeapi/host/block_allocator.cpp
Fixes #3267.
- Make `bulk_construct` and `bulk_destroy` no-ops if `count` is `0`.
=> Fix bulk_construct with count = 0

hpx/runtime/threads/coroutines/detail/context_generic_context.hpp
The two removed lines were wrapped in `#if BOOST_VERSION < 105600`, and should not be there now that the minimum required Boost version is higher.
Should fix [these build failures](http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_63_centos_x86_64_debug/builds/260/steps/build_core/logs/stdio), although I could not reproduce it with gcc 6.3 (rostam has 6.4).
=> Remove leftover code from context_generic_context.hpp

tests/unit/performance_counter/reinit_counters.cpp
The reinit must happen before `get_counter_values_array` is called.
This is required by #3243, where the `reinit` always gets called after `get_counter_values_array`.
=> Reinit counters synchronously in reinit_counters test

hpx/runtime/resource/detail/partitioner.hpp, hpx/runtime/resource/partitioner.hpp, hpx/runtime/threads/policies/scheduler_mode.hpp, src/runtime/resource/detail/detail_partitioner.cpp, src/runtime/resource/partitioner.cpp, src/runtime/threads/threadmanager.cpp, tests/unit/resource/CMakeLists.txt, tests/unit/resource/shutdown_suspended_pus.cpp, tests/unit/resource/suspend_disabled.cpp, tests/unit/resource/suspend_pool.cpp, tests/unit/resource/suspend_pool_external.cpp, tests/unit/resource/suspend_runtime.cpp, tests/unit/resource/suspend_thread.cpp, tests/unit/resource/suspend_thread_external.cpp, tests/unit/resource/suspend_thread_timed.cpp
General cleanup of suspension tests.
- Use new `create_thread_pool` function to set elasticity flag
- Rename throttle tests to suspend_thread_X
- Improve general consistency of tests
- Test all schedulers (whether they should succeed or not)
Depends on #3228 and #3230.
=> Clean up suspension tests

hpx/config.hpp, hpx/plugins/plugin_registry.hpp, src/runtime/components/server/runtime_support_server.cpp, src/util/command_line_handling.cpp
A couple of minor changes allowing for external libraries to load their own plugins through HPX's plugin infrastructure. 
These are changes required by Phylanx.
=> Support external plugins

hpx/runtime/threads/policies/static_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/static_queue_scheduler.hpp
Fixes warnings in the static schedulers about virtual methods not being marked override.
=> Fix virtual method override warnings in static schedulers

hpx/lcos/future.hpp, hpx/lcos/local/packaged_continuation.hpp
- if the outer future of a future<Future> is ready we don't need to allocate a new
shared state while unwrapping
=> Do not unwrap ready future

cmake/HPX_SetupBoost.cmake, plugins/parcelport/libfabric/CMakeLists.txt, plugins/parcelport/libfabric/libfabric_controller.hpp, plugins/parcelport/libfabric/parcelport_libfabric.cpp, plugins/parcelport/libfabric/rma_receiver.cpp
HPX_PARCELPORT_LIBFABRIC_ENDPOINT_RDM fixes.
Fixes #2650 
platforms without LIBFABRIC_ENDPOINT_RDM turned on have compile time errors. this patch resolves compile issues. this patch also fixes an issue where the passive endpoint is not turned into an active endpoint for IPC. without this fix active endpoints are never created; active endpoints are created only in blocks of code with the HPX_PARCELPORT_LIBFABRIC_ENDPOINT_RDM #define guard. active endpoints are necessary for IPC.
=> libfabric parcelport w/o HPX_PARCELPORT_LIBFABRIC_ENDPOINT_RDM

hpx/lcos/local/packaged_continuation.hpp, tests/unit/parallel/segmented_algorithms/partitioned_vector_find.cpp, tests/unit/parallel/segmented_algorithms/partitioned_vector_find2.cpp
Fixes failures like [these](http://rostam.cct.lsu.edu/builders/hpx_clang_3_9_boost_1_62_centos_x86_64_release/builds/10/steps/run_unit_tests/logs/tests.unit.parallel.segmented_algorithms.distributed.tcp.partitioned_vector_find%20%280.78%20sec%29).
=> Fix partitioned vector include in partitioned_vector_find tests

hpx/lcos/detail/future_data.hpp, hpx/lcos/future.hpp, hpx/lcos/local/futures_factory.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/lcos/local/promise.hpp, hpx/lcos/promise.hpp, hpx/lcos/wait_all.hpp, hpx/runtime/components/client_base.hpp, tests/unit/lcos/CMakeLists.txt, tests/unit/lcos/make_ready_future.cpp, tests/unit/lcos/promise_emplace.cpp
This adds support for [P0319](http://wg21.link/p0319) to `hpx::lcos::promise`, `hpx::lcos::local::promise`, and hpx::make_ready_future`
=> Adding emplace support to promise and make_ready_future

hpx/runtime/resource/detail/create_partitioner.hpp, hpx/runtime/resource/partitioner.hpp, tests/unit/resource/suspend_pool_external.cpp, tests/unit/resource/suspend_runtime.cpp
Adds `nullptr_t` overloads to the resource partitioner (as previously for `hpx::init` and `start`). This is needed if one wants to use the resource partitioner and not set an entrypoint (since `hpx::init` and `start` have no effect after the resource partitioner has been created).
Also cleans up some suspension tests where `hpx_main` was not used.
=> Add nullptr_t overloads to resource partitioner

examples/compute/cuda/CMakeLists.txt, examples/compute/cuda/cublas_matmul.cpp, examples/compute/cuda/cuda_future.cpp, examples/compute/cuda/cuda_future_helper.h, examples/compute/cuda/trivial_demo.cu
This example shows how to launch a kuda kernel and bind it to
an hpx::future so that continuations may be attached to it
in the same way as a CPU task.
A new helper class is introduced that can be used with the old
cuBlas +future example code. This commit unifies the two to make a
cleaner integration.
The cuda_future_helper might benefit from being moved into the main
hpx::compute tree rather than being in examples.
=> Add new cuda kernel synchronization with hpx::future demo

hpx/runtime/components/server/migration_support.hpp, hpx/runtime/naming/name.hpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/server/primary_namespace_server.cpp, src/runtime/agas/server/route.cpp, tools/VS/gid_type.natvis
- this removes acquiring a lock from various AGAS operation for all
non-migratable object
=> Marking migratable objects in their gid to allow not handling migration in AGAS

.clang-format
This updates the .clang-format configuration file to utilize newer features of clang-format (V7.0 and later). This brings the formatted source code very close to the 'native' HPX way of formatting code.
=> This updates the .clang-format configuration file to utilize newer features

hpx/lcos/dataflow.hpp
When hpx::launch::sync is passed as the execution policy for long dataflow
chains with almost always ready futures, we might run into a stack overflow due
to recursion. This patch fixes it by detecting if there is enough stack space
left and creating a new thread if there isn't.
=> Fixing potential stack overflow for dataflow

.circleci/config.yml, tools/inspect/inspect_to_junit.py
With this PR CircleCI can understand Inspect tool errors and show them in its messages. This is done through conversion of inspect tool's HTML output to JUnit XML understood by CircleCI.
=> Add conversion of inspect reports to JUnit XML

hpx/runtime/threads/policies/affinity_data.hpp, src/runtime/resource/detail/detail_partitioner.cpp, src/runtime/threads/policies/affinity_data.cpp
Fixes #3300.
- Make sure pu masks and thread occupancy are used/computed correctly when using `pu-step` and `pu-offset` command line options.
=> Fix pu-step and pu-offset command line options

hpx/lcos/reduce.hpp
MSVC somehow confuses the two templates that have the same name. Renaming one fixes things...
=> Fix compilation with VS 15.7.1 and /std:c++latest

examples/1d_stencil/1d_stencil_1_omp.cpp, examples/1d_stencil/1d_stencil_3_omp.cpp
Makes sure the `1d_stencil` examples with OpenMP build.
Includes `hpx/config.hpp` before including `boost/program_options.hpp` to avoid this:
```
In file included from /home/simbergm/src/hpx/hpx/util/format.hpp:9:0,
from /home/simbergm/src/hpx/examples/1d_stencil/print_time_results.hpp:10,
from /home/simbergm/src/hpx/examples/1d_stencil/1d_stencil_1_omp.cpp:28:
/home/simbergm/src/hpx/hpx/config.hpp:14:2: error: #error Boost.Config was included before the hpx config header. This might lead to subtile failures and compile errors. Please include <hpx/config.hpp> before any other boost header
#error Boost.Config was included before the hpx config header. This might lead to subtile failures and compile errors. Please include <hpx/config.hpp> before any other boost header
```
=> Fix includes for 1d_stencil_*_omp examples

cmake/HPX_AddTest.cmake, cmake/templates/hpxrun.py.in, hpx/runtime/threads/detail/scheduling_loop.hpp, python/scripts/hpx_run_test.py, tests/regressions/agas/CMakeLists.txt, tests/regressions/components/CMakeLists.txt, tests/regressions/util/CMakeLists.txt, tests/regressions/util/command_line_arguments_706.cpp, tests/unit/agas/CMakeLists.txt, tests/unit/component/CMakeLists.txt, tests/unit/parallel/executors/service_executors.cpp, tests/unit/parcelset/put_parcels.cpp
- Disable the background thread completely in `scheduling_loop` if `HPX_HAVE_NETWORKING=OFF`
- The flag can still be set but has no effect
- This is unlikely to give a big speedup in any application, but it's nice to disable as the background thread doesn't do anything useful with networking off
@biddisco Might give you a *tiny* speedup for Cholesky, unless you've already disabled the background thread.
WIP as I will still run the tests with pycicle and networking off.
=> Disable background thread when networking is off

tests/performance/parallel_algorithms/local/benchmark_remove.cpp, tests/performance/parallel_algorithms/local/benchmark_remove_if.cpp, tests/performance/parallel_algorithms/local/benchmark_unique.cpp
Fixes #3318
The 4-argument version of `std::equal` that was used in the failing benchmarks is a C++14 feature which shouldn't have been used.
=> Replacing C++14 feature with equivalent C++11 code

hpx/runtime/applier/apply.hpp
Fixes #3297 
I'm not sure if this is correct, but it fixes my problems and now the traces are written
=> Fix a missing apex thread data (wrapper) initialization

tests/unit/parallel/algorithms/inplace_merge_tests.hpp, tests/unit/parallel/algorithms/merge_tests.hpp, tests/unit/parallel/algorithms/partition_copy_tests.hpp, tests/unit/parallel/algorithms/partition_tests.hpp, tests/unit/parallel/algorithms/remove_tests.hpp, tests/unit/parallel/algorithms/test_utils.hpp, tests/unit/parallel/algorithms/unique_copy_tests.hpp, tests/unit/parallel/algorithms/unique_tests.hpp, tests/unit/parallel/container_algorithms/inplace_merge_range.cpp, tests/unit/parallel/container_algorithms/merge_range.cpp, tests/unit/parallel/container_algorithms/partition_copy_range.cpp, tests/unit/parallel/container_algorithms/partition_range.cpp, tests/unit/parallel/container_algorithms/remove_if_range.cpp, tests/unit/parallel/container_algorithms/remove_range.cpp, tests/unit/parallel/container_algorithms/test_utils.hpp, tests/unit/parallel/container_algorithms/unique_copy_range.cpp, tests/unit/parallel/container_algorithms/unique_range.cpp
This is related to #3318 and #3319.
I fixed my mistakes in the codes written by me. (Sorry to my mistake)
=> Replace C++14 overload of std::equal with C++11 code.

src/exception.cpp, src/hpx_init.cpp, src/util/command_line_handling.cpp, src/util/init_ini_data.cpp
- add more logging to module discovery
- flyby: don't log hpx::success as error
=> Make sure logging is up and running while modules are being discovered.

hpx/components/component_storage/server/migrate_from_storage.hpp, hpx/include/traits.hpp, hpx/lcos/detail/async_implementations.hpp, hpx/runtime.hpp, hpx/runtime/actions/component_action.hpp, hpx/runtime/components/pinned_ptr.hpp, hpx/runtime/components/server/component_base.hpp, hpx/runtime/components/server/fixed_component_base.hpp, hpx/runtime/components/server/locking_hook.hpp, hpx/runtime/components/server/managed_component_base.hpp, hpx/runtime/components/server/memory.hpp, hpx/runtime/components/server/memory_block.hpp, hpx/runtime/components/server/migrate_component.hpp, hpx/runtime/components/server/migration_support.hpp, hpx/runtime/components/server/runtime_support.hpp, hpx/runtime/get_ptr.hpp, hpx/traits/action_decorate_function.hpp, hpx/traits/component_pin_support.hpp, tests/unit/component/migrate_component.cpp
- fix problem in traits::action_decorate_function when used with component type
- adding more test cases for migrating components that expose actions returning futures
- flyby: factor out pinning/unpinning into separate trait
This fixes #3325
=> Making sure object is pinned while executing actions, even if action returns a future

hpx/util/plugin/detail/dll_dlopen.hpp, src/lcos/barrier.cpp
- made global mutex in dll_open live long enough
- made sure barrier gets destructed on an HPX thread
=> Safeguard HPX against destruction in global contexts

hpx/util/command_line_handling.hpp, hpx/util/parse_command_line.hpp, src/util/command_line_handling.cpp, src/util/parse_command_line.cpp, tests/regressions/CMakeLists.txt, tests/regressions/options_as_config_3339.cpp
Fixes #3339
This patch allows for command line options to be used instead of the configuration setting as explained in #3339.
@bcumming, @biddisco please check whether this solves your problem
=> Allowing for all command line options to be used as configuration settings

.circleci/config.yml
Currently the inspect tool results are not converted to JUnit XML when it does actually fail. This PR ensures that it does.
=> Always convert inspect results to JUnit XML

docs/quickstart.qbk
`find_package` is case sensitive so correct name from `hpx` to `HPX`.
=> Fix CMakeLists.txt example in quick start

docs/manual/applying_actions.qbk, docs/manual/components.qbk, docs/manual/loading_components.qbk, docs/tutorial/futurization_example.qbk
The futurization examples use `hpx::components::component` opposed to what is stated in the description. According to H. Kaiser the usage of the template class aliases `simple_component` and `simple_component_base` is deprecated.
=> Replace `simple_component*` with `component*` in the Documentation

CMakeLists.txt, docs/manual/config_defaults.qbk, hpx/config.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, src/util/runtime_configuration.cpp
- Make scheduling loop idle backoff exponential
- Add maximum sleep time (can be configured through `hpx.max_idle_backoff_time`)
This makes HPX idle quicker than with the linear backoff. Combined with decreasing `hpx.max_idle_loop_count` this makes HPX idle CPU usage close to 0. This is useful for interactive HPX usage where HPX might not have work all the time (`HPX_HAVE_THREADMANAGER_IDLE_BACKOFF=Off` is still there for those who don't want this behaviour).
=> Make idle backoff exponential with maximum sleep time

plugins/parcelport/libfabric/libfabric_controller.hpp
Fixes #3352 
Allows nodes to send messages using libfabric over TCP
Does not yet fix the boot/initialization, this still uses the default TCP boost:asio parcelport
=> Fix libfabric tcp

hpx/plugins/parcelport/tcp/sender.hpp, src/state.cpp
- flyby: fix threadmanager_is()
=> Making sure all parcels get destroyed on an HPX thread (TCP pp)

.circleci/config.yml
This is a dumb solution to filtering not working on individual commands in the CircleCI config, i.e. it does the filtering with a bash if statement by checking the `CIRCLE_BRANCH` environment variable.
As far as I could tell, doing this the official way would involve copying files using the cache/workspace and or duplicating workflow steps, so I thought this is more manageable even though the docker push step will still show up on PRs.
=> Only run docker push on master on CircleCI

CMakeLists.txt
This is to adapt the integration of HPXMP to its latest changes (see https://github.com/STEllAR-GROUP/hpxMP/pull/6)
=> Adapt integration of HPXMP to latest build system changes

hpx/runtime/components/server/runtime_support.hpp, src/runtime/components/server/runtime_support_server.cpp
Fixes #3358.
The problem was likely introduced by me in #3209. The added `unlock_guard` in `runtime_support_server.cpp` allowed the `wait` function to proceed occasionally. This PR splits the `stopped_` variable to `stop_called_` (which prevents `stop` from being called multiple times) and `stop_done_` (which prevents `wait` from proceeding too early).
=> Fix deadlock during shutdown

hpx/runtime/agas/server/component_namespace.hpp, hpx/runtime/agas/server/locality_namespace.hpp, hpx/runtime/agas/server/primary_namespace.hpp, hpx/runtime/agas/server/symbol_namespace.hpp, hpx/util/scoped_timer.hpp, src/runtime/agas/server/component_namespace_server.cpp, src/runtime/agas/server/locality_namespace_server.cpp, src/runtime/agas/server/primary_namespace_server.cpp, src/runtime/agas/server/route.cpp, src/runtime/agas/server/symbol_namespace_server.cpp
- Make sure measurement of AGAS functionalities (count/time for the corresponding
performance counters) is actually performed only if a performance counter has
been instantiated.
=> Make AGAS measurements optional

hpx/include/components.hpp, hpx/include/sync.hpp, hpx/lcos/dataflow.hpp, hpx/lcos/detail/async_implementations.hpp, hpx/lcos/detail/async_implementations_fwd.hpp, hpx/lcos/detail/async_unwrap_result_implementations.hpp, hpx/lcos/detail/async_unwrap_result_implementations_fwd.hpp, hpx/lcos/detail/future_data.hpp, hpx/lcos/detail/future_transforms.hpp, hpx/lcos/detail/sync_implementations.hpp, hpx/lcos/detail/sync_implementations_fwd.hpp, hpx/lcos/sync.hpp, hpx/lcos/sync_fwd.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/components/colocating_distribution_policy.hpp, hpx/runtime/components/default_distribution_policy.hpp, hpx/runtime/components/target_distribution_policy.hpp, hpx/runtime/components/unwrapping_distribution_policy.hpp, hpx/runtime/components/unwrapping_result_policy.hpp, hpx/sync.hpp, hpx/util/detail/pack_traversal_async_impl.hpp, src/lcos/detail/future_data.cpp, tests/unit/lcos/CMakeLists.txt, tests/unit/lcos/async_unwrap_result.cpp, tests/unit/lcos/sync_remote.cpp
- add hpx::sync, semantically equivalent to hpx::async().get(), except that in the
case of local execution of a direct action no future needs to be created
- add hpx::unwrap_result 'distribution policy' that can be used with hpx::async and
direct actions that return a future on the server side. That allows to avoid
creating the outer future in case of local synchronous execution.
- several minor optimizations for hpx::future and hpx::unwrapping
=> Add several functionalities allowing to optimize synchronous action invocation

hpx/hpx_main.hpp, src/hpx_init.cpp, src/hpx_wrap.cpp
This PR adds Debug option for `hpx` initialization after using `hpx_main.hpp`. Consider the following example:
```cpp
#include <hpx/hpx_init.hpp>
#include <hpx/hpx_main.hpp>
int hpx_main()
{
return hpx::finalize();
}
int main()
{
return hpx::init();
}
```
Since `hpx` runtime is already initialized from main, this would result in the following error message:
```
hpx is already initialized from main.
Note: Delete hpx_main.hpp to initialize hpx system using hpx::init. Exiting...
```
This is more verbose as compared to previous error message which would explain that `hpx::init can't initialize the runtime system.`
=> Adds Debug option for hpx initializing from main

docs/hpx.qbk, docs/manual/applications.qbk, docs/manual/hpx_main_usage.qbk
This PR updates the docs to include the recent implementation for `hpx_main.hpp`. It now adds a `caution` for using `hpx_main.hpp` only once and in the executable. It also explains in brief how __HPX__ is able to seamlessly initiate things from main.
@hkaiser , I can add information specific to Linux and Apple implementations as well, if you want to include it in the docs.
=> Updates doc with recent hpx_wrap implementation

src/main.cpp
=> fixing multiple difinition of main() in linux

.circleci/config.yml
This PR adds `-DHPX_HAVE_THREAD_LOCAL_STORAGE=ON` to HPX builds. This is done since the HPX image created by CircleCI is used by the [HPX project](https://github.com/STEllAR-GROUP/hpxmp).
=> Adding DHPX_HAVE_THREAD_LOCAL_STORAGE=ON to builds

src/hpx_init.cpp
This PR fixes the breaking of master on non Linux systems for not finding out about `hpx_start` and `include_libhpx_wrap`.
=> Allow debug option to be enabled only for Linux systems with dynamic main on

docs/manual/existing_performance_counters.qbk
Mismatched brackets were causing docs build failures. I've also changed the indentation to match the style that was there.
=> Fix brackets and indentation in existing_performance_counters.qbk

hpx/util/lightweight_test.hpp, tests/performance/local/CMakeLists.txt, tests/performance/local/agas_cache_timings.cpp, tests/performance/local/async_overheads.cpp, tests/performance/local/future_overhead.cpp, tests/performance/local/resume_suspend.cpp, tests/performance/local/serialization_overhead.cpp, tests/performance/local/spinlock_overhead1.cpp, tests/performance/local/spinlock_overhead2.cpp, tests/performance/local/start_stop.cpp, tests/performance/local/stencil3_iterators.cpp, tests/performance/local/wait_all_timings.cpp, tests/unit/parallel/algorithms/exclusive_scan.cpp, tests/unit/parallel/algorithms/inclusive_scan.cpp, tests/unit/parallel/algorithms/inclusive_scan_tests.hpp, tests/unit/parallel/algorithms/reduce_by_key.cpp, tests/unit/parallel/algorithms/sort.cpp, tests/unit/parallel/algorithms/sort_by_key.cpp
This adds `DartMeasurement` tags to the output so that timing can be plotted in CDash.
The idea behind this is that if we take some simple test that provides a useful benchmark, we ought to be able to see if atomic futures and scheduling fixes make a noticable difference over time.
=> Add CDash timing output to future overhead test (for graphs)

.circleci/config.yml
Fixes #3424.
Note: this does a shallow local clone to avoid copying the whole 900 MB repository using the workspace between work steps. This is not strictly necessary and can be reverted if we ever want to query the git repo for more information than the current hash. I did this because copying the whole repo using the workspace was significantly slower than doing the same with the cache, but since there doesn't seem to be a way to save to the cache anymore on PRs from forked repos this is a small optimization to get it back to the same performance as before.
=> Use source cache and workspace between job steps on CircleCI

CMakeLists.txt
This suppresses a warning that has no consequences for HPX
=> This suppresses a deprecation warning that is being issued by MSVC 19.15.26726

hpx/util/apex.hpp
Only appears when APEX is enabled, so missed it in the last big warnings patch.
=> Fix unused params warning

src/hpx_init.cpp
Fixes #3426 
Changes the `extern bool` to actual bool variable in `hpx_init.cpp`. Turns out Mac OSX works differently for `weak` variables as compared to Linux. In Linux, if a variable is declared `extern weak` then it allows to compile and link without producing any errors. For Mac OSX, however, it produces errors while linking (it does compile without errors though).
I do not understand as to why we didn't get such an error before while merging the Mac OSX implementation. As of now, this PR should fix things.
**PS.** Tested with Mac OSX Sierra and Ubuntu Budgie 18.04.
=> Fixes #3426

cmake/templates/hpxrun.py.in, src/util/command_line_handling.cpp
Fixes a mistake introduced in #3429, hpx:threads=all was not working as expected and one test was failing due to a problem with hpxrun.py
=> Fix threads cores

hpx/runtime/threads/coroutines/detail/tss.hpp, src/runtime/threads/coroutines/detail/coroutine_impl.cpp, tests/unit/threads/tss.cpp
Fixes #1205
- Fixing double delete problem:
- This adds a move ctor and move assignment for tss_node to avoid double deletes
in case of temporary objects.
- Unbreaking unit test:
- The test had a timing issues. The TSS dtors are called after the task making
the future ready returns.
- Properly reseting the coroutine context to avoid an assertion being triggered.
=> Fixing 1205

src/util/runtime_configuration.cpp
Fixes `start_stop_callbacks` test when service pools are disabled (e.g. `HPX_HAVE_NETWORKING=OFF`).
=> Only enable service pool config options if pools are enabled

docs/CMakeLists.txt, hpx/include/parallel_find.hpp, hpx/parallel/algorithms/find.hpp, hpx/parallel/container_algorithms.hpp, hpx/parallel/container_algorithms/find.hpp, tests/unit/parallel/algorithms/findend.cpp, tests/unit/parallel/algorithms/findfirstof.cpp, tests/unit/parallel/container_algorithms/CMakeLists.txt, tests/unit/parallel/container_algorithms/find_end_range.cpp, tests/unit/parallel/container_algorithms/find_first_of_range.cpp
This started as an attempt to make find_* Ranges TS compliant (see #1668). But during testing, i discovered and fixed a bad bug in find_end making it unusable with custom comparison operator.
Because of this bug, i am making this pull request now, before writing a container version of the above algorithms. The regular versions are already usable as given in this pull request.
=> Add projection function to find_* (and fix very bad bug)

hpx/lcos/local/futures_factory.hpp, hpx/runtime/parcelset/decode_parcels.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, hpx/runtime/threads/thread_enums.hpp
- flyby: adding some override keywords
=> Fixing warnings related to silent conversion of size_t --> int16_t

CMakeLists.txt
The share directory is not created when the cmake tries to symlink
HPX installation to share directory. This creates a minor and
eventually inconsequential error in the configuration as shown
below:
failed to create symbolic link '/home/jayesh/build/hpx/share/hpx': No such file or directory
This commit fixes it by creating a directory beforehand.
Fixes #3462
=> - cmake : create the parent directory before symlinking

hpx/runtime/threads/detail/scheduled_thread_pool.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, hpx/runtime/threads/policies/scheduler_base.hpp
Adds an early return to `get_next_thread` in `local_(priority_)queue_scheduler` when
suspending worker thread (i.e. when not running).
The old behavior was to still try to steal pending threads from other worker threads. The current behavior is similar to `wait_or_add_new`, which already had an early return to not steal staged threads
when suspending. This should fix worker thread suspension cases where the HPX thread trying to suspend a worker thread would get scheduled on another thread (correctly) but then be stolen back immediately by the worker thread being suspended before another worker thread has the chance to run it. This should probably have been there all along.
Quick testing showed an immediate improvement but I'll keep this WIP until I've soak tested it a bit longer (and I'm …
=> Fix some thread suspension timeouts

.circleci/config.yml
Check `CIRCLE_PR_NUMBER` (in addition to checking for master branch) to see if a PR is from a forked repo in docker push step on CircleCI. With the old check PRs from master branches on forked repos would try to do `docker push` and fail.
=> Check for forked repos in CircleCI docker push step

hpx/config/attributes.hpp
These warnings come up when building HPX with C++11 or 14 and a new compiler such as gcc 7.
=> Add compiler specific fallthrough attributes if C++17 attribute is not available

hpx/lcos/dataflow.hpp, hpx/lcos/detail/future_data.hpp, hpx/lcos/detail/sync_implementations.hpp, hpx/lcos/future.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/lcos/local/promise.hpp, hpx/lcos/packaged_action.hpp, hpx/runtime/components/client_base.hpp, hpx/runtime/components/unwrapping_result_policy.hpp, hpx/traits/future_access.hpp, hpx/util/allocator_deleter.hpp, hpx/util/detail/pack_traversal_async_impl.hpp, hpx/util/pack_traversal_async.hpp, src/lcos/detail/future_data.cpp, src/runtime/agas/addressing_service.cpp, src/runtime/threads/thread_data.cpp, tests/unit/lcos/when_each.cpp, tests/unit/parallel/segmented_algorithms/CMakeLists.txt, tests/unit/parallel/segmented_algorithms/partitioned_vector_exclusive_scan2.cpp
- make AGAS properly (fast-)resolve local-only ids
- avoid reading atomic in future state  more than necessary
- marking certain hot-spot functions as force-inline
- extend `future_access_customization_point` to support addref-control while creating a future from a shared state
- `unwrapping_result_policy` now holds id by reference
- flyby: fix warnings in `when_each` test
- flyby: split `partitioned_vector_exclusive_scan` test
This also adds overloads for APIs that produce futures taking an allocator (dataflow, make_ready_future, etc.)
This may supersede #3406 if we decide not to add the `thread_local_allocator` proposed there.
=> This patch adds various optimizations extracted from the thread_local_allocator work

README.rst
Adds minimal instructions to install dependencies in the readme. Users now should be able to install dependencies by simply copying the bash command. This should simplify the overall installation process for installing HPX.
=> Updates readme

src/exception.cpp
On CircleCI the docker credentials of the current user are printed as part of the execution environment. This PR removes those from the output.
=> Don't print docker credentials as part of the environment.

src/CMakeLists.txt
The previous PR #3458 somehow got pushed by me with the wrong flag setting CMake call.
This one uses `target_compile_options` for the main hpx target and adds the PUBLIC setting so that all targets that depend on hpx also pick up the same flags.
@khuck noted on IRC that warnings had increased and he was correct.
=> Fix FLAGS - Use correct version of target_compile_options

src/hpx_wrap.cpp, tests/regressions/lcos/call_promise_get_gid_more_than_once.cpp, tests/unit/threads/tss.cpp
This fixes the issue that some tests don't report their errors back to CircleCI.
=> Making sure the application's exit code is properly propagated back to the OS

hpx/runtime/actions/basic_action.hpp
This fixes warnings occuring after recent changes to cmake.
=> Fixing type attribute warning for transfer_action

hpx/runtime/actions/basic_action.hpp
Reverts STEllAR-GROUP/hpx#3483 since it caused build failures where it should have just removed warnings. We can unrevert this again when pycicle is up so that we can check that everything is okay before merging.
=> Revert "Fixing type attribute warning for transfer_action"

hpx/runtime/actions/action_support.hpp, hpx/runtime/actions/continuation.hpp, hpx/runtime/serialization/detail/polymorphic_intrusive_factory.hpp, hpx/runtime/serialization/detail/polymorphic_nonintrusive_factory.hpp, hpx/util/debug/demangle_helper.hpp, hpx/util/demangle_helper.hpp, hpx/util/detail/function_registration.hpp
Adds an extra couple of type info print helpers and moves the demangler into the debug namespace.
Might not compile on all platforms because we had some problems with it in the past, so wanting to see what pycicle gives after a build/test of this PR.
=> Move type info into hpx::debug namespace and add print helper functions

hpx/util/detail/pack_traversal_async_impl.hpp, hpx/util/detail/pack_traversal_impl.hpp
This patch correctly handles vectors of futures that are passed in via `std::ref`.
Fixes #3248.
=> Fixing dataflow

plugins/parcelport/mpi/CMakeLists.txt, tests/headers/CMakeLists.txt
Fixes #3475
Disable MPI's (deprecated) C++ interface.
Including mpi.h might result in undefined references since it contains both the C and C++ interfaces but HPX only links against the C runtime. As HPX only uses the C interface, the C++ interface can be safely disabled to resolve the linker errors.
#3477 can be closed after merging this PR since it only provides an alternative fix.
=> Disabling MPI's (deprecated) C++ interface

cmake/HPX_AddLibrary.cmake
This just exposes `NONAMEPREFIX` to users of `add_hpx_library()` (not only `setup_target()`)
=> Support NONAMEPREFIX in add_hpx_library()

tests/unit/parallel/algorithms/CMakeLists.txt, tests/unit/parallel/algorithms/remove_if1.cpp
Fixes random test failures on CircleCI
=> Split parallel::remove_if tests to avoid OOM on CircleCI

hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp
Cherry-picked from @K-ballo's ref-qual-bind branch.
The `std::move`s were supposed to be `std::ref`s all along.
=> Fix bogus `throws` bindings in scheduled_thread_pool_impl

plugins/parcelport/mpi/CMakeLists.txt
Without this change, the fix for issue #3475, introduced in PR #3496, does break under certain circumstances.
=> Propagating the MPI compile definitions to all relevant targets

examples/resource_partitioner/CMakeLists.txt
Buildbot confirms that this now passes on the gcc 4_9 builder. I do not know how to fix the problem correctly, so the safest thing is to simply disable the tests on gcc4.9 and lower
=> Do not build guided pool examples with older GCC compilers

hpx/lcos/local/futures_factory.hpp, hpx/parallel/executors/thread_execution.hpp, hpx/runtime/threads/executors/guided_pool_executor.hpp, hpx/runtime/threads/policies/shared_priority_queue_scheduler.hpp
These patches appear to fix a couple of problems that sneaked through the guided executor merge.
Committing this to see if all tests pass with the slight tweak to the executor interface.
=> Fix guided exec

plugins/parcelport/mpi/CMakeLists.txt, tests/headers/CMakeLists.txt
Fixes #3475.
- Emulate add_compile_definitions. It was only introduced as part of CMake 3.11.
- Link against the C++-enabled MPI libraries
Unfortunately, our previous fix of disabling MPI's C++ interface via `MPI_CXX_SKIP_MPICXX` is broken. Newer versions of CMake introduce it as a cache variable. Therefore, we can not reliable
disable the C++ interface programmatically and have to link against the proper set of libraries.
If the C++ interfaces causes problems, `MPI_CXX_SKIP_MPICXX` can still be enabled manually.
=> Fixing the build system of the MPI parcelport

.circleci/config.yml
CircleCI does not build tags by default (and thus does not set the `$CIRCLE_TAG` variable for docs). This enables building for all tags and means that documentation from tagged releases will now automatically be pushed to GitHub pages.
I had to disable source caching on CircleCI (due to bugs with checking out tags) but the time for a clean clone compared to using the cache is more or less the same.
=> Add CircleCI filter for building all tags

examples/resource_partitioner/async_customization.cpp
Fixes #3549 
Simple mistake in type of int that would cause a problem on a 64bit int machine.
=> Fix uint64_t causing compilation fail on i686

hpx/exception.hpp, src/exception.cpp
=> Adding constructor `exception(boost::system::error_code const&)`

hpx/util/detail/basic_function.hpp, hpx/util/detail/vtable/vtable.hpp, hpx/util/function.hpp, hpx/util/unique_function.hpp, tests/unit/util/function/function_target.cpp
The functionality is not particularly useful, and has a high cost in binary bloat.
=> Drop util::[unique_]function target_type

CMakeLists.txt, cmake/HPX_SetupVc.cmake, tests/unit/parallel/datapar_algorithms/count_datapar.cpp, tests/unit/parallel/datapar_algorithms/countif_datapar.cpp, tests/unit/parallel/datapar_algorithms/foreach_datapar.cpp, tests/unit/parallel/datapar_algorithms/foreachn_datapar.cpp, tests/unit/parallel/datapar_algorithms/transform_binary2_datapar.cpp, tests/unit/parallel/datapar_algorithms/transform_binary_datapar.cpp, tests/unit/parallel/datapar_algorithms/transform_datapar.cpp
Fixes #3570
@diehlpk This ensures that all tests are compiling properly with the latest released version of Vc (V1.4.1)
=> Make sure HPX is usable with latest released version of Vc (V1.4.1)

tests/unit/component/CMakeLists.txt, tests/unit/component/inheritance_2_classes_concrete_simple.cpp
- flyby: make sure inheritance_2_classes_concrete test actually passes if run on  one core
@bremerm31 Everything is ok, the test you created (and the similar one that was already in HPX) was flawed. Because of the non-immediate nature of deleting components by AGAS the destructor of the objects was not called before you checked. I added an explicit call to `garbage_collect` (enforcing deletion of all pending objects) and now everything looks fine.
This fixes #3565
=> Adding test ensuring ticket 3565 is fixed

hpx/runtime/components/server/runtime_support.hpp, src/runtime/components/runtime_support.cpp, src/runtime/components/server/runtime_support_server.cpp
Fixes the possible use of empty startup/shutdown functions in the main HPX module.
=> Make sure empty startup/shutdown functions are not being used

CMakeLists.txt, README.rst, cmake/packaging/rpm/CMakeLists.txt, cmake/packaging/rpm/Changelog.txt, docs/sphinx/contributing/release_procedure.rst
Add support to generate rpm packages for HPX.
- Add HPX_WITH_RPM to generate a rpm packages using the cpack package
- make package target generates the rpm packages containing the current HPX version
-
make package generates hpx-1.2.0-1.x86_64.rpm in the build folder. The rpm packages contains boost, hwloc, and gperftools as its dependencies. 
sudo dnf install hpx-1.2.0-1.x86_64.rpm  install the headers, documentation, and all examples to /usr/local and installs the missing dependencies if they are not installed.
The package was generated on my desktop and installed within a VM using the same version of Fedora 28 and I was able to run the examples on the VM.
Once we have the debian package as well, the next step would be to integrate the packaging into our build process on circle-ci and …
=> Add support for rpm packaging

cmake/templates/HPXMacros.cmake.in
Fixes problems in dependent projects missing `CMAKE_INSTALL_LIBDIR` et.al.
=> Add include(GNUInstallDirs) to HPXMacros.cmake

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx11_std_forward_list.cpp, hpx/runtime/threads/thread_data.hpp, src/runtime/threads/thread_data.cpp
- flyby: add feature test for std::forward_list
=> Store thread exit functions in forward_list instead of deque to avoid allocations

hpx/lcos/async.hpp, hpx/lcos/sync.hpp, hpx/parallel/executors/execution.hpp, hpx/parallel/executors/thread_execution.hpp, hpx/parallel/executors/timed_executors.hpp, hpx/parallel/task_block.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/components/server/locking_hook.hpp, hpx/runtime/components/server/migration_support.hpp, hpx/runtime/parcelset/decode_parcels.hpp, hpx/runtime/parcelset/put_parcel.hpp, hpx/util/bind.hpp, hpx/util/bind_action.hpp, hpx/util/bind_back.hpp, hpx/util/bind_front.hpp, hpx/util/one_shot.hpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/big_boot_barrier.cpp, src/runtime/threads/executors/current_executor.cpp, src/runtime/threads/executors/pool_executor.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/executors/thread_pool_os_executors.cpp, src/runtime/threads/thread.cpp, tests/unit/component/action_invoke_no_more_than.hpp
Make bind propagate value category to the target callable. Make one_shot into a generic wrapper that forces rvalue-qualified invocation.
=>  Make bind propagate value category

src/runtime/resource/detail/detail_partitioner.cpp
Fixes #3594 and #3482
- Setting a wrong value to `-DHPX_WITH_MAX_CPU_COUNT` results in an unspecific error message
```
[diehlpk@centaur build]$ ./bin/fibonacci
terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
what():  The number of OS threads requested (20) does not match the number of threads to bind (12): HPX(bad_parameter)
```
This is misleading and we should improve the error handling here.
The PR shows this error message instead 
```
[diehlpk@centaur build]$ ./bin/fibonacci
terminate called after throwing an instance of 'std::runtime_error'
what():  partitioner::partioner: HPX_HAVE_MAX_CPU_COUNT is set as 64 your system has 160. Please recompile HPX and increase the maximal CPU count!
Aborted (core dumped)
```
and no error message when …
=> Improve the error message for using to less MAX_CPU_COUNT

hpx/util/checkpoint.hpp
The functions std::ostream& operator<<(std::ostream& ost, checkpoint const& ckp) and std::istream& operator>>(std::istream& ost, checkpoint const& ckp) are both defined in the header file hpx/util/checkpoint.hpp
As a result, including the header file within multiple translation units will result in a linker error due to multiple definitions of these functions.  Therefore, these functions either need to be prefaced with 'inline' or otherwise have their definitions placed in a .cpp file.  Since there is currently no file src/util/checkpoint.cpp, rather than adding this as a new file and moving the definitions there, this fix addresses the problem with the inline keyword instead.
- add inline keyword to function definitions for operator<< and operator>>
=> Add 'inline' to definition of checkpoint stream operators to fix link error

hpx/config/constexpr.hpp
Fixes constexpress defines for nvcc compiler 
- Add nvcc compiler to this check https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/config/constexpr.hpp#L12
Since we have `!defined(HPX_MSVC_NVCC)` we should add NVdida's nvcc compiler too.
=> Add nvcc to exclude constexpress since is it not supported by nvcc

hpx/util/ini.hpp, hpx/util/runtime_configuration.hpp, src/util/runtime_configuration.cpp
The new key is `hpx.component_path`. 
The configuration key with the same name was used before as the base path for component searches and has been renamed to `hpx.component_base_paths`.
This is necessary for Phylanx to allow specifying additional plugin directories.
=> Adding configuration key that allows to explicitly add a directory to the component search path 

CMakeLists.txt
Move the inclusion of `GNUInstallDirs` in the main `CMakeLists.txt` further up to have it available for subdirectories (like APEX).
=> Include GNUInstallDirs earlier to have it available for subdirectories

hpx/runtime/threads/detail/scheduled_thread_pool.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_executors.cpp
Fixes #3612
While this change did not show any significant overall performance improvements for the test applications I ran, I have seen in VTune that the amount of time spent in the scheduling_loop goes down significantly (almost a factor of 100). Therefor I'd suggest to merge this anyhow.
=> Restructuring counter data in scheduler to reduce false sharing

.clang-tidy, .gitlab-ci.yml, .gitlab-ci/cmake.yml, .gitlab-ci/core.yml, .gitlab-ci/docker.yml, .gitlab-ci/docs.yml, .gitlab-ci/inspect.yml, .gitlab-ci/linux/x86/clang-7.0.1/boost-1.65.1/debug.yml, .gitlab-ci/linux/x86/clang-7.0.1/boost-1.65.1/release.yml, .gitlab-ci/stages.yml, .gitlab-ci/test.yml, hpx/config/autolink.hpp, hpx/plugins/binary_filter_factory.hpp, hpx/runtime/threads/coroutines/detail/context_base.hpp, hpx/util/debug/demangle_helper.hpp, hpx/util/memory_chunk.hpp, src/runtime/threads/coroutines/detail/tss.cpp, src/util/register_locks_globally.cpp, tests/unit/threads/tss.cpp
This adds support for gitlab runners and enables a (semi modular) setup to add new configurations. This will allow for a basis to add more PR based tests for more configurations. The whole workflow was slightly changed:
- The tests are split up between unit, regression, performance and examples. Due to the enhanced infrastructure, we don't need to split them anymore
- Checking the code with clang-tidy is enabled by default. A .clang-tidy file has been added for the clang-tidy configuration
- We build both, a debug and release version.
This can be seen as a first step to add more and unified testing using the packet.net infrastructure to our codebase. The tests are run via a gitlab mirror which starts gitlab runners
=> Adding support for gitlab runner

hpx/util/thread_description.hpp, src/util/thread_description.cpp
The order is now:
1) current thread name
2) altname
3) current thread function address
This will correctly annotate the work associated with the new task with the current task description when there is one.  This can still be overridden with annotated_functions.
=> Updating the default order of priority for thread_description

.circleci/config.yml, CMakeLists.txt, cmake/HPX_AddTest.cmake
- Add CMake option `HPX_WITH_TESTS_DEBUG_LOG` which when enabled will add the command line argument `--hpx:debug-hpx-log` to tests. `HPX_WITH_TESTS_DEBUG_LOG_DESTINATION` sets the output destination.
- Enable `HPX_WITH_TESTS_DEBUG_LOG` on CircleCI and store output as artifacts.
- Enable core dumps on CircleCI and store output as artifacts.
Trying to get more information about timeouts and failures in our tests.
=> Store debug logs and core dumps on CircleCI

docs/sphinx/manual.rst, docs/sphinx/manual/building_hpx.rst, docs/sphinx/manual/getting_hpx.rst
- Add instructions on which packages are needed on Debian to build HPX
- Add notes to documentation about distribution packages
- Add "Getting HPX" section to manual
Replaces #3543.
=> Add instructions on getting HPX to documentation

hpx/lcos/future.hpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/shared_future_then_with_executor_3634.cpp
The separate overload for thread executors caused problems since
the implementation of `then` requires a `scheduled_executor` and not
just an `executor`.
The merged overload still does not test if the user-provided executor
does actually satisfy the requirements of a `scheduled_executor`.
Since future<>::then does exhibit the same issue, this should be
fixed in a separate PR.
This commit also adds a regression test demonstrating the issue.
This fixes issue #3634.
=> Merging the executor-enabled overloads of shared_future<>::then

examples/resource_partitioner/shared_priority_queue_scheduler.hpp, examples/resource_partitioner/system_characteristics.hpp, hpx/runtime.hpp, hpx/runtime/applier/applier.hpp, hpx/runtime/runtime_fwd.hpp, hpx/runtime/threads/coroutines/detail/coroutine_self.hpp, hpx/runtime/threads/detail/thread_num_tss.hpp, hpx/runtime/threads/policies/shared_priority_queue_scheduler.hpp, hpx/runtime/threads/thread_pool_base.hpp, hpx/runtime/threads/threadmanager.hpp, hpx/runtime/threads/topology.hpp, hpx/runtime_impl.hpp, hpx/util/register_locks.hpp, src/exception.cpp, src/runtime.cpp, src/runtime/applier/applier.cpp, src/runtime/threads/coroutines/detail/coroutine_self.cpp, src/runtime/threads/detail/thread_num_tss.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/thread_helpers.cpp, src/runtime/threads/thread_pool_base.cpp, src/runtime/threads/topology.cpp, src/runtime_impl.cpp, src/util/register_locks.cpp
`hpx::util::thread_specific_ptr` introduces an extra level of indirection and dynamic memory allocation where none should be needed. `thread_local` could be used instead, this patch is using `HPX_NATIVE_TLS` to allow for some backwards compatibility.
=> Remove thread specific ptr

.circleci/config.yml, .gitlab-ci/cmake.yml, src/runtime/components/server/runtime_support_server.cpp
This PR enables the deadlock detection for our spinlocks and unlocks the lock before throwing an exception during loading of components.
=> Attempt to tackle timeouts during startup

hpx/lcos/future.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/runtime/agas/addressing_service.hpp, hpx/runtime/agas/interface.hpp, hpx/runtime/agas/server/primary_namespace.hpp, hpx/runtime/components/component_type.hpp, hpx/runtime/components/server/component.hpp, hpx/runtime/components/server/wrapper_heap.hpp, hpx/runtime/naming/id_type.hpp, hpx/runtime/naming/id_type_impl.hpp, hpx/runtime/naming/name.hpp, hpx/runtime/threads/policies/thread_queue.hpp, src/performance_counters/server/component_instance_counter.cpp, src/runtime.cpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/interface.cpp, src/runtime/agas/server/primary_namespace_server.cpp, src/runtime/components/component_type.cpp, src/runtime/components/server/wrapper_heap.cpp, src/runtime/naming/name.cpp, src/runtime/parcelset/parcel.cpp, tools/VS/gid_type.natvis
Applying various (mostly minor) optimizations 
- avoid initial reference counting for id_type
- switch more allocations to use internal_allocator (mostly important for Windows)
- avoid memory allocations
- fix problem in AGAS resolve_gid
- avoid decref handling for purely local components
Improving error message 
- listing component types in error message of component type instance counter
=> Various optimizations

CMakeLists.txt, cmake/TargetArch.cmake, hpx/util/hardware/timestamp.hpp
- aligned cmake and code timestamp detection
This improves the error reporting for platforms for which we do not support extracting timestamps.
Fixes #3601
=> Added architecture identification to cmake to be able to detect timestamp support

hpx/lcos/detail/future_data.hpp
Avoid race between `future_data_base::wait` and
`future_data_base::set_value`/`future_data_base::set_exception` which
was observed in `parcelhandler::sync_put_parcel` (see #3656).
=> Fixing race between setting and getting the value inside future_data

hpx/lcos/detail/future_data.hpp, src/lcos/detail/future_data.cpp
Run the completion handlers as static functions.
With this change, completion handlers can not have
exceptions that escape the handler as this would lead
to silently swallow the exceptions.
Previously, this would have triggered a "promise_already_satisfied"
error. This is wrong behavior, exceptions escaping completion
handling should be considered a bug. always.
=> Fixing yet another race in future_data

tests/unit/lcos/async_cb_colocated.cpp, tests/unit/lcos/async_cb_remote.cpp, tests/unit/lcos/async_cb_remote_client.cpp, tests/unit/lcos/async_continue_cb.cpp, tests/unit/lcos/async_continue_cb_colocated.cpp
The callback is called after the value in the shared state
has been set. As such, the callback might not have been called
directly after `future::get` returns. Adding a small grace period
should mitigate that problem.
=> Unbreaking async_*cb* tests

.clang-tidy, hpx/exception_fwd.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/lcos/local/recursive_mutex.hpp, hpx/parallel/executors/execution_parameters.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/queue_helpers.hpp, src/hpx_init.cpp, src/runtime/agas/addressing_service.cpp, src/util/runtime_configuration.cpp, tests/performance/parallel_algorithms/local/benchmark_remove_if.cpp, tests/unit/parallel/algorithms/sort_tests.hpp, tests/unit/serialization/serialization_list.cpp, tests/unit/util/any.cpp, tests/unit/util/iterator/iterator_facade.cpp
This PR makes sure that the code is properly checked with the below enabled checks:
- All of bugprone except:
- bugprone-assert-side-effect
- bugprone-exception-escape
- bugprone-forward-declaration-namespace
- bugprone-macro-parentheses
- Removing removed tests
This PR includes the fixes that appeared.
=> making clang-tidy work properly again

CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx11_alignas.cpp, cmake/tests/cxx17_hardware_destructive_interference_size.cpp, hpx/lcos/local/spinlock.hpp, hpx/lcos/local/spinlock_pool.hpp, hpx/runtime/naming/name.hpp, hpx/runtime/threads/topology.hpp, hpx/util/fibhash.hpp, hpx/util/spinlock_pool.hpp, hpx/util/yield_while.hpp
This patch introduces a multiplicative hashing algorithm for the spinlock pools to avoid modulo operations in the critical paths.
This, together with #3498 shows up to 10% performance increase on the Phylanx simple loop benchmark: https://docs.google.com/spreadsheets/d/15aNdbbyrWg3L56kY5Ud56sflX3Iy3tqbOC5dBaDijsc/edit#gid=0
=> Improving spinlock pools

hpx/util/bind.hpp, hpx/util/bind_action.hpp, hpx/util/bind_back.hpp, hpx/util/bind_front.hpp, hpx/util/deferred_call.hpp, hpx/util/detail/vtable/callable_vtable.hpp, hpx/util/invoke.hpp, hpx/util/invoke_fused.hpp, hpx/util/one_shot.hpp
Reduce the number of function calls necessary to invoke the target callable in the functional utilities.
This PR relays on reverting the workaround introduced in #2404, and instead fixes the underlying bug that is believed to have caused the original issue (for which there is no report and no tests).
Each "flatten" commit removes one frame from the call stack. Most changes result in code simplification, but two commits (titled "flatten ... some more") result in more complex code in order to embed index sequences into the wrappers.
=> Reduce functional utilities call depth

tests/regressions/parallel/set_operations_3442.cpp
=> Remove thousands separators in set_operations_3442 to comply with C++11

hpx/runtime/threads/detail/set_thread_state.hpp, src/runtime/threads/threadmanager.cpp, tests/unit/threads/thread.cpp
- Handles `pending` and `pending_boost` states correctly in `set_thread_state`. When going from `pending` to `pending_boost` or vice versa the thread should not be scheduled again. This would sometimes cause this assert to fire: https://github.com/STEllAR-GROUP/hpx/blob/0c77050a7d402b771850ab876fff08daec37f9db/hpx/runtime/threads/policies/thread_queue.hpp#L495
- Ignore registered locks while calling `interruption_point` in `thread` test
- Flyby: fix check for valid states in `get_thread_state_name`
=> Fix a couple of test failures

hpx/components/component_storage/server/migrate_from_storage.hpp, hpx/components/component_storage/server/migrate_to_storage.hpp, hpx/error.hpp, hpx/runtime/agas/addressing_service.hpp, hpx/runtime/agas/interface.hpp, hpx/runtime/agas/primary_namespace.hpp, hpx/runtime/agas/server/primary_namespace.hpp, hpx/runtime/components/server/migrate_component.hpp, hpx/runtime/components/server/migration_support.hpp, src/runtime/agas/addressing_service.cpp, src/runtime/agas/interface.cpp, src/runtime/agas/primary_namespace.cpp, src/runtime/agas/server/primary_namespace_server.cpp, src/runtime/agas/server/route.cpp, tests/unit/component/migrate_component.cpp
Fixes the migration test that is failing intermittently.
This PR fixes several issues with component migration:
- one of the continuations involved was attached to the outer future of a `future<future<id_type>>` instead of the inner one
- in case of exceptions the interrupted migration operation is now cleaned up properly
- the migration operation is now (silently) retried if a global race is detected (see commit message below for an explanation)
=> Fixing component migration

.circleci/config.yml
This makes sure that build unit tests are run after installing HPX and that they would fail if HPX has not been installed.
Note that this contains a redundant `ninja install` because of the way workspaces are handled on CircleCI.
=> Make sure tests.unit.build are run after install on CircleCI

hpx/config/constexpr.hpp
Trying to fix some of the compilation errors occuring with nvcc+gcc. The combo nvcc++gcc *does* support constexpr so only disable it if using clang-cuda.
=> Only disable constexpr with clang-cuda, not nvcc+gcc

CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/tests/cxx11_thread_local.cpp
Attempt to fix [these](http://rostam.cct.lsu.edu/builders/hpx_clang_3_9_boost_1_62_centos_x86_64_release/builds/214/steps/build_core/logs/stdio) errors occuring with clang < 4.
=> Link with libsupc++ if needed for thread_local

hpx/runtime/threads/detail/set_thread_state.hpp
Trying to get more context for [this](https://circleci.com/gh/STEllAR-GROUP/hpx/64031?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification) failure.
=> Print thread state when getting disallowed value in set_thread_state

docs/sphinx/manual/building_hpx.rst
OpenMPI's `--enable-heterogeneous` build flag is considered deprecated and broken according to OpenMPI:s README and is documented to cause problems on Ubuntu's and debian's bug trackers:
https://bugs.launchpad.net/ubuntu/+source/openmpi/+bug/1731938
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886336
https://github.com/open-mpi/ompi/issues/171
This PR adds a documentation note to warn about this mentioning distributions which build with this flag.
Feedback on wording very welcome.
=> Document known broken OpenMPI builds

src/util/command_line_handling.cpp, src/util/runtime_configuration.cpp
=> Adding support for passing command line options through the HPX_COMMANDLINE_OPTIONS environment variable

hpx/util/detail/basic_function.hpp, hpx/util/detail/vtable/serializable_function_vtable.hpp, hpx/util/detail/vtable/vtable.hpp, hpx/util/function.hpp, hpx/util/unique_function.hpp, tests/unit/parcelset/set_parcel_write_handler.cpp
Separating the serialization logic from the function vtables allows:
- making function vtable instances constexpr objects,
- reusing function instantiations for serializable/non-serializable versions,
- various function simplifications (2+1 vtables vs 2*2 vtables),
...at the cost of an extra vtable pointer for the serializable functions.
=> Decouple serialization from function vtables

hpx/components/iostreams/ostream.hpp
- This forces to empty all data buffered server side
=> Send even empty buffers on hpx::endl and hpx::flush

examples/quickstart/CMakeLists.txt, examples/quickstart/component_with_custom_heap.cpp, hpx/include/traits.hpp, hpx/runtime/components/new.hpp, hpx/runtime/components/server/component.hpp, hpx/traits/component_heap_type.hpp, src/runtime/components/server/component_base.cpp, tests/unit/component/local_new.cpp
- adding traits::component_heap_type
- flyby: adding `local_new(launch::sync, ...)
- flyby: don't bind gids that hold lva
=> Adding example demonstrating how to customize the memory management for a component

hpx/util/bind.hpp, hpx/util/bind_back.hpp, hpx/util/bind_front.hpp, hpx/util/deferred_call.hpp, hpx/util/one_shot.hpp
Workaround for old libstdc++ single element `std::tuple` bug.
Fixes #3731
=> More constrained bound constructors

hpx/components/iostreams/server/output_stream.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, src/components/iostreams/server/output_stream.cpp, src/runtime/threads/threadmanager.cpp, src/runtime_impl.cpp, src/util/io_service_pool.cpp
During shutdown, the lifetime of the different components needs to be taken care of in specific orders. This PR takes care of correct lifetime for the iostream components, the io_service pool, and the timer pool.
=> Fix potential shutdown problems

tests/unit/parallel/segmented_algorithms/partitioned_vector_adjacent_difference1.cpp, tests/unit/parallel/segmented_algorithms/partitioned_vector_adjacent_difference2.cpp, tests/unit/parallel/segmented_algorithms/partitioned_vector_adjacent_find1.cpp, tests/unit/parallel/segmented_algorithms/partitioned_vector_adjacent_find2.cpp
Fixes these errors in partitioned vector tests with clang:
```
{compiler}: Clang version 3.8.1 (http://llvm.org/git/clang.git 07a6361e0f32f699d47c124106e7911b584974d4) (http://llvm.org/git/llvm.git 051e787f26dbfdc26cf61a57bc82ca00dcb812e8)
{stdlib}: libc++ version 3800
{what}: Unknown typename: N3hpx6server18partitioned_vectorIiNSt3__16vectorIiNS2_9allocatorIiEEEEE16get_value_actionE
: HPX(serialization_error)
terminating with uncaught exception of type hpx::detail::exception_with_info<hpx::exception>: Unknown typename: N3hpx6server18partitioned_vectorIiNSt3__16vectorIiNS2_9allocatorIiEEEEE16get_value_actionE
: HPX(serialization_error)
```
=> Fix includes in partitioned vector tests

examples/quickstart/component_with_custom_heap.cpp, examples/quickstart/potpourri.cpp, hpx/components/iostreams/server/buffer.hpp, hpx/components/iostreams/server/order_output.hpp
This is in addition to #3728 as we have missed some spots there.
=> More fixes to make sure that std::flush really flushes all output

CMakeLists.txt
Fixes #3746 (Detection of MPI with pmix)
=> Added PMIX_RANK to the defaults of HPX_WITH_PARCELPORT_MPI_ENV.

hpx/runtime/threads/run_as_hpx_thread.hpp
Fixes a problem in `run_as_hpx_thread` where the condition variable could be accessed after going out of scope.
=> Fix lifetime problem in run_as_hpx_thread

hpx/components/iostreams/ostream.hpp, hpx/lcos/detail/barrier_node.hpp, src/components/iostreams/standard_streams.cpp, src/lcos/barrier.cpp, src/lcos/detail/barrier_node.cpp
- Fixing memory leak with hpx::cout and friends during shutdown
- Fixing potential memory corruption with lcos barrier
=> Fixing problems with lcos::barrier and iostreams

src/runtime/parcelset/parcelhandler.cpp
Fixes https://github.com/STEllAR-GROUP/phylanx/issues/892
- this disables more startup code that does not need to run if networking is disabled or not available
=> Disable more code if networking is not available/not enabled

hpx/util/detail/empty_function.hpp, hpx/util/detail/vtable/callable_vtable.hpp
Workaround for GCC regression when forming function pointers to [[noreturn]] functions in constant expressions
=> Fix callable vtable for GCC4.9

examples/quickstart/component_with_custom_heap.cpp
`PAGE_SIZE` is a macro in Apple Clang.
- Rename the `PAGE_SIZE` constant in `examples/quickstart/component_with_custom_heap.cpp` to `PAGE_SIZE_`.
```
...
CompileC cmake-build-debug/examples/quickstart/HPX.build/Debug/component_with_custom_heap.build/Objects-normal/x86_64/component_with_custom_heap.o examples/quickstart/component_with_custom_heap.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
cd /Users/parsa/Repositories/hpx
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=204 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor …
```
=> Rename PAGE_SIZE to PAGE_SIZE_ because AppleClang

hpx/util/function.hpp, hpx/util/iterator_adaptor.hpp, hpx/util/transform_iterator.hpp, hpx/util/unique_function.hpp
- this touches on `util::function`, `util::unique_function`, and `util::iterator_adaptor`
- splitting SFINAE on `util::function` and friends to prevent MSVC to over-eagerly instantiate non-needed functions
- adding SFINAE to `util::iterator_adaptor` members to achieve similar effects
=> Prevent MSVC from prematurely instantiating things

hpx/lcos/detail/future_data.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/detail/set_thread_state.hpp, hpx/runtime/threads/thread_helpers.hpp, src/lcos/local/detail/condition_variable.cpp, src/runtime/threads/executors/current_executor.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/thread_helpers.cpp, src/util/interval_timer.cpp, tests/unit/threads/thread.cpp
- Add option to not retry setting state when target thread is active
- Don't retry setting state when interrupting a thread
- Remove some barriers from parts of the thread test to avoid rare hang
More details in commit messages.
=> Fix a couple of bugs in the thread test

hpx/runtime/threads/coroutines/detail/context_base.hpp, hpx/runtime/threads/coroutines/detail/context_generic_context.hpp, hpx/runtime/threads/coroutines/detail/context_impl.hpp, hpx/runtime/threads/coroutines/detail/context_linux_x86.hpp, hpx/runtime/threads/coroutines/detail/context_posix.hpp, hpx/runtime/threads/coroutines/detail/context_windows_fibers.hpp, hpx/runtime/threads/coroutines/detail/coroutine_impl.hpp, src/runtime/threads/coroutines/detail/context_base.cpp
This changes the context implementations to perform a lazy initialization
of their respective contexts. This potentially leads to less resource usage.
=> Changing the coroutine implementations to do a lazy init

.circleci/config.yml
- Create a Git tag named `stable` that refers to the most recent commit in the master branch that passed all CircleCI tests.
=> Tag and push stable builds

hpx/runtime/threads/executors/limiting_executor.hpp, tests/performance/local/future_overhead.cpp
This adds an executor that counts tasks and can be used to limit the number that go into the queues at any given time - and also to wait on them so that it is not necessary to wait on a vector of futures. It is similar to the aggregating executor and the recent changes to parallel algorithms to use a latch.
This executor can be used to replace sliding_semaphore and provides a much simpler and cleaner way of doing it.
=> Limiting executor

.circleci/config.yml
`ninja` defaults to parallel builds `-j` isn't specified. This sets it explicitly on all invocations on CircleCI. In particular, it sets it to `1` for the docs build. This is most likely why the docs build has been failing on master.
=> Explicitly set number of jobs for all ninja invocations on CircleCI

hpx/runtime/serialization/access.hpp, tests/unit/serialization/CMakeLists.txt, tests/unit/serialization/serialization_brace_initializable.cpp
- this is necessary as some compilers claim to support constexpr if but
eventually refuse to compile our code
- flyby: guard brace initialization serialization test with the correct pp constant
Fixes https://github.com/STEllAR-GROUP/phylanx/issues/915
=> Replacing constexpr if in brace-serialization code

tests/unit/component/migrate_polymorphic_component.cpp
Adding tests so that polymorphic component migration supports the features tested for component migration in `tests/unit/component/migrate_component.cpp`
This extends the unit tests added in #3773.
=> Extending migrate_polymorphic_component unit test

hpx/lcos/barrier.hpp, src/lcos/barrier.cpp, tests/regressions/lcos/CMakeLists.txt, tests/regressions/lcos/barrier_3792.cpp
This fixes the problems reported in #3792. The main issue lies within an
implementation detail of the barrier. The rank of a barrier is
completely decoupled from the locality id. For that reason, the barrier
root is always rank 0. If no barrier with rank 0 is given, we get the
reported hang. The added test shows both a workaround to that issue and
adds an additional barrier constructor that takes a vector of ranks, and
the rank of the given barrier instantiation.
=> Fixing #3792

CMakeLists.txt, cmake/HPX_SetupBoost.cmake, cmake/HPX_SetupBoostSIMD.cmake, docs/sphinx/manual/building_hpx.rst, docs/sphinx/manual/optimizing_hpx_applications.rst, examples/resource_partitioner/CMakeLists.txt, examples/resource_partitioner/async_customization.cpp, hpx/config.hpp, hpx/lcos/detail/future_data.hpp, hpx/runtime/threads/coroutines/detail/context_generic_context.hpp
Bump minimum Boost version to 1.61 and GCC to 5.
=> Bump minimum required versions for 1.3.0 release

hpx/runtime/threads/coroutines/detail/context_posix.hpp
Blind edit of the POSIX context switching, fixing it after lazy init changes
=> Attempt to fix Posix context switching after lazy init changes

cmake/HPX_CreateSymbolicLink.cmake, cmake/scripts/create_symbolic_link_directory.bat, cmake/scripts/create_symbolic_link_file.bat
This makes sure symlinks to files are properly created on Windows
- this also enables deleting linked directories using 'cmake -E remove_directory ...' (which failed before)
=> Windows requires to handle symlinks to directories differently from those linking files

tests/regressions/lcos/CMakeLists.txt
The test doesn't make much sense with only one locality (and it hangs) so we disable it.
=> Disable barrier_3792 test when networking is disabled

src/hpx_wrap.cpp
Including `hpx/hpx.hpp` pulls in unnecessary dependencies.
=> Change includes in hpx_wrap.cpp to more specific includes

cmake/templates/conf.py.in, docs/CMakeLists.txt, docs/sphinx/api.rst, docs/sphinx/contributing/documentation.rst, docs/sphinx/examples/hello_world.rst, docs/sphinx/manual/building_hpx.rst, libs/README.rst, libs/_example/docs/index.rst, libs/all_modules.rst, libs/create_library_skeleton.py, libs/overview.rst, libs/preprocessor/docs/index.rst
- Make sure API docs show up for modules
- Fix links to `HPX_PP_X` macro docs
- Slightly restructure modules documentation
- Add headings to API reference
- Move list of all modules to subsection
- Minor formatting and link fixes in docs
=> Fix and update modules documentation

hpx/runtime/get_ptr.hpp, hpx/runtime/naming/name.hpp, src/runtime/naming/name.cpp
- flyby: making many naming functions noexcept
This is an optimization that avoids a) going through AGAS and b) creating a future for the purely local application of `get_ptr<>`
=> Adding shortcut for hpx::get_ptr<>(sync, id) for a local, non-migratable objects

src/CMakeLists.txt
Currently we propagate link dependencies on the HPX module to any binary that depends on HPX. This is not necessary and not desirable. External binaries should depend on the HPX core binaries (libhpx and friends) only. At the same time however, external modules need to be able to find the header files of the modules as those might be indirectly included through HPX API headers. Thus the the corresponding include directories must be exported publicly.
=> Avoid for binaries that depend on HPX to directly link against internal modules

libs/_example/tests/CMakeLists.txt, libs/create_library_skeleton.py, libs/preprocessor/tests/CMakeLists.txt
CMake option HPX_WITH_TEST now disables all specialized test
=> minor fix: option HPX_WITH_TEST was not working correctly

.circleci/config.yml, CMakeLists.txt, libs/create_library_skeleton.py, libs/preprocessor/CMakeLists.txt, src/CMakeLists.txt
Add libs tests to CircleCI config.
Flyby: use `hpx_option` for all options in modules.
=> Fix CircleCI config for modules

.circleci/config.yml
This call to hwloc: https://github.com/STEllAR-GROUP/hpx/blob/8a8cec8dee6f0dc12200c124b6cb3bf43264bc27/src/runtime/threads/topology.cpp#L522-L528 returns `-1` and sets `errno = EPERM` (i.e. permission denied) on CircleCI. My guess is that this hasn't come up before because of recent changes to exception handling (#3662, #3814), or CircleCI launching containers differently. Since we have pycicle running as well without containers I think we can safely disable the example on CircleCI.
=> Disable transpose_block_numa example on CircleCI

hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp
=> Fixing misplaced #endif

hpx/lcos/local/latch.hpp
make all latch members protected for consistency
=> make all latch members protected for consistency

tests/unit/component/launched_process.cpp
- we have to make sure networking stays enabled for both parts of the test
=> This fixes the launch_process/launched_process pair of tests

docs/sphinx/quickstart.rst
=> Correct BOOST_ROOT variable name in quick start guide

.circleci/config.yml, CMakeLists.txt, examples/transpose/transpose_block_numa.cpp, hpx/parallel/util/numa_binding_allocator.hpp, hpx/runtime/threads/topology.hpp, src/runtime/threads/topology.cpp, tests/unit/CMakeLists.txt, tests/unit/topology/CMakeLists.txt, tests/unit/topology/allocator_binder_linear.hpp, tests/unit/topology/allocator_binder_matrix.hpp, tests/unit/topology/numa_allocator.cpp
This introduces a numa_allocator that can provide memory with interleaved/first touch or user defined numa binding per page of memory.
The allocator uses a 'binder' object that defines the way pages are bound and users can supply their own binders. A 1D and 2D example (unit test) are provided that mimic the way we bind memory in our matrix allocation
=> Numa binding allocator

cmake/HPX_AddCompileTest.cmake
Previously only build targets were created, but no tests. This adds the tests.
=> Add tests for libs header tests

tests/unit/lcos/local_dataflow_boost_small_vector.cpp
"Fixes" #3808. This sets the allocator explicitly in the test to avoid problems with dataflow not knowing what to do with a `void` allocator.
@hkaiser I'd be happy with this as a solution for the release to not have to rush in a proper fix.
I'm also tempted to say that this isn't even our problem since standard containers don't support `void` as an allocator either, but you're a better judge than I am of how bad this is and what we can reasonably do to support it.
=> Temporary fix to local_dataflow_boost_small_vector test

hpx/parallel/util/numa_binding_allocator.hpp, hpx/runtime/resource/detail/partitioner.hpp, hpx/runtime/resource/partitioner.hpp, src/runtime/resource/detail/detail_partitioner.cpp, src/runtime/resource/partitioner.cpp
This is a commit that was left off the original branch but is useful for other tests
Adds methods to query number of threads user requested on start (useful when creating custom pools and deciding how many to put in each), a utility function to access the topology from the RP.
Also adds a cast function to the allocator to convert the binder to a user type.
If this could go into the next release, it would be very useful.
=> Helper functions that are useful in numa binding and testing of allocator

hpx/include/serialization.hpp, hpx/runtime/actions/action_support.hpp, hpx/runtime/actions/basic_action.hpp, hpx/runtime/serialization/tuple.hpp, hpx/util/tuple.hpp, src/hpx_init.cpp
Remove the serialization implementation from the `tuple(_impl)` class so that the serialization functionality can be stored in a separate file. This lets parts of HPX that need `tuple` *not* depend on serialization (and transitively naming, AGAS details, etc.).
=> Make tuple serialization non-intrusive

cmake/HPX_UpdateGitDocs.cmake
Fixes #3867.
I've manually fixed the location of the docs for 1.3.0, so any previously broken links should also be fixed.
=> Fix latest HTML docs location

docs/sphinx/contributing/release_procedure.rst, tools/generate_issue_pr_list.sh, tools/roll_release.sh
Remove package generation from `tools/roll_release.sh`, and instead tag and create a release on GitHub with the `hub` tool. Also add a script to generate PR and issue lists using `hub`.
Not fully tested in real life for obvious reasons, but I'll amend these as needed when it's time for the next release.
=> Add scripts to create releases and generate lists of PRs and issues

cmake/templates/config_version.hpp.in, libs/cache/CMakeLists.txt, libs/config/CMakeLists.txt, libs/config/include/hpx/config/export_definitions.hpp, libs/config/src/version.cpp, libs/preprocessor/CMakeLists.txt
- flyby: removed definition of symbols from config module as those are part of the main library
- flyby: made COMPILE_DEFINITIONS in modules PRIVATE
@msimberg, @aurianer please note the addition of the `HPX_MODULE_EXPORTS` compile definition. I believe we should add that to all of our modules. Also, once modules start actually implementing things we'll have to come up with a way to force linking of the symbols that are implemented in a module to the main library.
=> Making sure symbols are properly exported from modules (needed for Windows/MacOS)

CMakeLists.txt
Updating APEX version tag to match current HPX build dependency requirements
Fixes errors building with APEX
- update APEX version to v2.1.4
=> Updating APEX version tag

cmake/templates/config_defines.hpp.in
That was overlooked during introducing the config module.
Fixes compilations with intel 2019 update 4
=> Removal of the default intel config include

docs/sphinx/manual/optimizing_hpx_applications.rst, hpx/runtime/parcelset/parcelhandler.hpp, hpx/runtime/parcelset/parcelport.hpp, hpx/runtime/parcelset/parcelport_impl.hpp, hpx/runtime/parcelset_fwd.hpp, hpx/runtime/threads/detail/scheduled_thread_pool.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/policies/scheduler_base.hpp, hpx/runtime/threads/scoped_background_timer.hpp, hpx/runtime/threads/thread_pool_base.hpp, hpx/runtime/threads/threadmanager.hpp, plugins/parcelport/libfabric/parcelport_libfabric.cpp, plugins/parcelport/libfabric/parcelport_libfabric.hpp, plugins/parcelport/mpi/parcelport_mpi.cpp, plugins/parcelport/verbs/parcelport_verbs.cpp, src/runtime.cpp, src/runtime/parcelset/parcelhandler.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_executors.cpp, src/runtime/threads/policies/scheduler_base.cpp, src/runtime/threads/threadmanager.cpp, src/runtime_impl.cpp, tests/performance/network/network_storage/network_storage.cpp
- `/threads/time/background-send-duration`, `/threads/time/background-receive-duration`
- `/threads/time/background-send-overhead`, `/threads/time/background-receive-overhead`
These counters currently return meaningful values for the MPI parcelport only
@justwagle please verify whether the new counters provide you with the information you need
=> Adding new performance counters

.gitignore
Ignore cache directory produced by [ccls](https://github.com/MaskRay/ccls).
=> Add ccls cache directory to gitignore

CMakeLists.txt, cmake/GitExternal.cmake
Fixes handling of tags for APEX and hpxMP. The old behaviour was to incorrectly do a `git rebase FETCH_HEAD` after checking out a tag, which would always end up on the latest `develop` commit. This PR skips the rebase if `HPX_WITH_X_TAG` is not a branch (with the assumption that tags never change).
@khuck I noticed that you've already had to fix this in APEX (you're using the same `GitExternal.cmake` script). Not sure how general my solution is but you might want to have a look at it.
=> Fix git_external fetching of tags

hpx/traits/pack_traversal_rebind_container.hpp, hpx/util/detail/pack_traversal_impl.hpp, tests/unit/lcos/local_dataflow_boost_small_vector.cpp
This removes the dependency of the unwrapping code on boost::small_vector
Fixes #3871
=> Factoring out container remapping into a separate trait

examples/resource_partitioner/async_customization.cpp, hpx/runtime/threads/executors/guided_pool_executor.hpp, plugins/parcelport/libfabric/parcelport_libfabric.cpp
This is a minor cleanup of the async_customization example that was incorrect when the guided_executor was fixed.
=> Fix async_customization dataflow example and Clarify what's being tested

cmake/templates/modules.cpp.in, libs/CMakeLists.txt, libs/cache/CMakeLists.txt, libs/cache/include/hpx/cache/force_linking.hpp, libs/cache/tests/unit/local_mru_cache.cpp, libs/cache/tests/unit/local_statistics.cpp, libs/config/CMakeLists.txt, libs/config/include/hpx/config/force_linking.hpp, libs/config/src/version.cpp, libs/preprocessor/CMakeLists.txt, libs/preprocessor/include/hpx/preprocessor/force_linking.hpp, libs/preprocessor/src/preprocessor.cpp, src/CMakeLists.txt, src/version.cpp, tests/performance/local/agas_cache_timings.cpp
Move version check definitions to config module. They should've been defined there in the first place (instead of duplicated in the core library and config). Moving this to the config library means that using modules also have the version check. Should also fix the linker errors in the assertion PR.
Flyby: use non-compatibility headers from the cache module.
=> Move version check to config module

CTestConfig.cmake
Required after CDash upgrade. Fixes missing submissions on dashboard.
=> Use https for CDash submissions

hpx/util/batch_environments/slurm_environment.hpp, src/util/batch_environments/slurm_environment.cpp, tests/unit/util/parse_slurm_environment.cpp
Fixed for heterogeneous slurm environments
- number of tasks determination
- number of threads determination
Added test to show the slurm environment with its variables.
Changed the behavior with hyperthreading. Before it was determined by hpx::topology, now it depends on the slurm argument --threads-per-core, which is intended for this purpose, according to the approach `2019-03-18 14:23 <hkaiser> mdiers_: all depends on the environment`.
Some more informations about it: http://irclog.cct.lsu.edu/ste~b~~b~ar/2019-03-18
=> fixed number of tasks and number of threads for heterogeneous slurm environments

cmake/templates/HPXMacros.cmake.in
Fixes #3935
Disable the strict compiler check when we build HPX as the distribution packages.
- We also use the option `HPX_WITH_BUILD_BINARY_PACKAGE` to disable certain features for building distribution packages. So we can reuse this option here.
On the Fedora build system, not all packages are recompiled if there is a minor update of the compiler. So we should disable the strict compiler check to not scare new users playing around with HPX.
=> Add HPX_WITH_BUILD_BINARY_PACKAGE to the compiler check (refs #3935)

tests/unit/lcos/CMakeLists.txt, tests/unit/lcos/broadcast_component.cpp
As per request on hpx-users (https://www.mail-archive.com/hpx-users@stellar.cct.lsu.edu/msg01134.html)
=> Add test demonstrating the use of broadcast with component actions

cmake/HPX_AddComponent.cmake, cmake/HPX_AddLibrary.cmake, cmake/HPX_SetupTarget.cmake
- on windows, all executable code must go into CMAKE_INSTALL_BINDIR
=> Fixing installation of binaries on windows

src/util/batch_environment.cpp
The number of localities wasn't set properly to run distributed
applications properly
=> Fixing ALPS environment

cmake/HPX_AddModule.cmake
- Move the generated headers into the `CMAKE_CURRENT_BIN_DIR`.
- Install those headers (including config/defines.hpp).
- Remove the duplicated `write_config_defines_file`.
=> [Modules] Move the location of the generated headers

.github/stale.yml
- The time frames currently set will consider a PR as stale after 180 and will
close it after another month.
Marking issues with 'tag: pinned' keeps them open. If we decided to go for this we should first mark all issues that shouldn't be closed.
=> This adds a configuration file that will cause for stale issues to be automatically closed

.circleci/config.yml, libs/cache/examples/CMakeLists.txt, libs/collectives/examples/CMakeLists.txt, libs/config/examples/CMakeLists.txt, libs/create_library_skeleton.py
Fixes #3953.
Also adds a few CircleCI steps which simply configure HPX with different combinations of options. For now only:
- tests on, examples off
- tests off, examples on
- apex on (and tests on, examples on)
If someone can think of other combinations that we've had troubles with I'll happily add them.
=> Fix CMake configuration with examples off and tests on

libs/collectives/CMakeLists.txt, libs/collectives/include/hpx/collectives/all_reduce.hpp, libs/collectives/include/hpx/collectives/all_to_all.hpp, libs/collectives/tests/unit/CMakeLists.txt, libs/collectives/tests/unit/all_reduce.cpp
- flyby: minor fixes to all_to_all
=> Adding all_reduce facility to collectives module

libs/collectives/include/hpx/collectives/all_reduce.hpp, libs/collectives/include/hpx/collectives/all_to_all.hpp
The headers in the collectives module where added concurrently to the assertion module, thus where missed while fixing the related #include changes.
=> Fixing merge problems

libs/assertion/include/hpx/assertion/current_function.hpp
void constexpr functions not supported in C++11 (https://cdash.cscs.ch/viewBuildError.php?buildid=59491).
=> Change current_function_helper back to non-constexpr

CMakeLists.txt, src/CMakeLists.txt
Forgot to remove this from the assertion PR after it was added as a per-target option (for modules).
=> Remove leftover PIC settings from main CMakeLists.txt

hpx/lcos/local/detail/sliding_semaphore.hpp, hpx/lcos/local/sliding_semaphore.hpp
This allows the semaphore distance to be adjusted after initial use.
Largely obsolete now, due to the limiting_executor, but I have some code still using this.
=> Add set function for sliding_semaphore max_difference 

hpx/parallel/exception_list.hpp, hpx/parallel/executors/sequenced_executor.hpp, tests/regressions/parallel/scan_different_inits.cpp, tests/unit/lcos/condition_variable.cpp, tests/unit/util/iterator/iterator_tests.hpp
Fixes compilation warnings issued by GCC 9.
- Warnings about redundant moves
- Warnings about implicitly created copy constructors
- Clash with (parallel) standard library exclusive_scan overloads
=> Fix compilation with GCC 9

cmake/HPX_AddComponent.cmake, components/component_storage/CMakeLists.txt, components/containers/partitioned_vector/CMakeLists.txt, components/containers/unordered/CMakeLists.txt, components/iostreams/CMakeLists.txt, components/performance_counters/io/CMakeLists.txt, components/performance_counters/memory/CMakeLists.txt, components/performance_counters/papi/CMakeLists.txt, components/process/CMakeLists.txt
Add option to explicitly prepend the root path to source and header files. Otherwise leave paths as they are (old behaviour).
@hkaiser does this work for phylanx?
=> Fix default behaviour of paths in add_hpx_component

components/performance_counters/papi/CMakeLists.txt, components/performance_counters/papi/tests/regressions/CMakeLists.txt, tests/regressions/performance_counters/CMakeLists.txt
Fixes master. I broke configuration with PAPI turned on with #3954. This attempts to fix it. There's a build running on rostam here: http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_64_centos_x86_64_debug/builds/373.
=> Fix CMake configuration with PAPI on

CMakeLists.txt
Allow compilation with an existing apex directory outside of the hpx source directory. Need to specify a cmake APEX_ROOT option to point at this folder, if not specified, the normal clone is done.
Easier to work on several modules, I'll have one apex worktree per module, so that I don't have to change the headers and dependencies every time I switch between them.
=> Add condition to clone apex + use of new cmake var APEX_ROOT

libs/logging/CMakeLists.txt
This makes sure that external modules can still use the old logging module headers
=> Enable support for compatibility headers for logging module

libs/assertion/include/hpx/assertion/evaluate_assert.hpp, libs/assertion/include/hpx/assertion/force_linking.hpp, libs/assertion/src/assertion.cpp
Fixes GCC release builds. The function was not declared exported inside the assertion module, only for consumers of the module.
[Before](http://rostam.cct.lsu.edu/builders/hpx_gcc_8_boost_1_70_centos_x86_64_release/builds/85) and [after](http://rostam.cct.lsu.edu/builders/hpx_gcc_8_boost_1_70_centos_x86_64_release/builds/86).
=> Export handle_assert function

.circleci/config.yml, tests/unit/resource/shutdown_suspended_pus.cpp, tests/unit/resource/suspend_runtime.cpp
Explicitly sets the timeout to 60 seconds (I *think* it's enough, let's see...) on CircleCI instead of waiting for the 10 minute timeout that CircleCI has by default.
=> Shorten CTest timeout on CircleCI

hpx/lcos/gather.hpp, hpx/runtime/actions/component_action.hpp, hpx/runtime/components/server/migrate_component.hpp, tests/unit/component/migrate_component.cpp
- flyby: properly unmark as migrated component that do not need to be migrated as target locality is the same as current locality
- flyby: adding missing functions to `gather_here`/`gather_there`
@parsa this should fix the hang in your application, please re-check
=> Fixing migration for components that have actions returning a client

hpx/runtime/threads/policies/lockfree_queue_backends.hpp, hpx/runtime/threads/policies/shared_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/thread_queue_mc.hpp, hpx/util/lockfree/concurrentqueue.hpp
This PR replaces some of our usage of boost::lockfree fifo queue with an alternative lockfree queue from MoodyCamel. Please see the commit log for extra info.
Improvements come in two places. 1) we get better performance with our task queues as this queue outperforms the boost one. Particularly on higher thread count numbers. 2) The removal of an alloc/dealloc in the task description queue reduces work in jemalloc/other allocators which can hit posix locks when they are maxxed out (particularly noticable in the future_overhead test for example).
I would like to have approval from @cameron314 that the inclusion of the boost license in the concurrentqueue.h file is in accordance with his terms and conditions.
=> MoodyCamel lockfree

hpx/compute/cuda/allocator.hpp, hpx/util/detail/basic_function.hpp, hpx/util/detail/empty_function.hpp, libs/config/include/hpx/config/compiler_specific.hpp, tests/unit/computeapi/host/CMakeLists.txt, tests/unit/computeapi/host/block_allocator.cpp
Fixes CUDA compilation.
1. `function_base` constructor was `constexpr` which `nvcc` didn't like. This was causing the `there was an error in verifying the lgenfe output!` errors. I couldn't figure out if this is a known bug or not. @K-ballo was the `constexpr` critical for performance?
2. `construct`/`bulk_construct`/`bulk_destroy` didn't instantiate `detail::launch` in device code which meant that kernel launches would fail.
=> Fix CUDA compilation

.circleci/config.yml
Check for circular `#include` dependencies for the modules, the `cpp-dependencies` being installed in the Dockerfile from STE||AR-GROUP/docker_build_env
=> Check circular dependencies in a circle ci step

docs/sphinx/manual/launching_and_configuring_hpx_applications.rst, hpx/runtime/threads/policies/affinity_data.hpp, hpx/runtime/threads/policies/parse_affinity_options.hpp, hpx/runtime/threads/topology.hpp, hpx/util/command_line_handling.hpp, src/runtime/threads/policies/affinity_data.cpp, src/runtime/threads/policies/parse_affinity_options.cpp, src/util/command_line_handling.cpp, src/util/parse_command_line.cpp
Adds a new thread binding option `--hpx:bind=process` which looks at the CPU mask of the process to choose which PUs to use for worker threads. If threads is `"cores"` (default) or `"all"` it overrides the number of threads to the number of PUs in the CPU mask, and if an explicit number has been set it uses that.
This is useful for making thread bindings consistent with the behaviour of other applications in batch environments. If this works well it could even replace the batch environment support we have (assuming all of them use mpi).
=> Add process thread binding option

hpx/runtime/threads/policies/thread_queue_mc.hpp
Fixes warnings (and errors on CircleCI) from using the old deprecated headers from the errors module.
=> Update deprecated header in thread_queue_mc.hpp

tests/performance/local/future_overhead.cpp
Some improvements to the future overheads benchmark. Main one is using a parallel for loop to launch futures instead of a serial one - this allows multiple threads to inject tasks and provides a better load balance across cores - this significantly improves the overall timing of all schedulers.
=> Future overheads

hpx/runtime/threads/topology.hpp, hpx/util/cache_aligned_data.hpp
Correctly sets the padding to 0 when the size of the data is a multiple of the cache line size. If the calculation looks too cryptic I can change it to something a bit more explicit.
I've also made `get_cache_line_padding_size` and `get_cache_line_size` unconditionally `constexpr` since they have to be `constexpr`.
=> Fix padding calculation in cache_aligned_data.hpp

src/runtime/resource/detail/detail_partitioner.cpp
This probably got lost in a rebase, leaving the `--hpx:use-process-mask` option quite ineffective...
=> Make sure process mask option is passed to affinity_data

hpx/runtime/threads/policies/thread_queue.hpp, hpx/runtime/threads/policies/thread_queue_mc.hpp, tests/performance/local/future_overhead.cpp
Adds a few more variations to the `future_overhead` test:
- Spawn tasks directly using `register_work` (overhead of executors)
- Spawn tasks directly on scheduler using `create_thread` (overhead of dispatching through applier, thread manager, thread pool)
- Spawn tasks hierarchically using `create_thread` with task placement (spawn one task per core which spawns all tasks for that core)
- Spawn tasks hierarchically using `apply` with task placement
Timings on Piz Daint (sorry about the ugly tables):
```
invoked 100000, futures      apply   limiting-Exec     default_executor in      0.071536 seconds        : 0.715361 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures      apply   limiting-Exec …
```
=> Add more variations to future_overhead test

libs/config/include/hpx/config.hpp
=> Making sure HPX_IDLE_BACKOFF_TIME_MAX is always defined (even if its unused)

docs/sphinx/manual.rst, docs/sphinx/manual/troubleshooting.rst
Adds a short troubleshooting section to the manual. Generally I think we should try to keep tips like these in their appropriate sections, but some things pop up frequently enough that I think it's worth having a separate section just for common problems. Doesn't contain much yet, but it'll hopefully expand over time.
=> Add troubleshooting section to manual

plugins/parcelport/mpi/parcelport_mpi.cpp
Adding PMIx environment variable. This allows to automatically detect the MPI environment on summit.
=> Fixing MPI detection for PMIx

libs/algorithms/tests/CMakeLists.txt, libs/allocator_support/tests/CMakeLists.txt, libs/assertion/tests/CMakeLists.txt, libs/cache/tests/CMakeLists.txt, libs/collectives/tests/CMakeLists.txt, libs/concepts/tests/CMakeLists.txt, libs/concurrency/tests/CMakeLists.txt, libs/config/tests/CMakeLists.txt, libs/create_library_skeleton.py, libs/datastructures/tests/CMakeLists.txt, libs/errors/tests/CMakeLists.txt, libs/filesystem/tests/CMakeLists.txt, libs/format/tests/CMakeLists.txt, libs/hardware/tests/CMakeLists.txt, libs/hashing/tests/CMakeLists.txt, libs/iterator_support/tests/CMakeLists.txt, libs/logging/tests/CMakeLists.txt, libs/parallel_executors/tests/CMakeLists.txt, libs/preprocessor/tests/CMakeLists.txt, libs/program_options/tests/CMakeLists.txt, libs/resiliency/tests/CMakeLists.txt, libs/segmented_algorithms/tests/CMakeLists.txt, libs/statistics/tests/CMakeLists.txt, libs/testing/tests/CMakeLists.txt, libs/thread_support/tests/CMakeLists.txt, libs/timing/tests/CMakeLists.txt, libs/topology/tests/CMakeLists.txt, libs/type_support/tests/CMakeLists.txt, libs/util/tests/CMakeLists.txt
- indenting cmake output generated from module configuration
This just cleans up the generated output from module configuration.
=> Switching the use of message(STATUS "...") to hpx_info

libs/plugin/include/hpx/plugin/export_plugin.hpp
Fixes compilation on GCC 5 after #4050. It looks like our `any` constructor here: https://github.com/STEllAR-GROUP/hpx/blob/7305142684e4872f82a093c08d889c0f384f235e/libs/datastructures/include/hpx/datastructures/any.hpp#L457-L468 should not actually be explicit according to [cppreference](https://en.cppreference.com/w/cpp/utility/any/any). If that's the case I'll change the constructor instead of the construction. @hkaiser @K-ballo do you know what the correct thing to do here is?
=> Fix compilation on GCC 5

libs/filesystem/CMakeLists.txt, libs/filesystem/include/hpx/filesystem.hpp, src/util/parse_command_line.cpp
- this is useful in situations where other parts of an application rely on Boost.FileSystem
=> Adding option allowing to force using Boost.FileSystem

examples/resource_partitioner/shared_priority_queue_scheduler.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/policies/shared_priority_queue_scheduler.hpp, hpx/runtime/threads/thread.hpp, hpx/runtime_handlers.hpp, src/hpx_init.cpp, src/runtime/threads/executors/current_executor.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/thread.cpp, src/runtime_handlers.cpp, tests/unit/threads/thread.cpp
Minor threading refactoring to remove a few more dependencies.
- Use `hpx::threads::detail::get_thread_num_tss` instead of `hpx::get_worker_thread_num` to get thread number in schedulers etc.
- Pass thread pool into `hpx::thread` constructor. Old constructors remain, but don't fall back to the default thread pool if not on an HPX thread.
- Remove some leftover includes.
=> Threading refactoring
