CMakeLists.txt, hpx/runtime/threads/coroutines/detail/context_generic_context.hpp, hpx/runtime/threads/coroutines/detail/context_linux_x86.hpp, hpx/runtime/threads/coroutines/detail/context_posix.hpp, hpx/runtime/threads/coroutines/detail/context_windows_fibers.hpp, src/runtime/threads/threadmanager_counters.cpp, tests/unit/performance_counter/all_counters.cpp
Makes the counters optional and turns them off by default. Saves us some cache misses when creating and rebinding threads. It makes a small but noticeable difference in the `future_overheads` benchmark.
=> Make counters in coroutines optional

CMakeLists.txt
`HPX_WITH_MORE_THAN_64_THREADS` should always be determined from `HPX_WITH_MAX_CPU_COUNT` (there is no use in `HPX_WITH_MAX_CPU_COUNT` > 64 and `HPX_WITH_MORE_THAN_64_THREADS=OFF`, or vice versa). `HPX_WITH_MORE_THAN_64_THREADS` was also not updated when reconfiguring with `HPX_WITH_MAX_CPU_COUNT` > 64.
=> Deprecate HPX_WITH_MORE_THAN_64_THREADS

hpx/lcos/detail/future_data.hpp, hpx/lcos/local/packaged_continuation.hpp
When running the tss_test compiled with clang 8, I encountered strange segfaults (address sanitizer was complaining about stack use after end of scope). After removing those returns, the segfault and sanitizer report went away.
=> Removing return of thread_result_type from functions not needing them

libs/functional/include/hpx/functional/function_ref.hpp, libs/functional/tests/unit/CMakeLists.txt, libs/functional/tests/unit/function/allocator_test.cpp, libs/functional/tests/unit/function/contains_test.cpp, libs/functional/tests/unit/function/function_args.cpp, libs/functional/tests/unit/function/function_arith.cpp, libs/functional/tests/unit/function/function_bind_test.cpp, libs/functional/tests/unit/function/function_ref.cpp, libs/functional/tests/unit/function/function_ref_wrapper.cpp, libs/functional/tests/unit/function/function_target.cpp, libs/functional/tests/unit/function/function_test.cpp, libs/functional/tests/unit/function/nothrow_swap.cpp, libs/functional/tests/unit/function/stateless_test.cpp, libs/functional/tests/unit/function/sum_avg.cpp, tests/unit/util/function/CMakeLists.txt
This PR moves some of the tests related to `hpx::util::function_nonser` to the functional module.
Flyby: function_ref now properly handles `std::reference_wrapper`
=> Function tests

src/runtime/threads/policies/parse_affinity_options.cpp
=> use std::round for guaranteed rounding without errors

hpx/hpx_init.hpp, hpx/hpx_init_impl.hpp, hpx/hpx_start.hpp, hpx/hpx_start_impl.hpp
Fixes #4107.
This overload allows starting the runtime while providing no entry point
and no command line arguments to parse.
=> Overload for start without entry point/argv.

hpx/runtime/threads/policies/lockfree_queue_backends.hpp
@tianyi93 Could you please verify whether this fixes your performance issue?
=> Fixing performance regression introduced earlier

libs/collectives/CMakeLists.txt, libs/execution/include/hpx/parallel/executors/parallel_executor.hpp
Fixes deadlocks typically seen in the `1d_stencil` example caused by yielding while initializing a static variable. Details in commit message.
Also initializes `global_num_tasks` in the `parallel_executor` based on the number of threads in the current pool (or default pool if not on an HPX thread).
=> Fix initialization of global_num_tasks in parallel_executor

hpx/lcos/local/channel.hpp, hpx/runtime/parcelset/parcelhandler.hpp
The implicit capture of 'this' by default by-value capture is deprecated in C++20.  This revision is intended to address this change (and to eliminate numerous warnings when building code).
=> Add this to lambda capture list

hpx/compute/host/block_executor.hpp, tests/regressions/computeapi/CMakeLists.txt, tests/regressions/computeapi/parallel_fill_4132.cpp
Fixes #4132. In general fixes the `block_executor` to make sure it forwards all chunks to the underlying executors.
@hkaiser this fixes the problem, but I'm unsure about my `std::advance`s. A forward iterator does not guarantee O(1) complexity for it, does it? I found the current version easier to read, but I'll obviously change it to do fewer `std::advance`s if needed.
=> Fix block_executor

libs/coroutines/src/detail/coroutine_impl.cpp, libs/coroutines/src/detail/tss.cpp
These were not supposed to be there anymore after #4099. Nothing from the headers was used though so removing them is enough.
=> Remove runtime includes from coroutines module

hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/policies/thread_queue.hpp, hpx/runtime/threads/policies/thread_queue_init_parameters.hpp, hpx/runtime/threads/policies/thread_queue_mc.hpp, hpx/runtime/threads/thread_data.hpp, hpx/runtime/threads/thread_data_fwd.hpp, hpx/runtime/threads/thread_data_stackful.hpp, hpx/runtime/threads/thread_data_stackless.hpp, hpx/runtime/threads/thread_helpers.hpp, libs/coroutines/CMakeLists.txt, libs/coroutines/include/hpx/coroutines/coroutine.hpp, libs/coroutines/include/hpx/coroutines/coroutine_fwd.hpp, libs/coroutines/include/hpx/coroutines/detail/context_base.hpp, libs/coroutines/include/hpx/coroutines/detail/coroutine_impl.hpp, libs/coroutines/include/hpx/coroutines/stackless_coroutine.hpp, libs/coroutines/include/hpx/coroutines/thread_enums.hpp, src/runtime/applier/applier.cpp, src/runtime/threads/thread_data.cpp, src/runtime/threads/thread_data_stackful.cpp, src/runtime/threads/thread_data_stackless.cpp, src/runtime/threads/threadmanager.cpp, src/util/runtime_configuration.cpp, tests/headers/CMakeLists.txt, tests/performance/local/timed_task_spawn.cpp
=> Adding basic support for stackless threads

libs/program_options/include/hpx/program_options/parsers.hpp
Fixes compilation with `HPX_PROGRAM_OPTIONS_WITH_BOOST_PROGRAM_OPTIONS_COMPATIBILITY=OFF`.
@hkaiser would you happen to remember if the warning was about an unused variable? Can we ignore the check on that line somehow?
=> Add back private m_desc member variable in program_options module

hpx/plugins/parcelport/mpi/sender.hpp
GCC 7.3 and openmpi 4 was complaining about this assignment, added a cast to make it happy.  
Fixes #4151
- minor change to cast a variable assignment
=> Casting MPI tag value

examples/resource_partitioner/shared_priority_queue_scheduler.hpp, libs/collectives/tests/performance/osu/osu_coll.hpp, libs/segmented_algorithms/tests/unit/partitioned_vector_exclusive_scan.cpp, libs/segmented_algorithms/tests/unit/partitioned_vector_exclusive_scan2.cpp, libs/segmented_algorithms/tests/unit/partitioned_vector_inclusive_scan.cpp, libs/segmented_algorithms/tests/unit/partitioned_vector_inclusive_scan2.cpp, src/runtime/components/server/runtime_support_server.cpp, src/util/init_logging.cpp, tools/inspect/include_check.cpp
- add header iomanip to those missing places and inspect tool
I have bugs when building tests: https://gist.github.com/weilewei/087b30fd5fe07ac885553c6709c18c34
for example:
```
/gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx/libs/segmented_algorithms/tests/unit/partitioned_vector_exclusive_scan2.cpp:27:23: error: 'setw' is not a member of 'std'
std::cout << std::setw(60) << a << std::setw(40) << b << std::setw(10)     \
```
=> add header iomanip to tests and tool

plugins/parcelport/libfabric/CMakeLists.txt, plugins/parcelport/mpi/CMakeLists.txt, plugins/parcelport/tcp/CMakeLists.txt
Fixes master, missing `hpx_memory` dependency
=> Add hpx_memory as a dependency of parcelport plugins

cmake/HPX_SetupTarget.cmake
While the policy CMP0060 is activated for building HPX itself, for HPX
applications #2396 can lead to errors during linking if the wrong Boost
installation is picked up by the CMake module.
=> Added CMake policy CMP0060 for HPX applications.

libs/allocator_support/CMakeLists.txt
Fixes master with jemalloc and `HPX_WITH_INTERNAL_ALLOCATOR`
=> Adding allocator imported target as a dependency of allocator module

hpx/hpx_init.hpp, hpx/hpx_init_impl.hpp, hpx/hpx_start.hpp, hpx/hpx_start_impl.hpp, src/runtime.cpp
Sometimes the HPX library gets simply unloaded as a result of some extreme error handling. Avoid hangs in the end by setting a flag.
=> Handle quick exit

plugins/parcelport/mpi/CMakeLists.txt
I tried to do it like the TCP parcel port, but that didn't work.  This works.  Fixes #4169
Fixes #
-
-
-
=> Adding APEX dependency to MPI parcelport

libs/coroutines/include/hpx/coroutines/detail/coroutine_accessor.hpp, libs/coroutines/include/hpx/coroutines/detail/coroutine_self.hpp, libs/coroutines/include/hpx/coroutines/detail/coroutine_stackful_self.hpp, libs/coroutines/include/hpx/coroutines/detail/coroutine_stackless_self.hpp, libs/coroutines/include/hpx/coroutines/stackless_coroutine.hpp, libs/coroutines/src/detail/coroutine_impl.cpp, src/runtime/threads/thread_data.cpp, tests/regressions/threads/CMakeLists.txt, tests/regressions/threads/stackless_self_4155.cpp
=> Stackless coroutines now can refer to themselves (through get_self() and friends)

hpx/lcos/local/condition_variable.hpp
Fixes errors about suspending with held locks in mutex/condition variable: https://circleci.com/gh/STEllAR-GROUP/hpx/138751.
=> Ignore lock in condition_variable::wait

CMakeLists.txt, cmake/HPX_ForwardCacheVariables.cmake, cmake/HPX_SetupBoost.cmake, cmake/HPX_SetupBoostFilesystem.cmake, cmake/HPX_SetupBoostProgramOptions.cmake, cmake/templates/HPXConfig.cmake.in
Generalises  #4159
Forward `HPX_*` like CMake Cache variables to hpx dependent projects
=> Forward HPX_* cmake cache variables to external projects

src/runtime_impl.cpp, tests/performance/local/resume_suspend.cpp, tests/unit/resource/suspend_runtime.cpp
Makes `hpx::start` return slightly later, but means that users don't have to worry about waiting for `state_running` manually before calling `hpx::suspend`.
=> Wait for runtime to be running before returning from hpx::start

docs/sphinx/manual/miscellaneous.rst, examples/1d_stencil/1d_stencil_4_checkpoint.cpp, hpx/runtime/naming/name.hpp, hpx/runtime/naming_fwd.hpp, hpx/util/checkpoint.hpp, src/runtime/naming/name.cpp, tests/unit/util/CMakeLists.txt, tests/unit/util/checkpoint.cpp, tests/unit/util/checkpoint_component.cpp
Extended current implementation of `hpx::util::checkpoint` to properly handle components.
Summary:
- Fixed `checkpoint.cpp` to make floats constant
- Makes MSVC happy
- Adding `checkpoint_component.cpp`
- Raise abstraction level in checkpoint
- Create new function arch_data that will be overloaded to properly
handle components
- Adding in components to test
- Working component checkpointing!
- Checkpoints a server
- Still needs to create a new client
- Create new client on restored server
- Adding functionality to enable checkpointing of clients
- Checkpoints the server the client points to
- Still need to add functionality to restore which would
create a new client with the resurrected server
- Allowing components to be restored with provided client
- Users can now use clients to …
=> Support Checkpointing Components

libs/basic_execution/include/hpx/basic_execution/agent_ref.hpp
Building with C++11 gives the warning about constexpr not being implicitly const in newer standards. This adds the explicit const.
=> Small const fix to basic_execution module

CMakeLists.txt
- this helps if the user reuses an existing cmake cache after switching branches
=> Resetting some cached variables to make sure those are re-filled

cmake/templates/HPXConfig.cmake.in
Makes sure the `hpx::cuda` target is available for dependent projects.
=> Set up CUDA in HPXConfig.cmake

hpx/runtime/threads/thread_data.hpp
Fixes errors like these in `thread_data.hpp`:
```
.../src/hpx/runtime/threads/thread_data.hpp:245:50: error: enclosing class of constexpr non-static member function ‘hpx::naming::address_type hpx::threads::thread_data::get_component_id() const’ is not a literal type
HPX_CXX14_CONSTEXPR naming::address_type get_component_id()
```
(http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_63_centos_x86_64_release/builds/451/steps/build_core/logs/stdio)
This restriction was lifted in GCC 7.
=> Don't use constexpr in thread_data with GCC <= 6

src/runtime/threads/execution_agent.cpp
Fixes
```
/buildbot/rostam/slave_rostam/hpx_gcc_5_boost_1_62_centos_x86_64_release/src/src/runtime/threads/execution_agent.cpp:145:76: error: no matching function for call to ‘std::pair<hpx::threads::thread_state_enum, hpx::threads::thread_id>::pair(hpx::threads::thread_state_enum&, std::nullptr_t)’
statex = self_.yield(threads::thread_result_type(state, nullptr));
```
caused by the implicit conversion required from `nullptr_t` to `thread_id`. GCC 6 onwards accepts the code as it is.
=> Fix execution_agent.cpp compilation with GCC 5

.circleci/config.yml
I'm hoping this will fix the `stable` tag not always being successfully pushed. The error messages hint that the shallow clone is the problem so I'd like to give this a go. I don't understand why the push sometimes succeeds though.
=> Use full clone on CircleCI for pushing stable tag

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx11_std_quick_exit.cpp, hpx/hpx_init_impl.hpp, hpx/hpx_start_impl.hpp
`quick_exit` is not always available on macOS.
=> Only use quick_exit if available

docs/sphinx/examples/hello_world.rst, examples/quickstart/hello_world_distributed.cpp
This both makes sure tasks are scheduled sooner on the correct worker threads and avoids certain infinite loops in which the foreman thread always gets scheduled on an odd-numbered thread and the last worker task always gets scheduled on an even-numbered thread, or vice versa, because of round-robin scheduling. With an even number of worker threads this can lead to the worker thread never being scheduled on the correct thread. This commit adds scheduling hints to the worker tasks to ensure this will not happen. To make this happen `hello_world_worker` is no longer an action, but this is appropriate as it's only called locally.
=> Add scheduling hints to hello_world_distributed

libs/algorithms/include/hpx/parallel/util/detail/handle_local_exceptions.hpp, libs/assertion/include/hpx/assertion.hpp, src/util/interval_timer.cpp, src/util/one_size_heap_list.cpp
Disables `handle_local_exception` code from being compiled in device mode. Flybys:
- Use CUDA's `assert` for handling assertions on device (no custom message, but prints file and location)
- Change a couple of `register_*` calls from the `hpx::applier` namespace to `hpx::threads`
=> Fix CUDA 10 build

CMakeLists.txt, libs/coroutines/include/hpx/coroutines/detail/context_impl.hpp, libs/hashing/include/hpx/hashing/fibhash.hpp
- flyby: move hpx_option to before first usage of the option value
- also fixes a misspelled pp constant
Fixes 32bit rpm builds, @msimberg I think this should be part of the V1.4 release
Fixes #4215
=> Fixing gcc warning on 32bit platforms (integer truncation)

cmake/templates/HPXConfig.cmake.in, cmake/templates/HPXMacros.cmake.in
Do we want to go all in and check the allocator library paths as well?
=> Clean up allocator checks for dependent projects

examples/1d_stencil/1d_stencil_4_throttle.cpp
Fixes last APEX test that only fails when Active Harmony is used and the system has lm_sensors and/or RAPL power measurement support
- explicitly stop the periodic policy that controls number of active workers
-
-
=> Fixing APEX shutdown by explicitly shutting down throttling

.travis.yml, tools/travis/build_and_run_tests.sh, tools/travis/configure.sh, tools/travis/install_dependencies.sh
Travis CI has a timeout of 50 minutes per build which is not enough to build everything, but this will at least build the core libraries and perhaps examples.
=> Add OS X builds to Travis CI

CMakeLists.txt, cmake/toolchains/BGION-gcc.cmake, cmake/toolchains/BGQ.cmake, cmake/toolchains/XeonPhi.cmake
Flyby: fixes verbs and other parcelport related options.
=> Deprecate verbs parcelport

examples/CMakeLists.txt, hpx/include/lcos.hpp
The option was already removed in the previous version.
=> Remove leftover queue compatibility checks

src/runtime_impl.cpp
The main thread startup callbacks were called after `hpx_main` was scheduled. This meant that the test failed occasionally if `hpx_main` was scheduled quickly enough. This moves the main thread tss init (which calls the startup functions) to before `hpx_main` is scheduled.
=> Fix start_stop_callbacks test

libs/compute/include/hpx/compute/detail/target_distribution_policy.hpp
Fixes a harmless error from holding a lock while suspending in the `partitioned_vector_target` test. The error message is usually this:
```
terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
what():  suspending thread while at least one lock is being held, stack backtrace: 37 frames:
0x2aaaac0d3833  : ??? + 0x2aaaac0d3833 in /scratch/snx3000/simbergm/pycicle/instance-gcc-oldest/build/hpx-master-gcc-oldest/lib/libhpxd.so.1
0x2aaaac135c40  : ??? + 0x2aaaac135c40 in /scratch/snx3000/simbergm/pycicle/instance-gcc-oldest/build/hpx-master-gcc-oldest/lib/libhpxd.so.1
0x2aaaac1419e2  : ??? + 0x2aaaac1419e2 in /scratch/snx3000/simbergm/pycicle/instance-gcc-oldest/build/hpx-master-gcc-oldest/lib/libhpxd.so.1
0x2aaaac0f969a  : …
```
=> Ignore lock in target_distribution_policy

libs/concurrency/include/hpx/concurrency/cache_line_data.hpp
"Fixes" #4148 by reverting to the non-alignas versions with all C++ standards.
=> Don't use alignas in cache_{aligned,line}_data

cmake/HPX_GeneratePackage.cmake
=> Allow CMAKE_INSTALL_PREFIX to be a relative path

docs/sphinx/manual/optimizing_hpx_applications.rst, src/runtime/components/server/runtime_support_server.cpp
Fixes #4123.
- Fixes command line option documentation.
- Fixes loop condition for handling unregistered options.
=> Fix PAPI command line option documentation

tests/regressions/lcos/ignore_while_locked_1485.cpp
Ignores yet another lock held while suspending.
The test was originally introduced in https://github.com/STEllAR-GROUP/hpx/pull/1487/files, but I can't tell if I'm actually subverting what it's supposed to be testing by ignoring the lock. @hkaiser, @sithhell do you remember what the original failure mode of that test was before it was fixed? I'm starting to get a bad feeling about this whole ignoring-locks business...
=> Ignore lock in ignore_while_locked_1485 test

libs/collectives/include/hpx/collectives/all_reduce.hpp, libs/collectives/include/hpx/collectives/all_to_all.hpp
Fixes #
- Adding lock ignore to all_reduce and all_to_all
Related to a Phylanx issue encountered when trying to add matrices with Blaze. When the matrix size exceeded the Blaze parallelization threshold, the presence of the lock in all_reduce caused hpx to throw when suspension was attempted during the parallel add
=> Ignoring lock in all_to_all and all_reduce

hpx/util/annotated_function.hpp
Fixes annotating HPX threads with APEX
- minor change to use the passed in name
=> fixing annotated task to use the name, not the desc

cmake/templates/HPXMacros.cmake.in
Makes it an error (in CMake) to mix Debug and Release builds, with an option to ignore the check. I left the warning there even if the check is ignored to make sure users remember it's a bad idea to mix build types.
=> Make mismatching build types a hard error in CMake

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx17_noexcept_function.cpp, hpx/runtime/actions/component_action.hpp, hpx/runtime/actions/plain_action.hpp, tests/performance/local/future_overhead.cpp
Fixes compilation errors in C++17 mode if noexcept functions are bound to actions
=> Adding action specializations for noexcept functions

cmake/HPX_SetupApex.cmake, cmake/templates/HPXConfig.cmake.in, src/CMakeLists.txt
Fixes linking problems with external executables. Fixes flatbed problems from apex dependencies.
=> Fixing HPX/APEX linking and dependencies for external projects like Phylanx

hpx/async_launch_policy_dispatch.hpp, hpx/lcos/detail/future_data.hpp, hpx/lcos/local/futures_factory.hpp, hpx/lcos/local/packaged_continuation.hpp, hpx/runtime/threads/executors/guided_pool_executor.hpp, libs/affinity/tests/unit/parse_affinity_options.cpp, libs/execution/include/hpx/parallel/executors/thread_execution.hpp, libs/resource_partitioner/examples/async_customization.cpp, src/lcos/detail/future_data.cpp, src/util/backtrace/backtrace.cpp, src/util/thread_description.cpp
When an annotated task is passed though the asyn dispatch, we can strip
off the task 'name' or annotation and pass it through to the thread
creation so that it is used when the task is initialized and apex
get the right name. We make use of
traits::get_function_annotation<typename hpx::util::decay<F>::type>::call(f)
to achieve this.
=> Fix apex annotation for async dispatch

libs/allocator_support/src/CMakeLists.txt, libs/concepts/src/CMakeLists.txt, libs/datastructures/src/CMakeLists.txt, libs/debugging/src/CMakeLists.txt, libs/errors/src/CMakeLists.txt, libs/hashing/src/CMakeLists.txt, libs/iterator_support/src/CMakeLists.txt, libs/program_options/src/CMakeLists.txt, libs/thread_support/src/CMakeLists.txt, libs/type_support/CMakeLists.txt, libs/type_support/src/CMakeLists.txt, libs/util/src/CMakeLists.txt
- Removes empty `src/CMakeLists.txt` files
- Removes `concepts` dependency from the `type_support` module (this was a circular dependency only in the CMake world, in the source code there is no circular dependency)
=> Cleanup modules CMakeLists.txt

cmake/HPX_AddModule.cmake, libs/basic_execution/CMakeLists.txt, libs/compute/CMakeLists.txt, libs/compute_cuda/CMakeLists.txt, libs/memory/CMakeLists.txt
- Adds a missing option to `basic_execution`
- Removes the option for modules that don't need it
- Doesn't create the `HPX_X_WITH_COMPATIBILITY_HEADERS` option if it's not requested
=> Clean up compatibility header options

cmake/HPX_PerformCxxFeatureTests.cmake
=> Testing for noexcept function specializations in in C++11/14 mode

.circleci/config.yml, CMakeLists.txt, hpx/runtime/threads/thread_init_data.hpp
Updating APEX tag, don't create new task_wrapper on operator= of hpx_thread object
- Update APEX tag to 2.1.7
- Don't create new apex_wrapper object when hpx_thread operator=() is used.
-
=> Updating APEX tag, don't create new task_wrapper on operator= of hpx_thread object

CMakeLists.txt, docs/sphinx/about_hpx/people.rst, docs/sphinx/releases/whats_new_1_4_0.rst, tools/generate_issue_pr_list.sh
Adds release notes for the 1.4.0 release.
Note: they are currently just in the form of bullet points. Everyone, please have a look and let me know if you'd like to have something added (or removed) to the list.
=> Add release notes for 1.4.0

tools/inspect/inspect.cpp, tools/inspect/inspector.hpp
- this avoids a 'missing SPDX' inspect error
@msimberg this should go into the release, I think (without it even master is 'broken').
=> Do not check LICENSE_1_0.txt for inspect violations

hpx/runtime/threads/policies/queue_holder_thread.hpp, hpx/runtime/threads/policies/shared_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/thread_queue_mc.hpp, libs/debugging/include/hpx/debugging/print.hpp, tests/unit/resource/CMakeLists.txt
- flyby: fixing a ton of signed/unsigned and narrowing warnings
- flyby: moving a MSVC specific change from release to master
@msimberg I think this should be added to the release, still.
=> Fixing problem if 128 bit atomics are not available

hpx/plugins/parcelport/mpi/mpi_environment.hpp, plugins/parcelport/mpi/mpi_environment.cpp
`MPI_Init` called twice now throws error:
```
--------------------------------------------------------------------------
Open MPI has detected that this process has attempted to initialize
MPI (via MPI_INIT or MPI_INIT_THREAD) more than once.  This is
erroneous.
--------------------------------------------------------------------------
[72238f88c12e:44621] *** An error occurred in MPI_Init
[72238f88c12e:44621] *** reported by process [3814129665,0]
[72238f88c12e:44621] *** on a NULL communicator
[72238f88c12e:44621] *** Unknown error
[72238f88c12e:44621] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[72238f88c12e:44621] ***    and potentially your MPI job)
```
This PR adds `MPI_Initialized` to the mpi parcelport before calling the MPI_Init function. This allows …
=> Checks for MPI_Init being called twice

CMakeLists.txt, cmake/HPX_SetupApex.cmake, cmake/HPX_SetupBoostIostreams.cmake, cmake/HPX_SetupBoostRegex.cmake, cmake/HPX_SetupGooglePerfTools.cmake, cmake/HPX_SetupLibfabric.cmake, cmake/HPX_SetupMPI.cmake, cmake/HPX_SetupValgrind.cmake, cmake/HPX_SetupVerbs.cmake
Fixes CMake configuration with APEX and CUDA enabled at the same time. Also adds more guards for targets that may be created multiple times when HPX is found multiple times.
=> Small CMake fixes

examples/jacobi/CMakeLists.txt, examples/jacobi/jacobi_component/CMakeLists.txt, hpx/custom_exception_info.hpp, hpx/lcos/detail/async_implementations_fwd.hpp, hpx/lcos/detail/async_unwrap_result_implementations_fwd.hpp, hpx/lcos/detail/future_data.hpp, hpx/runtime/actions/base_action.hpp, hpx/runtime/components/pinned_ptr.hpp, hpx/runtime/naming_fwd.hpp, hpx/runtime/parcelset/parcel.hpp, hpx/runtime/threads/thread_data.hpp, hpx/runtime/threads/thread_init_data.hpp, hpx/traits/action_decorate_function.hpp, hpx/traits/action_select_direct_execution.hpp, hpx/util/wrapper_heap_base.hpp, libs/CMakeLists.txt, libs/all_modules.rst, libs/create_library_skeleton.py, libs/naming_base/CMakeLists.txt, libs/naming_base/README.rst, libs/naming_base/docs/index.rst, libs/naming_base/examples/CMakeLists.txt, libs/naming_base/include/hpx/naming_base.hpp, libs/naming_base/tests/CMakeLists.txt, libs/naming_base/tests/performance/CMakeLists.txt, libs/naming_base/tests/regressions/CMakeLists.txt, libs/naming_base/tests/unit/CMakeLists.txt, libs/serialization/CMakeLists.txt, src/util/init_logging.cpp
Move the `address_type`, `component_type` and `invalid_locality_id` to a `naming_base` module to eliminates some dependencies.
=> Module naming base

hpx/plugins/parcelport/tcp/receiver.hpp, hpx/plugins/parcelport/tcp/sender.hpp, hpx/util/asio_util.hpp, hpx/util/io_service_pool.hpp
The boost asio support includes termios.h.
The termios.h file on ppc64le defines these macros, which
are also used by blaze, blaze_tensor as Template names.
Make sure we undefine them before continuing.
Fixes phylanx bug https://github.com/STEllAR-GROUP/phylanx/issues/1088
- After boost/asio includes, undefine VT1 and VT2.
As requested by @hkaiser, this is a better solution than using `sed` on the blaze library, and it works.
=> Undefine VT1 and VT2 after boost includes.

libs/algorithms/include/hpx/parallel/util/prefetching.hpp
Replaces hardcoded value with `hpx::threads::get_cache_line_size` in prefetching.hpp.
=> Use hpx::threads::get_cache_line_size in prefetching.hpp

libs/compute/include/hpx/compute/vector.hpp
Fix of issue #4323.
- Addition of a temporary allocator, which stores the assigned vector's allocator
As discussed on the #ste||ar IRC channel with @K-ballo.
=> Usage of temporary allocator in assignment operator of compute::vector

libs/execution/CMakeLists.txt
Enables the option for compatibility headers in the execution module.
=> Enable compatibility headers option for execution module

CMakeLists.txt
CMP0074 find_package() uses <PackageName>_ROOT variables
This simplifies cmake invocation by allowing you to use package `MPI_ROOT` or `HDF5_ROOT` style vars and have them searched by default when finding a package of the same name as the `var_ROOT`
=> Add cmake policy - CMP0074 

src/runtime_handlers.cpp
The test segfaulted trying to access parent task information from another
locality. This happened because parent task handling was enabled when the
initial number of localities was 1. However, even when the initial number of
localities is 1 additional localities can connect later (as in the launch
process test) leading to APEX trying to acccess task information from another
locality. This changes the behaviour to only enable parent task handling when
networking is disabled.
=> Fix launch process test with APEX enabled

plugins/parcelport/mpi/mpi_environment.cpp
I am running HPX with the MPI parcelport inside another application that also uses MPI. If my application calls `MPI_Init` or `MPI_Init_thread` before starting the HPX runtime with `hpx::start`, `mpi_environment::init` correctly detects this and skips `MPI_Init`. In that case, I would expect HPX to not call `MPI_Finalize` when `hpx::stop` is called.
I get the error: `Attempting to use an MPI routine after finalizing MPI` when the rest of my application tries to make other MPI calls after `hpx::stop`.
Related to: https://github.com/STEllAR-GROUP/hpx/issues/1066
=> Skip MPI_Finalize if MPI_Init is not called from HPX

CMakeLists.txt
"Fixes" #4336.
@McKillroy how does this look to you?
=> Give a hard error if IO counters are enabled on non-Linux systems

.circleci/config.yml
Only run the step on changed files in pull requests, not on e.g. master.
Also skip HDF5 and PNG files.
=> Fix spellcheck step in CircleCI config

.circleci/config.yml, .clang-format, libs/coroutines/include/hpx/coroutines/detail/context_generic_context.hpp, libs/coroutines/include/hpx/coroutines/stackless_coroutine.hpp, libs/serialization/include/hpx/serialization/brace_initializable.hpp
Goes together with https://github.com/STEllAR-GROUP/docker_build_env/pull/19. Brace wrapping after case labels can be kept as it is with a new option but I don't see any obvious options to avoid the other formatting changes. They look like something that should've been applied with clang-format-8 anyway.
=> Update clang-format config file for version 9

libs/collectives/src/latch.cpp, src/CMakeLists.txt, src/lcos/base_lco_with_value.cpp, src/lcos/base_lco_with_value_1.cpp, src/lcos/base_lco_with_value_2.cpp, src/lcos/base_lco_with_value_3.cpp, src/performance_counters/counters.cpp, src/runtime/agas/component_namespace.cpp, src/runtime/agas/locality_namespace.cpp, src/runtime/agas/primary_namespace.cpp, src/runtime/agas/server/symbol_namespace_server.cpp
- flyby: clean up -fPIC option
Fixes #4320
=> Adding missing #includes to fix gcc V10 linker problems

hpx/runtime/threads/detail/thread_num_tss.hpp, hpx/runtime/threads/policies/queue_holder_numa.hpp, hpx/runtime/threads/policies/queue_holder_thread.hpp, hpx/runtime/threads/policies/shared_priority_queue_scheduler.hpp, libs/debugging/include/hpx/debugging/print.hpp
… mostly in the shared_priority_scheduler
- flyby: changing `debug::hex` and `debug::bin` to deduce their argument types
=> Another attempt at fixing the integral mismatch and conversion warnings

libs/resource_partitioner/examples/async_customization.cpp, libs/resource_partitioner/examples/guided_pool_test.cpp
Removes superfluous `HPX_EXPORT`s from resource partitioner examples.
=> Attempt to fix some test build errors on Windows

hpx/hpx_init.hpp, hpx/hpx_init_impl.hpp, hpx/hpx_start.hpp, hpx/hpx_start_impl.hpp, libs/resource_partitioner/examples/guided_pool_test.cpp, libs/resource_partitioner/examples/simple_resource_partitioner.cpp, libs/resource_partitioner/examples/simplest_resource_partitioner_1.cpp, libs/resource_partitioner/examples/simplest_resource_partitioner_2.cpp, libs/resource_partitioner/include/hpx/resource_partitioner/partitioner.hpp, libs/resource_partitioner/src/partitioner.cpp, libs/resource_partitioner/tests/unit/named_pool_executor.cpp, libs/resource_partitioner/tests/unit/resource_partitioner_info.cpp, libs/resource_partitioner/tests/unit/used_pus.cpp, src/hpx_init.cpp, tests/unit/resource/cross_pool_injection.cpp, tests/unit/resource/scheduler_priority_check.cpp, tests/unit/topology/numa_allocator.cpp
- this helps resolving linker errors on Windows if the main entry point to HPX is in a shared library
- this also cleans up the API as it makes the use of the resource partitioner explicit
Note that this is a breaking API as the use of the no-argument versions of `init` and `start` is now deprecated when using an explicit resource partitioner.
=> Adding overload for `hpx::init`/`hpx::start` for use with resource partitioner

cmake/HPX_SetupCUDA.cmake
Newer CMake (3.15 tested) accepted the old code, but older ones (3.10 tested) complain rightfully that `hpx_base_libraries` is not built by the dependent project when calling `find_package(HPX)`.
I've already added this change to the 1.4.1 release.
=> Fix configuration with CUDA and older CMake versions

tools/roll_release.sh
Not pushing the created tag explicitly leads to the `hub` command creating the tag instead of using the one created by the script. This seems to have been "close enough" for me not to notice any problems (plus my local tags showed the correct commit).
The `1.4.1-rc1` and `1.4.1` tags pointed to the wrong commits. I've corrected `1.4.1-rc1` and retracted the `1.4.1` tag until I'm sure things are done correctly. Apologies for any inconvenience this may have caused.
=> Fix roll_release.sh

cmake/HPX_ForwardCacheVariables.cmake, cmake/templates/HPXCacheVariables.cmake.in
Mainly just to get rid of the message `Installing: .../HPXCacheVariables.cmake` when configuring HPX.
=> Use configure_file for HPXCacheVariables.cmake

src/util/command_line_handling.cpp
Attempt to fix #4349. @albestro would you mind testing the changes?
=> Add warning messages for using thread binding options on macOS

libs/concurrency/include/hpx/concurrency/cache_line_data.hpp
=> Use appropriate cache-line size defaults for different platforms

libs/algorithms/include/hpx/parallel/algorithms/partition.hpp, libs/algorithms/include/hpx/parallel/algorithms/sort.hpp, libs/algorithms/include/hpx/parallel/util/detail/chunk_size.hpp, libs/execution/include/hpx/execution/executors/auto_chunk_size.hpp, libs/execution/include/hpx/execution/executors/persistent_auto_chunk_size.hpp
- note, this is a breaking change (with minimal potential impact) that adds
an argument to the callback function that is used by get_chunk_size()
- this also removes unnecessary limitations from `auto_chunk_size` such that 
the measurement is now always performed
=> Adding a parameter to auto_chunk_size allowing to control the amount of iterations to measure

libs/concurrency/include/hpx/concurrency/deque.hpp
This removes the deprecated use of Allocator::template rebind<>
=> Fixing use of allocator for C++20

hpx/lcos/detail/future_data.hpp, libs/compute_cuda/include/hpx/compute/cuda/target.hpp, libs/compute_cuda/src/cuda_target.cpp
Adds a free function to get a future from a stream (instead of requiring a `hpx::compute::cuda::target`).
@G-071
@biddisco I didn't get to creating a module yet, but can add that as well.
=> Add a helper function to get a future from a cuda stream

hpx/runtime/threads/detail/scheduled_thread_pool.hpp, hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp, hpx/runtime/threads/detail/scheduling_loop.hpp, hpx/runtime/threads/executors/thread_pool_os_executors.hpp, hpx/runtime/threads/policies/local_priority_queue_scheduler.hpp, hpx/runtime/threads/policies/local_queue_scheduler.hpp, libs/threading_base/include/hpx/threading_base/scheduler_base.hpp, libs/threading_base/include/hpx/threading_base/thread_pool_base.hpp, libs/threading_base/src/thread_pool_base.cpp, libs/threadmanager/include/hpx/threadmanager.hpp, src/runtime/threads/thread_pool_suspension_helpers.cpp
The pool and the scheduler both kept copies of the scheduler
mode and it was set on startup in different places. Some user
code that wished to set the scheduler mode to a non default
value at the start of hpx_main suffered from a race that allowed
the pool to overwrite the mode flags.
This commit removes the copy of the scheduler mode that was held
by the pool as well as some unnecessary set/get calls to the mode.
This also tidies up a lot of calls to if (get_scheduler_mode() & xxx)
and replaces them with a has_scheduler_mode(xxx) call that makes the
code a little more readable and maintainable.
=> Fix a race condition and clean-up usage of scheduler mode

tests/unit/resource/cross_pool_injection.cpp
The cross pool scheduler test fails for some builds because the shared priority scheduler is not enabled.
This fix should drop down to the default scheduler if the other is not available.
In future I'd like to extend the test to test all schedulers in turn.
=> Fix cross pool injection test, use default scheduler as falback

src/util/command_line_handling.cpp
=> Making sure to issue a warning if a file specified using --hpx:options-file is not found

tests/regressions/component/CMakeLists.txt
Fixes left-over issues as commented on #4373
=> Partially reverting changes applied by PR 4373

CMakeLists.txt, docs/sphinx/contributing/release_procedure.rst, docs/sphinx/manual/building_hpx.rst, libs/config/include/hpx/config/threads_stack.hpp
Updates the minimum GCC version in the documentation to 7.0. Also removes the "Recommended version" column from the tables as it's usually a safe assumption to take the latest version (if we have problems with the latest versions we can add it to the notes column). Also adds a new step to the release procedure to update minimum required versions.
=> Clean up and correct minimum required versions

CMakeLists.txt
To fix warnings like these: https://cdash.cscs.ch/viewBuildError.php?buildid=98781.
=> Ignore warnings about name mangling changing

hpx/runtime.hpp, hpx/util/interval_timer.hpp, hpx/util/query_counters.hpp, src/runtime.cpp, src/runtime/components/server/runtime_support_server.cpp, src/util/interval_timer.cpp, src/util/query_counters.cpp
- flyby: stopping timed counters at shutdown properly unregisters counters
Fixes #4419 
@diehlpk please verify that this solves the problem you reported.
=> Making sure interval time stops underlying timer thread on termination

cmake/HPX_SetupTarget.cmake
Fix to follow up on #4246. The `component` and `plugin` targets were linked publicly in `hpx_setup_target` leading to dependent targets to also get definitions like `HPX_COMPONENT_EXPORTS` which should stay private.
=> Link HPX::plugin and component privately in hpx_setup_target

libs/datastructures/include/hpx/datastructures/tuple.hpp, libs/errors/include/hpx/errors/exception_fwd.hpp
- Add a dummy `hpx::throws` declaration to suppress errors about `hpx::throws` being undefined in device code (suggestions for better/safer ways to fix this welcome!)
- Remove `HPX_HOST_DEVICE` attribute from defaulted `tuple` constructors; this is apparently not needed (and causes annoying warnings)
=> Minor CUDA fixes

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx17_std_variant.cpp, libs/serialization/CMakeLists.txt, libs/serialization/include/hpx/serialization/boost_variant.hpp, libs/serialization/include/hpx/serialization/std_tuple.hpp, libs/serialization/include/hpx/serialization/variant.hpp, libs/serialization/tests/unit/CMakeLists.txt, libs/serialization/tests/unit/serialization_boost_variant.cpp, libs/serialization/tests/unit/serialization_std_tuple.cpp, libs/serialization/tests/unit/serialization_std_variant.cpp, libs/serialization/tests/unit/serialization_tuple.cpp
- adding missing tests for tuple serialization
Fixes #4416
@McKillroy please verify whether this fixes the issue you reported
=> Adding serialization support for std::variant (if available) and std::tuple

hpx/traits/is_launch_policy.hpp, plugins/parcelport/mpi/mpi_environment.cpp
This also fixes an assertion that fires when MPI is enabled in the build but is not actually used to a distributed application.
=> This fixes an obsolete #include

libs/version/src/version.cpp
We have https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/plugins/parcelport/mpi/mpi.hpp, but to avoid a dependency on the plugins in the version module, I've just included the warning suppression pragmas directly in the `version.cpp` file. With this I'll enable the MPI parcelport on pycicle again (on the `gcc-cuda` builder).
=> Suppress MPI warnings in version.cpp

src/CMakeLists.txt
Potentially uncovered by #4388, which requires linking to `hpx_init` because of the introduced statics in `hpx_init`.
=> Make sure pkgconfig applications link with hpx_init

libs/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp, libs/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp, libs/threading_base/include/hpx/threading_base/thread_data.hpp, libs/threading_base/include/hpx/threading_base/thread_num_tss.hpp, libs/threading_base/src/execution_agent.cpp, libs/threading_base/src/thread_data.cpp, libs/threading_base/src/thread_num_tss.cpp, libs/threadmanager/include/hpx/threadmanager.hpp, src/runtime/threads/executors/current_executor.cpp, src/runtime/threads/executors/this_thread_executors.cpp, src/runtime/threads/executors/thread_pool_attached_executors.cpp
Resumes tasks on the worker thread that they were suspended on. This is something I *think* will help in some cases (based on some task plots I've seen), but I don't currently have a benchmark to verify if this makes things better or worse. It does make sense to avoid invalidating caches though.
I've at the same time tried to clean up the thread number implementation. Please comment on naming, exposed functions etc.
=> Resume tasks where they were suspended

examples/quickstart/CMakeLists.txt, examples/quickstart/executor_with_thread_hooks.cpp
- this executor wraps any other executor and makes sure that given start
and stop functions are being called for each HPX thread created by the
executor
=> Added example demonstrating how to create and use a wrapping executor

libs/coroutines/src/swapcontext.cpp
Bare minimum. I think we could do more to detect this automatically, but I'm scared of the complexities it'll introduce in our CMake (cross-compilation etc.).
=> Add more descriptive error message when using x86 coroutines on non-x86 platforms

docs/sphinx/quickstart.rst
hpx is available as a port in vcpkg, a C++ library manager that simplifies installation for hpx and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build hpx , ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.
Note: Currently only support dynamic build on Windows.
I'm a maintainer for vcpkg, and here is what the port script looks like. We try to keep the library maintained as close as possible to the original library.
=> Add vcpkg installation instructions

libs/execution/CMakeLists.txt
Fixes master
3 headers added in the CMakeLists.txt: `limiting_executor`, `guided_pool_executor`, `current_executor`
=> Add missing current_executor header

hpx/runtime/threads/executors/pool_executor.hpp
Forwarded `thread_pool_executor` instead of `pool_executor`.
=> Fix compatibility of `pool_executor`

init/src/hpx_wrap.cpp
There were still some linking errors on macOS that we didn't notice with the previous PR (#4475). This seems to fix them, but I don't know yet if I've broken Linux in return.
=> Attempting to fix hpx_init linking on macOS

libs/checkpoint/tests/unit/CMakeLists.txt, libs/errors/tests/unit/CMakeLists.txt, libs/iterator_support/tests/unit/CMakeLists.txt, libs/synchronization/tests/performance/CMakeLists.txt
The branch name was more optimistic than the results. Something is still not quite right with our sanitizer integration, and I managed to get it to report the ODR violations fixed in this PR. In doing so I broke other things in the sanitizer integration so those changes will have to wait. The ODR violations are real though, but not as serious as they sound. They are just a result of some tests linking to both `libhpx` and some of the static module libraries (`hpx_testing`).
=> Fix duplicate linking in tests (ODR violations)

.github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml
It seems like GitHub actions was not smart enough to only trigger one build per push when the triggers were `[push, pull_request]`. Please don't merge yet as I want to make sure that `pull_request` doesn't mean builds will be triggered only once when a pull request is opened.
If someone wants the builders to run on their branch without opening a PR, they can temporarily add `push` to the triggers.
=> Only test pull requests (not all branches) with GitHub actions

libs/async/include/hpx/async/async.hpp, libs/async/include/hpx/async/sync.hpp, libs/execution/CMakeLists.txt, libs/execution/include/hpx/execution/executors/parallel_executor.hpp, libs/execution/include/hpx/execution/executors/parallel_executor_aggregated.hpp, libs/execution/include/hpx/execution/executors/sequenced_executor.hpp, libs/execution/include/hpx/execution/executors/thread_pool_executor.hpp
I had forgotten to turn on deprecation warnings for the `execution` module. This fixes that and the associated headers.
=> Enable and fix deprecation warnings in execution module

hpx/traits/future_then_result_exec.hpp, libs/execution/CMakeLists.txt, libs/execution/include/hpx/execution/detail/async_launch_policy_dispatch.hpp, libs/execution/include/hpx/execution/executors/execution.hpp, libs/execution/include/hpx/execution/executors/execution_fwd.hpp, libs/execution/include/hpx/execution/executors/parallel_executor.hpp, libs/execution/include/hpx/execution/executors/parallel_executor_aggregated.hpp, libs/execution/include/hpx/execution/executors/polymorphic_executor.hpp, libs/execution/include/hpx/execution/force_linking.hpp, libs/execution/src/force_linking.cpp, libs/execution/src/polymorphic_executor.cpp, libs/execution/tests/unit/CMakeLists.txt, libs/execution/tests/unit/polymorphic_executor.cpp, libs/functional/include/hpx/functional/deferred_call.hpp
- flyby: fixing various flaws in executor implementation
Fixes #4489
=> Adding polymorphic_executor

cmake/templates/conf.py.in, docs/sphinx/api.rst
Related to #4329. Location, wording etc. can all be changed. Just wanted to get this up for people to comment. Contains one section for our current guarantees (i.e. close to none), and a commented out section for a potential 2.0.0.
We can discuss this at tomorrow's meeting.
=> Add API guarantee notes to API reference documentation

libs/version/CMakeLists.txt
Possibly fixes #4523. @kordejong mind giving this a try?
I'm not sure how best to test this... @kordejong with your permission I might just fork your `hello_hpx` repo and stick a CircleCI config in it and point it to the latest HPX master.
=> Make sure version module uses HPX's binary dir, not the parent's

hpx/lcos/local/futures_factory.hpp, libs/schedulers/include/hpx/schedulers/queue_holder_thread.hpp, libs/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp, libs/thread_executors/CMakeLists.txt, libs/thread_executors/include/hpx/thread_executors/thread_executor.hpp, tests/unit/resource/CMakeLists.txt, tests/unit/resource/scheduler_binding_check.cpp
A user on IRC posted a request to bind tasks to threads, but when using the default executor, the schedulehint was not being taken from the executor, instead the default was being used.
=> Fix schedule hint not being taken from executor

libs/async_base/include/hpx/async_base/sync.hpp, libs/execution/include/hpx/execution/apply.hpp, libs/execution/include/hpx/execution/dataflow.hpp
Fixes missed review comments on #4478. I tried this out with `apply` and the generated code ends up exactly the same (i.e. a call to `register_thread_nullary`, that speaks highly of the customization points). More complicated cases might not do the same (although one would hope so... it's templated anyway). In any case, like this we're consistent (`async` and `sync` already did the same), and protect ourselves against potential changes in the customization points.
Also fixes that one typo in `hpx/async_base/sync.hpp`...
=> Skip execution customization points when executor is known

libs/thread_executors/CMakeLists.txt
Fixes #4533.
I think I fixed this on another branch as well, but I can't find it now and it deserves its own PR anyway.
=> Enable compatibility headers for thread_executors module

docs/sphinx/manual/writing_single_node_hpx_applications.rst, examples/quickstart/CMakeLists.txt, examples/quickstart/channel_docs.cpp, examples/quickstart/local_channel_docs.cpp
Fixes #4519. @tiagofgon would you mind looking through this (I know you can't see the final result without building it but the examples are marked with `//[start` and `//]` comments in the two new examples)?
I do wish we had a better way of doing this. It may be possible to go the other way around (i.e. examples in docs and extract them into source files).
=> Move channel documentation examples to examples directory

cmake/templates/conf.py.in
Fixes this funny order: https://stellar-group.github.io/hpx-docs/tags/1.4.1/html/api.html#modules-reference.
=> Make sure module API docs show up in correct order

hpx/runtime/thread_pool_helpers.hpp, libs/execution/include/hpx/execution/executors/pool_executor.hpp, libs/resource_partitioner/tests/unit/named_pool_executor.cpp, libs/threadmanager/include/hpx/threadmanager.hpp, libs/threadmanager/src/threadmanager.cpp, src/runtime/thread_pool_helpers.cpp
Fixes #4535. Also adds a default constructor `pool_executor`.
=> Add API to check if a thread pool exists

docs/sphinx/manual/debugging_hpx_applications.rst
The flag `HPX_WITH_STACK_OVERFLOW_DETECTION` should be `HPX_WITH_STACKOVERFLOW_DETECTION` without the underscore.
=> Fix a typo in sanitizer build

examples/quickstart/component_with_executor.cpp, libs/coroutines/include/hpx/coroutines/thread_enums.hpp, libs/threading/src/thread.cpp, libs/threading_base/include/hpx/threading_base/set_thread_state.hpp, tests/regressions/CMakeLists.txt, tests/regressions/stack_size_config_4543.cpp
Fixes #4543. The changes are a bit awkard, so as I said in #4543 I'll change `thread_init_data` to use the enum stacksize along with #4542. I also changed the `thread_schedule_hint` one-argument constructor to be explicit to avoid having me pass a stack size for the hint...
=> Fix stack size

libs/algorithms/tests/regressions/count_3646.cpp, libs/compute/include/hpx/compute/host/block_allocator.hpp, libs/compute/include/hpx/compute/traits/allocator_traits.hpp, libs/execution/include/hpx/execution/executors/static_chunk_size.hpp, tests/performance/local/stream.cpp
Adds `hpx::compute::host::detail::policy_allocator` which allows creating an allocator for use with `hpx::compute::vector` with any execution policy, not just with the `block_executor`. The `block_allocator` has been rewritten to use `policy_allocator`, but the implementation itself is unchanged from `block_allocator` on master.
I have also changed the `static_chunk_size` executor parameters to only return powers of two chunk sizes (benchmarks below the fold).
I was unsure if it would be enough to make it generic over executors, but doing it over policies means that one can also switch allocation to be serial by changing the policy. `policy_allocator` is now in `detail`, and I don't know yet if we want to expose it directly.
My main motivation with this is to have be able to use the …
=> Add generic allocator for execution policies

libs/serialization/CMakeLists.txt, libs/serialization/include/hpx/serialization/force_linking.hpp, libs/serialization/include/hpx/serialization/serializable_any.hpp, libs/serialization/src/force_linking.cpp, libs/serialization/src/serializable_any.cpp
=> Making sure hash_any::operator()() is linked into core library

CMakeLists.txt
Added the missing "_WITH" in the error message.
=> fix CMake option typo

hpx/runtime/naming/name.hpp, libs/basic_execution/include/hpx/basic_execution/this_thread.hpp, libs/synchronization/include/hpx/synchronization/spinlock.hpp, libs/synchronization/include/hpx/synchronization/spinlock_no_backoff.hpp, libs/synchronization/src/stop_token.cpp
This reduces the cache-pressure while acquiring highly contented spinlock instances by mostly reading from it instead of constantly trying to write to it.
As a flyby, this removes the dependency on `boost/smart_ptr/detail/spinlock.hpp` and related Boost facilities.
=> Improve spinlock implementation to perform better in high-contention situations

libs/debugging/CMakeLists.txt
Fixes #4559
This prevents `hpx::util::backtrace` from being defined twice if `HPX_WITH_STACKTRACES=Off`.
=> Excluding unconditional definition of class backtrace from global header

libs/threading/include/hpx/threading/thread.hpp, libs/threading/src/thread.cpp, libs/topology/include/hpx/topology/topology.hpp, libs/topology/src/topology.cpp
Fixes #4569
- flyby: making the return value `[[nodiscard]]`
=> Changing return type of hardware_concurrency() to unsigned int

libs/synchronization/src/mutex.cpp
This one came up in the `shared_mutex1` test. There's more, but at least this fixes one failure. The comment above the fix should describe the change.
=> Unregister lock earlier to avoid holding it while suspending

docs/sphinx/manual/launching_and_configuring_hpx_applications.rst, libs/runtime_configuration/src/init_ini_data.cpp, libs/runtime_configuration/src/runtime_configuration.cpp, src/custom_exception_info.cpp, src/runtime.cpp
Adds the option `hpx.exception_verbosity`. It currently takes three values:
- `0`: prints filename, line, function name, and the exception string
- `1`: prints everything except the build configuration and environment variables
- `2`: prints everything
I'm not sure if they need to be shifted to have `0` mean no output, but I don't see that being useful for anyone. We could also use names (like `minimal`, `reduced`, `full`), but using numbers for the level is similar to what we do with logging.
Flyby: fix reading of ini files from `HOME` and `PWD`.
To do:
=> Add configuration option for making exceptions less noisy

libs/performance_counters/src/registry.cpp, src/runtime/agas/addressing_service.cpp, tests/performance/network/network_storage/network_storage.cpp
- flyby remove unneeded using statements
Fixes compilation problems with Boost V1.73
=> Adding missing using placeholder::_X

libs/testing/include/hpx/testing.hpp, libs/testing/src/testing.cpp, libs/testing/tests/unit/CMakeLists.txt, libs/testing/tests/unit/test_macros.cpp
Fixes #4554
This adds macro overloads to all `HPX_TEST()` macros allowing to pass any output stream as the respective first arguments. For instance:
```
HPX_TEST(true);             // uses std::cerr as before
HPX_TEST(hpx::cout, true);  // uses hpx::cout for generated output
```
=> Adding test macros supporting custom output stream

CMakeLists.txt, init/CMakeLists.txt, libs/basic_execution/include/hpx/basic_execution/register_locks.hpp, libs/basic_execution/src/register_locks.cpp, libs/debugging/include/hpx/debugging/backtrace/backtrace.hpp, libs/debugging/src/backtrace.cpp, libs/runtime_configuration/include/hpx/runtime_configuration/runtime_configuration.hpp, libs/runtime_configuration/src/runtime_configuration.cpp, src/custom_exception_info.cpp, src/hpx_init.cpp, src/runtime.cpp
Fixes #4580
This also adds a runtime configuration option to specify the stack trace depth: `--hpx:ini=hpx.trace_depth=<N>`.
Note: the symbol lookup fix proposed here was not actually tested. @teonnik, @msimberg would you be able to verify this, please?
=> Attempting to fix missing symbols in stack trace 

libs/algorithms/include/hpx/parallel/algorithms/for_loop.hpp, libs/algorithms/include/hpx/parallel/algorithms/for_loop_induction.hpp, libs/algorithms/include/hpx/parallel/algorithms/for_loop_reduction.hpp, libs/algorithms/tests/unit/algorithms/CMakeLists.txt, libs/algorithms/tests/unit/algorithms/for_loop_exception.cpp, libs/execution/include/hpx/execution/algorithms/detail/predicates.hpp
- flyby: adding constexpr to some utility functions for for_loop
=> Adding missing exception test for for_loop()

wrap/CMakeLists.txt
Fixes linking of HPX applications that rely on hpx_main.hpp if `HPX_WITH_DYNAMIC_MAIN=OFF`. This is the main mode on Windows but will work on other platforms as well.
=> Making sure main.cpp is built as a library if HPX_WITH_DYNAMIC_MAIN=OFF

hpx/hpx_init_impl.hpp, hpx/hpx_main_winsocket.hpp, hpx/hpx_start_impl.hpp, init/CMakeLists.txt, src/CMakeLists.txt, src/hpx_main_winsocket.cpp
Fixes linker errors if `hpx::init` or `hpx::start` are used from a shared library.
=> Moving winsocket initialization to core library

libs/mpi/include/hpx/mpi/mpi_future.hpp
Fixes wrong namespace leftover from latest merges
=> Fixing moodycamel namespace

libs/collectives/CMakeLists.txt, libs/collectives/include/hpx/collectives/all_reduce.hpp, libs/collectives/include/hpx/collectives/all_to_all.hpp, libs/collectives/include/hpx/collectives/broadcast.hpp, libs/collectives/include/hpx/collectives/broadcast_direct.hpp, libs/collectives/include/hpx/collectives/detail/communicator.hpp, libs/collectives/include/hpx/collectives/gather.hpp, libs/collectives/include/hpx/collectives/spmd_block.hpp, libs/collectives/include_compatibility/hpx/lcos/broadcast.hpp, libs/collectives/tests/performance/osu/osu_bcast.cpp, libs/collectives/tests/unit/CMakeLists.txt, libs/collectives/tests/unit/broadcast.cpp, libs/collectives/tests/unit/broadcast_direct.cpp
- unify implementation of collectives
- factor out beginnings of communicator functionality
- fixing a couple of minor issues in existing collectives
- modernized API of gather_here/gather_there (futures are now taken by rvalue ref)
- renamed existing broadcast.hpp to broadcast_direct.hpp
=> Adding broadcast_to/broadcast_from to collectives module

cmake/templates/HPXMacros.cmake.in
It should advise users to set it to `ON` to ignore the build type.
=> Fix error message when HPX_IGNORE_CMAKE_BUILD_TYPE_COMPATIBILITY=OFF

tests/performance/network/network_storage/CMakeLists.txt
`OUTPUT` keyword is expected to come first in `add_custom_command` (by `cmake-format`).
=> Fix cmake-format warning

libs/basic_execution/tests/CMakeLists.txt, libs/plugin/CMakeLists.txt, libs/plugin/tests/CMakeLists.txt, libs/plugin/tests/performance/CMakeLists.txt, libs/plugin/tests/regressions/CMakeLists.txt, libs/plugin/tests/unit/CMakeLists.txt, libs/prefix/CMakeLists.txt, libs/prefix/tests/CMakeLists.txt, libs/prefix/tests/performance/CMakeLists.txt, libs/prefix/tests/regressions/CMakeLists.txt, libs/prefix/tests/unit/CMakeLists.txt, libs/schedulers/include/hpx/schedulers/queue_holder_thread.hpp, libs/schedulers/tests/CMakeLists.txt, libs/version/include/hpx/version.hpp
This fixes a couple of dependencies on the main headers from the modules and makes their header tests use `NOLIBS`. This also adds header tests for the `plugin` and `prefix` modules.
Incidentally, this means that I was able to build the following libs into a standalone library without any dependencies from the main library:
```
affinity
allocator_support
asio
assertion
basic_execution
concepts
concurrency
config
coroutines
datastructures
debugging
errors
filesystem
format
functional
hardware
hashing
io_service
iterator_support
logging
memory
naming_base
pack_traversal
plugin
prefix
preprocessor
schedulers
serialization
static_reinit
string_util
testing
thread_pools
thread_support
threading_base
timing
topology
type_support
util
version
```
I think this is pretty close to what I think a …
=> Small module fixes

libs/basic_execution/include/hpx/basic_execution/register_locks.hpp, libs/basic_execution/src/register_locks.cpp, libs/threading_base/CMakeLists.txt, libs/threading_base/src/execution_agent.cpp
Currently, if a lock is actively ignored while the executing thread is suspended, then the lock is not properly de-registered if the thread is resumed on a different core. This PR fixes the issue by moving the lock registration data to a different core with the executing thread.
=> Making sure the thread-local lock registration data is moving to the core the suspended HPX thread is resumed on

libs/basic_execution/src/agent_ref.cpp, libs/execution/include/hpx/execution/executors/auto_chunk_size.hpp, libs/execution/tests/unit/parallel_executor.cpp, libs/execution/tests/unit/parallel_fork_executor.cpp, libs/execution/tests/unit/parallel_policy_executor.cpp, libs/executors/CMakeLists.txt, libs/executors/include/hpx/executors/force_linking.hpp, libs/executors/include/hpx/executors/parallel_executor.hpp, libs/executors/include/hpx/executors/parallel_executor_aggregated.hpp, libs/executors/src/force_linking.cpp, libs/thread_executors/include/hpx/thread_executors/thread_pool_os_executors.hpp, libs/thread_executors/src/force_linking.cpp, libs/thread_executors/src/thread_pool_os_executors.cpp
- flyby: adding sync_execute to parallel_executor and parallel_aggregated_executor
@McKillroy this should fix your issue with the wrapping executor not being invoked when the auto_chunker is used. This however requires that you implement the `sync_execute` method on your executor.
=> Making auto_chunk_size execute the given function using the given executor

examples/quickstart/executor_with_thread_hooks.cpp
=> Adding missing bulk_sync_execute wrapper to example executor

.circleci/config.yml, CMakeLists.txt, libs/debugging/src/backtrace.cpp
@hkaiser you mentioned that this lead to segfaults in some tests. Did you notice if that was reproducible? If this causes problems let's not merge it, but if things work well this is really helpful for seeing where failures happen.
=> Enable static symbols for stacktraces in CircleCI config

cmake/tests/cxx17_inline_constexpr_variable.cpp, libs/config/include/hpx/config/constexpr.hpp, libs/functional/CMakeLists.txt, libs/functional/include/hpx/functional/tag_invoke.hpp, libs/functional/tests/unit/CMakeLists.txt, libs/functional/tests/unit/tag_invoke.cpp
This PR introduces `hpx::functional::tag_invoke` which is an implementation
of https://wg21.link/p1895. This is needed to implement https://wg21.link/p0443.
=> Implementing `hpx::functional::tag_invoke`

hpx/runtime/thread_pool_helpers.hpp, libs/schedulers/include/hpx/schedulers/local_priority_queue_scheduler.hpp, libs/schedulers/include/hpx/schedulers/local_queue_scheduler.hpp, libs/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp, libs/thread_pools/include/hpx/thread_pools/scheduled_thread_pool.hpp, libs/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp, libs/threading_base/include/hpx/threading_base/scheduler_base.hpp, libs/threading_base/include/hpx/threading_base/thread_pool_base.hpp, libs/threadmanager/include/hpx/threadmanager.hpp, libs/threadmanager/src/threadmanager.cpp, src/runtime/thread_pool_helpers.cpp
Fixes #4599
The new API function is `hpx::get_idle_core_count()`, it will return the number of cores that have no threads (staged or pending) waiting in their queues.
=> Adding an API function that exposes the number of idle cores

libs/synchronization/CMakeLists.txt, libs/synchronization/include/hpx/latch.hpp, libs/synchronization/include/hpx/synchronization/latch.hpp, libs/synchronization/tests/unit/CMakeLists.txt, libs/synchronization/tests/unit/latch_cpp20.cpp, libs/threading/CMakeLists.txt, libs/threading/include/hpx/thread.hpp
- adding `hpx/latch.hpp` that imports `hpx::lcos::local::latch` into namespace hpx
- flyby: adding `hpx/thread.hpp` for compatibility
=> Adding C++20 latch API

libs/algorithms/include/hpx/parallel/algorithms/detail/set_operation.hpp, libs/algorithms/include/hpx/parallel/algorithms/partition.hpp, libs/algorithms/include/hpx/parallel/algorithms/sort.hpp, libs/algorithms/include/hpx/parallel/util/detail/chunk_size.hpp, libs/execution/include/hpx/execution/executors/execution_fwd.hpp, libs/execution/include/hpx/execution/executors/execution_information.hpp, libs/execution/include/hpx/execution/executors/execution_information_fwd.hpp, libs/execution/include/hpx/execution/executors/execution_parameters.hpp, libs/execution/include/hpx/execution/executors/execution_parameters_fwd.hpp, libs/execution/tests/unit/CMakeLists.txt, libs/execution/tests/unit/executor_parameters_dispatching.cpp, libs/thread_executors/include/hpx/thread_executors/thread_execution_information.hpp, libs/thread_executors/tests/unit/resource_manager.cpp
- This unifies the processing of all execution parameters customization
points such that all invocations are dispatched through the executor
first before handled by the parameters object (if the executor does not
implement the functionality)
- This also consolidates the customization points `count_processing_units`
and `processing_units_count` by removing the former as it was never used
anywhere. This is a slightly breaking change, which shouldn't have any
impact on existing code.
=> Unify execution parameters customization points

tools/pre-commit
The use of clang-format and cmake-format in HPX makes it
tedious to check that formatting of files is correct prior to commits;
this hook can be installed to run checks on files that are about to be
committed.
To install the hook, copy the file to your git hooks as follows
```
cp tools/pre-commit .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
```
If all files are ok, then the commit will happen as normal,
but if any file fails the clang/cmake format checks, then the commit
will be aborted and a message such as the following will be displayed
(see image above)
```
clang-format -style=file -i libs/compute_cuda/include/hpx/compute/cuda.hpp
clang-format -style=file -i libs/cuda_support/include/hpx/cuda_support/target.hpp
cmake-format -i libs/compute_cuda/CMakeLists.txt
cmake-format -i …
```
=> Add a pre-commit hook script to check file formatting

libs/synchronization/CMakeLists.txt, libs/synchronization/include/hpx/condition_variable.hpp, libs/synchronization/include/hpx/semaphore.hpp, libs/synchronization/include/hpx/stop_token.hpp, libs/synchronization/include/hpx/synchronization/counting_semaphore.hpp, libs/synchronization/include/hpx/synchronization/detail/counting_semaphore.hpp, libs/synchronization/tests/unit/CMakeLists.txt, libs/synchronization/tests/unit/binary_semaphore_cpp20.cpp, libs/synchronization/tests/unit/counting_semaphore_cpp20.cpp, tests/unit/component/action_invoke_no_more_than.hpp
- adding `hpx::binary_semaphore`
- adding `hpx/counting_semaphore.hpp` that imports it into namespace hpx
- flyby: adding `hpx/condition_variable.hpp` and `hpx/stop_token.hpp` headers for
conformance. This also imports `lcos::local::conditional_variable`
into namespace hpx
=> Adding C++20 counting semaphore API

libs/resource_partitioner/CMakeLists.txt, libs/resource_partitioner/src/detail_partitioner.cpp, libs/threading_base/include/hpx/threading_base/scheduler_base.hpp, src/hpx_init.cpp
- Checking MPI environment before initializing the runtime
- flyby: handling stack size problem for newly created threads
=> Fixing support for mpirun (and similar)

libs/basic_execution/include/hpx/basic_execution/register_locks.hpp
=> Making sure declarations match definitions in register_locks implementation

hpx/hpx_init_impl.hpp, hpx/hpx_start_impl.hpp
- this is a Windows specific change
This makes APEX usable on windows (to some minimal extend), relies on https://github.com/khuck/xpress-apex/pull/122 being merged.
=> Making sure APEX is linked into every application, if needed

hpx/util/serialize_exception.hpp, libs/serialization/CMakeLists.txt, libs/serialization/include/hpx/serialization/exception_ptr.hpp, libs/serialization/src/exception_ptr.cpp, src/hpx_init.cpp, src/util/serialize_exception.cpp
This takes care of the circular dependency between the runtime and futures/exceptions, but there *must* be a better way of handling this.
=> Add handler for serializing custom exceptions

libs/errors/src/exception.cpp
Probably fixes #4669. The builder to look out for is the GH actions "Linux (Release, FetchContent)" (because of the relase build, not the fetchcontent part...).
=> Explicitly instantiate get_exception

libs/pack_traversal/include/hpx/pack_traversal/traits/pack_traversal_rebind_container.hpp
Fixes
```
2020-05-27T14:05:31.6837782Z D:\a\hpx\hpx\libs\pack_traversal\include\hpx\pack_traversal\traits\pack_traversal_rebind_container.hpp(68,5): error C2499: 'hpx::traits::pack_traversal_rebind_container<NewType,Container,void>': a class cannot be its own base class [D:\a\hpx\hpx\build\libs\resource_partitioner\examples\guided_pool_test.vcxproj]
2020-05-27T14:05:31.6842176Z           with
2020-05-27T14:05:31.6843495Z           [
2020-05-27T14:05:31.6845687Z               NewType=char,
2020-05-27T14:05:31.6849490Z               Container=std::string
2020-05-27T14:05:31.6851492Z           ]
2020-05-27T14:05:31.6855935Z D:\a\hpx\hpx\libs\pack_traversal\include\hpx\pack_traversal\detail\pack_traversal_impl.hpp(340): message : see reference to class template instantiation …
```
=> Fix compilation of pack_traversal_rebind_container.hpp

libs/functional/tests/unit/tag_invoke.cpp, libs/futures/tests/regressions/CMakeLists.txt, libs/futures/tests/regressions/future_hang_on_get_629.cpp, libs/futures/tests/regressions/future_hang_on_then_629.cpp, libs/futures/tests/regressions/future_hang_on_wait_with_callback_629.cpp, libs/synchronization/tests/unit/barrier_cpp20.cpp, libs/synchronization/tests/unit/latch_cpp20.cpp, libs/threading/tests/unit/condition_variable2.cpp, libs/threading_base/include/hpx/threading_base/print.hpp, libs/threading_base/src/execution_agent.cpp
Fixes small things that broke while pycicle was down. I think I fixed all that were reported directly by pycicle but I may have missed other things that were broken but didn't show up in the logs. I'm enabling pycicle for all PRs now to see what's missing.
Flyby: reformat some command line options in the futures module.
=> Miscellaneous compilation fixes

libs/collectives/include/hpx/collectives/detail/communicator.hpp, libs/collectives/src/detail/barrier_node.cpp, libs/performance_counters/src/counters.cpp, src/runtime/agas/addressing_service.cpp
Fixes #4675 and probably fixes #4620 (I could not reproduce the error but I've added the header that should fix it).
@biddisco would you mind giving this a try to verify that things are ok for you too?
=> Add missing hpx/execution.hpp includes for future::then

libs/collectives/CMakeLists.txt, libs/collectives/include/hpx/collectives/all_reduce.hpp, libs/collectives/include/hpx/collectives/broadcast.hpp, libs/collectives/include/hpx/collectives/detail/communicator.hpp, libs/collectives/include/hpx/collectives/gather.hpp, libs/collectives/include/hpx/collectives/scatter.hpp, libs/collectives/tests/regressions/multiple_gather_ops_2001.cpp, libs/collectives/tests/unit/CMakeLists.txt, libs/collectives/tests/unit/gather.cpp, libs/collectives/tests/unit/scatter.cpp, libs/local_lcos/include/hpx/local_lcos/and_gate.hpp
- ~~adding hpx::gather API combining gather_here/gather_there~~ (adding this was a mistake as it did turn gather into an equivalent for all_gather)
- adding missing gather test
- fixing various problems and inconsistencies with broadcast
=> Adding scatter_to/scatter_from collective operations

libs/schedulers/include/hpx/schedulers/thread_queue.hpp, libs/schedulers/include/hpx/schedulers/thread_queue_mc.hpp, libs/threading_base/include/hpx/threading_base/scheduler_base.hpp, libs/threading_base/src/thread_data.cpp, libs/threading_base/tests/regressions/CMakeLists.txt, libs/threading_base/tests/regressions/thread_stacksize_current.cpp
Fixes #4648. The stack size enum is now updated from `thread_stacksize_current` to an actual stack size when a thread is added.
=> Fix thread stack size handling

cmake/templates/conf.py.in, docs/sphinx/manual/hpx_runtime_and_resources.rst, libs/affinity/docs/index.rst, libs/asio/docs/index.rst, libs/async_base/docs/index.rst, libs/command_line_handling/docs/index.rst, libs/config_registry/docs/index.rst, libs/distributed_executors/docs/index.rst, libs/executors/docs/index.rst, libs/futures/docs/index.rst, libs/io_service/docs/index.rst, libs/itt_notify/docs/index.rst, libs/local_async/docs/index.rst, libs/mpi/docs/index.rst, libs/mpi_base/docs/index.rst, libs/performance_counters/docs/index.rst, libs/prefix/docs/index.rst, libs/resource_partitioner/docs/index.rst, libs/runtime_configuration/docs/index.rst, libs/schedulers/docs/index.rst, libs/static_reinit/docs/index.rst, libs/thread_executors/docs/index.rst, libs/thread_pools/docs/index.rst, libs/threading/docs/index.rst, libs/threadmanager/docs/index.rst, libs/timed_execution/docs/index.rst, libs/version/docs/index.rst
Fixes #4571. Apologies for the brief descriptions for some modules. However, I don't think it's worth spending a lot of time on some of these modules that are purely for internal use. Adding a one- or two-sentence description is more about having a slightly friendlier entry to modules for potential developers than `TODO: Document`... I think we'll learn over time if certain modules actually require more documentation.
=> Add short descriptions to modules missing documentation

libs/execution/include/hpx/execution/executors/execution.hpp, libs/executors/include/hpx/executors/apply.hpp
Two patches:
#p1
Use decltype(auto) for apply return type to fix cuda executor issue:
makes the `hpx::apply` dispatch match the `hpx::async` dispatch and allows the return type to be deduced by return from the executor instead of the function - which breaks when functions have things like cuda streams added by the executor
#p2 Allow apply to return a value:
Certain executors such as cuda, cublas, or networking, are able to
create asynchronous work without spawning a task and will usually return
a future, however the use of `apply` instead of `async` might be preferred
in certain cases to allow multiple kernels (for example) to be launched
on a stream (execution order guaranteed by the 3rd party library).
In these cases, the return value of the function invocation should
be passed back to …
=> Changes to apply needed for cuda/cublas executor

libs/compute/include/hpx/compute/host/block_executor.hpp, libs/execution/include/hpx/execution/detail/post_policy_dispatch.hpp, libs/execution/include/hpx/execution/executors/thread_pool_executor.hpp, libs/executors/include/hpx/executors/restricted_thread_pool_executor.hpp, libs/futures/include/hpx/futures/futures_factory.hpp
*How to make your PRs look good: Introduce a performance regression without benchmarking (#4301), followed by another PR which improves performance a bit (#4536).*
The improvements in #4536 were real, but ignore that #4301 introduced a regression. The regression was caused by the `block_executor` previously relying on thread executors which eagerly created threads for bulk execution (`run_now = true`), whereas the new underlying executor `restricted_thread_pool_executor` only creates task descriptions. In addition the `restricted_thread_pool_executor` did hierarchical spawning. Both of these seem to have caused the performance regression (fixing just one of them is not enough). This is based on the stream benchmark and @m-diers observations on his application.
In this PR I've extended the …
=> Fix performance regression in block_executor

docs/sphinx/manual/optimizing_hpx_applications.rst
Updates to documentation 
Added hyperlink
Changed name of Example section to avoid confusion, as "Two Simple Examples" could be misread as giving examples for only simple counter names. 
Grammar edits
=> Doc updates optimizing hpx applications

tools/pre-commit
cmake-format doesn't accept a file piped from stdin
so write a temp file with formatted version and compare to
original to check if changes are needed,
Watch out for paths as hook runs at root of repo.
=> Fix incorrect behaviour of cmake-format check

libs/collectives/CMakeLists.txt, libs/collectives/include/hpx/collectives/all_reduce.hpp, libs/collectives/include/hpx/collectives/all_to_all.hpp, libs/collectives/include/hpx/collectives/broadcast.hpp, libs/collectives/include/hpx/collectives/detail/communicator.hpp, libs/collectives/include/hpx/collectives/force_linking.hpp, libs/collectives/include/hpx/collectives/gather.hpp, libs/collectives/include/hpx/collectives/scatter.hpp, libs/collectives/src/detail/communicator.cpp, libs/collectives/src/force_linking.cpp, libs/collectives/tests/unit/all_reduce.cpp, libs/collectives/tests/unit/all_to_all.cpp, libs/collectives/tests/unit/broadcast.cpp, libs/collectives/tests/unit/gather.cpp, libs/collectives/tests/unit/scatter.cpp, libs/thread_support/include/hpx/thread_support/assert_owns_lock.hpp
- This allows to get rid of the macros for `all_reduce`, `all_to_all`, `broadcast`, `gather`, and `scatter`
Relies on #4676 (only the last commit is significant)
=> Typeless communicator

components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_impl.hpp, components/iostreams/src/standard_streams.cpp, hpx/runtime/components/default_distribution_policy.hpp, libs/collectives/include/hpx/collectives/broadcast_direct.hpp
Fixes #4679. @weilewei would you mind trying again?
I'd like to prioritize getting #4696 first in though (it will otherwise keep conflicting or have a few headers missing). I'll update this one to use `hpx/modules/execution.hpp` after that.
=> Fix missing includes for future::then specializations

libs/collectives/CMakeLists.txt, libs/collectives/include/hpx/collectives/all_gather.hpp, libs/collectives/include/hpx/collectives/all_to_all.hpp, libs/collectives/include/hpx/collectives/gather.hpp, libs/collectives/tests/unit/CMakeLists.txt, libs/collectives/tests/unit/all_gather.cpp, libs/collectives/tests/unit/all_to_all.cpp
This essentially renames the existing `all_to_all` to `all_gather` and adds a proper implementation of `all_to_all`.
This relies on #4678 (only the last commit is significant).
=> Adding all_gather and fixing all_to_all 

hpx/runtime/components/server/migration_support.hpp
- this makes sure an assertion does not trigger a locking error
- additional check to avoid unpinning migrated objects
=> Attempt to fixing migration tests

.circleci/config.yml, CMakeLists.txt, examples/heartbeat/heartbeat.cpp, examples/quickstart/init_globally.cpp, examples/throttle/throttle_client.cpp, hpx/runtime/agas/addressing_service.hpp, libs/command_line_handling/include/hpx/command_line_handling/command_line_handling.hpp, libs/command_line_handling/include/hpx/command_line_handling/parse_command_line.hpp, libs/command_line_handling/src/command_line_handling.cpp, libs/command_line_handling/src/parse_command_line.cpp, libs/init_runtime/include/hpx/hpx_init.hpp, libs/init_runtime/include/hpx/hpx_init_params.hpp, libs/init_runtime/include/hpx/hpx_start.hpp, libs/init_runtime/src/hpx_init.cpp, libs/init_runtime/tests/unit/CMakeLists.txt, libs/init_runtime/tests/unit/runtime_type.cpp, libs/mpi_base/src/mpi_environment.cpp, libs/runtime_configuration/include/hpx/runtime_configuration/runtime_mode.hpp, libs/runtime_configuration/src/runtime_mode.cpp, src/runtime_distributed.cpp, tests/unit/component/launched_process.cpp, wrap/src/hpx_wrap.cpp
Note: this builds on #4606. Only the last commit belongs to this PR.
This adds a `runtime_type` enum that can be passed in the `init_params` struct, to choose which runtime to start. If the distributed runtime isn't enabled and it's requested an exception will be thrown during init. The default is to use the distributed runtime if available and otherwise the local one.
=> Runtime type

hpx/runtime/threads/thread_pool_suspension_helpers.hpp, libs/basic_execution/CMakeLists.txt, libs/basic_execution/include/hpx/basic_execution/register_locks.hpp, libs/errors/CMakeLists.txt, libs/errors/include/hpx/errors/exception.hpp, libs/execution/include/hpx/execution/detail/execution_parameter_callbacks.hpp, libs/executors/include/hpx/executors/exception_list.hpp, libs/futures/include/hpx/futures/detail/future_data.hpp, libs/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp, libs/serialization/include/hpx/serialization/exception_ptr.hpp, libs/testing/CMakeLists.txt, libs/testing/include/hpx/modules/testing.hpp, libs/threading/include/hpx/threading/thread.hpp, libs/threading_base/include/hpx/threading_base/external_timer.hpp, libs/threading_base/include/hpx/threading_base/register_thread.hpp, libs/threading_base/include/hpx/threading_base/scheduler_base.hpp, plugins/parcelport/libfabric/libfabric_controller.hpp, plugins/parcelport/libfabric/pinned_memory_vector.hpp, plugins/parcelport/verbs/pinned_memory_vector.hpp, plugins/parcelport/verbs/rdma/rdma_controller.hpp, src/runtime/threads/thread_pool_suspension_helpers.cpp
Fixes #4672. I've only replaced uses of `std::function` in the main library. I've left `std::function` in tests, examples, and the `program_options` module.
=> Use hpx::function_nonser instead of std::function internally

hpx/runtime/parcelset/parcelport_impl.hpp, libs/algorithms/CMakeLists.txt, libs/algorithms/include/hpx/parallel/util/detail/handle_exception_termination_handler.hpp, libs/algorithms/include/hpx/parallel/util/detail/handle_local_exceptions.hpp, libs/algorithms/include/hpx/parallel/util/detail/handle_remote_exceptions.hpp, libs/algorithms/src/handle_exception_termination_handler.cpp, libs/coroutines/include/hpx/coroutines/detail/context_posix.hpp, libs/executors/src/exception_list_callbacks.cpp, libs/init_runtime/CMakeLists.txt, libs/init_runtime/src/hpx_init.cpp, plugins/parcelport/libfabric/fabric_error.hpp, plugins/parcelport/libfabric/libfabric_controller.hpp, plugins/parcelport/libfabric/receiver.cpp, plugins/parcelport/verbs/parcelport_verbs.cpp, plugins/parcelport/verbs/rdma/rdma_controller.cpp, plugins/parcelport/verbs/rdma/verbs_completion_queue.hpp, plugins/parcelport/verbs/rdma/verbs_endpoint.hpp, tools/inspect/include_check.cpp
I thought this was a circular dependency that `cpp-dependencies` did not see. It turns out it was fine, since the `init_runtime` module did not depend on algorithms. In any case, this gets rid of the dependency from `algorithms` to `init_runtime` and allows us to have `algorithms` in a separate library that does not depend on the runtime.
=> Add termination handler for parallel algorithms

libs/algorithms/include_compatibility/hpx/algorithms.hpp, libs/cache/include_compatibility/hpx/cache.hpp, libs/collectives/include_compatibility/hpx/collectives.hpp, libs/hardware/include_compatibility/hpx/hardware.hpp, libs/local_lcos/include_compatibility/hpx/local_lcos.hpp, libs/preprocessor/include_compatibility/hpx/preprocessor.hpp, libs/segmented_algorithms/include_compatibility/hpx/segmented_algorithms.hpp
Fixes #4720. Leaves out `hpx/execution.hpp` as that'll get a proper replacement.
=> Add more compatibility headers for deprecated module headers

CMakeLists.txt, cmake/HPX_AddModule.cmake, libs/thread_executors/CMakeLists.txt, libs/thread_executors/include/hpx/thread_executors/detail/on_self_reset.hpp, libs/thread_executors/src/embedded_thread_pool_executors.cpp, libs/thread_executors/src/this_thread_executors.cpp, src/CMakeLists.txt, src/runtime/agas/server/route.cpp, src/runtime/parcelset/detail/parcel_route_handler.cpp
This adds a CMake option to use CMake's unity build functionality from 3.16 onwards (https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html). Essentially this batches compilation of source files to save a bit (or a lot) of header parsing. Internally CMake batches up to 8 (default) source files into one file that looks roughly like this:
```
#include "/path/to/source1.cpp"
#include "/path/to/source2.cpp"
#include "/path/to/source3.cpp"
...
```
and compiles that instead. The downside of this is that files that are batched together can't have duplicate static definitions. For `on_self_reset` in the `thread_executors` module I just lifted the definitions out into a separate header file. If needed the batching can be turned off for specific source files as well. This can also lead to …
=> Add experimental unity build option to CMake configuration

components/containers/partitioned_vector/tests/regressions/CMakeLists.txt, components/containers/partitioned_vector/tests/unit/CMakeLists.txt, components/containers/unordered/include/hpx/components/containers/unordered/unordered_map.hpp, components/containers/unordered/tests/regressions/CMakeLists.txt, components/containers/unordered/tests/regressions/unordered_compilation_4685.cpp, components/containers/unordered/tests/unit/CMakeLists.txt
- flyby: fixing cmake FOLDERs for container component tests
Fixes #4685
@nickrobison-usds please check whether this solves your issue
=> Fixing compilation problems with unordered map

libs/threading_base/tests/regressions/thread_stacksize_current.cpp
Finally fixes #4648. It was just a question of some schedulers being disabled on the particular builder, and the test not accounting for that.
=> Conditionally test schedulers in thread_stacksize_current test

.circleci/config.yml
Now that https://github.com/STEllAR-GROUP/docker_build_env/pull/25 is merged, this PR generates coverage reports and uploads them to codecov.io. I believe codecov will magically accept reports without any other config. 
On my fork of hpx circle ci timed out, so we have to see here if it works.
=> Create coverage reports and upload them to codecov.io

.circleci/config.yml
Reverts STEllAR-GROUP/hpx#4748
`lcov` causes timeouts which make CI fail.
=> Revert "Create coverage reports and upload them to codecov.io"

cmake/templates/hpxrun.py.in
hpxrun.py is a useful command, but does not allow running on remote localities.
specify -n nodes to allow running on remote locations for tcp parcelport.
=> Allow hpxrun.py to run on remote nodes with tcp parcelport

examples/quickstart/init_globally.cpp
Or would someone prefer to explicitly use `runtime_mode::console` when `HPX_HAVE_DISTRIBUTED_RUNTIME` is defined, and `runtime_mode::local` otherwise?
=> Fix init_globally example after runtime mode changes

components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_component_decl.hpp, components/performance_counters/papi/src/papi_startup.cpp, components/performance_counters/papi/src/server/papi.cpp, components/performance_counters/papi/src/util/papi.cpp
Fixes #4755 and the `clang-oldest` build. The clang fix is for what seems to be this, or a related bug: https://bugs.llvm.org/show_bug.cgi?id=39649, with the difference it's not a defaulted move constructor that I had to change, just the default constructor. I've not verified if the bug is there still in clang 6. It's not a problem on gcc 7, gcc 10, or clang 9.
=> Fix compilation issues

.circleci/config.yml
The regexes didn't quite work after the renaming in #4740.
=> Fix running and building of execution module tests on CircleCI

libs/futures/CMakeLists.txt, libs/futures/include/hpx/futures/detail/future_data.hpp
- flyby: add missing headers to CMakeLists.txt
=> Reduce memory requirements for our main shared state

.cmake-format.py, cmake/HPX_AddModule.cmake, cmake/HPX_Option.cmake, cmake/HPX_PrintSummary.cmake, cmake/installed_hpx.cmake, libs/datastructures/CMakeLists.txt, libs/serialization/CMakeLists.txt
Fixes #4758 
As it turns out, CMake profiling reports only data for the configure step (not for the generation step). For this reason, the change proposed here improves only the configure step by reducing the amount of time required to create the configuration summary for each module. See here for the new trace:
which demonstrates the reduction nicely (if compared to #4758).
Overall timing: the configure step went down from 49s to 28s for me.
=> Storing hpx_options in global property to speed up summary report

CMakeLists.txt, cmake/HPX_AddCompileTest.cmake, cmake/HPX_AddTest.cmake, examples/transpose/CMakeLists.txt, libs/compute/tests/regressions/CMakeLists.txt, libs/futures/tests/regressions/future_timed_wait_1025.cpp, libs/synchronization/tests/performance/channel_mpmc_throughput.cpp, libs/synchronization/tests/performance/channel_mpsc_throughput.cpp, libs/synchronization/tests/performance/channel_spsc_throughput.cpp, tests/unit/component/CMakeLists.txt, tests/unit/resource/suspend_pool.cpp
Forces some tests to run serially if `ctest` is given the `-j` option.
I've set all distributed tests, benchmarks, and tests that request `all` or `cores` threads. I've been a bit conservative and set the compile tests to run serially as well as I've seen problems before trying to build multiple header tests concurrently.
This would allow us to run tests much more quickly on hardware that has spare resources (most tests run with 1 or 4 threads).
@haampie I'm currently running the tests to see if there are any unexpected results. The option does work as advertised, I just have to make sure I haven't missed any other tests that require running serially.
=> Force some tests to run serially

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx20_disable_sized_sentinel_for.cpp, cmake/tests/cxx20_std_disable_sized_sentinel_for.cpp, libs/algorithms/include/hpx/parallel/algorithms/detail/distance.hpp, libs/algorithms/tests/unit/algorithms/CMakeLists.txt, libs/algorithms/tests/unit/algorithms/distance.cpp, libs/algorithms/tests/unit/algorithms/iter_sent.hpp, libs/iterator_support/include/hpx/iterator_support/traits/is_sentinel_for.hpp, libs/iterator_support/tests/unit/CMakeLists.txt, libs/iterator_support/tests/unit/is_sized_sentinel_for.cpp
- Added `sized_sentinel_for` on `is_sentinel_for.hpp`
- Added the `disable_sized_sentinel_for` feature check
- Adjusted `hpx::parallel::v1::detail::distance()` in order to decide for the type dispatching according to `sized_sentinel_for`
- Added test for the adapted `distance` implementation
=> Add sized_sentinel_for concept and make distance dispatch according to that

hpx/runtime/components/server/runtime_support.hpp, libs/collectives/tests/unit/CMakeLists.txt, libs/collectives/tests/unit/all_gather.cpp, libs/collectives/tests/unit/all_reduce.cpp, libs/collectives/tests/unit/all_to_all.cpp, libs/collectives/tests/unit/broadcast.cpp, libs/collectives/tests/unit/gather.cpp, libs/collectives/tests/unit/scatter.cpp, src/runtime/components/server/runtime_support_server.cpp
Fixes #4770 (at least for core, have not yet built the rest). Pycicle's `clang-oldest` now builds with `HPX_HAVE_NETWORKING=OFF` (`gcc-newest` has `HPX_WITH_DISTRIBUTED_RUNTIME=OFF` in addition, the rest are with full networking).
=> Fix compilation with HPX_WITH_NETWORKING=OFF

cmake/HPX_AddCompileTest.cmake
I did not see any test failures from running those tests in parallel
=> Make header tests parallel again

libs/collectives/src/barrier.cpp, libs/collectives/src/detail/barrier_node.cpp, libs/collectives/tests/unit/barrier.cpp
- flyby: making sure barrier is not released prematurely when used in
asynchronous mode
=> Fixing barrier test

docs/sphinx/manual/starting_the_hpx_runtime.rst
Many functions other than just hpx::init/start/stop can be called in main and outside the HPX runtime. Thanks to @finkandreas for pointing this out.
=> Remove outdated comment about hpx::stop in documentation

libs/runtime_local/src/runtime_handlers.cpp, src/runtime/agas/interface.cpp, src/runtime_distributed.cpp
This was triggered by passing `--hpx:debug-timing-log` to any application which would lead to trying to print runtime information before the distributed runtime was completely set up. There were three separate, but related bugs:
- Assertion handling didn't detect if an assertion fails while handling an assertion.
- The distributed runtime TSS pointer wasn't set up as early as possible in the distributed runtime constructor.
- `get_locality_id` was checking if the local runtime pointer was available, whereas it needs the distributed runtime pointer.
Maybe, just maybe, we'll have fewer hangs with this...
=> Fix hangs during assertion handling and distributed runtime construction

libs/algorithms/include/hpx/parallel/algorithms/reduce.hpp
I replaced `enable_if` with the `HPX_CONCEPT_REQUIRES_` macro and added `is_sentinel_for` trait (except for the segmented algorithm part). All pre-existing tests seem to pass.
=> Replace enable_if with HPX_CONCEPT_REQUIRES_ and add is_sentinel_for constraint

cmake/HPX_SetupCUDA.cmake, libs/async_cuda/CMakeLists.txt
Since PR #4385  got merged, HPX master could not be built with g++ and HPX_WITH_CUDA=ON as g++ was not able to find the cuda_runtime.h header file during the compilation.
This PR fixes this issue by simply adding the CUDA argument to the appropriate add_hpx_module call.
=> Add CUDA flag to async_cuda CMakeLists

tools/pre-commit
Just for ease of use - if you commit from a subdir instead of the root dir of the git repo ...
=> Display relative paths in hook to make cut'n'paste easier

libs/algorithms/include/hpx/parallel/datapar/iterator_helpers.hpp, libs/algorithms/include/hpx/parallel/datapar/loop.hpp, libs/algorithms/include/hpx/parallel/datapar/zip_iterator.hpp, libs/execution/include/hpx/execution/traits/vector_pack_alignment_size.hpp, libs/execution/include/hpx/execution/traits/vector_pack_count_bits.hpp, libs/execution/include/hpx/execution/traits/vector_pack_load_store.hpp, libs/execution/include/hpx/execution/traits/vector_pack_type.hpp
Some of the datapar header include paths are wrong (```hpx/execution/parallel/traits/...``` instead of ```hpx/execution/traits/...```) causing issues during the compilation of Octo-Tiger using the latest HPX master.
This PR fixes this issue!
=> Fix datapar header paths

libs/functional/include/hpx/functional/deferred_call.hpp, libs/functional/include/hpx/functional/invoke_fused.hpp, libs/functional/include/hpx/functional/invoke_result.hpp, libs/functional/include/hpx/functional/traits/is_invocable.hpp
Having the deprecation attribute on the base template lead to warnings when specializing the template, even though the specializations were not used anywhere. It seems like clang was fine with the old behaviour, but gcc does not want the deprecation attribute on the base template.
=> Move deprecation warnings from base template to template specializations for result_of etc. structs

libs/runtime_local/include/hpx/runtime_local/runtime_local.hpp, libs/runtime_local/src/runtime_local.cpp
Jut a flyby fix that was causing build errors for me
=> Fix a wrong #ifdef for IO/TIMER pools causing build errors

libs/algorithms/include/hpx/parallel/algorithms/for_each.hpp, libs/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/algorithms/tests/unit/container_algorithms/foreach_adapt.cpp, libs/algorithms/tests/unit/container_algorithms/iter_sent.hpp, libs/segmented_algorithms/include/hpx/parallel/segmented_algorithms/for_each.hpp
Adapt for_each in order to support for the begin and end iterators to be of different type
=> Foreach adapt

cmake/HPX_SetupBoostFilesystem.cmake, cmake/HPX_SetupBoostProgramOptions.cmake, tests/unit/build/fetchcontent/CMakeLists.txt
Attempt to fix #4816. The GitHub actions fetchcontent build should test this now. Let's see what it says. I have not tested the full build locally.
=> Allow finding Boost components before finding HPX

cmake/HPX_SetupMPI.cmake
Fixes #4286
`MPI_CXX_COMPILE_FLAGS` is a string and needs to be separated in order to be interpreted as a list of options.
=> Making sure MPI_CXX_COMPILE_FLAGS is interpreted as a sequence  of options

.github/workflows/windows_debug.yml, .github/workflows/windows_release.yml, cmake/HPX_SetupTarget.cmake, examples/gtest_emulation/CMakeLists.txt, examples/gtest_emulation/hpx_main_ext_main.cpp, examples/gtest_emulation/static_main.cpp, examples/hello_world_component/CMakeLists.txt, src/CMakeLists.txt, tests/unit/build/CMakeLists.txt
- Change the default hpx target not to include `wrap_main` as discussed in the last PMC meeting, the `HPX::wrap_main` target is exposed to the user in case it's needed
- Add a gtest unit test to check we don't break anything during our changes to the cmake targets
=> Change cmake targets

examples/1d_stencil/1d_stencil_7.cpp, hpx/runtime/naming/name.hpp, hpx/runtime/serialization/detail/preprocess_futures.hpp, hpx/runtime/serialization/detail/preprocess_gid_types.hpp, src/runtime/naming/name.cpp, src/runtime/parcelset/detail/parcel_await.cpp, src/runtime/parcelset/parcel.cpp
Fixes #4732
Fixes #4746
The two mentioned issues were connected. The cause for the memory leak (and as a side effect for the assertions) was that parcel preprocessing is done on a parcel-by-parcel basis, while the actual serialization may store several parcels using the same serialization archive. This caused (managed) `id_types` that were part of two or more parcels to have their credits split two or more times but subsequently they were serialized only once (because of pointer tracking). As a result the credits were leaked that were supposed to be sent over the wire by the second (or subsequent) instance of the same `id_type`.
This patch fixes this by giving back to AGAS all credits that end up not being sent. 
This patch also fixes a possible race condition between handling the credit …
=> Fixing assertion in split_gids and memory leaks in 1d_stencil_7

docs/sphinx/manual/creating_hpx_projects.rst, docs/sphinx/manual/starting_the_hpx_runtime.rst, docs/sphinx/quickstart.rst
Fixes #4619. I didn't mention anything about the fancier variations of linking with e.g. `gtest_main` since it's not portable. If it's going to be something more people want to do we can make it a bit more offical, and describe it in detail, but for now I'd like to not encourage more people to do so than the ones who have already tried to do so.
=> Update documentation on using HPX::wrap_main

libs/algorithms/include/hpx/parallel/algorithms/copy.hpp
This was accidentally left in #4821.
=> Restore compatibility for old (now deprecated) copy algorithms

libs/functional/include/hpx/type_traits.hpp
Fixes a ton of warnings for MSVC. 
This shouldn't be imported as an API into namespace hpx to begin with as it is deprecated anyways.
=> Remove `using util::result_of` from namespace hpx

libs/coroutines/include/hpx/coroutines/detail/coroutine_impl.hpp, libs/coroutines/src/detail/coroutine_impl.cpp, libs/coroutines/tests/regressions/CMakeLists.txt, libs/coroutines/tests/regressions/coroutine_function_destructor_yield_4800.cpp, libs/functional/include_compatibility/hpx/functional/traits/is_callable.hpp
Fixes #4800.
The problem was the coroutine thread function destructor yielding (because of user code). Since the thread function was reset after the thread id, stack, local self reference etc. the bookkeeping got somewhat messed up (the thread result was set to `pending` by the yield after the thread result had been set to `terminated`). I think this is a reasonable thing to allow, but it's not 100% clear to me if this can be avoided in dataflow or in user code.
I've added a test that reproduces the problem. The first variant always fails before the fixes here. The second uses dataflow and fails occasionally. This is the closest I could get to the original code while still triggering the assertion. I've also added `hpx::future::then` and `hpx::apply` tests that do not trigger the …
=> Allow thread function destructors to yield

libs/algorithms/CMakeLists.txt, libs/algorithms/include/hpx/numeric.hpp, libs/algorithms/include/hpx/parallel/algorithms/copy.hpp, libs/algorithms/include/hpx/parallel/algorithms/reduce.hpp, libs/algorithms/include/hpx/parallel/container_algorithms.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/copy.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/reduce.hpp, libs/algorithms/include/hpx/parallel/container_numeric.hpp, libs/algorithms/tests/performance/transform_reduce_scaling.cpp, libs/algorithms/tests/regressions/reduce_3641.cpp, libs/algorithms/tests/unit/algorithms/reduce_.cpp, libs/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/algorithms/tests/unit/container_algorithms/reduce_range.cpp, libs/collectives/include/hpx/collectives/all_reduce.hpp, libs/include/include/hpx/include/parallel_reduce.hpp, libs/segmented_algorithms/include/hpx/parallel/segmented_algorithms/reduce.hpp, libs/segmented_algorithms/tests/unit/partitioned_vector_reduce.cpp
- also add hpx::ranges::reduce implementations
- deprecate hpx::parallel::reduce
This makes all `reduce` variations fully conforming to C++20
=> Adding CPOs for hpx::reduce

CMakeLists.txt, components/performance_counters/papi/src/server/papi.cpp, components/performance_counters/papi/tests/regressions/CMakeLists.txt, libs/runtime_configuration/src/runtime_configuration.cpp, libs/runtime_local/include/hpx/runtime_local/thread_mapper.hpp, libs/runtime_local/src/thread_mapper.cpp
Fixes #4820. It seems like PAPI was not happy with the changes to thread ids in #4693. From my testing the only thread ids that PAPI accepts are the ones from the `gettid` syscall. This was (and is) Linux only, so I've also added a check that the PAPI counters can only be enabled on Linux (as far as I can tell they're definitely not available on Windows; other unixy platforms may support it but that would need testing by someone on those platforms).
Other changes:
- I've disabled one of the PAPI tests as it relies on the `PAPI_FP_INS` counter which doesn't seem to be available everywhere (I'm hoping the two other tests will be enough to make sure we don't completely break the PAPI counters).
- Ignoring a lock that's held if an error happens during counter construction.
- Use …
=> Fix PAPI counters

libs/async_cuda/src/cuda_future.cpp, libs/async_mpi/src/mpi_future.cpp, libs/thread_pools/include/hpx/thread_pools/scheduling_loop.hpp, libs/threading_base/include/hpx/threading_base/scheduler_base.hpp, libs/threading_base/include/hpx/threading_base/scheduler_mode.hpp, libs/threading_base/src/scheduler_base.cpp
The polling functions will hardly ever change during normal
operation, so to avoid taking a lock, we use an function pointer
for each of the polling functions for MPI and CUDA separately.
This means they can be set/cleared by any thread and when unchanged
no cache lines are affected and overheads are minimized.
=> Allow combined MPI and/or CUDA polling for futures

libs/async_mpi/tests/unit/CMakeLists.txt, libs/async_mpi/tests/unit/mpi_ring_async_executor.cpp
Fixes : Test problem on rostam hopefully
Flyby. Remove the MPI_Barrier that was annoying @hkaiser
=> Fix mpi_ring test in distributed mode by ensuring all ranks run hpx_main

CMakeLists.txt, cmake/HPX_SetupLibCDS.cmake, tests/performance/local/libcds_hazard_pointer_overhead.cpp
- make git repository and tag configurable
- place generated projects in 'Core' FOLDER
@weilewei please check
@aurianer could we add this to the release, still (doesn't have to go into RC1)?
=> Improve libCDS integration

docs/sphinx/manual/optimizing_hpx_applications.rst
The following changes have been made:
- The keyword for `cache/insertion` in `/agas/count/<cache_statistics>`
was wrong
- In `/parcelport/count/<connection_type>/<cache_statistics>`, a 
duplicate of `cache/misses` has been removed
- Correct weird formatting in `/agas/count/<cache_statistics>`
=> Correct typos in the documentation of the hpx performance counters

libs/algorithms/CMakeLists.txt, libs/algorithms/include/hpx/parallel/algorithms/all_any_none.hpp, libs/algorithms/include/hpx/parallel/algorithms/copy.hpp, libs/algorithms/include/hpx/parallel/algorithms/detail/accumulate.hpp, libs/algorithms/include/hpx/parallel/algorithms/detail/find.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/all_any_none.hpp, libs/algorithms/include/hpx/parallel/util/cancellation_token.hpp, libs/algorithms/tests/unit/algorithms/all_of.cpp, libs/algorithms/tests/unit/algorithms/any_of.cpp, libs/algorithms/tests/unit/algorithms/none_of.cpp, libs/algorithms/tests/unit/container_algorithms/all_of_range.cpp, libs/algorithms/tests/unit/container_algorithms/any_of_range.cpp, libs/algorithms/tests/unit/container_algorithms/none_of_range.cpp, libs/include/include/hpx/algorithm.hpp, libs/segmented_algorithms/include/hpx/parallel/segmented_algorithms/all_any_none.hpp, libs/segmented_algorithms/tests/unit/partitioned_vector_all_of1.cpp, libs/segmented_algorithms/tests/unit/partitioned_vector_all_of2.cpp, libs/segmented_algorithms/tests/unit/partitioned_vector_any_of1.cpp, libs/segmented_algorithms/tests/unit/partitioned_vector_any_of2.cpp, libs/segmented_algorithms/tests/unit/partitioned_vector_none1.cpp, libs/segmented_algorithms/tests/unit/partitioned_vector_none2.cpp
- this introduces CPOs for the algorithms
- flyby: make detail::accumulate constexpr
=> Adapting all_of, any_of, and none_of to C++20

libs/threading_base/src/register_thread.cpp, wrap/include/hpx/wrap_main.hpp, wrap/src/hpx_wrap.cpp
This PR adds a different runtime exception that will be thrown in scenarios where the user includes `hpx_main.hpp` but fails to link to `libhpx_wrap`. The error thrown is self sufficient and should let the user know that he/she is required to link to `libhpx_wrap`.
This fixes scenarios where the user faces thread registering exception that is orthogonal to the actual cause (see #4877 ).
Code 1:
```
#include <hpx/hpx_main.hpp>
#include <hpx/include/future.hpp>
#include <hpx/async_local/async.hpp>
int main(int argc, char * argv[])
{
hpx::future<int> f = hpx::async([]() { return 42; });
std::cout << f.get() << std::endl;
return 0;
}
```
Code 2:
```
#include <hpx/include/future.hpp>
#include <hpx/async_local/async.hpp>
int main(int argc, char * argv[])
{
hpx::future<int> f = hpx::async([]() { …
```
=> Adds different runtime exception when registering thread with the HPX runtime

examples/quickstart/CMakeLists.txt, examples/quickstart/disable_thread_stealing_executor.cpp
@scheherzade This should demonstrate what you asked for. The new executor disables thread stealing while the parallel algorithm using it executes.
=> Adding example demonstrating how to disable thread stealing during the execution of parallel algorithms

src/util/serialize_exception.cpp, tests/regressions/util/CMakeLists.txt, tests/regressions/util/serialize_exception_4886.cpp
Fixes #4886
@NK-Nikunj this should solve the issue you reported
@aurianer I think this should be part of the upcoming release as it fixes a serious problem with remote exception handling
=> Making sure remotely thrown (non-hpx) exceptions are properly marshaled back to invocation site

libs/algorithms/CMakeLists.txt, libs/algorithms/include/hpx/parallel/algorithms/mismatch.hpp, libs/algorithms/include/hpx/parallel/container_algorithms.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/equal.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/mismatch.hpp, libs/algorithms/include/hpx/parallel/util/compare_projected.hpp, libs/algorithms/include/hpx/parallel/util/projection_identity.hpp, libs/algorithms/include/hpx/parallel/util/result_types.hpp, libs/algorithms/tests/performance/benchmark_unique.cpp, libs/algorithms/tests/unit/algorithms/mismatch_binary.cpp, libs/algorithms/tests/unit/algorithms/unique_copy_tests.hpp, libs/algorithms/tests/unit/algorithms/unique_tests.hpp, libs/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/algorithms/tests/unit/container_algorithms/mismatch_binary_range.cpp, libs/algorithms/tests/unit/container_algorithms/mismatch_range.cpp, libs/algorithms/tests/unit/container_algorithms/unique_copy_range.cpp, libs/algorithms/tests/unit/container_algorithms/unique_range.cpp, libs/execution/include/hpx/execution/algorithms/detail/predicates.hpp, libs/include/include/hpx/algorithm.hpp, libs/include/include/hpx/include/parallel_mismatch.hpp, libs/iterator_support/include/hpx/iterator_support/traits/is_iterator.hpp, libs/iterator_support/include/hpx/iterator_support/traits/is_sentinel_for.hpp, libs/type_support/CMakeLists.txt, libs/type_support/include/hpx/type_support/equality.hpp
- add overloads for mismatch taking ranges
- flyby: making projection_identity constexpr
=> Adapting mismatch to C++20

cmake/HPX_AddTest.cmake, libs/segmented_algorithms/tests/unit/CMakeLists.txt
I could not figure out why, but the `partitioned_vector_{in,ex}clusive_scan` tests run significantly slower (to the point of timing out like here: https://cdash.cscs.ch/viewTest.php?onlyfailed&buildid=120322, even though they do eventually finish) when run in parallel or even in parallel with `--hpx:bind=none`. This makes them run serially and makes other multi-locality tests use `--hpx:bind=none` when networking is off.
=> Force partitioned vector scan tests to run serially

libs/resiliency/CMakeLists.txt, libs/resiliency/include/hpx/resiliency/async_replay.hpp, libs/resiliency/include/hpx/resiliency/async_replay_executor.hpp, libs/resiliency/include/hpx/resiliency/async_replicate.hpp, libs/resiliency/include/hpx/resiliency/async_replicate_executor.hpp, libs/resiliency/include/hpx/resiliency/replay_executor.hpp, libs/resiliency/include/hpx/resiliency/replicate_executor.hpp, libs/resiliency/tests/unit/CMakeLists.txt, libs/resiliency/tests/unit/replay_executor.cpp, libs/resiliency/tests/unit/replicate_executor.cpp
- this allows for instance for the parallel algorithms to be resilient
to failing iterations
=> Adding replay_executor and replicate_executor

libs/algorithms/CMakeLists.txt, libs/algorithms/include/hpx/parallel/algorithms/detail/advance_to_sentinel.hpp, libs/algorithms/include/hpx/parallel/algorithms/find.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/copy.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/find.hpp, libs/algorithms/include/hpx/parallel/util/loop.hpp, libs/algorithms/tests/unit/algorithms/findfirstof.cpp, libs/algorithms/tests/unit/algorithms/findfirstof_binary.cpp, libs/algorithms/tests/unit/algorithms/findif.cpp, libs/algorithms/tests/unit/algorithms/findifnot_bad_alloc.cpp, libs/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/algorithms/tests/unit/container_algorithms/find_end_range.cpp, libs/algorithms/tests/unit/container_algorithms/find_end_range2.cpp, libs/algorithms/tests/unit/container_algorithms/find_first_of_range.cpp, libs/algorithms/tests/unit/container_algorithms/find_first_of_range2.cpp, libs/algorithms/tests/unit/container_algorithms/find_if_not_exception_range.cpp, libs/algorithms/tests/unit/container_algorithms/find_if_not_range.cpp, libs/algorithms/tests/unit/container_algorithms/find_if_range.cpp, libs/algorithms/tests/unit/container_algorithms/find_range.cpp, libs/include/include/hpx/algorithm.hpp, libs/segmented_algorithms/include/hpx/parallel/segmented_algorithms/find.hpp, libs/segmented_algorithms/tests/unit/partitioned_vector_find.cpp, libs/segmented_algorithms/tests/unit/partitioned_vector_find2.cpp
This adds compatibility to C++20 for
This also adds range based overloads for those algorithms
This also adds `constexpr` to a couple of facilities (as a flyby).
=> Adapting hpx::find and friends to C++20

hpx/lcos/detail/promise_base.hpp, libs/async_combinators/include/hpx/async_combinators/split_future.hpp, libs/async_cuda/include/hpx/async_cuda/cublas_executor.hpp, libs/async_cuda/include/hpx/async_cuda/cuda_executor.hpp, libs/executors/include/hpx/executors/dataflow.hpp, libs/executors/include/hpx/executors/service_executors.hpp, libs/futures/include/hpx/futures/detail/future_data.hpp, libs/futures/include/hpx/futures/futures_factory.hpp, libs/futures/include/hpx/futures/packaged_continuation.hpp, libs/futures/tests/regressions/future_unwrap_878.cpp, libs/lcos_local/include/hpx/lcos_local/packaged_task.hpp
Setting the exception on a future may yield (a lock is required), and thus lead to the task being resumed on another worker thread after setting the exception. Before this change the exception for a future was set directly in the catch block which could lead to the catch block being entered on one worker thread and exited on another thread. This seems to not be allowed and leads to
segfaults at least with gcc and clang. This change only gets the current exception in the catch block, but sets it after the catch block to avoid potentially yielding in the catch block.
I'm currently stress testing `partition` and `uninitialized_move` and they seem to not fail anymore locally. I'm assuming this will fix most of the other `tests.unit.modules.algorithms` tests that occasionally fail (it always …
=> Fix exception handling for tasks

libs/algorithms/include/hpx/parallel/algorithms/all_any_none.hpp, libs/algorithms/include/hpx/parallel/algorithms/count.hpp, libs/algorithms/include/hpx/parallel/algorithms/destroy.hpp, libs/algorithms/include/hpx/parallel/algorithms/equal.hpp, libs/algorithms/include/hpx/parallel/algorithms/fill.hpp, libs/algorithms/include/hpx/parallel/algorithms/find.hpp, libs/algorithms/include/hpx/parallel/algorithms/generate.hpp, libs/algorithms/include/hpx/parallel/algorithms/mismatch.hpp, libs/algorithms/include/hpx/parallel/algorithms/move.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/all_any_none.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/count.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/destroy.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/equal.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/fill.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/find.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/generate.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/mismatch.hpp, libs/algorithms/include/hpx/parallel/container_algorithms/move.hpp, libs/resiliency/include/hpx/resiliency/resiliency_cpos.hpp
Potentially fixes some compilation problems seen by @G-071 (i.e. `/home/daissgr/external_packages/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.5.0/hpx-master-52nq7dny5j2onrsczqrnwazze6zduz6y/include/hpx/parallel/algorithms/all_any_none.hpp(628): error: const variable "hpx::none_of" requires an initializer -- class "hpx::none_of_t" has no user-provided default constructor`).
I'm a bit surprised by this, but it could be nvcc being dumb (gcc 8 and CUDA 10 is fine with this)? @G-071 would you mind posting the actual compiler version (gcc is apparently 7.5.0), CUDA version, and C++ standard that you're using?
=> Aggregate initialize CPOs

libs/algorithms/include/hpx/parallel/algorithms/for_loop.hpp, libs/algorithms/include/hpx/parallel/util/loop.hpp, libs/algorithms/include/hpx/parallel/util/prefetching.hpp
- flyby: improve loop unrolling for algorithms
This requires some more thorough performance measurements, from my minimal tests this PR improves the picture slightly.
=> Adding specializations for simple for_loops

cmake/HPX_GeneratePackage.cmake, cmake/HPX_SetupTarget.cmake, src/CMakeLists.txt
Adds alias targets for internal use (i.e. within the HPX CMake project) which have the namespace used when exporting. This should fix #4913, and removes some ugly `$<TARGET_NAME_IF_EXISTS:...>` generator expressions.
@kordejong would you mind trying this out for yourself?
Let's try to get this in 1.5.0 still.
=> Add alias targets with namespaces used for exporting

CMakeLists.txt
Update the APEX tag on master instead of release as there are some failures due to this
=> Update apex tag

libs/async_cuda/include/hpx/async_cuda/cuda_future.hpp, libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp
Avoid mistakes where user polling is enabled and disabled immediately, instead of at the end of a scope.
@auriane this is a nice extra for the release, but it does not have to be in 1.5.0-rc3.
=> Add HPX_NODISCARD to enable_user_polling structs

docs/sphinx/manual/writing_distributed_hpx_applications.rst
Replacing the variable `localvv` with `local_vv`
While using the code snippet I found this typo in the variable name and think that it is intended to work with `local_vv`, correct?
=> Documentation Distributed HPX applications localvv with local_vv

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, examples/quickstart/disable_thread_stealing_executor.cpp, examples/quickstart/executor_with_thread_hooks.cpp, libs/algorithms/CMakeLists.txt, libs/algorithms/include/hpx/parallel/algorithms/for_loop.hpp, libs/algorithms/tests/regressions/for_loop_2281.cpp, libs/algorithms/tests/unit/algorithms/for_loop.cpp, libs/algorithms/tests/unit/algorithms/for_loop_exception.cpp, libs/algorithms/tests/unit/algorithms/for_loop_induction.cpp, libs/algorithms/tests/unit/algorithms/for_loop_induction_async.cpp, libs/algorithms/tests/unit/algorithms/for_loop_n.cpp, libs/algorithms/tests/unit/algorithms/for_loop_n_strided.cpp, libs/algorithms/tests/unit/algorithms/for_loop_reduction.cpp, libs/algorithms/tests/unit/algorithms/for_loop_reduction_async.cpp, libs/algorithms/tests/unit/algorithms/for_loop_strided.cpp, libs/async_cuda/tests/unit/cublas_matmul.cpp, libs/collectives/tests/performance/osu/osu_bibw.cpp, libs/compute_cuda/tests/unit/for_loop_compute.cu, libs/include/include/hpx/algorithm.hpp, libs/resource_partitioner/examples/oversubscribing_resource_partitioner.cpp, libs/resource_partitioner/examples/simple_resource_partitioner.cpp, tests/performance/local/future_overhead.cpp
Can go in 1.5.0 or 1.6.0. This should be fairly straightforward (i.e. no big surprises with builds and tests), but let's see.
=> Add CPOs for for_loop algorithms

CMakeLists.txt, docs/sphinx/contributing/release_procedure.rst
Post release cleanup
- Change tag/versions
- Update again the release procedure notes
=> Post release cleanup

.cmake-format.py, docs/sphinx/releases/whats_new_0_9_6.rst, docs/sphinx/releases/whats_new_1_5_0.rst, examples/quickstart/1d_wave_equation.cpp, hpx/util/connection_cache.hpp, libs/algorithms/include/hpx/parallel/util/low_level.hpp, libs/algorithms/tests/unit/algorithms/parallel_sort.cpp, libs/checkpoint_base/docs/index.rst, libs/debugging/include/hpx/debugging/print.hpp, libs/executors/include/hpx/executors/limiting_executor.hpp, libs/runtime_configuration/src/ini.cpp, libs/serialization/docs/index.rst, plugins/parcelport/libfabric/rma_receiver.cpp, tests/performance/local/nonconcurrent_fifo_overhead.cpp, tests/performance/local/nonconcurrent_lifo_overhead.cpp
Fixes #4940. I've left typos that come from an external source (mainly PR titles).
=> Fix typos reported by fossies codespell report

.jenkins/cscs/Jenkinsfile, .jenkins/cscs/entry.sh, .jenkins/lsu/Jenkinsfile, .jenkins/lsu/entry.sh
Set a limit on days and number of artifacts to keep. Also make sure that artifacts from previous builds are deleted at the beginning of a build.
=> Clean up old artifacts better and more aggressively on Jenkins

libs/full/runtime_local/src/runtime_local.cpp, src/runtime_distributed.cpp
The restriction of the suspend/resume mechanism of the runtime to a single locality seems unnecessary.
Fixes #4937
According to a short discussion with @msimberg it should be possible to suspend/resume the runtime also on multiple localities, so as a test I removed the corresponding checks and did some test runs on our cluster which showed no problems. Nevertheless, I would appreciate the input of someone with a deeper understanding of the code.
=> Allow suspension on multiple localities

libs/core/functional/CMakeLists.txt, libs/core/functional/include/hpx/functional/detail/invoke.hpp, libs/core/functional/include/hpx/functional/invoke.hpp, libs/core/functional/include/hpx/functional/invoke_result.hpp, libs/core/functional/include/hpx/functional/tag_invoke.hpp, libs/core/functional/include/hpx/functional/traits/is_invocable.hpp
This alternative INVOKE implementation takes full advantage of C++11 features. The old implementation is very conservative, carefully designed to work with compilers lacking full expression SFINAE support (specifically anything mem-ptr related). Now that those compilers are no longer targeted we can have a more straightforward implementation, and one that fully supports member pointers (the old implementation lacks support for ref-qualified mem-funs, noexcept mem-funs, C-style variadics mem-funs, ...).
As a bonus, this straightforward implementation compiles in about half the time for msvc.
=> Alternative INVOKE implementation

.jenkins/cscs/env-clang-newest.sh, hpx/runtime/parcelset/encode_parcels.hpp, libs/core/schedulers/include/hpx/schedulers/local_priority_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/local_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp
Fixes #4950
@kordejong this should fix the problem you reported.
@msimberg could you suggest one of the builders we could use to enable `HPX_WITH_PARCELPORT_ACTION_COUNTERS` to avoid similar issues in the future?
=> Fixing build if HPX_WITH_PARCELPORT_ACTION_COUNTERS=On

libs/full/collectives/CMakeLists.txt, libs/full/collectives/include/hpx/collectives/communication_set.hpp, libs/full/collectives/include/hpx/collectives/detail/communication_set_node.hpp, libs/full/collectives/src/create_communication_set.cpp, libs/full/collectives/src/detail/communication_set_node.cpp, libs/full/collectives/tests/unit/CMakeLists.txt, libs/full/collectives/tests/unit/communication_set.cpp
A `communication_set` is a set of connected `communicator_node` objects that are connected using a binomial communication pattern. A `communication_set` can be created once and reused with any of the collective operations. This not only removes the overhead of establishing the connections for each instance of a collective operation, it also switches from the linear communication model to a tree based one.
Note that this PR does not change the collective operations (yet). These will be changed separately. Eventually all existing collective operations will be adapted to use the new `communication_set` mechanism.
=> Adding communications set

.circleci/config.yml
The docker image is installing the latest version, add print in circleci to know which version is currenly used.
=> Add clang-format and cmake-format version prints

libs/core/format/include/hpx/modules/format.hpp
Before there was a format module, this hack was necessary to have performance tests not depend on all of HPX. The hack was dropped once format became a module. The format export macro is a left-over.
=> Remove leftover format export hack

libs/full/include/CMakeLists.txt, libs/full/include/include/hpx/include/parallel_make_heap.hpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithm.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/make_heap.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/make_heap.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/detail/handle_local_exceptions.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/partitioner_with_cleanup.hpp, libs/parallelism/algorithms/tests/unit/algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/algorithms/make_heap.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/make_heap_range.cpp
This revives #1914, which has never made it in. This also converts the algorithm to CPOs and makes it conforming to C++20. Thanks again @Syntaf for working on this and sorry it took so long to get back to it.
=> Adding parallel make_heap 

libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/parallel_stable_sort.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/sample_sort.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/spin_sort.hpp, libs/parallelism/algorithms/tests/unit/algorithms/detail/test_sample_sort.cpp, libs/parallelism/algorithms/tests/unit/algorithms/detail/test_spin_sort.cpp
- these functions have been deprecated in C++17 and removed in C++20
Fixes #4971
=> Removing use of get_temporary_buffer and return_temporary_buffer

libs/core/concurrency/include/hpx/concurrency/cache_line_data.hpp
Fixes HPX compile problem on MSVC using C++17
This PR adds the missing include.
=> Adding the missing include

cmake/templates/conf.py.in, docs/sphinx/citing.rst, docs/sphinx/index.rst
I added a separate section in the documentation and link to it on the intro page. Prominent enough? I also left the links in place in the readme. I don't think it hurts to have it in both places.
=> Add page about citing HPX to documentation

libs/core/datastructures/include/hpx/datastructures/tagged.hpp, libs/core/datastructures/include/hpx/datastructures/tagged_pair.hpp, libs/core/datastructures/include/hpx/datastructures/tagged_tuple.hpp, libs/core/iterator_support/include/hpx/iterator_support/zip_iterator.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/for_loop.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/reduce.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/tagged_pair.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/tagged_tuple.hpp, libs/parallelism/execution/include/hpx/execution/executors/rebind_executor.hpp, libs/parallelism/executors/include/hpx/executors/dataflow.hpp, libs/parallelism/pack_traversal/include/hpx/pack_traversal/detail/pack_traversal_async_impl.hpp, libs/parallelism/pack_traversal/include/hpx/pack_traversal/detail/pack_traversal_impl.hpp, libs/parallelism/timed_execution/include/hpx/timed_execution/timed_executors.hpp
There are probably more warnings caused by the recent enabling of the deprecation macros. The changes in this PR make Phylanx compile without those.
=> Fixing some warnings from HPX complaining about use of obsolete types

libs/core/debugging/CMakeLists.txt, libs/core/debugging/include/hpx/debugging/print.hpp, libs/core/debugging/src/print.cpp, libs/core/debugging/tests/unit/CMakeLists.txt, libs/core/schedulers/include/hpx/schedulers/queue_holder_numa.hpp, libs/core/schedulers/include/hpx/schedulers/queue_holder_thread.hpp, libs/core/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/thread_queue_mc.hpp, libs/core/thread_pools/CMakeLists.txt, libs/core/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp, libs/core/threading_base/CMakeLists.txt, libs/core/threading_base/include/hpx/threading_base/print.hpp, libs/core/threading_base/src/print.cpp, libs/full/collectives/tests/performance/osu/osu_bibw.cpp, libs/full/collectives/tests/performance/osu/osu_bw.cpp, libs/full/collectives/tests/performance/osu/osu_latency.cpp, libs/full/collectives/tests/performance/osu/osu_multi_lat.cpp, libs/full/compute/include/hpx/compute/host/numa_binding_allocator.hpp, libs/parallelism/algorithms/tests/performance/transform_reduce_scaling.cpp, tests/performance/local/agas_cache_timings.cpp, tests/performance/local/foreach_scaling.cpp
- move as much as possible into separate compilation units
- break circular dependency between threading_base and debugging modules
- flyby: disable debug output from numa allocator
=> Cleaning up debug::print functionalities

libs/core/debugging/src/print.cpp, tests/unit/build/CMakeLists.txt
Add explicit template instanciation to fix undefined symbol when `print_bin` with `unsigned long` use
=> Attempt to fix MacOS Github action error

hpx/runtime/serialization/detail/preprocess_gid_types.hpp, libs/core/serialization/include/hpx/serialization/detail/extra_archive_data.hpp, libs/core/serialization/include/hpx/serialization/detail/pointer.hpp, libs/core/serialization/src/detail/pointer.cpp, libs/full/checkpoint_base/include/hpx/checkpoint_base/checkpoint_data.hpp, libs/full/checkpoint_base/src/checkpoint_data.cpp, libs/parallelism/lcos_local/include/hpx/lcos_local/detail/preprocess_future.hpp, libs/parallelism/lcos_local/src/preprocess_future.cpp, src/runtime/parcelset/detail/parcel_await.cpp, src/runtime/serialization/detail/preprocess_gid_types.cpp
- this was broken on Windows, not sure if it was broken on other platforms as well
This fixes a serious issue and if it turns out that this was broken on non-Windows platforms as well then this would be a candidate for another point release.
=> Fixing template specializations that make extra archive data types unique across module boundaries

hpx/runtime/serialization/detail/preprocess_gid_types.hpp, libs/core/serialization/include/hpx/serialization/basic_archive.hpp, libs/core/serialization/include/hpx/serialization/detail/extra_archive_data.hpp, libs/core/serialization/include/hpx/serialization/detail/pointer.hpp, libs/core/serialization/src/detail/pointer.cpp, libs/full/checkpoint_base/include/hpx/checkpoint_base/checkpoint_data.hpp, libs/full/checkpoint_base/src/checkpoint_data.cpp, libs/parallelism/lcos_local/include/hpx/lcos_local/detail/preprocess_future.hpp, libs/parallelism/lcos_local/src/preprocess_future.cpp, src/runtime/serialization/detail/preprocess_gid_types.cpp
- This fixes an issue that is caused by not cleaning out the pointer
tracking data in output archives during serialization preprocessing
while repeatedly serializing the data because of futures not being
ready
=> Properly reset pointer tracking data in output_archive

tools/inspect/inspect.cpp
- Handle exceptions thrown from inspect's main
- Store parsed options into associated variables
- Change inspect check arguments into flags
=> Inspect command line tweaks

cmake/HPX_AddTest.cmake, libs/full/include/include/hpx/include/resource_partitioner.hpp, tests/unit/resource/CMakeLists.txt, tests/unit/resource/cross_pool_injection.cpp
I could get reliable hangs with the shared priority scheduler, and none with the other schedulers. This does not mean that the others are fault free, but at least I could not reproduce the issue with them. The other schedulers also don't use exactly the same flags as the shared priority scheduler, so it's not a 100% fair comparison. Time will tell if the test will keep failing.
=> Test all schedulers in cross_pool_injection test except shared_priority_queue_scheduler

libs/parallelism/algorithms/include/hpx/parallel/algorithms/fill.hpp, libs/parallelism/algorithms/tests/regressions/CMakeLists.txt, libs/parallelism/algorithms/tests/regressions/fill_executor_5016.cpp
Fixes #5016
@stevenrbrandt please verify whether this fixes your issue.
Please note that `hpx::parallel::fill` was deprecated and will be removed in the future, use `hpx::fill` instead (which also is not affected by this issue).
=> Fixing broken backwards compatibility for hpx::parallel::fill

cmake/templates/hpxrun.py.in
Improve hpxrun.py for Phylanx
- Allow the setting of a default port
- Allow the specification of environment variables to pass along
- Work with Singularity environments
=> Improve hpxrun.py for Phylanx

.circleci/config.yml, CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/HPX_AddModule.cmake, cmake/HPX_AddParcelport.cmake, cmake/HPX_SetupLibfabric.cmake, cmake/HPX_SetupVerbs.cmake, cmake/installed_hpx.cmake, docs/sphinx/contributing/docker_image.rst, examples/interpolate1d/CMakeLists.txt, libs/core/datastructures/include/hpx/datastructures/tuple.hpp, libs/core/serialization/tests/unit/CMakeLists.txt, libs/core/synchronization/tests/regressions/ignore_while_locked_1485.cpp, libs/core/synchronization/tests/unit/shared_mutex/shared_mutex1.cpp, libs/core/synchronization/tests/unit/shared_mutex/shared_mutex2.cpp, libs/full/collectives/tests/performance/osu/CMakeLists.txt, libs/full/runtime_local/src/runtime_local.cpp, src/CMakeLists.txt, src/runtime_distributed.cpp, tests/unit/agas/components/CMakeLists.txt, tests/unit/component/CMakeLists.txt, tests/unit/resource/suspend_pool_external.cpp, tools/docker/Dockerfile
I've updated the base image for CI to Ubuntu 20.04 (20.10 is still a bit too recent, and not all packages worked there). At the same time I started tagging the pushed images with a simple incrementing number. That means that we can update the image without having all CI builds use the new image immediately. A PR on the HPX side (like this one) is required to actually update to the new version. The versioning is completely manual for the moment, as e.g. installing a single new package in the image doesn't necessarily require a new version. We can improve this later if needed. The `latest` tag always refers to the latest image.
With the move to Ubuntu 20.04 clang is updated to 10, but I've kept clang-format on 9 for now. Ubuntu helpfully provides a few versions of clang-format so we can in …
=> Use versioned container image on CircleCI

.jenkins/lsu/slurm-configuration-gcc-9-cuda-11.sh
Both nodes with AMD GPUs are used for jenkins, one for the cuda run and the other for the hip run.
This limit the cuda jenkins run to partitions which contains exclusively NVIDIA GPUs.
=> Limit cuda jenkins run to nodes with exclusively Nvidia GPUs 

.jenkins/lsu/slurm-configuration-hipcc.sh
Paired with #5047
Limit the hipcc jenkins to only the reno nodes, will revert it once the main work on hipcc is done.
=> Limit jenkins hipcc to the reno node

docs/sphinx/manual/starting_the_hpx_runtime.rst
Adds the warning that #4946 warrants to the documentation.
=> Add warning about suspending/resuming the runtime in multi-locality scenarios

libs/core/datastructures/include/hpx/datastructures/tuple.hpp, libs/core/datastructures/include/hpx/datastructures/variant_helper.hpp
The deprecated forwarding definition was... not right.
=> Fix hpx::util::get

tests/performance/local/future_overhead.cpp
Instead of disabling the entire test we only disable the distributed parts (forgotten in #5061)
=> Limit the device code guards to the distributed parts of the future_overhead bench

components/component_storage/include/hpx/components/component_storage/server/migrate_to_storage.hpp, components/component_storage/src/component_storage.cpp, components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_component_impl.hpp, components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_impl.hpp, components/containers/unordered/include/hpx/components/containers/unordered/partition_unordered_map_component.hpp, components/containers/unordered/include/hpx/components/containers/unordered/unordered_map.hpp, components/iostreams/include/hpx/components/iostreams/ostream.hpp, libs/full/agas/src/primary_namespace.cpp, libs/full/collectives/src/latch.cpp, libs/full/performance_counters/src/counter_creators.cpp, libs/full/performance_counters/src/performance_counter.cpp, src/runtime/components/server/runtime_support_server.cpp, src/runtime/components/stubs/runtime_support_stubs.cpp, src/runtime/trigger_lco.cpp, src/runtime_distributed.cpp
Fix unused variables warnings in hipcc after #5057
=> Fix unused variables warnings in hipcc

libs/core/string_util/include/hpx/string_util/split.hpp, libs/core/string_util/tests/unit/string_split.cpp
The implementation could dereference the end or past the end of the input. Fixes #5067.
=> Fix string split function

libs/parallelism/algorithms/include/hpx/parallel/util/result_types.hpp
This fixes the convertibility mismatch that we had on `result_types` according to C++20.
=> Fix is_convertible args in result_types

CMakeLists.txt
Might fix #5077. Completely untested, but I'm pretty sure the reason the plugins are not found is simply because we don't add the GNUInstallDirs-enabled lib64 directory to the list of search paths. @shahrzad I'd appreciate if you could give this a try.
=> Add install lib directory to list of component search paths

libs/parallelism/pack_traversal/include/hpx/pack_traversal/detail/pack_traversal_impl.hpp, libs/parallelism/pack_traversal/tests/regressions/CMakeLists.txt, libs/parallelism/pack_traversal/tests/regressions/unwrapping_noncopyable.cpp
Avoiding decays at least makes the simple case work. CI will tell me if I've broken something else (unsure if some of the asynchronous cases depend on copies being made; should not if everything is set up correctly...).
Edit: this works for noncopyable lvalues but something breaks trying to make it work for rvalues. There's likely something that depends on having to make copies (e.g. containers). The current fix is enough for me at the moment.
=> Allow using noncopyable types with unwrapping

tests/performance/local/future_overhead.cpp
=> Remove duplicated call to the limiting_executor in future_overhead test

libs/core/iterator_support/include/hpx/iterator_support/traits/is_iterator.hpp, libs/core/iterator_support/tests/unit/iterator_tests.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/transfer.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/set_difference.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/set_intersection.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/set_symmetric_difference.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/set_union.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_reduce.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/all_any_none.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/set_difference.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/set_intersection.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/set_symmetric_difference.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/set_union.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/transform_reduce.hpp
- some sequential algorithms (copy, etc.) are fully functional if - when used sequentially - the destination is just an output iterator
- fixing is_output_iterator
- fixing `transform_reduce` implementation to properly handle constant input sequences
- flyby: minor formatting changes
=> Lessen constraints on certain algorithm arguments

libs/full/async_cuda/include/hpx/async_cuda/cuda_future.hpp, libs/full/async_cuda/src/cuda_future.cpp, libs/full/async_mpi/src/mpi_future.cpp
Adds a check to make sure that polling has been registered at least once before getting MPI/CUDA futures, and another that checks that there are no more unprocessed events/requests/futures when polling is disabled. `HPX_NODISCARD` helps if one actually remembers to try to enable polling, but doesn't help one hasn't even remembered to do that. In those cases the application just hangs without any indication of what is wrong. These checks are intended to help debugging those situations.
The reason for the currently vague "registered at least once" is that the polling could be enabled on *any* pool, and I didn't want to look through every pool to see if at least one of them has polling enabled. This may be necessary in the end, but this should already catch most cases of not enabling …
=> Add checks to make sure that MPI/CUDA polling is enabled/not disabled too early

hpx/runtime/agas/addressing_service.hpp, libs/core/affinity/include/hpx/affinity/affinity_data.hpp, libs/core/affinity/src/affinity_data.cpp, libs/full/command_line_handling/include/hpx/command_line_handling/command_line_handling.hpp, libs/full/command_line_handling/src/command_line_handling.cpp, libs/full/init_runtime/src/hpx_init.cpp, libs/full/resource_partitioner/CMakeLists.txt, libs/full/resource_partitioner/include/hpx/resource_partitioner/detail/create_partitioner.hpp, libs/full/resource_partitioner/include/hpx/resource_partitioner/detail/partitioner.hpp, libs/full/resource_partitioner/include/hpx/resource_partitioner/partitioner.hpp, libs/full/resource_partitioner/src/detail_partitioner.cpp, libs/full/resource_partitioner/src/partitioner.cpp, libs/full/runtime_local/include/hpx/runtime_local/runtime_local.hpp, libs/full/runtime_local/src/runtime_local.cpp, libs/full/threadmanager/include/hpx/modules/threadmanager.hpp, libs/full/threadmanager/src/threadmanager.cpp, src/runtime/agas/addressing_service.cpp, src/runtime_distributed.cpp
Moves command line handling out of the resource partitioner and into `hpx_init.cpp`. This leaves the partitioner only needing the runtime configuration and affinity data to set things up. The command line handling is now also slightly dumber in the sense that it only parses command line options and populates the configuration, but after that configuration options should be accessed through the runtime configuration, not through the command line handling.
This does contain some potentially breaking changes (e.g. command line handling can't be accessed through the partitioner), and we'll have to see how this affects users. My guess is that it's again a very small fraction (like @biddisco) who are affected.
@K-ballo this should also get rid of program options leaking out from the …
=> Refactor runtime configuration, command line handling, and resource partitioner

libs/full/compute_cuda/tests/unit/transform_compute.cu, libs/full/include/include/hpx/algorithm.hpp, libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/detail/dispatch.hpp, libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/transform.hpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_transform1.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_transform2.cpp, libs/full/segmented_algorithms/tests/unit/test_transform_binary.hpp, libs/full/segmented_algorithms/tests/unit/test_transform_binary2.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/dispatch.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/transform.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/result_types.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/transform_loop.hpp, libs/parallelism/algorithms/tests/unit/algorithms/transform.cpp, libs/parallelism/algorithms/tests/unit/algorithms/transform_binary.cpp, libs/parallelism/algorithms/tests/unit/algorithms/transform_binary2.cpp, libs/parallelism/algorithms/tests/unit/algorithms/transform_binary2_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/transform_binary_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/transform_tests.hpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/transform_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/transform_range2.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/transform_range_binary.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/transform_range_binary2.cpp, tests/performance/local/stream.cpp
This adapts `transform` to C++20 (all overloads according to [the Standard](http://eel.is/c++draft/alg.transform)) and adds unit tests. It deprecates the `hpx::parallel::transform` overloads.
flyby: it adds `get_in_in_out_result`.
=> Adapt transform to C++20

cmake/HPX_AddModule.cmake, cmake/TargetArch.cmake
The modules_enabled.hpp file was being wiped by a cleanup step
in the module creation script.
Architecture detection generated a file on every configure
step and only needs to be done once, so cache the result fo
reuse on subsequent runs.
=> Fix regeneration of two files that trigger unnecessary rebuilds

libs/core/coroutines/include/hpx/coroutines/thread_enums.hpp
These were not meant to be disabled yet, and I'd prefer not to have a CMake option at all. They will simply be available but deprecated until they're removed.
=> Untie deprecated thread enums from the CMake option

CMakeLists.txt
Currently updated to the develop branch while we wait for a real tag for APEX.
=> Update APEX tag for 1.6.0

libs/full/init_runtime/include/hpx/hpx_init.hpp, libs/full/init_runtime/include/hpx/hpx_start.hpp
These overloads may take precedence over the non-deprecated overloads
using `hpx::init_params` when the mode has a default value. Since these
overloads are deprecated, we don't want them to take precedence.
=> Remove default runtime mode argument from start/init overloads

libs/full/init_runtime/include/hpx/hpx_init.hpp, libs/full/init_runtime/include/hpx/hpx_start.hpp
Apologies, I was off by one in #5103. On top of that `hpx::start` did not need any change...
=> Remove default runtime mode argument from init overload, again

libs/core/iterator_support/tests/unit/is_sentinel_for.cpp, libs/core/iterator_support/tests/unit/is_sized_sentinel_for.cpp, libs/core/iterator_support/tests/unit/iter_sent.hpp, libs/parallelism/algorithms/tests/regressions/count_3646.cpp, libs/parallelism/algorithms/tests/regressions/iter_sent.hpp, libs/parallelism/algorithms/tests/regressions/reduce_3641.cpp, libs/parallelism/algorithms/tests/unit/algorithms/distance.cpp, libs/parallelism/algorithms/tests/unit/algorithms/iter_sent.hpp, libs/parallelism/algorithms/tests/unit/container_algorithms/foreach_adapt.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/iter_sent.hpp
Fixes #5075 
- Change Iterator struct to iterator
- Change Sentinel struct to sentinel
- Cleanup in files that had unnecessary includes
=> Refactor iter_sent.hpp to make structs lowercase

libs/core/properties/include/hpx/properties/property.hpp, libs/parallelism/execution/include/hpx/execution/executors/execution_parameters.hpp
Probably fixes compilation on older nvcc's. Not regression test (yet) as I couldn't reproduce this with gcc 8.3 and cuda 10.2. Likely only happens on older cuda versions. Same problem as in #4912.
@G-071 I'd appreciate you trying this out!
=> Change initialization of property CPOs to satisfy older nvcc versions

CMakeLists.txt, cmake/HPX_AddConfigTest.cmake
Fixes #5112 
We test a link to atomics and set the `HPX_WITH_CXX11_ATOMIC` if ok, but if it fails, we add lib atomic and try again. Then repeat the process with 128 bit atomics. If either needs lib atomic, then `HPX_CXX11_STD_ATOMIC_LIBRARIES` is set to `atomic` and we add that as a dependency to the main hpx_core library.
This fixes my problems (for now at least)
Edit : The problem seems to have been that the check_function_exists call was not delivering as expected.
=> Fix 5112 - make sure libatomic is used when needed

libs/parallelism/executors/include/hpx/executors/dataflow.hpp, libs/parallelism/lcos_local/tests/unit/local_dataflow_executor_additional_arguments.cpp
Removes a `typename hpx::util::always_void<typename hpx::util::detail::invoke_fused_result<F, Args>::type>::type` from the `dataflow_return_impl` specialization as it can in certain cases trigger errors where none should be triggered. There is an added test case which triggers this problem.
Regarding the test case, a trailing `-> decltype(void_f(std::forward<Ts>(ts)...))` on the wrapper does also avoid the error, but I don't see a need for the `always_void<...>` in the specialization so I've removed that. Might I be missing some corner case that requires it?
=> Relax dataflow internals

libs/parallelism/algorithms/tests/performance/benchmark_partial_sort.cpp, libs/parallelism/algorithms/tests/performance/benchmark_partial_sort_parallel.cpp
The benchmarks otherwise take too long to run.
=> Reduce vector sizes in partial sort benchmarks when running in debug mode

libs/parallelism/algorithms/include/hpx/parallel/algorithms/all_any_none.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/find.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/find.hpp
This makes `hpx::find` and friends to use the `sequential_find` functions that are located under the detail directory and thus removes the ones placed in the same header.
flyby: It adds the projection utility in the overloads under the separate header.
=> Use sequential_find and friends from separate detail header

libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/transform.hpp, plugins/parcelport/libfabric/sender.cpp
- flyby: fixing compatibility warning in libfabric parcelport
=> Fixing compatibility warnings in hpx::transform implementation

docs/sphinx/releases/whats_new_1_6_0.rst
Getting the process started for a 1.6.0 release.
The main question I have is how we want to deal with our compatibility options. There are a number of them that we "should" have turned off in the previous release (i.e. according to our release procedure). However, I consider a feature off by default the same as removed (pre-built packages are unlikely to turn those on just for users who need them).
My preference would be to outright remove the options and code guarded by the options (how many users' code will we actually break?). The other option is to properly add actual deprecation warnings to the removed features and remove the compatibility options. If a user has had a warning about a deprecated feature in a previous release we don't need to feel so bad about removing them quickly.
=> 1.6.0 release notes

libs/core/iterator_support/include/hpx/iterator_support/counting_iterator.hpp
Small fix overdue for `hpx-kokkos`.
=> Mark counting_iterator member functions as HPX_HOST_DEVICE

docs/joss_paper/paper.bib, docs/sphinx/manual/launching_and_configuring_hpx_applications.rst, docs/sphinx/releases/whats_new_0_9_6.rst, docs/sphinx/releases/whats_new_0_9_8.rst, docs/sphinx/releases/whats_new_0_9_9.rst, docs/sphinx/releases/whats_new_0_9_99.rst, docs/sphinx/releases/whats_new_1_0_0.rst, examples/quickstart/composable_guard.cpp, examples/spell_check/5desk.txt, libs/core/concurrency/include/hpx/concurrency/detail/contiguous_index_queue.hpp, libs/core/config/include/hpx/config.hpp, libs/full/collectives/src/create_communication_set.cpp, libs/full/program_options/include/hpx/program_options/parsers.hpp, libs/full/resiliency_distributed/examples/async_replay_distributed.cpp, libs/full/resiliency_distributed/examples/async_replicate_distributed.cpp, libs/full/resiliency_distributed/tests/performance/replay/1d_stencil_replay_distributed.cpp, libs/full/resiliency_distributed/tests/performance/replay/async_replay_distributed_validate.cpp, libs/full/resiliency_distributed/tests/performance/replicate/async_replicate_distributed.cpp, libs/full/resiliency_distributed/tests/performance/replicate/async_replicate_distributed_validate.cpp, libs/full/resiliency_distributed/tests/performance/replicate/async_replicate_distributed_vote.cpp, libs/full/resiliency_distributed/tests/performance/replicate/async_replicate_distributed_vote_validate.cpp, libs/parallelism/resiliency/examples/dataflow_replicate.cpp, plugins/parcelport/libfabric/receiver.hpp
...as reported by https://fossies.org/linux/test/hpx/codespell.html
Fixes #4940
Thanks @jschleus! One of the spelling problems can't be fixed, could you add the word to the whitelist, please (`'unitialized'`, here: https://github.com/STEllAR-GROUP/hpx/blob/master/docs/sphinx/releases/whats_new_1_1_0.rst)?
=> Fixing spelling errors 

.jenkins/lsu/env-clang-9.sh, libs/core/topology/CMakeLists.txt, libs/core/topology/include/hpx/topology/topology.hpp, libs/core/topology/src/topology.cpp
- on certain platforms (like BSD), hwloc doesn't correctly report the number of cores, use number of PUs instead
Fixes #5115
@bgoglin I have no way of actually testing this. Would you be able to verify if this fixes the issue by any chance?
=> Working around hwloc limitation on certain platforms

.circleci/config.yml
I *think* this fixes it. The CircleCI build will show if it's correct. I'll check if it does the right thing on master once merged.
=> Make sure codespell checks run on CircleCI

components/performance_counters/memory/CMakeLists.txt, components/process/include/hpx/components/process/util/posix/initializers/inherit_env.hpp, examples/quickstart/CMakeLists.txt, libs/core/debugging/CMakeLists.txt, libs/core/debugging/include/hpx/debugging/environ.hpp, libs/core/debugging/src/print.cpp, libs/full/performance_counters/tests/regressions/CMakeLists.txt, libs/full/program_options/src/parsers.cpp, libs/full/runtime_local/src/custom_exception_info.cpp
- flyby: disable memory perf counters for FreeBSD
Fixes #5115
=> Fixing environment handling for FreeBSD

tools/pre-commit
To use this file execute
cp tools/pre-commit .git/hooks/pre-commit
The pre-commit hook failed to work properly if a file in the
root dir was changed as the relative path was passed an empty
string. Fix that by quoting the path.
Add an extra line to the output to summarize the file changes
into a new commit line so that after fixing format errors
it is easy to commit the fixed files.
=> Fix path problem in pre-commit hook, add summary commit line

libs/core/threading_base/src/scheduler_base.cpp, libs/full/threadmanager/src/threadmanager.cpp
I had problems with background idle flags being set even when I had set them to off - this PR fixes a wrong use of add_scheduler_mode - it should be set_scheduler_mode on initialization.
I also protected a couple of places that don't need to be run when the idle flag is unset.
=> Scheduler mode

libs/core/schedulers/tests/unit/schedule_last.cpp, libs/full/compute/tests/unit/numa_allocator.cpp, libs/full/init_runtime/include/hpx/hpx_init_params.hpp, libs/full/init_runtime/src/hpx_init.cpp, libs/full/resource_partitioner/examples/CMakeLists.txt, libs/full/resource_partitioner/examples/guided_pool_test.cpp, libs/full/resource_partitioner/examples/oversubscribing_resource_partitioner.cpp, libs/full/resource_partitioner/examples/simple_resource_partitioner.cpp, libs/full/resource_partitioner/examples/simplest_resource_partitioner_2.cpp, libs/full/resource_partitioner/tests/unit/named_pool_executor.cpp, tests/unit/resource/cross_pool_injection.cpp, tests/unit/resource/scheduler_binding_check.cpp, tests/unit/resource/shutdown_suspended_pus.cpp, tests/unit/resource/suspend_disabled.cpp, tests/unit/resource/suspend_pool.cpp, tests/unit/resource/suspend_pool_external.cpp, tests/unit/resource/suspend_runtime.cpp, tests/unit/resource/suspend_thread.cpp, tests/unit/resource/suspend_thread_external.cpp
Passing the variables map to the init callback for the resource
partitioner makes passing of options like "--pool-threads" more
straightforward than some of the alternatives such as parsing
the command-line twice.
Some of the examples/tests that use the resource partitioner
had copy/pasted a bunch of init from some very early tests and
some cleanup/simplication has been made, but not to all tests
so far.
=> Add program options variable map to resource partitioner init

hpx/runtime/components/server/runtime_support.hpp, src/runtime/components/server/runtime_support_server.cpp
Fixes #5148
('module' is a keyword starting with C++20)
=> Rename 'module' symbols to avoid keyword conflict

libs/full/include/include/hpx/algorithm.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/find.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/remove.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/remove.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/result_types.hpp, libs/parallelism/algorithms/tests/performance/benchmark_remove.cpp, libs/parallelism/algorithms/tests/performance/benchmark_remove_if.cpp, libs/parallelism/algorithms/tests/unit/algorithms/remove_tests.hpp, libs/parallelism/algorithms/tests/unit/container_algorithms/iter_sent.hpp, libs/parallelism/algorithms/tests/unit/container_algorithms/remove_if_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/remove_range.cpp
This adapts `hpx::remove` and `hpx::ranges:remove_if` to C++20 with the latest API, supporting `iterator` - `sentinel` pairs and `ranges`.
flyby: adds `make_subrange` utility function.
=> Adapt remove and remove_if to C++20

.jenkins/cscs/env-clang-newest.sh, examples/cancelable_action/cancelable_action/server/cancelable_action.hpp, libs/core/config/include/hpx/config/endian.hpp, libs/core/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp, libs/core/serialization/tests/performance/serialization_performance.cpp, libs/full/compute/include/hpx/compute/traits/allocator_traits.hpp, libs/parallelism/pack_traversal/tests/regressions/unwrapping_noncopyable.cpp, tests/regressions/threads/block_os_threads_1036.cpp
Tentatively just changed the C++ standard on the `clang-newest` builder. Boost might need a separate build, although I think this configuration is free of compiled Boost.
=> Use C++20 on clang-newest Jenkins CI configuration

CMakeLists.txt, cmake/HPX_AddComponent.cmake, cmake/HPX_AddExecutable.cmake, cmake/HPX_AddLibrary.cmake, cmake/HPX_AddModule.cmake, cmake/HPX_SetupCUDA.cmake, libs/full/async_cuda/CMakeLists.txt, libs/full/compute_cuda/CMakeLists.txt, tests/performance/local/stream.cpp
Alternative to #5141. @biddisco could you check if the options behave the way you'd expect on this branch?
=> Adjust handling of CUDA/HIP options in CMake

libs/core/threading_base/CMakeLists.txt, libs/core/threading_base/include/hpx/threading_base/annotated_function.hpp, libs/core/threading_base/src/annotated_function.cpp, tests/unit/apex/annotation_check.cpp
Storing the annotations in the `annotated_function` wrapper ensures that the annotations live at least until its `operator()` is called, by which point the annotation should already have been set to APEX.
The `annotation_check` test is updated to use dynamically allocated annotations which go out of scope before the tasks have completed (and it fails before the second commit in this PR).
Fixes #5126.
=> Store annotated_function annotations as std::strings

CMakeLists.txt, cmake/HPX_AddModule.cmake, cmake/HPX_AddParcelport.cmake, cmake/HPX_SetupTarget.cmake, src/CMakeLists.txt
Seems to give a modest improvement (5-10% on top of a unity build, for `hpx_core`). The list of headers may need some tweaking, since there's a tradeoff between how many headers are included and how many are actually used by HPX.
Boost headers are not included since they need to come after `hpx/config.hpp` (what's the reason for this?).
I've no clue if this will work correctly on Windows, so please give it a try and see what happens!
=> Add HPX_WITH_PRECOMPILED_HEADERS option

.github/workflows/windows_debug.yml, .github/workflows/windows_release.yml, CMakeLists.txt, cmake/HPX_AddModule.cmake, cmake/HPX_CompilerFlagsTargets.cmake, cmake/templates/HPXConfig.cmake.in, cmake/templates/HPXMacros.cmake.in, examples/hello_world_component/CMakeLists.txt, hpx/runtime/components/server/component_base.hpp, hpx/runtime/components/server/fixed_component_base.hpp, hpx/runtime/components/server/managed_component_base.hpp, libs/core/config/include/hpx/config/debug.hpp, libs/core/functional/include/hpx/functional/one_shot.hpp, libs/core/functional/include/hpx/functional/tag_invoke.hpp, libs/core/preprocessor/include/hpx/preprocessor/config.hpp, libs/core/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp, libs/core/thread_support/include/hpx/thread_support/assert_owns_lock.hpp, libs/full/actions/include/hpx/actions/transfer_base_action.hpp, libs/full/runtime_local/src/runtime_local.cpp, libs/parallelism/algorithms/include/hpx/algorithms/traits/projected.hpp, libs/parallelism/algorithms/include/hpx/algorithms/traits/projected_range.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/make_heap.hpp, src/runtime_distributed.cpp, tests/unit/build/CMakeLists.txt
Fixes #5013.
Testing if this is feasible. In principle it is, but I'd appreciate feedback on if there are any pitfalls that I'm not aware of, especially on Windows. Ideally we only use `HPX_DEBUG` determine if parts of the code should be conditionally compiled/disabled/etc. However, there are a few additional macros that we use:
- `DEBUG`: I could find no reference to anything using this, does anyone know what it's doing in HPX?
- `_DEBUG`: Windows specific, added automatically in debug mode, correct? There are a couple of uses of this one. Can we replace them with `HPX_DEBUG`? (https://github.com/STEllAR-GROUP/hpx/blob/8cb1829d7ae94d1cc078a7ed1a6014c212406a09/src/runtime_distributed.cpp#L546-L551)
- `NDEBUG`: Disables `assert`. We have a few uses of `assert` which are fine, but as far as …
=> Allow mixing debug and release builds

libs/full/include/include/hpx/algorithm.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/remove_copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/remove_copy.hpp, libs/parallelism/algorithms/tests/regressions/scan_shortlength.cpp, libs/parallelism/algorithms/tests/unit/algorithms/remove_copy.cpp, libs/parallelism/algorithms/tests/unit/algorithms/remove_copy_if.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/remove_copy_if_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/remove_copy_range.cpp
This adapts `remove_copy` and `remove_copy_if` to C++20 by providing the ranges overloads according to the Standard. 
Note: _It is based on #5125 in order for the iterator-sentinel_value test cases to run (due to iter_sent.hpp changes) and thus this particular test is commented out for the time being. When #5125 will be merged, proper rebasing will take place._
Proper documentation will be added soon.
=> Adapt remove_copy(_if) to C++20

.circleci/config.yml, libs/full/segmented_algorithms/tests/unit/partitioned_vector_exclusive_scan.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_exclusive_scan2.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_inclusive_scan.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_inclusive_scan2.cpp
Flyby: increase test timeout for segmented algorithms (This is just me being hopeful. It may be that the segmented algorithm tests have started timing out more frequently simply because they run slower. Whether this is due to CircleCI or HPX becoming slower is another question).
=> Don't run segmented algorithms twice on CircleCI

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst
Fixing a minor documentation oversight on the parallel algos I adapted.
=> Fix parallel remove/remove_copy/transform namespace references in docs

libs/core/coroutines/CMakeLists.txt, libs/core/coroutines/include/hpx/coroutines/detail/context_posix.hpp, libs/core/coroutines/src/detail/context_posix.cpp
On Fedora rawhide we get the following error on power and s390
```
In file included from /usr/include/signal.h:315,
from /usr/include/sys/param.h:28,
from /builddir/build/BUILD/hpx-1.6.0/libs/core/coroutines/include/hpx/coroutines/detail/posix_utility.hpp:55,
from /builddir/build/BUILD/hpx-1.6.0/libs/core/coroutines/include/hpx/coroutines/detail/context_posix.hpp:164,
from /builddir/build/BUILD/hpx-1.6.0/libs/core/coroutines/include/hpx/coroutines/detail/context_impl.hpp:129,
from /builddir/build/BUILD/hpx-1.6.0/libs/core/coroutines/include/hpx/coroutines/detail/context_base.hpp:44,
from /builddir/build/BUILD/hpx-1.6.0/libs/core/coroutines/src/detail/context_base.cpp:12:
/builddir/build/BUILD/hpx-1.6.0/libs/core/coroutines/include/hpx/coroutines/detail/context_posix.hpp:224:62: error: …
```
=> Another attempt at fixing the Fedora 35 problem

cmake/HPX_CheckCXXStandard.cmake, cmake/templates/HPXConfig.cmake.in
Fixes CUDA compilation with clang.
@NK-Nikunj would you mind trying this out?
Based on https://github.com/kokkos/kokkos/issues/2520 and https://github.com/masterleinad/kokkos/commit/2a562399fa273952b1910f4c690e4f1a50e9d0ff.
=> Force CMake to set the -std=c++XX flag

libs/core/coroutines/src/detail/context_posix.cpp
I merged #5194 prematurely. The unity build configuration did not work with the given changes, and this attempts to fix it (cscs/clang-newest tests this and is the one which should pass if this is correct).
=> Attempt to fix compilation of context implementations with unity build enabled

.github/workflows/windows_debug.yml, .github/workflows/windows_release.yml, CMakeLists.txt, cmake/HPX_SetupBoost.cmake, components/component_storage/CMakeLists.txt, components/containers/partitioned_vector/CMakeLists.txt, components/containers/unordered/CMakeLists.txt, components/create_component_skeleton.py, components/iostreams/CMakeLists.txt, components/performance_counters/io/CMakeLists.txt, components/performance_counters/memory/CMakeLists.txt, components/performance_counters/papi/CMakeLists.txt, components/process/CMakeLists.txt, libs/core/thread_support/include/hpx/thread_support/thread_specific_ptr.hpp
Removes `HPX_WITH_DEFAULT_TARGETS`, `HPX_WITH_PSEUDO_DEPENDENCIES`, `HPX_WITH_MORE_THAN_64_THREADS`, and `HPX_WITH_NATIVE_TLS`. The last two are definitely unnecessary. `HPX_WITH_PSEUDO_DEPENDENCIES` is always off on Windows, on otherwise, so I've just made it an internal variable. `HPX_WITH_DEFAULT_TARGETS` I could see someone finding useful so please speak up if you think it should be kept around.
=> Remove some minor unnecessary CMake options

tests/performance/local/htts_v2/CMakeLists.txt
Looks like there is an ABI problem with boost regex, this is an attempt to fix it
=> Fix htts_v2 tests linking

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/include/include/hpx/algorithm.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/replace.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/replace.hpp, libs/parallelism/algorithms/tests/unit/algorithms/replace.cpp, libs/parallelism/algorithms/tests/unit/algorithms/replace_copy.cpp, libs/parallelism/algorithms/tests/unit/algorithms/replace_copy_if.cpp, libs/parallelism/algorithms/tests/unit/algorithms/replace_if.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/replace_copy_if_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/replace_copy_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/replace_if_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/replace_range.cpp
This adapts `replace`/`replace_if`/`replace_copy`/`replace_copy_if` to C++20.
Please don't merge yet, docs will be added soon.
=> Adapt replace(_if) to C++20

libs/parallelism/algorithms/include/hpx/parallel/algorithms/copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/copy.hpp
- replaced tag_fallback_invoke header
- replaced tag   with   tag_fallback
- replaced tag_invoke    with   tag_fallback_invoke
From PR #5156
=> Move copy algorithms to tag_fallback_invoke

libs/parallelism/algorithms/include/hpx/parallel/algorithms/adjacent_find.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/adjacent_find.hpp
Replaced tag_invoke with tag_fallback_invoke for adjacent_find algorithm as mentioned here https://github.com/STEllAR-GROUP/hpx/pull/5176#issuecomment-781142703 .
=> Replaced tag_invoke with tag_fallback_invoke for adjacent_find algorithm

libs/core/functional/include/hpx/functional/tag_fallback_invoke.hpp, libs/core/functional/include/hpx/functional/tag_priority_invoke.hpp, libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/for_each.hpp
@hkaiser, @gonidelis, @gnikunj, @srinivasyadav18, @Jedi18, does this explain the helper classes a bit better?
=> Add examples and explanation on when tag_fallback/priority are useful

docs/sphinx/manual/creating_hpx_projects.rst
Looks like this option is not parsed in `add_hpx_executable` so simply removing it.
=> Removing ESSENTIAL option to the doc example

libs/parallelism/algorithms/include/hpx/parallel/algorithms/remove.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/remove.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/remove_copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/replace.hpp, libs/parallelism/algorithms/tests/unit/algorithms/remove_copy.cpp, libs/parallelism/algorithms/tests/unit/algorithms/remove_copy_if.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/remove_copy_if_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/remove_copy_range.cpp
This fixes minor flaws on previous adaptations of mine:
1. It removes unnecessary "async without execution policy" tests.
2. It imposes deprecated algos to use base implementations instead of unquialified  (or adapted qualified ones). In general, I tried to avoid using top level algos.
3. It adds `static_assert`ions for the iterator types of the adapted overloads.
4. _todo:_ Change `tag`s to `tag_fallback`s maybe.
I am curious to see if GCC will complain about deprecations on the lambda calls.
=> Minor adapted algos fixes

libs/core/config/include/hpx/config/compiler_specific.hpp, libs/core/logging/include/hpx/logging/format/named_write.hpp, libs/core/logging/include/hpx/logging/message.hpp, libs/full/compute_cuda/include/hpx/compute/cuda/allocator.hpp, libs/full/compute_cuda/include/hpx/compute/cuda/default_executor.hpp, libs/full/compute_cuda/include/hpx/compute/cuda/detail/launch.hpp
Always define `HPX_COMPUTE_HOST_CODE` for host code, instead of only when compiling with nvcc or hipcc. This is a subtle change, which may in the worst case break someone's code, but I think it's mostly safe. This means that one doesn't have to do `#if !defined(HPX_COMPUTE_DEVICE_CODE)` when one wants something to be compiled only for the host, and `#if defined(HPX_COMPUTE_HOST_CODE)` will be enough (and the two are equivalent after with this PR). I've also cleaned up some other #ifdefs that I think didn't do right in the first place.
=> Always define HPX_COMPUTE_HOST_CODE for host code

CMakeLists.txt, libs/core/iterator_support/CMakeLists.txt, libs/core/iterator_support/include/hpx/iterator_support/boost_iterator_categories.hpp, libs/core/iterator_support/include/hpx/iterator_support/traits/is_iterator.hpp, libs/core/iterator_support/tests/unit/CMakeLists.txt, libs/core/iterator_support/tests/unit/boost_iterator_categories.cpp, libs/core/iterator_support/tests/unit/is_iterator.cpp, libs/core/type_support/include/hpx/type_support/identity.hpp, libs/core/type_support/include/hpx/type_support/lazy_enable_if.hpp
- flyby: add `_t `/`_v` variations for `is_iterator` traits
=> Remove dependency on boost/iterators/iterator_categories.hpp

libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/for_each.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/for_each.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/for_each.hpp
Seperate segmented algorithms for for_each_n and move tag_invoke to tag_fallback_invoke for for_each_n
Removed for_each_n_ function that used to dispatch to segmented/non-segmented algorithms
Added tag_invoke overload to segmented_algorithms/for_each.hpp instead that does the dispatching
Replaced tag_invoke with tag_fallback_invoke so that it properly falls back to the non-segmented overload
Issue #5156 
Issue #5204
=> Seperate segmented algorithms for for_each_n

libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/adjacent_find.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/adjacent_find.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/adjacent_find.hpp
Seperate segmented algorithms for adjacent_find
Any background context you want to provide?
Issue #5156
=> Seperate segmented algorithms for adjacent_find

libs/parallelism/algorithms/include/hpx/parallel/algorithms/replace.hpp, libs/parallelism/algorithms/tests/unit/algorithms/replace.cpp, libs/parallelism/algorithms/tests/unit/algorithms/replace_copy.cpp, libs/parallelism/algorithms/tests/unit/algorithms/replace_copy_if.cpp, libs/parallelism/algorithms/tests/unit/algorithms/replace_if.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/replace_copy_if_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/replace_copy_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/replace_if_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/replace_range.cpp
MInor `hpx::replace` and `hpx::ranges::replace` misses from previous adaptation.
1. Docs signature matching.
2. Add tests for the no-exec-policy overloads.
3. Minor typo in deprecated overload.
=> Fix C++20 replace algo adaptation misses

cmake/HPX_PrintSummary.cmake, libs/core/version/src/version.cpp
Makes the config options more readable as alphabetically ordered, if nobody is against it..
=> Sort printed config options

libs/parallelism/algorithms/include/hpx/parallel/datapar/transform_loop.hpp
Fixes #
- changed sequenced_policy to execution::policy
- parallel::execution::datapar_policy to execution::sequenced_policy
- seq to hpx::execution::seq
With this changes I was able to build and install hpx with Vc on my local system.
=> change namespace for transform_loop.hpp

libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform.hpp
Fixes #5232. @severinstrobl would you mind checking that this works for you as well?
Note: there may be other places that need this treatment, but I'm doing only this one for now.
=> Make sure annotations are used in the binary transform

.jenkins/cscs/env-clang-cuda.sh, .jenkins/cscs/env-gcc-cuda.sh
This reverts to use (some of) the old defaults on Piz Daint from before the upgrade this week.
The cray clang compiler was updated to be based on clang 11 (instead of 10), and the new compiler does not like to link one of our CUDA tests that needs to be looked into separately.
In case it sounds familiar to someone, it does not find a `__global__` CUDA function compiled in a separate translation unit. My attempts at enabling relocatable device code did not help. @G-071 pinging you since I think this is exactly the same issue you had trying to compile octotiger.
=> Use old Piz Daint modules after upgrade

components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_component_impl.hpp, components/containers/unordered/include/hpx/components/containers/unordered/partition_unordered_map_component.hpp, components/iostreams/include/hpx/components/iostreams/ostream.hpp, components/iostreams/src/standard_streams.cpp, components/performance_counters/memory/src/mem_counter_linux.cpp, components/process/include/hpx/components/process/util/posix/wait_for_exit.hpp, libs/core/assertion/src/source_location.cpp, libs/core/config_registry/src/config_registry.cpp, libs/core/coroutines/include/hpx/coroutines/thread_enums.hpp, libs/core/errors/src/exception.cpp, libs/core/execution_base/src/agent_ref.cpp, libs/core/plugin/include/hpx/plugin/detail/dll_dlopen.hpp, libs/core/plugin/include/hpx/plugin/detail/dll_windows.hpp, libs/core/serialization/include/hpx/serialization/basic_archive.hpp, libs/core/testing/include/hpx/modules/testing.hpp, libs/core/testing/src/testing.cpp, libs/core/threading_base/src/thread_description.cpp, libs/full/components_base/include/hpx/components_base/server/wrapper_heap_list.hpp, libs/full/components_base/src/address_ostream.cpp, libs/full/compute/include/hpx/compute/host/numa_binding_allocator.hpp, libs/full/naming_base/src/gid_type.cpp, libs/full/naming_base/src/id_type.cpp, libs/full/program_options/src/cmdline.cpp, libs/full/program_options/src/config_file.cpp, libs/full/program_options/src/convert.cpp, libs/full/program_options/src/parsers.cpp, libs/full/runtime_configuration/include/hpx/runtime_configuration/ini.hpp, libs/full/runtime_configuration/src/ini.cpp, libs/full/thread_executors/src/thread_pool_os_executors.cpp, libs/parallelism/executors/include/hpx/executors/limiting_executor.hpp
This header adds the global std::cin/cout/cerr and wide counterparts to the users' translation unit.
=> Banish <iostream> from library headers

libs/parallelism/execution/CMakeLists.txt, libs/parallelism/execution/include/hpx/execution/algorithms/detail/partial_algorithm.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/detail/single_result.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/just.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/just_on.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/on.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/sync_wait.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/transform.hpp, libs/parallelism/execution/tests/unit/CMakeLists.txt, libs/parallelism/execution/tests/unit/algorithm_just.cpp, libs/parallelism/execution/tests/unit/algorithm_just_on.cpp, libs/parallelism/execution/tests/unit/algorithm_on.cpp, libs/parallelism/execution/tests/unit/algorithm_sync_wait.cpp, libs/parallelism/execution/tests/unit/algorithm_transform.cpp, libs/parallelism/execution/tests/unit/future_then_executor.cpp, libs/parallelism/executors/tests/unit/p0443_executor.cpp
Adds `operator|` overloads for `on`, `sync_wait`, and `transform`. The other algorithms don't really benefit from an `operator|` overload.
Also builds on #5237.
=> P1897 operator| overloads

libs/parallelism/execution/CMakeLists.txt, libs/parallelism/execution/include/hpx/execution/algorithms/detail/single_result.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/just.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/just_on.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/on.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/sync_wait.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/transform.hpp, libs/parallelism/execution/tests/unit/CMakeLists.txt, libs/parallelism/execution/tests/unit/algorithm_just.cpp, libs/parallelism/execution/tests/unit/algorithm_just_on.cpp, libs/parallelism/execution/tests/unit/algorithm_on.cpp, libs/parallelism/execution/tests/unit/algorithm_sync_wait.cpp, libs/parallelism/execution/tests/unit/algorithm_transform.cpp, libs/parallelism/execution/tests/unit/future_then_executor.cpp, libs/parallelism/executors/tests/unit/p0443_executor.cpp
Also makes (previously and newly added) P1897 algorithms customization point objects. Adds tests for newly added algorithms, and expands those for `transform` and `sync_wait`.
Part of #5045.
There are two decisions I'm punting until a later point unless someone has a clear opinion on them right now:
1. Should `just{,_on}` allow storing references? Currently all values are copied internally. There's always `std::ref` in the meantime. Just as another point of reference, libunifex seems to also not store references.
2. The default `sync_wait` makes certain assumptions about running on the HPX runtime, which makes it not quite as generic as it could be. On the other hand one can always customize it for the cases where it's needed.
=> Add P1897 just, just_on, and on algorithms

libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_reduce.hpp
This is sort of a follow-up to #5232. Similar to the other parallel algorithms, `hpx::transform_reduce` should support annotations. I'm not sure this is the best way to handle the annotations, as really there are two functors involved, one for the reduction and one for the transformation/conversion. With the proposed implementation both can be annotated, but the annotation of the reduction takes precedence.
=> Support annotations in hpx::transform_reduce

libs/full/agas_base/src/symbol_namespace.cpp
Fixes: https://github.com/STEllAR-GROUP/phylanx/issues/1321
=> Correcting target ids for symbol_namespace::iterate

libs/core/iterator_support/tests/unit/counting_iterator.cpp
With certain seeds the test would attempt to compute the remainder of division by zero.
=> Avoid modulo by zero in counting_iterator test

libs/core/thread_pools/include/hpx/thread_pools/scheduling_loop.hpp, libs/core/threading_base/include/hpx/threading_base/scheduler_base.hpp, libs/full/async_cuda/include/hpx/async_cuda/custom_gpu_api.hpp, libs/full/async_cuda/src/cuda_future.cpp, libs/full/async_cuda/tests/unit/cuda_future.cpp, libs/full/async_mpi/include/hpx/async_mpi/mpi_future.hpp, libs/full/async_mpi/src/mpi_future.cpp
- Return a status enum from the polling functions to indicate if the scheduler should call the idle callback (useful if polling is the only thing done on a separate pool, and the pool would otherwise call the idle callback even if there's polling to be done).
- The CUDA polling function used to spin waiting for events to complete. As far as I can tell this was unintentional (@biddisco? the iterator was not incremented on `cudaErrorNotReady`).
- Avoid quadratic worst-case complexity in the CUDA polling function in terms of the number of active futures (if every future is ready every iteration would shift the remaining elements to the front when calling `vector::erase`).
- Use CUDA host pinned memory in the `cuda_future` test to actually enable asynchronous data transfers.
=> Small fixes and improvements to CUDA/MPI polling

libs/full/init_runtime/include/hpx/hpx_init.hpp, libs/full/init_runtime/include/hpx/hpx_init_impl.hpp, libs/full/init_runtime/tests/unit/runtime_type.cpp
Use std::function in public APIs
Use std::function in public APIs: https://github.com/STEllAR-GROUP/hpx/issues/4987
=> Replacing util::function_nonser on std::function in hpx_init

libs/parallelism/async_combinators/include/hpx/async_combinators/split_future.hpp, libs/parallelism/lcos_local/tests/unit/split_future.cpp
Analogous to the case of std::pair, it should be possible to split a `hpx::future<std::tuple<Ts...>>` into `std::tuple<hpx::future<Ts>...>`.
=> Allow splitting of futures holding std::tuple

docs/sphinx/examples/1d_stencil.rst, docs/sphinx/examples/accumulator.rst, docs/sphinx/examples/fibonacci.rst, docs/sphinx/examples/interest_calculator.rst
Updated the source code includes in the examples documentation, because the source files are not exactly the same anymore.
Worst case, source code blocks are empty: [accumulator examples](https://hpx-docs.stellar-group.org/latest/html/examples/accumulator.html)
=> Fixed source file line statements in examples documentation

libs/parallelism/algorithms/include/hpx/parallel/datapar/iterator_helpers.hpp, libs/parallelism/algorithms/include/hpx/parallel/datapar/loop.hpp, libs/parallelism/algorithms/include/hpx/parallel/datapar/transform_loop.hpp, libs/parallelism/algorithms/include/hpx/parallel/datapar/zip_iterator.hpp, libs/parallelism/algorithms/tests/regressions/CMakeLists.txt, libs/parallelism/algorithms/tests/regressions/for_each_datapar.cpp
- The len variable in initialised to count but did not use rightly in the loop.
- replace **count** with **len**, must be a typo. 
https://github.com/STEllAR-GROUP/hpx/pull/5235#issuecomment-814671031
=> Fix Segmentation fault on foreach_datapar_zipiter

.jenkins/cscs/env-clang-cuda.sh, libs/full/async_cuda/tests/unit/cuda_future.cpp, libs/full/async_cuda/tests/unit/saxpy.cu
Updating clang cuda config to use Clang 11 resulted in a undefined symbol for `saxpy` in `cuda_future.cpp` unit test, `nm` shows:
```
Clang 11                                                                        
saxpy.cu.o:0000000000000000 T __device_stub__saxpy(int, float, float *, float *)                         
Clang 10                                                                        
saxpy.cu.o:0000000000000000 T saxpy(int, float, float *, float *)
```
Not sure if it's a bug in Clang / Clang cuda or our own cmake config.
The temporary fix is just moving the apply function in the `saxpy.cu` file.
=> Fix Clang 11 cuda_future test bug

libs/core/synchronization/CMakeLists.txt, libs/core/synchronization/include/hpx/synchronization/async_rw_mutex.hpp, libs/core/synchronization/tests/unit/CMakeLists.txt, libs/core/synchronization/tests/unit/async_rw_mutex.cpp
Adds an `async_rw_mutex` (name not finalized, but I think this describes it fairly well). Instead of directly locking a mutex, the async mutex returns senders that give access to a resource when scheduled. The `rw` part means that access can be read-only (shared, multiple concurrent readers allowed), or exclusively read-write.
This is based on an implementation used in DLA-Future where they protect access to tiles of a matrix in this fashion. That mechanism is based on futures/promises and custom for their matrix class. This is an attempt at a more generic version.
Contains #5274 so the diff is rather large.
=> Add async_rw_mutex based on senders

cmake/HPX_AddCompileFlag.cmake
Issue: `CXX` compile flags were also propagated to `nvcc`, which caused build problems with the new CUDA setup necessary for #5283
Solution: Add the flag with the compile language generator expression even when no config (Release/Debug...) is specified.
=> Fix cmake bug, now propagate flag with right language

libs/core/execution_base/include/hpx/execution_base/sender.hpp
Same problem as https://github.com/STEllAR-GROUP/hpx/pull/4912. I've set a reminder for myself to come back and add an actual regression test for this.
=> Fix compilation of sender CPOs with nvcc

.jenkins/cscs/Jenkinsfile, .jenkins/cscs/env-gcc-10.sh, .jenkins/cscs/slurm-constraint-gcc-10.sh, examples/transpose/transpose_serial_vector.cpp
This also triggered the error reported in https://github.com/STEllAR-GROUP/hpx/issues/5275. I've simply made the conversion explicit, but I don't know if there's a more proper fix for the issue.
=> Add GCC 11 builder to jenkins

cmake/HPX_AddConfigTest.cmake
In cases where libatomic does not actually exist we still attempted to link with libatomic later for 128-bit atomics. This tries to fix that.
@G-071 would you mind trying this?
=> Attempt to fix checking for libatomic

libs/core/serialization/include/hpx/serialization/serialize_buffer.hpp
This is needed for @NanmiaoWu's work on the SHAD backend.
=> Adding resize() to serialize_buffer allowing to shrink its size

libs/core/execution_base/include/hpx/execution_base/sender.hpp, libs/core/execution_base/tests/unit/basic_sender.cpp
Mainly fixes the `is_sender` trait. It was returning true for things like `int`. The reason was a missing constraint in the fallback which was meant to apply for executors. It was treating `int` as an executor. Purely my mistake, but in the interest of simplicity I've removed the fallback completely. In my understanding there's already been quite some discussion about how executors should not be treated as schedulers, and especially not as senders, implicitly.
I've also applied small fixes to the `is_executor` trait and the schedule CPO (which was using `is_executor` rather than `is_scheduler` as a constraint).
=> Fix is_sender trait and other small fixes to p0443 traits

libs/core/hardware/include/hpx/hardware/timestamp/linux_generic.hpp
Fixes #5333
@diehlpk could you please check whether this solves your issue?
=> Making sure hpx::util::hardware::timestamp() is always defined

libs/parallelism/execution/CMakeLists.txt, libs/parallelism/execution/include/hpx/execution/algorithms/keep_future.hpp, libs/parallelism/executors/tests/unit/p0443_executor.cpp
This solves the problem of trying to use a `shared_future<noncopyable_type>` with e.g. `on` or `sync_wait` which fails because the algorithms have to copy the value internally (which obviously does not work with noncopyable types). This adds a wrapper algorithm `keep_future` (other name suggestions?) which calls `set_value` on receivers connected to futures with the future instead of the contained value.
Note: This could very well be a better default than the current implementation of futures as senders. There's always `unwrapping` for dealing with futures in continuations.
Builds on #5274 since it requires some fixes to `on`. Only the last commit is new.
=> Add keep_future algorithm

libs/core/synchronization/include/hpx/synchronization/async_rw_mutex.hpp
Just a little convenience for the cases when one doesn't want to/can't use the implicit conversion.
Edit: Flyby: initialize the `value` member in `async_rw_mutex` in the member initializer list instead of in the constructor body, to have it work for non-default constructible types.
=> Add get member functions to async_rw_mutex proxy objects for explicitly getting the wrapped value

libs/core/functional/include/hpx/functional/tag_fallback_invoke.hpp, libs/core/functional/include/hpx/functional/tag_invoke.hpp, libs/core/functional/include/hpx/functional/tag_priority_invoke.hpp
The goal is to streamline the implementation of `tag_invoke` and friends. 
@msimberg, @K-ballo, if you could spare a minute, I'd appreciate a second pair of eyes as I'm not sure that the proposed changes will not subtly change overload resolution.
=> Simplify tag_invoke and friends

libs/parallelism/execution/include/hpx/execution/executors/execution_parameters.hpp
Fixes #5338
- static cast [result](https://github.com/STEllAR-GROUP/hpx/blob/timed_executors/libs/parallelism/execution/include/hpx/execution/executors/execution_parameters.hpp#L675) to `const*`
=> Fix timed_executor static cast conversion

libs/parallelism/execution/include/hpx/execution/executors/execution_parameters.hpp, libs/parallelism/execution/tests/unit/executor_parameters_dispatching.cpp
=> Fixing timed_executor specializations of customization points

libs/parallelism/executors/include/hpx/executors/sequenced_executor.hpp
@srinivasyadav18 this should fix your build error on the GCC 11 build.
=> Make the sequenced_executor processing_units_count member function const

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/include_local/include/hpx/local/algorithm.hpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithms/lexicographical_compare.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/lexicographical_compare.hpp, libs/parallelism/algorithms/tests/unit/algorithms/lexicographical_compare.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/lexicographical_compare_range.cpp
Adapted lexicographical_compare to C++ 20 and added container overloads. (range and sentinel)
Issue #4822
Issue #3646
Issue #1668
=> Adapt lexicographical_compare to C++20

libs/core/debugging/src/print.cpp, libs/full/async_mpi/include/hpx/async_mpi/mpi_executor.hpp, libs/full/async_mpi/include/hpx/async_mpi/mpi_future.hpp, libs/full/async_mpi/src/mpi_future.cpp, libs/full/async_mpi/tests/unit/mpi_ring_async_executor.cpp
The mpi_ring_async_executor_test occasionally failed because
the limiting executor was calling find_if on a vector that
was modified by the mpi polling thread.
Instead of allowing external checks (limiting executor) to
access the vector, we use an atomic counter that only the mpi
polling thread increments/decrements and stores the number
of futures/requests in flight. The limiting executor can safely
read this value from any thread.
=> Fix a race condition in async mpi affecting limiting executor

.github/workflows/windows_debug.yml, .github/workflows/windows_release.yml, cmake/HPX_CompilerFlagsTargets.cmake, examples/gtest_emulation/CMakeLists.txt, examples/hello_world_component/CMakeLists.txt, examples/hello_world_component/hello_world_client.cpp, tests/unit/build/CMakeLists.txt
Attempts to fix #5099 properly. The `HPX_DEBUG` definition was being set with a generator expression based on the build type of the project being built, meaning it was not consistent between HPX and consumers as it was meant to be.
@rbyshko would you mind trying this out? Locally I can now mix release/debug builds freely in the example you provided.
I still have to figure out the testing situation for this on CI, hence a draft.
=> Make sure HPX_DEBUG is set based on HPX's build type, not consuming project's build type

examples/quickstart/init_globally.cpp, libs/core/execution_base/include/hpx/execution_base/this_thread.hpp, libs/core/execution_base/src/this_thread.cpp, libs/core/thread_pools/include/hpx/thread_pools/scheduled_thread_pool.hpp, libs/core/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp, libs/core/threading_base/include/hpx/threading_base/scheduler_base.hpp, libs/core/threading_base/include/hpx/threading_base/thread_pool_base.hpp, libs/core/threading_base/src/scheduler_base.cpp, libs/full/async_cuda/src/cuda_future.cpp, libs/full/async_mpi/src/mpi_future.cpp, libs/full/command_line_handling_local/examples/CMakeLists.txt, libs/full/command_line_handling_local/tests/CMakeLists.txt, libs/full/init_runtime/tests/unit/CMakeLists.txt, libs/full/init_runtime/tests/unit/shutdown_suspended_thread.cpp, libs/full/init_runtime_local/tests/CMakeLists.txt, libs/full/init_runtime_local/tests/unit/CMakeLists.txt, libs/full/init_runtime_local/tests/unit/shutdown_suspended_thread_local.cpp, libs/full/runtime_configuration/src/runtime_configuration.cpp, libs/full/runtime_distributed/src/server/runtime_support_server.cpp, libs/full/runtime_local/src/runtime_local.cpp, libs/full/threadmanager/include/hpx/modules/threadmanager.hpp, libs/full/threadmanager/src/threadmanager.cpp, libs/parallelism/execution/tests/unit/standalone_thread_pool_executor.cpp, tests/performance/local/future_overhead.cpp, tests/performance/local/libcds_hazard_pointer_overhead.cpp
Fixes (or at least improves) the termination detection used in the occasionally timing-out `standalone_thread_pool_executor` test.
Using the thread-local task counts to decide if it's ok to stop a thread pool is racey since the total count can come out to zero even if there are tasks remaining (if stealing is enabled). This introduces a pool-global thread count that can be used instead to check if there are tasks remaining.
However, there are further problems which is why I'm leaving this as a draft:
- I think the interaction between the new task count and background task count is also racey (but less likely to fail).
- Scheduling tasks from one thread pool to another may lead to similar races when checking if the full runtime can be shutdown.
- MPI/CUDA polling is not taken into account …
=> "Fix" termination detection

libs/core/logging/include/hpx/logging/manipulator.hpp, libs/core/logging/include/hpx/modules/logging.hpp, libs/core/logging/src/logging.cpp, libs/full/init_runtime/CMakeLists.txt, libs/full/init_runtime/include/hpx/init_runtime/detail/init_logging.hpp, libs/full/init_runtime/src/hpx_init.cpp, libs/full/init_runtime/src/init_logging.cpp, libs/full/init_runtime_local/include/hpx/init_runtime_local/detail/init_logging.hpp, libs/full/init_runtime_local/src/init_logging.cpp, libs/full/init_runtime_local/src/init_runtime_local.cpp, libs/full/runtime_configuration/src/runtime_configuration.cpp
- flyby: simplify logging initialization, moving code to source files
@diehlpk you should be able to use this to enable logging from the command line and disable it first thing in `hpx_main` (add `--hpx:debug-hpx-log=<filename>` on the command line, and insert a `hpx::util::disable_logging(hpx::destination_hpx);` in `hpx_main`). This might help diagnosing the startup hangs on summit.
=> Adding enable_logging/disable_logging API functions

CMakeLists.txt
I unintentionally re-enabled the build unit test with pkgbuild on macOS in #5330. This turns it off by default on macOS.
=> Disable pkgconfig by default again on macOS

.jenkins/lsu/env-clang-9.sh, libs/core/logging/src/logging.cpp, libs/full/init_runtime_local/src/init_logging.cpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/minmax.hpp
These changes give me 10-15% improvement of the sequential execution speed (which should translate to some speedups for parallel execution as well).
=> Slight improvements to min/max/minmax_element algorithms

.jenkins/cscs/env-clang-cuda.sh, components/performance_counters/io/src/io_counters.cpp
On the clang-cuda configuration the build unit test hangs when mixing Debug and... Debug. Other mixes are fine. I have no idea why this is the case. The non-Cray clang 12 configuration has no problems with that particular mix.
=> More changes to clang-cuda Jenkins configuration

libs/core/iterator_support/include/hpx/iterator_support/traits/is_iterator.hpp, libs/full/compute_cuda/include/hpx/compute/cuda/transfer.hpp, libs/parallelism/algorithms/include/hpx/algorithms/traits/pointer_category.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/move.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/transfer.hpp
- this improves the detection of contiguous trivially copyable sequences
for which copy and move can fall back to memcpy
- flyby: adding traits::is_contiguous_iterator
- flyby: modernize transfer algorithm implementations
The sequential version gives me about 40% speedup when copying `vector<>`s of trivially copyable types.
=> Slight performance improvement for hpx::copy and hpx::move et.al.

docs/CMakeLists.txt
They're added through the `HPX_LIBS` variable just below the manual listing...
=> Remove unnecessary explicit listing of library modules.rst files in CMakeLists.txt

libs/full/collectives/include/hpx/collectives/gather.hpp
@msimberg sorry for this oversight... Could we add this to the release, please?
=> Fixing wrong usage of std::forward

docs/sphinx/manual/launching_and_configuring_hpx_applications.rst, libs/core/config/include/hpx/config.hpp, libs/core/schedulers/include/hpx/schedulers/local_priority_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/local_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/thread_queue.hpp, libs/core/thread_pools/include/hpx/thread_pools/scheduling_loop.hpp, libs/core/threading_base/include/hpx/threading_base/create_thread.hpp, libs/core/threading_base/include/hpx/threading_base/create_work.hpp, libs/core/threading_base/include/hpx/threading_base/scheduler_base.hpp, libs/core/threading_base/include/hpx/threading_base/thread_pool_base.hpp, libs/core/threading_base/src/execution_agent.cpp, libs/core/threading_base/src/scheduler_base.cpp, libs/core/threading_base/src/thread_pool_base.cpp
This PR is the result of some debuggin in DLA-Future of a deadlock caused by a combination of our scheduler and a blocking MPI call being made in an HPX thread. We know that the latter is very naughty, but at the same time it can lead to performance benefits in this particular case (lots of small tasks if one does not do the blocking call). We're looking into alternatives, but one of the changes here also helps for the particular situation. I'm happy to drop it though as it's only a question of default configuration values. That said, the changes here are:
- Add more extensive logging to the scheduling loop. Previously the state of an HPX thread was logged only once the context was changed back to the scheduler. This PR adds logging both before and after threads are scheduled so that one …
=> Extend thread state logging and change default stealing parameters

libs/core/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp
I've re-enabled the cross pool injection test with the shared priority scheduler in the hopes that this maybe fixes the hangs there, but have not tested it myself. Edit: this does not seem to fix that particular problem, so I'm leaving it disabled.
=> Make sure shared priority scheduler steals tasks on the current NUMA domain when (core) stealing is enabled

libs/core/concepts/include/hpx/concepts/has_member_xxx.hpp, libs/core/concepts/include/hpx/concepts/has_xxx.hpp, libs/core/execution_base/include/hpx/execution_base/traits/is_executor.hpp, libs/core/execution_base/include/hpx/execution_base/traits/is_executor_parameters.hpp, libs/core/functional/include/hpx/functional/deferred_call.hpp, libs/core/functional/include/hpx/functional/tag_dispatch.hpp, libs/core/functional/include/hpx/functional/tag_fallback_dispatch.hpp, libs/core/functional/include/hpx/functional/tag_priority_dispatch.hpp, libs/core/type_support/include/hpx/type_support/always_void.hpp, libs/parallelism/execution/include/hpx/execution/executors/execution.hpp, libs/parallelism/execution/include/hpx/execution/executors/fused_bulk_execute.hpp, libs/parallelism/execution/include/hpx/execution/traits/executor_traits.hpp, libs/parallelism/executors/CMakeLists.txt, libs/parallelism/executors/include/hpx/executors/annotating_executor.hpp, libs/parallelism/executors/include/hpx/executors/execution_policy_annotation.hpp, libs/parallelism/executors/include/hpx/executors/parallel_executor.hpp, libs/parallelism/executors/tests/unit/CMakeLists.txt, libs/parallelism/executors/tests/unit/annotating_executor.cpp, libs/parallelism/executors/tests/unit/annotation_property.cpp, libs/parallelism/timed_execution/include/hpx/timed_execution/traits/is_timed_executor.hpp
- flyby: removed obsolete #if defined(HPX_HAVE_CXX17_VARIABLE_TEMPLATES)
- flyby: constexpr variables can be inline
- flyby: modernize execution traits
=> Create generic executor that adds annotations to any other executor

libs/core/properties/include/hpx/properties/property.hpp, libs/parallelism/executors/include/hpx/executors/annotating_executor.hpp, libs/parallelism/executors/include/hpx/executors/execution_policy_annotation.hpp, libs/parallelism/executors/include/hpx/executors/parallel_executor.hpp, libs/parallelism/executors/tests/unit/annotating_executor.cpp
This is mostly a cleanup PR for #5403 simplifying the selection conditions for the various `with_annotation` tag_dispatch overloads.
=> Simplify dispatching to annotation handlers

.jenkins/cscs/env-common.sh
Reducing the cache size since the files count towards a shared quota. Hoping that it won't affect build speeds too dramatically.
=> Reduce max size and number of files in ccache cache

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx17_copy_elision.cpp, libs/core/datastructures/CMakeLists.txt, libs/core/datastructures/include/hpx/datastructures/detail/variant.hpp, libs/core/datastructures/include/hpx/datastructures/optional.hpp, libs/core/datastructures/include/hpx/datastructures/variant.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/let_error.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/let_value.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/on.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/transform.hpp, libs/parallelism/executors/include/hpx/executors/p0443_executor.hpp, libs/parallelism/executors/tests/unit/p0443_executor.cpp
- flyby: using try_catch_exception_ptr in p443_executor, adding support for the `with_annotation` property
This fixes compilation of the sender/receiver tests on MSVC by adding a workaround to `util::optional` and by adding a (slightly) modified version of MPark's variant.
=> Fixing sender/receiver code base to compile with MSVC

libs/core/hardware/CMakeLists.txt, libs/core/hardware/include/hpx/hardware/timestamp.hpp, libs/core/hardware/include/hpx/hardware/timestamp/bgq.hpp, libs/core/hardware/include/hpx/hardware/timestamp/cuda.hpp, libs/core/hardware/include/hpx/hardware/timestamp/linux_generic.hpp, libs/core/hardware/include/hpx/hardware/timestamp/linux_x86_32.hpp, libs/core/hardware/include/hpx/hardware/timestamp/linux_x86_64.hpp, libs/core/hardware/include/hpx/hardware/timestamp/msvc.hpp
This PR provides support for timestamps in CUDA kernels. The output is received in nanosecond duration and more information can be found [here](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#special-registers-globaltimer).
I'm adding CUDA support so that I can use timestamp instead of relying on asm directly within my hpx-kokkos-resilience project.
=> Add CUDA timestamp support to HPX Hardware Clock

CMakeLists.txt, cmake/FindAsio.cmake, cmake/HPX_GeneratePackage.cmake, cmake/HPX_SetupBoost.cmake, cmake/HPX_SetupThreads.cmake, cmake/templates/HPXConfig.cmake.in
Fixes #5412 and #4942.
Removes the custom logic for adding pthread flags and uses `FindThreads` exclusively. The manually added pthread flags were interfering with CMake's detection for if `-pthread` should be added. However, the manually added flags were also not in the public interface, leading to linker errors in certain configurations.
Removing the manually added flags also lead to a different path in `FindThreads.cmake` which was triggering #4942. I've added a workaround for that, which is to filter out the `Threads::Threads` target from the pkgconfig file generation. *This may mean that pkgconfig file users have to add `-pthread` manually*. @stevenrbrandt is this an acceptable workaround for you?
@kordejong this is mostly the same changes that you tested earlier, but since I did …
=> Update logic to find threading library

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/include_local/include/hpx/local/memory.hpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_move.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_move.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_memory.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/result_types.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_move.cpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_move_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_moven.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_move_n_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_move_range.cpp
Adapted uninitialized _move and uninitialized_move_n to C++ 20 and added container overloads. (range and sentinel). Added container tests.
Issue #4822
Issue #3646
Issue #1668
=> Adapt uninitialized_move and uninitialized_move_n to C++ 20

.circleci/config.yml
Conjecture, but I think this will fix the failing "install" step on CircleCI. Running the hello world example with the `setup_remote_docker` key fails with exit code 132 which apparently is sigkill 128 + illegal instruction 4. This started appearing when we merged the changes for datapar (https://github.com/STEllAR-GROUP/hpx/pull/5235).
=> Disable Vc in final docker image created in CI

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/include_local/include/hpx/local/memory.hpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_default_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_default_construct.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_default_construct_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_default_constructn.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_default_construct_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_default_constructn_range.cpp
Adapted uninitialized _default_construct and uninitialized_default_construct_n to C++ 20 and added container overloads. (range and sentinel). Added container tests.
Issue #4822
Issue #3646
Issue #1668
=> Adapt uninitialized_default_construct and uninitialized_default_construct_n to C++ 20

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/include_local/include/hpx/local/memory.hpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_default_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_value_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_default_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_value_construct.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_default_construct_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_default_constructn.cpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_value_construct_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_value_constructn.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_default_construct_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_default_constructn_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_value_construct_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_value_constructn_range.cpp
Adapted uninitialized_value_construct and uninitialized_value_construct_n to C++ 20 and added container overloads. (range and sentinel). Added container tests.
Issue #4822
Issue #3646
Issue #1668
=> Adapt uninitialized_value_construct and uninitialized_value_construct_n to C++ 20

libs/core/type_support/include/hpx/type_support/pack.hpp, libs/parallelism/execution/CMakeLists.txt, libs/parallelism/execution/include/hpx/execution/algorithms/bulk.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/transform.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/when_all.hpp, libs/parallelism/execution/tests/unit/CMakeLists.txt, libs/parallelism/execution/tests/unit/algorithm_bulk.cpp, libs/parallelism/execution/tests/unit/algorithm_test_utils.hpp
This adds the `bulk()` algorithm for the sender/receiver framework
As a flyby this slightly cleans up the `transform` algorithm ~and also fixes an issue with the `when_all` algorithm~ (see #5423).
=> Adding execution::experimental::bulk algorithm

libs/core/serialization/CMakeLists.txt, libs/core/serialization/include/hpx/serialization/array.hpp, libs/core/serialization/include/hpx/serialization/complex.hpp, libs/core/serialization/include/hpx/serialization/detail/vc.hpp, libs/core/serialization/include/hpx/serialization/input_archive.hpp, libs/core/serialization/include/hpx/serialization/map.hpp, libs/core/serialization/include/hpx/serialization/output_archive.hpp, libs/core/serialization/include/hpx/serialization/traits/is_not_bitwise_serializable.hpp, libs/core/serialization/include/hpx/serialization/tuple.hpp, libs/core/serialization/include/hpx/serialization/vector.hpp, libs/core/serialization/tests/unit/CMakeLists.txt, libs/core/serialization/tests/unit/any_serialization.cpp, libs/core/serialization/tests/unit/not_bitwise_serializable.cpp, libs/full/compute/include/hpx/compute/serialization/vector.hpp, libs/full/include/include/hpx/include/traits.hpp
- this also allows for certain types to be normally serialized, still
More explanations of the rationale for this:
HPX so far assumes that only types that are specifically marked as such are bitwise serializable. This is fine in normal situations. Certain systems (like [SHAD](https://github.com/pnnl/SHAD)) however assume the opposite: all types are bitwise serializable by default, and only few require proper serialization. This PR adds an option to HPX that allows to support such systems by defining the new configuration option `HPX_SERIALIZATION_WITH_ALL_TYPES_ARE_BITWISE_SERIALIZABLE=On`. This also adds a new helper macro `HPX_IS_NOT_BITWISE_SERIALIZABLE(T)` which marks `T` as not bitwise serializable.
@msimberg I'd appreciate it if this PR could still make it into the release.
=> This adds support for systems that assume all types are bitwise serializable by default

libs/core/synchronization/tests/unit/async_rw_mutex.cpp, libs/full/async_cuda/tests/unit/transform_stream.cu, libs/full/compute_cuda/tests/performance/synchronize.cu, libs/parallelism/executors/CMakeLists.txt, libs/parallelism/executors/include/hpx/executors/thread_pool_scheduler.hpp, libs/parallelism/executors/tests/unit/CMakeLists.txt, libs/parallelism/executors/tests/unit/thread_pool_scheduler.cpp
I suggest `thread_pool_scheduler` to mirror `thread_pool_executor`, both of which allow scheduling/executing tasks on a given HPX `thread_pool_base`. Other suggestions are welcome.
I'm leaving the "executor" functionality for now in `thread_pool_scheduler` but it's likely that the change to make `execute` a plain algorithm in P2300 will likely be supported. I'll remove it separately (there's a meeting today on P2300, and unless the feedback is very negative I think we can start applying changes from it more widely).
Edit: I also wanted to add that I'm not sure if the thread pool attached to the scheduler should be a "property" or not, so it's currently not one (it's also not a property at the moment for `thread_pool_executor`/`parallel_executor`). If someone has a good argument for either …
=> Rename the new P0443/P2300 executor to thread_pool_scheduler

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/include_local/include/hpx/local/memory.hpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_default_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_value_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_default_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_value_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_memory.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_copy_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_copyn.cpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_default_construct_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_default_constructn.cpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_value_construct_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/uninitialized_value_constructn.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_copy_n_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_copy_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_default_construct_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_default_constructn_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_value_construct_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/uninitialized_value_constructn_range.cpp
Adapted uninitialized copy and uninitialized_copy_n to C++ 20 and added container overloads. (range and sentinel). Added container tests.
Issue #4822
Issue #3646
Issue #1668
=> Adapt uninitialized_copy and uninitialized_copy_n to C++ 20

CMakeLists.txt, cmake/HPX_AddCompileFlag.cmake, cmake/HPX_AddLinkFlag.cmake, cmake/HPX_SetupThreads.cmake
It turns out that we do actually need the `-pthread` flag when using the Cray compiler, so I'm adding it back here for both compilation and linking (#5420 is responsible for the timeouts on the clang-cuda configuration and I missed this before merging). The flag also now gets passed on to consuming projects unlike before #5420.
@kordejong I know you may be tired of rebuilding HPX, but if you have the time I'd be very grateful if you could also test this on your system to ensure that I haven't brought things back to before #5420...
=> Add back explicit -pthread flags when available

libs/parallelism/execution/include/hpx/execution/algorithms/bulk.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/detach.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/ensure_started.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/just.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/let_error.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/let_value.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/make_future.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/on.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/sync_wait.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/transform.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/when_all.hpp, libs/parallelism/execution/tests/unit/algorithm_ensure_started.cpp
I've been a bit unnecessarily frugal when naming template parameters and members in the sender algorithms. This expands them a bit. Suggestions for other/better names are also welcome, or if someone prefers the shorter names please speak up as well.
=> Use more verbose names in sender algorithms

libs/parallelism/algorithms/include/hpx/parallel/algorithms/find.hpp, libs/parallelism/algorithms/tests/unit/algorithms/findend.cpp
The current version just checks the first element in the subsequence and returns the iterator if matches.
It does not check the whole subsequence.
- Replaces typedef reference with auto.
- Removes unused `curr` Iterator variable.
- Uses `mid` and `mid2` to check the whole subsequence.
=> Fix find_end parallel overload

libs/core/synchronization/include/hpx/synchronization/spinlock.hpp, libs/core/thread_support/include/hpx/thread_support/spinlock.hpp
The current implementation of spinlocks uses atomic exchanges on every loop iteration that can cause excess contention due to cache coherence policies within the CPU. This will lead to overwhelming traffic on the bus reducing the performance of the locks. The backoff through yield does reduce contention but we can still do better in performance.
I have mitigated this by first checking if the lock can be acquired by loading the value to cache and then spinning on it every iteration. This reduces the contention from every iteration to iterations where the lock has been released by another thread. The improvements will be insignificant for low contention situations (probably an improvement of a couple of nanoseconds) but should be observable for very high contention situations.
=> Improve performance of Spinlocks

cmake/HPX_AddConfigTest.cmake
Fixup for the C+17 PR #5283
A warning for unrecognized parameters in try_compile is issued when CUDA is disabled, this PR makes the parameter optional
=> Make the cuda parameters of try_compile optional

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/core/iterator_support/include/hpx/iterator_support/traits/is_range.hpp, libs/full/collectives/include/hpx/collectives/inclusive_scan.hpp, libs/full/include_local/include/hpx/local/numeric.hpp, libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/inclusive_scan.hpp, libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/transform_inclusive_scan.hpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_adjacent_difference1.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_adjacent_difference2.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_find.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_find2.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_inclusive_scan.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_inclusive_scan2.cpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithms/inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/reduce_by_key.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_numeric.hpp, libs/parallelism/algorithms/tests/regressions/scan_different_inits.cpp, libs/parallelism/algorithms/tests/regressions/scan_non_commutative.cpp, libs/parallelism/algorithms/tests/unit/algorithms/inclusive_scan.cpp, libs/parallelism/algorithms/tests/unit/algorithms/inclusive_scan_tests.hpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/inclusive_scan_range.cpp
Adapted inclusive_scan to C++ 20 and added container overloads. (range and sentinel). Added container tests. Seperated segmented overloads.
Issue #4822
Issue #3646
Issue #1668
Issue #5156
=> Adapt inclusive_scan to C++ 20

cmake/HPX_SetupApex.cmake, cmake/templates/conf.py.in
at https://github.com/UO-OACISS/apex.git, and updating
the APEX documentation link to https://uo-oaciss.github.io/apex.
Moved the APEX repo from my personal workspace on GitHub to the UO-OACISS organization.
=> Changing the APEX repository to the new location

libs/parallelism/lcos_local/include/hpx/lcos_local/channel.hpp
The version check was not accurate. It turns out that the behaviour is also dependent on the GCC version, and the new check is what I *think* is closer to the truth. I have not exhaustively tested the combinations though. This seems to hold for the versions on rostam and on compiler explorer. What I had missed earlier is that the different nvcc versions on compiler explorer of course implicitly change the GCC version as well, leading me to incorrectly think that the bug was dependent on the CUDA version (and I seem to have had the version wrong even if the GCC version would not have changed implicitly).
=> Fix version check for CUDA noexcept/result_of bug

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/collectives/include/hpx/collectives/exclusive_scan.hpp, libs/full/include_local/include/hpx/local/numeric.hpp, libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/exclusive_scan.hpp, libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/transform_exclusive_scan.hpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_exclusive_scan.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_exclusive_scan2.cpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithms/exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_numeric.hpp, libs/parallelism/algorithms/tests/regressions/scan_different_inits.cpp, libs/parallelism/algorithms/tests/regressions/scan_non_commutative.cpp, libs/parallelism/algorithms/tests/unit/algorithms/exclusive_scan.cpp, libs/parallelism/algorithms/tests/unit/algorithms/exclusive_scan2.cpp, libs/parallelism/algorithms/tests/unit/algorithms/exclusive_scan_bad_alloc.cpp, libs/parallelism/algorithms/tests/unit/algorithms/exclusive_scan_exception.cpp, libs/parallelism/algorithms/tests/unit/algorithms/exclusive_scan_validate.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/exclusive_scan_range.cpp
Adapted exclusive_scan to C++ 20 and added container overloads. (range and sentinel). Added container tests. Seperated segmented overloads.
Issue #4822
Issue #3646
Issue #1668
Issue #5156
=> Adapt exclusive_scan to C++20

docs/sphinx/api/public_api.rst, libs/full/include_local/include/hpx/local/numeric.hpp, libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/transform_exclusive_scan.hpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_transform_scan.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_transform_scan2.cpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/transform_exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_numeric.hpp, libs/parallelism/algorithms/tests/regressions/scan_different_inits.cpp, libs/parallelism/algorithms/tests/unit/algorithms/transform_exclusive_scan.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/transform_exclusive_scan_range.cpp
Adapted transform_exclusive_scan to C++ 20 and added container overloads. (range and sentinel). Added container tests. Seperated segmented overloads.
Issue #4822
Issue #3646
Issue #1668
Issue #5156
=> Adapt transform_exclusive_scan to C++ 20

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/include_local/include/hpx/local/numeric.hpp, libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/transform_inclusive_scan.hpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_transform_scan.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_transform_scan2.cpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/transform_inclusive_scan.hpp, libs/parallelism/algorithms/tests/regressions/scan_different_inits.cpp, libs/parallelism/algorithms/tests/regressions/transform_inclusive_scan_4786.cpp, libs/parallelism/algorithms/tests/regressions/transform_inclusive_scan_4787.cpp, libs/parallelism/algorithms/tests/unit/algorithms/transform_inclusive_scan.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/transform_inclusive_scan_range.cpp
Adapted transform_inclusive_scan to C++ 20 and added container overloads. (range and sentinel). Added container tests. Seperated segmented overloads.
Issue #4822
Issue #3646
Issue #1668
Issue #5156
=> Adapt transform_inclusive_scan to C++ 20

CMakeLists.txt, init/CMakeLists.txt, libs/core/config/include/hpx/config.hpp, libs/core/coroutines/include/hpx/coroutines/detail/tss.hpp, libs/core/coroutines/src/detail/tss.cpp, libs/core/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp, libs/core/threading_base/CMakeLists.txt, libs/core/threading_base/include/hpx/threading_base/detail/get_default_pool.hpp, libs/core/threading_base/include/hpx/threading_base/detail/get_default_timer_service.hpp, libs/core/threading_base/include/hpx/threading_base/register_thread.hpp, libs/core/threading_base/include/hpx/threading_base/set_thread_state.hpp, libs/core/threading_base/include/hpx/threading_base/set_thread_state_timed.hpp, libs/core/threading_base/include/hpx/threading_base/thread_specific_ptr.hpp, libs/core/threading_base/src/get_default_pool.cpp, libs/core/threading_base/src/get_default_timer_service.cpp, libs/core/threading_base/src/thread_helpers.cpp, libs/parallelism/execution/include/hpx/execution/algorithms/ensure_started.hpp, libs/parallelism/lcos_local/include/hpx/lcos_local/and_gate.hpp, wrap/CMakeLists.txt
- Adds Asio and Boost headers to the precompiled headers target
- Does some small rearranging to reduce Asio includes
- ifdefs out more of thread local storage when it's disabled
Regarding the first point, `boost/config.hpp` was problematic. We force `hpx/config.hpp` to be included before `boost/config.hpp`. However, I can't find any reasoning about *why* that's the case. It looks like the current check was introduced in https://github.com/STEllAR-GROUP/hpx/commit/a370734ce21e700aa5e7a7e9a119865178b74f47, and the accompanying intel compiler config is gone since then. Does anyone know? Is it also a problem on Windows?
=> More precompiled headers

examples/jacobi/jacobi_component/server/solver.hpp
With networking on, `find_all_localities` is included implicitly. In certain configurations with networking off, `find_all_localities` is no longer included. This explicitly includes `hpx/runtime.hpp`.
Flyby: format the file.
=> Add missing header to jacobi_component/server/solver.hpp

libs/parallelism/algorithms/include/hpx/parallel/datapar/transform_loop.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/detail/algorithm_result.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/detail/select_partitioner.hpp, libs/parallelism/algorithms/tests/regressions/for_each_datapar.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/copy_datapar.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/copyn_datapar.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/count_datapar.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/countif_datapar.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/foreach_datapar.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/foreach_datapar_zipiter.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/foreachn_datapar.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/transform_binary2_datapar.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/transform_binary_datapar.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/transform_datapar.cpp, libs/parallelism/algorithms/tests/unit/datapar_algorithms/transform_reduce_binary_datapar.cpp, libs/parallelism/execution/tests/regressions/lambda_arguments_2403.cpp, libs/parallelism/execution/tests/regressions/lambda_return_type_2402.cpp, libs/parallelism/executors/include/hpx/executors/datapar/execution_policy.hpp, libs/parallelism/executors/include/hpx/executors/datapar/execution_policy_fwd.hpp, libs/parallelism/executors/include/hpx/executors/exception_list.hpp, tests/performance/local/transform_reduce_binary_scaling.cpp
Fixes #5494. I just did a find-and-replace, hoping there are no surprises.
=> Rename simdpar to par_simd

libs/parallelism/algorithms/tests/unit/container_algorithms/exclusive_scan_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/inclusive_scan_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/transform_exclusive_scan_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/transform_inclusive_scan_range.cpp
Will lead to a segmentation fault if end_len happens to be the vector size value.
=> Minor bug fix in transform exclusive and inclusive scan tests

libs/core/serialization/CMakeLists.txt, libs/core/serialization/include/hpx/serialization/access.hpp, libs/core/serialization/include/hpx/serialization/array.hpp, libs/core/serialization/include/hpx/serialization/detail/constructor_selector.hpp, libs/core/serialization/include/hpx/serialization/detail/non_default_constructible.hpp, libs/core/serialization/include/hpx/serialization/detail/pointer.hpp, libs/core/serialization/include/hpx/serialization/detail/polymorphic_nonintrusive_factory.hpp, libs/core/serialization/include/hpx/serialization/detail/serialize_collection.hpp, libs/core/serialization/include/hpx/serialization/input_archive.hpp, libs/core/serialization/include/hpx/serialization/map.hpp, libs/core/serialization/include/hpx/serialization/output_archive.hpp, libs/core/serialization/include/hpx/serialization/std_tuple.hpp, libs/core/serialization/include/hpx/serialization/traits/is_not_bitwise_serializable.hpp, libs/core/serialization/include/hpx/serialization/traits/polymorphic_traits.hpp, libs/core/serialization/include/hpx/serialization/tuple.hpp, libs/core/serialization/include/hpx/serialization/vector.hpp, libs/core/serialization/tests/unit/not_bitwise_serializable.cpp, libs/full/compute/include/hpx/compute/serialization/vector.hpp, libs/full/include/include/hpx/hpx.hpp, libs/full/performance_counters/src/counters.cpp, libs/parallelism/futures/include/hpx/futures/future.hpp
These changes are needed to make the changes from #5435 actually work.
@msimberg I hate to ask, but would it be possible for this to still get into V1.7? We discovered this issue just now. Nan will test it on her side today and report back asap. I think this would be a very low risk change as it doesn't touch on code that is used for normal operation.
=> More fixes to enable for all types to be assumed to be bitwise copyable

.circleci/config.yml, .github/workflows/linux_debug.yml, .github/workflows/linux_hip.yml, .github/workflows/linux_release_fetchcontent.yml, .github/workflows/linux_sanitizers.yml, .github/workflows/windows_debug.yml, .github/workflows/windows_release.yml, .jenkins/cscs-perftests/env-perftests.sh, .jenkins/cscs/env-clang-10.sh, .jenkins/cscs/env-clang-8.sh, .jenkins/cscs/env-clang-9.sh, .jenkins/cscs/env-clang-apex.sh, .jenkins/cscs/env-clang-newest.sh, .jenkins/cscs/env-clang-oldest.sh, .jenkins/cscs/env-common.sh, .jenkins/cscs/env-gcc-10.sh, .jenkins/cscs/env-gcc-cuda.sh, .jenkins/cscs/env-gcc-newest.sh, .jenkins/cscs/env-gcc-oldest.sh, CMakeLists.txt, cmake/HPX_UpdateGitDocs.cmake, cmake/templates/HPXConfig.cmake.in, components/create_component_skeleton.py, docs/sphinx/manual/building_hpx.rst, docs/sphinx/manual/creating_hpx_projects.rst, docs/sphinx/quickstart.rst, examples/gtest_emulation/CMakeLists.txt, examples/hello_world_component/CMakeLists.txt, tests/unit/build/fetchcontent/CMakeLists.txt, tools/docker/Dockerfile
In accordance to [this comment](https://github.com/STEllAR-GROUP/hpx/pull/5283/files#r625587954)
CMake 3.18 is necessary to handle the cuda_std_17 compiler feature
TODO
=> Require CMake 3.18 as it is already a requirement for CUDA

libs/parallelism/executors/tests/unit/thread_pool_scheduler.cpp
Added predicates to the `wait_for`s. Without them the waits may fail even if the the tasks were executed (and since https://github.com/STEllAR-GROUP/hpx/blob/0bfa445daefecb5ab4f8a4bb1873c3b92ceed468/libs/parallelism/executors/tests/unit/thread_pool_scheduler.cpp#L1229 seems to not fail, it must be the case here).
=> Attempt to fix thread_pool_scheduler test

libs/core/execution_base/CMakeLists.txt, libs/core/execution_base/include/hpx/execution_base/completion_scheduler.hpp, libs/core/execution_base/include/hpx/execution_base/execution.hpp, libs/core/execution_base/include/hpx/execution_base/receiver.hpp, libs/core/iterator_support/include/hpx/iterator_support/counting_iterator.hpp, libs/core/iterator_support/include/hpx/iterator_support/counting_shape.hpp, libs/core/iterator_support/include/hpx/iterator_support/traits/is_range.hpp, libs/core/tag_dispatch/include/hpx/functional/tag_dispatch.hpp, libs/core/tag_dispatch/include/hpx/functional/tag_fallback_dispatch.hpp, libs/core/tag_dispatch/include/hpx/functional/tag_priority_dispatch.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/bulk.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/on.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/transform.hpp, libs/parallelism/executors/CMakeLists.txt, libs/parallelism/executors/include/hpx/executors/scheduler_executor.hpp, libs/parallelism/executors/include/hpx/executors/thread_pool_scheduler.hpp, libs/parallelism/executors/include/hpx/executors/thread_pool_scheduler_bulk.hpp, libs/parallelism/executors/tests/unit/thread_pool_scheduler.cpp
Customizes `bulk` for `thread_pool_scheduler`. The customization currently does *not* do any chunking or hierarchical spawning like the `parallel_executor` does. Hierarchical spawning will be a must that I will do separately. I also think the chunking should be the responsibility of the scheduler, rather than the algorithms, but there may be trade-offs I'm missing (and things like this should not be necessary: https://github.com/STEllAR-GROUP/hpx/blob/master/libs/full/compute_cuda/include/hpx/compute/cuda/default_executor_parameters.hpp).
The `get_completion_scheduler` customizations are somewhat verbose, but as far as I can tell it's all mostly necessary. If there are ideas on simplifying them I'd be happy to hear them. Also, all senders don't have a customization since I'm not yet sure …
=> Add get_completion_scheduler CPO and customize bulk for thread_pool_scheduler

.circleci/config.yml, cmake/packaging/rpm/Changelog.txt, docs/sphinx/contributing/release_procedure.rst, docs/sphinx/quickstart.rst, docs/sphinx/releases.rst, docs/sphinx/releases/whats_new_1_7_1.rst, tools/roll_release.sh
Cherry-picks release notes from 1.7.1 branch, and slightly updates the release procedures. Also adds a basic sanity check to the `roll_release.sh` script (can/should be expanded, feel free to comment with ideas).
=> Minor release changes from 1.7.1

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx20_std_ranges_iter_swap.cpp, docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/include_local/include/hpx/local/algorithm.hpp, libs/parallelism/algorithms/CMakeLists.txt, libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/rotate.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/partial_sort.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/partition.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/reverse.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/sort.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/swap_ranges.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/swap_ranges.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/result_types.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/zip_iterator.hpp, libs/parallelism/algorithms/tests/unit/algorithms/swapranges.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/CMakeLists.txt, libs/parallelism/algorithms/tests/unit/container_algorithms/swap_ranges_range.cpp
Adapted swap_ranges to C++ 20 and added container overloads. (range and sentinel). Added container tests.
Issue #4822
Issue #3646
Issue #1668
=> Adapt swap_ranges to C++ 20

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/include_local/include/hpx/local/algorithm.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/unique.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/unique.hpp, libs/parallelism/algorithms/tests/performance/benchmark_unique.cpp, libs/parallelism/algorithms/tests/performance/benchmark_unique_copy.cpp, libs/parallelism/algorithms/tests/unit/algorithms/unique_copy_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/unique_tests.hpp, libs/parallelism/algorithms/tests/unit/container_algorithms/unique_copy_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/unique_range.cpp
Adapted unique and unique_copy to C++ 20 and added container overloads. (range and sentinel). Added container tests.
Issue #4822
Issue #3646
=> Adapt unique and unique_copy to C++ 20

docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, libs/full/include_local/include/hpx/local/algorithm.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/stable_sort.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/unique.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/stable_sort.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/unique.hpp, libs/parallelism/algorithms/tests/performance/benchmark_unique.cpp, libs/parallelism/algorithms/tests/performance/benchmark_unique_copy.cpp, libs/parallelism/algorithms/tests/unit/algorithms/stable_sort.cpp, libs/parallelism/algorithms/tests/unit/algorithms/stable_sort_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/unique_copy_tests.hpp, libs/parallelism/algorithms/tests/unit/algorithms/unique_tests.hpp, libs/parallelism/algorithms/tests/unit/container_algorithms/stable_sort_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/stable_sort_range_tests.hpp, libs/parallelism/algorithms/tests/unit/container_algorithms/unique_copy_range.cpp, libs/parallelism/algorithms/tests/unit/container_algorithms/unique_range.cpp
Adapted stable_sort to C++ 20 and added container overloads. (range and sentinel). Added sentinel tests.
Issue #4822
=> Adapt stable_sort to C++ 20

libs/parallelism/algorithms/include/hpx/parallel/algorithms/rotate.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/rotate.hpp
Add sender overloads to parallel algorithms.
#5513 PR was closed by accident.
=> Add sender overloads to rotate/rotate_copy

libs/core/synchronization/tests/regressions/ignore_while_locked_1485.cpp
Fixes deadlocks that appear every now and then on `ignore_while_locked_1485` (`notify` called before `wait` again). However, the test is either unnecessary or wrong and could possibly be removed? The description in the test claims that it's testing `ignore_while_locked` but doesn't actually use it. @hkaiser do you know if the test is even needed anymore?
=> Avoid deadlock in ignore_while_locked_1485 test

libs/parallelism/algorithms/include/hpx/parallel/algorithms/exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/sort.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/stable_sort.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/swap_ranges.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/unique.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/sort.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/stable_sort.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/swap_ranges.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/transform_exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/transform_inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_default_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_fill.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_move.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/uninitialized_value_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/unique.hpp
Update the remaining algorithms to change the tag_fallback base classes to tag_parallel_algorithm. [PR #5329](https://github.com/STEllAR-GROUP/hpx/pull/5329#issuecomment-900733077).
=> Add sender overloads for remaining algorithms

libs/core/datastructures/include/hpx/datastructures/variant.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/bulk.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/detach.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/ensure_started.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/let_error.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/sync_wait.hpp, libs/parallelism/execution/include/hpx/execution/algorithms/when_all.hpp
There's no longer a feature check for `std::variant`. We assume it is always available.
=> Fix condition for checking if we should use our own variant

docs/sphinx/quickstart.rst
Change instructions for building HPX from paragraphs to structured information (numbered and bulleted lists, code blocks etc.)
[skip ci]
=> Fix Building HPX in Quick start

libs/core/schedulers/include/hpx/schedulers/local_queue_scheduler.hpp
We were setting it in the `local/static_priority_queue_scheduler` and `shared_priority_scheduler`, but not the non-priority schedulers. Allows the use of e.g. the `fork_join_scheduler`.
=> Set local thread/pool number in local/static_queue_scheduler

libs/parallelism/execution/include/hpx/execution/executors/execution_parameters.hpp, libs/parallelism/executors/include/hpx/executors/parallel_executor.hpp, libs/parallelism/executors/include/hpx/executors/scheduler_executor.hpp
- Adds support for `thread_priority` to `parallel_policy_executor`.
- Adds support for all currently available properties (hint, annotation, priority, stacksize) to `scheduler_executor`, *if* the `BaseScheduler` supports them.
- Adds more verbose message when a property is not supported.
=> Add missing properties to executors/schedulers

libs/parallelism/executors/include/hpx/executors/scheduler_executor.hpp, tests/performance/local/future_overhead.cpp, tests/performance/local/stream.cpp
- Add support for `scheduler_executor<thread_pool_scheduler>` to the stream and future overhead benchmarks.
- Add default constructor (and copy/move constructors/assignment operators) to `scheduler_executor`.
- Add support for setting warmup iterations in stream benchmark.
- Allow using `scheduler_executor` with forward iterators.
=> Update benchmarks and add support for scheduler_executor

libs/core/iterator_support/include/hpx/iterator_support/traits/is_sentinel_for.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/adjacent_difference.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/adjacent_find.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/advance_to_sentinel.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/search.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/detail/set_operation.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/find.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/is_heap.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/is_sorted.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/lexicographical_compare.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/mismatch.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/remove.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_exclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/transform_inclusive_scan.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_copy.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_default_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_fill.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_move.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/uninitialized_value_construct.hpp, libs/parallelism/algorithms/include/hpx/parallel/algorithms/unique.hpp, libs/parallelism/algorithms/include/hpx/parallel/util/detail/algorithm_result.hpp
- flyby: modernize the implementation of mismatch
- flyby: modernize `advance_to_sentinel`, `algorithm_result`
for more details, see https://github.com/STEllAR-GROUP/hpx/pull/5410#issuecomment-911790179
@Jedi18 please verify whether this fixes the issues you were seeing.
=> This fixes referencing stale iterators during the execution of binary mismatch

libs/full/async_cuda/include/hpx/async_cuda/cuda_future.hpp, libs/full/async_cuda/src/cuda_future.cpp, libs/full/runtime_distributed/include/hpx/runtime_distributed.hpp, libs/full/runtime_distributed/src/runtime_distributed.cpp, libs/full/runtime_local/include/hpx/runtime_local/runtime_local.hpp, libs/full/runtime_local/src/runtime_local.cpp
Tentatively removing it because removing it should also fix the regression in #5366.
This is untested and I want to see what the different CUDA and HIP builders say about this change. According to @DarkDeepBlue things seem to be fine without the wrapper.
I think the wrapper is mostly unneeded, but I continuations are probably still problematic without the wrapper. When run on a non-HPX thread they would fall back to trying to get the default pool which is done through the runtime pointer.
One possible solution to this is to not have the thread-local runtime pointer be thread-local anymore. @hkaiser, @sithhell what was the original motivation for making it thread-local? The pointer itself is only ever read (except when initialized or reset during init and finalize), so I don't see any …
=> Tentatively remove runtime_registration_wrapper from cuda futures

libs/core/threading_base/include/hpx/threading_base/annotated_function.hpp, libs/core/threading_base/src/annotated_function.cpp, tests/unit/apex/CMakeLists.txt, tests/unit/apex/annotation_check.cpp
`annotate_function` did not have a constructor taking `std::string`s which means that passing a `std::string` to it would try to use `get_function_annotation` for getting an annotation from a `std::string`. Since there's no specialization, this returns `<unknown>`. This adds an explicit constructor taking a `std::string`.
This also updates the `annotation_check` test and adds a test for `annotate_function`.
Flyby: restore the thread description correctly in the `annotate_function` destructor. @hkaiser after https://github.com/STEllAR-GROUP/hpx/pull/5401/commits/21f87b24ba8ecef89ac89807b1ecb99ca7fb36e1#diff-9d331166da570e7469e476d468b684dfd42590305a752f337fd6f9aa3f3bff86 there was no description stored in the `annotate_function` constructors, meaning that it was always restored to a …
=> Fix `annotate_function` for `std::string`

libs/parallelism/executors/include/hpx/executors/thread_pool_scheduler_bulk.hpp
The iterator should be copied, not moved. libstdc++ reported this with `_GLIBCXX_DEBUG` defined. I've opened https://github.com/STEllAR-GROUP/hpx/issues/5544 to remind us to get back to enabling it in CI.
=> Remove wrong move in thread_pool_scheduler_bulk.hpp

libs/core/mpi_base/include/hpx/mpi_base/mpi_environment.hpp, libs/core/runtime_configuration/CMakeLists.txt, libs/core/runtime_configuration/include/hpx/runtime_configuration/static_factory_data.hpp, libs/core/runtime_configuration/src/static_factory_data.cpp, libs/core/runtime_local/src/runtime_local.cpp, libs/full/collectives/src/barrier.cpp, libs/full/command_line_handling/CMakeLists.txt, libs/full/init_runtime/include/hpx/hpx_init_impl.hpp, libs/full/init_runtime/include/hpx/hpx_start_impl.hpp, libs/full/init_runtime/include/hpx/init_runtime/detail/run_or_start.hpp, libs/full/runtime_distributed/src/server/runtime_support_server.cpp, plugins/parcelport/mpi/parcelport_mpi.cpp, src/runtime/parcelset/parcelhandler.cpp
- this is a somewhat hacky solution as it marks functions that are declared in the core module with `HPX_EXPORT` (those are defined in full, currently)
=> More changes to overcome build problems on Windows after recent module rearrangements

libs/core/command_line_handling_local/include/hpx/command_line_handling_local/parse_command_line_local.hpp, libs/core/command_line_handling_local/src/parse_command_line_local.cpp, libs/core/command_line_handling_local/tests/regressions/CMakeLists.txt, libs/core/command_line_handling_local/tests/regressions/ignore_aliases_local.cpp, libs/full/command_line_handling/src/command_line_handling.cpp, libs/full/command_line_handling/src/parse_command_line.cpp, libs/full/command_line_handling/tests/regressions/CMakeLists.txt, libs/full/command_line_handling/tests/regressions/ignore_aliases.cpp
If `--hpx:ini=hpx.commandline.aliasing!=0` and `--hpx:ini=hpx.commandline.allow_unknown!=1` were given on the command line, HPX still tried to apply aliases while interpreting non-HPX options. This patch fixes the issue by ignoring aliases during the first attempt to parse the command line arguments.
=> Make sure command line aliasing is properly handled

libs/core/execution_base/src/this_thread.cpp
When `HPX_SMT_PAUSE` is available, `default_agent::yield` would never actually yield. This changes it to actually yield (`HPX_SMT_PAUSE` is still used in the first iterations of `yield_k`). See discussion at https://github.com/STEllAR-GROUP/hpx/pull/5549#discussion_r707106060 for context.
=> Make default_agent::yield actually yield

libs/core/serialization/CMakeLists.txt, libs/core/serialization/include/hpx/serialization/basic_archive.hpp, libs/core/serialization/include/hpx/serialization/input_archive.hpp, libs/core/serialization/include/hpx/serialization/output_archive.hpp, libs/core/serialization/include/hpx/serialization/serialization_fwd.hpp, libs/core/serialization/include/hpx/serialization/std_tuple.hpp, libs/core/serialization/include/hpx/serialization/traits/is_bitwise_serializable.hpp, libs/core/serialization/include/hpx/serialization/tuple.hpp, libs/core/serialization/tests/unit/CMakeLists.txt, libs/core/serialization/tests/unit/serialization_raw_pointer.cpp, libs/full/actions_base/include/hpx/actions_base/basic_action.hpp
- This functionality is needed for systems that rely on sending pointers to other localities just to send them back before they are being dereferenced.
@NanmiaoWu Could you please try adding the `-DHPX_SERIALIZATION_WITH_ALLOW_RAW_POINTER_SERIALIZATION=On` to your setup and see whether this solves the SHAD compilation problems?
=> Add option enabling serializing raw pointers

libs/core/string_util/include/hpx/string_util/trim.hpp
I've applied the workaround only for the required case to avoid someone coming along later thinking that the `begin`/`end` calls can be changed to `cbegin`/`cend`.
Fixes #5565.
@Spongman would you mind trying this in your setup as well?
=> Add workaround for libstc++ in string_util trim

libs/core/algorithms/tests/unit/algorithms/fill_tests.hpp, libs/core/algorithms/tests/unit/algorithms/filln_tests.hpp
Replaces std::size_t with int as Vc vector types does not have constructor overloads for unsigned long.
https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/8871/workflows/9f63859c-78aa-42ed-bc33-836a9549aa89/jobs/267395
=> fix unit fill test for datapar with Vc

libs/core/async_cuda/include/hpx/async_cuda/transform_stream.hpp, libs/core/execution/include/hpx/execution/algorithms/bulk.hpp, libs/core/execution/include/hpx/execution/algorithms/detach.hpp, libs/core/execution/include/hpx/execution/algorithms/just.hpp, libs/core/execution/include/hpx/execution/algorithms/keep_future.hpp, libs/core/execution/include/hpx/execution/algorithms/let_error.hpp, libs/core/execution/include/hpx/execution/algorithms/let_value.hpp, libs/core/execution/include/hpx/execution/algorithms/make_future.hpp, libs/core/execution/include/hpx/execution/algorithms/on.hpp, libs/core/execution/include/hpx/execution/algorithms/split.hpp, libs/core/execution/include/hpx/execution/algorithms/sync_wait.hpp, libs/core/execution/include/hpx/execution/algorithms/transform.hpp, libs/core/execution/include/hpx/execution/algorithms/when_all.hpp, libs/core/execution/tests/unit/algorithm_execute.cpp, libs/core/execution/tests/unit/algorithm_just.cpp, libs/core/execution/tests/unit/algorithm_test_utils.hpp, libs/core/execution/tests/unit/algorithm_transform.cpp, libs/core/execution/tests/unit/algorithm_when_all.cpp, libs/core/execution_base/include/hpx/execution_base/operation_state.hpp, libs/core/execution_base/include/hpx/execution_base/receiver.hpp, libs/core/execution_base/include/hpx/execution_base/sender.hpp, libs/core/execution_base/tests/unit/basic_operation_state.cpp, libs/core/execution_base/tests/unit/basic_receiver.cpp, libs/core/execution_base/tests/unit/basic_schedule.cpp, libs/core/execution_base/tests/unit/basic_sender.cpp, libs/core/executors/include/hpx/executors/thread_pool_scheduler.hpp, libs/core/executors/include/hpx/executors/thread_pool_scheduler_bulk.hpp, libs/core/executors/tests/unit/thread_pool_scheduler.cpp, libs/core/futures/include/hpx/futures/future.hpp, libs/core/synchronization/include/hpx/synchronization/async_rw_mutex.hpp
In P0443 member functions were given priority over free functions in the various CPOs. In P2300 tag_dispatch is the only way to implement various CPOs, i.e. member functions are not taken into account. This updates our execution CPOs to behave like P2300. This means that `schedule`, `set_value`, `set_error`, `set_done`, `start`, `connect` inherit `hpx::functional::tag`, not `hpx::functional::tag_priority`. This is slightly more verbose (`friend void tag_dispatch(start_t, ...)` instead of `void start(...)`) but is simpler to reason about. Additionally, the `thread_pool_scheduler` test compiles 10-15% faster with this change.
As a flyby I've:
- Removed the leftover scheduler is a sender functionality (i.e. one has to use `schedule(scheduler)` to get a sender; `thread_pool_scheduler` was …
=> Simplify execution CPOs

components/iostreams/include/hpx/components/iostreams/server/output_stream.hpp, components/iostreams/src/server/output_stream.cpp, components/iostreams/src/standard_streams.cpp, libs/core/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp, libs/core/threading_base/src/set_thread_state.cpp, libs/full/runtime_distributed/src/server/runtime_support_server.cpp
- flyby: handle terminate threads while waiting for activities to cease
=> Fixing shutdown problems caused by missing ref-counting

libs/core/config/include/hpx/config.hpp, libs/core/coroutines/include/hpx/coroutines/coroutine.hpp, libs/core/coroutines/include/hpx/coroutines/detail/context_base.hpp, libs/core/coroutines/include/hpx/coroutines/detail/coroutine_impl.hpp, libs/core/coroutines/include/hpx/coroutines/thread_id_type.hpp, libs/core/executors/tests/unit/thread_pool_scheduler.cpp, libs/core/runtime_configuration/src/runtime_configuration.cpp, libs/core/schedulers/include/hpx/schedulers/queue_holder_thread.hpp, libs/core/schedulers/include/hpx/schedulers/thread_queue.hpp, libs/core/threading_base/include/hpx/threading_base/thread_data.hpp, libs/core/threading_base/include/hpx/threading_base/thread_data_stackful.hpp, libs/core/threading_base/include/hpx/threading_base/thread_data_stackless.hpp, libs/core/threading_base/include/hpx/threading_base/thread_queue_init_parameters.hpp, libs/core/threading_base/src/thread_data.cpp, libs/core/threadmanager/src/threadmanager.cpp
This adds a configuration option `hpx.thread_queue.init_threads_count` (default `10`) which controls how many threads to allocate and initialize (including allocating a stack) with the default stack size in each `thread_queue`. The thread queue also first attempts to clean up terminated threads when it runs out of recycled threads to reuse existing threads if possible. Only if it can't reuse an old thread will it actually allocate a new thread. Checking for this is cheap, and we are anyway holding the thread queue lock at that point.
This reduces the need to "warm up" the scheduler and thread queues when benchmarking (see benchmarks below), and I don't see the harm in doing this generally either since threads will need to be allocated sooner or later.
To achieve this, I've added a way to …
=> Eagerly initialize a configurable number of threads on scheduler/thread queue init

cmake/HPX_GeneratePackageUtils.cmake
Absolute paths to shared libraries in the generated pkg-config files are not fully supported by waf-based build systems and are especially problematic in conjunction with `-Wl,--as-needed`. While the pkg-config format does not explicitly mention absolute paths, the 'Libs' entry should contain the 'Required linking flags for this package'.
=> Split absolute paths for generated pkg-config files into -L/-l parts

libs/core/futures/include/hpx/futures/traits/detail/future_await_traits.hpp
re: #5502, #5517
these are the changes required to get my coroutine-using application to build with gcc 10.2 & hpx.
it doesn't fix #5502 (I had to force `HPX_HAVE_CXX20_COROUTINES` in my non-cmake build).
=> fix coroutine_traits allocate calls, add unhandled_exception() implementation.

libs/core/serialization/include/hpx/serialization/tuple.hpp
As HPX can be configured without the compatibility of `hpx::tuple` and `std::tuple`, `hpx::get` must be used for accessing the elements of a `hpx::tuple`.  
This fixes a compilation error with the current master when configured with `-DHPX_DATASTRUCTURES_WITH_ADAPT_STD_TUPLE=OFF`
=> Serialization of hpx::tuple must use hpx::get

libs/core/async_base/CMakeLists.txt, libs/core/async_base/include/hpx/async_base/launch_policy.hpp, libs/core/async_base/include/hpx/async_base/scheduling_properties.hpp, libs/core/async_base/include/hpx/async_base/traits/is_launch_policy.hpp, libs/core/async_base/src/launch_policy.cpp, libs/core/async_base/tests/unit/CMakeLists.txt, libs/core/async_base/tests/unit/launch_policy.cpp, libs/core/coroutines/include/hpx/coroutines/thread_enums.hpp, libs/core/execution/include/hpx/execution/detail/async_launch_policy_dispatch.hpp, libs/core/execution/include/hpx/execution/detail/post_policy_dispatch.hpp, libs/core/execution/include/hpx/execution/executors/execution_parameters.hpp, libs/core/executors/include/hpx/executors/detail/hierarchical_spawning.hpp, libs/core/executors/include/hpx/executors/fork_join_executor.hpp, libs/core/executors/include/hpx/executors/guided_pool_executor.hpp, libs/core/executors/include/hpx/executors/parallel_executor.hpp, libs/core/executors/include/hpx/executors/restricted_thread_pool_executor.hpp, libs/core/futures/include/hpx/futures/detail/future_data.hpp, libs/core/futures/include/hpx/futures/futures_factory.hpp, libs/core/futures/src/future_data.cpp, libs/core/properties/CMakeLists.txt, libs/core/runtime_local/src/custom_exception_info.cpp
This PR extends `hpx::launch` and related types (i.e. `hpx::launch::async`, etc.) such that they contain the scheduling hint and the stack size in addition to the thread priority.
This will be needed for the direct scoped execution to be able to control whether threads should be executed directly or not. This also simplifies a couple of internal interfaces.
As a flyby, this PR changes all thread enums to be of size `std::int8_t`, which allows for the launch policy to fit into a 64 bit register.
=> Extend launch policy to carry stack size and scheduling hint in addition to priority

libs/core/async_cuda/tests/unit/CMakeLists.txt, libs/core/execution/tests/unit/CMakeLists.txt, libs/core/executors/tests/unit/CMakeLists.txt, libs/core/synchronization/tests/unit/CMakeLists.txt, libs/full/compute_cuda/tests/performance/CMakeLists.txt
Not needed anymore since we require C++17.
=> Remove unnecessary checks for C++17 for tests

libs/core/execution/include/hpx/execution/algorithms/just.hpp, libs/core/execution_base/CMakeLists.txt, libs/core/execution_base/include/hpx/execution_base/any_sender.hpp, libs/core/execution_base/src/any_sender.cpp, libs/core/execution_base/tests/unit/CMakeLists.txt, libs/core/execution_base/tests/unit/any_sender.cpp
Adds type-erased senders, `any_sender` and `unique_any_sender` (of which the latter is move-only). I'd appreciate feedback on this as it's the first time I do any serious type-erasing. The type-erasure mechanisms don't have to stay this way if the techniques used elsewhere are preferable.
The senders are currently templated on the value types that the wrapped senders send, and only on that. The wrapped senders must send only one set of values (i.e. no multiple variants in `value_types`). The senders are currently not templated on the error type at all, and assume `std::exception_ptr`. This could easily be changed if needed.
The buffers used for SBO are quite big right now and may be self-defeating. I guess experience will show what are good sizes for the buffers. It can of course also …
=> Add any_sender and unique_any_sender

libs/full/actions/tests/regressions/CMakeLists.txt, libs/full/naming_base/src/gid_type.cpp, libs/full/naming_base/tests/regressions/CMakeLists.txt, libs/full/naming_base/tests/regressions/format_id_type.cpp
This fixes the wrong output reported here: https://gist.github.com/severinstrobl/bfba712aa4a03454e5fbab65bd70046e
=> Fixing the output formatting for id_types

libs/core/execution_base/include/hpx/execution_base/any_sender.hpp, libs/core/execution_base/src/any_sender.cpp, libs/core/execution_base/tests/unit/any_sender.cpp
Apologies for breaking master. #5510 passed CI before #5332 was merged, but I did not update #5510 to use `tag_dispatch` instead of member functions before merging. This should fix things.
=> Update any_sender to use tag_dispatch for execution customizations

.gitignore, CMakeLists.txt, cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx17_memory_resource.cpp, libs/core/datastructures/CMakeLists.txt, libs/core/datastructures/include/hpx/datastructures/detail/small_vector.hpp, libs/core/datastructures/tests/unit/CMakeLists.txt, libs/core/datastructures/tests/unit/small_vector.cpp, libs/core/execution/include/hpx/execution/algorithms/split.hpp, libs/core/futures/include/hpx/futures/detail/future_data.hpp, libs/core/lcos_local/tests/unit/CMakeLists.txt, libs/core/lcos_local/tests/unit/local_dataflow_small_vector.cpp, libs/core/synchronization/include/hpx/synchronization/async_rw_mutex.hpp, plugins/parcelport/libfabric/parcelport_libfabric.cpp, plugins/parcelport/libfabric/parcelport_libfabric.hpp, plugins/parcelport/libfabric/receiver.hpp, plugins/parcelport/libfabric/rma_receiver.hpp, plugins/parcelport/libfabric/sender.hpp
This removes the dependency on `boost::container::small_vector`
Working towards #3440
=> Replacing boost::container::small_vector

.circleci/config.yml, .github/workflows/linux_debug.yml, .github/workflows/linux_release_fetchcontent.yml, .github/workflows/linux_sanitizers.yml, cmake/templates/conf.py.in, docs/sphinx/manual/optimizing_hpx_applications.rst, docs/sphinx/references.bib, tools/docker/Dockerfile
Fixes #4698 
- Adds support for BibTeX references in Sphinx docs
- Added an example citation (this will have to be removed before merging)
This is how the references/citations will look with this change:
EDIT:
Changed the style of references because earlier style would have meant there would me a single, unified bibliography section. New style should look like this:
=> docs: add support for BibTeX references in Sphinx docs

.github/workflows/linux_hip.yml
This one seems to have been left behind at some point (maybe even intentionally, hmm... @aurianer do you remember anything about this?). Bumping it up to the latest. #5626 bumps the others from `9` to `10`.
=> Update container image tag in GitHub actions HIP configuration

libs/core/algorithms/include/hpx/parallel/algorithms/copy.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/exclusive_scan.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/inclusive_scan.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/partition.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/reduce_by_key.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/transform_exclusive_scan.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/transform_inclusive_scan.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/unique.hpp, libs/core/algorithms/include/hpx/parallel/util/scan_partitioner.hpp, libs/core/algorithms/tests/performance/CMakeLists.txt, libs/core/algorithms/tests/performance/benchmark_scan_algorithms.cpp, libs/core/datastructures/include/hpx/datastructures/tuple.hpp, libs/core/execution/tests/regressions/chunk_size_4118.cpp
Modify scan partitioner implementation to execute f2 sequentially once f1 tasks are done, so that f3 tasks can all be executed in parallel.
Minor changes to algorithms using the scan partitioner.
Added benchmark for comparing sequential and parallel execution times of scan algorithms.
Issue #3733
=> Change scan partitioner implementation

libs/core/datastructures/include/hpx/datastructures/variant.hpp, libs/core/execution/include/hpx/execution/algorithms/sync_wait.hpp
Use `hpx::holds_alternative` instead.
=> Fix leftover std::holds_alternative usage

.circleci/config.yml, .github/bors.toml, .github/workflows/linux_bors.yml
Bors is meant to avoid this problem: https://bors.tech/essay/2017/02/02/pitch/, which happened (again) yesterday.
This will not be very useful until CI actually passes reliably, but I'm starting by setting it up for a subset, i.e. one single GitHub action on Linux that builds and runs the examples (i.e. the current "Linux CI (Debug)" configuration). Eventually all CI should just report to bors, but I'm keeping it separate for now until we get some experience with how well this works.
=> Use bors for merging pull requests

docs/sphinx/manual/optimizing_hpx_applications.rst, docs/sphinx/manual/writing_distributed_hpx_applications.rst
The documentation contained two dead links to source code examples, hopefully I got the syntax right for the new scheme.
=> Fixed links to sources in Sphinx documentation

components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_segmented_iterator.hpp, libs/core/algorithms/include/hpx/algorithms/traits/is_value_proxy.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/adjacent_difference.hpp, libs/core/algorithms/include/hpx/parallel/container_algorithms/adjacent_difference.hpp, libs/full/compute/tests/regressions/for_each_value_proxy.cpp, libs/full/compute_cuda/include/hpx/compute/cuda/value_proxy.hpp, libs/full/segmented_algorithms/include/hpx/parallel/segmented_algorithms/adjacent_difference.hpp
- fixing assignment operator for proxy objects returned from segmented iterators
- adding proxy_value trait allowing to extract type returned by a proxy
- flyby: modernize adjacent_difference algorithm, adding missing concept checks
=> Adapting adjacent_difference to work with proxy iterators

libs/core/algorithms/tests/unit/datapar_algorithms/generate_tests.hpp, libs/core/algorithms/tests/unit/datapar_algorithms/generaten_tests.hpp
Same problem as https://github.com/STEllAR-GROUP/hpx/pull/5613.
This was again not caught because @srinivasyadav18's PRs don't run on circleci (at least not under STEllAR-GROUP). However, I just noticed that @srinivasyadav18 has CircleCI enabled on his own fork, and the PRs do actually build there. This may be the reason why it doesn't run under STEllAR-GROUP. @srinivasyadav18 could you try if disabling builds on your fork would get the builds over to the main repo again. There should be a "stop building" button on this page for you: https://app.circleci.com/settings/project/github/srinivasyadav18/hpx.
=> Fix generate datapar tests for Vc

.github/PULL_REQUEST_TEMPLATE.md, libs/core/algorithms/tests/unit/algorithms/ends_with.cpp, libs/core/algorithms/tests/unit/algorithms/starts_with.cpp
With certain seeds/random numbers it would fail with a floating point exception because of `x % 0` (like this: https://cdash.cscs.ch/testDetails.php?test=57251016&build=196753). I've updated it to use `uniform_int_distribution` to avoid the modulo in the first place. `starts_with` was not buggy in the same way, but I've still updated it to use `uniform_int_distribution` as I find it much easier to see what range of values can be generated.
Finally, I've added a "Checklist" section to the pull request template. Anything that can be checked in CI should be checked there, but some things are hard or impossible to check automatically. For those cases it's sometimes enough to have a gentle reminder to check things manually. Please feel free to expand the list in the future (or remove things; …
=> Fix ends_with test

cmake/templates/conf.py.in
Sphinx configuration file uses the following words as variable names:
- Python already has a built-in function called `dir`. Redefining this can cause subtle and hard-to-find bugs.
- Renamed to `Dir`
- `copyright` is a built-in constant in Python. From [Python documentation](https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module) -- ` They [built-in constants like copyright] are useful for the interactive interpreter shell and should not be used in programs.`
- Renamed to `Copyright`
=> build: replace usage of Python's reserved words and functions as variable names

cmake/HPX_AddModule.cmake
The CMake variables `HPX_ENABLED_MODULES` and `HPX_[CORE|FULL]_ENABLED_MODULES` have to be made unique as otherwise they grow indefinitely in the CMake cache.
=> Avoid for module lists to grow indefinitely in cmake cache

libs/core/algorithms/include/hpx/parallel/algorithms/detail/dispatch.hpp
This slipped into master while the Windows builders were not working
=> Disambiguate namespace for MSVC

libs/core/schedulers/include/hpx/schedulers/local_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/queue_helpers.hpp, libs/core/schedulers/include/hpx/schedulers/static_queue_scheduler.hpp, libs/core/threading_base/src/set_thread_state.cpp
None of the changed messages are errors. They may indicate a problem, but are not errors in themselves.
=> Change logging errors to warnings in schedulers

libs/core/async_cuda/tests/unit/transform_stream.cu, libs/core/execution/CMakeLists.txt, libs/core/execution/include/hpx/execution/algorithms/schedule_from.hpp, libs/core/execution/include/hpx/execution/algorithms/transfer.hpp, libs/core/execution/include/hpx/execution/algorithms/transfer_just.hpp, libs/core/execution/tests/unit/algorithm_just_on.cpp, libs/core/execution/tests/unit/algorithm_on.cpp, libs/core/executors/include/hpx/executors/scheduler_executor.hpp, libs/core/executors/tests/unit/thread_pool_scheduler.cpp, libs/core/synchronization/tests/unit/async_rw_mutex.cpp, libs/full/compute_cuda/tests/performance/synchronize.cu
=> Rename on execution::schedule_from, rename just_on to just_transfer, and add transfer

libs/core/executors/CMakeLists.txt, libs/core/executors/include/hpx/executors/fork_join_executor.hpp, libs/core/executors/src/fork_join_executor.cpp, libs/core/executors/tests/unit/fork_join_executor.cpp
I've expanded the `fork_join_executor` to also test the dynamic schedule. I've also added tests for normal and high priority threads.
The constructor now throws an exception if the executor is constructed with `thread_stacksize::nostack` since that would prevent yielding. For an unclear reason `thread_priority::low` does not work with the executor. I'm guessing it has to do with how we decide to steal threads, and low priority threads having a single queue, but I don't have a full explanation. I'm leaving it out of the test at the moment, but I'm not adding a check for it in the constructor without understanding the reason for it.
@gonidelis could you please try this on your test cases as well? 
=> Fix `fork_join_executor` with dynamic schedule

libs/core/executors/include/hpx/executors/service_executors.hpp, libs/core/executors/tests/regressions/CMakeLists.txt, libs/core/executors/tests/regressions/service_executor_cuda.cu
Despite the service executors not being marked as device code, nvcc manages to fail to compile the service executors. Since the service executors can't be used on the device I've simply disabled the piece of code that triggers the error.
An example of the failure (thanks @G-071!) is the following:
```
/data/scratch/daissgr/ModernTiger/build/hpx/include/asio/detail/handler_work.hpp(482): error: more than one partial specialization matches the template argument list of class "asio::detail::handler_work_base<asio::io_context::executor_type, void, asio::io_context, asio::executor, void>"            "asio::detail::handler_work_base<Executor, CandidateExecutor, IoContext, PolymorphicExecutor, std::enable_if<<expression>, void>::type>"            "asio::detail::handler_work_base<Executor, void, …
```
=> Fix compilation of service executors with nvcc

libs/core/execution/include/hpx/execution/algorithms/detail/single_result.hpp, libs/core/execution/include/hpx/execution/algorithms/when_all.hpp, libs/core/execution/tests/unit/algorithm_when_all.cpp, libs/core/type_support/include/hpx/type_support/pack.hpp
Previously `execution::when_all` required all predecessors to send exactly one variant with exactly one type. This relaxes it to allow exactly one variant with any number of types (including zero). This brings it in line with P2300 and makes it much closer to `dataflow` (and much more useful).
=> Relax constraints on `execution::when_all`

cmake/templates/conf.py.in
Fixes #
Removed any reference of  hpx/modules/futures.hpp from the introduction of futures.
=> Fix future API

.jenkins/cscs/env-clang-10.sh, .jenkins/cscs/env-clang-12.sh, .jenkins/cscs/env-clang-13.sh, .jenkins/cscs/env-clang-7.sh, .jenkins/cscs/env-clang-8.sh, .jenkins/cscs/env-clang-9.sh, .jenkins/cscs/env-clang-cuda.sh, CMakeLists.txt, tools/perftests_ci/driver.py
Maybe fixes #5661.
Opening this as a draft only to see the performance test CI results.
=> Use dynamic bitsets by default for CPU masks

docs/sphinx/examples.rst, docs/sphinx/examples/matrix_multiplication.rst, examples/quickstart/CMakeLists.txt, examples/quickstart/matrix_multiplication.cpp
- matrix multiplication example
- matrix multiplication explanation
=> Add matrix multiplication example

docs/sphinx/api/public_api.rst, libs/core/algorithms/include/hpx/parallel/algorithms/for_each.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/for_loop.hpp, libs/core/algorithms/tests/regressions/for_each_annotated_function.cpp, libs/core/execution/tests/regressions/annotated_minmax_2593.cpp, libs/core/executors/include/hpx/executors/annotating_executor.hpp, libs/core/executors/include/hpx/executors/dataflow.hpp, libs/core/executors/include/hpx/executors/parallel_executor.hpp, libs/core/executors/include/hpx/executors/thread_pool_scheduler.hpp, libs/core/executors/include/hpx/executors/thread_pool_scheduler_bulk.hpp, libs/core/futures/include/hpx/futures/packaged_continuation.hpp, libs/core/futures/include/hpx/futures/packaged_task.hpp, libs/core/futures/src/future_data.cpp, libs/core/include_local/include/hpx/local/functional.hpp, libs/core/resource_partitioner/examples/async_customization.cpp, libs/core/resource_partitioner/tests/unit/scheduler_priority_check.cpp, libs/core/threading_base/CMakeLists.txt, libs/core/threading_base/include/hpx/threading_base/annotated_function.hpp, libs/core/threading_base/include/hpx/threading_base/scoped_annotation.hpp, libs/core/threading_base/src/annotated_function.cpp, libs/full/components/include/hpx/components/executor_component.hpp, tests/unit/apex/CMakeLists.txt, tests/unit/apex/annotation_check.cpp
Fixes #5686. Also moves the utilities to the top-level `hpx` namespace. Adds them to the public API list.
Open question: which header should provide these? I've now added both to `hpx/local/functional.hpp` (and by extension `hpx/functional.hpp`). `scoped_annotation` could also fit in `hpx/local/execution.hpp` in my opinion (`annotated_function` could sort of also fit there). 
Some (in my opinion worse) alternative names:
- `annotation`
- `annotate_scope`
- `annotation_scoped`
- `raii_annotation`
=> Rename `annotate_function` to `scoped_annotation`

libs/core/iterator_support/tests/unit/counting_iterator.cpp, libs/core/iterator_support/tests/unit/iterator_tests.hpp
The random_access_iterator test requires at least two elements in the container. I've added an assertion to the test to make the precondition slightly more obvious. Fixes these types of failures: https://cdash.cscs.ch/testDetails.php?test=60179258&build=205784, i.e.
```
using seed: 1639331791
/dev/shm/hpx/src/libs/core/iterator_support/tests/unit/iterator_tests.hpp(106): test '*i1 == v2' failed in function 'void tests::input_iterator_test(Iterator, T, T) [Iterator = hpx::util::counting_iterator<std::__wrap_iter<int *>>, T = std::__wrap_iter<int *>]'
/dev/shm/hpx/src/libs/core/iterator_support/tests/unit/iterator_tests.hpp(107): test '*i == v2' failed in function 'void tests::input_iterator_test(Iterator, T, T) [Iterator = hpx::util::counting_iterator<std::__wrap_iter<int *>>, T = …
```
=> Fix `counting_iterator` container tests

components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_decl.hpp, components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_impl.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_all.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_any.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_each.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_some.hpp, libs/core/async_combinators/include/hpx/async_combinators/when_all.hpp, libs/core/async_combinators/include/hpx/async_combinators/when_any.hpp, libs/core/async_combinators/include/hpx/async_combinators/when_each.hpp, libs/core/async_combinators/include/hpx/async_combinators/when_some.hpp, libs/core/futures/include/hpx/futures/traits/acquire_future.hpp, libs/core/resource_partitioner/examples/async_customization.cpp, libs/core/resource_partitioner/tests/unit/named_pool_executor.cpp, libs/full/agas/src/addressing_service.cpp, tests/performance/network/network_storage/network_storage.cpp
This also moves those facilities into `namespace hpx` and deprecates the same in `namespace hpx::lcos`
=> Modernize when_all and friends (when_any, when_some, when_each)

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx20_trivial_virtual_destructor.cpp, libs/core/execution_base/include/hpx/execution_base/any_sender.hpp, libs/core/execution_base/tests/unit/any_sender.cpp
This allows storing `(unique_)any_sender` in global variables (or even function-local statics). The problem is that the destructor of the `any_sender` may hold e.g. hold an `any_operation_state/receiver` from a type-erased predecessor sender. When the global `any_sender` is destroyed it may try to access an empty vtable that was destroyed before the global `any_sender` was destroyed. The failure case in the added test is a segfault. The `empty` method on the (supposed) empty vtable happens to return `false` and the destructor tries to delete the empty vtable even though it was never dynamically allocated.
~This changes the empty vtables to be `inline constexpr` variables.~ This adds a helper base class which accesses the `any_operation_state` and `any_receiver` empty vtables when …
=> Allow using  `any_sender` in global variables

CMakeLists.txt, cmake/HPX_SetupHPXLocal.cmake
`OMPI_IMPORTS` is already defined in hpx-local if ASYNC_MPI is enabled
=> Avoid duplicate definition error

.jenkins/lsu/entry.sh
This is an attempt to overcome the Slurm issues we're seeing on rostam (sporadic failures to launch the builders that do not seem to be reproducible).
=> Randomly delay execution of bash scripts launched by Jenkins

.jenkins/cscs/entry.sh, .jenkins/lsu/entry.sh
@hkaiser this is required if you decide to try to use bors more extensively. Otherwise it's not necessary and can be closed without merging.
=> Set commit status from Jenkins also for special branches 

libs/core/mpi_base/src/mpi_environment.cpp
- If MPICH is used we set `export MPICH_MAX_THREAD_SAFETY=multiple` to activate multithreaded MPI.
This might solve some hanging, we experienced with MPI recently.
Note, this has to happen before `MPI_Init` is being called.
=> Add check for MPICH and set the correct env to suport multi-threaded

.circleci/config.yml, .github/workflows/linux_bors.yml, .github/workflows/linux_debug.yml, .github/workflows/linux_hip.yml, .github/workflows/linux_release_fetchcontent.yml, .github/workflows/linux_sanitizers.yml, .jenkins/cscs/env-common.sh, .jenkins/lsu/env-common.sh, CMakeLists.txt, cmake/HPX_AddModule.cmake
CMake runs out of memory when using the Ninja generator if the modules are being built as OBJECT libraries. In this case the fallback is to build STATIC (whole-archive) libraries instead.
=> Workaround for CMake/Ninja generator OOM problem

libs/core/config/include/hpx/config/compiler_specific.hpp, libs/core/execution/CMakeLists.txt, libs/core/execution/include/hpx/execution/algorithms/let_value.hpp, libs/core/execution_base/CMakeLists.txt, libs/core/execution_base/include/hpx/execution_base/get_allocator.hpp, libs/core/execution_base/include/hpx/execution_base/get_delegatee_scheduler.hpp, libs/core/execution_base/include/hpx/execution_base/get_env.hpp, libs/core/execution_base/include/hpx/execution_base/get_scheduler.hpp, libs/core/execution_base/include/hpx/execution_base/get_stop_token.hpp, libs/core/execution_base/include/hpx/execution_base/read.hpp, libs/core/execution_base/include/hpx/execution_base/sender.hpp, libs/core/execution_base/tests/unit/CMakeLists.txt, libs/core/execution_base/tests/unit/environment_queries.cpp, libs/core/execution_base/tests/unit/forwarding_env_query.cpp, libs/core/execution_base/tests/unit/get_env.cpp, libs/core/tag_invoke/include/hpx/functional/detail/tag_fallback_invoke.hpp, libs/core/testing/include/hpx/modules/testing.hpp, libs/core/testing/src/testing.cpp, libs/core/type_support/CMakeLists.txt, libs/core/type_support/include/hpx/type_support/hide_from_adl.hpp, libs/core/type_support/include/hpx/type_support/unwrap_ref.hpp
- flyby: fixing global_fixture linking problems with MSVC
=> Adding environmental query CPOs

.jenkins/common/set_github_status.sh
The url has changed from `/buildSummary.php?buildid=<buildid>` to just `/build/<buildid>`. The old urls still work and get forwarded to the new ones.
=> Update cdash build url

libs/core/execution/CMakeLists.txt, libs/core/execution/include/hpx/execution/executors/num_cores.hpp
- Aim to control the number of cores in executors 
- A functionality setting the number of cores to be used by an algorithm directly
note: under ..hpx/libs/core/execution/include/hpx/execution/executors/..
=> add num_cores facility

libs/core/execution/CMakeLists.txt, libs/core/execution/include/hpx/execution/algorithms/let_error.hpp, libs/core/execution/include/hpx/execution/algorithms/let_value.hpp, libs/core/execution/include/hpx/execution/algorithms/schedule_from.hpp, libs/core/execution/include/hpx/execution/algorithms/when_all.hpp, libs/core/execution/include/hpx/execution/queries/get_allocator.hpp, libs/core/execution/include/hpx/execution/queries/get_delegatee_scheduler.hpp, libs/core/execution/include/hpx/execution/queries/get_scheduler.hpp, libs/core/execution/include/hpx/execution/queries/get_stop_token.hpp, libs/core/execution/include/hpx/execution/queries/read.hpp, libs/core/execution/tests/unit/CMakeLists.txt, libs/core/execution/tests/unit/algorithm_transfer_when_all.cpp, libs/core/execution/tests/unit/forwarding_env_query.cpp, libs/core/execution_base/CMakeLists.txt, libs/core/execution_base/include/hpx/execution_base/completion_scheduler.hpp, libs/core/execution_base/include/hpx/execution_base/get_env.hpp, libs/core/execution_base/include/hpx/execution_base/sender.hpp, libs/core/execution_base/tests/unit/CMakeLists.txt, libs/core/threading/src/thread.cpp, libs/core/type_support/include/hpx/type_support/equality.hpp, libs/core/type_support/include/hpx/type_support/pack.hpp
- fixes to environmental query support
- move queries to execution module
- adding transfer_when_all (and test)
- flyby: add concept checks to get_completion_handler<CPO>
This relies on #5748
=> Add stop support to when_all

libs/core/runtime_local/src/runtime_local.cpp
Fixes a warning as reported here: https://irclog.cct.lsu.edu/ste~b~~b~ar/2022-02-06#374594;
=> Fixing a integral conversion warning

.github/workflows/windows_debug.yml, .github/workflows/windows_release.yml
Github has removed VS2019 from the used Windows image
=> Updating used version of Visual Studio

cmake/templates/conf.py.in, docs/sphinx/extensions/sphinx-hpx.py
@dimitraka: this adds a new role (a first version of it, at least) that enables linking a specific file to it's page on github:
```
:hpx-header:`libs/core/include_local/include,hpx/local/algorithm.hpp`
```
will link for instance to https://github.com/STEllAR-GROUP/hpx/blob/20bcde189e62bd617f6403a8a9c95a0945b2fffa/libs/core/include_local/include/hpx/local/algorithm.hpp (if the git-hash is '20bcde189e62bd617f6403a8a9c95a0945b2fffa') and show `hpx/local/algorithm.hpp` in the generated html (please note the comma in the `base_path,file_name` argument to the new role).
=> Adding a sphinx role allowing to link to a file directly in github

.jenkins/cscs/env-clang-cuda.sh, .jenkins/cscs/env-gcc-cuda.sh
Attempt to update the configurations... One of the Boost modules has been removed, hence I'm using one of our Boost installs directly. Since it's header-only the used compiler shouldn't matter.
@hkaiser I'll update the performance CI references separately.
=> Update Piz Daint Jenkins configuration

libs/core/config/include/hpx/config.hpp, libs/full/parcelport_mpi/src/parcelport_mpi.cpp
This PR adds an option to the MPI parcelport that allows specifying the maximum number of cores that will participate in the MPI parcelport background work: `--hpx:ini=hpx.parcel.mpi.background_threads!=N`, where `N` is the number of cores that will participate (default is `-1`, meaning all cores participate). Alternatively, this can be set through the environment variable `HPX_HAVE_PARCELPORT_MPI_BACKGROUND_THREADS`.
@diehlpk please verify whether this has any effect on the performance issues you're investigating.
=> Add option to restrict MPI background work to subset of cores

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx20_source_location.cpp, libs/core/assertion/include/hpx/assertion/evaluate_assert.hpp, libs/core/assertion/include/hpx/assertion/source_location.hpp, libs/core/assertion/include/hpx/modules/assertion.hpp, libs/core/assertion/src/assertion.cpp, libs/core/assertion/src/source_location.cpp, libs/core/include_local/CMakeLists.txt, libs/core/include_local/include/hpx/local/source_location.hpp, libs/core/runtime_local/include/hpx/runtime_local/runtime_handlers.hpp, libs/core/runtime_local/src/runtime_handlers.cpp, libs/core/type_support/include/hpx/type_support/meta.hpp, libs/full/include/CMakeLists.txt, libs/full/include/include/hpx/source_location.hpp
- move hpx::assertion::source_location to hpx::source_location
- adding hpx/source_location.hpp header file
Fixes #3995
=> Use C++20 std::source_location, if available

libs/core/execution/include/hpx/execution/algorithms/sync_wait.hpp
This fails to compile at least with GCC 9.3.0 and CUDA 11.3 unless the template parameter is specified explicitly.
=> Add back explicit template parameter to `ignore_while_checking` to compile with nvcc

cmake/templates/conf.py.in, docs/sphinx/api/public_api.rst
Fixes #
- Table names in Public API page
- Add github link at top of the page
- Include home page in the table of contents
- Add header file hpx/source_location.hpp
=> API docs changes

docs/sphinx/manual/launching_and_configuring_hpx_applications.rst, libs/core/serialization/include/hpx/serialization/container.hpp, libs/core/serialization/include/hpx/serialization/input_archive.hpp, libs/core/serialization/include/hpx/serialization/input_container.hpp, libs/core/serialization/include/hpx/serialization/output_archive.hpp, libs/core/serialization/include/hpx/serialization/output_container.hpp, libs/full/parcelset/include/hpx/parcelset/encode_parcels.hpp, libs/full/parcelset/include/hpx/parcelset/parcelport_impl.hpp, libs/full/parcelset/src/parcelhandler.cpp, libs/full/parcelset_base/include/hpx/parcelset_base/parcelport.hpp, libs/full/parcelset_base/src/parcelport.cpp, libs/full/plugin_factories/include/hpx/plugin_factories/parcelport_factory.hpp
- this adds a new configuration option `hpx.parcel.zero_copy_serialization_threshold`
- flyby: rename `hpx.max_backgroud_threads` to `hpx.parcel.max_background_threads`,
- expose parcelport specific `hpx.parcel.<pptype>.max_background_threads` and `hpx.parcel.<pptype>.zero_copy_serialization_threshold` (those default to the respective 'global' setting)
- added missing documentation for both
=> Exposing zero-copy serialization threshold through configuration option

CMakeLists.txt
Change the default value of HPX_WITH_LCI_TAG to the tag "v1.7".
Previously, it is a hardcoded commit hash value, which will be hard to update if we fix a bug in LCI in the future.
=> change the default value of HPX_WITH_LCI_TAG to v1.7

libs/core/algorithms/include/hpx/parallel/algorithms/rotate.hpp, libs/core/algorithms/include/hpx/parallel/util/detail/sender_util.hpp, libs/core/algorithms/tests/unit/algorithms/rotate.cpp, libs/core/executors/include/hpx/executors/execution_policy.hpp
Aim to further improve **_rotate_** algorithm
-  Adding core partition functionality: enables the left and right sides of rotate to allocate the number of cores as needed
- Removing the unneeded asynchronous code: decreases the overheads by removing the third step operation of rotate 
add num_cores facility #5763
Making sure num_cores is properly handled by parallel_executor #5792
=> Further improvement actions to rotate

libs/core/algorithms/include/hpx/parallel/algorithms/make_heap.hpp, libs/core/algorithms/include/hpx/parallel/util/foreach_partitioner.hpp, libs/core/algorithms/include/hpx/parallel/util/partitioner.hpp, libs/core/algorithms/include/hpx/parallel/util/partitioner_with_cleanup.hpp, libs/core/algorithms/include/hpx/parallel/util/scan_partitioner.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_all.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_any.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_some.hpp, libs/core/async_combinators/tests/unit/wait_all.cpp, libs/core/async_combinators/tests/unit/wait_all_std_array.cpp, libs/core/async_combinators/tests/unit/wait_any.cpp, libs/core/async_combinators/tests/unit/wait_any_std_array.cpp, libs/core/async_combinators/tests/unit/wait_some.cpp, libs/core/async_combinators/tests/unit/wait_some_std_array.cpp, libs/core/futures/tests/regressions/exception_from_continuation_1613.cpp, libs/full/compute/include/hpx/compute/host/numa_allocator.hpp, libs/full/resiliency_distributed/tests/performance/replay/async_replay_distributed.cpp, libs/full/resiliency_distributed/tests/performance/replay/async_replay_distributed_validate.cpp
This is a potential optimization allowing to skip checking for exceptional futures after calling one of the `wait_xxx_nothrow` functions.
=> wait_xxx_nothrow functions return whether one of the futures is exceptional

CMakeLists.txt
- Supressing gcc warning about ABI problem with std::destructive_intererence_size
=> Fedora related fixes

.circleci/config.yml, docs/CMakeLists.txt
CircleCI documentation generation times out for master and release branches (after recent changes). This PR slits the generation of the html, singlehtml, and latexpdf docs into separate steps in the hope that those will not time out separately anymore.
=> Splitting documentation generation steps on CircleCI

libs/core/lci_base/include/hpx/lci_base/lci_environment.hpp, libs/core/lci_base/src/lci_environment.cpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/receiver.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/receiver_connection.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/sender.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/sender_connection.hpp
Optimize LCI parcelport.
Done:
- only use a single progress thread to call LCI_progress;
- remove all the locks around LCI calls;
- use LCI_sendm or LCI_sendl based on message size. Previously, we only use LCI_sendl.
- simultaneously post multiple send/recv for the same connection. Only synchronize in the end.
=> Optimize LCI parcelport

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx11_atomic_init_flag.cpp, cmake/tests/cxx11_std_atomic.cpp, libs/core/execution_base/tests/unit/execution_context.cpp, libs/core/functional/tests/unit/is_invocable.cpp, libs/core/threading_base/tests/regressions/thread_stacksize_current.cpp
- this disables the use of ATOMIC_INIT_FLAG if needed (clang 14 complains about its use)
=> ATOMIC_INIT_FLAG is deprecated starting C++20

.jenkins/cscs/env-common.sh, .jenkins/lsu/env-common.sh, CMakeLists.txt, docs/sphinx/manual/optimizing_hpx_applications.rst, libs/full/actions/include/hpx/actions/transfer_base_action.hpp, libs/full/actions_base/include/hpx/actions_base/detail/per_action_data_counter_registry.hpp, libs/full/actions_base/src/detail/per_action_data_counter_registry.cpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/receiver_connection.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/sender_connection.hpp, libs/full/parcelport_libfabric/src/rma_receiver.cpp, libs/full/parcelport_libfabric/src/sender.cpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/receiver_connection.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/sender_connection.hpp, libs/full/parcelport_tcp/include/hpx/parcelport_tcp/receiver.hpp, libs/full/parcelport_tcp/include/hpx/parcelport_tcp/sender.hpp, libs/full/parcelset/include/hpx/parcelset/decode_parcels.hpp, libs/full/parcelset/include/hpx/parcelset/encode_parcels.hpp, libs/full/parcelset/include/hpx/parcelset/parcel_buffer.hpp, libs/full/parcelset/include/hpx/parcelset/parcelhandler.hpp, libs/full/parcelset/src/parcelhandler.cpp, libs/full/parcelset/tests/unit/put_parcels.cpp, libs/full/parcelset_base/include/hpx/parcelset_base/detail/per_action_data_counter.hpp, libs/full/parcelset_base/include/hpx/parcelset_base/parcelport.hpp, libs/full/parcelset_base/src/detail/per_action_data_counter.cpp, libs/full/parcelset_base/src/parcelport.cpp, libs/full/performance_counters/include/hpx/performance_counters/counter_creators.hpp, libs/full/performance_counters/include/hpx/performance_counters/per_action_data_counter_discoverer.hpp, libs/full/performance_counters/src/parcelhandler_counter_types.cpp, libs/full/performance_counters/src/per_action_data_counter_discoverer.cpp, libs/full/performance_counters/src/server/per_action_data_counters.cpp
Turn on/off the performance counters related to parcelport
Those counters can be expensive due to the locks when gathering data
=> add cmake option HPX_WITH_PARCELPORT_COUNTERS

libs/full/collectives/include/hpx/collectives/all_gather.hpp, libs/full/collectives/include/hpx/collectives/all_reduce.hpp, libs/full/collectives/include/hpx/collectives/all_to_all.hpp, libs/full/collectives/include/hpx/collectives/broadcast.hpp, libs/full/collectives/include/hpx/collectives/exclusive_scan.hpp, libs/full/collectives/include/hpx/collectives/gather.hpp, libs/full/collectives/include/hpx/collectives/inclusive_scan.hpp, libs/full/collectives/include/hpx/collectives/scatter.hpp
The collectives headers were mentioning a non-existing function create_reducer to create a communicator.
-Renamed all create_reducer instances to the correct create_communicator function.
=> Docs: Replaced non-existent create_reducer function with create_communicator

.circleci/config.yml, cmake/HPX_AddModule.cmake
This hopefully solves the CircleCI problem that the install step rebuilds everything.
=> Prevent certain generated files from being deleted on reconfigure

cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx11_std_atomic.cpp, libs/core/execution_base/tests/unit/execution_context.cpp
The original PR #5864 introduced problems on older platforms. This hopefully fixes those.
=> Fixing recent patch that disables ATOMIC_FLAG_INIT for C++20 and up

docs/sphinx/manual/optimizing_hpx_applications.rst, libs/full/parcelset/include/hpx/parcelset/decode_parcels.hpp, libs/full/parcelset/include/hpx/parcelset/encode_parcels.hpp, libs/full/parcelset/include/hpx/parcelset/parcelhandler.hpp, libs/full/parcelset/src/parcelhandler.cpp, libs/full/parcelset_base/include/hpx/parcelset_base/detail/data_point.hpp, libs/full/parcelset_base/include/hpx/parcelset_base/detail/gatherer.hpp, libs/full/parcelset_base/include/hpx/parcelset_base/parcelport.hpp, libs/full/parcelset_base/src/parcelport.cpp, libs/full/performance_counters/src/parcelhandler_counter_types.cpp
/parcelport/count/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: total number of zero-copy chunks
/parcelport/count-max/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: maximum number of zero-copy chunks per message
/parcelport/size/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: total size of zero-copy chunks
/parcelport/size-max/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: maximum size of zero-copy chunks
=> New performance counters related to zero-copy chunks.

components/performance_counters/papi/include/hpx/components/performance_counters/papi/server/papi.hpp, components/performance_counters/papi/src/server/papi.cpp, examples/performance_counters/sine/server/sine.cpp, libs/full/performance_counters/include/hpx/performance_counters/counters.hpp, libs/full/performance_counters/include/hpx/performance_counters/counters_fwd.hpp, libs/full/performance_counters/include/hpx/performance_counters/manage_counter_type.hpp, libs/full/performance_counters/src/counters.cpp, libs/full/performance_counters/src/manage_counter.cpp, libs/full/performance_counters/src/manage_counter_type.cpp, libs/full/performance_counters/src/registry.cpp, libs/full/performance_counters/src/server/arithmetics_counter.cpp, libs/full/performance_counters/src/server/arithmetics_counter_extended.cpp, libs/full/performance_counters/src/server/elapsed_time_counter.cpp, libs/full/performance_counters/src/server/raw_counter.cpp, libs/full/performance_counters/src/server/raw_values_counter.cpp, libs/full/performance_counters/src/server/statistics_counter.cpp, libs/full/performance_counters/tests/unit/all_counters.cpp, libs/full/performance_counters/tests/unit/path_elements.cpp, libs/full/performance_counters/tests/unit/reinit_counters.cpp
Convert `enum counter_status` to `enum class counter_status` and remove `status_` prefixes from status values.
=> Convert enum counter_status to enum class

libs/core/execution_base/include/hpx/execution_base/sender.hpp, libs/core/execution_base/tests/unit/basic_schedule.cpp
- Alias schedule_result_t gives the result type of schedule
- https://github.com/STEllAR-GROUP/hpx/issues/5045#issuecomment-868810753
=> [execution] Add schedule_result_t alias template.

cmake/HPX_GeneratePackageUtils.cmake
Fixes pkg-config file generation on windows where CMAKE_SHARED_LIBRARY_PREFIX is empty. 
Always quote string like inputs to functions because they can be empty.
=> Add missing ""

components/parcel_plugins/coalescing/include/hpx/parcel_coalescing/counter_registry.hpp, components/parcel_plugins/coalescing/src/coalescing_counter_registry.cpp, components/performance_counters/papi/include/hpx/components/performance_counters/papi/server/papi.hpp, components/performance_counters/papi/src/papi_startup.cpp, examples/performance_counters/sine/sine.cpp, libs/full/init_runtime/src/hpx_init.cpp, libs/full/performance_counters/include/hpx/performance_counters/action_invocation_counter_discoverer.hpp, libs/full/performance_counters/include/hpx/performance_counters/counter_creators.hpp, libs/full/performance_counters/include/hpx/performance_counters/counters.hpp, libs/full/performance_counters/include/hpx/performance_counters/counters_fwd.hpp, libs/full/performance_counters/include/hpx/performance_counters/per_action_data_counter_discoverer.hpp, libs/full/performance_counters/include/hpx/performance_counters/registry.hpp, libs/full/performance_counters/src/action_invocation_counter_discoverer.cpp, libs/full/performance_counters/src/counter_creators.cpp, libs/full/performance_counters/src/counters.cpp, libs/full/performance_counters/src/per_action_data_counter_discoverer.cpp, libs/full/performance_counters/src/performance_counter.cpp, libs/full/performance_counters/src/performance_counter_set.cpp, libs/full/performance_counters/src/registry.cpp, libs/full/performance_counters/src/server/action_invocation_counter.cpp, libs/full/performance_counters/src/server/per_action_data_counters.cpp, libs/full/performance_counters/src/threadmanager_counter_types.cpp, tests/performance/local/activate_counters.cpp
Final enum to enum class conversion for performance counters module (`discover_counter_mode`). It's minimal and couldn't find any local fails so I will let CI guide me. I would hope for these PRs to go to 1.9.
=> Change discover counters mode enum to enum class

examples/quickstart/executor_with_thread_hooks.cpp
Uses `executor_execution_category` and `executor_parameters_type` instead of `embedded types` from the Executor.
=> Fix executor_with_thread_hooks example

CMakeLists.txt
see https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html
`CMAKE_SHARED_LIBS` doesn't exist
=> Use BUILD_SHARED_LIBS correctly

cmake/HPX_AddModule.cmake, cmake/HPX_GeneratePackageUtils.cmake
`$<TARGET_NAME:...>` is required for the install interface
Don't yet know what all the code does but it generates wrong stuff in the INSTALL_INTERFACE which needs to be informed about target names. 
see
https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:TARGET_NAME
Fixes using static exports of HPX on windows.
=> Fix incorrect usage of generator expressions

components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_segmented_iterator.hpp, components/containers/unordered/include/hpx/components/containers/unordered/unordered_map_segmented_iterator.hpp
Some comments for the iterators of `hpx::partitioned_vector` and `hpx::unordered_map` contained references to `hpx::vector`, which was renamed to `hpx::partitioned_vector` a good while ago.
=> Removed references to hpx::vector in comments

libs/core/algorithms/CMakeLists.txt, libs/core/algorithms/include/hpx/parallel/algorithms/detail/reduce.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/reduce.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/transform_reduce.hpp, libs/core/algorithms/include/hpx/parallel/datapar.hpp, libs/core/algorithms/include/hpx/parallel/datapar/iterator_helpers.hpp, libs/core/algorithms/include/hpx/parallel/datapar/loop.hpp, libs/core/algorithms/include/hpx/parallel/datapar/reduce.hpp, libs/core/algorithms/include/hpx/parallel/util/loop.hpp, libs/core/algorithms/tests/unit/algorithms/reduce_tests.hpp, libs/core/algorithms/tests/unit/datapar_algorithms/CMakeLists.txt, libs/core/algorithms/tests/unit/datapar_algorithms/reduce_datapar.cpp, libs/core/algorithms/tests/unit/datapar_algorithms/transform_reduce_datapar.cpp, libs/core/execution/CMakeLists.txt, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_reduce.hpp, libs/core/execution/include/hpx/execution/traits/detail/vc/vector_pack_reduce.hpp, libs/core/execution/include/hpx/execution/traits/vector_pack_reduce.hpp
Contributes to Fixing #2333 
- Adapts new **vector_pack** trait `reduce` to support simd reductions.
- Adapts new **CPO** `sequential_reduce` to support tag_fallback overloads on `reduce, transform_reduce, transform_reduce_binary` algorithms.
- Adds tag dispatching overloads to support data-parallelism on `reduce, transform_reduce, transform_reduce_binary` algorithms.
- Adds unit tests to newly supported data-parallel algorithms.
=> Support for data-parallelism for reduce, transform reduce, transform_binary_reduce algorithms

.jenkins/lsu/env-clang-11.sh, .jenkins/lsu/env-clang-12.sh, .jenkins/lsu/env-clang-13.sh, .jenkins/lsu/env-clang-14.sh, .jenkins/lsu/env-gcc-10.sh, .jenkins/lsu/env-gcc-11.sh, .jenkins/lsu/env-gcc-9.sh, cmake/FindPWR.cmake, components/performance_counters/CMakeLists.txt, components/performance_counters/power/CMakeLists.txt, components/performance_counters/power/include/hpx/components/performance_counters/power/power_counter.hpp, components/performance_counters/power/src/power.cpp, components/performance_counters/power/src/power_counter.cpp, components/performance_counters/power/tests/CMakeLists.txt, components/performance_counters/power/tests/performance/CMakeLists.txt, components/performance_counters/power/tests/regressions/CMakeLists.txt, components/performance_counters/power/tests/unit/CMakeLists.txt, components/performance_counters/power/tests/unit/power_counter.cpp
This adds an HPX performance counter `/runtime{locality#N/total}/average_power`. The power consumption is collected through the PWR library (http://powerapi.sandia.gov/).
The build system expects for the library to be installed, available through pkg_config, or found using the `HPX_PWR_ROOT` cmake variable.
=> Adding simple average power consumption performance counter

libs/core/algorithms/include/hpx/parallel/container_algorithms/partial_sort.hpp, libs/core/algorithms/include/hpx/parallel/container_algorithms/sort.hpp, libs/core/algorithms/include/hpx/parallel/container_algorithms/stable_sort.hpp, libs/core/algorithms/include/hpx/parallel/container_algorithms/unique.hpp
Fixes minor typo that might cause hyperlink to break in Doxygen. The warning stems from line #199 and everything below that fails to link to our docs page. Let's merge it as it is a typo anyways and see if it also fixes the linking problem.
I don't think the `\a` clause has to be an one-liner, does it?
=> Fix minor doxygen parsing typo

.gitignore, cmake/templates/conf.py.in
Fixes broken algorithm links on the public API page.
- added vscode's cache directory to gitignore 
- remove part of the commit that broke the links
=> docs: fix broken api algo links

libs/core/assertion/include/hpx/modules/assertion.hpp, libs/core/futures/include/hpx/futures/detail/future_data.hpp, libs/core/futures/src/future_data.cpp, libs/core/synchronization/include/hpx/synchronization/barrier.hpp, libs/core/synchronization/include/hpx/synchronization/detail/condition_variable.hpp, libs/core/synchronization/include/hpx/synchronization/latch.hpp, libs/core/synchronization/src/detail/condition_variable.cpp, libs/core/synchronization/src/stop_token.cpp, libs/core/thread_support/include/hpx/thread_support/assert_owns_lock.hpp
- flyby: introduce HPX__ASSERT_LOCKED() et.al. facilities that unlock a given lock
before invoking the assert
=> Fixing various 'held lock while suspending' problems

libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp, libs/core/execution_base/include/hpx/execution_base/receiver.hpp, libs/core/execution_base/tests/unit/basic_receiver.cpp, libs/core/execution_base/tests/unit/basic_sender.cpp
- The `receiver_of` concept takes a receiver and an instance of the `completion_signatures<>` class template.
- The `sender_of` concept defines the requirements for a sender type that on successful completion sends the specified set of value types.
=> [P2300] enhancements: receiver_of, sender_of improvements

components/parcel_plugins/binary_filter/bzip2/include/hpx/binary_filter/bzip2_serialization_filter.hpp, components/parcel_plugins/binary_filter/bzip2/src/bzip2_serialization_filter.cpp, components/parcel_plugins/binary_filter/snappy/include/hpx/binary_filter/snappy_serialization_filter.hpp, components/parcel_plugins/binary_filter/snappy/src/snappy_serialization_filter.cpp, components/parcel_plugins/binary_filter/zlib/include/hpx/binary_filter/zlib_serialization_filter.hpp, components/parcel_plugins/binary_filter/zlib/src/zlib_serialization_filter.cpp, libs/core/datastructures/include/hpx/datastructures/serialization/serializable_any.hpp, libs/core/datastructures/src/serializable_any.cpp, libs/core/memory/tests/unit/intrusive_ptr_polymorphic.cpp, libs/core/serialization/include/hpx/serialization/binary_filter.hpp, libs/core/serialization/include/hpx/serialization/detail/polymorphic_intrusive_factory.hpp, libs/core/serialization/include/hpx/serialization/input_archive.hpp, libs/core/serialization/include/hpx/serialization/output_archive.hpp, libs/core/serialization/tests/regressions/CMakeLists.txt, libs/core/serialization/tests/regressions/serialization_unsigned_buffer.cpp, libs/core/serialization/tests/unit/not_bitwise_serializable.cpp, libs/core/serialization/tests/unit/polymorphic/polymorphic_pointer.cpp, libs/core/serialization/tests/unit/polymorphic/polymorphic_reference.cpp, libs/core/serialization/tests/unit/polymorphic/polymorphic_template.cpp, libs/core/serialization/tests/unit/polymorphic/smart_ptr_polymorphic.cpp
- flyby: add 'override' specifiers to compression filters
- flyby: add tests for explicitly signed and long long integral types
- flyby: add support for long double to serialization
=> Fixing serialization to work with buffers of unsigned chars

libs/full/collectives/include/hpx/collectives/all_reduce.hpp, libs/full/collectives/include/hpx/collectives/broadcast.hpp, libs/full/collectives/include/hpx/collectives/channel_communicator.hpp, libs/full/collectives/include/hpx/collectives/detail/communicator.hpp, libs/full/collectives/include/hpx/collectives/exclusive_scan.hpp, libs/full/collectives/include/hpx/collectives/inclusive_scan.hpp, libs/full/collectives/include/hpx/collectives/reduce.hpp, libs/full/collectives/include/hpx/collectives/scatter.hpp, libs/full/collectives/tests/regressions/CMakeLists.txt, libs/full/collectives/tests/regressions/collectives_bool_5940.cpp, libs/full/collectives/tests/unit/exclusive_scan_.cpp, libs/full/collectives/tests/unit/inclusive_scan_.cpp
- std::vector<T> is internally used to store intermediate results for the collective operations. This change makes sure that automatic return type deduction does not get fooled by the `vector<bool>`'s proxy value_type.
=> Protect collective operations against std::vector<bool> idiosyncrasies

components/performance_counters/memory/src/mem_counter_linux.cpp, libs/core/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp, libs/core/coroutines/include/hpx/coroutines/detail/posix_utility.hpp, libs/core/debugging/src/backtrace.cpp, libs/core/plugin/include/hpx/plugin/detail/dll_dlopen.hpp
These are some patches that make it possible to build hpx on musl.
Signed-off-by: brahmajit das <brahmajit.xyz@gmail.com>
Fixes #5946
- EXEC_PAGESIZE is not defined under musl so including linux/param.h
where it should be defined. Header linux/param.h does not depend on
any libc and hence can use included on any linux system.
- execinfo.h is only present on glibc and ulibc, but not on musl so
before defining HPX_HAVE_EXECINFO it's being checked whether we're on
a glibc or ulibc system
- RTLD_DI_ORIGIN is not present on musl, hence the alternate
the solution is implemented if RTLD_DI_ORIGIN is undefined.
hpx was failing to build with musl libc, these patches should fix them without affecting other libc systems
=> Fix building on musl.

libs/core/algorithms/include/hpx/parallel/algorithms/reduce.hpp
- renamed iterator to correct type (`FwdIter` to `InItr`) in some `reduce` overloads
=> refactor: rename itr to correct type (`reduce`)

libs/core/algorithms/tests/unit/container_algorithms/foreach_tests.hpp, libs/core/async_cuda/tests/unit/transform_stream.cu, libs/core/async_mpi/tests/unit/algorithm_transform_mpi.cpp, libs/core/execution/include/hpx/execution/algorithms/detail/single_result.hpp, libs/core/execution/include/hpx/execution/algorithms/sync_wait.hpp, libs/core/execution/tests/unit/algorithm_sync_wait.cpp, libs/core/execution_base/tests/include/algorithm_test_utils.hpp, libs/core/executors/tests/unit/thread_pool_scheduler.cpp
Issue:
_sync_wait implementation assumes the senders send only one single value. (Actually, senders can pass several values);
sync_wait looks at the variant of the predecessor and makes sure that it contains one tuple with one element._
which is not conform to the description of sync_wait in P2300.
revamp :
The result_type should be optional of the variant of the tuples;
The sync_wait works when the variant has one tuple( no matter how many elements in the tuple)
=> Fix sync_wait

examples/quickstart/hello_world_distributed.cpp, libs/full/collectives/include/hpx/collectives/latch.hpp, libs/full/performance_counters/include/hpx/performance_counters/performance_counter.hpp
- flyby: fix dll-export warnigs
=> Prevent stalling during shutdown when running hello_world_distributed

CMakeLists.txt, cmake/TargetArch.cmake, libs/core/config/include/hpx/config/compiler_fence.hpp, libs/core/coroutines/include/hpx/coroutines/detail/get_stack_pointer.hpp, libs/core/hardware/CMakeLists.txt, libs/core/hardware/include/hpx/hardware/timestamp.hpp, libs/core/hardware/include/hpx/hardware/timestamp/linux_riscv_64.hpp
N/A; adds processor support (new feature)
- adds risc-v 64 bit support; required small changes to CMake build scripts and runtime source pertaining to compiler-fence, stack-pointer access, and timestamp.
PR provides support for risc-v 64 bit processors. PR developed and tested in the following hardware and software environment:
- Hardware: SiFive HiFive Unleashed
- OS: Ubuntu 10.3.0-1
- Compiler: gcc/g++ 10.3.0
- Cluster Management: Slurm 20.11.4
- Parcelport tested: TCP/IP
Compiled using the following flags:
`cmake -D HPX_WITH_GENERIC_CONTEXT_COROUTINES=ON -DHPX_WITH_FETCH_ASIO=ON -DBOOST_ROOT=<PATH_TO_BOOST> -DHPX_WITH_MALLOC=tcmalloc ..`
The existing suite of example and test programs work.
=> adds risc-v 64 bit support

libs/core/async_combinators/CMakeLists.txt, libs/core/async_combinators/include/hpx/async_combinators/wait_all.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_any.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_each.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_some.hpp, libs/core/async_combinators/include/hpx/async_combinators/when_all.hpp, libs/core/async_combinators/include/hpx/async_combinators/when_any.hpp, libs/core/async_combinators/include/hpx/async_combinators/when_each.hpp, libs/core/async_combinators/include/hpx/async_combinators/when_some.hpp, libs/core/async_combinators/tests/unit/wait_all.cpp, libs/core/async_combinators/tests/unit/when_all.cpp, libs/core/async_combinators/tests/unit/when_any.cpp, libs/core/async_combinators/tests/unit/when_some.cpp, libs/core/execution_base/include/hpx/execution_base/traits/is_executor_parameters.hpp
- flyby: add unary wait_all() expecting a single future
=> Converting async combinators into CPOs

cmake/TargetArch.cmake, libs/core/hardware/include/hpx/hardware/timestamp/linux_riscv_64.hpp, libs/core/hardware/tests/CMakeLists.txt
Modification to cmake target detection script. Enforces 64-bit target constraint on risc-v builds.
- cmake/TargetArch.cmake has 1 modification
Current risc-v support does not check to see if the compiler is configured for the 32 bit or 64 bit build target. This PR enforces a check, in cmake, making sure the 64-bit build target is configured in the compiler.
=> added logic to detect riscv compiler configured for 64 bit target

CMakeLists.txt, cmake/TargetArch.cmake
N/A
- when riscv64 detected, automatically sets `HPX_WITH_GENERIC_CONTEXT_COROUTINES=ON` (Boost.Context)
- eases compilation process for users; "quality of life" modification.
=> defaults boost.context on riscv64

libs/core/execution_base/tests/unit/completion_signatures.cpp
- Wrap completion_signatures awaitable tests using HPX_HAVE_CXX20_COROUTINES
Fixes #
https://github.com/STEllAR-GROUP/hpx/runs/7716108866?check_suite_focus=true
=> fix: Compilation errors for -std=c++17 builders

libs/core/affinity/src/affinity_data.cpp, libs/core/algorithms/tests/performance/foreach_report.cpp, libs/core/allocator_support/include/hpx/allocator_support/internal_allocator.hpp, libs/core/compute_local/CMakeLists.txt, libs/core/compute_local/include/hpx/compute_local/host/block_allocator.hpp, libs/core/compute_local/include/hpx/compute_local/host/block_fork_join_executor.hpp, libs/core/compute_local/tests/unit/CMakeLists.txt, libs/core/compute_local/tests/unit/block_fork_join_executor.cpp, libs/core/config/include/hpx/config/compiler_fence.hpp, libs/core/coroutines/src/thread_enums.cpp, libs/core/executors/CMakeLists.txt, libs/core/executors/include/hpx/executors/fork_join_executor.hpp, libs/core/executors/tests/unit/thread_pool_scheduler.cpp, libs/core/iterator_support/include/hpx/iterator_support/counting_iterator.hpp, libs/core/iterator_support/include/hpx/iterator_support/counting_shape.hpp, libs/core/iterator_support/include/hpx/iterator_support/iterator_range.hpp, libs/core/resource_partitioner/include/hpx/resource_partitioner/detail/partitioner.hpp, libs/core/resource_partitioner/src/detail_partitioner.cpp, libs/core/schedulers/include/hpx/schedulers/local_priority_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/local_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp, libs/core/threading_base/include/hpx/threading_base/annotated_function.hpp, libs/core/threading_base/include/hpx/threading_base/scheduler_base.hpp, libs/core/threading_base/include/hpx/threading_base/thread_description.hpp, libs/core/threading_base/src/create_work.cpp, libs/core/topology/include/hpx/topology/cpu_mask.hpp, libs/core/topology/include/hpx/topology/topology.hpp, tests/performance/local/stream.cpp
The `block_fork_join_executor` is building on top of a set of plain `fork_join_executor`s such that those build a hierarchy of executors allowing to restrict the necessary synchronization to a subset of cores for each of those executors. This allows to build for instance a NUMA-aware `fork_join_executor`, where each of the NUMA-domains has its own executor and those are combined into a higher-level executor that performs synchronization between the NUMA-domains.
The hope is that this executor helps reducing cross-NUMA domain synchronization. 
This PR contains a couple of flyby changes:
- adding support for `thread_priority::bound` to the default scheduler
- replace some of the uses of `boost::irange` with our `hpx::util::detail::make_counting_shape`
- added `thread_description(std::string …
=> Block fork join executor

.jenkins/lsu/env-clang-13.sh, .jenkins/lsu/env-clang-14.sh
- fixing configuration of our clang-v13 builder
=> Using EVE requires C++20

libs/core/runtime_local/src/runtime_local.cpp
According to https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler
returning TRUE will stop further execution of installed handlers and stop the normal handler from running.
=> Fix CTRL+C on windows

libs/core/executors/include/hpx/executors/execution_policy.hpp
This fixes oversight that introduces an incompatibility with HPX-Kokkos
=> Re-add deprecated tag_policy_tag et.al. types that were removed in V1.8.1

libs/core/execution/include/hpx/execution/algorithms/run_loop.hpp, libs/core/executors/include/hpx/executors/fork_join_executor.hpp
Fixes compilation with nvcc. I can also make the template arguments conditional on whether CUDA was enabled or not if you prefer.
=> Add back explicit template parameters to lock_guards for nvcc

libs/core/datastructures/include/hpx/datastructures/serialization/tuple.hpp, libs/full/actions/tests/regressions/CMakeLists.txt, libs/full/actions/tests/regressions/non_default_constructible_argument_5998.cpp
- if one or more argument to an action was non-default constructible, then the other (default constructible) arguments were not always properly constructed
Fixes #5998
=> Making sure that default constructble arguments are properly constructed during deserialization

cmake/templates/hpxcxx.in
Recently, I attempted to compile simple_resource_partitioner.cpp using hpxcxx and got some undefined symbols, but these symbols were defined in libhpx_init.a, a library that is already on the link line.
Add -Wl,--start-group before linking libs and -Wl,--end-group after linking libs.
=> Add --start-group and --end-group before libraries are added for linking

docs/sphinx/manual/launching_and_configuring_hpx_applications.rst, libs/core/asio/include/hpx/asio/asio_util.hpp, libs/core/asio/include/hpx/asio/map_hostnames.hpp, libs/core/asio/src/asio_util.cpp, libs/core/asio/src/map_hostnames.cpp, libs/full/command_line_handling/src/command_line_handling.cpp, libs/full/command_line_handling/src/parse_command_line.cpp
- add an option to force resolving hostnames to ipv4 adresses
Local hostnames on windows are commonly resolved to ipv6 addresses while remote hostnames resolved to ipv4 addresses. This leads to hpx applications to listen on the wrong addresses if using hostnames on windows. 
The following code might also be related to this since pinging localhost returns a ipv6 `::1` instead of ipv4. 
https://github.com/STEllAR-GROUP/hpx/blob/435ae68f04084df3fa652ef76571b78db1980e8d/libs/core/asio/src/map_hostnames.cpp#L26-L36
Maybe HPX should detect ipv4/ipv6 mismatch on its own since it has to lookup the endpoints any way?
=> add option hpx:force_ipv4 to force resolving hostnames to ipv4 adresses

libs/core/execution/include/hpx/execution/algorithms/sync_wait.hpp, libs/core/execution/tests/unit/CMakeLists.txt, libs/core/execution/tests/unit/algorithm_sync_wait_with_variant.cpp, libs/core/execution_base/tests/include/algorithm_test_utils.hpp
Ref: [P2300R5](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2300r5.html#example-schedulers)
Integrate sync_wait and sync_wait_with_variant.
-  I have added a new feature and have added tests to go along with it.
=> Integrating sync_wait & sync_wait_with_variant

libs/core/plugin/include/hpx/plugin/traits/plugin_config_data.hpp, libs/full/init_runtime/src/hpx_init.cpp, libs/full/parcelport_lci/src/parcelport_lci.cpp, libs/full/parcelport_libfabric/include/hpx/parcelport_libfabric/parcelport_libfabric.hpp, libs/full/parcelport_mpi/src/parcelport_mpi.cpp, libs/full/parcelport_tcp/src/parcelport_tcp.cpp, libs/full/parcelset/include/hpx/parcelset/parcelhandler.hpp, libs/full/parcelset/src/parcelhandler.cpp, libs/full/plugin_factories/include/hpx/plugin_factories/parcelport_factory.hpp, libs/full/plugin_factories/include/hpx/plugin_factories/parcelport_factory_base.hpp
This adds a hook to all parcelports that will be invoked during initialization giving each parcelport a chance to create thread pools or perform other initialization work involving the resource partitioner.
=> Adding parcelport initialization hook for resource partitioner operation

examples/quickstart/CMakeLists.txt, examples/quickstart/hello_world_3.cpp, libs/core/command_line_handling_local/include/hpx/command_line_handling_local/command_line_handling_local.hpp, libs/core/command_line_handling_local/include/hpx/command_line_handling_local/late_command_line_handling_local.hpp, libs/core/command_line_handling_local/include/hpx/command_line_handling_local/parse_command_line_local.hpp, libs/core/command_line_handling_local/src/command_line_handling_local.cpp, libs/core/command_line_handling_local/src/late_command_line_handling_local.cpp, libs/core/command_line_handling_local/src/parse_command_line_local.cpp, libs/core/init_runtime_local/include/hpx/init_runtime_local/init_runtime_local.hpp, libs/core/init_runtime_local/src/init_runtime_local.cpp, libs/full/command_line_handling/include/hpx/command_line_handling/command_line_handling.hpp, libs/full/command_line_handling/src/command_line_handling.cpp, libs/full/command_line_handling/src/late_command_line_handling.cpp, libs/full/command_line_handling/src/parse_command_line.cpp, libs/full/init_runtime/include/hpx/hpx_init_params.hpp
- flyby: add purely local hello world example
- flyby: fix APPLICATION name for local runtime
=> Clean up command line handling

.cmake-format.py, cmake/HPX_AddModule.cmake, libs/core/async_base/CMakeLists.txt, libs/core/async_base/include/hpx/async_base/dataflow.hpp, libs/core/executors/CMakeLists.txt, libs/core/executors/include/hpx/executors/dataflow.hpp, libs/core/functional/include/hpx/functional/invoke_fused.hpp, libs/core/futures/CMakeLists.txt, libs/core/resiliency/include/hpx/resiliency/async_replicate.hpp, libs/full/async_distributed/include/hpx/async_distributed/dataflow.hpp, libs/full/async_distributed/tests/unit/remote_dataflow.cpp
- introduce `hpx::detail::dataflow_t` CPO
- deprecate `dataflow_alloc()` and `dataflow<Action>()`
=> Modernize dataflow API

.github/workflows/linux_crosscompile_arm_sve_release.yml, cmake/HPX_SetupDatapar.cmake, cmake/HPX_SetupSVE.cmake, cmake/templates/HPXConfig.cmake.in, libs/CMakeLists.txt, libs/core/execution/CMakeLists.txt, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_alignment_size.hpp, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_all_any_none.hpp, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_conditionals.hpp, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_count_bits.hpp, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_find.hpp, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_get_set.hpp, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_load_store.hpp, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_reduce.hpp, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_simd.hpp, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_type.hpp, libs/core/functional/tests/regressions/is_callable_1179.cpp
- Adds cmake integration for SVE through `find_package(sve)` and `cmake_fetch_content`. 
- Adds a common namespace and header to use existing vector_pack traits.
=> Support new datapar backend : SVE

libs/core/algorithms/include/hpx/parallel/algorithms/remove.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/unique.hpp, libs/core/algorithms/include/hpx/parallel/util/scan_partitioner.hpp
- Removed scan_partitioner sequential f3 implementation (obsolete)
- Refactored parallel algorithms that used above implementation ("remove" and "unique") to use util::partitioner instead
- Marginal performance improvement (if any)
=> Clean up scan_partitioner

libs/core/execution_base/tests/include/coroutine_task.hpp, libs/core/execution_base/tests/unit/coroutine_utils.cpp
- flyby: used predefined `stop_token_of_t` instead of redefining it
https://cdash.cscs.ch/viewBuildError.php?buildid=43534
- `std::declval` is not supposed to be ODR used.
=> [P2300] Fix: declval cannot be ODR used

libs/core/algorithms/include/hpx/parallel/algorithms/detail/dispatch.hpp, libs/core/executors/examples/executor_with_thread_hooks.cpp, libs/core/executors/tests/regressions/CMakeLists.txt, libs/core/executors/tests/regressions/wrapping_executor.cpp
- when used with a seq(task) execution policy
- flyby: modernize executor_with_thread_hooks example
=> Make sure wrapping executor does not go out of scope prematurely

docs/sphinx/api/public_api.rst, libs/core/algorithms/include/hpx/parallel/task_group.hpp, libs/core/algorithms/include/hpx/parallel/util/detail/partitioner_iteration.hpp, libs/core/compute_local/include/hpx/compute_local/host/block_allocator.hpp, libs/core/execution/include/hpx/execution/algorithms/let_value.hpp, libs/core/execution/include/hpx/execution/algorithms/schedule_from.hpp, libs/core/execution/include/hpx/execution/algorithms/split.hpp, libs/core/execution_base/tests/unit/any_sender.cpp, libs/core/executors/include/hpx/executors/dataflow.hpp, libs/core/executors/include/hpx/executors/fork_join_executor.hpp, libs/core/executors/include/hpx/executors/guided_pool_executor.hpp, libs/core/executors/include/hpx/executors/scheduler_executor.hpp, libs/core/executors/include/hpx/executors/thread_pool_scheduler_bulk.hpp, libs/core/functional/docs/index.rst, libs/core/functional/include/hpx/functional/invoke_fused.hpp, libs/core/include_local/include/hpx/local/functional.hpp, libs/core/lcos_local/tests/unit/local_dataflow_external_future.cpp, libs/core/pack_traversal/include/hpx/pack_traversal/detail/pack_traversal_async_impl.hpp, libs/core/pack_traversal/include/hpx/pack_traversal/detail/pack_traversal_impl.hpp, libs/core/pack_traversal/include/hpx/pack_traversal/detail/unwrap_impl.hpp, libs/core/resiliency/include/hpx/resiliency/async_replicate_executor.hpp, libs/core/resource_partitioner/examples/async_customization.cpp, libs/full/actions_base/include/hpx/actions_base/basic_action.hpp
Deprecated:
-  `hpx::util::invoke_fused` in favor of `hpx::invoke_fused`
-  `hpx::util::invoke_fused_r` in favor of `hpx::invoke_fused_r`
Working towards resolving https://github.com/STEllAR-GROUP/hpx/issues/6000
=> Deprecated hpx::util::invoke_fused in favor of hpx::invoke_fused

libs/core/compute_local/include/hpx/compute_local/host/numa_binding_allocator.hpp, libs/full/parcelset_base/include/hpx/parcelset_base/locality.hpp, libs/full/parcelset_base/include/hpx/parcelset_base/parcelset_base_fwd.hpp
This PR contains a subset of patches I use to be able to build HPX-1.8.1 on all platforms I use.
Not all patches I use are needed anymore with the current state of the master branch. I left those out.
I did not keep track of which platform (OS, compiler) required which patch, unfortunately. Will do that in future cases.
The second patch, in `parcelset_base_fwd.hpp` is weird, but required in some case(s). IIRC, the `locality` class is already annotated with export somewhere else and the compiler didn't like the second occurrence. I could be wrong.
=> Patches needed to be able to build HPX 1.8.1 on various platforms

docs/sphinx/manual/launching_and_configuring_hpx_applications.rst, libs/core/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp, libs/core/coroutines/include/hpx/coroutines/signal_handler_debugging.hpp, libs/core/coroutines/src/signal_handler_debugging.cpp, libs/core/runtime_configuration/src/runtime_configuration.cpp, libs/core/runtime_local/src/runtime_local.cpp
This adds the `hpx.handle_signals` configuration option (defaults to `1`), which if set to `0` will disable handling signal handlers. This allows to generate core dumps to support debugging.
This is limited to non-windows systems.
@srinivasyadav18 this PR enables using the `--hpx:ini=hpx.handle_signals!=0` command line option instead of commenting out the signal registration. Please verify.
=> Allow to disable registering signal handlers

libs/core/functional/docs/index.rst, libs/core/functional/include/hpx/functional/mem_fn.hpp, libs/core/functional/tests/unit/mem_fn_derived_test.cpp, libs/core/functional/tests/unit/mem_fn_dm_test.cpp, libs/core/functional/tests/unit/mem_fn_eq_test.cpp, libs/core/functional/tests/unit/mem_fn_rv_test.cpp, libs/core/functional/tests/unit/mem_fn_test.cpp, libs/core/functional/tests/unit/mem_fn_unary_addr_test.cpp, libs/core/functional/tests/unit/mem_fn_void_test.cpp, libs/core/include_local/include/hpx/local/functional.hpp
Deprecated `hpx::util::mem_fn` in favor of `hpx::mem_fn`
Working towards resolving https://github.com/STEllAR-GROUP/hpx/issues/6000
=> Deprecated hpx::util::mem_fn in favor of hpx::mem_fn

libs/core/executors/include/hpx/executors/execution_policy.hpp, libs/core/executors/include/hpx/executors/execution_policy_mappings.hpp
This prevents using constructs like `task(par)` while still allowing writing `par(task)` (and similar).
=> Prevent using task and non_task as a CPO

libs/core/algorithms/tests/unit/container_algorithms/foreach_tests.hpp, libs/core/algorithms/tests/unit/container_algorithms/foreach_tests_projection.hpp, libs/core/concurrency/include/hpx/concurrency/cache_line_data.hpp, libs/core/config/include/hpx/config/constexpr.hpp, libs/core/datastructures/CMakeLists.txt, libs/core/datastructures/include/hpx/datastructures/detail/intrusive_list.hpp, libs/core/datastructures/tests/unit/CMakeLists.txt, libs/core/datastructures/tests/unit/intrusive_list.cpp, libs/core/synchronization/include/hpx/synchronization/detail/condition_variable.hpp, libs/core/synchronization/include/hpx/synchronization/mutex.hpp, libs/core/synchronization/include/hpx/synchronization/spinlock.hpp, libs/core/synchronization/src/detail/condition_variable.cpp, libs/core/synchronization/src/mutex.cpp, libs/core/thread_support/include/hpx/thread_support/atomic_count.hpp
Fixes #6008
This also helps with #3440
=> Making default constructor of hpx::mutex constexpr

libs/core/algorithms/include/hpx/parallel/util/detail/sender_util.hpp, libs/core/algorithms/tests/unit/algorithms/CMakeLists.txt, libs/core/algorithms/tests/unit/algorithms/foreach_scheduler.cpp, libs/core/execution_base/include/hpx/execution_base/sender.hpp, libs/core/executors/CMakeLists.txt, libs/core/executors/include/hpx/executors/execute_on.hpp
This PR adds the facilities that are proposed by [P2690](http://wg21.link/p2690). It also adds default implementations for all of our algorithms.
Coincidentally, this goes beyond P2690 as it also enables asynchronous invocations of the algorithms using the new facilities. Here are a couple of examples:
```
// synchronous parallel invocation
hpx::for_each(scheduler_t(), std::begin(c), std::end(c), f);
// synchronous invocation using hpx::execution::par
hpx::for_each(ex::execute_on(scheduler_t(), hpx::execution::par), std::begin(c), std::end(c), f);
// asynchronous invocation using hpx::execution::par
hpx::for_each(
ex::execute_on(scheduler_t(), hpx::execution::par(hpx::execution::task)), std::begin(c), std::end(c), f) | 
tt::sync_wait();
// asynchronous invocation using hpx::execution::par …
```
=> Implement P2690 for our algorithms

libs/core/algorithms/include/hpx/parallel/algorithms/detail/find.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/find.hpp, libs/core/algorithms/include/hpx/parallel/datapar/find.hpp, libs/core/algorithms/include/hpx/parallel/datapar/iterator_helpers.hpp, libs/core/algorithms/include/hpx/parallel/datapar/loop.hpp, libs/core/algorithms/include/hpx/parallel/util/loop.hpp
The goal is to improve the performance of the algorithms that rely on optional cancellation (like `hpx::find`, et.al.)
=> Do not check for cancellation during each iteration but only once per partition

components/process/include/hpx/components/process/util/posix/initializers/close_fds.hpp, components/process/include/hpx/components/process/util/posix/initializers/close_fds_if.hpp, examples/1d_stencil/1d_stencil_4.cpp, examples/1d_stencil/1d_stencil_4_repart.cpp, examples/1d_stencil/1d_stencil_4_throttle.cpp, examples/jacobi/jacobi_component/row_range.hpp, examples/transpose/transpose_await.cpp, examples/transpose/transpose_block.cpp, examples/transpose/transpose_smp.cpp, examples/transpose/transpose_smp_block.cpp, libs/core/algorithms/include/hpx/parallel/spmd_block.hpp, libs/core/algorithms/include/hpx/parallel/util/detail/chunk_size.hpp, libs/core/iterator_support/tests/performance/stencil3_iterators.cpp, libs/core/resiliency/tests/performance/replay/1d_stencil.cpp, libs/core/resiliency/tests/performance/replay/1d_stencil_checksum.cpp, libs/core/resiliency/tests/performance/replay/1d_stencil_replay.cpp, libs/core/resiliency/tests/performance/replay/dataflow_replay.cpp, libs/core/resiliency/tests/performance/replay/dataflow_replay_validate.cpp, libs/core/resiliency/tests/performance/replay/pure_dataflow.cpp, libs/core/resiliency/tests/performance/replicate/1d_stencil_replicate.cpp, libs/core/resiliency/tests/performance/replicate/1d_stencil_replicate_checksum.cpp, libs/full/checkpoint/examples/1d_stencil_4_checkpoint.cpp, libs/full/collectives/include/hpx/collectives/spmd_block.hpp, libs/full/collectives/tests/performance/osu/osu_bw.cpp, libs/full/collectives/tests/performance/osu/osu_latency.cpp, libs/full/collectives/tests/performance/osu/osu_multi_lat.cpp, libs/full/collectives/tests/regressions/barrier_hang.cpp, tools/inspect/deprecated_include_check.cpp
=> Replacing facilities from Boost.Range

cmake/tests/cxx20_no_unique_address_attribute.cpp
clang-cl does not support `[[no_unique_address]]` nor does it support `[[msvc::no_unique_address]]`. This PR fixes the related warning generated by it.
=> Prevent warnings generated by clang-cl

cmake/tests/cxx17_aligned_new.cpp
=> Use pragma error directive to report warnings as errors on msvc

docs/sphinx/api/public_api.rst, libs/core/functional/include/hpx/functional/bind_back.hpp, libs/core/functional/include/hpx/functional/bind_front.hpp, libs/core/functional/include/hpx/functional/traits/is_bind_expression.hpp, libs/core/functional/include/hpx/functional/traits/is_placeholder.hpp
- Add documentation for `bind_back`
- Fix documentation for `bind_front`, `is_placeholder`, `is_bind_expression`
=> Add/fix Public API documentation

CMakeLists.txt, docs/sphinx/api/public_api.rst, docs/sphinx/manual/writing_single_node_hpx_applications.rst, examples/quickstart/sort_by_key_demo.cpp, libs/core/algorithms/include/hpx/parallel/algorithms/for_loop_induction.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/for_loop_reduction.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/reduce_by_key.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/sort_by_key.hpp, libs/core/algorithms/tests/unit/algorithms/reduce_by_key.cpp, libs/core/algorithms/tests/unit/algorithms/sort_by_key.cpp, libs/core/runtime_local/include/hpx/runtime_local/runtime_local_fwd.hpp
- Fix typos
- Move functions to `experimental` namespace
=> Deprecate `hpx::parallel::reduce_by_key` in favor of `hpx::experimental::reduce_by_key`

cmake/templates/conf.py.in, docs/sphinx/api/public_api.rst, libs/core/algorithms/include/hpx/parallel/task_group.hpp
- Add header file `task_group.hpp` to the Public API page
- Add documentation for `task_group`
=> Document `task_group` and include in Public API

libs/full/parcelset_base/include/hpx/parcelset_base/detail/gatherer.hpp
Fix a typo:
Initialize buffer_allocate_time_ to 0. Otherwise, it will give a random number.
BTW, this "buffer allocation time" performance counter doesn't appear to be updated anywhere in the code.
=> Initialize buffer_allocate_time_ to 0

libs/core/resource_partitioner/src/partitioner.cpp
Remove the mutex lock in the critical path of hpx::resource::detail::get_partitioner.
The protected variable `partitioner_ref` is only set once during initialization.
=> Remove the mutex lock in the critical path of get_partitioner.

libs/core/schedulers/CMakeLists.txt, libs/core/schedulers/include/hpx/modules/schedulers.hpp, libs/core/schedulers/include/hpx/schedulers/background_scheduler.hpp, libs/core/thread_pools/include/hpx/thread_pools/scheduling_loop.hpp, libs/core/thread_pools/src/scheduled_thread_pool.cpp, libs/core/threading_base/include/hpx/threading_base/scheduler_mode.hpp, libs/core/threadmanager/include/hpx/modules/threadmanager.hpp, libs/core/threadmanager/src/threadmanager.cpp
@JiakunYan This adds a new scheduler that is an abridged version of the static scheduler. This one allows running background threads only, no real work can be submitted to it. You can enable this scheduler by calling
```
rp.create_thread_pool("lci-progress-pool",
hpx::resource::scheduling_policy::static_,   // note: use static_
hpx::threads::policies::scheduler_mode::do_background_work_only);
```
Please let me know if this resolves your issues.
=> Adding abridged static scheduler that supports running background threads only

libs/full/parcelset/src/parcelhandler.cpp, libs/full/parcelset_base/include/hpx/parcelset_base/parcelport.hpp, libs/full/parcelset_base/src/parcelport.cpp
Parcelports now can override a new function `void initialized()` that will be called after early parcel handling is finished and before the thread pools are operational (i.e. before background work starts).
@JiakunYan please let me know if this is what you requested.
=> Adding notification function for parcelports to be called after early parcel handling

examples/quickstart/CMakeLists.txt, examples/quickstart/simple_master_slave.cpp
The purpose of this example is to demonstrate how HPX actions can be used to build a simple master-slave application. The master (locality 0) assigns work to the slaves (all other localities). Note that if this application is run on one locality only it uses the same locality for the master and the slave functionalities.
The slaves receive a message that encodes how many sub-tasks of a certain type they should spawn locally.
=> Adding example of a simple master/slave distributed application

libs/core/coroutines/include/hpx/coroutines/detail/posix_utility.hpp
This reduces the exploitation surface area and resolves an issue with macOS hardened runtime that does not allow executable memory without an entitlement.
=> Make posix co-routine stacks non-executable

.jenkins/lsu/env-gcc-10-cuda-11.sh, libs/core/async_combinators/include/hpx/async_combinators/wait_all.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_any.hpp, libs/core/async_combinators/include/hpx/async_combinators/wait_some.hpp, libs/core/coroutines/include/hpx/coroutines/detail/coroutine_impl.hpp, libs/core/threading_base/include/hpx/threading_base/detail/reset_lco_description.hpp
- this fixes ambiguities if another library defines its own tag_invoke overloads
- flyby: add missing constexpr, suppress dllexport warnings
=> Avoid ambiguities wrt tag_invoke

libs/core/resource_partitioner/include/hpx/resource_partitioner/detail/partitioner.hpp, libs/core/resource_partitioner/include/hpx/resource_partitioner/partitioner.hpp, libs/core/resource_partitioner/include/hpx/resource_partitioner/partitioner_fwd.hpp, libs/core/resource_partitioner/src/detail_partitioner.cpp, libs/core/resource_partitioner/src/partitioner.cpp, libs/core/resource_partitioner/tests/unit/CMakeLists.txt, libs/core/resource_partitioner/tests/unit/background_scheduler.cpp, libs/core/schedulers/include/hpx/schedulers/background_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/local_priority_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/local_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/static_priority_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/static_queue_scheduler.hpp, libs/core/thread_pools/CMakeLists.txt, libs/core/thread_pools/include/hpx/thread_pools/detail/background_thread.hpp, libs/core/thread_pools/include/hpx/thread_pools/detail/scheduling_callbacks.hpp, libs/core/thread_pools/include/hpx/thread_pools/detail/scheduling_counters.hpp, libs/core/thread_pools/include/hpx/thread_pools/detail/scoped_background_timer.hpp, libs/core/thread_pools/include/hpx/thread_pools/scheduling_loop.hpp, libs/core/thread_pools/src/detail/background_thread.cpp, libs/core/threading_base/include/hpx/threading_base/scheduler_base.hpp, libs/core/threading_base/include/hpx/threading_base/threading_base_fwd.hpp, libs/core/threadmanager/src/threadmanager.cpp, libs/full/runtime_distributed/src/runtime_distributed.cpp
- flyby: add API to add background work to any thread pool
=> Fixing background scheduler to properly exit in the end

cmake/templates/hpxcxx.in
The arg parsing logic was broken in a number of ways. For example, if any option was provided after -rd (RelWithDebInfo), it automatically reverted to -r (Release). The same for -g, etc. In addition "-rd" is non-standard for a multi-letter unix arg. It was changed to --rd.
=> The -rd and -mr options didn't work, and they should have been --rd and --mr

libs/full/agas/tests/regressions/send_gid_keep_component_1624.cpp, libs/full/agas_base/include/hpx/agas_base/server/primary_namespace.hpp, libs/full/agas_base/src/server/primary_namespace_server.cpp, libs/full/components_base/include/hpx/components_base/server/managed_component_base.hpp, libs/full/components_base/include/hpx/components_base/server/wrapper_heap.hpp, libs/full/components_base/include/hpx/components_base/server/wrapper_heap_base.hpp, libs/full/components_base/include/hpx/components_base/server/wrapper_heap_list.hpp, libs/full/components_base/src/server/component_base.cpp, libs/full/components_base/src/server/wrapper_heap.cpp, libs/full/naming_base/include/hpx/naming_base/gid_type.hpp, libs/full/naming_base/src/gid_type.cpp
This will reduce contention while resolving global ids.
=> Assign global ids to managed component instances that are locally resolvable

libs/core/command_line_handling_local/include/hpx/command_line_handling_local/late_command_line_handling_local.hpp, libs/core/command_line_handling_local/src/late_command_line_handling_local.cpp, libs/core/runtime_local/include/hpx/runtime_local/runtime_local.hpp, libs/core/runtime_local/src/runtime_local.cpp
@weilewei this should fix the issue you were seeing (`--hpx:print-bind` being invoked twice)
=> Avoid performing late command line handling twice in distributed runtime

libs/core/lci_base/include/hpx/lci_base/lci_environment.hpp, libs/core/lci_base/src/lci_environment.cpp, libs/full/parcelport_lci/src/parcelport_lci.cpp
The `LCI_progress` function is not thread-safe and must be called frequently. Previously, we created a dedicated progress thread using pthread when initializing LCI. However, HPX doesn't know this progress thread and thus cannot bind threads to cores correctly.
This PR uses the new resource partitioner hook in the parcelport to create a thread pool "lci-progress-pool" (which only contains one core) to run LCI_progress.
Fixed:
- The thread pool will be allocated even if users are not using LCI parcelport.
=> Create a dedicated thread pool to run LCI_progress.

libs/full/parcelset/src/parcelhandler.cpp
The mutex lock is very expensive as the program needs to acquire it whenever a parcel is sent.
It appears the original mutex lock is used to protect the handler invocation from hpx::set_parcel_write_handler, but I think the code would be ill-formed anyway if the user wants to set the handler when there are parcels on the fly.
=> Remove the mutex lock in parcelhandler::invoke_write_handler

docs/sphinx/manual/building_tests_examples.rst
Docs provide an example of how to run single/specific tests. The given test name pattern does not seem to be accurate. 
-   This PR attempts to fix the test name pattern.
The correct test name pattern can be found using `ctest -N`
=> [Docs] Fix example of how to run single/specific test(s)

tests/performance/local/timed_task_spawn.cpp
**Context**: 
- `boost::integer::gcd` was being used [here](https://github.com/STEllAR-GROUP/hpx/blob/8927e02a0a8d1c4b7bfae150dbd0f1baa9731efc/tests/performance/local/timed_task_spawn.cpp#L415) to calculate gcd
- [#3440](https://github.com/STEllAR-GROUP/hpx/issues/3440) states we are trying to remove dependence on boost libraries
- [#5497](https://github.com/STEllAR-GROUP/hpx/issues/5497) states we can use C++17 features unconditionally
- `std::gcd` is available from C++17 onwards: https://en.cppreference.com/w/cpp/numeric/gcd
**Proposed change**: Replace `boost::integer::gcd` with `std::gcd`
**Expected Outcome**: HPX is no longer dependent on `boost::integer`
=> Replace boost::integer::gcd with std::gcd

libs/full/parcelport_lci/include/hpx/parcelport_lci/sender.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/sender_connection.hpp, libs/full/parcelport_lci/src/parcelport_lci.cpp, libs/full/parcelport_libfabric/include/hpx/parcelport_libfabric/connection_handler.hpp, libs/full/parcelport_mpi/src/parcelport_mpi.cpp, libs/full/parcelport_tcp/include/hpx/parcelport_tcp/connection_handler.hpp, libs/full/parcelset/include/hpx/parcelset/parcelport_impl.hpp, libs/full/plugin_factories/include/hpx/plugin_factories/parcelport_factory.hpp
Originally, when hpx tries to send a parcel, it will (1) push the parcel into a parcel queue corresponding to its destination (2) try to get a "connection" of the destination from the connection cache (3) dequeue multiple parcels from the parcel queue (4) encode the parcels into a message and pass it to the parcelport layer. This process contains multiple attempts of acquiring mutex locks.
This PR optimizes the LCI parcelport so that it could bypass the parcel queue and connection cache. The parcelport layer offers a "send" function. Whenever the upper layer wants to send a parcel, it can directly invoke this function.
This PR shares the same idea as the "send_immediate" feature of the libfabric parcelport (#2379).
=> LCI parcelport: bypass the parcel queue and connection cache.

.github/workflows/linux_crosscompile_arm_eve_sve_release.yml, .jenkins/lsu/env-gcc-12.sh, cmake/HPX_SetupDatapar.cmake
Use latest eve release tag `v2023.02.15`, which supports SVE.
Update lsu gcc-12 CI to test EVE datapar backend with master branch.
Add new GitHub action to test SVE vectorization with EVE.
=> Update CI integration for EVE

libs/core/lci_base/include/hpx/lci_base/lci_environment.hpp, libs/core/lci_base/src/lci_environment.cpp, libs/full/parcelport_lci/CMakeLists.txt, libs/full/parcelport_lci/include/hpx/parcelport_lci/backlog_queue.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/parcelport_lci.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/receiver.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/sender.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/sender_connection.hpp, libs/full/parcelport_lci/src/backlog_queue.cpp, libs/full/parcelport_lci/src/parcelport_lci.cpp, libs/full/parcelport_lci/src/sender.cpp, libs/full/parcelport_lci/src/sender_connection.cpp, libs/full/parcelport_mpi/src/parcelport_mpi.cpp, libs/full/plugin_factories/include/hpx/plugin_factories/parcelport_factory.hpp, libs/full/runtime_distributed/tests/unit/thread_mapper_parcel_pools.cpp
More optimizations for LCI parcelport.
- Add a TLS message backlog queue for unsucceeded sends and eager message aggregation. Use option hpx.parcel.lci.backlog_queue to control (default is 0).
- Let users be able to control progress thread pinning. Use option hpx.parcel.lci.prg_thread_core to control. Only valid if hpx.parcel.lci.rp_prg_pool=0
- Use LCI_mbuffer_alloc for eager message
- Use separate devices/progress threads for eager/iovec messages. Use option hpx.parcel.lci.use_two_device to control (default is 0).
- Change the default value of hpx.parcel.lci.sendimm to 1, a.k.a bypass parcel queues and connection caches by default.
=> LCI parcelport: backlog queue, aggregation, separate devices, and more

libs/core/thread_support/CMakeLists.txt
Fix typo in libs/core/thread_support/CMakeLists.txt which was causing a build failure.
=> thread_support/CMakeLists: Fix build issue

cmake/HPX_SetupDatapar.cmake
Fixes issue #6164  by using ``hpx_error`` if  ``HPX_WITH_DATAPAR_BACKEND=EVE`` is used with ``HPX_WITH_CXX_STANDARD`` less than 20.
=> Fix EVE datapar with cxx_standard less than 20

CMakeLists.txt
LCI v1.7.3 provides more ways of performance profiling and tuning. It also has some performance improvement.
[v1.7.3 change log](https://github.com/uiuc-hpc/LC/blob/dev-v1.7/doc/changelog_1_7_3.md)
=> Change the default tag of autofetch LCI to v1.7.3.

libs/core/executors/include/hpx/executors/restricted_thread_pool_executor.hpp, libs/core/executors/tests/regressions/CMakeLists.txt, libs/core/executors/tests/regressions/pu_count_6184.cpp, libs/core/itt_notify/include/hpx/modules/itt_notify.hpp
=> Making sure restricted_thread_pool_executor properly reports used number of cores

libs/full/parcelport_mpi/include/hpx/parcelport_mpi/header.hpp
Without this change, it will give me (with HPX_WITH_COMPILER_WARNINGS_AS_ERRORS=ON)
/XXX/hpx/libs/full/parcelport_mpi/include/hpx/parcelport_mpi/header.hpp: In member function ‘bool hpx::parcelset::policies::mpi::header::valid() const’: /XXX/hpx/libs/full/parcelport_mpi/include/hpx/parcelport_mpi/header.hpp:85:29: error: comparison is always true due to limited range of data type [-Werror=type-limits]
85 |             return data_[0] != -1;
=> Fix the compilation warning in the MPI parcelport with gcc 11.2

CMakeLists.txt
=> Automatically enable Boost.Context when compiling for arm64.

docs/sphinx/manual/using_the_lci_parcelport.rst
Update the document.
The new version of LCI can automatically detect the libfabric/cxi provider, so no need to manually set `LCI_OFI_PROVIDER_HINT_DEFAULT`.
=> Update the LCI parcelport documents

libs/core/thread_pools/include/hpx/thread_pools/detail/background_thread.hpp, libs/core/thread_pools/include/hpx/thread_pools/scheduling_loop.hpp, libs/core/thread_pools/src/detail/background_thread.cpp
- flyby: slight cleanup of scheduler loop
=> Prevent thread stealing during scheduler shutdown

CMakeLists.txt
Added cmake Option HPX_PARALLEL_LINK_JOBS to limit number of parallel link jobs if using ninja as generator.
Usage: 
-DHPX_PARALLEL_LINK_JOBS=2
defaults to 2 if not set (and generator is ninja)
How do I test if it works?
Referenced and motivated from https://github.com/llvm/llvm-project/blob/main/llvm/cmake/modules/HandleLLVMOptions.cmake#L46
=> Par link jobs

libs/full/segmented_algorithms/tests/unit/partitioned_vector_adjacent_find1.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_adjacent_find2.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_all_of1.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_all_of2.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_any_of1.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_any_of2.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_max_element1.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_max_element2.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_min_element1.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_min_element2.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_minmax_element1.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_minmax_element2.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_none1.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_none2.cpp
Fixes a group of tests for HPX segmented algorithms, which were occasionally failing due to improper initialization of partitioned_vector. Initialization using partitioned_vector::set_value() is asynchronous and returns a future, but we never waited for it to complete.
=> Fix segmented algorithms tests

libs/core/algorithms/include/hpx/parallel/algorithms/detail/set_operation.hpp, libs/core/algorithms/tests/regressions/set_operations_3442.cpp
Fixes #6198 
Error : when number of chunks < number of cores => error occurred as chunk by default length of chunk was -1 (changed to 1)
added randomised tests which assume std::set_difference is implemented correctly
=> added tests for set_difference, updated set_operation.hpp to fix #6198

libs/core/algorithms/include/hpx/parallel/util/detail/chunk_size.hpp, libs/core/algorithms/include/hpx/parallel/util/detail/chunk_size_iterator.hpp, libs/core/algorithms/tests/unit/algorithms/foreach_sender.cpp
@Pansysk75 this should fix the issue we discussed. Please verify.
=> Fixing algorithms for zero length sequences when run with s/r scheduler

libs/core/algorithms/include/hpx/parallel/algorithms/make_heap.hpp, libs/core/algorithms/tests/unit/algorithms/make_heap.cpp
Fixes #6217
added tests, fixed bug. We try to find last element index of parent level (end_exclusive). If child is element of index 1, last element of parent level becomes -1 and there is negative overflow.
fixed it by enforcing end_exclusive to be >=0
=> Make heap fails in par for small sized heaps #6217

libs/core/algorithms/CMakeLists.txt, libs/core/algorithms/include/hpx/algorithms/traits/is_relocatable.hpp, libs/core/algorithms/include/hpx/algorithms/traits/pointer_category.hpp, libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt, libs/core/algorithms/tests/unit/algorithms/util/test_is_relocatable.cpp
This is a draft pr to implement the basic traits for P1144 (relocatable).
I defined a meta function (`is_relocatable`) and `pointer_relocate_category` allongside the existing `pointer_copy_category` and `pointer_move_category`. 
A type is `relocatable` if it is not tied to a specific location in memory.  (An example object that is not relocatable is std::mutex)
The aim of this branch is to implement the trivially relocatable trait and the faster data transfer algorithms it allows us to use.
To move forward I ask if this is the right file to the `is_relocatable` definitions.
I believe the `trivially_copyable_pointer` part of this file focuses on if an iterator is suitable for a contiguous `memcpy`, and not in determining if the underlying object is `trivially_copyable`; it uses …
=> Initial trait definition for `relocatable`

libs/core/algorithms/include/hpx/algorithms/traits/is_relocatable.hpp
Fixes compilation problems on master
=> Moving is_relocatable to namespace hpx

libs/core/algorithms/include/hpx/parallel/util/loop.hpp
Using HPX 1.9.0, the Octo-Tiger compilation (using just CUDA, not Kokkos) with gcc+nvcc fails due to an internal nvcc error pointing to loop.hpp within HPX:
```
build/hpx/include/hpx/parallel/util/loop.hpp(216): internal error: assertion failed at: "cp_gen_be.c", line 22617 in gen_variable_decl                                                                                                                 
1 catastrophic error detected in the compilation of "/src/octotiger/src/unitiger/hydro_impl/flux_cuda_kernel.cpp".                                                                                                                                      
Compilation aborted.
nvcc error   : 'cudafe++' died due to signal 6
nvcc error   : 'cudafe++' core dumped
```
That is with using g++10 and …
=> Fix nvcc/gcc-10 (Octo-Tiger) compilation issue 

docs/sphinx/manual/optimizing_hpx_applications.rst, docs/sphinx/manual/using_the_lci_parcelport.rst
The content of the tables used to overlap with the side bar of the documentation making it impossible to actually read the information. These extended tables were split to smaller tables which are now clear and readable. 
With this change there is no need to include anchors to the table rows. For each counter there is a separate table, so one can just use the reference to the table in order to refer to a specific counter.
=> Fix `Optimizing HPX applications` page of Manual

libs/core/async_combinators/CMakeLists.txt, libs/core/async_combinators/include/hpx/async_combinators/wait_some.hpp
- flyby: fixing possible race in latch
@m-diers Could you please try this patch to see if it fixes your issue?
=> Rewriting wait_some to circumvent data races causing hangs

libs/full/parcelport_lci/include/hpx/parcelport_lci/parcelport_lci.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/sender.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/sender_connection.hpp, libs/full/parcelport_mpi/src/parcelport_mpi.cpp, libs/full/plugin_factories/include/hpx/plugin_factories/parcelport_factory.hpp
Users can use the option `hpx.parcel.mpi.sendimm` to enable and disable it.
When HPX wants to send a parcel, the default behavior is to enqueue this parcel into the parcel queue of the target locality, dequeue all the parcels from that parcel queue, aggregate them, and pass them in one `parcel_buffer` structure. It will also try to get an existing connection from the connection cache. These two data structures are protected by locks and can be a source of thread contention.
With the send immediate optimization, the parcelport will bypass the connection cache and parcel queues and directly send the parcel.
This option is mainly for research purposes. The default is off since it will slow down the MPI parcelport in most cases.
=> Implement the send immediate optimization for the MPI parcelport.

libs/core/errors/include/hpx/errors/error.hpp, libs/core/errors/src/error_code.cpp
In one of the recent HPX versions, the previously publicly available string representations of the HPX error code were removed from the public API. This PR introduces an API that allows to query the error names.
=> Re-expose error names

CMakeLists.txt, cmake/toolchains/Cray.cmake, cmake/toolchains/CrayKNL.cmake, cmake/toolchains/CrayKNLStatic.cmake, cmake/toolchains/CrayStatic.cmake, libs/core/mpi_base/include/hpx/mpi_base/mpi_environment.hpp, libs/core/mpi_base/src/mpi_environment.cpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/header.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/header.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/receiver.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/receiver_connection.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/sender.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/sender_connection.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/tag_provider.hpp
Improve the MPI parcelport:
- Replace the lock-based tag provider with an atomic variable
- Make the header message size dynamic
Since the maximum size of the dynamic header message is set to be the zero-copy serialization threshold, I also changed it from 128B to 8192B. (The message size that MPI switches from eager protocol to rendezvous protocol is usually around 8K - 64K).
Experiments: Octo-Tiger, max_level=6, SDSC Expanse, 32 nodes, 128 threads per node.
With `hpx.parcel.mpi.sendimm=0`, this PR improves the total execution time from 11.77s to 10.68s.
With `hpx.parcel.mpi.sendimm=1`, this PR improves the total execution time from ~60s to 11.72s.
=> Improve the MPI parcelport and change the zero-copy threshold to 8192

CMakeLists.txt, docs/sphinx/manual/using_the_lci_parcelport.rst
LCI v1.7.5 improves its flexibility and usability. It also fixes various minor compilation warnings and errors.
=> update(lci pp): update the default version of LCI autofetch to v1.7.5

cmake/templates/hpxcxx.in
The hpxcxx script was broken such that it could only compile for _release. This modification makes it more robust in finding a compiled hpx installation and changes the 2 character flags to use -- instead of -.
Fixes #
- Changes 2 character flags so that they use -- instead of -
- Fixes bug which prevents non-release versions from working
- Makes specifying the release optional
-  corrects relwithdebinfo to relwithdebuginfo
=> The hpxcxx script was broken such that it could only compile for _release

libs/core/config/include/hpx/config/compiler_specific.hpp
This resolves a compilation issue where timestamp_cuda is required in device code for a certain build configuration (using ONEAPI/SYCL/dpcpp with an enabled CUDA backend and specific GPU architecture) but not found. The underlying issue: The include command for the timestamp_cuda header is protected with an ifdef HPX_COMPUTE_CODE and the header was thus not included  - hence the timestamp method was not found, and the code did not compile in this configuration!
This commit resolves the issue! Not by changing or removing the ifdef timestamp guard, but instead by defining HPX_COMPUTE_CODE for SYCL builds in the compiler_specific.hpp header as well. This ensures that the behavior for non-SYCL builds stays the same as before.
=> Define HPX_COMPUTE_CODE in builds with SYCL

libs/core/synchronization/include/hpx/synchronization/counting_semaphore.hpp, libs/core/synchronization/include/hpx/synchronization/detail/counting_semaphore.hpp, libs/core/synchronization/include/hpx/synchronization/detail/sliding_semaphore.hpp, libs/core/synchronization/include/hpx/synchronization/sliding_semaphore.hpp
Use intrusive_ptr to implement internal reference counting for semaphores.
=> Add internal reference counting to semaphores

libs/core/algorithms/include/hpx/parallel/util/partitioner.hpp, libs/core/compute_local/include/hpx/compute_local/host/block_fork_join_executor.hpp, libs/core/compute_local/tests/unit/block_fork_join_executor.cpp, libs/core/execution/include/hpx/execution/executors/execution.hpp, libs/core/execution_base/include/hpx/execution_base/execution.hpp, libs/core/executors/include/hpx/executors/fork_join_executor.hpp, libs/core/executors/tests/unit/fork_join_executor.cpp, libs/core/functional/CMakeLists.txt, libs/core/functional/include/hpx/functional/detail/runtime_get.hpp
This adds new CPOs: `sync_invoke` and `async_invoke`. It also adds an implementation for the `fork_join_executor` and `block_fork_join_executor` as well as fallback implementations for all executors not supporting these. The APIs are:
```
namespace hpx::parallel::execution {
template <typename Executor, typename F, typename... Fs,
HPX_CONCEPT_REQUIRES_(
std::is_invocable_v<F> && (std::is_invocable_v<Fs> && ...)
)>
void sync_invoke(Executor&& exec, F&& f, Fs&&... fs);
template <typename Executor, typename F, typename... Fs,
HPX_CONCEPT_REQUIRES_(
std::is_invocable_v<F> && (std::is_invocable_v<Fs> && ...)
)>
decltype(auto) async_invoke(Executor&& exec, F&& f, Fs&&... fs);
}
```
For executors supporting the CPOs this will concurrently launch the given functions and will either wait for them …
=> Adding executor parallel invoke CPOs

libs/core/runtime_local/src/runtime_local.cpp, libs/full/init_runtime/src/hpx_init.cpp, libs/full/runtime_distributed/src/runtime_distributed.cpp, tests/regressions/threads/CMakeLists.txt, tests/regressions/threads/main_thread_exit_callbacks.cpp
Ensure that hpx_main is launched as a thread_function, so that exit callbacks are respected, and the following code will actually be used:
https://github.com/STEllAR-GROUP/hpx/blob/e7c31a49dd4e550a61134e498f3ecfb585d201cb/libs/core/threading_base/include/hpx/threading_base/register_thread.hpp#L28-L52
I should add that previously the callbacks were never executed, so using add_thread_exit_callback would cause an assertion failure later on thread destruction (L163), due to this sequence of calls:
https://github.com/STEllAR-GROUP/hpx/blob/e7c31a49dd4e550a61134e498f3ecfb585d201cb/libs/core/threading_base/src/thread_data.cpp#L107-L111
https://github.com/STEllAR-GROUP/hpx/blob/e7c31a49dd4e550a61134e498f3ecfb585d201cb/libs/core/threading_base/src/thread_data.cpp#L157-L166
@hkaiser Let me know if …
=> Ensure hpx_main is a proper thread_function

libs/core/futures/tests/regressions/shared_future_continuation_order.cpp
Fixes occasional failure of shared_future_continuation_order regression test.
If my understanding is correct, continuations are executed on newly spawned threads by default, which would not guarantee their order of execution. Launching with hpx::launch::sync should guarantee that no new thread is spawned, thus they are executed in sequence.
(@hkaiser We had fixed this in some PR in the past, but it seems it didn't make it into master)
=> Fix shared_future_continuation_order regression test

libs/core/runtime_local/src/runtime_local.cpp
Adds logging when an HPX program is terminated suddenly (ie by a termination signal, addresses issue #6329).
I'll leave it as draft until I make up my mind on whether I think it is actually a good idea
=> Log alive hpx threads on exit

.jenkins/lsu-test-coverage/Jenkinsfile, .jenkins/lsu-test-coverage/batch.sh, .jenkins/lsu-test-coverage/entry.sh, .jenkins/lsu-test-coverage/env-test-coverage.sh, .jenkins/lsu-test-coverage/slurm-constraint-test-coverage.sh, README.rst
Runs coverage tests on Jenkins, and uploads results to Codacy.
Relies on fetching `grcov` utility.
=> Add coverage testing on Jenkins

components/process/src/server/child_component.cpp, examples/quickstart/init_globally.cpp, libs/core/runtime_local/include/hpx/runtime_local/run_as_hpx_thread.hpp, libs/core/runtime_local/include/hpx/runtime_local/run_as_os_thread.hpp, libs/full/collectives/src/barrier.cpp, tests/regressions/threads/run_as_hpx_thread_exceptions_3304.cpp, tests/regressions/threads/run_as_os_thread_lockup_2991.cpp
- run_as_os_thread
- run_as_hpx_thread
=> Moving hpx::threads::run_as_xxx to namespace hpx

libs/core/concurrency/include/hpx/concurrency/detail/tagged_ptr_pair.hpp, libs/core/concurrency/include/hpx/concurrency/detail/tagged_ptr_ptrcompression.hpp, libs/full/async_colocated/src/server/destroy_component.cpp
=> Fixing compilation problems on 32 Linux systems

libs/core/algorithms/tests/unit/algorithms/uninitialized_relocate_par.cpp
In the original test there where two errors:
1. An atomic variable was fetched in a way that introduced race conditions, skipping the `throw` portion of the code.
2. The testing was more strict than necessary, making guesses about the inner workings of `partitioner_with_cleanup`. Testing that every created object is destroyed in case of an exception is enough to abide by P1144.
=> Fix parallel relocation test

.jenkins/lsu/Jenkinsfile, .jenkins/lsu/env-clang-15.sh, .jenkins/lsu/env-clang-16.sh, .jenkins/lsu/env-clang-17.sh, .jenkins/lsu/env-gcc-12-cuda-12.sh, .jenkins/lsu/env-gcc-12.sh, .jenkins/lsu/env-gcc-13-cuda-12-dgx.sh
Adding new libraries to LSU Jenkins:
- gcc/13.2 with boost 1.83
- llvm/17 with boost 1.83
- llvm/16 with boost 1.82
- gcc/13 + cuda 12 with boost 1.83
- gcc/12 + cuda 12 with boost 1.82
=> Update LSU Jenkins with 2023-10 libraries

examples/jacobi_smp/jacobi.cpp, examples/jacobi_smp/jacobi_nonuniform.cpp
Makes sure the `HPX_APPLICATION_STRING` is set correctly for non-hpx targets in Jacobi examples when `HPX_WITH_EXAMPLES_OPENMP=ON`.
- We may want to have a testing pipeline for non-hpx examples.
- Thank you @G-071!
=> Fix jacobi omp examples.

examples/1d_stencil/1d_stencil_6.cpp, examples/1d_stencil/1d_stencil_7.cpp, examples/1d_stencil/1d_stencil_8.cpp, examples/quickstart/zerocopy_rdma.cpp, libs/core/serialization/include/hpx/serialization/serialize_buffer.hpp, libs/full/checkpoint/examples/1d_stencil_4_checkpoint.cpp
=> Making sure serialize_buffer properly destroys buffer, if needed.

libs/core/resource_partitioner/tests/unit/named_pool_executor.cpp, libs/core/resource_partitioner/tests/unit/resource_partitioner_info.cpp, libs/core/resource_partitioner/tests/unit/shutdown_suspended_pus.cpp, libs/core/resource_partitioner/tests/unit/suspend_pool.cpp, libs/core/resource_partitioner/tests/unit/suspend_thread.cpp, libs/core/resource_partitioner/tests/unit/suspend_thread_external.cpp
Fixes certain resource partitioner tests which would fail when --hpx:threads was set to a number <4.
Should fix current failures on MacOS CI
=> Fix resource partitioner tests for small thread count

cmake/templates/hpxcxx.in
Fixes issue with hpxcxx. The program does not break out of the outer loop after it finds a matching suffix like it should.
=> Need to break out of the loop when searching the suffixes.

libs/core/algorithms/tests/performance/foreach_scaling_helpers.hpp, libs/core/async_mpi/include/hpx/async_mpi/mpi_executor.hpp, libs/core/compute_local/include/hpx/compute_local/host/block_allocator.hpp, libs/core/compute_local/include/hpx/compute_local/host/block_executor.hpp, libs/core/compute_local/include/hpx/compute_local/host/numa_allocator.hpp, libs/core/execution/CMakeLists.txt, libs/core/execution/include/hpx/execution/executors/adaptive_static_chunk_size.hpp, libs/core/execution/include/hpx/execution/executors/auto_chunk_size.hpp, libs/core/execution/include/hpx/execution/executors/default_parameters.hpp, libs/core/execution/include/hpx/execution/executors/dynamic_chunk_size.hpp, libs/core/execution/include/hpx/execution/executors/execution_parameters.hpp, libs/core/execution/include/hpx/execution/executors/execution_parameters_fwd.hpp, libs/core/execution/include/hpx/execution/executors/guided_chunk_size.hpp, libs/core/execution/include/hpx/execution/executors/num_cores.hpp, libs/core/execution/include/hpx/execution/executors/persistent_auto_chunk_size.hpp, libs/core/execution/include/hpx/execution/traits/executor_traits.hpp, libs/core/execution/tests/unit/executor_parameters.cpp, libs/core/execution/tests/unit/executor_parameters_dispatching.cpp, libs/core/execution/tests/unit/executor_parameters_timer_hooks.cpp, libs/core/executors/include/hpx/executors/execution_policy_parameters.hpp, libs/core/executors/include/hpx/executors/explicit_scheduler_executor.hpp, libs/core/executors/include/hpx/executors/fork_join_executor.hpp, libs/core/executors/include/hpx/executors/parallel_executor.hpp, libs/core/executors/include/hpx/executors/scheduler_executor.hpp, libs/core/tag_invoke/include/hpx/functional/detail/tag_priority_invoke.hpp, libs/full/include/include/hpx/include/parallel_executor_parameters.hpp, tests/performance/local/future_overhead.cpp
This introduces a breaking change as it changes the preferences for which of the parametrizations for execution policies takes a preference. With this change parameter values introduced through execution parameter objects take always precedence. 
This change also enforces using `tag_invoke` for exposing parameter values from executors and `tag_override_invoke` for exposing those from execution parameter objects.
=> Consistently treat conflicting parameters provided by executors and parameter objects

libs/core/algorithms/include/hpx/parallel/algorithms/for_each.hpp, libs/core/algorithms/include/hpx/parallel/algorithms/rotate.hpp, libs/core/algorithms/include/hpx/parallel/util/adapt_placement_mode.hpp, libs/core/algorithms/include/hpx/parallel/util/adapt_sharing_mode.hpp, libs/core/algorithms/include/hpx/parallel/util/adapt_thread_priority.hpp, libs/core/futures/include/hpx/futures/packaged_continuation.hpp, libs/core/lcos_local/tests/unit/local_dataflow_external_future.cpp, libs/core/serialization/include/hpx/serialization/array.hpp, libs/core/serialization/include/hpx/serialization/detail/serialize_collection.hpp, libs/core/serialization/include/hpx/serialization/map.hpp, libs/core/serialization/include/hpx/serialization/vector.hpp
- this helps working around recent MSVC problems
=> Making function local constexpr variables non-static

libs/core/executors/include/hpx/executors/fork_join_executor.hpp, libs/core/executors/tests/regressions/CMakeLists.txt, libs/core/executors/tests/regressions/fork_join_with_result.cpp, libs/core/executors/tests/unit/fork_join_executor.cpp
@gonidelis this should resolve your issue with using `fork_join_executor` with the `transform_reduce` algorithm.
=> Enable fork_join_executor to handle return values from scheduled functions

libs/core/batch_environments/include/hpx/batch_environments/batch_environment.hpp, libs/core/batch_environments/src/batch_environment.cpp, libs/full/command_line_handling/src/command_line_handling.cpp
Fixes #6388
@JiakunYan would you be able to check whether this resolves the issue you reported?
=> Disable resolving hostnames if TCP is disabled

libs/core/algorithms/include/hpx/parallel/util/adapt_thread_priority.hpp, libs/core/lock_registration/include/hpx/lock_registration/detail/register_locks.hpp, libs/core/synchronization/include/hpx/synchronization/condition_variable.hpp, libs/core/synchronization/include/hpx/synchronization/detail/condition_variable.hpp, libs/core/synchronization/include/hpx/synchronization/shared_mutex.hpp, libs/core/synchronization/src/detail/condition_variable.cpp, libs/core/synchronization/tests/unit/shared_mutex/shared_mutex1.cpp, libs/core/synchronization/tests/unit/shared_mutex/shared_mutex2.cpp, libs/core/synchronization/tests/unit/shared_mutex/shared_mutex_locking_thread.hpp, libs/core/synchronization/tests/unit/shared_mutex/thread_group.hpp, libs/full/components_base/include/hpx/components_base/server/one_size_heap_list.hpp, libs/full/components_base/include/hpx/components_base/server/wrapper_heap.hpp, libs/full/components_base/include/hpx/components_base/server/wrapper_heap_list.hpp, libs/full/components_base/src/server/one_size_heap_list.cpp, libs/full/components_base/src/server/wrapper_heap.cpp
The original implementation uses an HPX mutex to ensure thread safety. This PR replaces it with a pthread rwlock, which greatly improves its performance. Multiple allocation/free calls can proceed simultaneously under the read lock, and the pthread read lock only costs an atomic fetch-and-add in most cases.
Need to discuss: directly using pthread rwlock in HPX codebase may not be a good idea, but implementing the whole pthread rwlock algorithm in HPX can also be cumbersome.
=> improve one_size_heap_list: use rwlock to speedup the allocation/free

libs/full/parcelport_lci/src/parcelport_lci.cpp
Fixes #6398.
The HPX runtime relies on `used_cores_map_` to set the affinity correctly when running multiple localities per node (see `runtime_distributed::assign_cores` for details). `used_cores_map_` maps hostnames to "used cores" and assumes the hostname of all localities on the same node are the same. The hostname is generated using the `parcelport::get_locality_name` method (I would say the name of this method is misleading).
The previous LCI parcelport used "processor_name+rank" as a locality name, which breaks the assumption of `used_cores_map_`. This PR fixed this issue.
=> Fx the affinity setting bug when using LCI pp and multiple localities per node

libs/core/serialization/include/hpx/serialization/traits/is_bitwise_serializable.hpp, libs/full/actions_base/src/detail/action_factory.cpp
This should have been in place from day 1,
=> Making is_bitwise_serializable SFINAE-friendly

libs/full/parcelport_lci/src/sender_connection_base.cpp
In the previous LCI parcelport, too many failed sends will trigger `background_work` and `yield` as a way of back pressure propagation. These calls might cause the current thread to be de-scheduled. However, I found those rescheduled threads may never be scheduled again after yielding, leading to deadlocks. Not sure whether this is a bug of the scheduler or not.
This PR temporarily disabled the invocation of the `background_work` and `yield` functions and fixed the deadlock issue.
This PR overwrites the changes in #6401.
=> fix(lci pp): fix deadlocks with too many failed sends

.github/workflows/windows_release_gcc_mingw.yml, CMakeLists.txt, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/cxx20_no_unique_address_attribute.cpp, libs/core/lcos_local/include/hpx/lcos_local/and_gate.hpp
The CMake configuration variable `HPX_WITH_SUPPORT_NO_UNIQUE_ADDRESS` can be used to disable the `[[no_unique_address]]` attribute in cases when HPX is compiled using MSVC but the code using it is compiled using clang-cl (which doesn't support this attribute on Windows before V18).
`HPX_WITH_SUPPORT_NO_UNIQUE_ADDRESS` defaults to `ON`.
=> Allow to disable use of [[no_unique_address]] attribute

libs/core/program_options/src/value_semantic.cpp
=> Working around ROCm compiler issue

libs/core/properties/include/hpx/properties/property.hpp
=> Working around CUDA issue

libs/core/runtime_local/include/hpx/runtime_local/run_as_os_thread.hpp
Moving ```run_as_os_thread``` from the namespace ```hpx::threads``` to the namespace ```hpx``` caused some compilations with the AMD hipcc comiler (rocm 5.7.3) :
```
>> 1320    /work/gdaiss/spack_workshop/spack_new/opt/spack/linux-rhel8-zen2/rocmcc-5.7.3/hpx-master-redf563a75azthtk2hmqogvlynvmf5zt/include/hpx/runtime_local/run_as_os_thread.hpp:43:38: error: no matching function for call to 'forward'
1321            return hpx::run_as_os_thread(HPX_FORWARD(F, f), HPX_FORWARD(Ts, ts)...);
1322                                         ^~~~~~~~~~~~~~~~~
1323    /work/gdaiss/spack_workshop/spack_new/opt/spack/linux-rhel8-zen2/rocmcc-5.7.3/hpx-masterredf563a75azthtk2hmqogvlynvmf5zt/include/hpx/config/forward.hpp:14:29: note: expanded from macro 'HPX_FORWARD'
1324    #define HPX_FORWARD(T, ...) …
```
=> Change run_as_os_thread deprecation forwarding due to hipcc compilation issue

libs/full/parcelport_lci/include/hpx/parcelport_lci/config.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/header.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/parcelport_lci.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/sendrecv/sender_connection_sendrecv.hpp, libs/full/parcelport_lci/src/config.cpp, libs/full/parcelport_lci/src/parcelport_lci.cpp, libs/full/parcelport_lci/src/sender_connection_base.cpp, libs/full/parcelport_lci/src/sendrecv/sender_connection_sendrecv.cpp, tests/performance/network/pingpong_performance2.cpp
For the LCI parcelport:
- Add an option to enable/disable in-buffer assembly of header messages
- Fix the lci_progress_poll in cases where there are multiple pus per core.
- Minor changes to the log output.
For the pingpong_performance2 benchmark
- Add warmup
=> Minor refactoring and fixes to the LCI parcelport and pingpong_performance2 benchmark

libs/core/futures/include/hpx/futures/future_or_value.hpp, libs/core/type_support/include/hpx/type_support/extra_data.hpp, libs/full/agas/src/detail/interface.cpp, libs/full/async_colocated/src/get_colocation_id.cpp, libs/full/async_distributed/include/hpx/async_distributed/put_parcel.hpp, libs/full/components/include/hpx/components/client_base.hpp, libs/full/components/include/hpx/components/get_ptr.hpp, libs/full/components/src/client_base.cpp, libs/full/components_base/src/agas_interface.cpp
Fixes #6414
@G-071 could you please verify whether this fixes the segfault you reported?
=> Attempting to avoid segfault in OctoTiger during initialization

.github/workflows/linux_debug_fetch_hwloc.yml, .github/workflows/macos_debug_fetch_hwloc.yml, .github/workflows/windows_debug_vs2022_fetch_hwloc.yml, CMakeLists.txt, cmake/HPX_SetupHwloc.cmake
References #6392 
- Added `HPX_WITH_FETCH_HWLOC` option for fetching Hwloc using CMake FetchContent
- Added CI tests for the same, on Linux, macOS and Windows platforms
=> Adding option for installing Hwloc using CMake FetchContent

libs/core/async_mpi/CMakeLists.txt
=> Making sure HPX_WITH_ASYNC_MPI is reported properly

libs/full/agas/include/hpx/agas/addressing_service.hpp, libs/full/agas/src/addressing_service.cpp
`resolve_locality` is on the critical path of parcel sending. Originally, it used `hpx:spinlock` to protect its `unordered_map::find`. This turns out to be too expensive. This PR replaces the `spinlock` with `hpx::shared_mutex` and greatly improves the maximum parcel sending throughput.
=> Use shared mutex for resolve_locality procedure.

libs/full/runtime_distributed/include/hpx/runtime_distributed/server/runtime_support.hpp, libs/full/runtime_distributed/src/server/runtime_support_server.cpp
`dijkstra_make_black` is on the critical path of parcel sending. Taking a unique lock once per parcel sending is too expensive. This PR mitigates this overhead.
=> improve termination detection: removing lock from criticial path

.github/workflows/windows_debug_vs2022_fetch_hwloc.yml, CMakeLists.txt, cmake/HPX_SetupHwloc.cmake
References #6394 , #6392 
- Added the HwlocDLL custom target (defined in #6394), used for copying `libhwloc-15.dll` to the binary folder, directly as a psuedo-target
- Hence, the above copy operation is now independent of the `examples` psuedo-target 
https://github.com/STEllAR-GROUP/hpx/pull/6394#discussion_r1466557733
=> Modifying CMakeLists to copy libhwloc-15.dll to the binary folder in Windows, independently

libs/full/agas/include/hpx/agas/addressing_service.hpp, libs/full/agas/src/addressing_service.cpp, libs/full/agas/src/route.cpp, libs/full/async_distributed/include/hpx/async_distributed/put_parcel.hpp, libs/full/async_distributed/include/hpx/async_distributed/put_parcel_fwd.hpp, libs/full/naming_base/include/hpx/naming_base/gid_type.hpp, libs/full/naming_base/include/hpx/naming_base/id_type.hpp
@JiakunYan these are some tweaks to the parcel layer as discussed. Please verify.
=> Parcel layer tweaks

libs/full/agas/src/addressing_service.cpp
Fixes #6443
The `get_entry` method of `lru_cache` is not read-only. There is a `touch` method being invoked inside it.
=> Fix agas addressing cache

.jenkins/lsu/env-gcc-11.sh, cmake/HPX_AddConfigTest.cmake, cmake/tests/cxx11_std_atomic.cpp, cmake/tests/cxx11_std_atomic_128bit.cpp, libs/core/concurrency/include/hpx/concurrency/detail/freelist_stack.hpp, libs/core/config/include/hpx/config/compiler_specific.hpp, libs/core/resource_partitioner/tests/unit/cross_pool_injection.cpp, libs/core/resource_partitioner/tests/unit/shutdown_suspended_pus.cpp, libs/core/resource_partitioner/tests/unit/suspend_pool.cpp, libs/core/resource_partitioner/tests/unit/suspend_pool_external.cpp, libs/core/resource_partitioner/tests/unit/suspend_runtime.cpp, libs/core/resource_partitioner/tests/unit/suspend_thread.cpp, libs/core/resource_partitioner/tests/unit/suspend_thread_external.cpp, libs/core/resource_partitioner/tests/unit/suspend_thread_timed.cpp, libs/core/thread_pools/src/scheduled_thread_pool.cpp, libs/core/threading_base/tests/regressions/thread_stacksize_current.cpp, libs/core/threadmanager/src/threadmanager.cpp
Fixes atomics on some of the ARM machines (A64FX).
- Enable **cxx std atomic 128** bits (**HPX_HAVE_CXX11_STD_ATOMIC_128BIT**) only when **lockfree** in cmake cxx feature tests.
- Enable **work_requesting_lifo** scheduler only when 128 bit atomics are available. 
- Fallback to **HPX_LOCKFREE_PTR_COMPRESSION** when **HPX_HAVE_CXX11_STD_ATOMIC_128BIT** is not available. 
- Use cache alignment only on **std::atomic** of the tagged_index in freelist_stack.
=> Use compressed ptr in schedulers when 128 atomics are not lockfree

docs/sphinx/manual/using_the_lci_parcelport.rst, libs/full/parcelport_lci/CMakeLists.txt, libs/full/parcelport_lci/include/hpx/parcelport_lci/config.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/helper.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/parcelport_lci.hpp, libs/full/parcelport_lci/src/config.cpp, libs/full/parcelport_lci/src/putva/sender_connection_putva.cpp, libs/full/parcelport_lci/src/sender_connection_base.cpp, libs/full/parcelport_lci/src/sendrecv/sender_connection_sendrecv.cpp
In the LCI parcelport, there are several while (resource is available, retry) loops, i.e. the nonblocking send loop and the medium buffer allocation loop. In extreme cases, if all worker threads got into those retry loops and no threads are working on releasing the resource, HPX can get into deadlocks.
This PR lets those threads yield themselves after the max retry count (32).
Preliminary experiments show that the max retry count does not have visible performance effects on actually applications' performance (tried 1-256), so we just set it to 32 arbitrarily for now.
=> LCI parcelport: add yield to potentially inifinite retry loop

libs/core/concurrency/tests/unit/freelist.cpp
Reduce workload on `freelist` test, to prevent CircleCI test from timing out.
=> Reduce test workload to fix CI/CD time-out

libs/core/async_cuda/tests/performance/synchronize.cu, libs/core/async_cuda/tests/unit/transform_stream.cu, libs/core/execution/include/hpx/execution/algorithms/just.hpp
With CUDA 12.3 nvcc does not outright crash anymore when compiling sender-receiver code. 
Though, to make them compile, we still need to conditionally remove the noexcept with an IFDEF, which this PR adds.
Hence, we can activate the synchronize and the transform_stream tests when the CUDA version ist 12.3 and newer.
Fixes #5799
=> Fix nvcc crashes in transform_stream.cu and synchronize.cu

cmake/HPX_SetupLCI.cmake, docs/sphinx/manual/using_the_lci_parcelport.rst
The Github repo name of LCI has been changed from `uiuc-hpc/LC` to `uiuc-hpc/lci`. Although the old URL (github.com/uiuc-hpc/LC) is automatically redirected to the new URL, it would still be good to change the existing reference to the new URL.
This PR implemented the corresponding changes.
=> lci pp: lci's github repo name changed from LC to lci

components/parcel_plugins/binary_filter/bzip2/tests/CMakeLists.txt, components/parcel_plugins/binary_filter/bzip2/tests/regressions/CMakeLists.txt, components/parcel_plugins/binary_filter/bzip2/tests/unit/CMakeLists.txt, components/parcel_plugins/binary_filter/snappy/tests/CMakeLists.txt, components/parcel_plugins/binary_filter/snappy/tests/regressions/CMakeLists.txt, components/parcel_plugins/binary_filter/snappy/tests/unit/CMakeLists.txt, components/parcel_plugins/binary_filter/zlib/tests/CMakeLists.txt, components/parcel_plugins/binary_filter/zlib/tests/regressions/CMakeLists.txt, components/parcel_plugins/binary_filter/zlib/tests/unit/CMakeLists.txt
Not unique target names in the tests of binary_filter which leads to build errors when switching on the different filter at the same time, e.g. with
```
-DHPX_WITH_COMPRESSION_BZIP2=ON \
-DHPX_WITH_COMPRESSION_SNAPPY=ON \
-DHPX_WITH_COMPRESSION_ZLIB=ON \
-DHPX_WITH_TESTS=ON \
```
- unique target names for binary_filter tests
Replaced the non unique copy-paste name with the unique names of the different binary filter in the build config files.
=> Fixing binary filter test target names

libs/core/datastructures/include/hpx/datastructures/any.hpp, libs/core/datastructures/include/hpx/datastructures/serialization/serializable_any.hpp, libs/core/program_options/tests/unit/variable_map.cpp, libs/core/serialization/include/hpx/serialization/access.hpp, libs/full/collectives/tests/regressions/CMakeLists.txt, libs/full/collectives/tests/regressions/trivially_copyable_all_gather.cpp
This prevents instantiation errors in collective operations. This also makes hpx::any more conforming to std::any.
=> Remove equal_to from hpx::any

cmake/HPX_CompilerFlagsTargets.cmake, libs/core/schedulers/include/hpx/schedulers/local_priority_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/local_queue_scheduler.hpp, libs/core/schedulers/include/hpx/schedulers/local_workrequesting_scheduler.hpp, libs/core/serialization/include/hpx/serialization/access.hpp, libs/core/serialization/include/hpx/serialization/input_archive.hpp, libs/core/serialization/include/hpx/serialization/output_archive.hpp, libs/core/serialization/include/hpx/serialization/traits/brace_initializable_traits.hpp, libs/core/serialization/include/hpx/serialization/traits/is_bitwise_serializable.hpp, libs/core/serialization/tests/unit/serialization_raw_pointer.cpp, libs/full/collectives/tests/regressions/trivially_copyable_all_gather.cpp
- flyby: fix setting HPX_DEBUG on Windows platform
- flyby: protect against out-of-bounds access in schedulers during early parcel exceptions
=> Generalize the notion of bitwise serialization

CMakeLists.txt, cmake/CacheLineSize.cmake, cmake/HPX_AddModule.cmake, libs/core/concurrency/include/hpx/concurrency/cache_line_data.hpp, libs/core/config/cmake/templates/cache_line_size.hpp.in, libs/core/config/include/hpx/config.hpp
This ensures consistent cache line sizes for HPX and dependent projects, even if different compiler versions are used
=> Destructive interference size

libs/full/command_line_handling/src/command_line_handling.cpp
@Pansysk75 this should resolve the initialization issue discussed, could you check, please?
=> Ensure TCP parcelport is deactivated if not needed

libs/core/execution/include/hpx/execution/algorithms/detail/partial_algorithm.hpp, libs/core/execution/include/hpx/execution/algorithms/split.hpp
With CUDA 12.3 nvcc does not outright crash anymore when compiling sender-receiver code and with #6452 the HPX sender-receiver examples compile and work again with nvcc after fixing some compilation errors.
The last remaining problem related to this was to compile the Kokkos HPX execution space (using sender-receivers internally) with nvcc: Here we still got a few compilation problems such as:
- ``` member_pack.hpp(143): error: function returning function is not allowed ```
- ```split.hpp:289:38: error: use of deleted function ‘hpx::execution::experimental::detail::any_receiver<Ts>::any_receiver(const hpx::execution::experimental::detail::any_receiver<Ts>&) [with Ts = {}]’```
This PR addresses these issues!
By itself, this PR is not quite enough to make the HPX execution space compile …
=> Fix kokkos hpx nvcc compilation

libs/core/prefix/src/find_prefix.cpp
The std::vector object needs to have the element allocated in order to take its address.
=> Fix crash in get_executable_filename on FreeBSD

libs/core/algorithms/include/hpx/parallel/algorithms/uninitialized_relocate.hpp
Probably affects the docs generation in some way?
=> Fix typo: s/unititiallized/uninitialized/

cmake/HPX_SetupHwloc.cmake
Fixes a bug related to incorrect paths when automatically loading `hwloc`.
If the path for downloaded projects is `FETCHCONTENT_BASE_DIR`
has been changed, then the existing `cmake` script points to a non-existent folder, since `hwloc` will be loaded to another location.
=> custom FETCHCONTENT_BASE_DIR bug fix

.jenkins/lsu/env-clang-16.sh, .jenkins/lsu/env-gcc-12.sh, .jenkins/lsu/env-gcc-14.sh, libs/core/mpi_base/CMakeLists.txt, libs/core/mpi_base/include/hpx/mpi_base/mpi_environment.hpp, libs/core/mpi_base/src/mpi_environment.cpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/header.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/receiver.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/receiver_connection.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/sender.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/sender_connection.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/tag_provider.hpp, libs/full/parcelport_mpi/src/parcelport_mpi.cpp
- this prevents sends to be posted before their corresponding receives
- this option can be enabled by adding the command line argument `--hpx:ini=hpx.parcel.mpi.ack_handshake!=1`
=> Adding optional handshakes to acknowledge the received data

libs/full/collectives/include/hpx/collectives/all_to_all.hpp, libs/full/collectives/include/hpx/collectives/gather.hpp, libs/full/init_runtime/include/hpx/hpx_finalize.hpp
Fix incorrect signature of `collectives::all_to_all` and ` collectives::gather_there`.
Towards resolving https://github.com/STEllAR-GROUP/hpx/issues/6544
Also update `hpx::finalize` documentation.
=> Fix incorrect signature of distributed API functions

docs/sphinx/manual/launching_and_configuring_hpx_applications.rst, libs/core/errors/include/hpx/errors/exception.hpp, libs/core/errors/include/hpx/errors/throw_exception.hpp, libs/core/errors/src/exception.cpp, libs/core/errors/src/throw_exception.cpp, libs/core/format/include/hpx/modules/format.hpp, libs/core/format/src/format.cpp, libs/core/runtime_configuration/src/runtime_configuration.cpp, libs/core/runtime_local/src/runtime_local.cpp, libs/core/schedulers/include/hpx/schedulers/queue_holder_thread.hpp, libs/core/schedulers/include/hpx/schedulers/thread_queue.hpp, libs/core/threading_base/src/thread_helpers.cpp, libs/full/components_base/src/server/one_size_heap_list.cpp, libs/full/init_runtime/src/hpx_init.cpp
- flyby: don't register signal(SIGABRT, ...) if hpx.handle_signals == 0
Fixes #6542
=> Throwing an exception derived from std::bad_alloc on OOM conditions

docs/sphinx/index.rst, docs/sphinx/manual/migration_guide.rst
The title of our documentation is "Welcome to the HPX documentation!" which I feel like is a bit odd. 
This means that also when someone searches for the docs in google they see this title. Apart from being odd, if you use a device with smaller screen, the title doesn't fit and you only see "Welcome to the..." 
Our title could simply be "HPX documentation". The welcome message is moved to the beginning of the first paragraph.
=> Fix title and minor typos in documentation

.jenkins/lsu/env-clang-17.sh, .jenkins/lsu/env-gcc-13.sh, libs/core/algorithms/include/hpx/parallel/unseq/loop.hpp, libs/core/algorithms/include/hpx/parallel/unseq/reduce_helpers.hpp, libs/core/algorithms/include/hpx/parallel/unseq/transform_loop.hpp, libs/core/algorithms/include/hpx/parallel/util/loop.hpp
Fixes https://github.com/STEllAR-GROUP/hpx/issues/6552
=> Fix omp vectorization pragma errors

libs/full/collectives/include/hpx/collectives/broadcast_direct.hpp, libs/full/collectives/include/hpx/collectives/reduce_direct.hpp
Fixes NVCC compilation errors, fixes #6563
=> Remove superfluous HPX_MOVE()

.github/workflows/macos_debug_fetch_hwloc.yml, .github/workflows/windows_release_gcc_mingw.yml
Sourceforge has occasional problems, switching to native Boost download archives.
=> Download Boost from their own archives, not from Sourceforge

.circleci/config.yml, .circleci/conv.xsl
The Kitware team has recently removed their CircleCI support files from their repository (https://github.com/Kitware/CDash/pull/2570). This PR replaces the download of this file with a local version.
=> Replace previously downloaded CDash conv.xsl with local version

components/performance_counters/io/CMakeLists.txt, components/performance_counters/memory_counters/CMakeLists.txt, examples/jacobi_smp/CMakeLists.txt, libs/core/affinity/CMakeLists.txt, libs/core/batch_environments/CMakeLists.txt, libs/full/performance_counters/CMakeLists.txt
Fixes #6579
@phetdam would you be able to try this out?
=> Attempting to work around a Boost.Spirit problem

cmake/templates/conf.py.in
Fixes #
Added '\' to strings containing '\'. A single '\' results in taking the following char as an escape character.
Existing code results with the following warnings:
/home/shachar/OpenSource/hpx/build3/docs/sphinx/conf.py:75: SyntaxWarning: invalid escape sequence '\p'
if "/// \page" in line:
/home/shachar/OpenSource/hpx/build3/docs/sphinx/conf.py:76: SyntaxWarning: invalid escape sequence '\p'
title = line.split("/// \page", 1)[-1].strip()
/home/shachar/OpenSource/hpx/build3/docs/sphinx/conf.py:77: SyntaxWarning: invalid escape sequence '\h'
elif "/// \headerfile" in line:
/home/shachar/OpenSource/hpx/build3/docs/sphinx/conf.py:78: SyntaxWarning: invalid escape sequence '\h'
header = line.split("/// \headerfile", 1)[-1].strip()
Add '\' to single '\'
Not all points below apply to all …
=> Fixed escape characters format to handle warning due to misinterpretation of syntax

cmake/HPX_AddConfigTest.cmake, cmake/HPX_PerformCxxFeatureTests.cmake, cmake/tests/builtin_frame_address.cpp, libs/core/coroutines/include/hpx/coroutines/detail/get_stack_pointer.hpp
Add a feature test for `__builtin_frame_address`. Before, it was assumed that if the compiler `__GNUC__` then `__builtin_frame_address` is available: https://github.com/STEllAR-GROUP/hpx/blob/3c0ebc8a5f23b7c4f197fa1970c4560a61e16b34/libs/core/coroutines/include/hpx/coroutines/detail/get_stack_pointer.hpp#L33-L35
But this is not the case when building HPX with [Circle](https://www.circle-lang.org/site/index.html).
=> Feature test for __builtin_frame_address

libs/core/coroutines/include/hpx/coroutines/detail/get_stack_pointer.hpp
make HPX_HAVE_THREADS_GET_STACK_POINTER match the builtin_frame_address feature test
=> HPX_HAVE_THREADS_GET_STACK_POINTER to match builtin_frame_address feature test

CMakeLists.txt, libs/full/collectives/include/hpx/collectives/all_gather.hpp, libs/full/collectives/include/hpx/collectives/all_reduce.hpp, libs/full/collectives/include/hpx/collectives/all_to_all.hpp, libs/full/collectives/include/hpx/collectives/broadcast.hpp, libs/full/collectives/include/hpx/collectives/create_communicator.hpp, libs/full/collectives/include/hpx/collectives/exclusive_scan.hpp, libs/full/collectives/include/hpx/collectives/gather.hpp, libs/full/collectives/include/hpx/collectives/inclusive_scan.hpp, libs/full/collectives/include/hpx/collectives/reduce.hpp, libs/full/collectives/include/hpx/collectives/scatter.hpp, libs/full/collectives/src/create_communicator.cpp, libs/full/collectives/tests/unit/CMakeLists.txt, libs/full/collectives/tests/unit/all_gather_sync.cpp, libs/full/collectives/tests/unit/all_reduce_sync.cpp, libs/full/collectives/tests/unit/all_to_all_sync.cpp, libs/full/collectives/tests/unit/broadcast_sync.cpp, libs/full/collectives/tests/unit/exclusive_scan_sync.cpp, libs/full/collectives/tests/unit/gather_sync.cpp, libs/full/collectives/tests/unit/inclusive_scan_sync.cpp, libs/full/collectives/tests/unit/reduce_sync.cpp, libs/full/collectives/tests/unit/scatter_sync.cpp
- adding predefined world_comunicator
=> Adding synchronous collective operations

libs/core/coroutines/CMakeLists.txt, libs/core/coroutines/include/hpx/coroutines/detail/get_stack_pointer.hpp, libs/core/coroutines/src/detail/get_stack_pointer.cpp
`get_stack_ptr()` is moved to a source file so it still works when there is a mismatch in the features of the compiler building HPX and the compiler building the HPX headers along with the application that uses them.
=> Move get_stack_ptr to source 

CMakeLists.txt, docs/sphinx/releases/whats_new_1_11_0.rst, libs/core/functional/include/hpx/functional/detail/basic_function.hpp, libs/full/command_line_handling/src/command_line_handling.cpp, libs/full/init_runtime/include/hpx/hpx_init.hpp, libs/full/init_runtime/include/hpx/hpx_init_impl.hpp, libs/full/init_runtime/include/hpx/hpx_init_params.hpp, libs/full/init_runtime/include/hpx/hpx_start.hpp, libs/full/init_runtime/include/hpx/hpx_start_impl.hpp, libs/full/init_runtime/include/hpx/hpx_user_main_config.hpp, libs/full/init_runtime/src/hpx_init.cpp, wrap/CMakeLists.txt, wrap/include/hpx/hpx_main.hpp, wrap/src/hpx_main.cpp
The CMake option `HPX_WITH_RUN_MAIN_EVERYWHERE` is now deprecated.
=> Make HPX_HAVE_RUN_MAIN_EVERYWHERE application specific

.github/workflows/tests.examples.targets, libs/core/runtime_configuration/include/hpx/runtime_configuration/runtime_mode.hpp, libs/core/runtime_configuration/src/runtime_mode.cpp, libs/full/collectives/examples/CMakeLists.txt, libs/full/collectives/examples/distributed_pi.cpp, libs/full/collectives/include/hpx/collectives/broadcast.hpp, libs/full/collectives/include/hpx/collectives/channel_communicator.hpp, libs/full/collectives/include/hpx/collectives/create_communicator.hpp, libs/full/collectives/include/hpx/collectives/detail/channel_communicator.hpp, libs/full/collectives/include/hpx/collectives/reduce.hpp, libs/full/collectives/src/channel_communicator.cpp, libs/full/collectives/src/create_communicator.cpp, libs/full/collectives/src/detail/channel_communicator_server.cpp, libs/full/include/include/hpx/hpx.hpp, libs/full/init_runtime/src/pre_main.cpp, wrap/src/hpx_main.cpp
- adding example
- adding sync overloads for set/get
- adding predefined channel communicator
=> Fixing sync collectives

CMakeLists.txt, libs/core/mpi_base/include/hpx/mpi_base/mpi_environment.hpp, libs/core/mpi_base/src/mpi_environment.cpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/header.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/putva/receiver_putva.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/sendrecv/receiver_connection_sendrecv.hpp, libs/full/parcelport_lci/include/hpx/parcelport_lci/sendrecv/sender_connection_sendrecv.hpp, libs/full/parcelport_lci/src/putva/sender_connection_putva.cpp, libs/full/parcelport_lci/src/sendrecv/receiver_connection_sendrecv.cpp, libs/full/parcelport_lci/src/sendrecv/sender_connection_sendrecv.cpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/receiver_connection.hpp, libs/full/parcelport_mpi/include/hpx/parcelport_mpi/sender_connection.hpp, libs/full/parcelset/tests/regressions/CMakeLists.txt, libs/full/parcelset/tests/regressions/very_big_parcel.cpp
Following #6566. Make a new PR to avoid delaying the merge of the first one.
The basic idea is to create a very large data type to encapsulate the messages larger than INT_MAX.
=> mpi pp: fix messages larger than INT_MAX

libs/full/components_base/include/hpx/components_base/server/component_base.hpp
=> Making sure copy_component creates a new gid

.github/workflows/macos_debug_fetch_hwloc.yml, cmake/HPX_SetupHwloc.cmake
Fixes #
- MacOS CI currently fails at HWLoc build step in the cmake configuration
=> Remove unnecessary autoreconf

.github/workflows/macos_debug_fetch_boost.yml, .github/workflows/windows_clang_debug.yml, .github/workflows/windows_clang_release.yml, .github/workflows/windows_debug_vs2019.yml, .github/workflows/windows_debug_vs2022.yml, .github/workflows/windows_debug_vs2022_fetch_boost.yml, .github/workflows/windows_debug_vs2022_fetch_hwloc.yml, .github/workflows/windows_release_2019.yml, .github/workflows/windows_release_2022.yml, .github/workflows/windows_release_static.yml, CMakeLists.txt, cmake/HPX_GeneratePackage.cmake, cmake/HPX_GeneratePackageUtils.cmake, cmake/HPX_SetupBoost.cmake, cmake/HPX_SetupBoostFilesystem.cmake, cmake/HPX_SetupBoostIostreams.cmake, cmake/HPX_SetupBoostRegex.cmake, cmake/templates/HPXConfig.cmake.in, cmake/templates/HPXMacros.cmake.in
Draft PR for properly fetching and installing boost as a CMake subproject.
Still needs fixes, but I paused working on it since we need https://github.com/boostorg/cmake/pull/65 to move forward with this approach.
Can also move to using `find_package` Config mode, since Module mode (using `Find<PackageName>.cmake`) is being deprecated for Boost.
=> Include Boost as CMake subproject

libs/core/algorithms/include/hpx/parallel/datapar/iterator_helpers.hpp, libs/core/algorithms/include/hpx/parallel/datapar/loop.hpp, libs/core/algorithms/tests/unit/datapar_algorithms/CMakeLists.txt, libs/core/algorithms/tests/unit/datapar_algorithms/for_loop_datapar.cpp, libs/core/execution/include/hpx/execution/traits/detail/eve/vector_pack_get_set.hpp, libs/core/execution/include/hpx/execution/traits/detail/simd/vector_pack_get_set.hpp, libs/core/execution/include/hpx/execution/traits/detail/vc/vector_pack_get_set.hpp, libs/core/execution/include/hpx/execution/traits/vector_pack_alignment_size.hpp, libs/core/mpi_base/include/hpx/mpi_base/mpi_environment.hpp, libs/core/mpi_base/src/mpi_environment.cpp, libs/full/performance_counters/include/hpx/performance_counters/query_counters.hpp
This adds support for using the simd execution policies with `hpx::experimental::for_loop`. The support is restricted to using `for_loop` with integral loop boundaries. Using reduction/induction objects in this case will fall back to non-simd execution..
=> Partially support data parallel for_loop

CMakeLists.txt, cmake/HPX_FindHwloc.cmake, cmake/HPX_SetupHwloc.cmake, cmake/templates/HPXConfig.cmake.in
Fixes HWLOC FETCH CONTENT
- installs **HWLOC** into `CMAKE_INSTALL_PREFIX/hwloc_installed`
- uses `find_package` to find hwloc in all scenarios
=> Fix Hwloc fetch content

.github/workflows/macos_debug_fetch_hwloc.yml
MacOS CI fails because it cannot find aclocal-1.16 for hwloc
=> Link aclocal with aclocal-1.16 as hwloc asks for it

cmake/tests/cpuid.cpp
`cmake/tests/cpuid.cpp` uses `uint32_t` but does not include the appropriate header which defines the type.
The test hence, fails to compile.
[Godbolt link](https://godbolt.org/z/oPbfPzona)
- include `cstdint`
=> Fix CPUId test

libs/full/collectives/include/hpx/collectives/exclusive_scan.hpp, libs/full/collectives/src/exclusive_scan.cpp, libs/full/collectives/tests/regressions/CMakeLists.txt, libs/full/collectives/tests/regressions/collectives_bool_5940.cpp, libs/full/collectives/tests/regressions/exclusive_scan_6636.cpp, libs/full/collectives/tests/unit/concurrent_collectives.cpp, libs/full/collectives/tests/unit/exclusive_scan_.cpp, libs/full/collectives/tests/unit/exclusive_scan_sync.cpp
- adding exclusive_scan overloads that take an initial value for the scan operation
Fixes #6636
=> Fixing collectives::exclusive_scan

libs/core/algorithms/CMakeLists.txt, libs/core/algorithms/include/hpx/parallel/run_on_all.hpp, libs/core/algorithms/tests/unit/block/CMakeLists.txt, libs/core/algorithms/tests/unit/block/run_on_all.cpp, libs/core/include_local/CMakeLists.txt, libs/core/include_local/include/hpx/experimental/run_on_all.hpp
Working towards resolving #6651
This is a first minimal implementation, no execution policy, no asynchrony, etc.
=> Adding simple experimental::run_on_all

cmake/templates/HPXConfig.cmake.in
`HPX_CONFIG_IS_INSTALL` needs to be replaced when this file is configured:
https://github.com/STEllAR-GROUP/hpx/blob/735086d7122f45e88a8d46c73438fbf54d8b7572/cmake/HPX_GeneratePackage.cmake#L63-L93
=> Fix CMake template when fetching Boost

libs/core/algorithms/include/hpx/parallel/algorithms/for_loop.hpp
Fixes following warning on MSVC:
```
C:\Users\psyskakis\source\repos\STEllAR-GROUP\hpx\libs\core\algorithms\include\hpx\parallel\algorithms\for_loop.hpp(984): warning C4146: unary minus operator applied to unsigned type, result still unsigned
C:\Users\psyskakis\source\repos\STEllAR-GROUP\hpx\libs\core\algorithms\include\hpx\parallel\algorithms\for_loop.hpp(984): note: the template instantiation context (the oldest one first) is
C:\Users\psyskakis\source\repos\STEllAR-GROUP\hpx\examples\transpose\transpose_smp.cpp(80): note: see reference to function template instantiation 'void hpx::functional::detail::tag_base_ns::tag_fallback<Tag,hpx::meta::constant<std::integral_constant<bool,true>>>::operator ()<const hpx::execution::parallel_policy&,const …
```
=> Fix "unary minus operator applied to unsigned type" warning

cmake/FindTBB.cmake
Fixes#
- This PR fixes issue #6504 related to TBB detection during CMake configuration.
- Fixed `FindTBB.cmake` parsing issue that prevented CMake from locating the correct TBB library.
- Ensured proper detection of `TBB_LIBRARY` and `TBB_INCLUDE_DIR`.
- Verified successful configuration and build with TBB examples enabled.
This PR resolves issue #6504. While attempting to build HPX with TBB support (`HPX_WITH_EXAMPLES_TBB=ON`), CMake was failing to properly detect the TBB library due to a malformed or incorrect script in `FindTBB.cmake`. This caused users to be unable to compile with TBB-related examples or modules.
After fixing the CMake script, HPX now configures and compiles successfully with TBB enabled.
=> Fix: FindTBB.cmake cannot find correct TBB library. #6504

libs/core/async_sycl/include/hpx/async_sycl/sycl_executor.hpp, libs/core/async_sycl/tests/unit/sycl_stream.cpp
Our HPX-SYCL was originally written to support both hipSYCL and oneAPI. It allows passing a SYCL executor (containing a SYCL queue), a SYCL queue member function, and its parameters to hpx::async. The correct overload of the queue member function would be determined based on the passed parameters, the member function would then be launched asynchronously on the executor queue, and we would get an HPX future back.
However, oneAPI is using an additional (afaik non-standard) ```code_location``` parameter for many of its SYCL queue member functions. Usually, a SYCL user/developer would not notice this because the ```code_location``` has a default value. In our case, however, it is problematic as it messes with choosing the correct  function overloads when passing the calls to ```hpx::apply``` …
=> Fix oneapi overloads

components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_component_impl.hpp, components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_decl.hpp, components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_impl.hpp, components/containers/partitioned_vector/include/hpx/components/containers/partitioned_vector/partitioned_vector_predef.hpp, components/containers/partitioned_vector/src/partitioned_vector_component_double.cpp, components/containers/partitioned_vector/src/partitioned_vector_component_int.cpp, components/containers/partitioned_vector/src/partitioned_vector_component_std_string.cpp, components/containers/partitioned_vector/tests/regressions/CMakeLists.txt, components/containers/partitioned_vector/tests/regressions/partitioned_vector_constructor_6650.cpp, libs/full/segmented_algorithms/tests/unit/partitioned_vector_copy.cpp
- These allow to initialize the new instance with a given range of data
=> Adding constructor overloads to partitioned_vector

libs/core/algorithms/include/hpx/parallel/algorithms/set_union.hpp
Fixes #6631
1.Fixed the result_type in set_union.hpp as mentioned in issue 6631
2.Changed the 2nd parameter which was  FwdIter3 to  FwdIter2 as it was getting repeated, might be a type-error!
=> Update result_type in set_union.hpp

libs/core/execution/include/hpx/execution/algorithms/when_all_vector.hpp, libs/core/execution_base/include/hpx/execution_base/stdexec_forward.hpp
This updates `when_all_vector` to include the concept tags for operation state, and also adds the forwarding of the operation_state_t itsself. 
There will be a separate PR to address the partial or complete replacement of tag_invoke friends with member functions.
=> When_all_vector update

docs/sphinx/manual/creating_hpx_projects.rst, libs/CMakeLists.txt
- This is necessary to successfully use hpx::runtime_manager in shared libraries and similar
@SAtacker Would you mind verifying if this solves the issue you reported?
=> Expose an explicit CMake target HPX::init to be used by non-executables
